--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['town']['home_furniture_type'] = {
	[1] = {
		id = 1,
		name = '地面'
	},
	[2] = {
		id = 2,
		name = '墙面'
	},
	[3] = {
		id = 3,
		name = '家私'
	},
	[4] = {
		id = 4,
		name = '室外'
	},
	[5] = {
		id = 5,
		name = '样板间',
		homeLevel = 5
	},
	[101] = {
		id = 101,
		showType = 1,
		frontType = 21,
		name = '地板'
	},
	[102] = {
		id = 102,
		showType = 1,
		frontType = 23,
		name = '地毯'
	},
	[201] = {
		id = 201,
		showType = 2,
		frontType = 22,
		name = '墙纸'
	},
	[202] = {
		id = 202,
		showType = 2,
		frontType = 25,
		name = '功能设施'
	},
	[203] = {
		id = 203,
		showType = 2,
		frontType = 25,
		name = '门窗'
	},
	[204] = {
		id = 204,
		showType = 2,
		frontType = 25,
		name = '艺术'
	},
	[301] = {
		id = 301,
		showType = 3,
		frontType = 24,
		name = '桌子'
	},
	[302] = {
		id = 302,
		showType = 3,
		frontType = 24,
		name = '椅子'
	},
	[303] = {
		id = 303,
		showType = 3,
		frontType = 24,
		name = '居家'
	},
	[304] = {
		id = 304,
		showType = 3,
		frontType = 24,
		name = '收纳'
	},
	[305] = {
		id = 305,
		showType = 3,
		frontType = 24,
		name = '厨卫'
	},
	[306] = {
		id = 306,
		showType = 3,
		frontType = 24,
		name = '摆设'
	},
	[307] = {
		id = 307,
		showType = 3,
		frontType = 24,
		name = '其他'
	},
	[401] = {
		id = 401,
		showType = 4,
		frontType = 26,
		name = '院落'
	},
	[501] = {
		id = 501,
		showType = 5,
		frontType = 29,
		name = '墙壁'
	},
	[502] = {
		id = 502,
		showType = 5,
		frontType = 30,
		name = '地面'
	},
	[503] = {
		id = 503,
		showType = 5,
		frontType = 31,
		name = '院落'
	},
	__size = 22,
	__default = {
		__index = {
			showType = 0,
			frontType = 0,
			name = '',
			homeLevel = 0
		}
	}
}
return csv.town.home_furniture_type