slot0 = {
	__size = 18,
	[3] = {
		1
	},
	[4] = {
		__size = 1,
		[453.0] = 50
	},
	[5] = {
		0.05,
		0.1,
		0.15,
		0.2,
		0.25
	},
	[7] = {
		2,
		4,
		6,
		8,
		10
	},
	[8] = {
		__size = 1,
		[453.0] = 30
	},
	[9] = {
		0.03,
		0.06,
		0.09,
		0.12,
		0.15
	},
	[10] = {
		__size = 1,
		[453.0] = 35
	},
	[11] = {
		__size = 1,
		[453.0] = 60
	},
	[12] = {
		3,
		6,
		9,
		12,
		15
	},
	[13] = {
		__size = 1,
		[453.0] = 40
	},
	[14] = {
		0.01,
		0.02,
		0.03,
		0.04,
		0.05
	},
	[15] = {
		__size = 1,
		[453.0] = 45
	},
	[16] = {
		0.02,
		0.04,
		0.06,
		0.08,
		0.1
	},
	[17] = {
		__size = 1,
		[453.0] = 100
	},
	[18] = {
		__size = 1,
		[453.0] = 75
	},
	[20] = {
		0.05,
		0.1,
		0.15,
		0.2,
		0.25,
		0.3,
		0.35,
		0.4,
		0.45,
		0.5
	},
	[21] = {
		__size = 1,
		[453.0] = 70
	},
	[23] = {
		0.01,
		0.02,
		0.03,
		0.04,
		0.05,
		0.06,
		0.07,
		0.08,
		0.09,
		0.1
	}
}
slot1 = {
	slot0[3],
	slot0[5],
	[24] = slot0[5],
	[25] = slot0[3],
	[26] = slot0[7],
	[27] = slot0[14],
	[20] = slot0[5],
	[21] = slot0[14],
	[22] = slot0[7],
	[23] = slot0[14],
	[28] = slot0[14],
	[29] = slot0[20],
	[40] = slot0[23],
	[41] = slot0[14],
	[3] = slot0[7],
	[5] = slot0[7],
	[4] = slot0[9],
	[7] = slot0[3],
	[6] = slot0[5],
	[9] = slot0[9],
	[8] = slot0[12],
	[39] = slot0[23],
	[38] = slot0[7],
	[11] = slot0[7],
	[10] = slot0[14],
	[13] = slot0[16],
	[12] = slot0[14],
	[15] = slot0[3],
	[14] = slot0[7],
	[17] = slot0[14],
	[16] = slot0[14],
	[19] = slot0[16],
	[18] = slot0[12],
	[31] = slot0[14],
	[30] = slot0[12],
	[37] = slot0[20],
	[36] = slot0[9],
	[35] = slot0[14],
	[34] = slot0[7],
	[32] = slot0[14]
}
slot2 = {
	slot0[4],
	[24] = slot0[18],
	[26] = slot0[18],
	[27] = slot0[11],
	[20] = slot0[11],
	[21] = slot0[11],
	[22] = slot0[11],
	[23] = slot0[11],
	[28] = slot0[11],
	[29] = slot0[11],
	[40] = slot0[17],
	[41] = slot0[18],
	[3] = slot0[8],
	[5] = slot0[10],
	[4] = slot0[8],
	[7] = slot0[11],
	[6] = slot0[10],
	[9] = slot0[13],
	[8] = slot0[13],
	[39] = slot0[18],
	[38] = slot0[18],
	[11] = slot0[15],
	[10] = slot0[15],
	[13] = slot0[4],
	[12] = slot0[15],
	[15] = slot0[17],
	[14] = slot0[4],
	[17] = slot0[4],
	[16] = slot0[4],
	[19] = slot0[11],
	[18] = slot0[4],
	[31] = slot0[17],
	[30] = slot0[18],
	[37] = slot0[18],
	[36] = slot0[18],
	[35] = slot0[17],
	[34] = slot0[18],
	[33] = slot0[21],
	[32] = slot0[21]
}
csv.trainer.skills = {
	{
		type = 12,
		name = "Finance Novice",
		desc1 = "Treasure Pot",
		name_en = "Finance Novice",
		desc2_en = "Free daily chances +%d",
		desc2_vn = "Chances diárias grátis +%d",
		desc2_kr = "매일 무료 횟수+%d",
		desc2 = "Free daily chances +%d",
		desc1_vn = "Pote do Tesouro",
		icon = "city/develop/train/icon_jbfbzj.png",
		desc1_en = "Treasure Pot",
		desc2_pt = "Chances diárias grátis +%d",
		name_pt = "Iniciante em Finanças",
		desc1_pt = "Pote do Tesouro",
		name_vn = "Iniciante em Finanças",
		id = 1,
		levelMax = 1,
		nums = slot1[1],
		upCost = slot2[1]
	},
	{
		type = 18,
		name = "Exploration Will",
		desc1 = "Story dungeon",
		name_en = "Exploration Will",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de história",
		icon = "city/develop/train/icon_ptfbzj.png",
		desc1_en = "Story dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Testamento de ExploraçãoTestamento de Exploração",
		desc1_pt = "Masmorra de história",
		name_vn = "Testamento de ExploraçãoTestamento de Exploração",
		id = 2,
		levelMax = 5,
		nums = slot1[2],
		upCost = {
			__size = 1,
			[453.0] = 20
		}
	},
	{
		type = 14,
		name_en = "Full Lobster",
		desc1 = "Dinner",
		name = "Full Lobster",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Jantar",
		icon = "city/develop/train/icon_tllq.png",
		arg = 3,
		desc1_en = "Dinner",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Lagosta Cheia",
		desc1_pt = "Jantar",
		name_vn = "Lagosta Cheia",
		id = 3,
		levelMax = 5,
		nums = slot1[3],
		upCost = slot2[3]
	},
	{
		type = 13,
		name = "Financial Consultant",
		desc1 = "Treasure Pot",
		name_en = "Financial Consultant",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Pote do Tesouro",
		icon = "city/develop/train/icon_jbfbzj.png",
		desc1_en = "Treasure Pot",
		desc2_pt = "Moedas +%d",
		name_pt = "Consultor financeiro",
		desc1_pt = "Pote do Tesouro",
		name_vn = "Consultor financeiro",
		id = 4,
		levelMax = 5,
		nums = slot1[4],
		upCost = slot2[4]
	},
	{
		type = 14,
		name_en = "Exquisite Food",
		desc1 = "Lunch",
		name = "Exquisite Food",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Almoço",
		icon = "city/develop/train/icon_tllq.png",
		arg = 2,
		desc1_en = "Lunch",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Comida requintada",
		desc1_pt = "Almoço",
		name_vn = "Comida requintada",
		id = 5,
		levelMax = 5,
		nums = slot1[5],
		upCost = slot2[5]
	},
	{
		type = 19,
		name = "Elite member",
		desc1 = "Elite Dungeon",
		name_en = "Elite member",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de Elite",
		icon = "city/develop/train/icon_jyfbzj.png",
		desc1_en = "Elite Dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Sócio Elite",
		desc1_pt = "Masmorra de Elite",
		name_vn = "Sócio Elite",
		id = 6,
		levelMax = 5,
		nums = slot1[6],
		upCost = slot2[6]
	},
	{
		type = 11,
		name = "Magical Hands",
		desc1 = "Coin Card Draw",
		name_en = "Magical Hands",
		desc2_en = "Free daily chances +%d",
		desc2_vn = "Chances diárias grátis +%d",
		desc2_kr = "매일 무료 횟수+%d",
		desc2 = "Free daily chances +%d",
		desc1_vn = "Sorteio de cartão de moedas",
		icon = "city/develop/train/icon_ck.png",
		desc1_en = "Coin Card Draw",
		desc2_pt = "Chances diárias grátis +%d",
		name_pt = "Mãos mágicas",
		desc1_pt = "Sorteio de cartão de moedas",
		name_vn = "Mãos mágicas",
		id = 7,
		levelMax = 1,
		nums = slot1[7],
		upCost = slot2[7]
	},
	{
		type = 2,
		name = "Recover some HP",
		desc1 = "Maximum energy",
		name_en = "Recover some HP",
		desc2_en = "Increases +%d",
		desc2_vn = "Aumentos +%d",
		desc2_kr = "증가+%d",
		desc2 = "Increases +%d",
		desc1_vn = "Energia máxima",
		icon = "city/develop/train/icon_qfqn.png",
		desc1_en = "Maximum energy",
		desc2_pt = "Aumentos +%d",
		name_pt = "Recupere um pouco de HP",
		desc1_pt = "Energia máxima",
		name_vn = "Recupere um pouco de HP",
		id = 8,
		levelMax = 5,
		nums = slot1[8],
		upCost = slot2[8]
	},
	{
		type = 13,
		name = "Finance Expert",
		desc1 = "Treasure Pot",
		name_en = "Finance Expert",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Pote do Tesouro",
		icon = "city/develop/train/icon_jbfbzj.png",
		desc1_en = "Treasure Pot",
		desc2_pt = "Moedas +%d",
		name_pt = "Especialista em Finanças",
		desc1_pt = "Pote do Tesouro",
		name_vn = "Especialista em Finanças",
		id = 9,
		levelMax = 5,
		nums = slot1[9],
		upCost = slot2[9]
	},
	{
		type = 15,
		name = "Explorer Member",
		desc1 = "Coin dungeon",
		name_en = "Explorer Member",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de moedas",
		icon = "city/develop/train/icon_ptfbzj.png",
		desc1_en = "Coin dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Membro Explorador",
		desc1_pt = "Masmorra de moedas",
		name_vn = "Membro Explorador",
		id = 10,
		levelMax = 5,
		nums = slot1[10],
		upCost = slot2[10]
	},
	{
		type = 14,
		name_en = "Hearty breakfast",
		desc1 = "Breakfast",
		name = "Hearty breakfast",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Café da manhã",
		icon = "city/develop/train/icon_tllq.png",
		arg = 1,
		desc1_en = "Breakfast",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Café da manhã farto",
		desc1_pt = "Café da manhã",
		name_vn = "Café da manhã farto",
		id = 11,
		levelMax = 5,
		nums = slot1[11],
		upCost = slot2[11]
	},
	{
		type = 16,
		name = "Dungeon Expert",
		desc1 = "EXP Dungeon",
		name_en = "Dungeon Expert",
		desc2_en = "EXP +%d",
		desc2_vn = "EXP +%d",
		desc2_kr = "경험치 획득+%d",
		desc2 = "EXP +%d",
		desc1_vn = "EXP Masmorra",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "EXP Dungeon",
		desc2_pt = "EXP +%d",
		name_pt = "Especialista em Masmorras",
		desc1_pt = "EXP Masmorra",
		name_vn = "Especialista em Masmorras",
		id = 12,
		levelMax = 5,
		nums = slot1[12],
		upCost = slot2[12]
	},
	{
		type = 9,
		name = "Distributor",
		desc1 = "EXP Potion Purchase",
		name_en = "Distributor",
		desc2_en = "%d Discount",
		desc2_vn = "%d Desconto",
		desc2_kr = "가격 할인+%d",
		desc2 = "%d Discount",
		desc1_vn = "Compra de poções EXP",
		icon = "city/develop/train/icon_jb2.png",
		desc1_en = "EXP Potion Purchase",
		desc2_pt = "%d Desconto",
		name_pt = "Distribuidor",
		desc1_pt = "Compra de poções EXP",
		name_vn = "Distribuidor",
		id = 13,
		levelMax = 5,
		nums = slot1[13],
		upCost = slot2[13]
	},
	{
		type = 14,
		name_en = "Go for some skewers",
		desc1 = "Supper",
		name = "Go for some skewers",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Jantar",
		icon = "city/develop/train/icon_tllq.png",
		arg = 4,
		desc1_en = "Supper",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Vá para alguns espetos",
		desc1_pt = "Jantar",
		name_vn = "Vá para alguns espetos",
		id = 14,
		levelMax = 5,
		nums = slot1[14],
		upCost = slot2[14]
	},
	{
		type = 12,
		name = "Still insufficient!",
		desc1 = "Treasure Pot",
		name_en = "Still insufficient!",
		desc2_en = "Free daily chances +%d",
		desc2_vn = "Chances diárias grátis +%d",
		desc2_kr = "매일 무료 횟수+%d",
		desc2 = "Free daily chances +%d",
		desc1_vn = "Pote do Tesouro",
		icon = "city/develop/train/icon_djss.png",
		desc1_en = "Treasure Pot",
		desc2_pt = "Chances diárias grátis +%d",
		name_pt = "Ainda insuficiente!",
		desc1_pt = "Pote do Tesouro",
		name_vn = "Ainda insuficiente!",
		id = 15,
		levelMax = 1,
		nums = slot1[15],
		upCost = slot2[15]
	},
	{
		type = 26,
		name = "Training Master",
		desc1 = "Shard Dungeon",
		name_en = "Training Master",
		desc2_en = "Production +%d",
		desc2_vn = "Produção +%d",
		desc2_kr = "생산 증가+%d",
		desc2 = "Production +%d",
		desc1_vn = "Calabouço de Estilhaços",
		icon = "city/develop/train/icon_jb1.png",
		desc1_en = "Shard Dungeon",
		desc2_pt = "Produção +%d",
		name_pt = "Mestre de treinamento",
		desc1_pt = "Calabouço de Estilhaços",
		name_vn = "Mestre de treinamento",
		id = 16,
		levelMax = 5,
		nums = slot1[16],
		upCost = slot2[16]
	},
	{
		type = 17,
		name = "For others for self",
		desc1 = "union donation",
		name_en = "For others for self",
		desc2_en = "Union coins earned +%d",
		desc2_vn = "Moedas da União ganhadas +%d",
		desc2_kr = "길드 코인 획득량+%d",
		desc2 = "Union coins earned +%d",
		desc1_vn = "Doação Sindical",
		icon = "city/develop/train/icon_ghjz.png",
		desc1_en = "union donation",
		desc2_pt = "Moedas da União ganhadas +%d",
		name_pt = "Para os outros para si",
		desc1_pt = "Doação Sindical",
		name_vn = "Para os outros para si",
		id = 17,
		levelMax = 5,
		nums = slot1[17],
		upCost = slot2[17]
	},
	{
		type = 2,
		name = "Pokémon Gift",
		desc1 = "Maximum energy",
		name_en = "Pokémon Gift",
		desc2_en = "Increases +%d",
		desc2_vn = "Aumentos +%d",
		desc2_kr = "증가+%d",
		desc2 = "Increases +%d",
		desc1_vn = "Energia máxima",
		icon = "city/develop/train/icon_ghjz.png",
		desc1_en = "Maximum energy",
		desc2_pt = "Aumentos +%d",
		name_pt = "Presente Pokémon",
		desc1_pt = "Energia máxima",
		name_vn = "Presente Pokémon",
		id = 18,
		levelMax = 5,
		nums = slot1[18],
		upCost = slot2[18]
	},
	{
		type = 9,
		name = "Finance Master",
		desc1 = "EXP Potion Purchase",
		name_en = "Finance Master",
		desc2_en = "%d Discount",
		desc2_vn = "%d Desconto",
		desc2_kr = "가격 할인+%d",
		desc2 = "%d Discount",
		desc1_vn = "Compra de poções EXP",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "EXP Potion Purchase",
		desc2_pt = "%d Desconto",
		name_pt = "Mestre de Finanças",
		desc1_pt = "Compra de poções EXP",
		name_vn = "Mestre de Finanças",
		id = 19,
		levelMax = 5,
		nums = slot1[19],
		upCost = slot2[19]
	},
	{
		type = 18,
		name = "Go courageously",
		desc1 = "Story dungeon",
		name_en = "Go courageously",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de história",
		icon = "city/develop/train/icon_ptfbzj.png",
		desc1_en = "Story dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Vá corajosamente",
		desc1_pt = "Masmorra de história",
		name_vn = "Vá corajosamente",
		id = 20,
		levelMax = 5,
		nums = slot1[20],
		upCost = slot2[20]
	},
	{
		type = 24,
		name = "Santa Claus",
		desc1 = "Gift Dungeon",
		name_en = "Santa Claus",
		desc2_en = "Production +%d",
		desc2_vn = "Produção +%d",
		desc2_kr = "생산 증가+%d",
		desc2 = "Production +%d",
		desc1_vn = "Masmorra de Presentes",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "Gift Dungeon",
		desc2_pt = "Produção +%d",
		name_pt = "Papai Noel",
		desc1_pt = "Masmorra de Presentes",
		name_vn = "Papai Noel",
		id = 21,
		levelMax = 5,
		nums = slot1[21],
		upCost = slot2[21]
	},
	{
		type = 14,
		name_en = "Foodie",
		desc1 = "Dinner",
		name = "Foodie",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Jantar",
		icon = "city/develop/train/icon_tllq.png",
		arg = 3,
		desc1_en = "Dinner",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Viciado em comida",
		desc1_pt = "Jantar",
		name_vn = "Viciado em comida",
		id = 22,
		levelMax = 5,
		nums = slot1[22],
		upCost = slot2[22]
	},
	{
		type = 6,
		name = "Skilled",
		desc1 = "Daily quest",
		name_en = "Skilled",
		desc2_en = "Get extra EXP +%d",
		desc2_vn = "Obter EXP extra +%d",
		desc2_kr = "추가 경험치 증가+%d",
		desc2 = "Get extra EXP +%d",
		desc1_vn = "Missão diária",
		icon = "city/develop/train/icon_qfqn.png",
		desc1_en = "Daily quest",
		desc2_pt = "Obter EXP extra +%d",
		name_pt = "Especializado",
		desc1_pt = "Missão diária",
		name_vn = "Especializado",
		id = 23,
		levelMax = 5,
		nums = slot1[23],
		upCost = slot2[23]
	},
	{
		type = 19,
		name = "Sincerely",
		desc1 = "Elite Dungeon",
		name_en = "Sincerely",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de Elite",
		icon = "city/develop/train/icon_jyfbzj.png",
		desc1_en = "Elite Dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Sinceramente",
		desc1_pt = "Masmorra de Elite",
		name_vn = "Sinceramente",
		id = 24,
		levelMax = 5,
		nums = slot1[24],
		upCost = slot2[24]
	},
	{
		type = 22,
		name = "Supreme Black Card",
		desc1 = "Dispatch quest",
		name_en = "Supreme Black Card",
		desc2_en = "Free refresh chances+%d",
		desc2_vn = "Chances de atualização gratuitas+%d Chances de atualização gratuitas+%d",
		desc2_kr = "무료 새로고침 횟수+%d",
		desc2 = "Free refresh chances+%d",
		desc1_vn = "Despachar missão",
		icon = "city/develop/train/icon_ck.png",
		desc1_en = "Dispatch quest",
		desc2_pt = "Chances de atualização gratuitas+%d Chances de atualização gratuitas+%d",
		name_pt = "Cartão Preto Supremo",
		desc1_pt = "Despachar missão",
		name_vn = "Cartão Preto Supremo",
		id = 25,
		levelMax = 1,
		nums = slot1[25],
		upCost = {
			__size = 1,
			[453.0] = 150
		}
	},
	{
		type = 14,
		name_en = "Deluxe Lunch",
		desc1 = "Lunch",
		name = "Deluxe Lunch",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Almoço",
		icon = "city/develop/train/icon_tllq.png",
		arg = 2,
		desc1_en = "Lunch",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Almoço Deluxe",
		desc1_pt = "Almoço",
		name_vn = "Almoço Deluxe",
		id = 26,
		levelMax = 5,
		nums = slot1[26],
		upCost = slot2[26]
	},
	{
		type = 15,
		name = "Exploration Expert",
		desc1 = "Coin dungeon",
		name_en = "Exploration Expert",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de moedas",
		icon = "city/develop/train/icon_ptfbzj.png",
		desc1_en = "Coin dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Especialista em Exploração",
		desc1_pt = "Masmorra de moedas",
		name_vn = "Especialista em Exploração",
		id = 27,
		levelMax = 5,
		nums = slot1[27],
		upCost = slot2[27]
	},
	{
		type = 17,
		name = "Elite Core Member",
		desc1 = "union donation",
		name_en = "Elite Core Member",
		desc2_en = "Union coins earned +%d",
		desc2_vn = "Moedas da União ganhadas +%d",
		desc2_kr = "길드 코인 획득량+%d",
		desc2 = "Union coins earned +%d",
		desc1_vn = "Doação Sindical",
		icon = "city/develop/train/icon_ghjz.png",
		desc1_en = "union donation",
		desc2_pt = "Moedas da União ganhadas +%d",
		name_pt = "Membro Núcleo Elite",
		desc1_pt = "Doação Sindical",
		name_vn = "Membro Núcleo Elite",
		id = 28,
		levelMax = 5,
		nums = slot1[28],
		upCost = slot2[28]
	},
	{
		name = "Trainer Aura",
		type = 18,
		desc1 = "Story dungeon",
		desc2_en = "Coins +%d",
		name_en = "Trainer Aura",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de história",
		icon = "city/develop/train/icon_ptfbzj.png",
		desc1_en = "Story dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "Aura de treinador",
		desc1_pt = "Masmorra de história",
		name_vn = "Aura de treinador",
		id = 29,
		nums = slot1[29],
		upCost = slot2[29]
	},
	{
		type = 2,
		name = "Unyielding",
		desc1 = "Maximum energy",
		name_en = "Unyielding",
		desc2_en = "Increases +%d",
		desc2_vn = "Aumentos +%d",
		desc2_kr = "증가+%d",
		desc2 = "Increases +%d",
		desc1_vn = "Energia máxima",
		icon = "city/develop/train/icon_qfqn.png",
		desc1_en = "Maximum energy",
		desc2_pt = "Aumentos +%d",
		name_pt = "Inflexível",
		desc1_pt = "Energia máxima",
		name_vn = "Inflexível",
		id = 30,
		levelMax = 5,
		nums = slot1[30],
		upCost = slot2[30]
	},
	{
		type = 6,
		name = "Adventure Elite",
		desc1 = "Daily quest",
		name_en = "Adventure Elite",
		desc2_en = "Get extra EXP +%d",
		desc2_vn = "Obter EXP extra +%d",
		desc2_kr = "추가 경험치 증가+%d",
		desc2 = "Get extra EXP +%d",
		desc1_vn = "Missão diária",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "Daily quest",
		desc2_pt = "Obter EXP extra +%d",
		name_pt = "Elite de Aventura",
		desc1_pt = "Missão diária",
		name_vn = "Elite de Aventura",
		id = 31,
		levelMax = 5,
		nums = slot1[31],
		upCost = slot2[31]
	},
	{
		type = 16,
		name = "Future Star",
		desc1 = "EXP Dungeon",
		name_en = "Future Star",
		desc2_en = "EXP +%d",
		desc2_vn = "EXP +%d",
		desc2_kr = "경험치 획득+%d",
		desc2 = "EXP +%d",
		desc1_vn = "EXP Masmorra",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "EXP Dungeon",
		desc2_pt = "EXP +%d",
		name_pt = "Estrela do Futuro",
		desc1_pt = "EXP Masmorra",
		name_vn = "Estrela do Futuro",
		id = 32,
		levelMax = 5,
		nums = slot1[32],
		upCost = slot2[32]
	},
	{
		name = "Time Merchant",
		type = 9,
		desc1 = "EXP Potion Purchase",
		desc2_en = "%d Discount",
		name_en = "Time Merchant",
		desc2_vn = "%d Desconto",
		desc2_kr = "가격 할인+%d",
		desc2 = "%d Discount",
		desc1_vn = "Compra de poções EXP",
		icon = "city/develop/train/icon_jb2.png",
		desc1_en = "EXP Potion Purchase",
		desc2_pt = "%d Desconto",
		name_pt = "Comerciante de Tempo",
		desc1_pt = "Compra de poções EXP",
		name_vn = "Comerciante de Tempo",
		id = 33,
		nums = {
			0.02,
			0.04,
			0.06,
			0.08,
			0.1,
			0.12,
			0.14,
			0.16,
			0.18,
			0.2
		},
		upCost = slot2[33]
	},
	{
		type = 14,
		name_en = "Fritters and Soymilk",
		desc1 = "Breakfast",
		name = "Fritters and Soymilk",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Café da manhã",
		icon = "city/develop/train/icon_tllq.png",
		arg = 1,
		desc1_en = "Breakfast",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Fritos e Leite de Soja",
		desc1_pt = "Café da manhã",
		name_vn = "Fritos e Leite de Soja",
		id = 34,
		levelMax = 5,
		nums = slot1[34],
		upCost = slot2[34]
	},
	{
		type = 26,
		name = "Pokémon Ruins",
		desc1 = "Shard Dungeon",
		name_en = "Pokémon Ruins",
		desc2_en = "Production +%d",
		desc2_vn = "Produção +%d",
		desc2_kr = "생산 증가+%d",
		desc2 = "Production +%d",
		desc1_vn = "Calabouço de Estilhaços",
		icon = "city/develop/train/icon_jb1.png",
		desc1_en = "Shard Dungeon",
		desc2_pt = "Produção +%d",
		name_pt = "Ruínas de Pokémon",
		desc1_pt = "Calabouço de Estilhaços",
		name_vn = "Ruínas de Pokémon",
		id = 35,
		levelMax = 5,
		nums = slot1[35],
		upCost = slot2[35]
	},
	{
		type = 13,
		name = "Millionaire",
		desc1 = "Treasure Pot",
		name_en = "Millionaire",
		desc2_en = "Coins +%d",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Pote do Tesouro",
		icon = "city/develop/train/icon_jbfbzj.png",
		desc1_en = "Treasure Pot",
		desc2_pt = "Moedas +%d",
		name_pt = "Milionário",
		desc1_pt = "Pote do Tesouro",
		name_vn = "Milionário",
		id = 36,
		levelMax = 5,
		nums = slot1[36],
		upCost = slot2[36]
	},
	{
		name = "Resident",
		type = 19,
		desc1 = "Elite Dungeon",
		desc2_en = "Coins +%d",
		name_en = "Resident",
		desc2_vn = "Moedas +%d",
		desc2_kr = "골드 코인 획득+%d",
		desc2 = "Coins +%d",
		desc1_vn = "Masmorra de Elite",
		icon = "city/develop/train/icon_jyfbzj.png",
		desc1_en = "Elite Dungeon",
		desc2_pt = "Moedas +%d",
		name_pt = "ResidenteResidente",
		desc1_pt = "Masmorra de Elite",
		name_vn = "ResidenteResidente",
		id = 37,
		nums = slot1[37],
		upCost = slot2[37]
	},
	{
		type = 14,
		name_en = "Warm Milk",
		desc1 = "Supper",
		name = "Warm Milk",
		desc2_en = "Claim energy+%d",
		desc2_vn = "Reivindicar energia+%d",
		desc2_kr = "체력 수령 추가+%d",
		desc2 = "Claim energy+%d",
		desc1_vn = "Jantar",
		icon = "city/develop/train/icon_tllq.png",
		arg = 4,
		desc1_en = "Supper",
		desc2_pt = "Reivindicar energia+%d",
		name_pt = "Leite quente",
		desc1_pt = "Jantar",
		name_vn = "Leite quente",
		id = 38,
		levelMax = 5,
		nums = slot1[38],
		upCost = slot2[38]
	},
	{
		name = "Adventure Elder",
		type = 6,
		desc1 = "Daily quest",
		desc2_en = "Get extra EXP +%d",
		name_en = "Adventure Elder",
		desc2_vn = "Obter EXP extra +%d",
		desc2_kr = "추가 경험치 증가+%d",
		desc2 = "Get extra EXP +%d",
		desc1_vn = "Missão diária",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "Daily quest",
		desc2_pt = "Obter EXP extra +%d",
		name_pt = "Ancião da Aventura",
		desc1_pt = "Missão diária",
		name_vn = "Ancião da Aventura",
		id = 39,
		nums = slot1[39],
		upCost = slot2[39]
	},
	{
		name = "Crew",
		type = 17,
		desc1 = "union donation",
		desc2_en = "Union coins earned +%d",
		name_en = "Crew",
		desc2_vn = "Moedas da União ganhadas +%d",
		desc2_kr = "길드 코인 획득량+%d",
		desc2 = "Union coins earned +%d",
		desc1_vn = "Doação Sindical",
		icon = "city/develop/train/icon_ghjz.png",
		desc1_en = "union donation",
		desc2_pt = "Moedas da União ganhadas +%d",
		name_pt = "Equipe técnica",
		desc1_pt = "Doação Sindical",
		name_vn = "Equipe técnica",
		id = 40,
		nums = slot1[40],
		upCost = slot2[40]
	},
	{
		type = 24,
		name = "Master of Romance",
		desc1 = "Gift Dungeon",
		name_en = "Master of Romance",
		desc2_en = "Production +%d",
		desc2_vn = "Produção +%d",
		desc2_kr = "생산 증가+%d",
		desc2 = "Production +%d",
		desc1_vn = "Masmorra de Presentes",
		icon = "city/develop/train/icon_jyfbcc.png",
		desc1_en = "Gift Dungeon",
		desc2_pt = "Produção +%d",
		name_pt = "Mestre do Romantismo",
		desc1_pt = "Masmorra de Presentes",
		name_vn = "Mestre do Romantismo",
		id = 41,
		levelMax = 5,
		nums = slot1[41],
		upCost = slot2[41]
	},
	__size = 41,
	__default = {
		__index = {
			type = 0,
			name = "",
			desc1 = "",
			name_en = "",
			desc2_en = "",
			desc2_vn = "",
			desc2_kr = "",
			desc2 = "",
			desc1_vn = "",
			icon = "",
			arg = 0,
			desc1_en = "",
			desc2_pt = "",
			name_pt = "",
			desc1_pt = "",
			name_vn = "",
			levelMax = 10,
			nums = {},
			upCost = {
				__size = 0
			}
		}
	}
}

return csv.trainer.skills
