slot0 = {
	__size = 0
}
csv.hell_random_tower.buffs = {
	{
		attrNum1 = "5%",
		attrNum2 = "5%",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrType2 = 7,
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 1,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 150
	},
	{
		attrNum1 = "10%",
		attrNum2 = "10%",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrType2 = 7,
		group = 2,
		attrType1 = 8,
		limit = 3,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 150
	},
	{
		attrNum1 = "15%",
		attrNum2 = "15%",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrType2 = 7,
		group = 3,
		attrType1 = 8,
		limit = 2,
		desc = "P. ATK and SP.ATK of allied Pokémons +15%",
		buffColor = "effect",
		id = 3,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 150
	},
	{
		attrNum1 = "10%",
		attrNum2 = "10%",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrType2 = 9,
		attrType1 = 10,
		desc = "Allied Pokémons P.DEF and SP.DEF +10%",
		buffColor = "effect",
		id = 4,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 200
	},
	{
		attrNum1 = "20%",
		attrNum2 = "20%",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrType2 = 9,
		group = 2,
		attrType1 = 10,
		limit = 3,
		desc = "Allied Pokémons P.DEF and SP.DEF +20%",
		buffColor = "effect",
		id = 5,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 200
	},
	{
		attrNum1 = "30%",
		attrNum2 = "30%",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrType2 = 9,
		group = 3,
		attrType1 = 10,
		limit = 2,
		desc = "Allied Pokémons P.DEF and SP.DEF +30%",
		buffColor = "effect",
		id = 6,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 200
	},
	{
		attrNum1 = "500",
		attrType1 = 14,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 7,
		icon = "city/develop/talent/icon_bj.png",
		weight = 100,
		desc = "Critical hit rate of allied Pokémons +5%"
	},
	{
		attrNum1 = "1000",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2,
		attrType1 = 14,
		limit = 3,
		desc = "Critical hit rate of allied Pokémons +10%",
		buffColor = "effect",
		id = 8,
		icon = "city/develop/talent/icon_bj.png",
		weight = 120
	},
	{
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 3,
		attrType1 = 14,
		limit = 1,
		desc = "Critical hit rate of allied Pokémons +15%",
		buffColor = "effect",
		id = 9,
		icon = "city/develop/talent/icon_bj.png",
		weight = 150
	},
	{
		attrNum1 = "1000",
		attrType1 = 15,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		id = 10,
		icon = "city/develop/talent/icon_bj.png",
		weight = 50,
		desc = "Critical hit damage of allied Pokémons +10%"
	},
	{
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 2,
		attrType1 = 15,
		limit = 3,
		desc = "Critical hit damage of allied Pokémons +15%",
		buffColor = "effect",
		id = 11,
		icon = "city/develop/talent/icon_bj.png",
		weight = 50
	},
	{
		attrNum1 = "2000",
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 3,
		attrType1 = 15,
		limit = 1,
		desc = "Critical hit damage of allied Pokémons +20%",
		buffColor = "effect",
		id = 12,
		icon = "city/develop/talent/icon_bj.png",
		weight = 50
	},
	{
		attrNum1 = "500",
		attrType1 = 23,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 13,
		icon = "city/develop/talent/icon_shjm.png",
		weight = 100,
		desc = "Allied Pokémons damage reduction +5%"
	},
	{
		attrNum1 = "1000",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2,
		attrType1 = 23,
		limit = 3,
		desc = "Allied Pokémons damage reduction +10%",
		buffColor = "effect",
		id = 14,
		icon = "city/develop/talent/icon_shjm.png",
		weight = 100
	},
	{
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 3,
		attrType1 = 23,
		limit = 1,
		desc = "Allied Pokémons damage reduction +15%",
		buffColor = "effect",
		id = 15,
		icon = "city/develop/talent/icon_shjm.png",
		weight = 50
	},
	{
		attrNum1 = "400",
		attrType1 = 26,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		id = 16,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 50,
		desc = "Allied Pokémons life steal +4%"
	},
	{
		attrNum1 = "800",
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		group = 2,
		attrType1 = 26,
		desc = "Allied Pokémons life steal +8%",
		buffColor = "effect",
		id = 17,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 40
	},
	{
		attrNum1 = "1000",
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		group = 3,
		attrType1 = 26,
		desc = "Allied Pokémons life steal +10%",
		buffColor = "effect",
		id = 18,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 30
	},
	{
		attrNum1 = "1000",
		attrType1 = 17,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		id = 19,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 50,
		desc = "Allied Pokémons DEF +10%"
	},
	{
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2,
		attrType1 = 17,
		desc = "Allied Pokémons DEF +15%",
		buffColor = "effect",
		id = 20,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 50
	},
	{
		attrNum1 = "2000",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 3,
		attrType1 = 17,
		desc = "Allied Pokémons DEF +20%",
		buffColor = "effect",
		id = 21,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 50
	},
	__size = 182,
	[101] = {
		group = 4,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		supplyType = 1,
		supplyNum = 25,
		condition = 1,
		desc = "Recover 25% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 101,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 20
	},
	[102] = {
		group = 5,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		supplyType = 1,
		supplyNum = 50,
		condition = 1,
		desc = "Recover 50% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 102,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 50
	},
	[103] = {
		group = 5,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		supplyType = 1,
		supplyNum = 100,
		condition = 1,
		desc = "Recover 100% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 103,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 10
	},
	[104] = {
		group = 6,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		supplyType = 1,
		supplyNum = 100,
		condition = 1,
		desc = "HP of allied Pokémons fully recovers",
		supplyTarget = 2,
		id = 104,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 10
	},
	[105] = {
		group = 4,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 2,
		supplyNum = 25,
		condition = 2,
		desc = "Recover 200 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 105,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 20
	},
	[106] = {
		group = 5,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 2,
		supplyNum = 50,
		condition = 2,
		desc = "Recover 500 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 106,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 50
	},
	[107] = {
		group = 5,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 2,
		supplyNum = 100,
		condition = 2,
		desc = "Recover 1000 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 107,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 10
	},
	[108] = {
		group = 6,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 2,
		supplyNum = 100,
		condition = 2,
		desc = "Rage of all Pokémons in battle fully recovers",
		supplyTarget = 2,
		id = 108,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 20
	},
	[109] = {
		group = 4,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 3,
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 109,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 20
	},
	[110] = {
		group = 5,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 3,
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 110,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 20
	},
	[111] = {
		group = 6,
		buffType = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		supplyType = 3,
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 111,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 10
	},
	[151] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 3,
		group = 99,
		pointType = 1,
		desc = "At the end of the battle, you can get an additional points of remaining rounds x2",
		buffColor = "effect_huang",
		id = 151,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 2
	},
	[152] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 3,
		group = 99,
		pointType = 2,
		desc = "At the end of the battle, you can get an additional ponits of surviving Pokémons x1",
		buffColor = "effect_huang",
		id = 152,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 1
	},
	[153] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 3,
		group = 99,
		pointType = 2,
		desc = "At the end of the battle, you can get an additional ponits of surviving Pokémons x2",
		buffColor = "effect_huang",
		id = 153,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 2
	},
	[154] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 3,
		group = 99,
		pointType = 3,
		desc = "At the end of the battle, you can get an additional points of the current floor level x2",
		buffColor = "effect_huang",
		id = 154,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 2
	},
	[200] = {
		supplyType = 4,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 200,
		supplyNum = 10,
		desc = "Reduce current HP by 10%"
	},
	[201] = {
		supplyType = 4,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 201,
		supplyNum = 20,
		desc = "Reduce current HP by 20%"
	},
	[202] = {
		supplyType = 4,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 202,
		supplyNum = 30,
		desc = "Reduce current HP by 30%"
	},
	[203] = {
		supplyType = 5,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 203,
		supplyNum = 20,
		desc = "Current rage value reduces by 200"
	},
	[204] = {
		supplyType = 5,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 204,
		supplyNum = 50,
		desc = "Current rage value reduces by 500"
	},
	[205] = {
		supplyType = 5,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 205,
		supplyNum = 100,
		desc = "Current rage value reduces by 1000"
	},
	[206] = {
		supplyType = 2,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 206,
		supplyNum = 50,
		desc = "Increases current rage value by 500"
	},
	[207] = {
		group = 1111,
		buffColor = "effect_lan",
		id = 207,
		attrType1 = 13,
		attrNum1 = "-20%",
		desc = "Speed of allied Pokémons -20%"
	},
	[208] = {
		group = 1111,
		buffColor = "effect_lan",
		id = 208,
		attrType1 = 13,
		attrNum1 = "-40%",
		desc = "Speed of allied Pokémons -40%"
	},
	[210] = {
		supplyType = 1,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 210,
		supplyNum = 100,
		desc = "HP of allied Pokémons fully recovers"
	},
	[211] = {
		supplyType = 2,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 211,
		supplyNum = 100,
		desc = "Rage of all Pokémons in battle fully recovers"
	},
	[212] = {
		group = 1111,
		buffColor = "effect",
		id = 212,
		attrType1 = 7,
		attrNum1 = "-5%",
		desc = "P. ATK of allied Pokémons -5%"
	},
	[213] = {
		group = 1111,
		attrType1 = 8,
		buffColor = "effect",
		id = 213,
		icon = "city/adventure/random_tower/icon/icon_tg.png",
		attrNum1 = "-5%",
		desc = "SP.ATK of allied Pokémons -5%"
	},
	[214] = {
		supplyType = 1,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 214,
		supplyNum = 20,
		desc = "Allied Pokémons recovers 20% HP"
	},
	[215] = {
		supplyType = 2,
		buffType = 2,
		group = 1111,
		supplyTarget = 2,
		id = 215,
		supplyNum = 20,
		desc = "Rage of all Pokémons in battle increases by 200"
	},
	[301] = {
		id = 301,
		buffType = 4,
		effectTimes = 1,
		passiveSkill = 80052,
		group = 1000,
		desc = "All enemies are silence for 1 turn in the next battle",
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		icon = "city/adventure/random_tower/icon/icon_kz.png"
	},
	[1001] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1001,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82001
	},
	[1002] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1002,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82002
	},
	[1003] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1003,
		icon = "city/develop/talent/icon_bj.png",
		weight = 100,
		passiveSkill = 82003
	},
	[1004] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1004,
		icon = "city/develop/talent/icon_bj.png",
		weight = 100,
		passiveSkill = 82004
	},
	[1005] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1005,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82005
	},
	[1006] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1006,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 10,
		passiveSkill = 82006
	},
	[1007] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1007,
		icon = "city/adventure/random_tower/icon/icon_gj1.png",
		weight = 10,
		passiveSkill = 82007
	},
	[1008] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1008,
		icon = "city/adventure/random_tower/icon/icon_gj1.png",
		weight = 10,
		passiveSkill = 82008
	},
	[1009] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1009,
		icon = "city/adventure/random_tower/icon/icon_fs.png",
		weight = 1,
		passiveSkill = 82009
	},
	[1010] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1010,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 1,
		passiveSkill = 82010
	},
	[1021] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1021,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 0,
		passiveSkill = 82016
	},
	[1022] = {
		group = 101,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1022,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png",
		weight = 0,
		passiveSkill = 82017
	},
	[1031] = {
		group = 103,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82021,
		id = 1031,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png",
		limit = 1
	},
	[1032] = {
		group = 103,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82022,
		id = 1032,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png",
		limit = 1
	},
	[1033] = {
		group = 103,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82023,
		id = 1033,
		icon = "city/adventure/random_tower/icon/icon_js2.png",
		limit = 1
	},
	[1111] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1111,
		icon = "city/adventure/random_tower/icon/icon_pl.png",
		weight = 100,
		passiveSkill = 82101
	},
	[1112] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1112,
		icon = "city/develop/talent/icon_bj.png",
		weight = 100,
		passiveSkill = 82102
	},
	[1113] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1113,
		icon = "city/develop/talent/icon_bj.png",
		weight = 100,
		passiveSkill = 82103
	},
	[1114] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1114,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 100,
		passiveSkill = 82104
	},
	[1115] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1115,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 100,
		passiveSkill = 82105
	},
	[1116] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1116,
		icon = "city/adventure/random_tower/icon/icon_dk.png",
		weight = 10,
		passiveSkill = 82106
	},
	[1117] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1117,
		icon = "city/adventure/random_tower/icon/icon_dk.png",
		weight = 10,
		passiveSkill = 82107
	},
	[1118] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1118,
		icon = "city/adventure/random_tower/icon/icon_dk.png",
		weight = 10,
		passiveSkill = 82108
	},
	[1119] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1119,
		icon = "city/adventure/random_tower/icon/icon_qr.png",
		weight = 1,
		passiveSkill = 82109
	},
	[1120] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1120,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 1,
		passiveSkill = 82110
	},
	[1121] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1121,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 0,
		passiveSkill = 82116
	},
	[1122] = {
		group = 111,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1122,
		icon = "city/adventure/random_tower/icon/icon_pl.png",
		weight = 0,
		passiveSkill = 82117
	},
	[1131] = {
		group = 113,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82121,
		id = 1131,
		icon = "city/adventure/random_tower/icon/icon_yybm.png",
		limit = 1
	},
	[1132] = {
		group = 113,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82122,
		id = 1132,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png",
		limit = 1
	},
	[1133] = {
		group = 113,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82123,
		id = 1133,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png",
		limit = 1
	},
	[1211] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1211,
		icon = "city/adventure/random_tower/icon/icon_mf.png",
		weight = 100,
		passiveSkill = 82201
	},
	[1212] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1212,
		icon = "city/adventure/random_tower/icon/icon_mf.png",
		weight = 100,
		passiveSkill = 82202
	},
	[1213] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1213,
		icon = "city/adventure/random_tower/icon/icon_zh.png",
		weight = 100,
		passiveSkill = 82203
	},
	[1214] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1214,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 100,
		passiveSkill = 82204
	},
	[1215] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1215,
		icon = "city/adventure/random_tower/icon/icon_qz.png",
		weight = 100,
		passiveSkill = 82205
	},
	[1216] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1216,
		icon = "city/adventure/random_tower/icon/icon_sh2.png",
		weight = 10,
		passiveSkill = 82206
	},
	[1217] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1217,
		icon = "city/adventure/random_tower/icon/icon_dk.png",
		weight = 10,
		passiveSkill = 82207
	},
	[1218] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1218,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 10,
		passiveSkill = 82208
	},
	[1219] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1219,
		icon = "city/adventure/random_tower/icon/icon_qr.png",
		weight = 1,
		passiveSkill = 82209
	},
	[1220] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1220,
		icon = "city/adventure/random_tower/icon/icon_yybm3.png",
		weight = 1,
		passiveSkill = 82210
	},
	[1221] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1221,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png",
		weight = 0,
		passiveSkill = 82216
	},
	[1222] = {
		group = 121,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1222,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 0,
		passiveSkill = 82217
	},
	[1231] = {
		group = 123,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82221,
		id = 1231,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png",
		limit = 1
	},
	[1232] = {
		group = 123,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82222,
		id = 1232,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		limit = 1
	},
	[1233] = {
		group = 123,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82223,
		id = 1233,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		limit = 1
	},
	[1311] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1311,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82301
	},
	[1312] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1312,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82302
	},
	[1313] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1313,
		icon = "city/adventure/random_tower/icon/icon_xw.png",
		weight = 100,
		passiveSkill = 82303
	},
	[1314] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1314,
		icon = "city/adventure/random_tower/icon/icon_pl.png",
		weight = 100,
		passiveSkill = 82304
	},
	[1315] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1315,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82305
	},
	[1316] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1316,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 10,
		passiveSkill = 82306
	},
	[1317] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1317,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 10,
		passiveSkill = 82307
	},
	[1318] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1318,
		icon = "city/adventure/random_tower/icon/icon_gj1.png",
		weight = 10,
		passiveSkill = 82308
	},
	[1319] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1319,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 1,
		passiveSkill = 82309
	},
	[1320] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1320,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 1,
		passiveSkill = 82310
	},
	[1321] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1321,
		icon = "city/adventure/random_tower/icon/icon_ph.png",
		weight = 0,
		passiveSkill = 82316
	},
	[1322] = {
		group = 131,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1322,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 0,
		passiveSkill = 82317
	},
	[1331] = {
		group = 133,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82321,
		id = 1331,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png",
		limit = 1
	},
	[1332] = {
		group = 133,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82321,
		id = 1332,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		limit = 1
	},
	[1333] = {
		group = 133,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82321,
		id = 1333,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png",
		limit = 1
	},
	[1411] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1411,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 100,
		passiveSkill = 82401
	},
	[1412] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1412,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 100,
		passiveSkill = 82402
	},
	[1413] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1413,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 100,
		passiveSkill = 82403
	},
	[1414] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1414,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82404
	},
	[1415] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1415,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 100,
		passiveSkill = 82405
	},
	[1416] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1416,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 10,
		passiveSkill = 82406
	},
	[1417] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1417,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 10,
		passiveSkill = 82407
	},
	[1418] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1418,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 10,
		passiveSkill = 82408
	},
	[1419] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1419,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 1,
		passiveSkill = 82409
	},
	[1420] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1420,
		icon = "city/develop/talent/icon_ysg.png",
		weight = 1,
		passiveSkill = 82410
	},
	[1421] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1421,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 0,
		passiveSkill = 82416
	},
	[1422] = {
		group = 141,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1422,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 0,
		passiveSkill = 82417
	},
	[1431] = {
		group = 143,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82421,
		id = 1431,
		icon = "city/develop/talent/icon_ysg.png",
		limit = 1
	},
	[1432] = {
		group = 143,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82422,
		id = 1432,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		limit = 1
	},
	[1433] = {
		group = 143,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82423,
		id = 1433,
		icon = "city/develop/talent/icon_ysg.png",
		limit = 1
	},
	[1511] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1511,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 100,
		passiveSkill = 82501
	},
	[1512] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1512,
		icon = "city/develop/talent/icon_bsjc_kx.png",
		weight = 100,
		passiveSkill = 82502
	},
	[1513] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1513,
		icon = "city/develop/talent/icon_bsjc_kx.png",
		weight = 100,
		passiveSkill = 82503
	},
	[1514] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1514,
		icon = "city/adventure/random_tower/icon/icon_jh.png",
		weight = 100,
		passiveSkill = 82504
	},
	[1515] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1515,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 100,
		passiveSkill = 82505
	},
	[1516] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1516,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 10,
		passiveSkill = 82506
	},
	[1517] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1517,
		icon = "city/adventure/random_tower/icon/icon_jh.png",
		weight = 10,
		passiveSkill = 82507
	},
	[1518] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1518,
		icon = "city/adventure/random_tower/icon/icon_jh.png",
		weight = 10,
		passiveSkill = 82508
	},
	[1519] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1519,
		icon = "city/develop/talent/icon_bsjc_kx.png",
		weight = 1,
		passiveSkill = 82509
	},
	[1520] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1520,
		icon = "city/develop/talent/icon_bskx.png",
		weight = 1,
		passiveSkill = 82510
	},
	[1521] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1521,
		icon = "city/develop/talent/icon_bskx.png",
		weight = 0,
		passiveSkill = 82516
	},
	[1522] = {
		group = 151,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1522,
		icon = "city/develop/talent/icon_tf.png",
		weight = 0,
		passiveSkill = 82517
	},
	[1531] = {
		group = 153,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82521,
		id = 1531,
		icon = "city/develop/talent/icon_tf.png",
		limit = 1
	},
	[1532] = {
		group = 153,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82522,
		id = 1532,
		icon = "city/develop/talent/icon_sf.png",
		limit = 1
	},
	[1533] = {
		group = 153,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82523,
		id = 1533,
		icon = "city/develop/talent/icon_smz.png",
		limit = 1
	},
	[1611] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1611,
		icon = "city/develop/talent/icon_smz.png",
		weight = 100,
		passiveSkill = 82601
	},
	[1612] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1612,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 100,
		passiveSkill = 82602
	},
	[1613] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1613,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 100,
		passiveSkill = 82603
	},
	[1614] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1614,
		icon = "city/develop/talent/icon_smz.png",
		weight = 100,
		passiveSkill = 82604
	},
	[1615] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1615,
		icon = "city/develop/talent/icon_smz.png",
		weight = 100,
		passiveSkill = 82605
	},
	[1616] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1616,
		icon = "city/develop/talent/icon_smz.png",
		weight = 10,
		passiveSkill = 82606
	},
	[1617] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1617,
		icon = "city/develop/talent/icon_sf.png",
		weight = 10,
		passiveSkill = 82607
	},
	[1618] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1618,
		icon = "city/develop/talent/icon_bskx.png",
		weight = 10,
		passiveSkill = 82608
	},
	[1619] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1619,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1,
		passiveSkill = 82609
	},
	[1620] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1620,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 1,
		passiveSkill = 82610
	},
	[1621] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1621,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 0,
		passiveSkill = 82616
	},
	[1622] = {
		group = 161,
		buffType = 4,
		buffColor = "effect",
		limit = 1,
		id = 1622,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 0,
		passiveSkill = 82617
	},
	[1631] = {
		group = 163,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82621,
		id = 1631,
		icon = "city/adventure/random_tower/icon/icon_hx1.png",
		limit = 1
	},
	[1632] = {
		group = 163,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82622,
		id = 1632,
		icon = "city/adventure/random_tower/icon/icon_hx1.png",
		limit = 1
	},
	[1633] = {
		group = 163,
		buffType = 4,
		buffColor = "effect",
		passiveSkill = 82623,
		id = 1633,
		icon = "city/adventure/random_tower/icon/icon_hx1.png",
		limit = 1
	},
	[10001] = {
		id = 10001,
		buffType = 4,
		belongLib = 5,
		passiveSkill = 80058,
		group = 9999,
		desc = "Allied Pokémons gain a shield that is equal to the HP it lost at the start of the battle for 2 rounds",
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[10002] = {
		id = 10002,
		buffType = 4,
		belongLib = 5,
		passiveSkill = 80059,
		group = 9999,
		desc = "Allied Pokémons gain 8% damage reduction each time they lose 10% HP, this is only effecitve on the first round",
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[10003] = {
		group = 9999,
		buffType = 4,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		passiveSkill = 80060,
		id = 10003,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		limit = 1,
		desc = "Resets the enemies' rage value to zero during the second round of the battle"
	},
	[10004] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		id = 10004,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png",
		passiveSkill = 80061,
		desc = "When any of the allied Pokémon is defeated, the remaining surviving Pokémons gain 20% of its max. HP and 500 rage value"
	},
	[10005] = {
		group = 9999,
		buffType = 4,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		passiveSkill = 80062,
		id = 10005,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		desc = "At the end of the round, all allied Pokémons recover 15% of its lost HP"
	},
	[10006] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10006,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		passiveSkill = 80063,
		desc = "Gives 10% of chance to recover 100% rage level when allied Pokémon uses the ultimate skill"
	},
	[10007] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		id = 10007,
		icon = "city/adventure/random_tower/icon/icon_js1.png",
		passiveSkill = 80064,
		desc = "Marks a random enemy Pokémon at the beginning of each round to increase its damage taken by an additional 50%"
	},
	[10008] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10008,
		icon = "city/adventure/random_tower/icon/icon_yybm.png",
		passiveSkill = 80065,
		desc = "Speed increases by 20% for 2 rounds when allied Pokémons use the Ultimate Skill"
	},
	[10009] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		id = 10009,
		icon = "city/adventure/random_tower/icon/icon_cxsh.png",
		passiveSkill = 80066,
		desc = "Type effectiveness of allied Pokémons increases, causing 20% more damage to types that are effective during battles"
	},
	[10010] = {
		group = 9999,
		buffType = 4,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		passiveSkill = 80067,
		id = 10010,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		desc = "When your Pokémons defeat the opponent's Pokémons, you receive 10% HP and 200 rage level"
	},
	[10011] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80068,
		group = 9999,
		limit = 1,
		desc = "Enemy Pokémons with less than 10% HP at the end of the final round will be finished off by Yveltal, the god of death, and will leave the battlefield instantly",
		buffColor = "effect",
		id = 10011,
		icon = "city/adventure/random_tower/icon/icon_js.png"
	},
	[10012] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10012,
		icon = "city/adventure/random_tower/icon/icon_yybm.png",
		passiveSkill = 80069,
		desc = "Increases speed of allied team by 20% in the first round of the battle"
	},
	[10013] = {
		id = 10013,
		buffType = 4,
		belongLib = 1,
		passiveSkill = 80070,
		group = 9999,
		desc = "Increases the speed of an allied Pokémon type x4% only the Pokémon's first type is considered)",
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		icon = "city/adventure/random_tower/icon/icon_yybm.png"
	},
	[10014] = {
		id = 10014,
		buffType = 4,
		belongLib = 7,
		passiveSkill = 80071,
		group = 9999,
		desc = "There is a 50% chance the Pokémons in the front line are immune to status conditions",
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[10015] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80072,
		group = 9999,
		limit = 1,
		desc = "The enemy Pokémons receive a permanent reduction in max. HP by 10%",
		buffColor = "effect",
		id = 10015,
		icon = "city/adventure/random_tower/icon/icon_js.png"
	},
	[10016] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		id = 10016,
		icon = "city/adventure/random_tower/icon/icon_js1.png",
		passiveSkill = 80073,
		desc = "When an allied Pokémon is defeated, it deals equal damage to the enemy that slays it"
	},
	[10017] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		id = 10017,
		icon = "city/adventure/random_tower/icon/icon_fs.png",
		passiveSkill = 80074,
		desc = "When an enemy is defeated, it deals 40% of the damage on the defeated enemy to nearby Pokémons"
	},
	[10018] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10018,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		passiveSkill = 80075,
		desc = "Allied Pokémons get a 20% chance of stealing 50 rage level when attacking"
	},
	[10019] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		id = 10019,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png",
		passiveSkill = 80076,
		desc = "Healing rate increases by 30% for allied Pokémons"
	},
	[10020] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10020,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png",
		passiveSkill = 80077,
		desc = "Allied Pokémons will remove all buff effect of the enemy after using the Ultimate Skill"
	},
	[10021] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10021,
		icon = "city/adventure/random_tower/icon/icon_zh.png",
		passiveSkill = 80078,
		desc = "Ultimate damage of allied Pokémons increases by 30% in odd number rounds, but reduces by 15% in even number rounds"
	},
	[10022] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		id = 10022,
		icon = "city/adventure/random_tower/icon/icon_fs.png",
		passiveSkill = 80079,
		desc = "Deals a true damage of 20% ATK of the Pokémon with the highest ATK in the allied team to all enemy Pokémons at the end of the final round"
	},
	[10023] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		id = 10023,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		passiveSkill = 80080,
		desc = "When entering a battle, your team gain a shield that can absorb all damage taken by all the allied Pokémons, the amount of absorption is equal to the allied Pokémon with the highest HP"
	},
	[10024] = {
		id = 10024,
		buffType = 4,
		belongLib = 6,
		passiveSkill = 80081,
		group = 9999,
		desc = "Double the burning damage by allied Pokémons",
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		icon = "city/adventure/random_tower/icon/icon_cxsh.png"
	},
	[10025] = {
		group = 9999,
		buffType = 4,
		buffColor = "effect",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		id = 10025,
		icon = "city/adventure/random_tower/icon/icon_zh.png",
		passiveSkill = 80082,
		desc = "Full rage value during the first round of the battle, but Ultimate Skill reduces 20% for 1 round"
	},
	__default = {
		__index = {
			condition = 0,
			attrNum1 = "",
			attrNum2 = "",
			attrNum3 = "",
			effectTimes = 0,
			attrType1 = 0,
			pointType = 0,
			desc = "",
			group = 1,
			attrType3 = 0,
			pointValue = 0,
			supplyTarget = 0,
			icon = "",
			extraWeight = 0,
			limit = 99,
			onlyOne = false,
			buffType = 1,
			belongLib = 0,
			attrNatureType3 = 0,
			supplyType = 0,
			supplyNum = 0,
			attrNatureType1 = 0,
			attrType2 = 0,
			passiveSkill = 0,
			changeLib = 0,
			buffColor = "",
			iconBg = "",
			weight = 999,
			skillgroup = {}
		}
	}
}

return csv.hell_random_tower.buffs
