slot0 = {
	__size = 0
}
csv.explorer.tech_tree = {
	{
		id = 1,
		name = "Reinforced Components",
		addType = 3,
		needCoreLevel = 1,
		attrDesc = "All component stats percentage increased",
		levelLimit = 10,
		addAttrNum = "0.10%",
		attrAddDesc1 = "All component stats increased",
		icon = "city/develop/explore/icon_sxzj.png"
	},
	{
		attrNum2 = "0.50%",
		name = "Intense Attack Of The Rack",
		preTechLevel1 = 7,
		needCoreLevel = 1,
		attrAddDesc1 = "P.ATK increased",
		attrType1 = 7,
		attrDesc = "All Pokémon P.ATK and SP.ATK increased",
		levelLimit = 10,
		preTechID1 = 1,
		costID = 2,
		attrAddDesc2 = "SP.ATK increased",
		attrType2 = 8,
		id = 2,
		icon = "city/develop/explore/icon_wgts.png",
		attrNum1 = "0.50%"
	},
	{
		attrNum2 = "0.50%",
		name = "Rack Guard",
		preTechLevel1 = 7,
		needCoreLevel = 1,
		attrAddDesc1 = "P.DEF increased",
		attrType1 = 9,
		attrDesc = "All Pokémon P.DEF and SP. DEF increased",
		levelLimit = 10,
		preTechID1 = 1,
		costID = 2,
		attrAddDesc2 = "SP. DEF increased",
		attrType2 = 10,
		id = 3,
		icon = "city/develop/explore/icon_wfts.png",
		attrNum1 = "0.50%"
	},
	{
		attrNum2 = "30",
		name = "Intense attack reinforced",
		preTechLevel1 = 7,
		needCoreLevel = 10,
		attrAddDesc1 = "P.DMG increased",
		attrType1 = 32,
		attrDesc = "All Pokémon P.DMG and SP.DMG increased",
		levelLimit = 10,
		preTechID1 = 2,
		costID = 3,
		attrAddDesc2 = "SP.DMG increased",
		attrType2 = 34,
		id = 4,
		icon = "city/develop/explore/icon_wsts.png",
		attrNum1 = "30"
	},
	{
		preTechID2 = 3,
		name = "HP Enhanced",
		preTechLevel2 = 5,
		needCoreLevel = 10,
		preTechID1 = 2,
		attrType1 = 1,
		attrDesc = "All Pokémon HP increased",
		levelLimit = 10,
		attrAddDesc1 = "HP increased",
		costID = 3,
		preTechLevel1 = 5,
		id = 5,
		icon = "city/develop/explore/icon_smzts.png",
		attrNum1 = "0.50%"
	},
	{
		attrNum2 = "30",
		name = "Guard Reinforced",
		preTechLevel1 = 7,
		needCoreLevel = 10,
		attrAddDesc1 = "P.DMG Reduction increased",
		attrType1 = 33,
		attrDesc = "All Pokémon DMG Reduction and SP.DMG Reduction increased",
		levelLimit = 10,
		preTechID1 = 3,
		costID = 3,
		attrAddDesc2 = "SP.DMG Reduction increased",
		attrType2 = 35,
		id = 6,
		icon = "city/develop/explore/icon_wsjmts.png",
		attrNum1 = "30"
	},
	{
		attrNum2 = "50",
		name = "Intense Attack Recombined",
		preTechLevel1 = 7,
		needCoreLevel = 20,
		attrAddDesc1 = "P.DEF ignore increased",
		attrType1 = 11,
		attrDesc = "All Pokémon P.DEF ignore and SP. DEF ignore increased",
		levelLimit = 10,
		preTechID1 = 4,
		costID = 4,
		attrAddDesc2 = "SP. DEF ignore increased",
		attrType2 = 12,
		id = 7,
		icon = "city/develop/explore/icon_wfhszj.png",
		attrNum1 = "50"
	},
	{
		attrNum2 = "30",
		name = "Boosted CRI Attack",
		preTechLevel1 = 5,
		needCoreLevel = 20,
		attrAddDesc1 = "CRI Rate increased",
		attrType1 = 14,
		attrDesc = "All Pokémon CRI Rate and CRI DMG increased",
		levelLimit = 10,
		preTechID1 = 5,
		costID = 4,
		attrAddDesc2 = "CRI DMG increased",
		attrType2 = 15,
		id = 8,
		icon = "city/develop/explore/icon_bjlts.png",
		attrNum1 = "30"
	},
	{
		attrAddDesc1 = "Block rate increased",
		name = "Guard Regrouped",
		preTechID1 = 6,
		needCoreLevel = 20,
		attrType1 = 17,
		attrDesc = "All Pokémon Block rate increased",
		levelLimit = 10,
		costID = 4,
		preTechLevel1 = 7,
		id = 9,
		icon = "city/develop/explore/icon_dklts.png",
		attrNum1 = "50"
	},
	{
		preTechLevel1 = 7,
		name = "Device Core Upgraded",
		addType = 2,
		needCoreLevel = 30,
		explorerID = 7,
		attrType1 = 7,
		attrDesc = "Poliwhirl Explorer Device's combat skill effect improved",
		levelLimit = 5,
		costID = 5,
		preTechID1 = 7,
		id = 10,
		icon = "city/develop/explore/icon_wxwtxq.png",
		attrNum1 = "1"
	},
	{
		preTechID2 = 8,
		name = "Device Core Upgraded",
		preTechLevel2 = 5,
		needCoreLevel = 30,
		preTechID1 = 7,
		attrType1 = 9,
		attrDesc = "Volcanion Airship's combat skill effect improved",
		levelLimit = 5,
		addType = 2,
		costID = 6,
		preTechLevel1 = 5,
		explorerID = 9,
		id = 11,
		icon = "city/develop/explore/icon_beknefc.png",
		attrNum1 = "1"
	},
	{
		preTechID2 = 8,
		name = "Device Core Upgraded",
		preTechLevel2 = 5,
		needCoreLevel = 30,
		preTechID1 = 9,
		attrType1 = 8,
		attrDesc = "Pseudo-Legendary Aircraft's combat skill effect improved",
		levelLimit = 5,
		addType = 2,
		costID = 6,
		preTechLevel1 = 5,
		explorerID = 8,
		id = 12,
		icon = "city/develop/explore/icon_zshfc.png",
		attrNum1 = "1"
	},
	{
		preTechLevel1 = 7,
		name = "Device Core Upgraded",
		addType = 2,
		needCoreLevel = 30,
		explorerID = 6,
		attrType1 = 6,
		attrDesc = "Doduo Explorer Device's combat skill effect improved",
		levelLimit = 5,
		costID = 5,
		preTechID1 = 9,
		id = 13,
		icon = "city/develop/explore/icon_ddtxq.png",
		attrNum1 = "1"
	},
	__size = 13,
	__default = {
		__index = {
			preTechID2 = 0,
			attrNum2 = "",
			attrAddDesc2 = "所有精灵攻击力增加",
			needCoreLevel = 0,
			preTechID1 = 0,
			preTechLevel2 = 0,
			attrDesc = "提升所有精灵的生命值、攻击力",
			levelLimit = 0,
			addAttrNum = "",
			costID = 1,
			preTechLevel1 = 0,
			addType = 1,
			attrAddDesc1 = "所有精灵生命值增加",
			attrNum1 = ""
		}
	}
}

return csv.explorer.tech_tree
