--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['craft']['robot_num'] = {
	[1] = {
		id = 1,
		realNum = 200,
		totalNum = 500
	},
	[2] = {
		id = 2,
		realNum = 300,
		totalNum = 600
	},
	[3] = {
		id = 3,
		realNum = 400,
		totalNum = 800
	},
	[4] = {
		id = 4,
		realNum = 750,
		totalNum = 1000
	},
	[5] = {
		id = 5,
		realNum = 1500,
		totalNum = 2000
	},
	[6] = {
		id = 6,
		realNum = 3000,
		totalNum = 3000
	},
	__size = 6,
	__default = {
		__index = {
			
		}
	}
}
return csv.craft.robot_num