slot0 = {
	__size = 0
}
csv.cross.hunting.supply = {
	{
		desc_vn = "Restore 100% of the HP of the specified unit",
		name_en = "Healing single unit",
		name_tw = "Healing single unit",
		name_kr = "Healing single unit",
		effect = 100,
		desc_th = "Restore 100% of the HP of the specified unit",
		name = "Healing single unit",
		desc = "Restore 100% of the HP of the specified unit",
		type = 1,
		icon = "city/adventure/random_tower/icon/icon_zl.png",
		desc_tw = "Restore 100% of the HP of the specified unit",
		quality = 3,
		desc_en = "Restore 100% of the HP of the specified unit",
		name_vn = "Healing single unit",
		name_th = "รักษาเป้าหมายเดียว",
		id = 1,
		desc_kr = "Restore 100% of the HP of the specified unit"
	},
	{
		desc_vn = "Restore 30% health of all your units",
		name_en = "All ally healing",
		name_tw = "All ally healing",
		name_kr = "All ally healing",
		effect = 30,
		desc_th = "Restore 30% health of all your units",
		name = "All ally healing",
		desc = "Restore 30% health of all your units",
		type = 2,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		desc_tw = "Restore 30% health of all your units",
		quality = 5,
		desc_en = "Restore 30% health of all your units",
		name_vn = "All ally healing",
		name_th = "รักษาพันธมิตรทั้งหมด",
		id = 2,
		desc_kr = "Restore 30% health of all your units"
	},
	{
		type = 3,
		name = "Resurrection single unit",
		name_tw = "Resurrection single unit",
		name_kr = "Resurrection single unit",
		name_en = "Resurrection single unit",
		desc_en = "Resurrect a dead character",
		quality = 2,
		desc = "Resurrect a dead character",
		desc_vn = "Resurrect a dead character",
		desc_th = "Resurrect a dead character",
		name_vn = "Resurrection single unit",
		name_th = "ฟื้นชีพเป้าหมายเดียว",
		id = 3,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		desc_tw = "Resurrect a dead character",
		desc_kr = "Resurrect a dead character"
	},
	{
		desc_tw = "Restore 100% of the HP of the specified unit",
		name = "Healing single unit",
		name_tw = "Healing single unit",
		name_kr = "Healing single unit",
		quality = 3,
		desc_th = "Restore 100% of the HP of the specified unit",
		type = 1,
		desc = "Restore 100% of the HP of the specified unit",
		name_en = "Healing single unit",
		icon = "city/adventure/random_tower/icon/icon_zl.png",
		desc_vn = "Restore 100% of the HP of the specified unit",
		effect = 100,
		group = 2,
		desc_en = "Restore 100% of the HP of the specified unit",
		name_vn = "Healing single unit",
		name_th = "รักษาเป้ายหมายเดียว",
		id = 4,
		desc_kr = "Restore 100% of the HP of the specified unit"
	},
	{
		desc_tw = "Restore 30% health of all your units",
		name = "All ally healing",
		name_tw = "All ally healing",
		name_kr = "All ally healing",
		quality = 5,
		desc_th = "Restore 30% health of all your units",
		type = 2,
		desc = "Restore 30% health of all your units",
		name_en = "All ally healing",
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		desc_vn = "Restore 30% health of all your units",
		effect = 30,
		group = 2,
		desc_en = "Restore 30% health of all your units",
		name_vn = "All ally healing",
		name_th = "รักษาพันธมิตรทั้งหมด",
		id = 5,
		desc_kr = "Restore 30% health of all your units"
	},
	{
		desc_vn = "Resurrect a dead character",
		name = "Resurrection single unit",
		name_tw = "Resurrection single unit",
		name_kr = "Resurrection single unit",
		name_en = "Resurrection single unit",
		desc_th = "Resurrect a dead character",
		type = 3,
		desc = "Resurrect a dead character",
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		desc_tw = "Resurrect a dead character",
		quality = 2,
		group = 2,
		desc_en = "Resurrect a dead character",
		name_vn = "Resurrection single unit",
		name_th = "ฟื้นชีพเป้าหมายเดียว",
		id = 6,
		desc_kr = "Resurrect a dead character"
	},
	__size = 6,
	__default = {
		__index = {
			name_en = "",
			quality = 1,
			name_tw = "",
			name_kr = "",
			group = 1,
			desc_en = "",
			effect = 0,
			desc = "",
			name = "",
			desc_vn = "",
			name_vn = "",
			name_th = "",
			desc_th = "",
			icon = "",
			desc_tw = "",
			desc_kr = ""
		}
	}
}

return csv.cross.hunting.supply
