csv = {}
iup = {}
sdk = {}

print("jit off", jit.off())

ffi = require("ffi")

print("ffi.arch", ffi.arch)

if ffi.arch == "arm64" and package.path:find("x64/cocos") == nil then
	package.path = "x64/cocos/?.lua;x64/src/?.lua" .. package.path
end

require("lz4")
require("aes")
require("ymrand")
require("ymasync")
require("ymdump")
require("socket")
require("socket.core")
require("mime.core")
require("3rd.MD5")
require("3rd.CRC32")
require("3rd.msgpack")
require("3rd.stringzutils")
require("defines")
require("cocos_init")
require("util.random")
require("util.itertools")
require("util.arraytools")
require("util.maptools")
require("util.functools")
require("util.nodetools")
require("util.callbacks")
require("util.str")
require("util.csv")
require("util.log")
require("util.helper")
require("util.print_r")
require("util.config")
require("util.language")
require("util.time")
require("util.env")
require("util.eval")
require("util.randname")
require("util.debug")
require("util.debug_ui")
require("util.stat")
require("util.saltnumber")
require("util.versionvalue")
require("util.profiler")
require("luastl.vector")
require("luastl.list")
require("luastl.set")
require("luastl.map")
require("luastl.collection")
require("easy.extends.Director")
require("easy.extends.Node")
require("easy.extends.UIButton")
require("easy.extends.UIImageView")
require("easy.extends.UISlider")
require("easy.extends.UILoadingBar")
require("easy.extends.UIListView")
require("easy.extends.ParticleSystemQuad")
require("easy.text")
require("easy.label")
require("easy.table")
require("easy.richtext")
require("easy.action_richtext")
require("easy.stream_richtext")
require("easy.sprite")
require("easy.render_target")
require("easy.transition")
require("easy.widget")
require("easy.idlerdebug")
require("easy.idlersystem")
require("easy.idler")
require("easy.idlercomputer")
require("easy.idlereasy")
require("easy.beauty")
require("easy.effect")
require("easy.vmproxy")
require("easy.dialog")
require("easy.touchtip")
require("easy.ui_bind")
require("easy.ui_adapter")
require("easy.ui_l10n")
require("easy.user_default")
require("easy.blacklist")
require("cache.include")
require("app.include")
cc.load("mvc")
cc.load("components")
