--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['random_maze']['decorate'] = {
	[1] = {
		id = 1,
		res = 'city/adventure/random_maze/huoshan/beijing.png',
		layer = 'panelBg',
		scale = 4,
		theme = 1,
		z = 1
	},
	[2] = {
		id = 2,
		res = 'city/adventure/random_maze/huoshan/taimian_01.png',
		layer = 'panelBg',
		anchorX = 1,
		y = -100,
		scale = 2,
		theme = 1,
		z = 2
	},
	[3] = {
		id = 3,
		res = 'city/adventure/random_maze/huoshan/taimian_02.png',
		layer = 'panelBg',
		anchorX = 0,
		y = -100,
		scale = 2,
		theme = 1,
		z = 2
	},
	[4] = {
		id = 4,
		res = 'city/adventure/random_maze/huoshan/taimianzhedang.png',
		x = 216,
		layer = 'panelBottom',
		y = -716,
		scale = 2,
		theme = 1
	},
	[5] = {
		id = 5,
		res = 'city/adventure/random_maze/huoshan/taimianhou.png',
		layer = 'panelBg',
		y = 182,
		scale = 2,
		theme = 1,
		z = 3
	},
	[10] = {
		id = 10,
		res = 'city/adventure/random_maze/bingxue/beijing.png',
		layer = 'panelBg',
		scale = 4,
		theme = 2,
		z = 1
	},
	[11] = {
		id = 11,
		res = 'city/adventure/random_maze/bingxue/taimian_01.png',
		x = 2,
		layer = 'panelBg',
		anchorX = 1,
		y = 5,
		scale = 2,
		theme = 2,
		z = 2
	},
	[12] = {
		id = 12,
		res = 'city/adventure/random_maze/bingxue/taimian_02.png',
		x = 2,
		layer = 'panelBg',
		anchorX = 0,
		y = 5,
		scale = 2,
		theme = 2,
		z = 2
	},
	[13] = {
		id = 13,
		res = 'city/adventure/random_maze/bingxue/taimianzhedang.png',
		x = -48,
		layer = 'panelBottom',
		y = -664,
		scale = 2,
		theme = 2
	},
	[14] = {
		id = 14,
		res = 'city/adventure/random_maze/bingxue/taimianhou.png',
		layer = 'panelBg',
		y = 182,
		scale = 2,
		theme = 2,
		z = 3
	},
	[20] = {
		id = 20,
		res = 'city/adventure/random_maze/youming/beijing.png',
		layer = 'panelBg',
		scale = 4,
		theme = 3,
		z = 1
	},
	[21] = {
		id = 21,
		res = 'city/adventure/random_maze/youming/taimian_01.png',
		x = 2,
		layer = 'panelBg',
		anchorX = 1,
		y = 5,
		scale = 2,
		theme = 3,
		z = 2
	},
	[22] = {
		id = 22,
		res = 'city/adventure/random_maze/youming/taimian_02.png',
		x = 2,
		layer = 'panelBg',
		anchorX = 0,
		y = 5,
		scale = 2,
		theme = 3,
		z = 2
	},
	[23] = {
		id = 23,
		res = 'city/adventure/random_maze/youming/taimianzhedang.png',
		x = 30,
		layer = 'panelBottom',
		y = -730,
		scale = 2,
		theme = 3
	},
	[30] = {
		id = 30,
		res = 'city/adventure/random_maze/liekong/beijing.png',
		layer = 'panelBg',
		scale = 4,
		theme = 4,
		z = 1
	},
	[31] = {
		id = 31,
		res = 'city/adventure/random_maze/liekong/taimian_01.png',
		x = 2,
		layer = 'panelBg',
		anchorX = 1,
		y = 5,
		scale = 2,
		theme = 4,
		z = 2
	},
	[32] = {
		id = 32,
		res = 'city/adventure/random_maze/liekong/taimian_02.png',
		x = 2,
		layer = 'panelBg',
		anchorX = 0,
		y = 5,
		scale = 2,
		theme = 4,
		z = 2
	},
	[33] = {
		id = 33,
		res = 'city/adventure/random_maze/liekong/taimianzhedang.png',
		x = -90,
		layer = 'panelBottom',
		y = -768,
		scale = 2,
		theme = 4
	},
	__size = 18,
	__default = {
		__index = {
			anchorY = 0.5,
			res = '',
			x = 0,
			layer = '',
			anchorX = 0.5,
			y = 0,
			scale = 1
		}
	}
}
return csv.random_maze.decorate