--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[3] = {__size = 0}, 
	[4] = {1, 2, 3}, 
	[5] = {['height'] = 2880, ['width'] = 6224, __size = 2}, 
	[9] = {4, 5, 6}, 
	[11] = {['value'] = 1, __size = 1}, __size = 6}
local __data_t__attrFix = {
	["default"] = __predefine_t__[3]
}
local __data_t__descParams = {
	["default"] = __predefine_t__[3]
}
local __data_t__cardNatures = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4],
	[2] = __predefine_t__[9]
}
local __data_t__map = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4],
	[2] = __predefine_t__[9]
}
local __data_t__sceneSize = {
	[1] = __predefine_t__[5],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[5],
	[4] = __predefine_t__[5]
}
local __data_t__cardParams = {
	["default"] = __predefine_t__[3],
	[3] = __predefine_t__[11],
	[2] = __predefine_t__[11],
	[5] = __predefine_t__[11],
	[4] = __predefine_t__[11]
}
local __data_t__skillIDs = {
	["default"] = __predefine_t__[3]
}

csv['random_maze']['theme'] = {
	[1] = {
		id = 1,
		desc = '每{move}次移动后触发一次，火山岩将自动触发一处未激活事件格，将事件格转变为烧血格，移动到当前位置扣除血量',
		effectSpine = 'random_maze/yjpy.skel',
		weight = 100,
		title = '龟裂爆焰',
		cardDesc = '%s精灵基础六维度属性提升50%%',
		map = __data_t__map[1],
		-- {1, 2, 3}
		sceneSize = __data_t__sceneSize[1],
		-- {['height'] = 2880, ['width'] = 6224, __size = 2}
		descParams = {['cardHp'] = -0.2, ['move'] = 4, __size = 2},
		cardNatures = __data_t__cardNatures[1],
		-- {1, 2, 3}
		cardParams = {['value'] = 0.5, __size = 1},
		attrFix = {[10] = '50%', [13] = '50%', [1] = '50%', [7] = '50%', [9] = '50%', [8] = '50%', __size = 6}
	},
	[2] = {
		id = 2,
		desc = '每{move}次移动后触发一次，全场降临暴风雪，未进入保暖区将被冰冻，冰冻需要扣除1点行动力后解冻',
		effectSpine = 'random_maze/ldbx.skel',
		weight = 100,
		title = '极寒凛冬',
		cardDesc = '每携带1只%s精灵行动力+%s',
		map = __data_t__map[2],
		-- {4, 5, 6}
		sceneSize = __data_t__sceneSize[2],
		-- {['height'] = 2880, ['width'] = 6224, __size = 2}
		descParams = {['move'] = 6, ['moveAction'] = -1, __size = 2},
		cardNatures = __data_t__cardNatures[2],
		-- {4, 5, 6}
		cardParams = __data_t__cardParams[2]
		-- {['value'] = 1, __size = 1}
	},
	[3] = {
		id = 3,
		desc = '每{move}次移动触发一次，将对全部精灵进行血量扣除，扣除值根据累计挑战胜利的简单，困难，地狱对手事件数量决定(挑战失败和避战不计入)',
		effectSpine = 'random_maze/yuanlingguizhou.skel',
		weight = 100,
		title = '幽冥鬼咒',
		cardDesc = '携带的%s精灵体力+%s(双属性都满足也仅加1点)',
		map = {7, 8, 9},
		sceneSize = __data_t__sceneSize[3],
		-- {['height'] = 2880, ['width'] = 6224, __size = 2}
		descParams = {['battleHard'] = 0.005, ['battleHell'] = 0.005, ['move'] = 8, ['battleNormal'] = 0.005, __size = 4},
		cardNatures = {11, 14, 16},
		cardParams = __data_t__cardParams[3]
		-- {['value'] = 1, __size = 1}
	},
	[4] = {
		id = 4,
		desc = '每{move}次移动后触发一次，第{warnMove}次移动后将出现空风暴预警(预警风暴的吹第{move}次移动后触发风暴，玩家需躲避在障碍物后方，否则会被风暴吹{moveNumber}格',
		effectSpine = 'random_maze/kuangfengsinue.skel',
		weight = 100,
		title = '狂风冽空',
		cardDesc = '携带的%s精灵体力+%s(双属性都满足也仅加1点)',
		map = {10, 11, 12},
		sceneSize = __data_t__sceneSize[4],
		-- {['height'] = 2880, ['width'] = 6224, __size = 2}
		descParams = {['move'] = 8, ['moveNumber'] = 4, ['warnMove'] = 4, __size = 3},
		cardNatures = {10, 15, 18},
		cardParams = __data_t__cardParams[4]
		-- {['value'] = 1, __size = 1}
	},
	[5] = {
		id = 5,
		desc = '负重前行，玩家每次扣除的行动力+1，若本次跳过战斗，则返还{skipBattleMoveAction}点行动力',
		moveAction = 10,
		title = '动能',
		cardDesc = '每携带一只%s精灵，可跳过战斗的次数+%s(后续入队的三种属性精灵不计入)',
		descParams = {['moveAction'] = -1, ['skipBattleMoveAction'] = 1, __size = 2},
		cardNatures = {4, 5, 8},
		cardParams = __data_t__cardParams[5]
		-- {['value'] = 1, __size = 1}
	},
	[6] = {
		id = 6,
		desc = '每{move}次移动后触发一次，任意一行/一竖将生成荆棘壁垒，荆棘壁垒持续{times}次行动后消失，生成期间无法经过荆棘壁垒',
		title = '深林',
		cardDesc = '携带5/10只%s精灵，在玩法内获得的见闻值提升2%%/5%%',
		descParams = {['move'] = 5, ['times'] = 2, __size = 2},
		cardNatures = {4, 5, 7},
		cardParams = {[10] = 0.05, [5] = 0.02, __size = 2}
	},
	__size = 6,
	__default = {
		__index = {
			desc = '',
			moveAction = 0,
			effectSpine = '',
			weight = 0,
			title = '',
			cardDesc = '',
			sceneScale = 1,
			map = __data_t__map["default"]	--[[ {}]],
			sceneSize = {['height'] = 2880, ['width'] = 6224, __size = 2},
			descParams = __data_t__descParams["default"]	--[[ {__size = 0}]],
			cardNatures = __data_t__cardNatures["default"]	--[[ {}]],
			cardParams = __data_t__cardParams["default"]	--[[ {__size = 0}]],
			skillIDs = __data_t__skillIDs["default"]	--[[ {__size = 0}]],
			attrFix = __data_t__attrFix["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.random_maze.theme