--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}, __size = 1}
local __data_t__award = {
	[201] = __predefine_t__[2],
	[203] = __predefine_t__[2],
	[202] = __predefine_t__[2],
	[301] = __predefine_t__[2],
	[302] = __predefine_t__[2],
	[303] = __predefine_t__[2],
	[403] = __predefine_t__[2],
	[402] = __predefine_t__[2],
	[401] = __predefine_t__[2],
	[102] = __predefine_t__[2],
	[103] = __predefine_t__[2],
	[101] = __predefine_t__[2],
	[502] = __predefine_t__[2],
	[503] = __predefine_t__[2],
	[501] = __predefine_t__[2]
}

csv['totem']['collection'] = {
	[101] = {
		id = 101,
		sort = 1,
		text = '秘境领地中激活秘符%d个',
		activeNum = 10,
		groupType = 1,
		award = __data_t__award[101]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[102] = {
		id = 102,
		sort = 2,
		text = '秘境领地中激活秘符%d个',
		activeNum = 30,
		groupType = 1,
		award = __data_t__award[102]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[103] = {
		id = 103,
		sort = 3,
		text = '秘境领地中激活秘符%d个',
		activeNum = 50,
		groupType = 1,
		award = __data_t__award[103]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[201] = {
		id = 201,
		sort = 1,
		text = '梦境世界中激活秘符%d个',
		activeNum = 10,
		groupType = 2,
		award = __data_t__award[201]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[202] = {
		id = 202,
		sort = 2,
		text = '梦境世界中激活秘符%d个',
		activeNum = 30,
		groupType = 2,
		award = __data_t__award[202]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[203] = {
		id = 203,
		sort = 3,
		text = '梦境世界中激活秘符%d个',
		activeNum = 50,
		groupType = 2,
		award = __data_t__award[203]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[301] = {
		id = 301,
		sort = 1,
		text = '神秘力量中激活秘符%d个',
		activeNum = 10,
		groupType = 3,
		award = __data_t__award[301]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[302] = {
		id = 302,
		sort = 2,
		text = '神秘力量中激活秘符%d个',
		activeNum = 30,
		groupType = 3,
		award = __data_t__award[302]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[303] = {
		id = 303,
		sort = 3,
		text = '神秘力量中激活秘符%d个',
		activeNum = 50,
		groupType = 3,
		award = __data_t__award[303]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[401] = {
		id = 401,
		sort = 1,
		text = '自然之力中激活秘符%d个',
		activeNum = 10,
		groupType = 4,
		award = __data_t__award[401]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[402] = {
		id = 402,
		sort = 2,
		text = '自然之力中激活秘符%d个',
		activeNum = 30,
		groupType = 4,
		award = __data_t__award[402]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[403] = {
		id = 403,
		sort = 3,
		text = '自然之力中激活秘符%d个',
		activeNum = 50,
		groupType = 4,
		award = __data_t__award[403]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[501] = {
		id = 501,
		sort = 1,
		text = '山南海北中激活秘符%d个',
		activeNum = 10,
		groupType = 5,
		award = __data_t__award[501]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[502] = {
		id = 502,
		sort = 2,
		text = '山南海北中激活秘符%d个',
		activeNum = 30,
		groupType = 5,
		award = __data_t__award[502]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	[503] = {
		id = 503,
		sort = 3,
		text = '山南海北中激活秘符%d个',
		activeNum = 50,
		groupType = 5,
		award = __data_t__award[503]
		-- {['gold'] = 300000, ['rmb'] = 100, ['coin17'] = 100, __size = 3}
	},
	__size = 15,
	__default = {
		__index = {
			sort = 0,
			text = '',
			activeNum = 0,
			groupType = 0,
			award = {__size = 0}
		}
	}
}
return csv.totem.collection