--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, __size = 1}
local __data_t__validRarity = {
	["default"] = __predefine_t__[1]
}
local __data_t__validSpecial = {
	["default"] = __predefine_t__[1]
}
local __data_t__skillIDs = {
	["default"] = __predefine_t__[1]
}
local __data_t__validNature = {
	["default"] = __predefine_t__[1]
}

csv['cross']['circus']['theme'] = {
	[1] = {
		id = 1,
		name = '无垠灼枫',
		skillIDs = {84001, 84002}
	},
	[2] = {
		id = 2,
		name = '遁影幽怨',
		skillIDs = {84003, 84004}
	},
	[3] = {
		id = 3,
		name = '闪断绵雨',
		skillIDs = {84005, 84006}
	},
	[4] = {
		id = 4,
		name = '尘沙坠石',
		skillIDs = {84007, 84008}
	},
	[5] = {
		id = 5,
		name = '颤锻寒魂',
		skillIDs = {84009, 84010}
	},
	[6] = {
		id = 6,
		weight = 0,
		name = '奇念幻灵',
		skillIDs = {84011, 84012}
	},
	[7] = {
		id = 7,
		weight = 0,
		name = '凛空瞰望',
		skillIDs = {84013, 84014}
	},
	[8] = {
		id = 8,
		weight = 0,
		name = '无华霸劲',
		skillIDs = {84015, 84016}
	},
	[9] = {
		id = 9,
		weight = 0,
		name = '蛊毒疫瘴',
		skillIDs = {84017, 84018}
	},
	[10] = {
		id = 10,
		desc = '分段起伏的乐谱，紊乱的乐章--同一场比赛中，精灵分成三组上阵，每一组分别为1只2只3只，一方精灵阵亡后换下一组，一方已经获得两次胜利后对战结束',
		weight = 0,
		type = 2,
		name = '分节段奏',
		scene = 'csv.stage.ranks',
		troopNum = 3,
		deployType = 5,
		validSpecial = {{['troopMax'] = 1, __size = 1}, {['troopMax'] = 2, __size = 1}, {['troopMax'] = 3, __size = 1}}
	},
	[11] = {
		id = 11,
		desc = '悦居高位的乐谱，震撼的乐章--队伍仅允许上阵史诗或神话精灵，没有其余限制',
		type = 2,
		name = '诸神之战',
		scene = 'csv.stage.ranks',
		validRarity = {{[6] = {{4, 5}}, __size = 1}}
	},
	[12] = {
		id = 12,
		desc = '复合杂糅的乐谱，调和的乐章--队伍仅允许上阵至少4只双属性精灵，没有其余限制',
		type = 2,
		name = '属性混奏',
		scene = 'csv.stage.ranks',
		validSpecial = {{['twin'] = 4, __size = 1}}
	},
	[13] = {
		id = 13,
		desc = '规律严谨的乐谱，秩序的乐章--对于属性的有严苛的挑剔，需上阵2只冰系或龙系的精灵，另外还需上阵1只水系的精灵',
		type = 2,
		name = '属性分奏',
		scene = 'csv.stage.ranks',
		validNature = {{{{3}}, {{6, 15}}}}
	},
	[14] = {
		id = 14,
		desc = '规律严谨的乐谱，秩序的乐章--对于属性的有严苛的挑剔，需上阵3只虫系或妖精系的精灵，另外还需上阵2只火系或草系的精灵',
		weight = 0,
		type = 2,
		name = '属性分奏',
		scene = 'csv.stage.ranks',
		validNature = {{[1] = {{2, 4}}, [3] = {{12, 18}}, __size = 2}}
	},
	[15] = {
		id = 15,
		desc = '单一不染的乐谱，柔和的乐章--队伍仅允许上阵单属性精灵，没有其余限制',
		type = 2,
		name = '属性单奏',
		scene = 'csv.stage.ranks',
		validSpecial = {{['onlySingle'] = true, ['single'] = 6, __size = 2}}
	},
	[16] = {
		id = 16,
		type = 3,
		name = '渐近的死亡',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84101}
	},
	[17] = {
		id = 17,
		type = 3,
		name = '不灭的意志',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84102}
	},
	[18] = {
		id = 18,
		type = 3,
		name = '刺痛的枷锁',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84103}
	},
	[19] = {
		id = 19,
		type = 3,
		name = '浴血的希冀',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84104}
	},
	[20] = {
		id = 20,
		type = 3,
		name = '无尽的拳影',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84105}
	},
	[21] = {
		id = 21,
		weight = 0,
		type = 3,
		name = '戏弄的欢愉',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84106}
	},
	[22] = {
		id = 22,
		weight = 0,
		type = 3,
		name = '堕落的审判',
		scene = 'csv.stage.acrobatics',
		skillIDs = {84107}
	},
	__size = 22,
	__default = {
		__index = {
			desc = '',
			weight = 100,
			type = 1,
			name = '',
			scene = 'csv.stage.element',
			troopNum = 1,
			deployType = 1,
			skillIDs = __data_t__skillIDs["default"]	--[[ {}]],
			validRarity = __data_t__validRarity["default"]	--[[ {}]],
			validNature = __data_t__validNature["default"]	--[[ {}]],
			validSpecial = __data_t__validSpecial["default"]	--[[ {}]]
		}
	}
}
return csv.cross.circus.theme