--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[3] = {{1, 72, {[6005] = 1, __size = 1}}, {73, 150, {[6007] = 1, __size = 1}}}, 
	[4] = {{1, 72, {[6006] = 1, __size = 1}}, {73, 150, {[6008] = 1, __size = 1}}}, __size = 3}
local __data_t__winAward = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[3]
}
local __data_t__winAward_en = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[3]
}
local __data_t__winAward_tw = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[3]
}
local __data_t__failAward = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4]
}
local __data_t__failAward_en = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4]
}
local __data_t__winAward_kr = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[3]
}
local __data_t__failAward_kr = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4]
}
local __data_t__failAward_tw = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4]
}

csv['craft']['base'] = {
	[1] = {
		id = 1,
		numMax = 3000,
		winAward = __data_t__winAward[1],
		-- {{1, 72, {[6005] = 1, __size = 1}}, {73, 150, {[6007] = 1, __size = 1}}}
		winAward_kr = __data_t__winAward_kr[1],
		-- {{1, 72, {[6005] = 1, __size = 1}}, {73, 150, {[6007] = 1, __size = 1}}}
		winAward_en = __data_t__winAward_en[1],
		-- {{1, 72, {[6005] = 1, __size = 1}}, {73, 150, {[6007] = 1, __size = 1}}}
		winAward_tw = __data_t__winAward_tw[1],
		-- {{1, 72, {[6005] = 1, __size = 1}}, {73, 150, {[6007] = 1, __size = 1}}}
		failAward = __data_t__failAward[1],
		-- {{1, 72, {[6006] = 1, __size = 1}}, {73, 150, {[6008] = 1, __size = 1}}}
		failAward_kr = __data_t__failAward_kr[1],
		-- {{1, 72, {[6006] = 1, __size = 1}}, {73, 150, {[6008] = 1, __size = 1}}}
		failAward_en = __data_t__failAward_en[1],
		-- {{1, 72, {[6006] = 1, __size = 1}}, {73, 150, {[6008] = 1, __size = 1}}}
		failAward_tw = __data_t__failAward_tw[1],
		-- {{1, 72, {[6006] = 1, __size = 1}}, {73, 150, {[6008] = 1, __size = 1}}}
		servOpenDays = 9,
		autoSignVIP = 3,
		minBetRate = 2,
		betRateFix = 1,
		maxBetWin = 1000000,
		damageScoreRatio = 500
	},
	__size = 1,
	__default = {
		__index = {
			winAward = __data_t__winAward["default"]	--[[ {}]],
			winAward_kr = __data_t__winAward_kr["default"]	--[[ {}]],
			winAward_en = __data_t__winAward_en["default"]	--[[ {}]],
			winAward_tw = __data_t__winAward_tw["default"]	--[[ {}]],
			failAward = __data_t__failAward["default"]	--[[ {}]],
			failAward_kr = __data_t__failAward_kr["default"]	--[[ {}]],
			failAward_en = __data_t__failAward_en["default"]	--[[ {}]],
			failAward_tw = __data_t__failAward_tw["default"]	--[[ {}]],
			openWeekday = {1, 2, 3, 4, 5, 6, 7},
			damageScoreRatio = 1000
		}
	}
}
return csv.craft.base