slot0 = {
	[5] = {
		[1.0] = 0.1,
		__size = 1
	},
	[16] = {
		__size = 2,
		[8.0] = "20%",
		[7.0] = "20%"
	},
	[21] = {
		[9.0] = "60%",
		[10.0] = "60%",
		__size = 3,
		[23.0] = 2000
	},
	[28] = {
		[1.0] = "50%",
		__size = 1
	},
	[31] = {
		"60%",
		__size = 3,
		[22.0] = 3000,
		[23.0] = 3000
	},
	[33] = {
		0,
		1,
		0
	},
	[35] = {
		[9.0] = "40%",
		[10.0] = "40%",
		__size = 3,
		[23.0] = 1500
	},
	[37] = {
		__size = 3,
		[22.0] = 2000,
		[8.0] = "20%",
		[7.0] = "20%"
	},
	[39] = {
		1,
		1
	},
	[40] = {
		__size = 3,
		[13.0] = "20%",
		[8.0] = "10%",
		[7.0] = "10%"
	},
	[42] = {
		1,
		1,
		0
	},
	[48] = {
		"20%",
		nil,
		nil,
		nil,
		nil,
		nil,
		"10%",
		"10%",
		"30%",
		"30%",
		nil,
		nil,
		"10%",
		__size = 6
	},
	[57] = {
		__size = 3,
		[13.0] = "15%",
		[8.0] = "10%",
		[7.0] = "10%"
	},
	[59] = {
		309
	},
	[60] = {
		[9.0] = "40%",
		[10.0] = "40%",
		__size = 3,
		[23.0] = 1200
	},
	[63] = {
		313
	},
	[67] = {
		303,
		306
	},
	[71] = {
		305,
		308
	},
	[81] = {
		__size = 3,
		[22.0] = 1200,
		[8.0] = "12%",
		[7.0] = "12%"
	},
	[115] = {
		1,
		1,
		0,
		0,
		0
	}
}
csv.cross.union_adventure.map = {
	{
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		radius = 300,
		id = 1,
		type = 1,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		resScale = 2,
		scene = -1,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		oneMinuteAddHP = 0.65,
		x = -1700,
		adjoin = {
			3,
			4,
			5
		}
	},
	{
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		radius = 300,
		id = 2,
		type = 2,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		resScale = 2,
		scene = -1,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		oneMinuteAddHP = 0.65,
		x = 1700,
		adjoin = {
			6,
			7,
			8
		}
	},
	{
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		type = 3,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		resScale = 1.8,
		scene = -1,
		oneMinuteAddResource = 30,
		y = 550,
		id = 3,
		x = -800,
		adjoin = {
			1,
			4,
			6
		},
		adjoinSpeedUp = {
			6
		}
	},
	{
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		type = 3,
		enemyOccupyTimeBuff = 0.5,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		resScale = 1.8,
		scene = -1,
		oneMinuteAddResource = 50,
		id = 4,
		oneMinuteAddResourceSpecial = 80,
		x = -800,
		attrFix = slot0[5],
		teamAttrFix = slot0[5],
		adjoin = {
			1,
			3,
			5,
			7
		}
	},
	{
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		type = 3,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		resScale = 1.8,
		scene = -1,
		oneMinuteAddResource = 70,
		y = -550,
		id = 5,
		x = -800,
		adjoin = {
			1,
			4,
			8
		}
	},
	{
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		type = 3,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		resScale = 1.8,
		scene = -1,
		oneMinuteAddResource = 30,
		y = 550,
		id = 6,
		x = 800,
		adjoin = {
			2,
			7,
			3
		}
	},
	{
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		type = 3,
		enemyOccupyTimeBuff = 0.5,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		resScale = 1.8,
		scene = -1,
		oneMinuteAddResource = 50,
		id = 7,
		oneMinuteAddResourceSpecial = 80,
		x = 800,
		attrFix = slot0[5],
		teamAttrFix = slot0[5],
		adjoin = {
			2,
			6,
			8,
			4
		}
	},
	{
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		type = 3,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		resScale = 1.8,
		scene = -1,
		oneMinuteAddResource = 70,
		y = -550,
		id = 8,
		x = 800,
		adjoin = {
			2,
			7,
			5
		},
		adjoinSpeedUp = {
			5
		}
	},
	__size = 92,
	[101] = {
		dy = 80,
		name = "Cabo Poco",
		radius = 160,
		type = 1,
		dx = -150,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		id = 101,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		oneMinuteAddHP = 0.65,
		x = -3000,
		adjoin = {
			104,
			112,
			113
		}
	},
	[102] = {
		dy = 80,
		name = "Porto Marinada",
		radius = 160,
		type = 2,
		dx = 150,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		id = 102,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		oneMinuteAddHP = 0.65,
		x = 3000,
		adjoin = {
			107,
			110,
			111
		}
	},
	[103] = {
		dy = 55,
		radius = 130,
		name = "Crystal Shrine",
		type = 3,
		desc = "Special stronghold: After this stronghold is occupied, it will produce a high amount of resources for the occupying party.",
		buffRes = "city/union/cross_union_adventure/map/img_ziyuanup.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		resScale = 2.3,
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 103,
		oneMinuteAddResourceSpecial = 160,
		attrFix = {
			__size = 2,
			[13.0] = "20%",
			[22.0] = 2000
		},
		adjoin = {
			105,
			106,
			108,
			109
		}
	},
	[104] = {
		dy = 55,
		radius = 100,
		name = "Poco Path",
		type = 3,
		oneMinuteAddResource = 30,
		buffRes = "city/union/cross_union_adventure/map/img_shuanggong.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 104,
		x = -2050,
		attrFix = slot0[16],
		adjoin = {
			101,
			105
		}
	},
	[105] = {
		dy = 55,
		radius = 100,
		name = "Glaseado Mountain",
		type = 3,
		oneMinuteAddResource = 50,
		buffRes = "city/union/cross_union_adventure/map/img_shuanggong.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 105,
		x = -1090,
		attrFix = slot0[16],
		adjoin = {
			104,
			103,
			108,
			109
		}
	},
	[106] = {
		dy = 55,
		radius = 100,
		name = "Socarrat Trail",
		type = 3,
		oneMinuteAddResource = 70,
		buffRes = "city/union/cross_union_adventure/map/img_shuanggong.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 106,
		x = 1090,
		attrFix = slot0[16],
		adjoin = {
			107,
			103,
			108,
			109
		}
	},
	[107] = {
		dy = 55,
		radius = 100,
		name = "Dalizapa Passage",
		type = 3,
		oneMinuteAddResource = 30,
		buffRes = "city/union/cross_union_adventure/map/img_shuanggong.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 107,
		x = 2050,
		attrFix = slot0[16],
		adjoin = {
			106,
			102
		}
	},
	[108] = {
		dy = 55,
		radius = 100,
		name = "Alfornada Cavern",
		type = 3,
		oneMinuteAddResource = 50,
		buffRes = "city/union/cross_union_adventure/map/img_shuangfang.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		y = 975,
		id = 108,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[21],
		adjoin = {
			112,
			110,
			103,
			106,
			105
		}
	},
	[109] = {
		dy = 55,
		radius = 100,
		name = "Tagtree Thicket Park",
		type = 3,
		oneMinuteAddResource = 70,
		buffRes = "city/union/cross_union_adventure/map/img_shuangfang.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		y = -975,
		id = 109,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[21],
		adjoin = {
			113,
			111,
			103,
			105,
			106
		}
	},
	[110] = {
		oneMinuteAddResource = 20,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Inlet Grotto",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_huifu.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 975,
		id = 110,
		x = 2050,
		adjoin = {
			114,
			102,
			108
		}
	},
	[111] = {
		oneMinuteAddResource = 70,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Grand Olive Orchard",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_zhanlingshijian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -975,
		id = 111,
		x = 2050,
		adjoin = {
			115,
			102,
			109
		}
	},
	[112] = {
		oneMinuteAddResource = 70,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Colonnade Hollow",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_zhanlingshijian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 975,
		id = 112,
		x = -2050,
		adjoin = {
			101,
			114,
			108
		}
	},
	[113] = {
		oneMinuteAddResource = 20,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Gracia Stones",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_huifu.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -975,
		id = 113,
		x = -2050,
		adjoin = {
			101,
			115,
			109
		}
	},
	[114] = {
		dy = 55,
		radius = 100,
		name = "Grasswither Shrine",
		type = 3,
		oneMinuteAddResource = 30,
		buffRes = "city/union/cross_union_adventure/map/img_huifu.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the maximum HP of the current team's Pokémons will be increased.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		y = 1950,
		id = 114,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[28],
		adjoin = {
			112,
			110
		}
	},
	[115] = {
		dy = 55,
		radius = 100,
		name = "Icerend Shrine",
		type = 3,
		oneMinuteAddResource = 30,
		buffRes = "city/union/cross_union_adventure/map/img_huifu.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the maximum HP of the current team's Pokémons will be increased.",
		scene = 1,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		resScale = 1.8,
		y = -1950,
		id = 115,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[28],
		adjoin = {
			113,
			111
		}
	},
	[201] = {
		resScale = 2,
		radius = 160,
		type = 1,
		name = "Mesagoza",
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		oneMinuteAddHP = 0.65,
		dy = 80,
		dx = -100,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		scene = 2,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		id = 201,
		x = -3000,
		attrFix = slot0[31],
		adjoin = {
			203,
			204,
			211
		},
		adjoinZ = slot0[33]
	},
	[202] = {
		resScale = 2,
		radius = 160,
		type = 2,
		name = "Levincia",
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		oneMinuteAddHP = 0.65,
		dy = 80,
		dx = 100,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		scene = 2,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		id = 202,
		x = 3000,
		attrFix = slot0[31],
		adjoin = {
			212,
			207,
			208
		},
		adjoinZ = slot0[33]
	},
	[203] = {
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Leaking Tower of Paldea",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_shuangfang.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		oneMinuteAddResource = 40,
		y = 700,
		id = 203,
		x = -1850,
		attrFix = slot0[35],
		adjoin = {
			201,
			209,
			210
		},
		adjoinZ = slot0[33]
	},
	[204] = {
		oneMinuteAddResource = 50,
		name = "Grasswither Shrine",
		resScale = 1.8,
		type = 3,
		radius = 100,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_zhanlingshijian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		id = 204,
		x = -1500,
		attrFix = slot0[37],
		adjoin = {
			201,
			210
		},
		adjoinZ = slot0[39]
	},
	[205] = {
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Icerend Shrine",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_shuangfang.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		oneMinuteAddResource = 40,
		y = -1150,
		id = 205,
		x = -700,
		attrFix = slot0[40],
		adjoin = {
			211,
			213,
			210
		},
		adjoinZ = slot0[42]
	},
	[206] = {
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Zero Zone Entrance",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_shuanggong.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		oneMinuteAddResource = 70,
		y = 1150,
		id = 206,
		x = 700,
		attrFix = slot0[40],
		adjoin = {
			209,
			212,
			210
		},
		adjoinZ = slot0[42]
	},
	[207] = {
		oneMinuteAddResource = 50,
		name = "Groundblight Shrine",
		resScale = 1.8,
		type = 3,
		radius = 100,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_zhanlingshijian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		id = 207,
		x = 1500,
		attrFix = slot0[37],
		adjoin = {
			202,
			210
		},
		adjoinZ = slot0[39]
	},
	[208] = {
		oneMinuteAddResource = 30,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Firescourge Shrine",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_huifu.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -700,
		id = 208,
		x = 1850,
		attrFix = slot0[35],
		adjoin = {
			202,
			210,
			213
		},
		adjoinZ = {
			0,
			0,
			1
		}
	},
	[209] = {
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Watchtower",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_shuanggong.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		oneMinuteAddResource = 70,
		y = 1150,
		id = 209,
		x = -700,
		attrFix = slot0[40],
		adjoin = {
			203,
			206,
			210
		},
		adjoinZ = slot0[42]
	},
	[210] = {
		dy = 55,
		radius = 130,
		name = "lighthouse",
		type = 3,
		resScale = 2.3,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "Special stronghold: After this stronghold is occupied, attribute bonuses will be provided to all members of the occupying party.",
		scene = 2,
		oneMinuteAddResource = 20,
		buffRes = "city/union/cross_union_adventure/map/img_quanzengyi.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 210,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		teamAttrFix = slot0[48],
		adjoin = {
			203,
			204,
			205,
			206,
			207,
			208,
			209,
			211,
			213,
			212
		},
		adjoinZ = {
			0,
			1,
			0,
			0,
			1,
			0,
			0,
			0,
			0,
			0
		}
	},
	[211] = {
		oneMinuteAddResource = 30,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Paldea huge house",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_huifu.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -700,
		id = 211,
		x = -1850,
		attrFix = slot0[35],
		adjoin = {
			201,
			205,
			210
		},
		adjoinZ = slot0[33]
	},
	[212] = {
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Lighthouse Institute",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_shuangfang.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		oneMinuteAddResource = 40,
		y = 700,
		id = 212,
		x = 1850,
		attrFix = slot0[35],
		adjoin = {
			202,
			206,
			210
		},
		adjoinZ = slot0[33]
	},
	[213] = {
		res = "city/union/cross_union_adventure/map/img_judian.png",
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Asado house",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		dy = 55,
		buffRes = "city/union/cross_union_adventure/map/img_shuangfang.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 2,
		oneMinuteAddResource = 40,
		y = -1150,
		id = 213,
		x = 700,
		attrFix = slot0[40],
		adjoin = {
			205,
			210,
			208
		},
		adjoinZ = {
			1,
			0,
			0
		}
	},
	[301] = {
		resScale = 2,
		name = "Cabo Poco",
		radius = 160,
		type = 1,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		oneMinuteAddHP = 0.65,
		dy = 80,
		dx = -150,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		y = -800,
		id = 301,
		x = -3000,
		attrFix = slot0[31],
		adjoin = {
			304,
			303,
			305
		}
	},
	[302] = {
		resScale = 2,
		name = "Porto Marinada",
		radius = 160,
		type = 2,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		oneMinuteAddHP = 0.65,
		dy = 80,
		dx = 150,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		y = 800,
		id = 302,
		x = 3000,
		attrFix = slot0[31],
		adjoin = {
			307,
			306,
			308
		}
	},
	[303] = {
		oneMinuteAddResource = 40,
		resScale = 1.8,
		type = 3,
		radius = 100,
		name = "Crystal Shrine",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 800,
		id = 303,
		x = -1500,
		attrFix = slot0[57],
		adjoin = {
			301,
			309
		},
		adjoinSpeedUp = slot0[59]
	},
	[304] = {
		dy = 55,
		radius = 100,
		name = "Poco Path",
		type = 3,
		resScale = 1.8,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 3,
		oneMinuteAddResource = 50,
		id = 304,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		enemyOccupyTimeBuff = 0.5,
		x = -1500,
		attrFix = slot0[60],
		adjoin = {
			301,
			310,
			311
		}
	},
	[305] = {
		oneMinuteAddResource = 40,
		resScale = 1.8,
		type = 3,
		radius = 100,
		name = "Glaseado Mountain",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -800,
		id = 305,
		x = -1500,
		attrFix = slot0[21],
		adjoin = {
			311,
			313,
			301,
			312
		},
		adjoinSpeedUp = slot0[63]
	},
	[306] = {
		oneMinuteAddResource = 70,
		resScale = 1.8,
		type = 3,
		radius = 100,
		name = "Socarrat Trail",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 800,
		id = 306,
		x = 1500,
		attrFix = slot0[21],
		adjoin = {
			311,
			309,
			310,
			302
		},
		adjoinSpeedUp = slot0[59]
	},
	[307] = {
		dy = 55,
		radius = 100,
		name = "Dalizapa Passage",
		type = 3,
		resScale = 1.8,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 3,
		oneMinuteAddResource = 50,
		id = 307,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		enemyOccupyTimeBuff = 0.5,
		x = 1500,
		attrFix = slot0[60],
		adjoin = {
			302,
			312,
			311
		}
	},
	[308] = {
		oneMinuteAddResource = 30,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Alfornada Cavern",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -800,
		id = 308,
		x = 1500,
		attrFix = slot0[57],
		adjoin = {
			302,
			313
		},
		adjoinSpeedUp = slot0[63]
	},
	[309] = {
		dy = 55,
		radius = 100,
		name = "Tagtree Thicket Park",
		type = 3,
		resScale = 1.8,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 3,
		oneMinuteAddResource = 70,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 1600,
		id = 309,
		attrFix = slot0[40],
		adjoin = slot0[67],
		adjoinSpeedUp = slot0[67]
	},
	[310] = {
		dy = 55,
		radius = 100,
		name = "Inlet Grotto",
		type = 3,
		resScale = 1.8,
		id = 310,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		scene = 3,
		oneMinuteAddResource = 20,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 800,
		oneMinuteAddHP = 0.65,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[37],
		adjoin = {
			304,
			306,
			311
		}
	},
	[311] = {
		dy = 55,
		radius = 130,
		name = "Grand Olive Orchard",
		type = 3,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "Special stronghold: After this stronghold is occupied, attribute bonuses will be provided to all members of the occupying party.",
		scene = 3,
		oneMinuteAddResource = 30,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		resScale = 2.3,
		id = 311,
		teamAttrFix = slot0[48],
		adjoin = {
			312,
			310,
			305,
			306,
			304,
			307
		}
	},
	[312] = {
		dy = 55,
		radius = 100,
		name = "Colonnade Hollow",
		type = 3,
		oneMinuteAddResource = 40,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 3,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -800,
		id = 312,
		adjoin = {
			311,
			305,
			307
		}
	},
	[313] = {
		dy = 55,
		radius = 100,
		name = "Gracia Stones",
		type = 3,
		resScale = 1.8,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 3,
		oneMinuteAddResource = 40,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -1600,
		id = 313,
		attrFix = slot0[40],
		adjoin = slot0[71],
		adjoinSpeedUp = slot0[71]
	},
	[401] = {
		dy = 80,
		name = "Cabo Poco",
		radius = 160,
		type = 1,
		dx = -200,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		id = 401,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		oneMinuteAddHP = 0.65,
		x = -3000,
		adjoin = {
			412,
			413
		}
	},
	[402] = {
		dy = 80,
		name = "Porto Marinada",
		radius = 160,
		type = 2,
		dx = 200,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		id = 402,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		oneMinuteAddHP = 0.65,
		x = 3000,
		adjoin = {
			410,
			411
		}
	},
	[403] = {
		dy = 55,
		radius = 130,
		name = "Crystal Shrine",
		type = 3,
		desc = "Special stronghold: After this stronghold is occupied, it will produce a high amount of resources for the occupying party.",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		resScale = 2.3,
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		id = 403,
		oneMinuteAddResourceSpecial = 160,
		attrFix = slot0[31],
		adjoin = {
			405,
			408,
			406,
			409
		}
	},
	[404] = {
		dy = 55,
		name = "Poco Path",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 1950,
		id = 404,
		x = -1025,
		adjoin = {
			412,
			408
		}
	},
	[405] = {
		dy = 55,
		radius = 100,
		name = "Glaseado Mountain",
		type = 3,
		oneMinuteAddResource = 50,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 405,
		x = -1090,
		attrFix = slot0[60],
		adjoin = {
			412,
			413,
			403,
			408,
			409
		}
	},
	[406] = {
		dy = 55,
		radius = 100,
		name = "Socarrat Trail",
		type = 3,
		oneMinuteAddResource = 70,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 406,
		x = 1090,
		attrFix = slot0[60],
		adjoin = {
			410,
			411,
			403,
			408,
			409
		}
	},
	[407] = {
		dy = 55,
		name = "Dalizapa Passage",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -1950,
		id = 407,
		x = -1025,
		adjoin = {
			413,
			409
		}
	},
	[408] = {
		dy = 55,
		radius = 100,
		name = "Alfornada Cavern",
		type = 3,
		oneMinuteAddResource = 50,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 975,
		id = 408,
		attrFix = slot0[60],
		adjoin = {
			403,
			405,
			406,
			412,
			410,
			404,
			414
		}
	},
	[409] = {
		dy = 55,
		radius = 100,
		name = "Tagtree Thicket Park",
		type = 3,
		oneMinuteAddResource = 70,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -975,
		id = 409,
		attrFix = slot0[60],
		adjoin = {
			403,
			405,
			406,
			413,
			411,
			407,
			415
		}
	},
	[410] = {
		oneMinuteAddResource = 20,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Inlet Grotto",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 975,
		id = 410,
		x = 2050,
		attrFix = slot0[81],
		adjoin = {
			402,
			408,
			414,
			406
		}
	},
	[411] = {
		oneMinuteAddResource = 70,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Grand Olive Orchard",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -975,
		id = 411,
		x = 2050,
		attrFix = slot0[81],
		adjoin = {
			402,
			409,
			406,
			415
		}
	},
	[412] = {
		oneMinuteAddResource = 70,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Colonnade Hollow",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 975,
		id = 412,
		x = -2050,
		attrFix = slot0[81],
		adjoin = {
			401,
			408,
			405,
			404
		}
	},
	[413] = {
		oneMinuteAddResource = 20,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Gracia Stones",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -975,
		id = 413,
		x = -2050,
		attrFix = slot0[81],
		adjoin = {
			401,
			409,
			405,
			407
		}
	},
	[414] = {
		dy = 55,
		name = "Grasswither Shrine",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the maximum HP of the current team's Pokémons will be increased.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 1950,
		id = 414,
		x = 1025,
		adjoin = {
			408,
			410
		}
	},
	[415] = {
		dy = 55,
		name = "Icerend Shrine",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the maximum HP of the current team's Pokémons will be increased.",
		scene = 4,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -1950,
		id = 415,
		x = 1025,
		adjoin = {
			409,
			411
		}
	},
	[501] = {
		dy = 80,
		name = "Cabo Poco",
		radius = 100,
		type = 1,
		dx = -200,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		id = 501,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		oneMinuteAddHP = 0.65,
		x = -3000,
		adjoin = {
			506,
			509,
			504
		}
	},
	[502] = {
		dy = 80,
		name = "Porto Marinada",
		radius = 100,
		type = 2,
		dx = 200,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		id = 502,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		oneMinuteAddHP = 0.65,
		x = 3000,
		adjoin = {
			508,
			507,
			505
		}
	},
	[503] = {
		dy = 55,
		radius = 100,
		name = "Crystal Shrine",
		type = 3,
		desc = "Special stronghold: After this stronghold is occupied, it will produce a high amount of resources for the occupying party.",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		resScale = 2.3,
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		id = 503,
		oneMinuteAddResourceSpecial = 160,
		attrFix = slot0[31],
		adjoin = {
			504,
			506,
			510,
			509,
			505,
			507,
			511,
			508
		}
	},
	[504] = {
		dy = 55,
		radius = 100,
		name = "Poco Path",
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 504,
		x = -1500,
		adjoin = {
			506,
			509,
			501,
			503
		}
	},
	[505] = {
		dy = 55,
		radius = 100,
		name = "Glaseado Mountain",
		type = 3,
		oneMinuteAddResource = 50,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		id = 505,
		x = 1500,
		attrFix = slot0[60],
		adjoin = {
			508,
			507,
			502,
			503
		}
	},
	[506] = {
		dy = 55,
		name = "Socarrat Trail",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 70,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 900,
		id = 506,
		x = -2250,
		attrFix = slot0[60],
		adjoin = {
			501,
			504,
			503,
			512,
			510
		}
	},
	[507] = {
		dy = 55,
		name = "Dalizapa Passage",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -900,
		id = 507,
		x = 2250,
		adjoin = {
			502,
			505,
			503,
			515,
			511
		}
	},
	[508] = {
		dy = 55,
		name = "Alfornada Cavern",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 50,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 900,
		id = 508,
		x = 2250,
		attrFix = slot0[60],
		adjoin = {
			502,
			505,
			503,
			513,
			510
		}
	},
	[509] = {
		dy = 55,
		name = "Tagtree Thicket Park",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 70,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the Pokémons' double defense will be improved.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -900,
		id = 509,
		x = -2250,
		attrFix = slot0[60],
		adjoin = {
			501,
			504,
			503,
			514,
			511
		}
	},
	[510] = {
		dy = 55,
		radius = 100,
		name = "Inlet Grotto",
		type = 3,
		resScale = 1.8,
		id = 510,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		scene = 5,
		oneMinuteAddResource = 20,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 1800,
		oneMinuteAddHP = 0.65,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[81],
		adjoin = {
			512,
			513,
			506,
			508,
			503
		}
	},
	[511] = {
		dy = 55,
		radius = 130,
		name = "Grand Olive Orchard",
		type = 3,
		resScale = 1.8,
		id = 511,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		scene = 5,
		oneMinuteAddResource = 70,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = -1800,
		enemyOccupyTimeBuff = 0.5,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		attrFix = slot0[81],
		adjoin = {
			514,
			515,
			509,
			507,
			503
		}
	},
	[512] = {
		oneMinuteAddResource = 70,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Colonnade Hollow",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "During the opponent's process of robbing the stronghold, the natural time consumed by the robbing will increase.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 900,
		id = 512,
		x = -750,
		attrFix = slot0[81],
		adjoin = {
			506,
			510
		}
	},
	[513] = {
		oneMinuteAddResource = 20,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Gracia Stones",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 900,
		id = 513,
		x = 750,
		attrFix = slot0[81],
		adjoin = {
			508,
			510
		}
	},
	[514] = {
		dy = 55,
		name = "Grasswither Shrine",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the maximum HP of the current team's Pokémons will be increased.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -900,
		id = 514,
		x = -750,
		adjoin = {
			509,
			511
		}
	},
	[515] = {
		dy = 55,
		name = "Icerend Shrine",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 30,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the maximum HP of the current team's Pokémons will be increased.",
		scene = 5,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -900,
		id = 515,
		x = 750,
		adjoin = {
			507,
			511
		}
	},
	[601] = {
		dy = 80,
		name = "Mesagoza",
		radius = 160,
		type = 1,
		dx = -150,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s1.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_dabenying1.png",
		id = 601,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b1.png",
		oneMinuteAddHP = 0.65,
		x = -3000,
		attrFix = slot0[31],
		adjoin = {
			603,
			605,
			604,
			606
		}
	},
	[602] = {
		dy = 80,
		name = "Levincia",
		radius = 160,
		type = 2,
		dx = 150,
		resScale = 2,
		simpleRes = "city/union/cross_union_adventure/map/icon_dabenying_s2.png",
		desc = "When both teams of Pokémons are exhausted, the camp can provide resurrection, but resurrection will take time.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_dabenying2.png",
		id = 602,
		wholeRes = "city/union/cross_union_adventure/map/icon_dabenying_b2.png",
		oneMinuteAddHP = 0.65,
		x = 3000,
		attrFix = slot0[31],
		adjoin = {
			607,
			609,
			608,
			610
		}
	},
	[603] = {
		dy = 55,
		name = "Leaking Tower of Paldea",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 40,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 850,
		id = 603,
		x = -3000,
		attrFix = slot0[57],
		adjoin = {
			601,
			604,
			613
		}
	},
	[604] = {
		oneMinuteAddResource = 50,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Grasswither Shrine",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 850,
		id = 604,
		x = -1500,
		attrFix = slot0[60],
		adjoin = {
			601,
			611,
			613,
			603
		}
	},
	[605] = {
		dy = 55,
		name = "Icerend Shrine",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 40,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -850,
		id = 605,
		x = -3000,
		attrFix = slot0[21],
		adjoin = {
			601,
			606,
			612
		}
	},
	[606] = {
		dy = 55,
		name = "Zero Zone Entrance",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 70,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -850,
		id = 606,
		x = -1500,
		attrFix = slot0[21],
		adjoin = {
			601,
			611,
			612,
			605
		}
	},
	[607] = {
		oneMinuteAddResource = 50,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Groundblight Shrine",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		enemyOccupyTimeBuff = 0.5,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 850,
		id = 607,
		x = 3000,
		attrFix = slot0[60],
		adjoin = {
			602,
			608,
			613
		}
	},
	[608] = {
		oneMinuteAddResource = 30,
		radius = 100,
		resScale = 1.8,
		type = 3,
		name = "Firescourge Shrine",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		oneMinuteAddHP = 0.65,
		dy = 55,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		y = 850,
		id = 608,
		x = 1500,
		attrFix = slot0[57],
		adjoin = {
			602,
			611,
			613,
			607
		}
	},
	[609] = {
		dy = 55,
		name = "Watchtower",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 70,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -850,
		id = 609,
		x = 3000,
		attrFix = slot0[40],
		adjoin = {
			602,
			610,
			612
		}
	},
	[610] = {
		dy = 55,
		name = "lighthouse",
		radius = 100,
		type = 3,
		oneMinuteAddResource = 20,
		resScale = 1.8,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players stationed in the stronghold, the unexhausted Pokémons in the current team will receive life recovery.",
		scene = 6,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -850,
		id = 610,
		x = 1500,
		attrFix = slot0[37],
		adjoin = {
			602,
			611,
			612,
			609
		}
	},
	[611] = {
		dy = 55,
		radius = 130,
		name = "Paldea huge house",
		type = 3,
		resScale = 2.3,
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "Special stronghold: After this stronghold is occupied, attribute bonuses will be provided to all members of the occupying party.",
		scene = 6,
		oneMinuteAddResource = 30,
		id = 611,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		oneMinuteAddHP = 0.65,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		teamAttrFix = slot0[48],
		adjoin = {
			604,
			606,
			608,
			610,
			613,
			612
		}
	},
	[612] = {
		dy = 55,
		radius = 100,
		name = "Lighthouse Institute",
		type = 3,
		resScale = 1.8,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 6,
		oneMinuteAddResource = 40,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = -1700,
		id = 612,
		adjoin = {
			605,
			609,
			611,
			606,
			610
		},
		adjoinZ = slot0[115]
	},
	[613] = {
		dy = 55,
		radius = 100,
		name = "Asado house",
		type = 3,
		resScale = 1.8,
		res = "city/union/cross_union_adventure/map/img_judian.png",
		simpleRes = "city/union/cross_union_adventure/map/icon_judian_s.png",
		desc = "For players garrisoned in the stronghold, the double attack of the Pokémons will be improved.",
		scene = 6,
		oneMinuteAddResource = 40,
		wholeRes = "city/union/cross_union_adventure/map/icon_judian_b.png",
		y = 1700,
		id = 613,
		attrFix = slot0[40],
		adjoin = {
			603,
			607,
			611,
			608,
			604
		},
		adjoinZ = slot0[115]
	},
	__default = {
		__index = {
			oneMinuteAddResource = 0,
			radius = 0,
			type = 0,
			wholeRes = "",
			resScale = 1,
			oneMinuteAddHP = 0,
			dy = 0,
			buffRes = "",
			dx = 0,
			simpleRes = "",
			scene = 0,
			res = "",
			y = 0,
			oneMinuteAddResourceSpecial = 0,
			x = 0,
			attrFix = {
				__size = 0
			},
			teamAttrFix = {
				__size = 0
			},
			adjoin = {},
			adjoinSpeedUp = {},
			adjoinZ = {}
		}
	}
}

return csv.cross.union_adventure.map
