slot0 = {
	__size = 0
}
csv.gem.suit = {
	{
		suitName_th = "Punch",
		attrNum2 = "4%",
		suitName_en = "Punch",
		attrType1 = 7,
		attrType2 = 8,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Punch",
		id = 1,
		attrNum1 = "4%"
	},
	{
		attrNum1 = "300",
		attrNum2 = "300",
		suitName_en = "Punch",
		attrType1 = 11,
		attrType2 = 12,
		suitQuality = 2,
		suitName = "Punch",
		id = 2,
		suitName_th = "Punch"
	},
	{
		suitName_th = "Punch",
		attrNum2 = "5%",
		suitName_en = "Punch",
		attrType1 = 7,
		attrType2 = 8,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Punch",
		id = 3,
		attrNum1 = "5%"
	},
	{
		attrNum1 = "400",
		attrNum2 = "400",
		suitName_en = "Punch",
		attrType1 = 11,
		attrType2 = 12,
		suitQuality = 3,
		suitName = "Punch",
		id = 4,
		suitName_th = "Punch"
	},
	{
		suitName_th = "Punch",
		attrNum2 = "6%",
		suitName_en = "Punch",
		attrType1 = 7,
		attrType2 = 8,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Punch",
		id = 5,
		attrNum1 = "6%"
	},
	{
		attrNum1 = "500",
		attrNum2 = "500",
		suitName_en = "Punch",
		attrType1 = 11,
		attrType2 = 12,
		suitQuality = 4,
		suitName = "Punch",
		id = 6,
		suitName_th = "Punch"
	},
	{
		suitName_th = "Punch",
		attrNum2 = "9%",
		suitName_en = "Punch",
		attrType1 = 7,
		attrType2 = 8,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Punch",
		id = 7,
		attrNum1 = "9%"
	},
	{
		attrNum1 = "700",
		attrNum2 = "700",
		suitName_en = "Punch",
		attrType1 = 11,
		attrType2 = 12,
		suitQuality = 5,
		suitName = "Punch",
		id = 8,
		suitName_th = "Punch"
	},
	{
		suitName_th = "Punch",
		attrNum2 = "12%",
		suitName_en = "Punch",
		attrType1 = 7,
		attrType2 = 8,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Punch",
		id = 9,
		attrNum1 = "12%"
	},
	{
		attrNum1 = "1000",
		attrNum2 = "1000",
		suitName_en = "Punch",
		attrType1 = 11,
		attrType2 = 12,
		suitQuality = 6,
		suitName = "Punch",
		id = 10,
		suitName_th = "Punch"
	},
	{
		suitName_th = "Deadly",
		attrNum1 = "200",
		suitName_en = "Deadly",
		attrType1 = 14,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Deadly",
		id = 11,
		suitID = 2
	},
	{
		suitName_th = "Deadly",
		suitQuality = 2,
		suitName_en = "Deadly",
		suitName = "Deadly",
		id = 12,
		attrType1 = 15,
		suitID = 2,
		attrNum1 = "300"
	},
	{
		suitName_th = "Deadly",
		attrNum1 = "300",
		suitName_en = "Deadly",
		attrType1 = 14,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Deadly",
		id = 13,
		suitID = 2
	},
	{
		suitName_th = "Deadly",
		suitQuality = 3,
		suitName_en = "Deadly",
		suitName = "Deadly",
		id = 14,
		attrType1 = 15,
		suitID = 2,
		attrNum1 = "450"
	},
	{
		suitName_th = "Deadly",
		attrNum1 = "400",
		suitName_en = "Deadly",
		attrType1 = 14,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Deadly",
		id = 15,
		suitID = 2
	},
	{
		suitName_th = "Deadly",
		suitQuality = 4,
		suitName_en = "Deadly",
		suitName = "Deadly",
		id = 16,
		attrType1 = 15,
		suitID = 2,
		attrNum1 = "600"
	},
	{
		suitName_th = "Deadly",
		attrNum1 = "600",
		suitName_en = "Deadly",
		attrType1 = 14,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Deadly",
		id = 17,
		suitID = 2
	},
	{
		suitName_th = "Deadly",
		suitQuality = 5,
		suitName_en = "Deadly",
		suitName = "Deadly",
		id = 18,
		attrType1 = 15,
		suitID = 2,
		attrNum1 = "900"
	},
	{
		suitName_th = "Deadly",
		attrNum1 = "800",
		suitName_en = "Deadly",
		attrType1 = 14,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Deadly",
		id = 19,
		suitID = 2
	},
	{
		suitName_th = "Deadly",
		suitQuality = 6,
		suitName_en = "Deadly",
		suitName = "Deadly",
		id = 20,
		attrType1 = 15,
		suitID = 2,
		attrNum1 = "1200"
	},
	{
		suitName_th = "Warlike",
		attrNum1 = "200",
		suitName_en = "Warlike",
		attrType1 = 92,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Warlike",
		id = 21,
		suitID = 3
	},
	{
		suitName_th = "Warlike",
		suitQuality = 2,
		suitName_en = "Warlike",
		suitName = "Warlike",
		id = 22,
		attrType1 = 22,
		suitID = 3,
		attrNum1 = "200"
	},
	{
		suitName_th = "Warlike",
		attrNum1 = "300",
		suitName_en = "Warlike",
		attrType1 = 92,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Warlike",
		id = 23,
		suitID = 3
	},
	{
		suitName_th = "Warlike",
		suitQuality = 3,
		suitName_en = "Warlike",
		suitName = "Warlike",
		id = 24,
		attrType1 = 22,
		suitID = 3,
		attrNum1 = "300"
	},
	{
		suitName_th = "Warlike",
		attrNum1 = "400",
		suitName_en = "Warlike",
		attrType1 = 92,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Warlike",
		id = 25,
		suitID = 3
	},
	{
		suitName_th = "Warlike",
		suitQuality = 4,
		suitName_en = "Warlike",
		suitName = "Warlike",
		id = 26,
		attrType1 = 22,
		suitID = 3,
		attrNum1 = "400"
	},
	{
		suitName_th = "Warlike",
		attrNum1 = "600",
		suitName_en = "Warlike",
		attrType1 = 92,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Warlike",
		id = 27,
		suitID = 3
	},
	{
		suitName_th = "Warlike",
		suitQuality = 5,
		suitName_en = "Warlike",
		suitName = "Warlike",
		id = 28,
		attrType1 = 22,
		suitID = 3,
		attrNum1 = "600"
	},
	{
		suitName_th = "Warlike",
		attrNum1 = "800",
		suitName_en = "Warlike",
		attrType1 = 92,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Warlike",
		id = 29,
		suitID = 3
	},
	{
		suitName_th = "Warlike",
		suitQuality = 6,
		suitName_en = "Warlike",
		suitName = "Warlike",
		id = 30,
		attrType1 = 22,
		suitID = 3,
		attrNum1 = "800"
	},
	{
		suitName_th = "Defend",
		attrNum1 = "300",
		suitName_en = "Defend",
		attrType1 = 17,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Defend",
		id = 31,
		suitID = 4
	},
	{
		suitName_th = "Defend",
		suitQuality = 2,
		suitName_en = "Defend",
		suitName = "Defend",
		id = 32,
		attrType1 = 19,
		suitID = 4,
		attrNum1 = "300"
	},
	{
		suitName_th = "Defend",
		attrNum1 = "400",
		suitName_en = "Defend",
		attrType1 = 17,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Defend",
		id = 33,
		suitID = 4
	},
	{
		suitName_th = "Defend",
		suitQuality = 3,
		suitName_en = "Defend",
		suitName = "Defend",
		id = 34,
		attrType1 = 19,
		suitID = 4,
		attrNum1 = "400"
	},
	{
		suitName_th = "Defend",
		attrNum1 = "500",
		suitName_en = "Defend",
		attrType1 = 17,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Defend",
		id = 35,
		suitID = 4
	},
	{
		suitName_th = "Defend",
		suitQuality = 4,
		suitName_en = "Defend",
		suitName = "Defend",
		id = 36,
		attrType1 = 19,
		suitID = 4,
		attrNum1 = "500"
	},
	{
		suitName_th = "Defend",
		attrNum1 = "750",
		suitName_en = "Defend",
		attrType1 = 17,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Defend",
		id = 37,
		suitID = 4
	},
	{
		suitName_th = "Defend",
		suitQuality = 5,
		suitName_en = "Defend",
		suitName = "Defend",
		id = 38,
		attrType1 = 19,
		suitID = 4,
		attrNum1 = "750"
	},
	{
		suitName_th = "Defend",
		attrNum1 = "1000",
		suitName_en = "Defend",
		attrType1 = 17,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Defend",
		id = 39,
		suitID = 4
	},
	{
		suitName_th = "Defend",
		suitQuality = 6,
		suitName_en = "Defend",
		suitName = "Defend",
		id = 40,
		attrType1 = 19,
		suitID = 4,
		attrNum1 = "1000"
	},
	{
		suitName_th = "Shield",
		attrNum1 = "5%",
		suitName_en = "Shield",
		attrType1 = 1,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Shield",
		id = 41,
		suitID = 5
	},
	{
		suitName_th = "Shield",
		suitQuality = 2,
		suitName_en = "Shield",
		suitName = "Shield",
		id = 42,
		attrType1 = 16,
		suitID = 5,
		attrNum1 = "300"
	},
	{
		suitName_th = "Shield",
		attrNum1 = "6.50%",
		suitName_en = "Shield",
		attrType1 = 1,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Shield",
		id = 43,
		suitID = 5
	},
	{
		suitName_th = "Shield",
		suitQuality = 3,
		suitName_en = "Shield",
		suitName = "Shield",
		id = 44,
		attrType1 = 16,
		suitID = 5,
		attrNum1 = "400"
	},
	{
		suitName_th = "Shield",
		attrNum1 = "8%",
		suitName_en = "Shield",
		attrType1 = 1,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Shield",
		id = 45,
		suitID = 5
	},
	{
		suitName_th = "Shield",
		suitQuality = 4,
		suitName_en = "Shield",
		suitName = "Shield",
		id = 46,
		attrType1 = 16,
		suitID = 5,
		attrNum1 = "500"
	},
	{
		suitName_th = "Shield",
		attrNum1 = "12%",
		suitName_en = "Shield",
		attrType1 = 1,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Shield",
		id = 47,
		suitID = 5
	},
	{
		suitName_th = "Shield",
		suitQuality = 5,
		suitName_en = "Shield",
		suitName = "Shield",
		id = 48,
		attrType1 = 16,
		suitID = 5,
		attrNum1 = "700"
	},
	{
		suitName_th = "Shield",
		attrNum1 = "16%",
		suitName_en = "Shield",
		attrType1 = 1,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Shield",
		id = 49,
		suitID = 5
	},
	{
		suitName_th = "Shield",
		suitQuality = 6,
		suitName_en = "Shield",
		suitName = "Shield",
		id = 50,
		attrType1 = 16,
		suitID = 5,
		attrNum1 = "1000"
	},
	{
		suitName_th = "King Kong",
		attrNum1 = "200",
		suitName_en = "King Kong",
		attrType1 = 93,
		suitQuality = 2,
		suitNum = 3,
		suitName = "King Kong",
		id = 51,
		suitID = 6
	},
	{
		suitName_th = "King Kong",
		suitQuality = 2,
		suitName_en = "King Kong",
		suitName = "King Kong",
		id = 52,
		attrType1 = 23,
		suitID = 6,
		attrNum1 = "200"
	},
	{
		suitName_th = "King Kong",
		attrNum1 = "300",
		suitName_en = "King Kong",
		attrType1 = 93,
		suitQuality = 3,
		suitNum = 3,
		suitName = "King Kong",
		id = 53,
		suitID = 6
	},
	{
		suitName_th = "King Kong",
		suitQuality = 3,
		suitName_en = "King Kong",
		suitName = "King Kong",
		id = 54,
		attrType1 = 23,
		suitID = 6,
		attrNum1 = "300"
	},
	{
		suitName_th = "King Kong",
		attrNum1 = "400",
		suitName_en = "King Kong",
		attrType1 = 93,
		suitQuality = 4,
		suitNum = 3,
		suitName = "King Kong",
		id = 55,
		suitID = 6
	},
	{
		suitName_th = "King Kong",
		suitQuality = 4,
		suitName_en = "King Kong",
		suitName = "King Kong",
		id = 56,
		attrType1 = 23,
		suitID = 6,
		attrNum1 = "400"
	},
	{
		suitName_th = "King Kong",
		attrNum1 = "600",
		suitName_en = "King Kong",
		attrType1 = 93,
		suitQuality = 5,
		suitNum = 3,
		suitName = "King Kong",
		id = 57,
		suitID = 6
	},
	{
		suitName_th = "King Kong",
		suitQuality = 5,
		suitName_en = "King Kong",
		suitName = "King Kong",
		id = 58,
		attrType1 = 23,
		suitID = 6,
		attrNum1 = "600"
	},
	{
		suitName_th = "King Kong",
		attrNum1 = "800",
		suitName_en = "King Kong",
		attrType1 = 93,
		suitQuality = 6,
		suitNum = 3,
		suitName = "King Kong",
		id = 59,
		suitID = 6
	},
	{
		suitName_th = "King Kong",
		suitQuality = 6,
		suitName_en = "King Kong",
		suitName = "King Kong",
		id = 60,
		attrType1 = 23,
		suitID = 6,
		attrNum1 = "800"
	},
	{
		suitName_th = "Shelter",
		attrNum1 = "400",
		suitName_en = "Shelter",
		attrType1 = 28,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Shelter",
		id = 61,
		suitID = 7
	},
	{
		suitName_th = "Shelter",
		attrNum1 = "500",
		suitName_en = "Shelter",
		attrType1 = 28,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Shelter",
		id = 62,
		suitID = 7
	},
	{
		suitName_th = "Shelter",
		attrNum1 = "600",
		suitName_en = "Shelter",
		attrType1 = 28,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Shelter",
		id = 63,
		suitID = 7
	},
	{
		suitName_th = "Shelter",
		attrNum1 = "900",
		suitName_en = "Shelter",
		attrType1 = 28,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Shelter",
		id = 64,
		suitID = 7
	},
	{
		suitName_th = "Shelter",
		attrNum1 = "1200",
		suitName_en = "Shelter",
		attrType1 = 28,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Shelter",
		id = 65,
		suitID = 7
	},
	{
		suitName_th = "Shine",
		attrNum1 = "200",
		suitName_en = "Shine",
		attrType1 = 26,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Shine",
		id = 66,
		suitID = 8
	},
	{
		suitName_th = "Shine",
		attrNum1 = "300",
		suitName_en = "Shine",
		attrType1 = 26,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Shine",
		id = 67,
		suitID = 8
	},
	{
		suitName_th = "Shine",
		attrNum1 = "400",
		suitName_en = "Shine",
		attrType1 = 26,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Shine",
		id = 68,
		suitID = 8
	},
	{
		suitName_th = "Shine",
		attrNum1 = "600",
		suitName_en = "Shine",
		attrType1 = 26,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Shine",
		id = 69,
		suitID = 8
	},
	{
		suitName_th = "Shine",
		attrNum1 = "800",
		suitName_en = "Shine",
		attrType1 = 26,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Shine",
		id = 70,
		suitID = 8
	},
	{
		suitName_th = "Counter",
		attrNum1 = "300",
		suitName_en = "Counter",
		attrType1 = 27,
		suitQuality = 2,
		suitNum = 3,
		suitName = "Counter",
		id = 71,
		suitID = 9
	},
	{
		suitName_th = "Counter",
		attrNum1 = "450",
		suitName_en = "Counter",
		attrType1 = 27,
		suitQuality = 3,
		suitNum = 3,
		suitName = "Counter",
		id = 72,
		suitID = 9
	},
	{
		suitName_th = "Counter",
		attrNum1 = "600",
		suitName_en = "Counter",
		attrType1 = 27,
		suitQuality = 4,
		suitNum = 3,
		suitName = "Counter",
		id = 73,
		suitID = 9
	},
	{
		suitName_th = "Counter",
		attrNum1 = "900",
		suitName_en = "Counter",
		attrType1 = 27,
		suitQuality = 5,
		suitNum = 3,
		suitName = "Counter",
		id = 74,
		suitID = 9
	},
	{
		suitName_th = "Counter",
		attrNum1 = "1200",
		suitName_en = "Counter",
		attrType1 = 27,
		suitQuality = 6,
		suitNum = 3,
		suitName = "Counter",
		id = 75,
		suitID = 9
	},
	__size = 75,
	__default = {
		__index = {
			suitName_th = "",
			suitQuality = 1,
			suitName_en = "",
			suitName = "",
			suitNum = 6,
			attrType1 = 0,
			suitID = 1,
			attrType2 = 0
		}
	}
}

return csv.gem.suit
