--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['arena']['robot_fix'] = {
	[1] = {
		id = 1,
		range = {1, 11},
		fightC = 1.65
	},
	[2] = {
		id = 2,
		range = {11, 51},
		fightC = 1.6
	},
	[3] = {
		id = 3,
		range = {51, 90},
		fightC = 1.55
	},
	[4] = {
		id = 4,
		range = {90, 130},
		fightC = 1.5
	},
	[5] = {
		id = 5,
		range = {130, 170},
		fightC = 1.45
	},
	[6] = {
		id = 6,
		range = {170, 210},
		fightC = 1.4
	},
	[7] = {
		id = 7,
		range = {210, 250},
		fightC = 1.35
	},
	[8] = {
		id = 8,
		range = {250, 300},
		fightC = 1.3
	},
	[9] = {
		id = 9,
		range = {300, 350},
		fightC = 1.25
	},
	[10] = {
		id = 10,
		range = {350, 400},
		fightC = 1.2
	},
	[11] = {
		id = 11,
		range = {400, 450},
		fightC = 1.15
	},
	[12] = {
		id = 12,
		range = {450, 500},
		fightC = 1.1
	},
	[13] = {
		id = 13,
		range = {500, 800},
		fightC = 1.05
	},
	[14] = {
		id = 14,
		range = {800, 1100}
	},
	[15] = {
		id = 15,
		range = {1100, 1400},
		fightC = 0.95
	},
	[16] = {
		id = 16,
		range = {1400, 1700},
		fightC = 0.9
	},
	[17] = {
		id = 17,
		range = {1700, 2000},
		fightC = 0.85
	},
	[18] = {
		id = 18,
		range = {2000, 2800},
		fightC = 0.8
	},
	[19] = {
		id = 19,
		range = {2800, 3600},
		fightC = 0.75
	},
	[20] = {
		id = 20,
		range = {3600, 4400},
		fightC = 0.7
	},
	[21] = {
		id = 21,
		range = {4400, 5200},
		fightC = 0.65
	},
	[22] = {
		id = 22,
		range = {5200, 6000},
		fightC = 0.6
	},
	[23] = {
		id = 23,
		range = {6000, 7000},
		fightC = 0.55
	},
	[24] = {
		id = 24,
		range = {7000, 8000},
		fightC = 0.5
	},
	[25] = {
		id = 25,
		range = {8000, 9000},
		fightC = 0.45
	},
	[26] = {
		id = 26,
		range = {9000, 10000},
		fightC = 0.4
	},
	[27] = {
		id = 27,
		range = {10000, 9999999},
		fightC = 0.35
	},
	__size = 27,
	__default = {
		__index = {
			range = {},
			fightC = 1
		}
	}
}
return csv.cross.arena.robot_fix