--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['random_tower']['can_pass'] = {
	[1] = {
		id = 1
	},
	[2] = {
		id = 2,
		level = 50,
		canPass = 30,
		canPass_en = 30,
		canPass_tw = 30,
		canPass_kr = 30
	},
	[3] = {
		id = 3,
		level = 60,
		canPass = 30,
		canPass_en = 30,
		canPass_tw = 30,
		canPass_kr = 30
	},
	[4] = {
		id = 4,
		level = 70,
		canPass = 35,
		canPass_en = 35,
		canPass_tw = 35,
		canPass_kr = 35
	},
	[5] = {
		id = 5,
		level = 80,
		canPass = 40,
		canPass_en = 40,
		canPass_tw = 40,
		canPass_kr = 40
	},
	[6] = {
		id = 6,
		level = 90,
		canPass = 45,
		canPass_en = 45,
		canPass_tw = 45,
		canPass_kr = 45
	},
	[7] = {
		id = 7,
		level = 100,
		canPass = 50,
		canPass_en = 50,
		canPass_tw = 50,
		canPass_kr = 50
	},
	[8] = {
		id = 8,
		vip = 4
	},
	[9] = {
		id = 9,
		vip = 5
	},
	[10] = {
		id = 10,
		vip = 6
	},
	[11] = {
		id = 11,
		vip = 7
	},
	__size = 11,
	__default = {
		__index = {
			level = 1,
			vip = 0,
			canPass = 0,
			canPass_en = 0,
			canPass_tw = 0,
			canPass_kr = 0
		}
	}
}
return csv.random_tower.can_pass