--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['world_boss']['hp_fix'] = {
	[1] = {
		id = 1,
		level = 1,
		hpFix = 6.8
	},
	[2] = {
		id = 2,
		level = 2,
		hpFix = 7
	},
	[3] = {
		id = 3,
		level = 3,
		hpFix = 7.2
	},
	[4] = {
		id = 4,
		level = 4,
		hpFix = 7.4
	},
	[5] = {
		id = 5,
		level = 5,
		hpFix = 7.6
	},
	[6] = {
		id = 6,
		level = 6,
		hpFix = 7.8
	},
	[7] = {
		id = 7,
		level = 7,
		hpFix = 8
	},
	[8] = {
		id = 8,
		level = 8,
		hpFix = 8.2
	},
	[9] = {
		id = 9,
		level = 9,
		hpFix = 8.4
	},
	[10] = {
		id = 10,
		level = 10,
		hpFix = 8.6
	},
	[11] = {
		id = 11,
		level = 11,
		hpFix = 8.8
	},
	[12] = {
		id = 12,
		level = 12,
		hpFix = 9
	},
	[13] = {
		id = 13,
		level = 13,
		hpFix = 9.2
	},
	[14] = {
		id = 14,
		level = 14,
		hpFix = 9.4
	},
	[15] = {
		id = 15,
		level = 15,
		hpFix = 9.6
	},
	[16] = {
		id = 16,
		level = 16,
		hpFix = 9.8
	},
	[17] = {
		id = 17,
		level = 17,
		hpFix = 10
	},
	[18] = {
		id = 18,
		level = 18,
		hpFix = 10.2
	},
	[19] = {
		id = 19,
		level = 19,
		hpFix = 10.4
	},
	[20] = {
		id = 20,
		level = 20,
		hpFix = 10.6
	},
	[21] = {
		id = 21,
		level = 21,
		hpFix = 10.8
	},
	[22] = {
		id = 22,
		level = 22,
		hpFix = 11
	},
	[23] = {
		id = 23,
		level = 23,
		hpFix = 11.2
	},
	[24] = {
		id = 24,
		level = 24,
		hpFix = 11.4
	},
	[25] = {
		id = 25,
		level = 25,
		hpFix = 11.6
	},
	[26] = {
		id = 26,
		level = 26,
		hpFix = 11.8
	},
	[27] = {
		id = 27,
		level = 27,
		hpFix = 12
	},
	[28] = {
		id = 28,
		level = 28,
		hpFix = 12.2
	},
	[29] = {
		id = 29,
		level = 29,
		hpFix = 12.4
	},
	[30] = {
		id = 30,
		level = 30,
		hpFix = 12.6
	},
	[31] = {
		id = 31,
		level = 31,
		hpFix = 12.8
	},
	[32] = {
		id = 32,
		level = 32,
		hpFix = 13
	},
	[33] = {
		id = 33,
		level = 33,
		hpFix = 13.2
	},
	[34] = {
		id = 34,
		level = 34,
		hpFix = 13.4
	},
	[35] = {
		id = 35,
		level = 35,
		hpFix = 13.6
	},
	[36] = {
		id = 36,
		level = 36,
		hpFix = 13.8
	},
	[37] = {
		id = 37,
		level = 37,
		hpFix = 14
	},
	[38] = {
		id = 38,
		level = 38,
		hpFix = 14.2
	},
	[39] = {
		id = 39,
		level = 39,
		hpFix = 14.4
	},
	[40] = {
		id = 40,
		level = 40,
		hpFix = 14.6
	},
	[41] = {
		id = 41,
		level = 41,
		hpFix = 14.8
	},
	[42] = {
		id = 42,
		level = 42,
		hpFix = 15
	},
	[43] = {
		id = 43,
		level = 43,
		hpFix = 15.2
	},
	[44] = {
		id = 44,
		level = 44,
		hpFix = 15.4
	},
	[45] = {
		id = 45,
		level = 45,
		hpFix = 15.6
	},
	[46] = {
		id = 46,
		level = 46,
		hpFix = 15.8
	},
	[47] = {
		id = 47,
		level = 47,
		hpFix = 16
	},
	[48] = {
		id = 48,
		level = 48,
		hpFix = 16.2
	},
	[49] = {
		id = 49,
		level = 49,
		hpFix = 16.4
	},
	[50] = {
		id = 50,
		level = 50,
		hpFix = 16.6
	},
	[51] = {
		id = 51,
		level = 51,
		hpFix = 16.8
	},
	[52] = {
		id = 52,
		level = 52,
		hpFix = 17
	},
	[53] = {
		id = 53,
		level = 53,
		hpFix = 17.2
	},
	[54] = {
		id = 54,
		level = 54,
		hpFix = 17.4
	},
	[55] = {
		id = 55,
		level = 55,
		hpFix = 17.6
	},
	[56] = {
		id = 56,
		level = 56,
		hpFix = 17.8
	},
	[57] = {
		id = 57,
		level = 57,
		hpFix = 18
	},
	[58] = {
		id = 58,
		level = 58,
		hpFix = 18.2
	},
	[59] = {
		id = 59,
		level = 59,
		hpFix = 18.4
	},
	[60] = {
		id = 60,
		level = 60,
		hpFix = 18.6
	},
	[61] = {
		id = 61,
		level = 61,
		hpFix = 18.8
	},
	[62] = {
		id = 62,
		level = 62,
		hpFix = 19
	},
	[63] = {
		id = 63,
		level = 63,
		hpFix = 19.2
	},
	[64] = {
		id = 64,
		level = 64,
		hpFix = 19.4
	},
	[65] = {
		id = 65,
		level = 65,
		hpFix = 19.6
	},
	[66] = {
		id = 66,
		level = 66,
		hpFix = 19.8
	},
	[67] = {
		id = 67,
		level = 67,
		hpFix = 20
	},
	[68] = {
		id = 68,
		level = 68,
		hpFix = 22
	},
	[69] = {
		id = 69,
		level = 69,
		hpFix = 24
	},
	[70] = {
		id = 70,
		level = 70,
		hpFix = 26
	},
	[71] = {
		id = 71,
		level = 71,
		hpFix = 28
	},
	[72] = {
		id = 72,
		level = 72,
		hpFix = 30
	},
	[73] = {
		id = 73,
		level = 73,
		hpFix = 32
	},
	[74] = {
		id = 74,
		level = 74,
		hpFix = 34
	},
	[75] = {
		id = 75,
		level = 75,
		hpFix = 36
	},
	[76] = {
		id = 76,
		level = 76,
		hpFix = 38
	},
	[77] = {
		id = 77,
		level = 77,
		hpFix = 40
	},
	[78] = {
		id = 78,
		level = 78,
		hpFix = 42
	},
	[79] = {
		id = 79,
		level = 79,
		hpFix = 44
	},
	[80] = {
		id = 80,
		level = 80,
		hpFix = 46
	},
	[81] = {
		id = 81,
		level = 81,
		hpFix = 48
	},
	[82] = {
		id = 82,
		level = 82,
		hpFix = 50
	},
	[83] = {
		id = 83,
		level = 83,
		hpFix = 52
	},
	[84] = {
		id = 84,
		level = 84,
		hpFix = 54
	},
	[85] = {
		id = 85,
		level = 85,
		hpFix = 56
	},
	[86] = {
		id = 86,
		level = 86,
		hpFix = 58
	},
	[87] = {
		id = 87,
		level = 87,
		hpFix = 60
	},
	[88] = {
		id = 88,
		level = 88,
		hpFix = 62
	},
	[89] = {
		id = 89,
		level = 89,
		hpFix = 64
	},
	[90] = {
		id = 90,
		level = 90,
		hpFix = 66
	},
	[91] = {
		id = 91,
		level = 91,
		hpFix = 68
	},
	[92] = {
		id = 92,
		level = 92,
		hpFix = 70
	},
	[93] = {
		id = 93,
		level = 93,
		hpFix = 72
	},
	[94] = {
		id = 94,
		level = 94,
		hpFix = 74
	},
	[95] = {
		id = 95,
		level = 95,
		hpFix = 76
	},
	[96] = {
		id = 96,
		level = 96,
		hpFix = 78
	},
	[97] = {
		id = 97,
		level = 97,
		hpFix = 80
	},
	[98] = {
		id = 98,
		level = 98,
		hpFix = 85
	},
	[99] = {
		id = 99,
		level = 99,
		hpFix = 90
	},
	[100] = {
		id = 100,
		level = 100
	},
	[101] = {
		id = 101,
		level = 101,
		hpFix = 125
	},
	[102] = {
		id = 102,
		level = 102,
		hpFix = 150
	},
	[103] = {
		id = 103,
		level = 103,
		hpFix = 175
	},
	[104] = {
		id = 104,
		level = 104,
		hpFix = 200
	},
	[105] = {
		id = 105,
		level = 105,
		hpFix = 225
	},
	[106] = {
		id = 106,
		level = 106,
		hpFix = 250
	},
	[107] = {
		id = 107,
		level = 107,
		hpFix = 275
	},
	[108] = {
		id = 108,
		level = 108,
		hpFix = 300
	},
	[109] = {
		id = 109,
		level = 109,
		hpFix = 325
	},
	[110] = {
		id = 110,
		level = 110,
		hpFix = 350
	},
	[111] = {
		id = 111,
		level = 111,
		hpFix = 375
	},
	[112] = {
		id = 112,
		level = 112,
		hpFix = 400
	},
	[113] = {
		id = 113,
		level = 113,
		hpFix = 425
	},
	[114] = {
		id = 114,
		level = 114,
		hpFix = 450
	},
	[115] = {
		id = 115,
		level = 115,
		hpFix = 475
	},
	[116] = {
		id = 116,
		level = 116,
		hpFix = 500
	},
	[117] = {
		id = 117,
		level = 117,
		hpFix = 525
	},
	[118] = {
		id = 118,
		level = 118,
		hpFix = 550
	},
	[119] = {
		id = 119,
		level = 119,
		hpFix = 575
	},
	[120] = {
		id = 120,
		level = 120,
		hpFix = 600
	},
	[121] = {
		id = 121,
		level = 121,
		hpFix = 650
	},
	[122] = {
		id = 122,
		level = 122,
		hpFix = 700
	},
	[123] = {
		id = 123,
		level = 123,
		hpFix = 750
	},
	[124] = {
		id = 124,
		level = 124,
		hpFix = 800
	},
	[125] = {
		id = 125,
		level = 125,
		hpFix = 850
	},
	[126] = {
		id = 126,
		level = 126,
		hpFix = 900
	},
	[127] = {
		id = 127,
		level = 127,
		hpFix = 950
	},
	[128] = {
		id = 128,
		level = 128,
		hpFix = 1000
	},
	[129] = {
		id = 129,
		level = 129,
		hpFix = 1050
	},
	[130] = {
		id = 130,
		level = 130,
		hpFix = 1100
	},
	[131] = {
		id = 131,
		level = 131,
		hpFix = 1150
	},
	[132] = {
		id = 132,
		level = 132,
		hpFix = 1200
	},
	[133] = {
		id = 133,
		level = 133,
		hpFix = 1250
	},
	[134] = {
		id = 134,
		level = 134,
		hpFix = 1300
	},
	[135] = {
		id = 135,
		level = 135,
		hpFix = 1350
	},
	[136] = {
		id = 136,
		level = 136,
		hpFix = 1400
	},
	[137] = {
		id = 137,
		level = 137,
		hpFix = 1450
	},
	[138] = {
		id = 138,
		level = 138,
		hpFix = 1500
	},
	[139] = {
		id = 139,
		level = 139,
		hpFix = 1550
	},
	[140] = {
		id = 140,
		level = 140,
		hpFix = 1600
	},
	[141] = {
		id = 141,
		level = 141,
		hpFix = 1650
	},
	[142] = {
		id = 142,
		level = 142,
		hpFix = 1700
	},
	[143] = {
		id = 143,
		level = 143,
		hpFix = 1750
	},
	[144] = {
		id = 144,
		level = 144,
		hpFix = 1800
	},
	[145] = {
		id = 145,
		level = 145,
		hpFix = 1850
	},
	[146] = {
		id = 146,
		level = 146,
		hpFix = 1900
	},
	[147] = {
		id = 147,
		level = 147,
		hpFix = 1950
	},
	[148] = {
		id = 148,
		level = 148,
		hpFix = 2000
	},
	[149] = {
		id = 149,
		level = 149,
		hpFix = 2050
	},
	[150] = {
		id = 150,
		level = 150,
		hpFix = 2100
	},
	[151] = {
		id = 151,
		level = 151,
		hpFix = 2200
	},
	[152] = {
		id = 152,
		level = 152,
		hpFix = 2300
	},
	[153] = {
		id = 153,
		level = 153,
		hpFix = 2400
	},
	[154] = {
		id = 154,
		level = 154,
		hpFix = 2500
	},
	[155] = {
		id = 155,
		level = 155,
		hpFix = 2600
	},
	[156] = {
		id = 156,
		level = 156,
		hpFix = 2700
	},
	[157] = {
		id = 157,
		level = 157,
		hpFix = 2800
	},
	[158] = {
		id = 158,
		level = 158,
		hpFix = 2900
	},
	[159] = {
		id = 159,
		level = 159,
		hpFix = 3000
	},
	[160] = {
		id = 160,
		level = 160,
		hpFix = 3100
	},
	[161] = {
		id = 161,
		level = 161,
		hpFix = 3200
	},
	[162] = {
		id = 162,
		level = 162,
		hpFix = 3300
	},
	[163] = {
		id = 163,
		level = 163,
		hpFix = 3400
	},
	[164] = {
		id = 164,
		level = 164,
		hpFix = 3500
	},
	[165] = {
		id = 165,
		level = 165,
		hpFix = 3600
	},
	[166] = {
		id = 166,
		level = 166,
		hpFix = 3700
	},
	[167] = {
		id = 167,
		level = 167,
		hpFix = 3800
	},
	[168] = {
		id = 168,
		level = 168,
		hpFix = 3900
	},
	[169] = {
		id = 169,
		level = 169,
		hpFix = 4000
	},
	[170] = {
		id = 170,
		level = 170,
		hpFix = 4100
	},
	[171] = {
		id = 171,
		level = 171,
		hpFix = 4200
	},
	[172] = {
		id = 172,
		level = 172,
		hpFix = 4300
	},
	[173] = {
		id = 173,
		level = 173,
		hpFix = 4400
	},
	[174] = {
		id = 174,
		level = 174,
		hpFix = 4500
	},
	[175] = {
		id = 175,
		level = 175,
		hpFix = 4600
	},
	[176] = {
		id = 176,
		level = 176,
		hpFix = 4700
	},
	[177] = {
		id = 177,
		level = 177,
		hpFix = 4800
	},
	[178] = {
		id = 178,
		level = 178,
		hpFix = 4900
	},
	[179] = {
		id = 179,
		level = 179,
		hpFix = 5000
	},
	[180] = {
		id = 180,
		level = 180,
		hpFix = 5100
	},
	[181] = {
		id = 181,
		level = 181,
		hpFix = 5200
	},
	[182] = {
		id = 182,
		level = 182,
		hpFix = 5300
	},
	[183] = {
		id = 183,
		level = 183,
		hpFix = 5400
	},
	[184] = {
		id = 184,
		level = 184,
		hpFix = 5500
	},
	[185] = {
		id = 185,
		level = 185,
		hpFix = 5600
	},
	[186] = {
		id = 186,
		level = 186,
		hpFix = 5700
	},
	[187] = {
		id = 187,
		level = 187,
		hpFix = 5800
	},
	[188] = {
		id = 188,
		level = 188,
		hpFix = 5900
	},
	[189] = {
		id = 189,
		level = 189,
		hpFix = 6000
	},
	[190] = {
		id = 190,
		level = 190,
		hpFix = 6100
	},
	[191] = {
		id = 191,
		level = 191,
		hpFix = 6200
	},
	[192] = {
		id = 192,
		level = 192,
		hpFix = 6300
	},
	[193] = {
		id = 193,
		level = 193,
		hpFix = 6400
	},
	[194] = {
		id = 194,
		level = 194,
		hpFix = 6500
	},
	[195] = {
		id = 195,
		level = 195,
		hpFix = 6600
	},
	[196] = {
		id = 196,
		level = 196,
		hpFix = 6700
	},
	[197] = {
		id = 197,
		level = 197,
		hpFix = 6800
	},
	[198] = {
		id = 198,
		level = 198,
		hpFix = 6900
	},
	[199] = {
		id = 199,
		level = 199,
		hpFix = 7000
	},
	[200] = {
		id = 200,
		level = 200,
		hpFix = 7100
	},
	[201] = {
		id = 201,
		level = 201,
		hpFix = 7300
	},
	[202] = {
		id = 202,
		level = 202,
		hpFix = 7500
	},
	[203] = {
		id = 203,
		level = 203,
		hpFix = 7700
	},
	[204] = {
		id = 204,
		level = 204,
		hpFix = 7900
	},
	[205] = {
		id = 205,
		level = 205,
		hpFix = 8100
	},
	[206] = {
		id = 206,
		level = 206,
		hpFix = 8300
	},
	[207] = {
		id = 207,
		level = 207,
		hpFix = 8500
	},
	[208] = {
		id = 208,
		level = 208,
		hpFix = 8700
	},
	[209] = {
		id = 209,
		level = 209,
		hpFix = 8900
	},
	[210] = {
		id = 210,
		level = 210,
		hpFix = 9100
	},
	[211] = {
		id = 211,
		level = 211,
		hpFix = 9300
	},
	[212] = {
		id = 212,
		level = 212,
		hpFix = 9500
	},
	[213] = {
		id = 213,
		level = 213,
		hpFix = 9700
	},
	[214] = {
		id = 214,
		level = 214,
		hpFix = 9900
	},
	[215] = {
		id = 215,
		level = 215,
		hpFix = 10100
	},
	[216] = {
		id = 216,
		level = 216,
		hpFix = 10300
	},
	[217] = {
		id = 217,
		level = 217,
		hpFix = 10500
	},
	[218] = {
		id = 218,
		level = 218,
		hpFix = 10700
	},
	[219] = {
		id = 219,
		level = 219,
		hpFix = 10900
	},
	[220] = {
		id = 220,
		level = 220,
		hpFix = 11100
	},
	[221] = {
		id = 221,
		level = 221,
		hpFix = 11400
	},
	[222] = {
		id = 222,
		level = 222,
		hpFix = 11700
	},
	[223] = {
		id = 223,
		level = 223,
		hpFix = 12000
	},
	[224] = {
		id = 224,
		level = 224,
		hpFix = 12300
	},
	[225] = {
		id = 225,
		level = 225,
		hpFix = 12600
	},
	[226] = {
		id = 226,
		level = 226,
		hpFix = 12900
	},
	[227] = {
		id = 227,
		level = 227,
		hpFix = 13200
	},
	[228] = {
		id = 228,
		level = 228,
		hpFix = 13500
	},
	[229] = {
		id = 229,
		level = 229,
		hpFix = 13800
	},
	[230] = {
		id = 230,
		level = 230,
		hpFix = 14100
	},
	[231] = {
		id = 231,
		level = 231,
		hpFix = 14400
	},
	[232] = {
		id = 232,
		level = 232,
		hpFix = 14700
	},
	[233] = {
		id = 233,
		level = 233,
		hpFix = 15000
	},
	[234] = {
		id = 234,
		level = 234,
		hpFix = 15300
	},
	[235] = {
		id = 235,
		level = 235,
		hpFix = 15600
	},
	[236] = {
		id = 236,
		level = 236,
		hpFix = 15900
	},
	[237] = {
		id = 237,
		level = 237,
		hpFix = 16200
	},
	[238] = {
		id = 238,
		level = 238,
		hpFix = 16500
	},
	[239] = {
		id = 239,
		level = 239,
		hpFix = 16800
	},
	[240] = {
		id = 240,
		level = 240,
		hpFix = 17100
	},
	[241] = {
		id = 241,
		level = 241,
		hpFix = 17400
	},
	[242] = {
		id = 242,
		level = 242,
		hpFix = 17700
	},
	[243] = {
		id = 243,
		level = 243,
		hpFix = 18000
	},
	[244] = {
		id = 244,
		level = 244,
		hpFix = 18300
	},
	[245] = {
		id = 245,
		level = 245,
		hpFix = 18600
	},
	[246] = {
		id = 246,
		level = 246,
		hpFix = 18900
	},
	[247] = {
		id = 247,
		level = 247,
		hpFix = 19200
	},
	[248] = {
		id = 248,
		level = 248,
		hpFix = 19500
	},
	[249] = {
		id = 249,
		level = 249,
		hpFix = 19800
	},
	[250] = {
		id = 250,
		level = 250,
		hpFix = 20100
	},
	[251] = {
		id = 251,
		level = 251,
		hpFix = 20600
	},
	[252] = {
		id = 252,
		level = 252,
		hpFix = 21100
	},
	[253] = {
		id = 253,
		level = 253,
		hpFix = 21600
	},
	[254] = {
		id = 254,
		level = 254,
		hpFix = 22100
	},
	[255] = {
		id = 255,
		level = 255,
		hpFix = 22600
	},
	[256] = {
		id = 256,
		level = 256,
		hpFix = 23100
	},
	[257] = {
		id = 257,
		level = 257,
		hpFix = 23600
	},
	[258] = {
		id = 258,
		level = 258,
		hpFix = 24100
	},
	[259] = {
		id = 259,
		level = 259,
		hpFix = 24600
	},
	[260] = {
		id = 260,
		level = 260,
		hpFix = 25100
	},
	[261] = {
		id = 261,
		level = 261,
		hpFix = 25600
	},
	[262] = {
		id = 262,
		level = 262,
		hpFix = 26100
	},
	[263] = {
		id = 263,
		level = 263,
		hpFix = 26600
	},
	[264] = {
		id = 264,
		level = 264,
		hpFix = 27100
	},
	[265] = {
		id = 265,
		level = 265,
		hpFix = 27600
	},
	[266] = {
		id = 266,
		level = 266,
		hpFix = 28100
	},
	[267] = {
		id = 267,
		level = 267,
		hpFix = 28600
	},
	[268] = {
		id = 268,
		level = 268,
		hpFix = 29100
	},
	[269] = {
		id = 269,
		level = 269,
		hpFix = 29600
	},
	[270] = {
		id = 270,
		level = 270,
		hpFix = 30100
	},
	[271] = {
		id = 271,
		level = 271,
		hpFix = 30600
	},
	[272] = {
		id = 272,
		level = 272,
		hpFix = 31100
	},
	[273] = {
		id = 273,
		level = 273,
		hpFix = 31600
	},
	[274] = {
		id = 274,
		level = 274,
		hpFix = 32100
	},
	[275] = {
		id = 275,
		level = 275,
		hpFix = 32600
	},
	[276] = {
		id = 276,
		level = 276,
		hpFix = 33100
	},
	[277] = {
		id = 277,
		level = 277,
		hpFix = 33600
	},
	[278] = {
		id = 278,
		level = 278,
		hpFix = 34100
	},
	[279] = {
		id = 279,
		level = 279,
		hpFix = 34600
	},
	[280] = {
		id = 280,
		level = 280,
		hpFix = 35100
	},
	[281] = {
		id = 281,
		level = 281,
		hpFix = 35600
	},
	[282] = {
		id = 282,
		level = 282,
		hpFix = 36100
	},
	[283] = {
		id = 283,
		level = 283,
		hpFix = 36600
	},
	[284] = {
		id = 284,
		level = 284,
		hpFix = 37100
	},
	[285] = {
		id = 285,
		level = 285,
		hpFix = 37600
	},
	[286] = {
		id = 286,
		level = 286,
		hpFix = 38100
	},
	[287] = {
		id = 287,
		level = 287,
		hpFix = 38600
	},
	[288] = {
		id = 288,
		level = 288,
		hpFix = 39100
	},
	[289] = {
		id = 289,
		level = 289,
		hpFix = 39600
	},
	[290] = {
		id = 290,
		level = 290,
		hpFix = 40100
	},
	[291] = {
		id = 291,
		level = 291,
		hpFix = 40600
	},
	[292] = {
		id = 292,
		level = 292,
		hpFix = 41100
	},
	[293] = {
		id = 293,
		level = 293,
		hpFix = 41600
	},
	[294] = {
		id = 294,
		level = 294,
		hpFix = 42100
	},
	[295] = {
		id = 295,
		level = 295,
		hpFix = 42600
	},
	[296] = {
		id = 296,
		level = 296,
		hpFix = 43100
	},
	[297] = {
		id = 297,
		level = 297,
		hpFix = 43600
	},
	[298] = {
		id = 298,
		level = 298,
		hpFix = 44100
	},
	[299] = {
		id = 299,
		level = 299,
		hpFix = 44600
	},
	[300] = {
		id = 300,
		level = 300,
		hpFix = 45100
	},
	[301] = {
		id = 301,
		level = 301,
		hpFix = 45600
	},
	[302] = {
		id = 302,
		level = 302,
		hpFix = 46100
	},
	[303] = {
		id = 303,
		level = 303,
		hpFix = 46600
	},
	[304] = {
		id = 304,
		level = 304,
		hpFix = 47100
	},
	[305] = {
		id = 305,
		level = 305,
		hpFix = 47600
	},
	[306] = {
		id = 306,
		level = 306,
		hpFix = 48100
	},
	[307] = {
		id = 307,
		level = 307,
		hpFix = 48600
	},
	[308] = {
		id = 308,
		level = 308,
		hpFix = 49100
	},
	[309] = {
		id = 309,
		level = 309,
		hpFix = 49600
	},
	[310] = {
		id = 310,
		level = 310,
		hpFix = 50100
	},
	[311] = {
		id = 311,
		level = 311,
		hpFix = 50600
	},
	[312] = {
		id = 312,
		level = 312,
		hpFix = 51100
	},
	[313] = {
		id = 313,
		level = 313,
		hpFix = 51600
	},
	[314] = {
		id = 314,
		level = 314,
		hpFix = 52100
	},
	[315] = {
		id = 315,
		level = 315,
		hpFix = 52600
	},
	[316] = {
		id = 316,
		level = 316,
		hpFix = 53100
	},
	[317] = {
		id = 317,
		level = 317,
		hpFix = 53600
	},
	[318] = {
		id = 318,
		level = 318,
		hpFix = 54100
	},
	[319] = {
		id = 319,
		level = 319,
		hpFix = 54600
	},
	[320] = {
		id = 320,
		level = 320,
		hpFix = 55100
	},
	[321] = {
		id = 321,
		level = 321,
		hpFix = 55600
	},
	[322] = {
		id = 322,
		level = 322,
		hpFix = 56100
	},
	[323] = {
		id = 323,
		level = 323,
		hpFix = 56600
	},
	[324] = {
		id = 324,
		level = 324,
		hpFix = 57100
	},
	[325] = {
		id = 325,
		level = 325,
		hpFix = 57600
	},
	[326] = {
		id = 326,
		level = 326,
		hpFix = 58100
	},
	[327] = {
		id = 327,
		level = 327,
		hpFix = 58600
	},
	[328] = {
		id = 328,
		level = 328,
		hpFix = 59100
	},
	[329] = {
		id = 329,
		level = 329,
		hpFix = 59600
	},
	[330] = {
		id = 330,
		level = 330,
		hpFix = 60100
	},
	[331] = {
		id = 331,
		level = 331,
		hpFix = 60600
	},
	[332] = {
		id = 332,
		level = 332,
		hpFix = 61100
	},
	[333] = {
		id = 333,
		level = 333,
		hpFix = 61600
	},
	[334] = {
		id = 334,
		level = 334,
		hpFix = 62100
	},
	[335] = {
		id = 335,
		level = 335,
		hpFix = 62600
	},
	[336] = {
		id = 336,
		level = 336,
		hpFix = 63100
	},
	[337] = {
		id = 337,
		level = 337,
		hpFix = 63600
	},
	[338] = {
		id = 338,
		level = 338,
		hpFix = 64100
	},
	[339] = {
		id = 339,
		level = 339,
		hpFix = 64600
	},
	[340] = {
		id = 340,
		level = 340,
		hpFix = 65100
	},
	[341] = {
		id = 341,
		level = 341,
		hpFix = 65600
	},
	[342] = {
		id = 342,
		level = 342,
		hpFix = 66100
	},
	[343] = {
		id = 343,
		level = 343,
		hpFix = 66600
	},
	[344] = {
		id = 344,
		level = 344,
		hpFix = 67100
	},
	[345] = {
		id = 345,
		level = 345,
		hpFix = 67600
	},
	[346] = {
		id = 346,
		level = 346,
		hpFix = 68100
	},
	[347] = {
		id = 347,
		level = 347,
		hpFix = 68600
	},
	[348] = {
		id = 348,
		level = 348,
		hpFix = 69100
	},
	[349] = {
		id = 349,
		level = 349,
		hpFix = 69600
	},
	[350] = {
		id = 350,
		level = 350,
		hpFix = 70100
	},
	[351] = {
		id = 351,
		level = 351,
		hpFix = 70600
	},
	[352] = {
		id = 352,
		level = 352,
		hpFix = 71100
	},
	[353] = {
		id = 353,
		level = 353,
		hpFix = 71600
	},
	[354] = {
		id = 354,
		level = 354,
		hpFix = 72100
	},
	[355] = {
		id = 355,
		level = 355,
		hpFix = 72600
	},
	[356] = {
		id = 356,
		level = 356,
		hpFix = 73100
	},
	[357] = {
		id = 357,
		level = 357,
		hpFix = 73600
	},
	[358] = {
		id = 358,
		level = 358,
		hpFix = 74100
	},
	[359] = {
		id = 359,
		level = 359,
		hpFix = 74600
	},
	[360] = {
		id = 360,
		level = 360,
		hpFix = 75100
	},
	[361] = {
		id = 361,
		level = 361,
		hpFix = 75600
	},
	[362] = {
		id = 362,
		level = 362,
		hpFix = 76100
	},
	[363] = {
		id = 363,
		level = 363,
		hpFix = 76600
	},
	[364] = {
		id = 364,
		level = 364,
		hpFix = 77100
	},
	[365] = {
		id = 365,
		level = 365,
		hpFix = 77600
	},
	[366] = {
		id = 366,
		level = 366,
		hpFix = 78100
	},
	[367] = {
		id = 367,
		level = 367,
		hpFix = 78600
	},
	[368] = {
		id = 368,
		level = 368,
		hpFix = 79100
	},
	[369] = {
		id = 369,
		level = 369,
		hpFix = 79600
	},
	[370] = {
		id = 370,
		level = 370,
		hpFix = 80100
	},
	[371] = {
		id = 371,
		level = 371,
		hpFix = 80600
	},
	[372] = {
		id = 372,
		level = 372,
		hpFix = 81100
	},
	[373] = {
		id = 373,
		level = 373,
		hpFix = 81600
	},
	[374] = {
		id = 374,
		level = 374,
		hpFix = 82100
	},
	[375] = {
		id = 375,
		level = 375,
		hpFix = 82600
	},
	[376] = {
		id = 376,
		level = 376,
		hpFix = 83100
	},
	[377] = {
		id = 377,
		level = 377,
		hpFix = 83600
	},
	[378] = {
		id = 378,
		level = 378,
		hpFix = 84100
	},
	[379] = {
		id = 379,
		level = 379,
		hpFix = 84600
	},
	[380] = {
		id = 380,
		level = 380,
		hpFix = 85100
	},
	[381] = {
		id = 381,
		level = 381,
		hpFix = 85600
	},
	[382] = {
		id = 382,
		level = 382,
		hpFix = 86100
	},
	[383] = {
		id = 383,
		level = 383,
		hpFix = 86600
	},
	[384] = {
		id = 384,
		level = 384,
		hpFix = 87100
	},
	[385] = {
		id = 385,
		level = 385,
		hpFix = 87600
	},
	[386] = {
		id = 386,
		level = 386,
		hpFix = 88100
	},
	[387] = {
		id = 387,
		level = 387,
		hpFix = 88600
	},
	[388] = {
		id = 388,
		level = 388,
		hpFix = 89100
	},
	[389] = {
		id = 389,
		level = 389,
		hpFix = 89600
	},
	[390] = {
		id = 390,
		level = 390,
		hpFix = 90100
	},
	[391] = {
		id = 391,
		level = 391,
		hpFix = 90600
	},
	[392] = {
		id = 392,
		level = 392,
		hpFix = 91100
	},
	[393] = {
		id = 393,
		level = 393,
		hpFix = 91600
	},
	[394] = {
		id = 394,
		level = 394,
		hpFix = 92100
	},
	[395] = {
		id = 395,
		level = 395,
		hpFix = 92600
	},
	[396] = {
		id = 396,
		level = 396,
		hpFix = 93100
	},
	[397] = {
		id = 397,
		level = 397,
		hpFix = 93600
	},
	[398] = {
		id = 398,
		level = 398,
		hpFix = 94100
	},
	[399] = {
		id = 399,
		level = 399,
		hpFix = 94600
	},
	[400] = {
		id = 400,
		level = 400,
		hpFix = 95100
	},
	__size = 400,
	__default = {
		__index = {
			level = 0,
			hpFix = 100
		}
	}
}
return csv.world_boss.hp_fix