--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['sprite_jump']['board'] = {
	[1] = {
		id = 1,
		res = 'activity/sprite_jump/board1.png',
		speedX = 0,
		times = -1
	},
	[2] = {
		id = 2,
		res = 'activity/sprite_jump/board2.png',
		speedX = 0,
		times = 0
	},
	[3] = {
		id = 3,
		res = 'activity/sprite_jump/board3.png',
		speedX = 0,
		times = 1
	},
	[4] = {
		id = 4,
		res = 'activity/sprite_jump/board1.png',
		speedX = 5,
		times = -1
	},
	[5] = {
		id = 5,
		size = {['height'] = 0, ['width'] = 0, __size = 2},
		res = 'activity/sprite_jump/board1.png',
		speedX = 0,
		times = 0
	},
	__size = 5,
	__default = {
		__index = {
			size = {['height'] = 44, ['width'] = 400, __size = 2}
		}
	}
}
return csv.sprite_jump.board