--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {[519] = 1, ['gold'] = 200000, [930] = 20, __size = 3}, 
	[3] = {[519] = 1, ['rmb'] = 50, [59002] = 2, __size = 3}, __size = 2}
local __data_t__award = {
	[102] = __predefine_t__[3],
	[103] = __predefine_t__[2],
	[101] = __predefine_t__[2],
	[106] = __predefine_t__[3],
	[104] = __predefine_t__[3],
	[105] = __predefine_t__[2]
}

csv['sprite_jump']['tasks'] = {
	[101] = {
		id = 101,
		targetArg = 1000,
		huodongID = 1000,
		award = __data_t__award[101]
		-- {[519] = 1, ['gold'] = 200000, [930] = 20, __size = 3}
	},
	[102] = {
		id = 102,
		targetArg = 2000,
		huodongID = 1000,
		award = __data_t__award[102]
		-- {[519] = 1, ['rmb'] = 50, [59002] = 2, __size = 3}
	},
	[103] = {
		id = 103,
		targetArg = 3500,
		huodongID = 1000,
		award = __data_t__award[103]
		-- {[519] = 1, ['gold'] = 200000, [930] = 20, __size = 3}
	},
	[104] = {
		id = 104,
		targetArg = 5000,
		huodongID = 1000,
		award = __data_t__award[104]
		-- {[519] = 1, ['rmb'] = 50, [59002] = 2, __size = 3}
	},
	[105] = {
		id = 105,
		targetArg = 6500,
		huodongID = 1000,
		award = __data_t__award[105]
		-- {[519] = 1, ['gold'] = 200000, [930] = 20, __size = 3}
	},
	[106] = {
		id = 106,
		targetArg = 8000,
		huodongID = 1000,
		award = __data_t__award[106]
		-- {[519] = 1, ['rmb'] = 50, [59002] = 2, __size = 3}
	},
	[107] = {
		id = 107,
		targetArg = 9500,
		huodongID = 1000,
		award = {[519] = 1, ['gold'] = 200000, [59003] = 1, __size = 3}
	},
	[108] = {
		id = 108,
		targetArg = 11000,
		huodongID = 1000,
		award = {[519] = 1, ['rmb'] = 50, [59003] = 1, __size = 3}
	},
	[109] = {
		id = 109,
		targetArg = 13000,
		huodongID = 1000,
		award = {[519] = 1, ['rmb'] = 100, [59003] = 1, __size = 3}
	},
	__size = 9,
	__default = {
		__index = {
			targetArg = 0,
			huodongID = 0,
			award = {__size = 0}
		}
	}
}
return csv.sprite_jump.tasks