--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['online_auto_chess']['round_time'] = {
	[1] = {
		id = 1
	},
	[2] = {
		id = 2,
		time = 30,
		round = 1
	},
	[3] = {
		id = 3,
		time = 38,
		round = 2
	},
	[4] = {
		id = 4,
		round = 3
	},
	[5] = {
		id = 5,
		time = 60,
		round = 4
	},
	[6] = {
		id = 6,
		time = 90,
		round = 5
	},
	__size = 6,
	__default = {
		__index = {
			time = 45,
			round = 0
		}
	}
}
return csv.cross.online_auto_chess.round_time