--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['fishing']['base'] = {
	[1] = {
		id = 1,
		servOpenDays = 40,
		specialFish = 9999
	},
	__size = 1,
	__default = {
		__index = {
			specialFish = 0,
			groupSize = 20
		}
	}
}
return csv.cross.fishing.base