slot0 = {
	{},
	{
		"2%",
		"4%",
		"6%",
		"8%",
		"10%"
	},
	{
		101
	},
	{
		300,
		600,
		900,
		1200,
		1500
	},
	{
		"3%",
		"6%",
		"9%",
		"12%",
		"15%"
	},
	__size = 13,
	[7] = {
		400,
		800,
		1200,
		1600,
		2000
	},
	[10] = {
		1000,
		1500,
		2000,
		2500,
		3000
	},
	[15] = {
		"10%",
		"16%",
		"22%",
		"28%",
		"34%"
	},
	[21] = {
		"4%",
		"8%",
		"12%",
		"16%",
		"20%"
	},
	[22] = {
		201
	},
	[29] = {
		"8%",
		"14%",
		"20%",
		"26%",
		"32%"
	},
	[37] = {
		301
	},
	[43] = {
		600,
		1000,
		1400,
		1800,
		2200
	}
}
slot1 = {
	[203] = slot0[22],
	[202] = slot0[22],
	[302] = slot0[37],
	[303] = slot0[37],
	default = slot0[1],
	[102] = slot0[3],
	[103] = slot0[3]
}
slot2 = {
	[201] = slot0[21],
	[208] = slot0[29],
	default = slot0[1],
	[109] = slot0[15],
	[103] = slot0[5],
	[101] = slot0[2]
}
slot4 = {
	[308] = slot0[43],
	default = slot0[1],
	[301] = slot0[4],
	[201] = slot0[21],
	[309] = slot0[43],
	[203] = slot0[4],
	[202] = slot0[5],
	[205] = slot0[7],
	[204] = slot0[7],
	[206] = slot0[7],
	[208] = slot0[29],
	[303] = slot0[5],
	[304] = slot0[4],
	[305] = slot0[4],
	[306] = slot0[4],
	[109] = slot0[15],
	[102] = slot0[4],
	[103] = slot0[5],
	[101] = slot0[2],
	[106] = slot0[10],
	[107] = slot0[10],
	[104] = slot0[7],
	[105] = slot0[7]
}
csv.gym.talent_buff = {
	__size = 39,
	[101] = {
		costID = 1,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		name_en = "Damage bonus",
		attrType1 = 7,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่ม %s P. & Sp. ATK",
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s P. & Sp. ATK",
		depth = 1,
		levelUp = 5,
		icon = "config/card_ability/icon_gj_1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam %s ATQ Físico e Mágico",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s P. & Sp. ATK",
		attrType2 = 8,
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 101,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 물리&특수 공격 피해 %s 증가",
		attrNum1 = slot4[101],
		attrNum2 = slot2[101]
	},
	[102] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 2,
		attrType1 = 22,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase the damage bonus by %s",
		name_en = "Damage bonus",
		depth = 2,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มโบนัสความเสียหายอีก %s",
		icon = "config/card_ability/icon_gj1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam o Dano Bônus em %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase the damage bonus by %s",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 102,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 피해 보너스 %s 증가",
		preTalentIDs = slot1[102],
		attrNum1 = slot4[102]
	},
	[103] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 2,
		attrType1 = 7,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s P. & Sp. ATK",
		name_en = "Damage bonus",
		depth = 2,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่ม %s P. & Sp. ATK",
		icon = "config/card_ability/icon_gj2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam %s ATQ Físico e Mágico",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s P. & Sp. ATK",
		attrType2 = 8,
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 103,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 물리&특수 공격 피해 %s 증가",
		preTalentIDs = slot1[103],
		attrNum1 = slot4[103],
		attrNum2 = slot2[103]
	},
	[104] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 3,
		attrType1 = 14,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their Crit rate by %s",
		name_en = "Damage bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทุกตัวในสนามรบจะเพิ่มอัตราคริติคอลอีก %s",
		icon = "config/card_ability/icon_gj1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam taxa de Crítico em %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their Crit rate by %s",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 104,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 치명타율 %s 증가",
		preTalentIDs = {
			102
		},
		attrNum1 = slot4[104]
	},
	[105] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 3,
		attrType1 = 22,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield will increase Ultimate Skill damage bonus by %s.",
		name_en = "Damage bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มโบนัสความเสียหายของทักษะขั้นสูงสุดอีก %s",
		icon = "config/card_ability/icon_gj2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam o Dano Bônus da habilidade especial em %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield will increase Ultimate Skill damage bonus by %s.",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 105,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 필살기 피해 보너스  %s 증가",
		preTalentIDs = {
			102,
			103
		},
		attrNum1 = slot4[105]
	},
	[106] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 3,
		attrType1 = 29,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s type restraint",
		name_en = "Damage bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบได้เพิ่ม %s ประเภทการยับยั้งชั่งใจ",
		icon = "config/card_ability/icon_gj3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam a restrição do tipo %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s type restraint",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 106,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 타입 상성 피해 %s 증가",
		preTalentIDs = {
			103
		},
		attrNum1 = slot4[106]
	},
	[107] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 4,
		attrType1 = 15,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their Crit damage by %s",
		name_en = "Damage bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มความเสียหายคริติคอลอีก %s",
		icon = "config/card_ability/icon_gj1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam Dano Crítico em %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their Crit damage by %s",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 107,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 치명타 피해 %s 증가",
		preTalentIDs = {
			104
		},
		attrNum1 = slot4[107]
	},
	[108] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 4,
		attrType1 = 18,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase Block Break rate by %s",
		name_en = "Damage bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มอัตราการ Block Break อีก %s",
		icon = "config/card_ability/icon_gj2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam a Taxa de quebra de Bloqueio em %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase Block Break rate by %s",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 108,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 저항 무시율 %s 증가",
		preTalentIDs = {
			104,
			105
		},
		attrNum1 = {
			3000,
			4000,
			5000,
			6000,
			8000
		}
	},
	[109] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 4,
		attrType1 = 11,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all the Pokémon on the battlefield increase P. &Sp. DEF ignorance by %s",
		name_en = "Damage bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่ม P. &Sp. ความไม่รู้ DEF โดย %s",
		icon = "config/card_ability/icon_gj3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam Penetração de Defesa Física e Mágica em %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all the Pokémon on the battlefield increase P. &Sp. DEF ignorance by %s",
		attrType2 = 12,
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 109,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 물리&특수 방어력 무시 %s 증가",
		preTalentIDs = {
			105,
			106
		},
		attrNum1 = slot4[109],
		attrNum2 = slot2[109]
	},
	[110] = {
		levelUp = 5,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 4,
		attrType1 = 29,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s type restraint",
		name_en = "Damage bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบได้เพิ่ม %s ประเภทการยับยั้งชั่งใจ",
		icon = "config/card_ability/icon_gj4.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam a restrição do tipo %s",
		treeID = 1,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s type restraint",
		effectType = 1,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 110,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 타입 상성 피해 %s 증가",
		preTalentIDs = {
			106
		},
		attrNum1 = {
			2000,
			2500,
			3000,
			3500,
			5000
		}
	},
	[111] = {
		effectType = 2,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 5,
		desc_th = "Ultimate Skill แรกจะต้องเป็นการโจมตีคริติคอล และความเสียหายคริติคอลเพิ่มขึ้น $(20+skilllevel*4)$% ชั่วคราว",
		preLevel = 3,
		desc = "The first Ultimate Skill must be a critical attack, and Crit damage increase by $(20+skilllevel*4)$% temporarily",
		name_en = "Damage bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_gj.png",
		desc_vn = "A primeira Habilidade Especial será um ataque crítico, e o dano crítico aumenta em $(20+skilllevel*4)$% temporariamente",
		treeID = 1,
		desc_en = "The first Ultimate Skill must be a critical attack, and Crit damage increase by $(20+skilllevel*4)$% temporarily",
		skillID = 63001,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 111,
		desc_kr = "첫 필살기 발동시 반드시 치명타, 치명타 피해량 잠시 $(20+skilllevel*4)$% 증가",
		preTalentIDs = {
			107,
			108
		}
	},
	[112] = {
		effectType = 2,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 5,
		desc_th = "ในรอบแรกของการต่อสู้ รับความโกรธเพิ่ม $(250+skilllevel*70)$",
		preLevel = 3,
		desc = "At the first round of the battle, get an extra $(250+skilllevel*70)$ anger",
		name_en = "Damage bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_gj.png",
		desc_vn = "Na primeira rodada da batalha, obtenha uma raiva extra de $(250+skilllevel*70)$",
		treeID = 1,
		desc_en = "At the first round of the battle, get an extra $(250+skilllevel*70)$ anger",
		skillID = 63002,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 112,
		desc_kr = "전투 시작 시 분노치 $(250+skilllevel*70)$ 추가로 획득",
		preTalentIDs = {
			108,
			109
		}
	},
	[113] = {
		effectType = 2,
		name = "Damage bonus",
		name_tw = "輸出加成",
		name_kr = "공격력 버프",
		costID = 5,
		desc_th = "ความเสียหายเพิ่มขึ้น $(5+skilllevel*2)$% สำหรับการโจมตีแต่ละครั้งอย่างถาวร ซึ่งสามารถซ้อนได้ 15 ครั้ง",
		preLevel = 3,
		desc = "Damage increased by $(5+skilllevel*2)$% for each attack permanently , which can be stacked for 15 times",
		name_en = "Damage bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_gj.png",
		desc_vn = "Dano aumentado em $(5+skilllevel*2)$% para cada ataque permanentemente, que pode ser acumulado por 15 vezes",
		treeID = 1,
		desc_en = "Damage increased by $(5+skilllevel*2)$% for each attack permanently , which can be stacked for 15 times",
		skillID = 63003,
		name_vn = "Dano bônus",
		name_th = "Damage bonus",
		id = 113,
		desc_kr = "공격할 때마다 $(5+skilllevel*2)$%씩 증가한다. 최대 중첩 수: 15",
		preTalentIDs = {
			109,
			110
		}
	},
	[201] = {
		costID = 1,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		name_en = "Defense bonus",
		attrType1 = 9,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบได้เพิ่ม %s P. & Sp.DEF",
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s P. & Sp.DEF",
		depth = 1,
		levelUp = 5,
		icon = "config/card_ability/icon_fy_1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam %s Def Física e Mágica",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s P. & Sp.DEF",
		attrType2 = 10,
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 201,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 물리&특수 방어력 %s 증가",
		attrNum1 = slot4[201],
		attrNum2 = slot2[201]
	},
	[202] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 2,
		attrType1 = 1,
		preLevel = 2,
		desc = "In the battle between non-players in this service hall, all Pokémon on the battlefield increase the HP upper limit by %s",
		name_en = "Defense bonus",
		depth = 2,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในศูนย์บริการนี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มขีดจำกัดสูงสุดของ HP ขึ้น %s",
		icon = "config/card_ability/icon_fy1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam o limie de HP em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this service hall, all Pokémon on the battlefield increase the HP upper limit by %s",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 202,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 최대 HP %s 증가",
		preTalentIDs = slot1[202],
		attrNum1 = slot4[202]
	},
	[203] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 2,
		attrType1 = 23,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s damage reduction",
		name_en = "Defense bonus",
		depth = 2,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่ม %s ลดความเสียหาย",
		icon = "config/card_ability/icon_fy2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam a redução de dano em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s damage reduction",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 203,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 피해 감소 %s 증가",
		preTalentIDs = slot1[203],
		attrNum1 = slot4[203]
	},
	[204] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 3,
		attrType1 = 17,
		preLevel = 2,
		desc = "In the battle between non-playersin this server gym, all Pokémon on the battlefield increase their Block rate by %s",
		name_en = "Defense bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทุกตัวในสนามรบจะเพิ่มอัตราการบล็อกอีก %s",
		icon = "config/card_ability/icon_fy1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua taxa de bloqueio em %s",
		treeID = 2,
		desc_en = "In the battle between non-playersin this server gym, all Pokémon on the battlefield increase their Block rate by %s",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 204,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 저항률 %s 증가",
		preTalentIDs = {
			202
		},
		attrNum1 = slot4[204]
	},
	[205] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 3,
		attrType1 = 27,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their DMG reflection rate by %s",
		name_en = "Defense bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มอัตราการสะท้อน DMG ของพวกมันอีก %s",
		icon = "config/card_ability/icon_fy2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua taxa de reflexão de dano em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their DMG reflection rate by %s",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 205,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 반사율 %s 증가",
		preTalentIDs = {
			202,
			203
		},
		attrNum1 = slot4[205]
	},
	[206] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 3,
		attrType1 = 25,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase the Ult Skill DMG resistance by %s.",
		name_en = "Defense bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มความต้านทาน Ult Skill DMG ขึ้น %s",
		icon = "config/card_ability/icon_fy3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua resistência a habilidade especial em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase the Ult Skill DMG resistance by %s.",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 206,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 필사기 피해 저항 %s 증가",
		preTalentIDs = {
			203
		},
		attrNum1 = slot4[206]
	},
	[207] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 4,
		attrType1 = 17,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their Block Intensity by %s",
		name_en = "Defense bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่ม Block Intensity ขึ้น %s",
		icon = "config/card_ability/icon_fy1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua intensidade de bloqueio em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their Block Intensity by %s",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 207,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 저항 강도 %s 증가",
		preTalentIDs = {
			204
		},
		attrNum1 = {
			800,
			1400,
			2000,
			2600,
			3200
		}
	},
	[208] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 4,
		attrType1 = 9,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s P. & Sp.DEF",
		name_en = "Defense bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบได้เพิ่ม %s P. & Sp.DEF",
		icon = "config/card_ability/icon_fy2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam %s Def Física e Mágica",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased %s P. & Sp.DEF",
		attrType2 = 10,
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 208,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 물리&특수 방어력 %s 증가",
		preTalentIDs = {
			204,
			205
		},
		attrNum1 = slot4[208],
		attrNum2 = slot2[208]
	},
	[209] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 4,
		attrType1 = 1,
		preLevel = 3,
		desc = "In the battle between non-players in this service hall, all Pokémon on the battlefield increase the HP upper limit by %s",
		name_en = "Defense bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในศูนย์บริการนี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มขีดจำกัดสูงสุดของ HP ขึ้น %s",
		icon = "config/card_ability/icon_fy3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam o limie de HP em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this service hall, all Pokémon on the battlefield increase the HP upper limit by %s",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 209,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 최대 HP %s 증가",
		preTalentIDs = {
			205,
			206
		},
		attrNum1 = {
			"6%",
			"10%",
			"14%",
			"18%",
			"22%"
		}
	},
	[210] = {
		levelUp = 5,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 4,
		attrType1 = 16,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased their Crit resistance by %s",
		name_en = "Defense bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบได้เพิ่มความต้านทานคริติคอลขึ้น %s",
		icon = "config/card_ability/icon_fy1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam Resistencia Crítica em %s",
		treeID = 2,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield have increased their Crit resistance by %s",
		effectType = 1,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 210,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 치명타 내성 %s 증가",
		preTalentIDs = {
			206
		},
		attrNum1 = {
			1000,
			1600,
			2200,
			2800,
			3400
		}
	},
	[211] = {
		effectType = 2,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 5,
		desc_th = "รับโล่เมื่อเริ่มการต่อสู้เป็นจำนวนเงิน $(30+skilllevel*5)$% HP จำกัด สำหรับ 2 รอบ",
		preLevel = 3,
		desc = "Get a shield at the start of battle for the amount of  $(30+skilllevel*5)$% HP limit for 2 rounds",
		name_en = "Defense bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_fy.png",
		desc_vn = "Obtenha um escudo no início da batalha no valor de $(30+skilllevel*5)$% de limite de HP por 2 rodadas",
		treeID = 2,
		desc_en = "Get a shield at the start of battle for the amount of  $(30+skilllevel*5)$% HP limit for 2 rounds",
		skillID = 63011,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 211,
		desc_kr = "전투 시작 시 최대 HP $(30+skilllevel*5)$% 획득, 실드 지속 시간: 2턴",
		preTalentIDs = {
			207,
			208
		}
	},
	[212] = {
		effectType = 2,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 5,
		desc_th = "เมื่อจบรอบใหญ่แต่ละรอบ รักษาพันธมิตรทั้งหมดโดย $(15+skilllevel*3)$% ของ HP ที่เสียไป",
		preLevel = 3,
		desc = "At the end of each big round, heal all allies by $(15+skilllevel*3)$% of lost HP",
		name_en = "Defense bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_fy.png",
		desc_vn = "No final de cada grande rodada, cure todos os aliados em $(15+skilllevel*3)$% do HP perdido",
		treeID = 2,
		desc_en = "At the end of each big round, heal all allies by $(15+skilllevel*3)$% of lost HP",
		skillID = 63012,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 212,
		desc_kr = "라운드 종료마다 아군 전체가 손실한 HP의 HP$(15+skilllevel*3)$%를 회복한다",
		preTalentIDs = {
			208,
			209
		}
	},
	[213] = {
		effectType = 2,
		name = "Defense bonus",
		name_tw = "防守加成",
		name_kr = "방어력 버프",
		costID = 5,
		desc_th = "ทุกครั้งที่ถูกโจมตี ฟื้นคืนความโกรธ $(30+skilllevel*6)$ เพิ่มเติม",
		preLevel = 3,
		desc = "Each time being attacked, restores an additional $(30+skilllevel*6)$ anger",
		name_en = "Defense bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_fy.png",
		desc_vn = "Cada vez que é atacado, restaura uma raiva adicional de $(30+skilllevel*6)$",
		treeID = 2,
		desc_en = "Each time being attacked, restores an additional $(30+skilllevel*6)$ anger",
		skillID = 63013,
		name_vn = "Defesa bônus",
		name_th = "Defense bonus",
		id = 213,
		desc_kr = "공격을 받을 따마다 분노치 $(30+skilllevel*6)$를 추가로 회복한다",
		preTalentIDs = {
			209,
			210
		}
	},
	[301] = {
		costID = 1,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		name_en = "Skill bonus",
		attrType1 = 5,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทุกตัวในสนามรบจะเพิ่มความเร็วในการฟื้นฟูความโกรธอีก %s",
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their rage recovery speed by %s",
		depth = 1,
		levelUp = 5,
		icon = "config/card_ability/icon_ty.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua velocidade de recuperação de raiva em %s",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their rage recovery speed by %s",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 301,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 분노 회복 속도 %s 증가",
		attrNum1 = slot4[301]
	},
	[302] = {
		effectType = 2,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 2,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ ความเร็วของการต่อสู้รอบแรกจะเพิ่มขึ้น $(8+skilllevel*8)$%",
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, the speed of the first round of the battle is increased by $(8+skilllevel*8)$%",
		name_en = "Skill bonus",
		depth = 2,
		levelUp = 5,
		icon = "config/card_ability/icon_kz1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, a velocidade da primeira rodada da batalha é aumentada em $(8+skilllevel*8)$%",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, the speed of the first round of the battle is increased by $(8+skilllevel*8)$%",
		skillID = 63024,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 302,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 첫 턴에 $(8+skilllevel*8)$% 스피드 증가",
		preTalentIDs = slot1[302]
	},
	[303] = {
		levelUp = 5,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 2,
		attrType1 = 13,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their speed by %s",
		name_en = "Skill bonus",
		depth = 2,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มความเร็วอีก %s",
		icon = "config/card_ability/icon_kz1.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua velocidade em %s",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their speed by %s",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 303,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 스피드 %s 증가",
		preTalentIDs = slot1[303],
		attrNum1 = slot4[303]
	},
	[304] = {
		levelUp = 5,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 3,
		attrType1 = 95,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their dodge rate by %s",
		name_en = "Skill bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่มอัตราการหลบหลีกขึ้น %s",
		icon = "config/card_ability/icon_kz2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua taxa de esquiva em %s",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their dodge rate by %s",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 304,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 회피율 %s 증가",
		preTalentIDs = {
			302
		},
		attrNum1 = slot4[304]
	},
	[305] = {
		levelUp = 5,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 3,
		attrType1 = 91,
		preLevel = 2,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their control resist rate by %s",
		name_en = "Skill bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทุกตัวในสนามรบจะเพิ่มอัตราการต้านทานการควบคุมอีก %s",
		icon = "config/card_ability/icon_ty.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua taxa de resistência  a controle em %s",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their control resist rate by %s",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 305,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 면역률 %s 증가",
		preTalentIDs = {
			302,
			303
		},
		attrNum1 = slot4[305]
	},
	[306] = {
		levelUp = 5,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 3,
		attrType1 = 90,
		preLevel = 2,
		desc = "In the battle between non-playersin this server gym, all the Pokémon in the battle will increase their control rate by %s",
		name_en = "Skill bonus",
		depth = 3,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในการต่อสู้จะเพิ่มอัตราการควบคุมของพวกเขาอีก %s",
		icon = "config/card_ability/icon_hf2.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam sua taxa de controle em %s",
		treeID = 3,
		desc_en = "In the battle between non-playersin this server gym, all the Pokémon in the battle will increase their control rate by %s",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 306,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 제어율 %s 증가",
		preTalentIDs = {
			303
		},
		attrNum1 = slot4[306]
	},
	[307] = {
		effectType = 2,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 4,
		desc_th = "มีโอกาส $(2+skilllevel*2)$% ที่จะหลีกเลี่ยงการตายได้หนึ่งครั้งในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในสถานบริการแห่งนี้",
		preLevel = 3,
		desc = "There is a $(2+skilllevel*2)$% chance of avoiding death once in the battle between non-players in this service gym.",
		name_en = "Skill bonus",
		depth = 4,
		levelUp = 5,
		icon = "config/card_ability/icon_kz1.png",
		desc_vn = "Há uma chance de $(2+skilllevel*2)$% de evitar a morte uma vez na batalha entre não jogadores neste ginásio.",
		treeID = 3,
		desc_en = "There is a $(2+skilllevel*2)$% chance of avoiding death once in the battle between non-players in this service gym.",
		skillID = 63025,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 307,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 $(2+skilllevel*2)$%의 확률로 1회 죽음 면역",
		preTalentIDs = {
			304
		}
	},
	[308] = {
		levelUp = 5,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 4,
		attrType1 = 26,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s lifesteal",
		name_en = "Skill bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทั้งหมดในสนามรบจะเพิ่ม %s ดูดชีวิต",
		icon = "config/card_ability/icon_hf3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam o roubo de vida em %s",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase %s lifesteal",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 308,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 흡혈 %s 증가",
		preTalentIDs = {
			304,
			305
		},
		attrNum1 = slot4[308]
	},
	[309] = {
		levelUp = 5,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 4,
		attrType1 = 28,
		preLevel = 3,
		desc = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their healing effect by %s",
		name_en = "Skill bonus",
		depth = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมเซิร์ฟเวอร์นี้ โปเกมอนทุกตัวในสนามรบจะเพิ่มผลการรักษาขึ้นอีก %s",
		icon = "config/card_ability/icon_kz3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, todos os Pokémon no campo de batalha aumentam o efeito de cura em %s",
		treeID = 3,
		desc_en = "In the battle between non-players in this server gym, all Pokémon on the battlefield increase their healing effect by %s",
		effectType = 1,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 309,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 모든 포켓몬 치료율 %s 증가",
		preTalentIDs = {
			305,
			306
		},
		attrNum1 = slot4[309]
	},
	[310] = {
		effectType = 2,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 4,
		desc_th = "ในการต่อสู้ระหว่างผู้ที่ไม่ใช่ผู้เล่นในยิมบริการนี้ เพิ่มความต้านทานเชิงลบ $(4+skilllevel*4)$%",
		preLevel = 3,
		desc = "In the battle between non-players of this service gym, increase the negative resistance by $(4+skilllevel*4)$%",
		name_en = "Skill bonus",
		depth = 4,
		levelUp = 5,
		icon = "config/card_ability/icon_hf3.png",
		desc_vn = "Na batalha entre não jogadores no ginásio deste servidor, aumente a resistência negativa em $(4+skilllevel*4)$%",
		treeID = 3,
		desc_en = "In the battle between non-players of this service gym, increase the negative resistance by $(4+skilllevel*4)$%",
		skillID = 63026,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 310,
		desc_kr = "본 서버 체육관의 비 유저간의 전투 중 디버프 저항 $(4+skilllevel*4)$% 증가",
		preTalentIDs = {
			306
		}
	},
	[311] = {
		effectType = 2,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 5,
		desc_th = "เมื่อโปเกมอนฝ่ายเดียวกันได้รับเอฟเฟกต์การควบคุม มีโอกาส $(50+skilllevel*10)$% ที่จะลบเอฟเฟกต์การควบคุม 1 อย่างทันที และทำงานเพียง 5 ครั้งในการต่อสู้ทั้งหมด",
		preLevel = 3,
		desc = "When ally Pokémon receive a control effect, $(50+skilllevel*10)$% chance to immediately dispel 1 control effect, and only trigger 5 times in the entire battle",
		name_en = "Skill bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_kz.png",
		desc_vn = "Quando um Pokémon aliado recebe um efeito de controle, $(50+skilllevel*10)$% de chance de dissipar imediatamente 1 efeito de controle e aciona apenas 5 vezes em toda a batalha",
		treeID = 3,
		desc_en = "When ally Pokémon receive a control effect, $(50+skilllevel*10)$% chance to immediately dispel 1 control effect, and only trigger 5 times in the entire battle",
		skillID = 63021,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 311,
		desc_kr = "아군 포켓콘이 제어 효과를 받을 시 $(50+skilllevel*10)$% 확률로 즉시 1개의 제어 효과를 제거하며, 전장에서 단 5회만 발동한다.",
		preTalentIDs = {
			307,
			308
		}
	},
	[312] = {
		effectType = 2,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 5,
		desc_th = "การโจมตีแต่ละครั้งจะมีผลการรักษาของเป้าหมายลดลงอย่างถาวร $(20+skilllevel*3)$% (ไม่สามารถลบล้างได้) ซึ่งสามารถซ้อนกันได้ 6 ครั้ง",
		preLevel = 3,
		desc = "Each attack comes with a permanent reduction of the target's healing effect by $(20+skilllevel*3)$% (unable to dispel), which can be stacked for 6 times",
		name_en = "Skill bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_hf.png",
		desc_vn = "Cada ataque vem com uma redução permanente do efeito de cura do alvo em $(20+skilllevel*3)$% (incapaz de dissipar), que pode ser acumulado por 6 vezes",
		treeID = 3,
		desc_en = "Each attack comes with a permanent reduction of the target's healing effect by $(20+skilllevel*3)$% (unable to dispel), which can be stacked for 6 times",
		skillID = 63022,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 312,
		desc_kr = "공격할 때마다 목표 $(20+skilllevel*3)$%의 치료 효과 영구적으로 감소한다 (디스펠 불가), 최대 중첩 수: 6회",
		preTalentIDs = {
			308,
			309
		}
	},
	[313] = {
		effectType = 2,
		name = "Skill bonus",
		name_tw = "技巧加成",
		name_kr = "기술 버프",
		costID = 5,
		desc_th = "เพิ่มความเร็ว $(10+skilllevel*2)$% เป็นเวลา 2 รอบ ก่อนเริ่มรอบ คุณจะสูญเสีย HP ปัจจุบันเพื่อสร้างความโกรธขึ้นใหม่ หาก HP ต่ำกว่าค่าที่กำหนด จะไม่ทริกเกอร์",
		preLevel = 3,
		desc = "Increase speed by $(10+skilllevel*2)$% for 2 rounds. Before the start of the round, you will lost your current HP to regenerate anger. If the HP is lower than a certain value, it will not trigger",
		name_en = "Skill bonus",
		depth = 5,
		levelUp = 5,
		icon = "config/card_ability/icon_hf.png",
		desc_vn = "Aumente a velocidade em $(10+nível de habilidade*2)$% por 2 rodadas. Antes do início da rodada, você perderá seu HP atual para regenerar a raiva. Se o HP for menor que um determinado valor, ele não será acionado",
		treeID = 3,
		desc_en = "Increase speed by $(10+skilllevel*2)$% for 2 rounds. Before the start of the round, you will lost your current HP to regenerate anger. If the HP is lower than a certain value, it will not trigger",
		skillID = 63023,
		name_vn = "Bônus de habilidade",
		name_th = "Skill bonus",
		id = 313,
		desc_kr = "2턴 간 $(10+skilllevel*2)$% 스피드 증가, 턴이 시작되기 전에 자신의 HP를 손실하여 분노치를 회복하며 HP가 일정한 수치 이하 시 발동되지 않는다",
		preTalentIDs = {
			309,
			310
		}
	},
	__default = {
		__index = {
			iconRate = 1,
			name = "加成详情",
			name_tw = "加成详情",
			name_kr = "加成详情",
			preLevel = 10,
			attrType1 = 0,
			name_en = "加成详情",
			desc = "",
			attrType3 = 0,
			levelUp = 10,
			desc_th = "",
			icon = "city/drawcard/draw/icon_jbc1.png",
			desc_vn = "",
			desc_en = "",
			attrType2 = 0,
			name_vn = "加成详情",
			name_th = "加成详情",
			desc_kr = "",
			preTalentIDs = slot1.default,
			attrNum1 = slot4.default,
			attrNum2 = slot2.default,
			attrNum3 = ({
				default = slot0[1]
			}).default
		}
	}
}

return csv.gym.talent_buff
