--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['union_fight']['rank_point'] = {
	[1] = {
		id = 1,
		point = 2000
	},
	[2] = {
		id = 2,
		point = 1000
	},
	[3] = {
		id = 3,
		point = 500
	},
	[4] = {
		id = 4,
		point = 300
	},
	[5] = {
		id = 5,
		point = 100
	},
	__size = 5,
	__default = {
		__index = {
			point = 0
		}
	}
}
return csv.union_fight.rank_point