--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[5] = {['coin13'] = 1000, __size = 1}, 
	[6] = {150, 150}, 
	[7] = {'cn', 'en', 'tw', 'kr'}, 
	[11] = {['coin13'] = 800, __size = 1}, 
	[16] = {['coin13'] = 75000, __size = 1}, 
	[19] = {['coin13'] = 60000, __size = 1}, 
	[29] = {['coin13'] = 20000, __size = 1}, 
	[37] = {'cn', 'kr'}, __size = 9}
local __data_t__languages = {
	[201] = __predefine_t__[7],
	[1051] = __predefine_t__[7],
	[1041] = __predefine_t__[7],
	[1141] = __predefine_t__[37],
	[1021] = __predefine_t__[7],
	[1091] = __predefine_t__[7],
	[1081] = __predefine_t__[7],
	[211] = __predefine_t__[7],
	[1061] = __predefine_t__[7],
	[1121] = __predefine_t__[7],
	[1131] = __predefine_t__[37],
	[1151] = __predefine_t__[7],
	[1011] = __predefine_t__[7],
	[1111] = __predefine_t__[7],
	[241] = __predefine_t__[7],
	[221] = __predefine_t__[7],
	[1101] = __predefine_t__[7],
	[1071] = __predefine_t__[7],
	[1031] = __predefine_t__[7],
	[231] = __predefine_t__[7],
	[1001] = __predefine_t__[7]
}
local __data_t__levelRange = {
	[201] = __predefine_t__[6],
	[241] = __predefine_t__[6],
	[231] = __predefine_t__[6],
	[221] = __predefine_t__[6],
	[211] = __predefine_t__[6]
}
local __data_t__costMap = {
	[201] = __predefine_t__[5],
	[1051] = __predefine_t__[19],
	[1021] = __predefine_t__[16],
	[1091] = __predefine_t__[29],
	[211] = __predefine_t__[5],
	[1061] = __predefine_t__[16],
	[1131] = __predefine_t__[29],
	[1151] = __predefine_t__[29],
	[1011] = __predefine_t__[16],
	["default"] = __predefine_t__[1],
	[241] = __predefine_t__[11],
	[1031] = __predefine_t__[19],
	[231] = __predefine_t__[11],
	[221] = __predefine_t__[5]
}
local __data_t__itemMap = {
	["default"] = __predefine_t__[1]
}

csv['cross']['mine']['shop'] = {
	[201] = {
		id = 201,
		itemMap = {[21901] = 5, __size = 1},
		costMap = __data_t__costMap[201],
		-- {['coin13'] = 1000, __size = 1}
		exchangeLimit = 3,
		regainHour = 10,
		levelRange = __data_t__levelRange[201],
		-- {150, 150}
		languages = __data_t__languages[201]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[211] = {
		id = 211,
		itemMap = {[23001] = 5, __size = 1},
		costMap = __data_t__costMap[211],
		-- {['coin13'] = 1000, __size = 1}
		exchangeLimit = 3,
		regainHour = 10,
		levelRange = __data_t__levelRange[211],
		-- {150, 150}
		languages = __data_t__languages[211]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[221] = {
		id = 221,
		itemMap = {[22231] = 5, __size = 1},
		costMap = __data_t__costMap[221],
		-- {['coin13'] = 1000, __size = 1}
		exchangeLimit = 3,
		regainHour = 10,
		levelRange = __data_t__levelRange[221],
		-- {150, 150}
		languages = __data_t__languages[221]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[231] = {
		id = 231,
		itemMap = {[23141] = 5, __size = 1},
		costMap = __data_t__costMap[231],
		-- {['coin13'] = 800, __size = 1}
		exchangeLimit = 3,
		regainHour = 10,
		levelRange = __data_t__levelRange[231],
		-- {150, 150}
		languages = __data_t__languages[231]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[241] = {
		id = 241,
		itemMap = {[23411] = 5, __size = 1},
		costMap = __data_t__costMap[241],
		-- {['coin13'] = 800, __size = 1}
		exchangeLimit = 3,
		regainHour = 10,
		levelRange = __data_t__levelRange[241],
		-- {150, 150}
		languages = __data_t__languages[241]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1001] = {
		id = 1001,
		itemMap = {[21261] = 1, __size = 1},
		costMap = {['coin13'] = 120000, __size = 1},
		exchangeLimit = 2,
		regainHour = 30,
		sortValue = 1,
		languages = __data_t__languages[1001]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1011] = {
		id = 1011,
		itemMap = {[23151] = 3, __size = 1},
		costMap = __data_t__costMap[1011],
		-- {['coin13'] = 75000, __size = 1}
		exchangeLimit = 2,
		regainHour = 24,
		sortValue = 2,
		languages = __data_t__languages[1011]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1021] = {
		id = 1021,
		itemMap = {[502] = 1, __size = 1},
		costMap = __data_t__costMap[1021],
		-- {['coin13'] = 75000, __size = 1}
		exchangeLimit = 2,
		regainHour = 16,
		sortValue = 3,
		languages = __data_t__languages[1021]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1031] = {
		id = 1031,
		itemMap = {[21941] = 3, __size = 1},
		costMap = __data_t__costMap[1031],
		-- {['coin13'] = 60000, __size = 1}
		exchangeLimit = 2,
		regainHour = 18,
		sortValue = 4,
		languages = __data_t__languages[1031]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1041] = {
		id = 1041,
		itemMap = {[28504] = 1, __size = 1},
		costMap = {['coin13'] = 50000, __size = 1},
		exchangeLimit = 2,
		regainHour = 24,
		sortValue = 5,
		languages = __data_t__languages[1041]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1051] = {
		id = 1051,
		itemMap = {[21951] = 3, __size = 1},
		costMap = __data_t__costMap[1051],
		-- {['coin13'] = 60000, __size = 1}
		exchangeLimit = 2,
		regainHour = 18,
		sortValue = 6,
		languages = __data_t__languages[1051]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1061] = {
		id = 1061,
		itemMap = {['talent_point'] = 1, __size = 1},
		costMap = __data_t__costMap[1061],
		-- {['coin13'] = 75000, __size = 1}
		exchangeLimit = 2,
		regainHour = 24,
		sortValue = 7,
		languages = __data_t__languages[1061]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1071] = {
		id = 1071,
		itemMap = {[28505] = 1, __size = 1},
		costMap = {['coin13'] = 180000, __size = 1},
		exchangeLimit = 2,
		regainHour = 60,
		sortValue = 8,
		languages = __data_t__languages[1071]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1081] = {
		id = 1081,
		itemMap = {[529] = 500, __size = 1},
		costMap = {['coin13'] = 90000, __size = 1},
		exchangeLimit = 2,
		regainHour = 24,
		sortValue = 11,
		languages = __data_t__languages[1081]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1091] = {
		id = 1091,
		itemMap = {[514] = 60, __size = 1},
		costMap = __data_t__costMap[1091],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 2,
		regainHour = 48,
		sortValue = 13,
		languages = __data_t__languages[1091]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1101] = {
		id = 1101,
		itemMap = {[514] = 15, __size = 1},
		costMap = {['coin13'] = 5000, __size = 1},
		exchangeLimit = 10,
		regainHour = 12,
		sortValue = 14,
		languages = __data_t__languages[1101]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1111] = {
		id = 1111,
		itemMap = {[15] = 10, __size = 1},
		costMap = {['coin13'] = 15000, __size = 1},
		exchangeLimit = 2,
		regainHour = 24,
		sortValue = 15,
		languages = __data_t__languages[1111]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1121] = {
		id = 1121,
		itemMap = {[15] = 2, __size = 1},
		costMap = {['coin13'] = 3000, __size = 1},
		exchangeLimit = 12,
		regainHour = 4,
		sortValue = 16,
		languages = __data_t__languages[1121]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1131] = {
		id = 1131,
		itemMap = {[111] = 100, __size = 1},
		costMap = __data_t__costMap[1131],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 3,
		regainHour = 8,
		sortValue = 10,
		languages = __data_t__languages[1131]
		-- {'cn', 'kr'}
	},
	[1141] = {
		id = 1141,
		itemMap = {[112] = 20, __size = 1},
		costMap = {['coin13'] = 30000, __size = 1},
		exchangeLimit = 3,
		regainHour = 8,
		sortValue = 12,
		languages = __data_t__languages[1141]
		-- {'cn', 'kr'}
	},
	[1151] = {
		id = 1151,
		itemMap = {[5000] = 20, __size = 1},
		costMap = __data_t__costMap[1151],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 2,
		regainHour = 12,
		sortValue = 17,
		languages = __data_t__languages[1151]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	__size = 21,
	__default = {
		__index = {
			itemMap = __data_t__itemMap["default"]	--[[ {__size = 0}]],
			costMap = __data_t__costMap["default"]	--[[ {__size = 0}]],
			exchangeLimit = -1,
			regainHour = 0,
			beginDate = 0,
			endDate = 20990101,
			vipStart = 0,
			levelRange = {1, 150},
			limitType = 0,
			limitTimes = 0,
			showUnable = false,
			sortValue = 0,
			languages = {'cn'}
		}
	}
}
return csv.cross.mine.shop