--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['mimicry']['rank_award'] = {
	[1] = {
		id = 1,
		rankMax = 1,
		award = {['rmb'] = 200, ['gold'] = 2000000, [15] = 30, [161] = 850, __size = 4}
	},
	[2] = {
		id = 2,
		rankMax = 2,
		award = {['rmb'] = 180, ['gold'] = 1800000, [15] = 27, [161] = 750, __size = 4}
	},
	[3] = {
		id = 3,
		rankMax = 3,
		award = {['rmb'] = 160, ['gold'] = 1600000, [15] = 24, [161] = 660, __size = 4}
	},
	[4] = {
		id = 4,
		rankMax = 6,
		award = {['rmb'] = 140, ['gold'] = 1400000, [15] = 22, [161] = 610, __size = 4}
	},
	[5] = {
		id = 5,
		rankMax = 10,
		award = {['rmb'] = 120, ['gold'] = 1200000, [15] = 20, [161] = 560, __size = 4}
	},
	[6] = {
		id = 6,
		rankMax = 30,
		award = {['rmb'] = 100, ['gold'] = 1120000, [15] = 18, [161] = 510, __size = 4}
	},
	[7] = {
		id = 7,
		rankMax = 60,
		award = {['rmb'] = 90, ['gold'] = 1040000, [15] = 16, [161] = 460, __size = 4}
	},
	[8] = {
		id = 8,
		rankMax = 100,
		award = {['rmb'] = 80, ['gold'] = 960000, [15] = 14, [161] = 430, __size = 4}
	},
	[9] = {
		id = 9,
		rankMax = 300,
		award = {['rmb'] = 70, ['gold'] = 880000, [15] = 13, [161] = 400, __size = 4}
	},
	[10] = {
		id = 10,
		rankMax = 600,
		award = {['rmb'] = 60, ['gold'] = 800000, [15] = 12, [161] = 360, __size = 4}
	},
	[11] = {
		id = 11,
		rankMax = 1000,
		award = {['rmb'] = 55, ['gold'] = 720000, [15] = 11, [161] = 330, __size = 4}
	},
	[12] = {
		id = 12,
		rankMax = 99999,
		award = {['rmb'] = 50, ['gold'] = 640000, [15] = 10, [161] = 300, __size = 4}
	},
	__size = 12,
	__default = {
		__index = {
			rankMax = 0,
			award = {__size = 0}
		}
	}
}
return csv.mimicry.rank_award