--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['mimicry']['team'] = {
	[1] = {
		id = 1,
		system = 'union_skill',
		level = 24
	},
	[2] = {
		id = 2,
		csvID = 2,
		system = 'union_skill',
		level = 24
	},
	[3] = {
		id = 3,
		csvID = 3,
		system = 'union_skill',
		level = 24
	},
	[4] = {
		id = 4,
		csvID = 4,
		system = 'union_skill',
		level = 24
	},
	[5] = {
		id = 5,
		csvID = 5,
		system = 'union_skill',
		level = 24
	},
	[6] = {
		id = 6,
		csvID = 6,
		system = 'union_skill',
		level = 24
	},
	[7] = {
		id = 7,
		csvID = 7,
		system = 'union_skill',
		level = 24
	},
	[8] = {
		id = 8,
		csvID = 8,
		system = 'union_skill',
		level = 24
	},
	[9] = {
		id = 9,
		csvID = 9,
		system = 'union_skill',
		level = 24
	},
	[10] = {
		id = 10,
		csvID = 10,
		system = 'union_skill',
		level = 24
	},
	[11] = {
		id = 11,
		csvID = 11,
		system = 'union_skill',
		level = 24
	},
	[12] = {
		id = 12,
		csvID = 12,
		system = 'union_skill',
		level = 24
	},
	[13] = {
		id = 13,
		csvID = 13,
		system = 'union_skill',
		level = 24
	},
	[14] = {
		id = 14,
		csvID = 14,
		system = 'union_skill',
		level = 24
	},
	[15] = {
		id = 15,
		csvID = 15,
		system = 'union_skill',
		level = 24
	},
	[16] = {
		id = 16,
		csvID = 16,
		system = 'union_skill',
		level = 24
	},
	[17] = {
		id = 17,
		csvID = 17,
		system = 'union_skill',
		level = 24
	},
	[101] = {
		id = 101,
		system = 'explorer',
		level = 12
	},
	[102] = {
		id = 102,
		csvID = 2,
		system = 'explorer',
		level = 12
	},
	[103] = {
		id = 103,
		csvID = 3,
		system = 'explorer',
		level = 12
	},
	[104] = {
		id = 104,
		csvID = 4,
		system = 'explorer',
		level = 12
	},
	[105] = {
		id = 105,
		csvID = 5,
		system = 'explorer',
		level = 12
	},
	[106] = {
		id = 106,
		csvID = 6,
		system = 'explorer',
		level = 12
	},
	[107] = {
		id = 107,
		csvID = 7,
		system = 'explorer',
		level = 12
	},
	[108] = {
		id = 108,
		csvID = 8,
		system = 'explorer',
		level = 12
	},
	[109] = {
		id = 109,
		csvID = 9,
		system = 'explorer',
		level = 12
	},
	[201] = {
		id = 201,
		system = 'component',
		level = 12
	},
	[202] = {
		id = 202,
		csvID = 2,
		system = 'component',
		level = 12
	},
	[203] = {
		id = 203,
		csvID = 3,
		system = 'component',
		level = 12
	},
	[204] = {
		id = 204,
		csvID = 4,
		system = 'component',
		level = 12
	},
	[205] = {
		id = 205,
		csvID = 5,
		system = 'component',
		level = 12
	},
	[206] = {
		id = 206,
		csvID = 6,
		system = 'component',
		level = 12
	},
	[207] = {
		id = 207,
		csvID = 7,
		system = 'component',
		level = 12
	},
	[208] = {
		id = 208,
		csvID = 8,
		system = 'component',
		level = 12
	},
	[209] = {
		id = 209,
		csvID = 9,
		system = 'component',
		level = 12
	},
	[210] = {
		id = 210,
		csvID = 10,
		system = 'component',
		level = 12
	},
	[211] = {
		id = 211,
		csvID = 11,
		system = 'component',
		level = 12
	},
	[212] = {
		id = 212,
		csvID = 12,
		system = 'component',
		level = 12
	},
	[213] = {
		id = 213,
		csvID = 13,
		system = 'component',
		level = 12
	},
	[214] = {
		id = 214,
		csvID = 14,
		system = 'component',
		level = 12
	},
	[215] = {
		id = 215,
		csvID = 15,
		system = 'component',
		level = 12
	},
	[216] = {
		id = 216,
		csvID = 16,
		system = 'component',
		level = 12
	},
	[217] = {
		id = 217,
		csvID = 17,
		system = 'component',
		level = 12
	},
	[218] = {
		id = 218,
		csvID = 18,
		system = 'component',
		level = 12
	},
	[219] = {
		id = 219,
		csvID = 19,
		system = 'component',
		level = 12
	},
	[220] = {
		id = 220,
		csvID = 20,
		system = 'component',
		level = 12
	},
	[221] = {
		id = 221,
		csvID = 21,
		system = 'component',
		level = 12
	},
	[222] = {
		id = 222,
		csvID = 22,
		system = 'component',
		level = 12
	},
	[223] = {
		id = 223,
		csvID = 23,
		system = 'component',
		level = 12
	},
	[224] = {
		id = 224,
		csvID = 24,
		system = 'component',
		level = 12
	},
	[225] = {
		id = 225,
		csvID = 25,
		system = 'component',
		level = 12
	},
	[226] = {
		id = 226,
		csvID = 26,
		system = 'component',
		level = 12
	},
	[227] = {
		id = 227,
		csvID = 27,
		system = 'component',
		level = 12
	},
	[228] = {
		id = 228,
		csvID = 28,
		system = 'component',
		level = 12
	},
	[229] = {
		id = 229,
		csvID = 29,
		system = 'component',
		level = 12
	},
	[230] = {
		id = 230,
		csvID = 30,
		system = 'component',
		level = 12
	},
	[231] = {
		id = 231,
		csvID = 31,
		system = 'component',
		level = 12
	},
	[232] = {
		id = 232,
		csvID = 32,
		system = 'component',
		level = 12
	},
	[233] = {
		id = 233,
		csvID = 33,
		system = 'component',
		level = 12
	},
	[301] = {
		id = 301,
		system = 'attr_skills',
		level = 100
	},
	[302] = {
		id = 302,
		csvID = 2,
		system = 'attr_skills',
		level = 100
	},
	[303] = {
		id = 303,
		csvID = 3,
		system = 'attr_skills',
		level = 100
	},
	[304] = {
		id = 304,
		csvID = 4,
		system = 'attr_skills',
		level = 100
	},
	[305] = {
		id = 305,
		csvID = 5,
		system = 'attr_skills',
		level = 100
	},
	[307] = {
		id = 307,
		csvID = 7,
		system = 'attr_skills',
		level = 20
	},
	[308] = {
		id = 308,
		csvID = 8,
		system = 'attr_skills',
		level = 20
	},
	[309] = {
		id = 309,
		csvID = 9,
		system = 'attr_skills',
		level = 20
	},
	[310] = {
		id = 310,
		csvID = 10,
		system = 'attr_skills',
		level = 20
	},
	__size = 68,
	__default = {
		__index = {
			csvID = 1,
			system = '',
			level = 0
		}
	}
}
return csv.mimicry.team