--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {__size = 0}, 
	[5] = {[4] = 1, __size = 1}, 
	[9] = {['rmb'] = 300, ['gold'] = 2000000, ['coin5'] = 3600, [502] = 10, __size = 4}, 
	[10] = {[3] = 3, __size = 1}, 
	[14] = {[6] = 1, __size = 1}, 
	[79] = {'cn', 'kr', 'tw', 'en_us'}, 
	[92] = {'cn', 'tw', 'en_us'}, 
	[123] = {[5] = 1, __size = 1}, __size = 8}
local __data_t__costItems = {
	["default"] = __predefine_t__[2],
	[1102] = __predefine_t__[9],
	[1103] = __predefine_t__[9],
	[1101] = __predefine_t__[9]
}
local __data_t__costContractMap = {
	[1102] = __predefine_t__[10],
	[1546] = __predefine_t__[14],
	[1547] = __predefine_t__[14],
	[1544] = __predefine_t__[14],
	[1545] = __predefine_t__[14],
	[1542] = __predefine_t__[14],
	[1543] = __predefine_t__[14],
	[1540] = __predefine_t__[14],
	[1541] = __predefine_t__[14],
	[1658] = __predefine_t__[123],
	[1548] = __predefine_t__[14],
	[1549] = __predefine_t__[14],
	[1659] = __predefine_t__[123],
	[1678] = __predefine_t__[123],
	[1679] = __predefine_t__[123],
	[1674] = __predefine_t__[123],
	[1675] = __predefine_t__[123],
	[1676] = __predefine_t__[123],
	[1677] = __predefine_t__[123],
	[1670] = __predefine_t__[123],
	[1671] = __predefine_t__[123],
	[1672] = __predefine_t__[123],
	[1673] = __predefine_t__[123],
	[1700] = __predefine_t__[123],
	[1701] = __predefine_t__[123],
	[1652] = __predefine_t__[123],
	[1703] = __predefine_t__[123],
	[1653] = __predefine_t__[123],
	[1650] = __predefine_t__[123],
	[1551] = __predefine_t__[14],
	[1550] = __predefine_t__[14],
	[1702] = __predefine_t__[123],
	[1552] = __predefine_t__[14],
	[1704] = __predefine_t__[123],
	[1554] = __predefine_t__[14],
	[1656] = __predefine_t__[123],
	[1657] = __predefine_t__[123],
	[1669] = __predefine_t__[123],
	[1668] = __predefine_t__[123],
	[1667] = __predefine_t__[123],
	[1666] = __predefine_t__[123],
	[1665] = __predefine_t__[123],
	[1655] = __predefine_t__[123],
	[1663] = __predefine_t__[123],
	[1662] = __predefine_t__[123],
	[1661] = __predefine_t__[123],
	[1660] = __predefine_t__[123],
	[1524] = __predefine_t__[14],
	[1525] = __predefine_t__[14],
	[1526] = __predefine_t__[14],
	[1527] = __predefine_t__[14],
	[1520] = __predefine_t__[14],
	[1521] = __predefine_t__[14],
	[1522] = __predefine_t__[14],
	[1523] = __predefine_t__[14],
	[1403] = __predefine_t__[14],
	[1402] = __predefine_t__[14],
	[1401] = __predefine_t__[14],
	[1651] = __predefine_t__[123],
	[1528] = __predefine_t__[14],
	[1529] = __predefine_t__[14],
	[1654] = __predefine_t__[123],
	[1103] = __predefine_t__[10],
	[1664] = __predefine_t__[123],
	[1645] = __predefine_t__[123],
	[1644] = __predefine_t__[123],
	[1647] = __predefine_t__[123],
	[1646] = __predefine_t__[123],
	[1641] = __predefine_t__[123],
	[1640] = __predefine_t__[123],
	[1643] = __predefine_t__[123],
	[1642] = __predefine_t__[123],
	[1649] = __predefine_t__[123],
	[1648] = __predefine_t__[123],
	[1537] = __predefine_t__[14],
	[1536] = __predefine_t__[14],
	[1535] = __predefine_t__[14],
	[1534] = __predefine_t__[14],
	[1533] = __predefine_t__[14],
	[1532] = __predefine_t__[14],
	[1531] = __predefine_t__[14],
	[1530] = __predefine_t__[14],
	[1006] = __predefine_t__[5],
	[1004] = __predefine_t__[5],
	[1002] = __predefine_t__[5],
	[1539] = __predefine_t__[14],
	[1538] = __predefine_t__[14],
	["default"] = __predefine_t__[2],
	[1630] = __predefine_t__[123],
	[1631] = __predefine_t__[123],
	[1632] = __predefine_t__[123],
	[1633] = __predefine_t__[123],
	[1634] = __predefine_t__[123],
	[1635] = __predefine_t__[123],
	[1636] = __predefine_t__[123],
	[1637] = __predefine_t__[123],
	[1638] = __predefine_t__[123],
	[1639] = __predefine_t__[123],
	[1502] = __predefine_t__[14],
	[1501] = __predefine_t__[14],
	[1507] = __predefine_t__[14],
	[1504] = __predefine_t__[14],
	[1505] = __predefine_t__[14],
	[1508] = __predefine_t__[14],
	[1509] = __predefine_t__[14],
	[1623] = __predefine_t__[123],
	[1622] = __predefine_t__[123],
	[1621] = __predefine_t__[123],
	[1620] = __predefine_t__[123],
	[1627] = __predefine_t__[123],
	[1626] = __predefine_t__[123],
	[1625] = __predefine_t__[123],
	[1624] = __predefine_t__[123],
	[1629] = __predefine_t__[123],
	[1628] = __predefine_t__[123],
	[1519] = __predefine_t__[14],
	[1518] = __predefine_t__[14],
	[1101] = __predefine_t__[10],
	[1515] = __predefine_t__[14],
	[1514] = __predefine_t__[14],
	[1517] = __predefine_t__[14],
	[1516] = __predefine_t__[14],
	[1511] = __predefine_t__[14],
	[1510] = __predefine_t__[14],
	[1513] = __predefine_t__[14],
	[1512] = __predefine_t__[14],
	[1618] = __predefine_t__[123],
	[1619] = __predefine_t__[123],
	[1616] = __predefine_t__[123],
	[1617] = __predefine_t__[123],
	[1614] = __predefine_t__[123],
	[1615] = __predefine_t__[123],
	[1612] = __predefine_t__[123],
	[1613] = __predefine_t__[123],
	[1610] = __predefine_t__[123],
	[1611] = __predefine_t__[123],
	[1696] = __predefine_t__[123],
	[1697] = __predefine_t__[123],
	[1694] = __predefine_t__[123],
	[1695] = __predefine_t__[123],
	[1692] = __predefine_t__[123],
	[1693] = __predefine_t__[123],
	[1690] = __predefine_t__[123],
	[1691] = __predefine_t__[123],
	[1698] = __predefine_t__[123],
	[1699] = __predefine_t__[123],
	[1609] = __predefine_t__[123],
	[1608] = __predefine_t__[123],
	[1601] = __predefine_t__[123],
	[1603] = __predefine_t__[123],
	[1602] = __predefine_t__[123],
	[1605] = __predefine_t__[123],
	[1604] = __predefine_t__[123],
	[1607] = __predefine_t__[123],
	[1606] = __predefine_t__[123],
	[1681] = __predefine_t__[123],
	[1680] = __predefine_t__[123],
	[1683] = __predefine_t__[123],
	[1682] = __predefine_t__[123],
	[1685] = __predefine_t__[123],
	[1684] = __predefine_t__[123],
	[1687] = __predefine_t__[123],
	[1686] = __predefine_t__[123],
	[1689] = __predefine_t__[123],
	[1688] = __predefine_t__[123]
}
local __data_t__targetParam1 = {
	["default"] = __predefine_t__[2]
}
local __data_t__targetParam3 = {
	["default"] = __predefine_t__[2]
}
local __data_t__targetParam2 = {
	["default"] = __predefine_t__[2]
}
local __data_t__languages = {
	[1540] = __predefine_t__[92],
	[1541] = __predefine_t__[92],
	[1538] = __predefine_t__[79],
	[1658] = __predefine_t__[79],
	[1659] = __predefine_t__[79],
	[1674] = __predefine_t__[92],
	[1670] = __predefine_t__[92],
	[1657] = __predefine_t__[79],
	[1672] = __predefine_t__[92],
	[1673] = __predefine_t__[92],
	[1671] = __predefine_t__[92],
	[1537] = __predefine_t__[79],
	[1536] = __predefine_t__[79],
	[1535] = __predefine_t__[79],
	[1534] = __predefine_t__[79],
	[1533] = __predefine_t__[79],
	[1539] = __predefine_t__[92],
	[1669] = __predefine_t__[92],
	[1668] = __predefine_t__[79],
	[1667] = __predefine_t__[79],
	[1666] = __predefine_t__[79],
	[1665] = __predefine_t__[79],
	[1664] = __predefine_t__[79],
	[1663] = __predefine_t__[79],
	[1662] = __predefine_t__[79],
	[1661] = __predefine_t__[79],
	[1660] = __predefine_t__[79]
}

csv['contract']['activate_book'] = {
	[1002] = {
		id = 1002,
		exchangeTimes = 1,
		targetDesc1 = '养成开启后，竞技场累计胜利100次',
		targetArg1 = 100,
		targetType1 = 42,
		contractCsvID = 81403,
		costItems = {['gold'] = 2000000, ['rmb'] = 500, ['coin1'] = 48000, __size = 3},
		costContractMap = __data_t__costContractMap[1002]
		-- {[4] = 1, __size = 1}
	},
	[1004] = {
		id = 1004,
		exchangeTimes = 1,
		targetDesc1 = '养成开启后，以太乐园累计通关10次',
		targetArg1 = 10,
		targetType1 = 130,
		contractCsvID = 82403,
		costItems = {['coin2'] = 48000, ['rmb'] = 500, ['gold'] = 2000000, __size = 3},
		costContractMap = __data_t__costContractMap[1004]
		-- {[4] = 1, __size = 1}
	},
	[1006] = {
		id = 1006,
		exchangeTimes = 1,
		targetDesc1 = '养成开启后，公会捐献50次',
		targetArg1 = 50,
		targetType1 = 55,
		contractCsvID = 83404,
		costItems = {['gold'] = 2000000, ['rmb'] = 500, ['coin3'] = 24000, __size = 3},
		costContractMap = __data_t__costContractMap[1006]
		-- {[4] = 1, __size = 1}
	},
	[1101] = {
		id = 1101,
		exchangeTimes = 1,
		targetDesc1 = '小火龙系列达到12星',
		targetType1 = 128,
		contractCsvID = 81401,
		targetParam1 = {[12] = {11}, __size = 1},
		costItems = __data_t__costItems[1101],
		-- {['rmb'] = 300, ['gold'] = 2000000, ['coin5'] = 3600, [502] = 10, __size = 4}
		costContractMap = __data_t__costContractMap[1101]
		-- {[3] = 3, __size = 1}
	},
	[1102] = {
		id = 1102,
		exchangeTimes = 1,
		targetDesc1 = '杰尼龟系列达到12星',
		targetType1 = 128,
		contractCsvID = 82402,
		targetParam1 = {[12] = {21}, __size = 1},
		costItems = __data_t__costItems[1102],
		-- {['rmb'] = 300, ['gold'] = 2000000, ['coin5'] = 3600, [502] = 10, __size = 4}
		costContractMap = __data_t__costContractMap[1102]
		-- {[3] = 3, __size = 1}
	},
	[1103] = {
		id = 1103,
		exchangeTimes = 1,
		targetDesc1 = '妙蛙种子系列达到12星',
		targetType1 = 128,
		contractCsvID = 83402,
		targetParam1 = {[12] = {1}, __size = 1},
		costItems = __data_t__costItems[1103],
		-- {['rmb'] = 300, ['gold'] = 2000000, ['coin5'] = 3600, [502] = 10, __size = 4}
		costContractMap = __data_t__costContractMap[1103]
		-- {[3] = 3, __size = 1}
	},
	[1401] = {
		id = 1401,
		exchangeTimes = 1,
		targetDesc1 = '拥有超级裂空座解锁',
		targetArg1 = 1982,
		targetType1 = 13,
		contractCsvID = 81601,
		costItems = {[21981] = 30, ['gold'] = 8000000, ['rmb'] = 2000, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1401]
		-- {[6] = 1, __size = 1}
	},
	[1402] = {
		id = 1402,
		exchangeTimes = 1,
		targetDesc1 = '拥有原始固拉多解锁',
		targetArg1 = 1972,
		targetType1 = 13,
		contractCsvID = 82603,
		costItems = {['gold'] = 8000000, ['rmb'] = 2000, [521] = 10, [21971] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1402]
		-- {[6] = 1, __size = 1}
	},
	[1403] = {
		id = 1403,
		exchangeTimes = 1,
		targetDesc1 = '拥有原始盖欧卡解锁',
		targetArg1 = 1962,
		targetType1 = 13,
		contractCsvID = 83603,
		costItems = {['gold'] = 8000000, [21961] = 30, ['rmb'] = 2000, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1403]
		-- {[6] = 1, __size = 1}
	},
	[1501] = {
		id = 1501,
		exchangeTimes = 1,
		targetDesc1 = '帕路奇亚达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81602,
		targetParam1 = {[12] = {2361}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [22361] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1501]
		-- {[6] = 1, __size = 1}
	},
	[1502] = {
		id = 1502,
		exchangeTimes = 1,
		targetDesc1 = '雷吉奇卡斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81603,
		targetParam1 = {[12] = {2381}, __size = 1},
		costItems = {['gold'] = 6000000, [22381] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1502]
		-- {[6] = 1, __size = 1}
	},
	[1504] = {
		id = 1504,
		exchangeTimes = 1,
		targetDesc1 = '美录坦达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82601,
		targetParam1 = {[12] = {4171}, __size = 1},
		costItems = {['gold'] = 6000000, [24171] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1504]
		-- {[6] = 1, __size = 1}
	},
	[1505] = {
		id = 1505,
		exchangeTimes = 1,
		targetDesc1 = '酋雷姆达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82602,
		targetParam1 = {[12] = {3241}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [23241] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1505]
		-- {[6] = 1, __size = 1}
	},
	[1507] = {
		id = 1507,
		exchangeTimes = 1,
		targetDesc1 = '谢米达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83601,
		targetParam1 = {[12] = {2441}, __size = 1},
		costItems = {[22441] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1507]
		-- {[6] = 1, __size = 1}
	},
	[1508] = {
		id = 1508,
		exchangeTimes = 1,
		targetDesc1 = '达克莱伊达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83602,
		targetParam1 = {[12] = {2431}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [22431] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1508]
		-- {[6] = 1, __size = 1}
	},
	[1509] = {
		id = 1509,
		exchangeTimes = 1,
		targetDesc1 = '帝牙卢卡达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81604,
		targetParam1 = {[12] = {2351}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [22351] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1509]
		-- {[6] = 1, __size = 1}
	},
	[1510] = {
		id = 1510,
		exchangeTimes = 1,
		targetDesc1 = '玛夏多达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81605,
		targetParam1 = {[12] = {4121}, __size = 1},
		costItems = {[24121] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1510]
		-- {[6] = 1, __size = 1}
	},
	[1511] = {
		id = 1511,
		exchangeTimes = 1,
		targetDesc1 = '骑拉帝纳达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82604,
		targetParam1 = {[12] = {2391}, __size = 1},
		costItems = {[22391] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1511]
		-- {[6] = 1, __size = 1}
	},
	[1512] = {
		id = 1512,
		exchangeTimes = 1,
		targetDesc1 = '捷克罗姆达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81606,
		targetParam1 = {[12] = {3221}, __size = 1},
		costItems = {['gold'] = 6000000, [23221] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1512]
		-- {[6] = 1, __size = 1}
	},
	[1513] = {
		id = 1513,
		exchangeTimes = 1,
		targetDesc1 = '莱希拉姆达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82605,
		targetParam1 = {[12] = {3211}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [23211] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1513]
		-- {[6] = 1, __size = 1}
	},
	[1514] = {
		id = 1514,
		exchangeTimes = 1,
		targetDesc1 = '玛纳霏达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83604,
		targetParam1 = {[12] = {2421}, __size = 1},
		costItems = {['gold'] = 6000000, [22421] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1514]
		-- {[6] = 1, __size = 1}
	},
	[1515] = {
		id = 1515,
		exchangeTimes = 1,
		targetDesc1 = '美洛耶塔达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81607,
		targetParam1 = {[12] = {3261}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [23261] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1515]
		-- {[6] = 1, __size = 1}
	},
	[1516] = {
		id = 1516,
		exchangeTimes = 1,
		targetDesc1 = '盖诺赛克特达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81608,
		targetParam1 = {[12] = {3271}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [23271] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1516]
		-- {[6] = 1, __size = 1}
	},
	[1517] = {
		id = 1517,
		exchangeTimes = 1,
		targetDesc1 = '哲尔尼亚斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83605,
		targetParam1 = {[12] = {3601}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [23601] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1517]
		-- {[6] = 1, __size = 1}
	},
	[1518] = {
		id = 1518,
		exchangeTimes = 1,
		targetDesc1 = '超梦达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81609,
		targetParam1 = {[12] = {761}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [20761] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1518]
		-- {[6] = 1, __size = 1}
	},
	[1519] = {
		id = 1519,
		exchangeTimes = 1,
		targetDesc1 = '凤王达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83606,
		targetParam1 = {[12] = {1271}, __size = 1},
		costItems = {['gold'] = 6000000, [21271] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1519]
		-- {[6] = 1, __size = 1}
	},
	[1520] = {
		id = 1520,
		exchangeTimes = 1,
		targetDesc1 = '洛奇亚达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83607,
		targetParam1 = {[12] = {1261}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [21261] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1520]
		-- {[6] = 1, __size = 1}
	},
	[1521] = {
		id = 1521,
		exchangeTimes = 1,
		targetDesc1 = '比克提尼达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81610,
		targetParam1 = {[12] = {2461}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [22461] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1521]
		-- {[6] = 1, __size = 1}
	},
	[1522] = {
		id = 1522,
		exchangeTimes = 1,
		targetDesc1 = '时拉比达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83608,
		targetParam1 = {[12] = {1281}, __size = 1},
		costItems = {['gold'] = 6000000, [21281] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1522]
		-- {[6] = 1, __size = 1}
	},
	[1523] = {
		id = 1523,
		exchangeTimes = 1,
		targetDesc1 = '基拉祈达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83609,
		targetParam1 = {[12] = {1991}, __size = 1},
		costItems = {['gold'] = 6000000, [21991] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1523]
		-- {[6] = 1, __size = 1}
	},
	[1524] = {
		id = 1524,
		exchangeTimes = 1,
		targetDesc1 = '伊裴尔塔尔达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81611,
		targetParam1 = {[12] = {3611}, __size = 1},
		costItems = {['gold'] = 6000000, [23611] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1524]
		-- {[6] = 1, __size = 1}
	},
	[1525] = {
		id = 1525,
		exchangeTimes = 1,
		targetDesc1 = '基格尔德达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82606,
		targetParam1 = {[12] = {3621}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [23621] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1525]
		-- {[6] = 1, __size = 1}
	},
	[1526] = {
		id = 1526,
		exchangeTimes = 1,
		targetDesc1 = '蒂安希达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83610,
		targetParam1 = {[12] = {3631}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [23631] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1526]
		-- {[6] = 1, __size = 1}
	},
	[1527] = {
		id = 1527,
		exchangeTimes = 1,
		targetDesc1 = '惩戒胡帕达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81612,
		targetParam1 = {[12] = {3641}, __size = 1},
		costItems = {[23641] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1527]
		-- {[6] = 1, __size = 1}
	},
	[1528] = {
		id = 1528,
		exchangeTimes = 1,
		targetDesc1 = '捷拉奥拉达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81613,
		targetParam1 = {[12] = {4161}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [24161] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1528]
		-- {[6] = 1, __size = 1}
	},
	[1529] = {
		id = 1529,
		exchangeTimes = 1,
		targetDesc1 = '小智版甲贺忍蛙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81614,
		targetParam1 = {[12] = {7011}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [27011] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1529]
		-- {[6] = 1, __size = 1}
	},
	[1530] = {
		id = 1530,
		exchangeTimes = 1,
		targetDesc1 = '波尔凯尼恩达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81615,
		targetParam1 = {[12] = {3651}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [23651] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1530]
		-- {[6] = 1, __size = 1}
	},
	[1531] = {
		id = 1531,
		exchangeTimes = 1,
		targetDesc1 = '玛机雅娜达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83611,
		targetParam1 = {[12] = {4111}, __size = 1},
		costItems = {[24111] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1531]
		-- {[6] = 1, __size = 1}
	},
	[1532] = {
		id = 1532,
		exchangeTimes = 1,
		targetDesc1 = '艾岚超级喷火龙x达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81616,
		targetParam1 = {[12] = {7121}, __size = 1},
		costItems = {[27121] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1532]
		-- {[6] = 1, __size = 1}
	},
	[1533] = {
		id = 1533,
		exchangeTimes = 1,
		targetDesc1 = '奈克洛兹玛达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81617,
		targetParam1 = {[12] = {4101}, __size = 1},
		costItems = {['gold'] = 6000000, [24101] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1533],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1533]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1534] = {
		id = 1534,
		exchangeTimes = 1,
		targetDesc1 = '索尔迦雷欧达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82607,
		targetParam1 = {[12] = {4023}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [24023] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1534],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1534]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1535] = {
		id = 1535,
		exchangeTimes = 1,
		targetDesc1 = '露奈雅拉达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83612,
		targetParam1 = {[12] = {4024}, __size = 1},
		costItems = {[24024] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1535],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1535]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1536] = {
		id = 1536,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '苍响达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81618,
		targetParam1 = {[12] = {4591}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [24591] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1536],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1536]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1537] = {
		id = 1537,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '藏玛然特达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82608,
		targetParam1 = {[12] = {4601}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [24601] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1537],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1537]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1538] = {
		id = 1538,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '萨戮德达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83613,
		targetParam1 = {[12] = {4631}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [24631] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1538],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1538]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1539] = {
		id = 1539,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级耿鬼达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81619,
		targetParam1 = {[12] = {7021}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [27021] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1539],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1539]
		-- {'cn', 'tw', 'en_us'}
	},
	[1540] = {
		id = 1540,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级班基拉斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81620,
		targetParam1 = {[12] = {7031}, __size = 1},
		costItems = {['gold'] = 6000000, [27031] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1540],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1540]
		-- {'cn', 'tw', 'en_us'}
	},
	[1541] = {
		id = 1541,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '起源梦幻达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83614,
		targetParam1 = {[12] = {7041}, __size = 1},
		costItems = {['gold'] = 6000000, [27041] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1541],
		-- {[6] = 1, __size = 1}
		languages = __data_t__languages[1541]
		-- {'cn', 'tw', 'en_us'}
	},
	[1542] = {
		id = 1542,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级艾路雷朵达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81621,
		targetParam1 = {[12] = {7061}, __size = 1},
		costItems = {[27061] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1542]
		-- {[6] = 1, __size = 1}
	},
	[1543] = {
		id = 1543,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '凯路迪欧·觉悟达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81622,
		targetParam1 = {[12] = {7071}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [27071] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1543]
		-- {[6] = 1, __size = 1}
	},
	[1544] = {
		id = 1544,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级沙奈朵达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83615,
		targetParam1 = {[12] = {7051}, __size = 1},
		costItems = {[27051] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1544]
		-- {[6] = 1, __size = 1}
	},
	[1545] = {
		id = 1545,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '大吾超级巨金怪达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82609,
		targetParam1 = {[12] = {7081}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [27081] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1545]
		-- {[6] = 1, __size = 1}
	},
	[1546] = {
		id = 1546,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '竹兰超级烈咬陆鲨达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81623,
		targetParam1 = {[12] = {7091}, __size = 1},
		costItems = {['rmb'] = 1500, ['gold'] = 6000000, [27091] = 30, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1546]
		-- {[6] = 1, __size = 1}
	},
	[1547] = {
		id = 1547,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级路卡利欧达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81624,
		targetParam1 = {[12] = {7111}, __size = 1},
		costItems = {[27111] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1547]
		-- {[6] = 1, __size = 1}
	},
	[1548] = {
		id = 1548,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '蕾冠王·黑马达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81625,
		targetParam1 = {[12] = {4683}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [24683] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1548]
		-- {[6] = 1, __size = 1}
	},
	[1549] = {
		id = 1549,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级暴雪王达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81626,
		targetParam1 = {[12] = {7131}, __size = 1},
		costItems = {['gold'] = 6000000, [27131] = 30, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1549]
		-- {[6] = 1, __size = 1}
	},
	[1550] = {
		id = 1550,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '蕾冠王·白马达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83616,
		targetParam1 = {[12] = {4682}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [24682] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1550]
		-- {[6] = 1, __size = 1}
	},
	[1551] = {
		id = 1551,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '密勒顿达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81627,
		targetParam1 = {[12] = {5391}, __size = 1},
		costItems = {[25391] = 30, ['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, __size = 4},
		costContractMap = __data_t__costContractMap[1551]
		-- {[6] = 1, __size = 1}
	},
	[1552] = {
		id = 1552,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '闪光超级妙蛙花达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83617,
		targetParam1 = {[12] = {7151}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [27151] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1552]
		-- {[6] = 1, __size = 1}
	},
	[1554] = {
		id = 1554,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '无极汰那达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81629,
		targetParam1 = {[12] = {4611}, __size = 1},
		costItems = {['gold'] = 6000000, ['rmb'] = 1500, [521] = 10, [24611] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1554]
		-- {[6] = 1, __size = 1}
	},
	[1601] = {
		id = 1601,
		exchangeTimes = 1,
		targetDesc1 = '呱呱泡蛙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81501,
		targetParam1 = {[12] = {3301}, __size = 1},
		costItems = {[23301] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1601]
		-- {[5] = 1, __size = 1}
	},
	[1602] = {
		id = 1602,
		exchangeTimes = 1,
		targetDesc1 = '飞天螳螂达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81504,
		targetParam1 = {[12] = {571}, __size = 1},
		costItems = {['rmb'] = 1000, [20571] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1602]
		-- {[5] = 1, __size = 1}
	},
	[1603] = {
		id = 1603,
		exchangeTimes = 1,
		targetDesc1 = '懒人獭达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81502,
		targetParam1 = {[12] = {1421}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21421] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1603]
		-- {[5] = 1, __size = 1}
	},
	[1604] = {
		id = 1604,
		exchangeTimes = 1,
		targetDesc1 = '火焰鸟达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81507,
		targetParam1 = {[12] = {741}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20741] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1604]
		-- {[5] = 1, __size = 1}
	},
	[1605] = {
		id = 1605,
		exchangeTimes = 1,
		targetDesc1 = '宝贝龙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81508,
		targetParam1 = {[12] = {1891}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21891] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1605]
		-- {[5] = 1, __size = 1}
	},
	[1606] = {
		id = 1606,
		exchangeTimes = 1,
		targetDesc1 = '利欧路达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81509,
		targetParam1 = {[12] = {2241}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22241] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1606]
		-- {[5] = 1, __size = 1}
	},
	[1607] = {
		id = 1607,
		exchangeTimes = 1,
		targetDesc1 = '可可多拉达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82501,
		targetParam1 = {[12] = {1501}, __size = 1},
		costItems = {[21501] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1607]
		-- {[5] = 1, __size = 1}
	},
	[1608] = {
		id = 1608,
		exchangeTimes = 1,
		targetDesc1 = '小卡比兽达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82502,
		targetParam1 = {[12] = {711}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20711] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1608]
		-- {[5] = 1, __size = 1}
	},
	[1609] = {
		id = 1609,
		exchangeTimes = 1,
		targetDesc1 = '大舌贝达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82506,
		targetParam1 = {[12] = {381}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20381] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1609]
		-- {[5] = 1, __size = 1}
	},
	[1610] = {
		id = 1610,
		exchangeTimes = 1,
		targetDesc1 = '独剑鞘达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82507,
		targetParam1 = {[12] = {3411}, __size = 1},
		costItems = {[23411] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1610]
		-- {[5] = 1, __size = 1}
	},
	[1611] = {
		id = 1611,
		exchangeTimes = 1,
		targetDesc1 = '土地云达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82508,
		targetParam1 = {[12] = {3231}, __size = 1},
		costItems = {[23231] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1611]
		-- {[5] = 1, __size = 1}
	},
	[1612] = {
		id = 1612,
		exchangeTimes = 1,
		targetDesc1 = '急冻鸟达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82509,
		targetParam1 = {[12] = {721}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [20721] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1612]
		-- {[5] = 1, __size = 1}
	},
	[1613] = {
		id = 1613,
		exchangeTimes = 1,
		targetDesc1 = '花蓓蓓达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83504,
		targetParam1 = {[12] = {3351}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23351] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1613]
		-- {[5] = 1, __size = 1}
	},
	[1614] = {
		id = 1614,
		exchangeTimes = 1,
		targetDesc1 = '克雷色利亚达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83503,
		targetParam1 = {[12] = {2401}, __size = 1},
		costItems = {[22401] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1614]
		-- {[5] = 1, __size = 1}
	},
	[1615] = {
		id = 1615,
		exchangeTimes = 1,
		targetDesc1 = '闪电鸟达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83502,
		targetParam1 = {[12] = {731}, __size = 1},
		costItems = {[20731] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1615]
		-- {[5] = 1, __size = 1}
	},
	[1616] = {
		id = 1616,
		exchangeTimes = 1,
		targetDesc1 = '龙卷云达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83506,
		targetParam1 = {[12] = {3191}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23191] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1616]
		-- {[5] = 1, __size = 1}
	},
	[1617] = {
		id = 1617,
		exchangeTimes = 1,
		targetDesc1 = '水君达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83507,
		targetParam1 = {[12] = {1241}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21241] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1617]
		-- {[5] = 1, __size = 1}
	},
	[1618] = {
		id = 1618,
		exchangeTimes = 1,
		targetDesc1 = '藤藤蛇达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83509,
		targetParam1 = {[12] = {2471}, __size = 1},
		costItems = {[22471] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1618]
		-- {[5] = 1, __size = 1}
	},
	[1619] = {
		id = 1619,
		exchangeTimes = 1,
		targetDesc1 = '雷吉斯奇鲁达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81510,
		targetParam1 = {[12] = {1931}, __size = 1},
		costItems = {[21931] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1619]
		-- {[5] = 1, __size = 1}
	},
	[1620] = {
		id = 1620,
		exchangeTimes = 1,
		targetDesc1 = '雷吉洛克达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82510,
		targetParam1 = {[12] = {1911}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [21911] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1620]
		-- {[5] = 1, __size = 1}
	},
	[1621] = {
		id = 1621,
		exchangeTimes = 1,
		targetDesc1 = '雷吉艾斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83510,
		targetParam1 = {[12] = {1921}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21921] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1621]
		-- {[5] = 1, __size = 1}
	},
	[1622] = {
		id = 1622,
		exchangeTimes = 1,
		targetDesc1 = '代拉基翁达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81511,
		targetParam1 = {[12] = {3171}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [23171] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1622]
		-- {[5] = 1, __size = 1}
	},
	[1623] = {
		id = 1623,
		exchangeTimes = 1,
		targetDesc1 = '毕力吉翁达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81512,
		targetParam1 = {[12] = {3181}, __size = 1},
		costItems = {['rmb'] = 1000, [23181] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1623]
		-- {[5] = 1, __size = 1}
	},
	[1624] = {
		id = 1624,
		exchangeTimes = 1,
		targetDesc1 = '勾帕路翁达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82511,
		targetParam1 = {[12] = {3161}, __size = 1},
		costItems = {[23161] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1624]
		-- {[5] = 1, __size = 1}
	},
	[1625] = {
		id = 1625,
		exchangeTimes = 1,
		targetDesc1 = '拉帝欧斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81513,
		targetParam1 = {[12] = {1951}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21951] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1625]
		-- {[5] = 1, __size = 1}
	},
	[1626] = {
		id = 1626,
		exchangeTimes = 1,
		targetDesc1 = '拉帝亚斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83511,
		targetParam1 = {[12] = {1941}, __size = 1},
		costItems = {[21941] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1626]
		-- {[5] = 1, __size = 1}
	},
	[1627] = {
		id = 1627,
		exchangeTimes = 1,
		targetDesc1 = '甜竹竹达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81514,
		targetParam1 = {[12] = {3841}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23841] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1627]
		-- {[5] = 1, __size = 1}
	},
	[1628] = {
		id = 1628,
		exchangeTimes = 1,
		targetDesc1 = '木木枭达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81515,
		targetParam1 = {[12] = {3661}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [23661] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1628]
		-- {[5] = 1, __size = 1}
	},
	[1629] = {
		id = 1629,
		exchangeTimes = 1,
		targetDesc1 = '纸御剑达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81516,
		targetParam1 = {[12] = {4081}, __size = 1},
		costItems = {['rmb'] = 1000, [24081] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1629]
		-- {[5] = 1, __size = 1}
	},
	[1630] = {
		id = 1630,
		exchangeTimes = 1,
		targetDesc1 = '黏黏宝达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82512,
		targetParam1 = {[12] = {3541}, __size = 1},
		costItems = {['rmb'] = 1000, [23541] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1630]
		-- {[5] = 1, __size = 1}
	},
	[1631] = {
		id = 1631,
		exchangeTimes = 1,
		targetDesc1 = '球球海狮达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83512,
		targetParam1 = {[12] = {3681}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23681] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1631]
		-- {[5] = 1, __size = 1}
	},
	[1632] = {
		id = 1632,
		exchangeTimes = 1,
		targetDesc1 = '雷电云达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83513,
		targetParam1 = {[12] = {3201}, __size = 1},
		costItems = {[23201] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1632]
		-- {[5] = 1, __size = 1}
	},
	[1633] = {
		id = 1633,
		exchangeTimes = 1,
		targetDesc1 = '凯西达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83514,
		targetParam1 = {[12] = {261}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20261] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1633]
		-- {[5] = 1, __size = 1}
	},
	[1634] = {
		id = 1634,
		exchangeTimes = 1,
		targetDesc1 = '鬼斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83515,
		targetParam1 = {[12] = {391}, __size = 1},
		costItems = {['rmb'] = 1000, [20391] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1634]
		-- {[5] = 1, __size = 1}
	},
	[1635] = {
		id = 1635,
		exchangeTimes = 1,
		targetDesc1 = '梦妖达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83516,
		targetParam1 = {[12] = {971}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20971] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1635]
		-- {[5] = 1, __size = 1}
	},
	[1636] = {
		id = 1636,
		exchangeTimes = 1,
		targetDesc1 = '拉鲁拉丝达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83517,
		targetParam1 = {[12] = {1391}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21391] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1636]
		-- {[5] = 1, __size = 1}
	},
	[1637] = {
		id = 1637,
		exchangeTimes = 1,
		targetDesc1 = '小磁怪达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81517,
		targetParam1 = {[12] = {331}, __size = 1},
		costItems = {[20331] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1637]
		-- {[5] = 1, __size = 1}
	},
	[1638] = {
		id = 1638,
		exchangeTimes = 1,
		targetDesc1 = '电击怪达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81518,
		targetParam1 = {[12] = {591}, __size = 1},
		costItems = {[20591] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1638]
		-- {[5] = 1, __size = 1}
	},
	[1639] = {
		id = 1639,
		exchangeTimes = 1,
		targetDesc1 = '卡蒂狗达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81519,
		targetParam1 = {[12] = {241}, __size = 1},
		costItems = {[20241] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1639]
		-- {[5] = 1, __size = 1}
	},
	[1640] = {
		id = 1640,
		exchangeTimes = 1,
		targetDesc1 = '鸭嘴宝宝达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81520,
		targetParam1 = {[12] = {601}, __size = 1},
		costItems = {[20601] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1640]
		-- {[5] = 1, __size = 1}
	},
	[1641] = {
		id = 1641,
		exchangeTimes = 1,
		targetDesc1 = '戴鲁比达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81521,
		targetParam1 = {[12] = {1171}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21171] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1641]
		-- {[5] = 1, __size = 1}
	},
	[1642] = {
		id = 1642,
		exchangeTimes = 1,
		targetDesc1 = '炎帝达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82513,
		targetParam1 = {[12] = {1231}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21231] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1642]
		-- {[5] = 1, __size = 1}
	},
	[1643] = {
		id = 1643,
		exchangeTimes = 1,
		targetDesc1 = '烛光灵达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83518,
		targetParam1 = {[12] = {2991}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22991] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1643]
		-- {[5] = 1, __size = 1}
	},
	[1644] = {
		id = 1644,
		exchangeTimes = 1,
		targetDesc1 = '燃烧虫达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83519,
		targetParam1 = {[12] = {3151}, __size = 1},
		costItems = {[23151] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1644]
		-- {[5] = 1, __size = 1}
	},
	[1645] = {
		id = 1645,
		exchangeTimes = 1,
		targetDesc1 = '蚊香蝌蚪达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83520,
		targetParam1 = {[12] = {251}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [20251] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1645]
		-- {[5] = 1, __size = 1}
	},
	[1646] = {
		id = 1646,
		exchangeTimes = 1,
		targetDesc1 = '呆呆兽达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83521,
		targetParam1 = {[12] = {321}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20321] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1646]
		-- {[5] = 1, __size = 1}
	},
	[1647] = {
		id = 1647,
		exchangeTimes = 1,
		targetDesc1 = '暴鲤龙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81522,
		targetParam1 = {[12] = {631}, __size = 1},
		costItems = {[20631] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1647]
		-- {[5] = 1, __size = 1}
	},
	[1648] = {
		id = 1648,
		exchangeTimes = 1,
		targetDesc1 = '拉普拉斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83522,
		targetParam1 = {[12] = {641}, __size = 1},
		costItems = {[20641] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1648]
		-- {[5] = 1, __size = 1}
	},
	[1649] = {
		id = 1649,
		exchangeTimes = 1,
		targetDesc1 = '水跃鱼达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82514,
		targetParam1 = {[12] = {1311}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21311] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1649]
		-- {[5] = 1, __size = 1}
	},
	[1650] = {
		id = 1650,
		exchangeTimes = 1,
		targetDesc1 = '丑丑鱼达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83523,
		targetParam1 = {[12] = {1771}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21771] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1650]
		-- {[5] = 1, __size = 1}
	},
	[1651] = {
		id = 1651,
		exchangeTimes = 1,
		targetDesc1 = '凯罗斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81523,
		targetParam1 = {[12] = {611}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [20611] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1651]
		-- {[5] = 1, __size = 1}
	},
	[1652] = {
		id = 1652,
		exchangeTimes = 1,
		targetDesc1 = '化石翼龙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81524,
		targetParam1 = {[12] = {701}, __size = 1},
		costItems = {[20701] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1652]
		-- {[5] = 1, __size = 1}
	},
	[1653] = {
		id = 1653,
		exchangeTimes = 1,
		targetDesc1 = '大岩蛇达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82515,
		targetParam1 = {[12] = {401}, __size = 1},
		costItems = {['rmb'] = 1000, [20401] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1653]
		-- {[5] = 1, __size = 1}
	},
	[1654] = {
		id = 1654,
		exchangeTimes = 1,
		targetDesc1 = '独角犀牛达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82516,
		targetParam1 = {[12] = {491}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20491] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1654]
		-- {[5] = 1, __size = 1}
	},
	[1655] = {
		id = 1655,
		exchangeTimes = 1,
		targetDesc1 = '铁哑铃达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82517,
		targetParam1 = {[12] = {1901}, __size = 1},
		costItems = {[21901] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1655]
		-- {[5] = 1, __size = 1}
	},
	[1656] = {
		id = 1656,
		exchangeTimes = 1,
		targetDesc1 = '垒磊石达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82518,
		targetParam1 = {[12] = {4141}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [24141] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1656]
		-- {[5] = 1, __size = 1}
	},
	[1657] = {
		id = 1657,
		exchangeTimes = 1,
		targetDesc1 = '炎兔儿达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81525,
		targetParam1 = {[12] = {4191}, __size = 1},
		costItems = {[24191] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1657],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1657]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1658] = {
		id = 1658,
		exchangeTimes = 1,
		targetDesc1 = '雷公达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82519,
		targetParam1 = {[12] = {1221}, __size = 1},
		costItems = {[21221] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1658],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1658]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1659] = {
		id = 1659,
		exchangeTimes = 1,
		targetDesc1 = '蛋蛋达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83524,
		targetParam1 = {[12] = {441}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20441] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1659],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1659]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1660] = {
		id = 1660,
		exchangeTimes = 1,
		targetDesc1 = '小福蛋达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83525,
		targetParam1 = {[12] = {501}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [20501] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1660],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1660]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1661] = {
		id = 1661,
		exchangeTimes = 1,
		targetDesc1 = '波克比达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83526,
		targetParam1 = {[12] = {861}, __size = 1},
		costItems = {[20861] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1661],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1661]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1662] = {
		id = 1662,
		exchangeTimes = 1,
		targetDesc1 = '咩利羊达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83527,
		targetParam1 = {[12] = {881}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20881] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1662],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1662]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1663] = {
		id = 1663,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '快龙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81526,
		targetParam1 = {[12] = {751}, __size = 1},
		costItems = {['rmb'] = 1000, [20751] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1663],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1663]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1664] = {
		id = 1664,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '梦幻达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82520,
		targetParam1 = {[12] = {771}, __size = 1},
		costItems = {[20771] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1664],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1664]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1665] = {
		id = 1665,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '幼基拉斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82521,
		targetParam1 = {[12] = {1251}, __size = 1},
		costItems = {[21251] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1665],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1665]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1666] = {
		id = 1666,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '木守宫达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81527,
		targetParam1 = {[12] = {1291}, __size = 1},
		costItems = {[21291] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1666],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1666]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1667] = {
		id = 1667,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '火雉鸡达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81528,
		targetParam1 = {[12] = {1301}, __size = 1},
		costItems = {['rmb'] = 1000, [21301] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1667],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1667]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1668] = {
		id = 1668,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '小火焰猴达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81529,
		targetParam1 = {[12] = {2021}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22021] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1668],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1668]
		-- {'cn', 'kr', 'tw', 'en_us'}
	},
	[1669] = {
		id = 1669,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '天蝎达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81530,
		targetParam1 = {[12] = {1031}, __size = 1},
		costItems = {[21031] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1669],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1669]
		-- {'cn', 'tw', 'en_us'}
	},
	[1670] = {
		id = 1670,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '赫拉克罗斯达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81531,
		targetParam1 = {[12] = {1071}, __size = 1},
		costItems = {[21071] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1670],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1670]
		-- {'cn', 'tw', 'en_us'}
	},
	[1671] = {
		id = 1671,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '狃拉达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81532,
		targetParam1 = {[12] = {1081}, __size = 1},
		costItems = {[21081] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1671],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1671]
		-- {'cn', 'tw', 'en_us'}
	},
	[1672] = {
		id = 1672,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '牙牙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81533,
		targetParam1 = {[12] = {3001}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [23001] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1672],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1672]
		-- {'cn', 'tw', 'en_us'}
	},
	[1673] = {
		id = 1673,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '圆陆鲨达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81534,
		targetParam1 = {[12] = {2231}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22231] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1673],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1673]
		-- {'cn', 'tw', 'en_us'}
	},
	[1674] = {
		id = 1674,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '单首龙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81535,
		targetParam1 = {[12] = {3141}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23141] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1674],
		-- {[5] = 1, __size = 1}
		languages = __data_t__languages[1674]
		-- {'cn', 'tw', 'en_us'}
	},
	[1675] = {
		id = 1675,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '谜拟Ｑ达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83528,
		targetParam1 = {[12] = {3961}, __size = 1},
		costItems = {[23961] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1675]
		-- {[5] = 1, __size = 1}
	},
	[1676] = {
		id = 1676,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '阿勃梭鲁达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83529,
		targetParam1 = {[12] = {1841}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21841] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1676]
		-- {[5] = 1, __size = 1}
	},
	[1677] = {
		id = 1677,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '夜巡灵达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83530,
		targetParam1 = {[12] = {1811}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21811] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1677]
		-- {[5] = 1, __size = 1}
	},
	[1678] = {
		id = 1678,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '黑眼鳄达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81536,
		targetParam1 = {[12] = {2721}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22721] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1678]
		-- {[5] = 1, __size = 1}
	},
	[1679] = {
		id = 1679,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '索罗亚达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81537,
		targetParam1 = {[12] = {2821}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22821] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1679]
		-- {[5] = 1, __size = 1}
	},
	[1680] = {
		id = 1680,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '好坏星达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82522,
		targetParam1 = {[12] = {3771}, __size = 1},
		costItems = {[23771] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1680]
		-- {[5] = 1, __size = 1}
	},
	[1681] = {
		id = 1681,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '毒贝比达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81538,
		targetParam1 = {[12] = {4131}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [24131] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1681]
		-- {[5] = 1, __size = 1}
	},
	[1682] = {
		id = 1682,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '嗡蝠达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83533,
		targetParam1 = {[12] = {3591}, __size = 1},
		costItems = {[23591] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1682]
		-- {[5] = 1, __size = 1}
	},
	[1683] = {
		id = 1683,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '几何雪花达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82523,
		targetParam1 = {[12] = {3021}, __size = 1},
		costItems = {[23021] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1683]
		-- {[5] = 1, __size = 1}
	},
	[1684] = {
		id = 1684,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '小果然达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82524,
		targetParam1 = {[12] = {991}, __size = 1},
		costItems = {[20991] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1684]
		-- {[5] = 1, __size = 1}
	},
	[1685] = {
		id = 1685,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '超音蝠达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83531,
		targetParam1 = {[12] = {161}, __size = 1},
		costItems = {[20161] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1685]
		-- {[5] = 1, __size = 1}
	},
	[1686] = {
		id = 1686,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '魔尼尼达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83532,
		targetParam1 = {[12] = {561}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20561] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1686]
		-- {[5] = 1, __size = 1}
	},
	[1687] = {
		id = 1687,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '席多蓝恩达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82525,
		targetParam1 = {[12] = {2371}, __size = 1},
		costItems = {['rmb'] = 1000, [22371] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1687]
		-- {[5] = 1, __size = 1}
	},
	[1688] = {
		id = 1688,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '青绵鸟达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83534,
		targetParam1 = {[12] = {1671}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [21671] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1688]
		-- {[5] = 1, __size = 1}
	},
	[1689] = {
		id = 1689,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '火斑喵达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81539,
		targetParam1 = {[12] = {3671}, __size = 1},
		costItems = {[23671] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1689]
		-- {[5] = 1, __size = 1}
	},
	[1690] = {
		id = 1690,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '霏欧纳达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83535,
		targetParam1 = {[12] = {2411}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22411] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1690]
		-- {[5] = 1, __size = 1}
	},
	[1691] = {
		id = 1691,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '敲音猴达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83536,
		targetParam1 = {[12] = {4181}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [24181] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1691]
		-- {[5] = 1, __size = 1}
	},
	[1692] = {
		id = 1692,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '盆才怪达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83537,
		targetParam1 = {[12] = {901}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [20901] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1692]
		-- {[5] = 1, __size = 1}
	},
	[1693] = {
		id = 1693,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '凯路迪欧达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81540,
		targetParam1 = {[12] = {3251}, __size = 1},
		costItems = {['rmb'] = 1000, [23251] = 150, [502] = 30, ['gold'] = 3000000, __size = 4},
		costContractMap = __data_t__costContractMap[1693]
		-- {[5] = 1, __size = 1}
	},
	[1694] = {
		id = 1694,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '功夫鼬达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81541,
		targetParam1 = {[12] = {3051}, __size = 1},
		costItems = {[23051] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1694]
		-- {[5] = 1, __size = 1}
	},
	[1695] = {
		id = 1695,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '童偶熊达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81542,
		targetParam1 = {[12] = {3831}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23831] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1695]
		-- {[5] = 1, __size = 1}
	},
	[1696] = {
		id = 1696,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '虚吾伊德达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82526,
		targetParam1 = {[12] = {4031}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [24031] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1696]
		-- {[5] = 1, __size = 1}
	},
	[1697] = {
		id = 1697,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '鳃鱼龙达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82527,
		targetParam1 = {[12] = {4561}, __size = 1},
		costItems = {[24561] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1697]
		-- {[5] = 1, __size = 1}
	},
	[1698] = {
		id = 1698,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '费洛美螂达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83538,
		targetParam1 = {[12] = {4051}, __size = 1},
		costItems = {[24051] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1698]
		-- {[5] = 1, __size = 1}
	},
	[1699] = {
		id = 1699,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '泳圈鼬达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81543,
		targetParam1 = {[12] = {2131}, __size = 1},
		costItems = {[22131] = 150, ['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1699]
		-- {[5] = 1, __size = 1}
	},
	[1700] = {
		id = 1700,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '小智版皮卡丘达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81544,
		targetParam1 = {[12] = {7001}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [27001] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1700]
		-- {[5] = 1, __size = 1}
	},
	[1701] = {
		id = 1701,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '姆克儿达到12星解锁',
		targetType1 = 128,
		contractCsvID = 81545,
		targetParam1 = {[12] = {2041}, __size = 1},
		costItems = {[22041] = 150, ['gold'] = 3000000, ['rmb'] = 1000, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1701]
		-- {[5] = 1, __size = 1}
	},
	[1702] = {
		id = 1702,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '爆焰龟兽达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82528,
		targetParam1 = {[12] = {3941}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [23941] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1702]
		-- {[5] = 1, __size = 1}
	},
	[1703] = {
		id = 1703,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '铁火辉夜达到12星解锁',
		targetType1 = 128,
		contractCsvID = 82529,
		targetParam1 = {[12] = {4071}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [24071] = 150, [502] = 30, __size = 4},
		costContractMap = __data_t__costContractMap[1703]
		-- {[5] = 1, __size = 1}
	},
	[1704] = {
		id = 1704,
		redPoint = 1,
		exchangeTimes = 1,
		targetDesc1 = '艾姆利多达到12星解锁',
		targetType1 = 128,
		contractCsvID = 83539,
		targetParam1 = {[12] = {2331}, __size = 1},
		costItems = {['rmb'] = 1000, ['gold'] = 3000000, [502] = 30, [22331] = 150, __size = 4},
		costContractMap = __data_t__costContractMap[1704]
		-- {[5] = 1, __size = 1}
	},
	__size = 164,
	__default = {
		__index = {
			targetArg2 = 1,
			targetType2 = 0,
			redPoint = 0,
			exchangeTimes = 2,
			targetDesc1 = '',
			targetArg1 = 1,
			targetType1 = 0,
			contractCsvID = 0,
			onlyShow = 0,
			targetDesc3 = '',
			targetArg3 = 1,
			targetType3 = 0,
			targetDesc2 = '',
			pos = {['y'] = 0, ['x'] = 0, __size = 2},
			targetParam1 = __data_t__targetParam1["default"]	--[[ {__size = 0}]],
			targetParam2 = __data_t__targetParam2["default"]	--[[ {__size = 0}]],
			targetParam3 = __data_t__targetParam3["default"]	--[[ {__size = 0}]],
			costItems = __data_t__costItems["default"]	--[[ {__size = 0}]],
			costContractMap = __data_t__costContractMap["default"]	--[[ {__size = 0}]],
			languages = {'cn'}
		}
	}
}
return csv.contract.activate_book