--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[3] = {['gold'] = 22500, [135] = 45, __size = 2}, 
	[4] = {['gold'] = 52500, [135] = 105, __size = 2}, 
	[5] = {['gold'] = 75000, [135] = 150, __size = 2}, 
	[6] = {['gold'] = 150000, [135] = 300, __size = 2}, 
	[8] = {['gold'] = 25000, [135] = 50, __size = 2}, 
	[10] = {['gold'] = 82500, [135] = 165, __size = 2}, 
	[11] = {['gold'] = 165000, [135] = 330, __size = 2}, 
	[14] = {['gold'] = 27000, [135] = 54, __size = 2}, 
	[15] = {['gold'] = 63000, [135] = 126, __size = 2}, 
	[16] = {['gold'] = 90000, [135] = 180, __size = 2}, 
	[17] = {['gold'] = 180000, [135] = 360, __size = 2}, 
	[19] = {['gold'] = 30000, [135] = 60, __size = 2}, 
	[22] = {['gold'] = 97500, [135] = 195, __size = 2}, 
	[23] = {['gold'] = 195000, [135] = 390, __size = 2}, 
	[26] = {['gold'] = 31500, [135] = 63, __size = 2}, 
	[27] = {['gold'] = 73500, [135] = 147, __size = 2}, 
	[28] = {['gold'] = 105000, [135] = 210, __size = 2}, 
	[29] = {['gold'] = 210000, [135] = 420, __size = 2}, 
	[30] = {['gold'] = 35000, [135] = 70, __size = 2}, 
	[32] = {['gold'] = 79000, [135] = 158, __size = 2}, 
	[33] = {['gold'] = 112500, [135] = 225, __size = 2}, 
	[34] = {['gold'] = 225000, [135] = 450, __size = 2}, 
	[36] = {['gold'] = 36000, [135] = 72, __size = 2}, 
	[37] = {['gold'] = 84000, [135] = 168, __size = 2}, 
	[38] = {['gold'] = 120000, [135] = 240, __size = 2}, 
	[39] = {['gold'] = 240000, [135] = 480, __size = 2}, 
	[41] = {['gold'] = 37500, [135] = 75, __size = 2}, 
	[44] = {['gold'] = 127500, [135] = 255, __size = 2}, 
	[45] = {['gold'] = 255000, [135] = 510, __size = 2}, 
	[47] = {['gold'] = 40500, [135] = 81, __size = 2}, 
	[48] = {['gold'] = 94500, [135] = 189, __size = 2}, 
	[50] = {['gold'] = 270000, [135] = 540, __size = 2}, 
	[54] = {['gold'] = 100000, [135] = 200, __size = 2}, 
	[56] = {['gold'] = 285000, [135] = 570, __size = 2}, 
	[57] = {['gold'] = 45000, [135] = 90, __size = 2}, 
	[58] = {['gold'] = 300000, [135] = 600, __size = 2}, 
	[59] = {['gold'] = 47500, [135] = 95, __size = 2}, 
	[60] = {['gold'] = 110500, [135] = 221, __size = 2}, 
	[61] = {['gold'] = 157500, [135] = 315, __size = 2}, 
	[62] = {['gold'] = 315000, [135] = 630, __size = 2}, 
	[65] = {['gold'] = 49500, [135] = 99, __size = 2}, 
	[67] = {['gold'] = 330000, [135] = 660, __size = 2}, 
	[72] = {['gold'] = 345000, [135] = 690, __size = 2}, 
	[74] = {['gold'] = 54000, [135] = 108, __size = 2}, 
	[75] = {['gold'] = 126000, [135] = 252, __size = 2}, 
	[76] = {['gold'] = 360000, [135] = 720, __size = 2}, 
	[77] = {['gold'] = 57500, [135] = 115, __size = 2}, 
	[81] = {['gold'] = 375000, [135] = 750, __size = 2}, 
	[83] = {['gold'] = 58500, [135] = 117, __size = 2}, 
	[85] = {['gold'] = 390000, [135] = 780, __size = 2}, 
	[86] = {['gold'] = 60000, [135] = 120, __size = 2}, 
	[90] = {['gold'] = 405000, [135] = 810, __size = 2}, 
	[94] = {['gold'] = 420000, [135] = 840, __size = 2}, 
	[100] = {['gold'] = 435000, [135] = 870, __size = 2}, 
	[101] = {['gold'] = 67500, [135] = 135, __size = 2}, 
	[104] = {['gold'] = 70000, [135] = 140, __size = 2}, 
	[110] = {['gold'] = 72000, [135] = 144, __size = 2}, 
	[119] = {['gold'] = 76500, [135] = 153, __size = 2}, 
	[122] = {['gold'] = 80000, [135] = 160, __size = 2}, 
	[124] = {['gold'] = 262500, [135] = 525, __size = 2}, 
	[126] = {['gold'] = 81000, [135] = 162, __size = 2}, 
	[136] = {['gold'] = 85500, [135] = 171, __size = 2}, 
	[146] = {['gold'] = 92500, [135] = 185, __size = 2}, 
	[162] = {['gold'] = 102500, [135] = 205, __size = 2}, 
	[185] = {['gold'] = 115000, [135] = 230, __size = 2}, 
	[203] = {['gold'] = 125000, [135] = 250, __size = 2}, __size = 67}
local __data_t__costItemMap3 = {
	["default"] = __predefine_t__[1],
	[25] = __predefine_t__[119],
	[26] = __predefine_t__[32],
	[27] = __predefine_t__[126],
	[21] = __predefine_t__[101],
	[22] = __predefine_t__[104],
	[23] = __predefine_t__[110],
	[47] = __predefine_t__[75],
	[42] = __predefine_t__[185],
	[29] = __predefine_t__[136],
	[40] = __predefine_t__[60],
	[41] = __predefine_t__[33],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[14],
	[2] = __predefine_t__[8],
	[5] = __predefine_t__[26],
	[7] = __predefine_t__[36],
	[9] = __predefine_t__[47],
	[11] = __predefine_t__[57],
	[13] = __predefine_t__[65],
	[12] = __predefine_t__[59],
	[15] = __predefine_t__[74],
	[17] = __predefine_t__[83],
	[19] = __predefine_t__[15],
	[32] = __predefine_t__[146],
	[31] = __predefine_t__[16],
	[33] = __predefine_t__[48]
}
local __data_t__costItemMap2 = {
	[42] = __predefine_t__[185],
	["default"] = __predefine_t__[1],
	[24] = __predefine_t__[5],
	[26] = __predefine_t__[122],
	[27] = __predefine_t__[122],
	[21] = __predefine_t__[101],
	[22] = __predefine_t__[104],
	[46] = __predefine_t__[203],
	[47] = __predefine_t__[203],
	[44] = __predefine_t__[38],
	[48] = __predefine_t__[44],
	[28] = __predefine_t__[10],
	[41] = __predefine_t__[33],
	[1] = __predefine_t__[3],
	[2] = __predefine_t__[8],
	[4] = __predefine_t__[19],
	[7] = __predefine_t__[30],
	[6] = __predefine_t__[30],
	[8] = __predefine_t__[41],
	[38] = __predefine_t__[28],
	[11] = __predefine_t__[57],
	[12] = __predefine_t__[59],
	[14] = __predefine_t__[4],
	[17] = __predefine_t__[77],
	[16] = __predefine_t__[77],
	[18] = __predefine_t__[86],
	[31] = __predefine_t__[16],
	[37] = __predefine_t__[162],
	[36] = __predefine_t__[162],
	[35] = __predefine_t__[54],
	[34] = __predefine_t__[22],
	[32] = __predefine_t__[146]
}
local __data_t__costItemMap1 = {
	["default"] = __predefine_t__[1],
	[24] = __predefine_t__[65],
	[26] = __predefine_t__[4],
	[27] = __predefine_t__[74],
	[21] = __predefine_t__[57],
	[48] = __predefine_t__[136],
	[46] = __predefine_t__[10],
	[47] = __predefine_t__[37],
	[45] = __predefine_t__[126],
	[42] = __predefine_t__[119],
	[40] = __predefine_t__[27],
	[41] = __predefine_t__[5],
	[6] = __predefine_t__[3],
	[9] = __predefine_t__[14],
	[11] = __predefine_t__[19],
	[39] = __predefine_t__[110],
	[12] = __predefine_t__[26],
	[15] = __predefine_t__[36],
	[16] = __predefine_t__[41],
	[33] = __predefine_t__[15],
	[18] = __predefine_t__[47],
	[31] = __predefine_t__[86],
	[30] = __predefine_t__[83],
	[36] = __predefine_t__[101]
}
local __data_t__costItemMap6 = {
	[11] = __predefine_t__[58],
	[1] = __predefine_t__[6],
	[13] = __predefine_t__[67],
	[12] = __predefine_t__[62],
	[15] = __predefine_t__[76],
	[14] = __predefine_t__[72],
	[17] = __predefine_t__[85],
	[10] = __predefine_t__[56],
	[19] = __predefine_t__[94],
	[18] = __predefine_t__[90],
	[16] = __predefine_t__[81],
	[20] = __predefine_t__[100],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[17],
	[2] = __predefine_t__[11],
	[5] = __predefine_t__[29],
	[4] = __predefine_t__[23],
	[7] = __predefine_t__[39],
	[6] = __predefine_t__[34],
	[9] = __predefine_t__[50],
	[8] = __predefine_t__[45]
}
local __data_t__costItemMap5 = {
	[43] = __predefine_t__[85],
	["default"] = __predefine_t__[1],
	[25] = __predefine_t__[45],
	[26] = __predefine_t__[124],
	[27] = __predefine_t__[50],
	[21] = __predefine_t__[34],
	[23] = __predefine_t__[39],
	[47] = __predefine_t__[94],
	[45] = __predefine_t__[90],
	[29] = __predefine_t__[56],
	[41] = __predefine_t__[81],
	[1] = __predefine_t__[5],
	[3] = __predefine_t__[16],
	[2] = __predefine_t__[10],
	[5] = __predefine_t__[28],
	[4] = __predefine_t__[22],
	[7] = __predefine_t__[38],
	[6] = __predefine_t__[33],
	[8] = __predefine_t__[44],
	[39] = __predefine_t__[76],
	[11] = __predefine_t__[6],
	[13] = __predefine_t__[11],
	[12] = __predefine_t__[61],
	[15] = __predefine_t__[17],
	[17] = __predefine_t__[23],
	[19] = __predefine_t__[29],
	[31] = __predefine_t__[58],
	[49] = __predefine_t__[100],
	[37] = __predefine_t__[72],
	[35] = __predefine_t__[67],
	[33] = __predefine_t__[62]
}
local __data_t__costItemMap4 = {
	[11] = __predefine_t__[28],
	[1] = __predefine_t__[4],
	[12] = __predefine_t__[60],
	[15] = __predefine_t__[75],
	[21] = __predefine_t__[61],
	[10] = __predefine_t__[54],
	[31] = __predefine_t__[29],
	[41] = __predefine_t__[124],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[15],
	[5] = __predefine_t__[27],
	[7] = __predefine_t__[37],
	[6] = __predefine_t__[32],
	[9] = __predefine_t__[48]
}

csv['emera']['strength_cost'] = {
	[1] = {
		id = 1,
		costItemMap1 = {['gold'] = 15000, [135] = 30, __size = 2},
		costItemMap2 = __data_t__costItemMap2[1],
		-- {['gold'] = 22500, [135] = 45, __size = 2}
		costItemMap3 = __data_t__costItemMap3[1],
		-- {['gold'] = 22500, [135] = 45, __size = 2}
		costItemMap4 = __data_t__costItemMap4[1],
		-- {['gold'] = 52500, [135] = 105, __size = 2}
		costItemMap5 = __data_t__costItemMap5[1],
		-- {['gold'] = 75000, [135] = 150, __size = 2}
		costItemMap6 = __data_t__costItemMap6[1]
		-- {['gold'] = 150000, [135] = 300, __size = 2}
	},
	[2] = {
		id = 2,
		costItemMap1 = {['gold'] = 16500, [135] = 33, __size = 2},
		costItemMap2 = __data_t__costItemMap2[2],
		-- {['gold'] = 25000, [135] = 50, __size = 2}
		costItemMap3 = __data_t__costItemMap3[2],
		-- {['gold'] = 25000, [135] = 50, __size = 2}
		costItemMap4 = {['gold'] = 58000, [135] = 116, __size = 2},
		costItemMap5 = __data_t__costItemMap5[2],
		-- {['gold'] = 82500, [135] = 165, __size = 2}
		costItemMap6 = __data_t__costItemMap6[2]
		-- {['gold'] = 165000, [135] = 330, __size = 2}
	},
	[3] = {
		id = 3,
		costItemMap1 = {['gold'] = 18000, [135] = 36, __size = 2},
		costItemMap2 = {['gold'] = 27500, [135] = 55, __size = 2},
		costItemMap3 = __data_t__costItemMap3[3],
		-- {['gold'] = 27000, [135] = 54, __size = 2}
		costItemMap4 = __data_t__costItemMap4[3],
		-- {['gold'] = 63000, [135] = 126, __size = 2}
		costItemMap5 = __data_t__costItemMap5[3],
		-- {['gold'] = 90000, [135] = 180, __size = 2}
		costItemMap6 = __data_t__costItemMap6[3]
		-- {['gold'] = 180000, [135] = 360, __size = 2}
	},
	[4] = {
		id = 4,
		costItemMap1 = {['gold'] = 19500, [135] = 39, __size = 2},
		costItemMap2 = __data_t__costItemMap2[4],
		-- {['gold'] = 30000, [135] = 60, __size = 2}
		costItemMap3 = {['gold'] = 29500, [135] = 59, __size = 2},
		costItemMap4 = {['gold'] = 68500, [135] = 137, __size = 2},
		costItemMap5 = __data_t__costItemMap5[4],
		-- {['gold'] = 97500, [135] = 195, __size = 2}
		costItemMap6 = __data_t__costItemMap6[4]
		-- {['gold'] = 195000, [135] = 390, __size = 2}
	},
	[5] = {
		id = 5,
		costItemMap1 = {['gold'] = 21000, [135] = 42, __size = 2},
		costItemMap2 = {['gold'] = 32500, [135] = 65, __size = 2},
		costItemMap3 = __data_t__costItemMap3[5],
		-- {['gold'] = 31500, [135] = 63, __size = 2}
		costItemMap4 = __data_t__costItemMap4[5],
		-- {['gold'] = 73500, [135] = 147, __size = 2}
		costItemMap5 = __data_t__costItemMap5[5],
		-- {['gold'] = 105000, [135] = 210, __size = 2}
		costItemMap6 = __data_t__costItemMap6[5]
		-- {['gold'] = 210000, [135] = 420, __size = 2}
	},
	[6] = {
		id = 6,
		costItemMap1 = __data_t__costItemMap1[6],
		-- {['gold'] = 22500, [135] = 45, __size = 2}
		costItemMap2 = __data_t__costItemMap2[6],
		-- {['gold'] = 35000, [135] = 70, __size = 2}
		costItemMap3 = {['gold'] = 34000, [135] = 68, __size = 2},
		costItemMap4 = __data_t__costItemMap4[6],
		-- {['gold'] = 79000, [135] = 158, __size = 2}
		costItemMap5 = __data_t__costItemMap5[6],
		-- {['gold'] = 112500, [135] = 225, __size = 2}
		costItemMap6 = __data_t__costItemMap6[6]
		-- {['gold'] = 225000, [135] = 450, __size = 2}
	},
	[7] = {
		id = 7,
		costItemMap1 = {['gold'] = 24000, [135] = 48, __size = 2},
		costItemMap2 = __data_t__costItemMap2[7],
		-- {['gold'] = 35000, [135] = 70, __size = 2}
		costItemMap3 = __data_t__costItemMap3[7],
		-- {['gold'] = 36000, [135] = 72, __size = 2}
		costItemMap4 = __data_t__costItemMap4[7],
		-- {['gold'] = 84000, [135] = 168, __size = 2}
		costItemMap5 = __data_t__costItemMap5[7],
		-- {['gold'] = 120000, [135] = 240, __size = 2}
		costItemMap6 = __data_t__costItemMap6[7]
		-- {['gold'] = 240000, [135] = 480, __size = 2}
	},
	[8] = {
		id = 8,
		costItemMap1 = {['gold'] = 25500, [135] = 51, __size = 2},
		costItemMap2 = __data_t__costItemMap2[8],
		-- {['gold'] = 37500, [135] = 75, __size = 2}
		costItemMap3 = {['gold'] = 38500, [135] = 77, __size = 2},
		costItemMap4 = {['gold'] = 89500, [135] = 179, __size = 2},
		costItemMap5 = __data_t__costItemMap5[8],
		-- {['gold'] = 127500, [135] = 255, __size = 2}
		costItemMap6 = __data_t__costItemMap6[8]
		-- {['gold'] = 255000, [135] = 510, __size = 2}
	},
	[9] = {
		id = 9,
		costItemMap1 = __data_t__costItemMap1[9],
		-- {['gold'] = 27000, [135] = 54, __size = 2}
		costItemMap2 = {['gold'] = 40000, [135] = 80, __size = 2},
		costItemMap3 = __data_t__costItemMap3[9],
		-- {['gold'] = 40500, [135] = 81, __size = 2}
		costItemMap4 = __data_t__costItemMap4[9],
		-- {['gold'] = 94500, [135] = 189, __size = 2}
		costItemMap5 = {['gold'] = 135000, [135] = 270, __size = 2},
		costItemMap6 = __data_t__costItemMap6[9]
		-- {['gold'] = 270000, [135] = 540, __size = 2}
	},
	[10] = {
		id = 10,
		costItemMap1 = {['gold'] = 28500, [135] = 57, __size = 2},
		costItemMap2 = {['gold'] = 42500, [135] = 85, __size = 2},
		costItemMap3 = {['gold'] = 43000, [135] = 86, __size = 2},
		costItemMap4 = __data_t__costItemMap4[10],
		-- {['gold'] = 100000, [135] = 200, __size = 2}
		costItemMap5 = {['gold'] = 142500, [135] = 285, __size = 2},
		costItemMap6 = __data_t__costItemMap6[10]
		-- {['gold'] = 285000, [135] = 570, __size = 2}
	},
	[11] = {
		id = 11,
		costItemMap1 = __data_t__costItemMap1[11],
		-- {['gold'] = 30000, [135] = 60, __size = 2}
		costItemMap2 = __data_t__costItemMap2[11],
		-- {['gold'] = 45000, [135] = 90, __size = 2}
		costItemMap3 = __data_t__costItemMap3[11],
		-- {['gold'] = 45000, [135] = 90, __size = 2}
		costItemMap4 = __data_t__costItemMap4[11],
		-- {['gold'] = 105000, [135] = 210, __size = 2}
		costItemMap5 = __data_t__costItemMap5[11],
		-- {['gold'] = 150000, [135] = 300, __size = 2}
		costItemMap6 = __data_t__costItemMap6[11]
		-- {['gold'] = 300000, [135] = 600, __size = 2}
	},
	[12] = {
		id = 12,
		costItemMap1 = __data_t__costItemMap1[12],
		-- {['gold'] = 31500, [135] = 63, __size = 2}
		costItemMap2 = __data_t__costItemMap2[12],
		-- {['gold'] = 47500, [135] = 95, __size = 2}
		costItemMap3 = __data_t__costItemMap3[12],
		-- {['gold'] = 47500, [135] = 95, __size = 2}
		costItemMap4 = __data_t__costItemMap4[12],
		-- {['gold'] = 110500, [135] = 221, __size = 2}
		costItemMap5 = __data_t__costItemMap5[12],
		-- {['gold'] = 157500, [135] = 315, __size = 2}
		costItemMap6 = __data_t__costItemMap6[12]
		-- {['gold'] = 315000, [135] = 630, __size = 2}
	},
	[13] = {
		id = 13,
		costItemMap1 = {['gold'] = 33000, [135] = 66, __size = 2},
		costItemMap2 = {['gold'] = 50000, [135] = 100, __size = 2},
		costItemMap3 = __data_t__costItemMap3[13],
		-- {['gold'] = 49500, [135] = 99, __size = 2}
		costItemMap4 = {['gold'] = 115500, [135] = 231, __size = 2},
		costItemMap5 = __data_t__costItemMap5[13],
		-- {['gold'] = 165000, [135] = 330, __size = 2}
		costItemMap6 = __data_t__costItemMap6[13]
		-- {['gold'] = 330000, [135] = 660, __size = 2}
	},
	[14] = {
		id = 14,
		costItemMap1 = {['gold'] = 34500, [135] = 69, __size = 2},
		costItemMap2 = __data_t__costItemMap2[14],
		-- {['gold'] = 52500, [135] = 105, __size = 2}
		costItemMap3 = {['gold'] = 52000, [135] = 104, __size = 2},
		costItemMap4 = {['gold'] = 121000, [135] = 242, __size = 2},
		costItemMap5 = {['gold'] = 172500, [135] = 345, __size = 2},
		costItemMap6 = __data_t__costItemMap6[14]
		-- {['gold'] = 345000, [135] = 690, __size = 2}
	},
	[15] = {
		id = 15,
		costItemMap1 = __data_t__costItemMap1[15],
		-- {['gold'] = 36000, [135] = 72, __size = 2}
		costItemMap2 = {['gold'] = 55000, [135] = 110, __size = 2},
		costItemMap3 = __data_t__costItemMap3[15],
		-- {['gold'] = 54000, [135] = 108, __size = 2}
		costItemMap4 = __data_t__costItemMap4[15],
		-- {['gold'] = 126000, [135] = 252, __size = 2}
		costItemMap5 = __data_t__costItemMap5[15],
		-- {['gold'] = 180000, [135] = 360, __size = 2}
		costItemMap6 = __data_t__costItemMap6[15]
		-- {['gold'] = 360000, [135] = 720, __size = 2}
	},
	[16] = {
		id = 16,
		costItemMap1 = __data_t__costItemMap1[16],
		-- {['gold'] = 37500, [135] = 75, __size = 2}
		costItemMap2 = __data_t__costItemMap2[16],
		-- {['gold'] = 57500, [135] = 115, __size = 2}
		costItemMap3 = {['gold'] = 56500, [135] = 113, __size = 2},
		costItemMap4 = {['gold'] = 131500, [135] = 263, __size = 2},
		costItemMap5 = {['gold'] = 187500, [135] = 375, __size = 2},
		costItemMap6 = __data_t__costItemMap6[16]
		-- {['gold'] = 375000, [135] = 750, __size = 2}
	},
	[17] = {
		id = 17,
		costItemMap1 = {['gold'] = 39000, [135] = 78, __size = 2},
		costItemMap2 = __data_t__costItemMap2[17],
		-- {['gold'] = 57500, [135] = 115, __size = 2}
		costItemMap3 = __data_t__costItemMap3[17],
		-- {['gold'] = 58500, [135] = 117, __size = 2}
		costItemMap4 = {['gold'] = 136500, [135] = 273, __size = 2},
		costItemMap5 = __data_t__costItemMap5[17],
		-- {['gold'] = 195000, [135] = 390, __size = 2}
		costItemMap6 = __data_t__costItemMap6[17]
		-- {['gold'] = 390000, [135] = 780, __size = 2}
	},
	[18] = {
		id = 18,
		costItemMap1 = __data_t__costItemMap1[18],
		-- {['gold'] = 40500, [135] = 81, __size = 2}
		costItemMap2 = __data_t__costItemMap2[18],
		-- {['gold'] = 60000, [135] = 120, __size = 2}
		costItemMap3 = {['gold'] = 61000, [135] = 122, __size = 2},
		costItemMap4 = {['gold'] = 142000, [135] = 284, __size = 2},
		costItemMap5 = {['gold'] = 202500, [135] = 405, __size = 2},
		costItemMap6 = __data_t__costItemMap6[18]
		-- {['gold'] = 405000, [135] = 810, __size = 2}
	},
	[19] = {
		id = 19,
		costItemMap1 = {['gold'] = 42000, [135] = 84, __size = 2},
		costItemMap2 = {['gold'] = 62500, [135] = 125, __size = 2},
		costItemMap3 = __data_t__costItemMap3[19],
		-- {['gold'] = 63000, [135] = 126, __size = 2}
		costItemMap4 = {['gold'] = 147000, [135] = 294, __size = 2},
		costItemMap5 = __data_t__costItemMap5[19],
		-- {['gold'] = 210000, [135] = 420, __size = 2}
		costItemMap6 = __data_t__costItemMap6[19]
		-- {['gold'] = 420000, [135] = 840, __size = 2}
	},
	[20] = {
		id = 20,
		costItemMap1 = {['gold'] = 43500, [135] = 87, __size = 2},
		costItemMap2 = {['gold'] = 65000, [135] = 130, __size = 2},
		costItemMap3 = {['gold'] = 65500, [135] = 131, __size = 2},
		costItemMap4 = {['gold'] = 152500, [135] = 305, __size = 2},
		costItemMap5 = {['gold'] = 217500, [135] = 435, __size = 2},
		costItemMap6 = __data_t__costItemMap6[20]
		-- {['gold'] = 435000, [135] = 870, __size = 2}
	},
	[21] = {
		id = 21,
		costItemMap1 = __data_t__costItemMap1[21],
		-- {['gold'] = 45000, [135] = 90, __size = 2}
		costItemMap2 = __data_t__costItemMap2[21],
		-- {['gold'] = 67500, [135] = 135, __size = 2}
		costItemMap3 = __data_t__costItemMap3[21],
		-- {['gold'] = 67500, [135] = 135, __size = 2}
		costItemMap4 = __data_t__costItemMap4[21],
		-- {['gold'] = 157500, [135] = 315, __size = 2}
		costItemMap5 = __data_t__costItemMap5[21],
		-- {['gold'] = 225000, [135] = 450, __size = 2}
		costItemMap6 = {['gold'] = 450000, [135] = 900, __size = 2}
	},
	[22] = {
		id = 22,
		costItemMap1 = {['gold'] = 46500, [135] = 93, __size = 2},
		costItemMap2 = __data_t__costItemMap2[22],
		-- {['gold'] = 70000, [135] = 140, __size = 2}
		costItemMap3 = __data_t__costItemMap3[22],
		-- {['gold'] = 70000, [135] = 140, __size = 2}
		costItemMap4 = {['gold'] = 163000, [135] = 326, __size = 2},
		costItemMap5 = {['gold'] = 232500, [135] = 465, __size = 2},
		costItemMap6 = {['gold'] = 465000, [135] = 930, __size = 2}
	},
	[23] = {
		id = 23,
		costItemMap1 = {['gold'] = 48000, [135] = 96, __size = 2},
		costItemMap2 = {['gold'] = 72500, [135] = 145, __size = 2},
		costItemMap3 = __data_t__costItemMap3[23],
		-- {['gold'] = 72000, [135] = 144, __size = 2}
		costItemMap4 = {['gold'] = 168000, [135] = 336, __size = 2},
		costItemMap5 = __data_t__costItemMap5[23],
		-- {['gold'] = 240000, [135] = 480, __size = 2}
		costItemMap6 = {['gold'] = 480000, [135] = 960, __size = 2}
	},
	[24] = {
		id = 24,
		costItemMap1 = __data_t__costItemMap1[24],
		-- {['gold'] = 49500, [135] = 99, __size = 2}
		costItemMap2 = __data_t__costItemMap2[24],
		-- {['gold'] = 75000, [135] = 150, __size = 2}
		costItemMap3 = {['gold'] = 74500, [135] = 149, __size = 2},
		costItemMap4 = {['gold'] = 173500, [135] = 347, __size = 2},
		costItemMap5 = {['gold'] = 247500, [135] = 495, __size = 2},
		costItemMap6 = {['gold'] = 495000, [135] = 990, __size = 2}
	},
	[25] = {
		id = 25,
		costItemMap1 = {['gold'] = 51000, [135] = 102, __size = 2},
		costItemMap2 = {['gold'] = 77500, [135] = 155, __size = 2},
		costItemMap3 = __data_t__costItemMap3[25],
		-- {['gold'] = 76500, [135] = 153, __size = 2}
		costItemMap4 = {['gold'] = 178500, [135] = 357, __size = 2},
		costItemMap5 = __data_t__costItemMap5[25],
		-- {['gold'] = 255000, [135] = 510, __size = 2}
		costItemMap6 = {['gold'] = 510000, [135] = 1020, __size = 2}
	},
	[26] = {
		id = 26,
		costItemMap1 = __data_t__costItemMap1[26],
		-- {['gold'] = 52500, [135] = 105, __size = 2}
		costItemMap2 = __data_t__costItemMap2[26],
		-- {['gold'] = 80000, [135] = 160, __size = 2}
		costItemMap3 = __data_t__costItemMap3[26],
		-- {['gold'] = 79000, [135] = 158, __size = 2}
		costItemMap4 = {['gold'] = 184000, [135] = 368, __size = 2},
		costItemMap5 = __data_t__costItemMap5[26],
		-- {['gold'] = 262500, [135] = 525, __size = 2}
		costItemMap6 = {['gold'] = 525000, [135] = 1050, __size = 2}
	},
	[27] = {
		id = 27,
		costItemMap1 = __data_t__costItemMap1[27],
		-- {['gold'] = 54000, [135] = 108, __size = 2}
		costItemMap2 = __data_t__costItemMap2[27],
		-- {['gold'] = 80000, [135] = 160, __size = 2}
		costItemMap3 = __data_t__costItemMap3[27],
		-- {['gold'] = 81000, [135] = 162, __size = 2}
		costItemMap4 = {['gold'] = 189000, [135] = 378, __size = 2},
		costItemMap5 = __data_t__costItemMap5[27],
		-- {['gold'] = 270000, [135] = 540, __size = 2}
		costItemMap6 = {['gold'] = 540000, [135] = 1080, __size = 2}
	},
	[28] = {
		id = 28,
		costItemMap1 = {['gold'] = 55500, [135] = 111, __size = 2},
		costItemMap2 = __data_t__costItemMap2[28],
		-- {['gold'] = 82500, [135] = 165, __size = 2}
		costItemMap3 = {['gold'] = 83500, [135] = 167, __size = 2},
		costItemMap4 = {['gold'] = 194500, [135] = 389, __size = 2},
		costItemMap5 = {['gold'] = 277500, [135] = 555, __size = 2},
		costItemMap6 = {['gold'] = 555000, [135] = 1110, __size = 2}
	},
	[29] = {
		id = 29,
		costItemMap1 = {['gold'] = 57000, [135] = 114, __size = 2},
		costItemMap2 = {['gold'] = 85000, [135] = 170, __size = 2},
		costItemMap3 = __data_t__costItemMap3[29],
		-- {['gold'] = 85500, [135] = 171, __size = 2}
		costItemMap4 = {['gold'] = 199500, [135] = 399, __size = 2},
		costItemMap5 = __data_t__costItemMap5[29],
		-- {['gold'] = 285000, [135] = 570, __size = 2}
		costItemMap6 = {['gold'] = 570000, [135] = 1140, __size = 2}
	},
	[30] = {
		id = 30,
		costItemMap1 = __data_t__costItemMap1[30],
		-- {['gold'] = 58500, [135] = 117, __size = 2}
		costItemMap2 = {['gold'] = 87500, [135] = 175, __size = 2},
		costItemMap3 = {['gold'] = 88000, [135] = 176, __size = 2},
		costItemMap4 = {['gold'] = 205000, [135] = 410, __size = 2},
		costItemMap5 = {['gold'] = 292500, [135] = 585, __size = 2},
		costItemMap6 = {['gold'] = 585000, [135] = 1170, __size = 2}
	},
	[31] = {
		id = 31,
		costItemMap1 = __data_t__costItemMap1[31],
		-- {['gold'] = 60000, [135] = 120, __size = 2}
		costItemMap2 = __data_t__costItemMap2[31],
		-- {['gold'] = 90000, [135] = 180, __size = 2}
		costItemMap3 = __data_t__costItemMap3[31],
		-- {['gold'] = 90000, [135] = 180, __size = 2}
		costItemMap4 = __data_t__costItemMap4[31],
		-- {['gold'] = 210000, [135] = 420, __size = 2}
		costItemMap5 = __data_t__costItemMap5[31],
		-- {['gold'] = 300000, [135] = 600, __size = 2}
		costItemMap6 = {['gold'] = 600000, [135] = 1200, __size = 2}
	},
	[32] = {
		id = 32,
		costItemMap1 = {['gold'] = 61500, [135] = 123, __size = 2},
		costItemMap2 = __data_t__costItemMap2[32],
		-- {['gold'] = 92500, [135] = 185, __size = 2}
		costItemMap3 = __data_t__costItemMap3[32],
		-- {['gold'] = 92500, [135] = 185, __size = 2}
		costItemMap4 = {['gold'] = 215500, [135] = 431, __size = 2},
		costItemMap5 = {['gold'] = 307500, [135] = 615, __size = 2},
		costItemMap6 = {['gold'] = 615000, [135] = 1230, __size = 2}
	},
	[33] = {
		id = 33,
		costItemMap1 = __data_t__costItemMap1[33],
		-- {['gold'] = 63000, [135] = 126, __size = 2}
		costItemMap2 = {['gold'] = 95000, [135] = 190, __size = 2},
		costItemMap3 = __data_t__costItemMap3[33],
		-- {['gold'] = 94500, [135] = 189, __size = 2}
		costItemMap4 = {['gold'] = 220500, [135] = 441, __size = 2},
		costItemMap5 = __data_t__costItemMap5[33],
		-- {['gold'] = 315000, [135] = 630, __size = 2}
		costItemMap6 = {['gold'] = 630000, [135] = 1260, __size = 2}
	},
	[34] = {
		id = 34,
		costItemMap1 = {['gold'] = 64500, [135] = 129, __size = 2},
		costItemMap2 = __data_t__costItemMap2[34],
		-- {['gold'] = 97500, [135] = 195, __size = 2}
		costItemMap3 = {['gold'] = 97000, [135] = 194, __size = 2},
		costItemMap4 = {['gold'] = 226000, [135] = 452, __size = 2},
		costItemMap5 = {['gold'] = 322500, [135] = 645, __size = 2},
		costItemMap6 = {['gold'] = 645000, [135] = 1290, __size = 2}
	},
	[35] = {
		id = 35,
		costItemMap1 = {['gold'] = 66000, [135] = 132, __size = 2},
		costItemMap2 = __data_t__costItemMap2[35],
		-- {['gold'] = 100000, [135] = 200, __size = 2}
		costItemMap3 = {['gold'] = 99000, [135] = 198, __size = 2},
		costItemMap4 = {['gold'] = 231000, [135] = 462, __size = 2},
		costItemMap5 = __data_t__costItemMap5[35],
		-- {['gold'] = 330000, [135] = 660, __size = 2}
		costItemMap6 = {['gold'] = 660000, [135] = 1320, __size = 2}
	},
	[36] = {
		id = 36,
		costItemMap1 = __data_t__costItemMap1[36],
		-- {['gold'] = 67500, [135] = 135, __size = 2}
		costItemMap2 = __data_t__costItemMap2[36],
		-- {['gold'] = 102500, [135] = 205, __size = 2}
		costItemMap3 = {['gold'] = 101500, [135] = 203, __size = 2},
		costItemMap4 = {['gold'] = 236500, [135] = 473, __size = 2},
		costItemMap5 = {['gold'] = 337500, [135] = 675, __size = 2},
		costItemMap6 = {['gold'] = 675000, [135] = 1350, __size = 2}
	},
	[37] = {
		id = 37,
		costItemMap1 = {['gold'] = 69000, [135] = 138, __size = 2},
		costItemMap2 = __data_t__costItemMap2[37],
		-- {['gold'] = 102500, [135] = 205, __size = 2}
		costItemMap3 = {['gold'] = 103500, [135] = 207, __size = 2},
		costItemMap4 = {['gold'] = 241500, [135] = 483, __size = 2},
		costItemMap5 = __data_t__costItemMap5[37],
		-- {['gold'] = 345000, [135] = 690, __size = 2}
		costItemMap6 = {['gold'] = 690000, [135] = 1380, __size = 2}
	},
	[38] = {
		id = 38,
		costItemMap1 = {['gold'] = 70500, [135] = 141, __size = 2},
		costItemMap2 = __data_t__costItemMap2[38],
		-- {['gold'] = 105000, [135] = 210, __size = 2}
		costItemMap3 = {['gold'] = 106000, [135] = 212, __size = 2},
		costItemMap4 = {['gold'] = 247000, [135] = 494, __size = 2},
		costItemMap5 = {['gold'] = 352500, [135] = 705, __size = 2},
		costItemMap6 = {['gold'] = 705000, [135] = 1410, __size = 2}
	},
	[39] = {
		id = 39,
		costItemMap1 = __data_t__costItemMap1[39],
		-- {['gold'] = 72000, [135] = 144, __size = 2}
		costItemMap2 = {['gold'] = 107500, [135] = 215, __size = 2},
		costItemMap3 = {['gold'] = 108000, [135] = 216, __size = 2},
		costItemMap4 = {['gold'] = 252000, [135] = 504, __size = 2},
		costItemMap5 = __data_t__costItemMap5[39],
		-- {['gold'] = 360000, [135] = 720, __size = 2}
		costItemMap6 = {['gold'] = 720000, [135] = 1440, __size = 2}
	},
	[40] = {
		id = 40,
		costItemMap1 = __data_t__costItemMap1[40],
		-- {['gold'] = 73500, [135] = 147, __size = 2}
		costItemMap2 = {['gold'] = 110000, [135] = 220, __size = 2},
		costItemMap3 = __data_t__costItemMap3[40],
		-- {['gold'] = 110500, [135] = 221, __size = 2}
		costItemMap4 = {['gold'] = 257500, [135] = 515, __size = 2},
		costItemMap5 = {['gold'] = 367500, [135] = 735, __size = 2},
		costItemMap6 = {['gold'] = 735000, [135] = 1470, __size = 2}
	},
	[41] = {
		id = 41,
		costItemMap1 = __data_t__costItemMap1[41],
		-- {['gold'] = 75000, [135] = 150, __size = 2}
		costItemMap2 = __data_t__costItemMap2[41],
		-- {['gold'] = 112500, [135] = 225, __size = 2}
		costItemMap3 = __data_t__costItemMap3[41],
		-- {['gold'] = 112500, [135] = 225, __size = 2}
		costItemMap4 = __data_t__costItemMap4[41],
		-- {['gold'] = 262500, [135] = 525, __size = 2}
		costItemMap5 = __data_t__costItemMap5[41],
		-- {['gold'] = 375000, [135] = 750, __size = 2}
		costItemMap6 = {['gold'] = 750000, [135] = 1500, __size = 2}
	},
	[42] = {
		id = 42,
		costItemMap1 = __data_t__costItemMap1[42],
		-- {['gold'] = 76500, [135] = 153, __size = 2}
		costItemMap2 = __data_t__costItemMap2[42],
		-- {['gold'] = 115000, [135] = 230, __size = 2}
		costItemMap3 = __data_t__costItemMap3[42],
		-- {['gold'] = 115000, [135] = 230, __size = 2}
		costItemMap4 = {['gold'] = 268000, [135] = 536, __size = 2},
		costItemMap5 = {['gold'] = 382500, [135] = 765, __size = 2},
		costItemMap6 = {['gold'] = 765000, [135] = 1530, __size = 2}
	},
	[43] = {
		id = 43,
		costItemMap1 = {['gold'] = 78000, [135] = 156, __size = 2},
		costItemMap2 = {['gold'] = 117500, [135] = 235, __size = 2},
		costItemMap3 = {['gold'] = 117000, [135] = 234, __size = 2},
		costItemMap4 = {['gold'] = 273000, [135] = 546, __size = 2},
		costItemMap5 = __data_t__costItemMap5[43],
		-- {['gold'] = 390000, [135] = 780, __size = 2}
		costItemMap6 = {['gold'] = 780000, [135] = 1560, __size = 2}
	},
	[44] = {
		id = 44,
		costItemMap1 = {['gold'] = 79500, [135] = 159, __size = 2},
		costItemMap2 = __data_t__costItemMap2[44],
		-- {['gold'] = 120000, [135] = 240, __size = 2}
		costItemMap3 = {['gold'] = 119500, [135] = 239, __size = 2},
		costItemMap4 = {['gold'] = 278500, [135] = 557, __size = 2},
		costItemMap5 = {['gold'] = 397500, [135] = 795, __size = 2},
		costItemMap6 = {['gold'] = 795000, [135] = 1590, __size = 2}
	},
	[45] = {
		id = 45,
		costItemMap1 = __data_t__costItemMap1[45],
		-- {['gold'] = 81000, [135] = 162, __size = 2}
		costItemMap2 = {['gold'] = 122500, [135] = 245, __size = 2},
		costItemMap3 = {['gold'] = 121500, [135] = 243, __size = 2},
		costItemMap4 = {['gold'] = 283500, [135] = 567, __size = 2},
		costItemMap5 = __data_t__costItemMap5[45],
		-- {['gold'] = 405000, [135] = 810, __size = 2}
		costItemMap6 = {['gold'] = 810000, [135] = 1620, __size = 2}
	},
	[46] = {
		id = 46,
		costItemMap1 = __data_t__costItemMap1[46],
		-- {['gold'] = 82500, [135] = 165, __size = 2}
		costItemMap2 = __data_t__costItemMap2[46],
		-- {['gold'] = 125000, [135] = 250, __size = 2}
		costItemMap3 = {['gold'] = 124000, [135] = 248, __size = 2},
		costItemMap4 = {['gold'] = 289000, [135] = 578, __size = 2},
		costItemMap5 = {['gold'] = 412500, [135] = 825, __size = 2},
		costItemMap6 = {['gold'] = 825000, [135] = 1650, __size = 2}
	},
	[47] = {
		id = 47,
		costItemMap1 = __data_t__costItemMap1[47],
		-- {['gold'] = 84000, [135] = 168, __size = 2}
		costItemMap2 = __data_t__costItemMap2[47],
		-- {['gold'] = 125000, [135] = 250, __size = 2}
		costItemMap3 = __data_t__costItemMap3[47],
		-- {['gold'] = 126000, [135] = 252, __size = 2}
		costItemMap4 = {['gold'] = 294000, [135] = 588, __size = 2},
		costItemMap5 = __data_t__costItemMap5[47],
		-- {['gold'] = 420000, [135] = 840, __size = 2}
		costItemMap6 = {['gold'] = 840000, [135] = 1680, __size = 2}
	},
	[48] = {
		id = 48,
		costItemMap1 = __data_t__costItemMap1[48],
		-- {['gold'] = 85500, [135] = 171, __size = 2}
		costItemMap2 = __data_t__costItemMap2[48],
		-- {['gold'] = 127500, [135] = 255, __size = 2}
		costItemMap3 = {['gold'] = 128500, [135] = 257, __size = 2},
		costItemMap4 = {['gold'] = 299500, [135] = 599, __size = 2},
		costItemMap5 = {['gold'] = 427500, [135] = 855, __size = 2},
		costItemMap6 = {['gold'] = 855000, [135] = 1710, __size = 2}
	},
	[49] = {
		id = 49,
		costItemMap1 = {['gold'] = 87000, [135] = 174, __size = 2},
		costItemMap2 = {['gold'] = 130000, [135] = 260, __size = 2},
		costItemMap3 = {['gold'] = 130500, [135] = 261, __size = 2},
		costItemMap4 = {['gold'] = 304500, [135] = 609, __size = 2},
		costItemMap5 = __data_t__costItemMap5[49],
		-- {['gold'] = 435000, [135] = 870, __size = 2}
		costItemMap6 = {['gold'] = 870000, [135] = 1740, __size = 2}
	},
	[50] = {
		id = 50,
		costItemMap1 = {['gold'] = 88500, [135] = 177, __size = 2},
		costItemMap2 = {['gold'] = 132500, [135] = 265, __size = 2},
		costItemMap3 = {['gold'] = 133000, [135] = 266, __size = 2},
		costItemMap4 = {['gold'] = 310000, [135] = 620, __size = 2},
		costItemMap5 = {['gold'] = 442500, [135] = 885, __size = 2},
		costItemMap6 = {['gold'] = 885000, [135] = 1770, __size = 2}
	},
	__size = 50,
	__default = {
		__index = {
			costItemMap1 = __data_t__costItemMap1["default"]	--[[ {__size = 0}]],
			costItemMap2 = __data_t__costItemMap2["default"]	--[[ {__size = 0}]],
			costItemMap3 = __data_t__costItemMap3["default"]	--[[ {__size = 0}]],
			costItemMap4 = __data_t__costItemMap4["default"]	--[[ {__size = 0}]],
			costItemMap5 = __data_t__costItemMap5["default"]	--[[ {__size = 0}]],
			costItemMap6 = __data_t__costItemMap6["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.emera.strength_cost