slot0 = {
	{},
	__size = 12,
	[3] = {
		11,
		12,
		13,
		14,
		15,
		16
	},
	[4] = {
		5,
		10,
		15,
		20,
		25,
		30,
		35,
		40,
		45,
		50,
		55,
		60,
		65,
		70,
		75,
		80,
		85,
		90,
		95,
		100,
		105,
		110,
		115,
		120
	},
	[5] = {
		"2.0%",
		"4.0%",
		"6.0%",
		"8.0%",
		"10.0%",
		"12.0%",
		"14.0%",
		"16.0%",
		"18.0%",
		"20.0%",
		"22.0%",
		"24.0%",
		"26.0%",
		"28.0%",
		"30.0%",
		"32.0%",
		"34.0%",
		"36.0%",
		"38.0%",
		"40.0%",
		"42.0%",
		"44.0%",
		"46.0%",
		"48.0%"
	},
	[6] = {
		10,
		20,
		30,
		40,
		50,
		60,
		70,
		80,
		90,
		100,
		110,
		120,
		130,
		140,
		150,
		160,
		170,
		180,
		190,
		200,
		210,
		220,
		230,
		240
	},
	[8] = {
		21,
		22,
		23,
		24,
		25,
		26
	},
	[10] = {
		41,
		42,
		43,
		44,
		45,
		46
	},
	[12] = {
		31,
		32,
		33,
		34,
		35,
		36
	},
	[14] = {
		51,
		52,
		53,
		54,
		55,
		56
	},
	[16] = {
		61,
		62,
		63,
		64,
		65,
		66
	},
	[18] = {
		71,
		72,
		73,
		74,
		75,
		76
	},
	[20] = {
		81,
		82,
		83,
		84,
		85,
		86
	}
}
slot2 = {
	slot0[6],
	slot0[6],
	default = slot0[1],
	[3] = slot0[6],
	[5] = slot0[6],
	[4] = slot0[6],
	[7] = slot0[6],
	[6] = slot0[6],
	[8] = slot0[6]
}
slot4 = {
	slot0[4],
	slot0[4],
	default = slot0[1],
	[3] = slot0[4],
	[5] = slot0[4],
	[4] = slot0[4],
	[7] = slot0[4],
	[6] = slot0[4],
	[8] = slot0[4]
}
slot5 = {
	slot0[3],
	slot0[8],
	default = slot0[1],
	[3] = slot0[10],
	[5] = slot0[14],
	[4] = slot0[12],
	[7] = slot0[18],
	[6] = slot0[16],
	[8] = slot0[20]
}
slot6 = {
	slot0[3],
	slot0[8],
	default = slot0[1],
	[3] = slot0[10],
	[5] = slot0[14],
	[4] = slot0[12],
	[7] = slot0[18],
	[6] = slot0[16],
	[8] = slot0[20]
}
slot7 = {
	slot0[5],
	slot0[5],
	default = slot0[1],
	[3] = slot0[5],
	[5] = slot0[5],
	[4] = slot0[5],
	[7] = slot0[5],
	[6] = slot0[5],
	[8] = slot0[5]
}
csv.gym_badge.badge = {
	{
		name = "Rock Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_bing2.png",
		name_kr = "Rock Badge",
		attrType1 = 92,
		name_en = "Rock Badge",
		showIcon1 = "city/develop/gym_badge/icon_bing1.png",
		icon = "city/develop/gym_badge/badge/icon_bing.png",
		awakeCostSeqID = 1,
		name_pt = "Rock Badge",
		showIcon3 = "city/develop/gym_badge/icon_l3.png",
		name_vn = "Rock Badge",
		name_th = "Rock Badge",
		id = 1,
		awakeMaxLevel = 24,
		nature = {
			9,
			13
		},
		talentIDs = slot5[1],
		preTalentLevel = slot4[1],
		awakeTalentAttrs = slot7[1],
		attrNum1 = slot2[1],
		guardIDs = slot6[1]
	},
	{
		name = "Water Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_shui2.png",
		name_kr = "Water Badge",
		attrType1 = 93,
		name_en = "Water Badge",
		showIcon1 = "city/develop/gym_badge/icon_shui1.png",
		icon = "city/develop/gym_badge/badge/icon_shui.png",
		awakeCostSeqID = 2,
		name_pt = "Water Badge",
		showIcon3 = "city/develop/gym_badge/icon_lq2.png",
		name_vn = "Water Badge",
		name_th = "Water Badge",
		id = 2,
		awakeMaxLevel = 24,
		nature = {
			3,
			6
		},
		talentIDs = slot5[2],
		preTalentLevel = slot4[2],
		awakeTalentAttrs = slot7[2],
		attrNum1 = slot2[2],
		guardIDs = slot6[2]
	},
	{
		name = "Grass Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_cao2.png",
		name_kr = "Grass Badge",
		attrType1 = 92,
		name_en = "Grass Badge",
		showIcon1 = "city/develop/gym_badge/icon_cao1.png",
		icon = "city/develop/gym_badge/badge/icon_cao.png",
		awakeCostSeqID = 4,
		name_pt = "Grass Badge",
		showIcon3 = "city/develop/gym_badge/icon_lv.png",
		name_vn = "Grass Badge",
		name_th = "Grass Badge",
		id = 3,
		awakeMaxLevel = 24,
		nature = {
			1,
			4,
			10
		},
		talentIDs = slot5[3],
		preTalentLevel = slot4[3],
		awakeTalentAttrs = slot7[3],
		attrNum1 = slot2[3],
		guardIDs = slot6[3]
	},
	{
		name = "Fire Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_huo2.png",
		name_kr = "Fire Badge",
		attrType1 = 93,
		name_en = "Fire Badge",
		showIcon1 = "city/develop/gym_badge/icon_huo1.png",
		icon = "city/develop/gym_badge/badge/icon_huo.png",
		awakeCostSeqID = 3,
		name_pt = "Fire Badge",
		showIcon3 = "city/develop/gym_badge/icon_huang.png",
		name_vn = "Fire Badge",
		name_th = "Fire Badge",
		id = 4,
		awakeMaxLevel = 24,
		nature = {
			2,
			7
		},
		talentIDs = slot5[4],
		preTalentLevel = slot4[4],
		awakeTalentAttrs = slot7[4],
		attrNum1 = slot2[4],
		guardIDs = slot6[4]
	},
	{
		name = "Dragon Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_long2.png",
		name_kr = "Dragon Badge",
		attrType1 = 92,
		name_en = "Dragon Badge",
		showIcon1 = "city/develop/gym_badge/icon_long1.png",
		preBadgeID = 1,
		preLevel = 10,
		icon = "city/develop/gym_badge/badge/icon_long.png",
		awakeCostSeqID = 5,
		name_pt = "Dragon Badge",
		preBadgeType = 2,
		showIcon3 = "city/develop/gym_badge/icon_lq1.png",
		name_vn = "Dragon Badge",
		name_th = "Dragon Badge",
		id = 5,
		awakeMaxLevel = 24,
		nature = {
			5,
			15
		},
		talentIDs = slot5[5],
		preTalentLevel = slot4[5],
		awakeTalentAttrs = slot7[5],
		attrNum1 = slot2[5],
		guardIDs = slot6[5]
	},
	{
		name = "Dark Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_e2.png",
		name_kr = "Dark Badge",
		attrType1 = 93,
		name_en = "Dark Badge",
		showIcon1 = "city/develop/gym_badge/icon_e1.png",
		preBadgeID = 2,
		preLevel = 10,
		icon = "city/develop/gym_badge/badge/icon_e.png",
		awakeCostSeqID = 6,
		name_pt = "Dark Badge",
		preBadgeType = 2,
		showIcon3 = "city/develop/gym_badge/icon_hei.png",
		name_vn = "Dark Badge",
		name_th = "Dark Badge",
		id = 6,
		awakeMaxLevel = 24,
		nature = {
			14,
			16
		},
		talentIDs = slot5[6],
		preTalentLevel = slot4[6],
		awakeTalentAttrs = slot7[6],
		attrNum1 = slot2[6],
		guardIDs = slot6[6]
	},
	{
		name = "Ghost Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_du2.png",
		name_kr = "Ghost Badge",
		attrType1 = 92,
		name_en = "Ghost Badge",
		showIcon1 = "city/develop/gym_badge/icon_du1.png",
		preBadgeID = 3,
		preLevel = 10,
		icon = "city/develop/gym_badge/badge/icon_du.png",
		awakeCostSeqID = 7,
		name_pt = "Ghost Badge",
		preBadgeType = 2,
		showIcon3 = "city/develop/gym_badge/icon_zi.png",
		name_vn = "Ghost Badge",
		name_th = "Ghost Badge",
		id = 7,
		awakeMaxLevel = 24,
		nature = {
			8,
			12,
			17
		},
		talentIDs = slot5[7],
		preTalentLevel = slot4[7],
		awakeTalentAttrs = slot7[7],
		attrNum1 = slot2[7],
		guardIDs = slot6[7]
	},
	{
		name = "Fairy Badge",
		talentMaxLevel = 120,
		showIcon2 = "city/develop/gym_badge/icon_yao2.png",
		name_kr = "Fairy Badge",
		attrType1 = 93,
		name_en = "Fairy Badge",
		showIcon1 = "city/develop/gym_badge/icon_yao1.png",
		preBadgeID = 4,
		preLevel = 10,
		icon = "city/develop/gym_badge/badge/icon_yao.png",
		awakeCostSeqID = 8,
		name_pt = "Fairy Badge",
		preBadgeType = 2,
		showIcon3 = "city/develop/gym_badge/icon_hong.png",
		name_vn = "Fairy Badge",
		name_th = "Fairy Badge",
		id = 8,
		awakeMaxLevel = 24,
		nature = {
			11,
			18
		},
		talentIDs = slot5[8],
		preTalentLevel = slot4[8],
		awakeTalentAttrs = slot7[8],
		attrNum1 = slot2[8],
		guardIDs = slot6[8]
	},
	__size = 8,
	__default = {
		__index = {
			name = "",
			preBadgeType = 1,
			talentMaxLevel = 50,
			icon = "",
			awakeMaxLevel = 20,
			nature = ({
				default = slot0[1]
			}).default,
			talentIDs = slot5.default,
			preTalentLevel = slot4.default,
			awakeTalentAttrs = slot7.default,
			attrNum1 = slot2.default,
			attrNum2 = ({
				default = slot0[1]
			}).default,
			guardIDs = slot6.default
		}
	}
}

return csv.gym_badge.badge
