--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[2] = {__size = 0}, 
	[7] = {850009901}, 
	[8] = {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}, 
	[10] = {[1] = 'true', __size = 1}, 
	[16] = {850001401, 850000801}, 
	[19] = {850001201, 850001701}, 
	[21] = {850000201}, 
	[25] = {850000501}, 
	[30] = {850000301}, 
	[33] = {850000301, 850000901}, 
	[36] = {850001101, 850001801}, 
	[45] = {850001701, 850000701}, 
	[57] = {850001801}, __size = 14}
local __data_t__buffs = {
	[741] = __predefine_t__[21],
	[881] = __predefine_t__[25],
	[601] = __predefine_t__[21],
	[884] = __predefine_t__[25],
	[571] = __predefine_t__[19],
	[574] = __predefine_t__[19],
	["default"] = __predefine_t__[1],
	[1921] = __predefine_t__[7],
	[391] = __predefine_t__[16],
	[394] = __predefine_t__[16],
	[3661] = __predefine_t__[7],
	[1421] = __predefine_t__[7],
	[1171] = __predefine_t__[7],
	[4161] = __predefine_t__[25],
	[731] = __predefine_t__[25],
	[2421] = __predefine_t__[30],
	[1396] = __predefine_t__[36],
	[2241] = __predefine_t__[45],
	[1391] = __predefine_t__[36],
	[2243] = __predefine_t__[45],
	[3601] = __predefine_t__[57],
	[1314] = __predefine_t__[33],
	[1173] = __predefine_t__[7],
	[2461] = __predefine_t__[7],
	[1311] = __predefine_t__[33],
	[1271] = __predefine_t__[21],
	[711] = __predefine_t__[7],
	[3351] = __predefine_t__[57],
	[161] = __predefine_t__[7],
	[1991] = __predefine_t__[7],
	[1241] = __predefine_t__[30],
	[2391] = __predefine_t__[7],
	[2351] = __predefine_t__[7]
}
local __data_t__conditions = {
	[741] = __predefine_t__[8],
	[881] = __predefine_t__[8],
	[601] = __predefine_t__[8],
	[1081] = __predefine_t__[8],
	[884] = __predefine_t__[8],
	[571] = __predefine_t__[8],
	[574] = __predefine_t__[8],
	[1921] = __predefine_t__[8],
	[391] = __predefine_t__[8],
	[3151] = __predefine_t__[8],
	[394] = __predefine_t__[8],
	[3661] = __predefine_t__[8],
	[1891] = __predefine_t__[8],
	[2461] = __predefine_t__[8],
	[1421] = __predefine_t__[8],
	[2381] = __predefine_t__[10],
	[1221] = __predefine_t__[10],
	[4161] = __predefine_t__[8],
	[2471] = __predefine_t__[8],
	[3651] = __predefine_t__[8],
	[731] = __predefine_t__[8],
	[2421] = __predefine_t__[8],
	[1396] = __predefine_t__[8],
	[1261] = __predefine_t__[10],
	[1391] = __predefine_t__[8],
	[2243] = __predefine_t__[8],
	[3601] = __predefine_t__[8],
	[1314] = __predefine_t__[8],
	[1173] = __predefine_t__[8],
	[1231] = __predefine_t__[10],
	[1171] = __predefine_t__[8],
	[1271] = __predefine_t__[8],
	[611] = __predefine_t__[8],
	[3611] = __predefine_t__[8],
	[711] = __predefine_t__[8],
	[381] = __predefine_t__[10],
	[261] = __predefine_t__[10],
	[241] = __predefine_t__[10],
	[264] = __predefine_t__[10],
	[1911] = __predefine_t__[8],
	[1311] = __predefine_t__[8],
	[161] = __predefine_t__[8],
	[1991] = __predefine_t__[8],
	[1281] = __predefine_t__[10],
	[2391] = __predefine_t__[8],
	[1931] = __predefine_t__[8],
	[2431] = __predefine_t__[10],
	[2241] = __predefine_t__[8],
	[1241] = __predefine_t__[8],
	[2361] = __predefine_t__[10],
	[721] = __predefine_t__[10],
	[2721] = __predefine_t__[8],
	[3351] = __predefine_t__[8],
	[2351] = __predefine_t__[8]
}
local __data_t__skin2SkillID = {
	["default"] = __predefine_t__[2]
}
local __data_t__devSkillID = {
	["default"] = __predefine_t__[1]
}
local __data_t__keyWords = {
	["default"] = __predefine_t__[2]
}

csv['aid']['aid_skill'] = {
	[161] = {
		id = 161,
		name = '剧毒炸弹',
		triggerType = 3,
		devSkillID = {8001611, 8001621, 8001631},
		buffs = __data_t__buffs[161],
		-- {850009901}
		conditions = __data_t__conditions[161],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8001611
	},
	[241] = {
		id = 241,
		name = '闪焰冲锋',
		devSkillID = {8002411, 8002421},
		conditions = __data_t__conditions[241],
		-- {[1] = 'true', __size = 1}
		skillID = 8002421
	},
	[261] = {
		id = 261,
		name = '精神利刃',
		devSkillID = {8002611, 8002621, 8002631},
		skin2SkillID = {[265] = 8002651, __size = 1},
		conditions = __data_t__conditions[261],
		-- {[1] = 'true', __size = 1}
		skillID = 8002631
	},
	[264] = {
		id = 264,
		name = '超·精神利刃',
		conditions = __data_t__conditions[264],
		-- {[1] = 'true', __size = 1}
		skillID = 8002641
	},
	[381] = {
		id = 381,
		name = '水冰冲撞',
		devSkillID = {8003811, 8003821},
		conditions = __data_t__conditions[381],
		-- {[1] = 'true', __size = 1}
		skillID = 8003821
	},
	[391] = {
		id = 391,
		name = '恐惧',
		triggerType = 3,
		devSkillID = {8003911, 8003921, 8003931},
		skin2SkillID = {[395] = 8003951, __size = 1},
		buffs = __data_t__buffs[391],
		-- {850001401, 850000801}
		conditions = __data_t__conditions[391],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8003911
	},
	[394] = {
		id = 394,
		name = '食梦',
		triggerType = 3,
		buffs = __data_t__buffs[394],
		-- {850001401, 850000801}
		conditions = __data_t__conditions[394],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8003941
	},
	[571] = {
		id = 571,
		name = '飞天掠杀',
		triggerType = 3,
		devSkillID = {8057111, 8057211},
		skin2SkillID = {[573] = 8057311, __size = 1},
		buffs = __data_t__buffs[571],
		-- {850001201, 850001701}
		conditions = __data_t__conditions[571],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8057111
	},
	[574] = {
		id = 574,
		name = '超·飞天掠杀',
		triggerType = 3,
		buffs = __data_t__buffs[574],
		-- {850001201, 850001701}
		conditions = __data_t__conditions[574],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8057411
	},
	[601] = {
		id = 601,
		name = '岩浆烈焰',
		triggerType = 3,
		devSkillID = {8006011, 8006021, 8006031},
		buffs = __data_t__buffs[601],
		-- {850000201}
		conditions = __data_t__conditions[601],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8006031
	},
	[611] = {
		id = 611,
		name = '巨钳',
		triggerType = 3,
		buffs = {850001201},
		conditions = __data_t__conditions[611],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8006111
	},
	[711] = {
		id = 711,
		triggerType = 3,
		devSkillID = {8071111, 8071211},
		buffs = __data_t__buffs[711],
		-- {850009901}
		conditions = __data_t__conditions[711],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8071111
	},
	[721] = {
		id = 721,
		name = '冰山',
		conditions = __data_t__conditions[721],
		-- {[1] = 'true', __size = 1}
		skillID = 8007211
	},
	[731] = {
		id = 731,
		name = '雷霆万钧',
		triggerType = 3,
		skin2SkillID = {[732] = 8007321, __size = 1},
		buffs = __data_t__buffs[731],
		-- {850000501}
		conditions = __data_t__conditions[731],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8007311
	},
	[741] = {
		id = 741,
		name = '灰烬烈焰',
		triggerType = 3,
		buffs = __data_t__buffs[741],
		-- {850000201}
		conditions = __data_t__conditions[741],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8007411
	},
	[881] = {
		id = 881,
		name = '电能激荡',
		triggerType = 3,
		devSkillID = {8088111, 8088211, 8088311},
		buffs = __data_t__buffs[881],
		-- {850000501}
		conditions = __data_t__conditions[881],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8088311
	},
	[884] = {
		id = 884,
		name = '超·电能激荡',
		triggerType = 3,
		buffs = __data_t__buffs[884],
		-- {850000501}
		conditions = __data_t__conditions[884],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8088411
	},
	[1081] = {
		id = 1081,
		name = '超·寒冰陷阱',
		triggerType = 3,
		devSkillID = {8010811, 8010821},
		buffs = {850000601},
		conditions = __data_t__conditions[1081],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8010811
	},
	[1171] = {
		id = 1171,
		name = '围猎',
		triggerType = 3,
		devSkillID = {8011711, 8011721},
		buffs = __data_t__buffs[1171],
		-- {850009901}
		conditions = __data_t__conditions[1171],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8011721
	},
	[1173] = {
		id = 1173,
		name = '超·围猎',
		triggerType = 3,
		buffs = __data_t__buffs[1173],
		-- {850009901}
		conditions = __data_t__conditions[1173],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8011731
	},
	[1221] = {
		id = 1221,
		name = '雷霆之爪',
		conditions = __data_t__conditions[1221],
		-- {[1] = 'true', __size = 1}
		skillID = 8012211
	},
	[1231] = {
		id = 1231,
		name = '末日炎爆',
		conditions = __data_t__conditions[1231],
		-- {[1] = 'true', __size = 1}
		skillID = 8012311
	},
	[1241] = {
		id = 1241,
		name = '踏浪漩涡',
		triggerType = 3,
		buffs = __data_t__buffs[1241],
		-- {850000301}
		conditions = __data_t__conditions[1241],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8012411
	},
	[1261] = {
		id = 1261,
		name = '漩涡风暴',
		awakeDescribes = '额外给1个己方添加【助·风神结界】#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$回合（优先攻击最高队友）(【助·风神结界】：2级增益，不可叠加，闪避提升#C0x5c9970#$(10+(skillLevel >= 2 and 10 or 0))$%#C0x5B545B#，受到伤害降低#C0x5c9970#$(7+(skillLevel >= 3 and 8 or 0))$%#C0x5B545B#，攻击结界目标会受到释放者#C0x5c9970#$(40+(skillLevel >= 4 and 40 or 0))$%#C0x5B545B#特攻反伤；溅射、陷阱和负面效果不会扩散至结界外)',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		conditions = __data_t__conditions[1261],
		-- {[1] = 'true', __size = 1}
		skillID = 8012611
	},
	[1271] = {
		id = 1271,
		name = '凤翔九天',
		triggerType = 3,
		awakeDescribes = '额外给1个己方添加【助·涅磐】（每个单位限1次），触发后目标提升20%伤害减免2回合（【助·涅磐】：特殊效果，受到致死伤害消耗【助·涅磐】变成凤凰蛋，可承受#C0x5c9970#$(3+(skillLevel >= 2 and 1 or 0)+(skillLevel >= 4 and 1 or 0))$#C0x5B545B#次主动攻击，被攻击时对敌人添加1层【圣火灼烧】，若未被击破，则下回合行动前，以#C0x5c9970#$(50+(skillLevel >= 3 and 10 or 0)+(skillLevel >= 5 and 20 or 0))$%#C0x5B545B#的血量和#C0x5c9970#$(50+(skillLevel >= 3 and 20 or 0)+(skillLevel >= 5 and 30 or 0))$%#C0x5B545B#怒气重生）',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		buffs = __data_t__buffs[1271],
		-- {850000201}
		conditions = __data_t__conditions[1271],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8012711
	},
	[1281] = {
		id = 1281,
		name = '时空乱流',
		awakeDescribes = '额外给己方攻击最高的#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#个超/草系精灵添加【助·时间刻印】#C0x5c9970#$(1+(skillLevel >= 1 and 1 or 0)+(skillLevel >= 4 and 1 or 0))$#C0x5B545B#回合 【助·时间刻印】：3级增益，受到致命伤害时，消耗此刻印，回溯至#C0x5c9970#$(20+(skillLevel >= 3 and 20 or 0))$%#C0x5B545B#怒气和#C0x5c9970#$(20+(skillLevel >= 2 and 20 or 0))$%#C0x5B545B#血量（不受治疗效果和怒气回复速度影响）',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[1282] = 8012821, __size = 1},
		conditions = __data_t__conditions[1281],
		-- {[1] = 'true', __size = 1}
		skillID = 8012811
	},
	[1311] = {
		id = 1311,
		name = '泥巴潮汐',
		triggerType = 3,
		devSkillID = {8013111, 8013121, 8013131},
		buffs = __data_t__buffs[1311],
		-- {850000301, 850000901}
		conditions = __data_t__conditions[1311],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8013131
	},
	[1314] = {
		id = 1314,
		name = '超·泥巴潮汐',
		triggerType = 3,
		buffs = __data_t__buffs[1314],
		-- {850000301, 850000901}
		conditions = __data_t__conditions[1314],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8013141
	},
	[1391] = {
		id = 1391,
		name = '心灵致动',
		triggerType = 3,
		devSkillID = {8013911, 8013921, 8013931},
		skin2SkillID = {[1394] = 8013941, __size = 1},
		buffs = __data_t__buffs[1391],
		-- {850001101, 850001801}
		conditions = __data_t__conditions[1391],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8013911
	},
	[1396] = {
		id = 1396,
		name = '超·心灵致动',
		triggerType = 3,
		buffs = __data_t__buffs[1396],
		-- {850001101, 850001801}
		conditions = __data_t__conditions[1396],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8013961
	},
	[1421] = {
		id = 1421,
		name = '抓狂',
		triggerType = 3,
		devSkillID = {8014211, 8014221, 8014231},
		buffs = __data_t__buffs[1421],
		-- {850009901}
		conditions = __data_t__conditions[1421],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8014211
	},
	[1891] = {
		id = 1891,
		name = '爆裂龙息',
		triggerType = 3,
		devSkillID = {8018911, 8018921, 8018931},
		buffs = {850001001, 850001501},
		conditions = __data_t__conditions[1891],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8018911
	},
	[1911] = {
		id = 1911,
		name = '岩石冲击',
		triggerType = 3,
		buffs = {850001301},
		conditions = __data_t__conditions[1911],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8019111
	},
	[1921] = {
		id = 1921,
		name = '冰封大地',
		triggerType = 3,
		buffs = __data_t__buffs[1921],
		-- {850009901}
		conditions = __data_t__conditions[1921],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8019211
	},
	[1931] = {
		id = 1931,
		name = '加农光炮',
		triggerType = 3,
		buffs = {850001701},
		conditions = __data_t__conditions[1931],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8019311
	},
	[1991] = {
		id = 1991,
		name = '超·天恩',
		triggerType = 3,
		awakeDescribes = '额外给1个获得【助·天恩】的超/钢系队友添加【祈愿】#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#回合 【祈愿】：每次主动行动前额外获得1个许愿灵签；每次获得许愿灵签时，根据获得的许愿灵签强化目标，【助·反击之愿】给目标添加基拉祈#C0x5c9970#$(10+(skillLevel >= 2 and 10 or 0))$%#C0x5B545B#生命上限的护盾，【助·协战之愿】给目标治疗#C0x5c9970#$(5+(skillLevel >= 3 and 5 or 0))$%#C0x5B545B#生命上限的生命，【助·追击之愿】使目标获得#C0x5c9970#$(7+(skillLevel >= 4 and 8 or 0))$%#C0x5B545B#吸血率',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[1992] = 8019921, __size = 1},
		buffs = __data_t__buffs[1991],
		-- {850009901}
		conditions = __data_t__conditions[1991],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8019911
	},
	[2241] = {
		id = 2241,
		name = '真气弹',
		triggerType = 3,
		devSkillID = {8022411, 8022421},
		skin2SkillID = {[2243] = 8022431, __size = 1},
		buffs = __data_t__buffs[2241],
		-- {850001701, 850000701}
		conditions = __data_t__conditions[2241],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8022421
	},
	[2243] = {
		id = 2243,
		name = '超·真气弹',
		triggerType = 3,
		buffs = __data_t__buffs[2243],
		-- {850001701, 850000701}
		conditions = __data_t__conditions[2243],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8022441
	},
	[2351] = {
		id = 2351,
		name = '时光咆哮',
		triggerType = 3,
		awakeDescribes = '对1个双攻最高友方添加【时光回响】#C0x5c9970#$(2+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#回合（优先攻击最高队友）(【时光回响】:2级增益，期间伤害加成提升#C0x5c9970#$(10+(skillLevel >= 3 and 10 or 0))$%#C0x5B545B#，使用主动技能后，在大回合结束时有#C0x5c9970#$(30+(skillLevel >= 2 and 10 or 0)+(skillLevel >= 4 and 20 or 0))$%#C0x5B545B#概率再次无消耗释放对应技能)',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		buffs = __data_t__buffs[2351],
		-- {850009901}
		conditions = __data_t__conditions[2351],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8023511
	},
	[2361] = {
		id = 2361,
		name = '亚空裂斩',
		awakeDescribes = '额外给1个敌方添加【空间折跃】（优先攻击最高敌方）（【空间折跃】：2级负面，期间获得#C0x5c9970#$(5+(skillLevel >= 3 and 10 or 0))$%#C0x5B545B#水系易伤，水流刃造成伤害的#C0x5c9970#$(30+(skillLevel >= 2 and 20 or 0)+(skillLevel >= 4 and 20 or 0))$%#C0x5B545B#会传递给此目标；在友方单位受到必杀伤害时，自身会被折跃到其位置为其抵挡伤害，触发#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#次后解除）',
		cdRound = 2,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		conditions = __data_t__conditions[2361],
		-- {[1] = 'true', __size = 1}
		skillID = 8023611
	},
	[2381] = {
		id = 2381,
		name = '捏碎',
		awakeDescribes = '释放前先触发【助·板块移动】（优先前排和后排换位），触发后使换位者获得#C0x5c9970#$(20+(skillLevel >= 2 and 10 or 0))$%#C0x5B545B#易伤1回合，且期间无法因血量损失获得怒气（【助·板块移动】：3级控制，令敌方随机#C0x5c9970#$(2+(skillLevel >= 5 and 2 or 0))$#C0x5B545B#个目标互相置换位置，换位者降低#C0x5c9970#$(5+(skillLevel >= 3 and 10 or 0))$%#C0x5B545B#双攻，降低#C0x5c9970#$(3+(skillLevel >= 3 and 6 or 0))$%#C0x5B545B#速度，持续#C0x5c9970#$(1+(skillLevel >= 4 and 1 or 0))$#C0x5B545B#回合）',
		cdRound = 2,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		conditions = __data_t__conditions[2381],
		-- {[1] = 'true', __size = 1}
		skillID = 8023811
	},
	[2391] = {
		id = 2391,
		name = '幽冥鬼火',
		triggerType = 3,
		startRound = 2,
		awakeDescribes = '额外给随机#C0x5c9970#$(2+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#个单位添加【助·鬼盾】（优先鬼系）:特殊护盾，不会衰减，抵挡目标#C0x5c9970#$(8+(skillLevel >= 3 and 8 or 0))$%#C0x5B545B#最大血量的伤害（鬼系为#C0x5c9970#$(12+(skillLevel >= 3 and 12 or 0))$%#C0x5B545B#），破碎时减少攻击者#C0x5c9970#$(20+(skillLevel >= 2 and 40 or 0)+(skillLevel >= 4 and 40 or 0))$#C0x5B545B#点怒气',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		buffs = __data_t__buffs[2391],
		-- {850009901}
		conditions = __data_t__conditions[2391],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8023911
	},
	[2421] = {
		id = 2421,
		name = '沧海之王',
		triggerType = 3,
		awakeDescribes = '为随机#C0x5c9970#$(2+(skillLevel >= 3 and 2 or 0)+(skillLevel >= 5 and 2 or 0)+(skillLevel >= 3 and 1 or 0))$#C0x5B545B#名水系精灵添加【助·水泡泡】，持续1个大回合（【助·水泡泡】：3级增益，立刻移除灼烧类效果，受到的持续性和反伤型伤害降低#C0x5c9970#$(20+(skillLevel >= 4 and 20 or 0))$%#C0x5B545B#，提升#C0x5c9970#$(5+(skillLevel >= 2 and 10 or 0))$%#C0x5B545B#抗暴，降低#C0x5c9970#$(5+(skillLevel >= 2 and 10 or 0))$%#C0x5B545B#受到的暴击伤害）',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[2424] = 8024241, __size = 1},
		buffs = __data_t__buffs[2421],
		-- {850000301}
		conditions = __data_t__conditions[2421],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8024211
	},
	[2431] = {
		id = 2431,
		name = '噩梦梦境',
		awakeDescribes = '令1个敌方（优先双攻最高）进入【助·深度睡眠】1回合，并额外获得1层【噩梦印记】#C0x5c9970#$(1+(skillLevel >= 3 and 1 or 0))$#C0x5B545B#回合 （【助·深度睡眠】：1级控制，陷入深度沉睡无法行动，受击2次或者2次净化/驱散，可以移除该效果；持续期间，目标降低#C0x5c9970#$(5+(skillLevel >= 4 and 10 or 0))$%#C0x5B545B#速度和#C0x5c9970#$(5+(skillLevel >= 2 and 10 or 0))$%#C0x5B545B#伤害，且【噩梦印记】转化为【助·深度睡眠】的概率提升#C0x5c9970#$(10+(skillLevel >= 5 and 20 or 0))$%#C0x5B545B#）',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[2432] = 8024321, __size = 1},
		buffs = {802431111},
		conditions = __data_t__conditions[2431],
		-- {[1] = 'true', __size = 1}
		skillID = 8024311
	},
	[2461] = {
		id = 2461,
		name = 'V热焰',
		triggerType = 3,
		awakeDescribes = '额外释放【助·火种】，与己方攻击最高的火系精灵融合，持续#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#回合 【助·火种】：融合时，令目标立刻恢复#C0x5c9970#$(8+(skillLevel >= 2 and 8 or 0))$%#C0x5B545B#血量，获得比克提尼#C0x5c9970#$(8+(skillLevel >= 3 and 8 or 0))$%#C0x5B545B#基础双攻，提升#C0x5c9970#$(10+(skillLevel >= 4 and 10 or 0))$%#C0x5B545B#暴击率和暴击伤害',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[2463] = 8024621, __size = 1},
		buffs = __data_t__buffs[2461],
		-- {850009901}
		conditions = __data_t__conditions[2461],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8024611
	},
	[2471] = {
		id = 2471,
		name = '荆棘舞',
		triggerType = 3,
		devSkillID = {8024711, 8024721, 8024731},
		buffs = {850000401},
		conditions = __data_t__conditions[2471],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8024711
	},
	[2721] = {
		id = 2721,
		name = '潜藏猎杀',
		triggerType = 3,
		devSkillID = {8027211, 8027221, 8027231},
		buffs = {850000901, 850001601},
		conditions = __data_t__conditions[2721],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8027231
	},
	[3151] = {
		id = 3151,
		name = '虫虫火焰',
		triggerType = 3,
		devSkillID = {8031511, 8031521},
		buffs = {850001201, 850000201},
		conditions = __data_t__conditions[3151],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8031511
	},
	[3351] = {
		id = 3351,
		name = '花海冲击',
		triggerType = 3,
		devSkillID = {8033511, 8033521, 8033531},
		buffs = __data_t__buffs[3351],
		-- {850001801}
		conditions = __data_t__conditions[3351],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8033511
	},
	[3601] = {
		id = 3601,
		name = '生命链接',
		triggerType = 3,
		awakeDescribes = '令队伍中攻击最高的妖/草/地系精灵与其他生命上限的最高的#C0x5c9970#$(2+(skillLevel >= 4 and 1 or 0))$#C0x5B545B#名妖/草/地系精灵以【助·生命链接】相连，持续#C0x5c9970#$(1+(skillLevel >= 3 and 1 or 0))$#C0x5B545B#个大回合（【助·生命链接】：4级增益，链接目标受到伤害时，将50%伤害平摊给其他被链接队友，并提升目标#C0x5c9970#$(5+(skillLevel >= 2 and 5 or 0)+(skillLevel >= 5 and 5 or 0))$%#C0x5B545B#伤害减免）',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[3603] = 8036021, __size = 1},
		buffs = __data_t__buffs[3601],
		-- {850001801}
		conditions = __data_t__conditions[3601],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8036011
	},
	[3611] = {
		id = 3611,
		name = '死亡诅咒',
		triggerType = 3,
		awakeDescribes = '令#C0x5c9970#$(2+(skillLevel >= 4 and 1 or 0))$#C0x5B545B#个随机敌方形成【助·死亡链接】#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#回合 【助·死亡链接】：3级负面，不可叠加，将数个敌方单位链接，其中一个单位所受的主动攻击伤害，会传导#C0x5c9970#$(10+(skillLevel >= 3 and 15 or 0))$%#C0x5B545B#给其他目标（恶系传导伤害翻倍），被链接目标治疗率降低#C0x5c9970#$(15+(skillLevel >= 2 and 15 or 0))$%#C0x5B545B#',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		buffs = {850001601, 850001001},
		conditions = __data_t__conditions[3611],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8036111
	},
	[3651] = {
		id = 3651,
		name = '蒸汽爆炸',
		triggerType = 3,
		awakeDescribes = '对额外给#C0x5c9970#$(1+(skillLevel >= 3 and 1 or 0))$#C0x5B545B#个随机敌方添加【助·蒸汽】2回合并使所有【助·蒸汽】附带【蒸汽爆炸】特性 （【蒸汽爆炸】：敌方所有【助·蒸汽】目标累计被水/火精灵攻击6次后，立刻触发一次蒸汽爆炸，对敌方全体造成波尔凯尼恩20%特攻的火元素伤害，目标身上每有一层【助·蒸汽】，此伤害系数提升10%（冷却#C0x5c9970#$(3+(skillLevel >= 5 and -1 or 0))$#C0x5B545B#回合，全场限#C0x5c9970#$(1+(skillLevel >= 2 and 1 or 0)+(skillLevel >= 4 and 1 or 0))$#C0x5B545B#次））',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		buffs = {850000201, 850000301},
		conditions = __data_t__conditions[3651],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8036511
	},
	[3661] = {
		id = 3661,
		name = '强弓劲弩',
		triggerType = 3,
		devSkillID = {8036611, 8036621, 8036631},
		buffs = __data_t__buffs[3661],
		-- {850009901}
		conditions = __data_t__conditions[3661],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8036631
	},
	[4161] = {
		id = 4161,
		name = '等离子闪电拳',
		triggerType = 3,
		awakeDescribes = '额外给1个电系队友制造1个【助·雷电幻影】#C0x5c9970#$(1+(skillLevel >= 5 and 1 or 0))$#C0x5B545B#回合（优先给攻击最高的） 【助·雷电幻影】：跟随召唤物，继承释放者#C0x5c9970#$(50+(skillLevel >= 2 and 20 or 0)+(skillLevel >= 3 and 10 or 0)+(skillLevel >= 4 and 20 or 0))$%#C0x5B545B#属性，跟随本体对主目标造成幻像#C0x5c9970#$(50+(skillLevel >= 3 and 25 or 0)+(skillLevel >= 4 and 25 or 0))$%#C0x5B545B#物攻的电元素伤害，并有#C0x5c9970#$(30+(skillLevel >= 3 and 20 or 0)+(skillLevel >= 4 and 20 or 0))$%#C0x5B545B#概率替本体抵挡受到的主动攻击及效果（不会替本体抵挡地面系攻击）',
		cdRound = 3,
		timesLimit = '1+(self:flagAS6() and 1 or 0)',
		skin2SkillID = {[4163] = 8041631, [4162] = 8041621, __size = 2},
		buffs = __data_t__buffs[4161],
		-- {850000501}
		conditions = __data_t__conditions[4161],
		-- {[3] = 'moreE(self:getBuffOverlayCount(850000000),1)', __size = 1}
		skillID = 8041611
	},
	__size = 54,
	__default = {
		__index = {
			name = '',
			triggerType = 1,
			startRound = 1,
			awakeDescribes = '',
			cdRound = 0,
			timesLimit = '1',
			devSkillID = __data_t__devSkillID["default"]	--[[ {}]],
			skin2SkillID = __data_t__skin2SkillID["default"]	--[[ {__size = 0}]],
			buffs = __data_t__buffs["default"]	--[[ {}]],
			conditions = {['false'] = 'false', ['true'] = 'true', __size = 2},
			roundTimes = {1, 1},
			keyWords = __data_t__keyWords["default"]	--[[ {__size = 0}]],
			showConfig = {['y'] = 15, ['scale'] = 1.5, ['x'] = 0, __size = 3}
		}
	}
}
return csv.aid.aid_skill