--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, __size = 1}
local __data_t__topBattleHistoryPeriods = {
	["default"] = __predefine_t__[1]
}
local __data_t__aniCardId = {
	["default"] = __predefine_t__[1]
}

csv['cross']['supremacy']['base'] = {
	[1] = {
		id = 1,
		servOpenDays = 1,
		winStreakGradeLimit = 5,
		winStreakCount = 5,
		winStreakScoreAward = 10,
		openWholeMatchBeginGrade = 6,
		formulaValidBeginGrade = 13,
		initWeight = 30,
		deductWeight = 2,
		matchTime = 6,
		robotNumInGrade = 20,
		topBattleRank = 10,
		topBattleRound = 4,
		topBattleLastHP = 0.5,
		aniCardId = {1261, 1271, 1281, 1961, 1971, 1981, 1991, 2351, 2361, 2391, 2431, 2441, 2442, 2461, 3211, 3221, 3241, 3261, 3271, 3601, 3611, 3641, 3642, 4161, 4171, 4172},
		eventBuffNumLimit = 1,
		teamEliteAidNumLimit = 1,
		teamEliteNumLimit = 2,
		topRankNoticeDuration = 284400
	},
	__size = 1,
	__default = {
		__index = {
			winStreakScoreAward = 0,
			topBattleHistoryPeriods = __data_t__topBattleHistoryPeriods["default"]	--[[ {}]],
			topBattleRank = 0,
			topBattleRound = 0,
			topBattleLastHP = 0,
			aniCardId = __data_t__aniCardId["default"]	--[[ {}]],
			eventBuffNumLimit = 0,
			teamEliteAidNumLimit = 0,
			teamEliteNumLimit = 0,
			topRankNoticeDuration = 0
		}
	}
}
return csv.cross.supremacy.base