slot0 = {
	{},
	__size = 52,
	[3] = {
		80,
		120
	},
	[4] = {
		{
			2,
			5,
			0.5
		},
		{
			5,
			8,
			0.2
		},
		{
			8,
			13,
			0.1
		}
	},
	[5] = {
		__size = 1,
		libs = {
			601,
			611,
			621
		}
	},
	[6] = {
		1,
		999
	},
	[7] = {
		19,
		24
	},
	[8] = {
		5,
		10
	},
	[9] = {
		27,
		44
	},
	[10] = {
		60,
		90
	},
	[11] = {
		1
	},
	[12] = {
		{
			2,
			6,
			0.5
		},
		{
			6,
			9,
			0.2
		},
		{
			9,
			14,
			0.1
		}
	},
	[14] = {
		25,
		41
	},
	[15] = {
		20,
		40
	},
	[16] = {
		{
			2,
			7,
			0.5
		},
		{
			7,
			10,
			0.2
		},
		{
			10,
			15,
			0.1
		}
	},
	[17] = {
		15,
		18
	},
	[18] = {
		21,
		34
	},
	[19] = {
		50,
		70
	},
	[20] = {
		__size = 1,
		libs = {
			604,
			614,
			621
		}
	},
	[21] = {
		2,
		999
	},
	[23] = {
		2
	},
	[25] = {
		40,
		60
	},
	[29] = {
		__size = 1,
		libs = {
			607,
			614,
			621
		}
	},
	[30] = {
		3
	},
	[31] = {
		33,
		39
	},
	[32] = {
		37,
		76
	},
	[33] = {
		{
			2,
			8,
			0.5
		},
		{
			8,
			11,
			0.2
		},
		{
			11,
			16,
			0.1
		}
	},
	[34] = {
		3,
		999
	},
	[35] = {
		26,
		31
	},
	[36] = {
		37,
		60
	},
	[39] = {
		__size = 1,
		libs = {
			602,
			612,
			622
		}
	},
	[40] = {
		8,
		12
	},
	[41] = {
		__size = 1,
		libs = {
			605,
			615,
			622
		}
	},
	[44] = {
		33,
		69
	},
	[45] = {
		__size = 1,
		libs = {
			608,
			612,
			622
		}
	},
	[49] = {
		190,
		220
	},
	[50] = {
		__size = 1,
		libs = {
			603,
			613,
			623
		}
	},
	[52] = {
		10,
		15
	},
	[59] = {
		__size = 1,
		libs = {
			606,
			616,
			623
		}
	},
	[64] = {
		__size = 1,
		libs = {
			609,
			613,
			623
		}
	},
	[65] = {
		46,
		54
	},
	[66] = {
		46,
		87
	},
	[67] = {
		__size = 1,
		card = {
			id = 3471,
			__size = 1
		}
	},
	[68] = {
		1,
		2,
		3
	},
	[69] = {
		__size = 1,
		card = {
			id = 541,
			__size = 1
		}
	},
	[70] = {
		__size = 1,
		card = {
			id = 631,
			__size = 1
		}
	},
	[71] = {
		0,
		100
	},
	[72] = {
		0,
		0
	},
	[73] = {
		__size = 1,
		card = {
			id = 1311,
			__size = 1
		}
	},
	[75] = {
		15,
		20
	},
	[80] = {
		2,
		3,
		999
	},
	[81] = {
		20,
		50
	},
	[82] = {
		28,
		46
	}
}
slot1 = {
	slot0[4],
	slot0[4],
	default = slot0[1],
	[3] = slot0[12],
	[5] = slot0[12],
	[4] = slot0[16],
	[7] = slot0[12],
	[6] = slot0[12],
	[9] = slot0[16],
	[8] = slot0[12],
	[201] = slot0[16],
	[205] = slot0[33],
	[204] = slot0[33],
	[206] = slot0[33],
	[102] = slot0[16],
	[103] = slot0[33],
	[106] = slot0[16],
	[107] = slot0[16],
	[104] = slot0[33],
	[105] = slot0[33],
	[11] = slot0[33],
	[10] = slot0[33]
}
slot2 = {
	slot0[7],
	slot0[7],
	[1042] = slot0[7],
	[1201] = slot0[81],
	[1202] = slot0[81],
	default = slot0[1],
	[1111] = slot0[7],
	[4] = slot0[17],
	[9] = slot0[31],
	[1031] = slot0[71],
	[2011] = slot0[72],
	[1011] = slot0[7],
	[1012] = slot0[7],
	[205] = slot0[65],
	[206] = slot0[65],
	[1032] = slot0[71],
	[102] = slot0[31],
	[101] = slot0[35],
	[107] = slot0[31],
	[10] = slot0[35],
	[1041] = slot0[7],
	[1021] = slot0[7],
	[1022] = slot0[7],
	[2010] = slot0[72],
	[2002] = slot0[72],
	[2003] = slot0[72],
	[2001] = slot0[72],
	[1102] = slot0[71],
	[2004] = slot0[72],
	[1101] = slot0[71],
	[2101] = slot0[17],
	[1112] = slot0[7]
}
slot3 = {
	slot0[6],
	slot0[11],
	[1042] = slot0[68],
	[1201] = slot0[80],
	[1202] = slot0[80],
	default = slot0[1],
	[3] = slot0[6],
	[5] = slot0[21],
	[4] = slot0[11],
	[7] = slot0[21],
	[6] = slot0[23],
	[9] = slot0[30],
	[8] = slot0[23],
	[1031] = slot0[68],
	[2011] = slot0[68],
	[1011] = slot0[68],
	[1012] = slot0[68],
	[201] = slot0[6],
	[203] = slot0[21],
	[202] = slot0[11],
	[205] = slot0[30],
	[204] = slot0[23],
	[206] = slot0[34],
	[1032] = slot0[68],
	[102] = slot0[11],
	[103] = slot0[21],
	[101] = slot0[6],
	[106] = slot0[34],
	[107] = slot0[30],
	[104] = slot0[23],
	[105] = slot0[30],
	[11] = slot0[30],
	[10] = slot0[34],
	[1041] = slot0[68],
	[1021] = slot0[68],
	[1022] = slot0[68],
	[2010] = slot0[68],
	[2002] = slot0[68],
	[2003] = slot0[68],
	[2001] = slot0[68],
	[2004] = slot0[68]
}
slot5 = {
	slot0[3],
	slot0[10],
	default = slot0[1],
	[3] = slot0[10],
	[5] = slot0[19],
	[4] = slot0[15],
	[7] = slot0[25],
	[6] = slot0[19],
	[9] = slot0[15],
	[8] = slot0[15],
	[201] = slot0[49],
	[203] = slot0[3],
	[205] = slot0[3],
	[204] = slot0[49],
	[206] = slot0[3],
	[102] = slot0[3],
	[103] = slot0[3],
	[101] = slot0[15],
	[106] = slot0[25],
	[104] = slot0[15],
	[105] = slot0[3],
	[11] = slot0[25],
	[10] = slot0[19]
}
slot6 = {
	slot0[8],
	slot0[8],
	[1042] = slot0[52],
	[1201] = slot0[75],
	[1202] = slot0[75],
	default = slot0[1],
	[9999] = slot0[75],
	[1111] = slot0[75],
	[3] = slot0[8],
	[5] = slot0[8],
	[4] = slot0[8],
	[7] = slot0[8],
	[6] = slot0[8],
	[9] = slot0[8],
	[8] = slot0[8],
	[1031] = slot0[52],
	[2011] = slot0[75],
	[1011] = slot0[52],
	[1012] = slot0[52],
	[201] = slot0[52],
	[203] = slot0[52],
	[202] = slot0[52],
	[205] = slot0[52],
	[204] = slot0[52],
	[206] = slot0[52],
	[1032] = slot0[52],
	[102] = slot0[40],
	[103] = slot0[40],
	[101] = slot0[40],
	[106] = slot0[40],
	[107] = slot0[40],
	[104] = slot0[40],
	[105] = slot0[40],
	[11] = slot0[8],
	[10] = slot0[8],
	[1041] = slot0[52],
	[1021] = slot0[52],
	[1022] = slot0[52],
	[2010] = slot0[75],
	[2002] = slot0[75],
	[2003] = slot0[75],
	[2001] = slot0[75],
	[1102] = slot0[75],
	[2004] = slot0[75],
	[1101] = slot0[75],
	[2101] = slot0[8],
	[1112] = slot0[75]
}
slot7 = {
	slot0[9],
	slot0[9],
	[1042] = slot0[9],
	[1201] = slot0[82],
	[1202] = slot0[82],
	default = slot0[1],
	[1111] = slot0[9],
	[3] = slot0[14],
	[5] = slot0[9],
	[4] = slot0[18],
	[6] = slot0[14],
	[9] = slot0[32],
	[8] = slot0[14],
	[1031] = slot0[72],
	[2011] = slot0[72],
	[1011] = slot0[9],
	[1012] = slot0[9],
	[205] = slot0[66],
	[206] = slot0[66],
	[1032] = slot0[72],
	[102] = slot0[32],
	[103] = slot0[32],
	[101] = slot0[36],
	[106] = slot0[44],
	[107] = slot0[32],
	[104] = slot0[44],
	[105] = slot0[32],
	[11] = slot0[36],
	[10] = slot0[36],
	[1041] = slot0[9],
	[1021] = slot0[9],
	[1022] = slot0[9],
	[2010] = slot0[72],
	[2002] = slot0[72],
	[2003] = slot0[72],
	[2001] = slot0[72],
	[1102] = slot0[72],
	[2004] = slot0[72],
	[1101] = slot0[72],
	[2101] = slot0[18],
	[1112] = slot0[9]
}
slot8 = {
	slot0[5],
	slot0[5],
	[1042] = slot0[73],
	[3] = slot0[5],
	[5] = slot0[20],
	[4] = slot0[5],
	[7] = slot0[20],
	[6] = slot0[20],
	[9] = slot0[29],
	[8] = slot0[20],
	[1031] = slot0[70],
	[1011] = slot0[67],
	[1012] = slot0[67],
	[201] = slot0[50],
	[203] = slot0[59],
	[202] = slot0[50],
	[205] = slot0[64],
	[204] = slot0[59],
	[206] = slot0[64],
	[1032] = slot0[70],
	[102] = slot0[39],
	[103] = slot0[41],
	[101] = slot0[39],
	[106] = slot0[45],
	[107] = slot0[45],
	[104] = slot0[41],
	[105] = slot0[45],
	[11] = slot0[29],
	[10] = slot0[29],
	[1041] = slot0[73],
	[1021] = slot0[69],
	[1022] = slot0[69]
}
csv.fishing.fish = {
	{
		speed = 17,
		name = "Magikarp",
		probability = 0.8,
		name_kr = "잉어킹",
		desc_vn = "Apenas pular será suficiente, extremamente fraco em batalha, mas é o Pokémon mais tenaz que pode viver na água, não importa o quão sujo seja.",
		escape = 13,
		big = 110,
		icon = "config/portrait/jinglingtouxiang/img_129_lyw@.png",
		desc_en = "Just jumping will be enough, extremely weak in battle, but it is the most tenacious Pokémon can live in the water no matter how dirty.",
		rare = 1,
		res = "config/big_hero/standby/img_129_lyw@.png",
		name_th = "Magikarp",
		id = 1,
		scale = 1.4,
		desc_kr = "뛰기만 해도 만족하다. 전투력이 워낙 약하지만 어무리 더러운 물에서 잘 살 수 있는 포켓몬.",
		name_en = "Magikarp",
		desc_th = "แค่วิ่งก็พอใจแล้ว โปเกมอนที่มีพลังต่อสู้ต่ำมาก แต่สามารถอยู่รอดในน้ำสกปรกได้ไม่ว่าจะสกปรกแค่ไหน",
		desc = "Just jumping will be enough, extremely weak in battle, but it is the most tenacious Pokémon can live in the water no matter how dirty.",
		competitionSpeed = 17,
		point = 100,
		crossFishingWeight = 200,
		deadTime = 1,
		competitionEscape = 14,
		name_vn = "Magikarp",
		bookId = 1,
		weight = 60,
		length = slot5[1],
		operateTimePointUp = slot1[1],
		award = slot8[1],
		scene = slot3[1],
		randMove = slot2[1],
		time = slot6[1],
		competitionRandMove = slot7[1]
	},
	{
		name = "Goldeen",
		name_en = "Goldeen",
		name_kr = "콘치",
		desc_th = "ถ้าคุณใส่มันลงในถังน้ำ มันจะชนแก้วที่หนามากด้วยเขาของมัน ทุบมันแล้ววิ่งหนีไป",
		desc = "When putting it into a water tank, even a thick glass can not prevent it to use horn to break and flee.",
		weight = 300,
		probability = 0.8,
		point = 100,
		escape = 13,
		big = 80,
		icon = "config/portrait/jinglingtouxiang/img_118_jjy@.png",
		desc_vn = "Ao colocá-lo em um tanque de água, mesmo um vidro grosso não pode impedi-lo de usar chifre para quebrar e fugir.",
		deadTime = 1,
		speed = 17,
		competitionSpeed = 17,
		competitionEscape = 14,
		desc_en = "When putting it into a water tank, even a thick glass can not prevent it to use horn to break and flee.",
		rare = 1,
		res = "config/big_hero/standby/img_118_jjy@.png",
		name_vn = "Goldeen",
		name_th = "Goldeen",
		id = 2,
		bookId = 1,
		scale = 1.3,
		desc_kr = "물탱크에 넣으면 아주 두꺼운 유리라도 뿔로 부딪혀 부수고 도망한다.",
		length = slot5[2],
		operateTimePointUp = slot1[2],
		award = slot8[2],
		scene = slot3[2],
		randMove = slot2[2],
		time = slot6[2],
		competitionRandMove = slot7[2]
	},
	{
		name_en = "Feebas",
		name_kr = "빈티나",
		name = "Feebas",
		desc_th = "เขาขี้เหร่ เขาจึงได้รับความรักเพียงเล็กน้อย",
		desc = "No one like it because it looks ugly",
		crossFishingWeight = 200,
		probability = 0.8,
		point = 100,
		escape = 12,
		big = 80,
		icon = "config/portrait/jinglingtouxiang/img_349_ccy@.png",
		desc_vn = "Ninguém gosta porque parece feio",
		deadTime = 1,
		speed = 16,
		competitionSpeed = 16,
		competitionEscape = 13,
		desc_en = "No one like it because it looks ugly",
		rare = 1,
		res = "config/big_hero/standby/img_349_ccy@.png",
		name_vn = "Feebas",
		name_th = "Feebas",
		id = 3,
		bookId = 1,
		weight = 300,
		desc_kr = "잘 못 생겼어서 사랑을 거의 받지 못한다.",
		length = slot5[3],
		operateTimePointUp = slot1[3],
		award = slot8[3],
		scene = slot3[3],
		randMove = {
			18,
			23
		},
		time = slot6[3],
		competitionRandMove = slot7[3]
	},
	{
		name_en = "Pyukumuku",
		name_kr = "해무기",
		name = "Pyukumuku",
		desc_th = "แม้ว่ามันจะถูกย้าย มันก็กลับมาที่เดิม ดังนั้นหากไม่มีอาหาร มันก็ยังคงอดตาย",
		desc = "Even if it is moved, it will return to the place, so if there is no food there, it will always be hungry.",
		speed = 13,
		probability = 0.8,
		point = 100,
		escape = 10,
		big = 30,
		icon = "config/portrait/jinglingtouxiang/img_771_qhc@.png",
		desc_vn = "Mesmo que seja movido, ele retornará ao local, portanto, se não houver comida lá, sempre estará com fome.",
		deadTime = 1,
		competitionSpeed = 13,
		competitionEscape = 11,
		desc_en = "Even if it is moved, it will return to the place, so if there is no food there, it will always be hungry.",
		rare = 1,
		res = "config/big_hero/standby/img_771_qhc@.png",
		name_vn = "Pyukumuku",
		name_th = "Pyukumuku",
		id = 4,
		bookId = 1,
		weight = 300,
		desc_kr = "옮겨져도 제자리에 되돌아가기 때문에 거기에 먹이가 없으면 계속 굶다.",
		length = slot5[4],
		operateTimePointUp = slot1[4],
		award = slot8[4],
		scene = slot3[4],
		randMove = slot2[4],
		time = slot6[4],
		competitionRandMove = slot7[4]
	},
	{
		name_en = "Qwilfish",
		name_kr = "침바루",
		name = "Qwilfish",
		desc_th = "ด้านหลังมีหนามแหลมคมมากมาย ไม่มีครีบอื่นนอกจากครีบหาง และหางมีลวดลายเหมือนผี",
		desc = "It has many hard spines on its body. There are no other fins except the tail fin. The pattern on the tail looks like a ghost.",
		crossFishingWeight = 200,
		probability = 0.72,
		point = 120,
		escape = 13,
		big = 65,
		icon = "config/portrait/jinglingtouxiang/img_211_qzy@.png",
		desc_vn = "Tem muitos espinhos duros em seu corpo. Não há outras barbatanas, exceto a barbatana caudal. O padrão na cauda parece um fantasma.",
		deadTime = 1,
		speed = 16,
		competitionSpeed = 16,
		competitionEscape = 14,
		desc_en = "It has many hard spines on its body. There are no other fins except the tail fin. The pattern on the tail looks like a ghost.",
		rare = 1,
		res = "config/big_hero/standby/img_211_qzy@.png",
		name_vn = "Qwilfish",
		name_th = "Qwilfish",
		id = 5,
		bookId = 1,
		weight = 240,
		desc_kr = "등에 단단한 가시가 많이 있다. 꼬리 지느러미 외에 다른 지느러미가 없으며 꼬리에 유령 같은 무늬가 있다.",
		length = slot5[5],
		operateTimePointUp = slot1[5],
		award = slot8[5],
		scene = slot3[5],
		randMove = {
			19,
			36
		},
		time = slot6[5],
		competitionRandMove = slot7[5]
	},
	{
		name_en = "Remoraid",
		name_kr = "총어",
		name = "Remoraid",
		desc_th = "ร่างกายของเขาส่วนใหญ่เป็นสีเทาอ่อน และเขามีตาโตสองข้าง",
		desc = "Its body is mainly light gray with two big eyes. Its fins and tail are white.",
		speed = 15,
		probability = 0.72,
		point = 120,
		escape = 12,
		big = 65,
		icon = "config/portrait/jinglingtouxiang/img_223_tpy@.png",
		desc_vn = "Seu corpo é principalmente cinza claro com dois olhos grandes. Suas barbatanas e cauda são brancas.",
		deadTime = 1,
		competitionSpeed = 15,
		competitionEscape = 13,
		desc_en = "Its body is mainly light gray with two big eyes. Its fins and tail are white.",
		rare = 1,
		res = "config/big_hero/standby/img_223_tpy@.png",
		name_vn = "Remoraid",
		name_th = "Remoraid",
		id = 6,
		bookId = 1,
		weight = 240,
		desc_kr = "그의 몸은 주로 연한 회색이고 큰 두 눈을 가지고 있다.",
		length = slot5[6],
		operateTimePointUp = slot1[6],
		award = slot8[6],
		scene = slot3[6],
		randMove = {
			18,
			34
		},
		time = slot6[6],
		competitionRandMove = slot7[6]
	},
	{
		name_en = "Barboach",
		name_kr = "미꾸리",
		name = "Barboach",
		desc_th = "โลชมีรูปร่างเหมือนกันกับตัวของลอช แต่ลำตัวเป็นสีเทาอ่อนและมีลวดลายหยักสีดำที่ลำตัวทั้งสองด้าน",
		desc = "The shape of the Barboach is similar to mud loach, with a light gray body and a serrated black pattern on both sides.",
		crossFishingWeight = 200,
		probability = 0.72,
		point = 120,
		escape = 11,
		big = 55,
		icon = "config/portrait/jinglingtouxiang/img_339_nnq@.png",
		desc_vn = "A forma do Barboach é semelhante ao lama loach, com um corpo cinza claro e um padrão preto serrilhado em ambos os lados.",
		deadTime = 1,
		speed = 14,
		competitionSpeed = 14,
		competitionEscape = 12,
		desc_en = "The shape of the Barboach is similar to mud loach, with a light gray body and a serrated black pattern on both sides.",
		rare = 1,
		res = "config/big_hero/standby/img_339_nnq@.png",
		name_vn = "Barboach",
		name_th = "Barboach",
		id = 7,
		bookId = 1,
		weight = 240,
		desc_kr = "미꾸리는 미꾸라지의 모습과 같지만 몸은 연한 회색이고 몸 양쪽에 톱니 모양의 검은 무늬가 있다.",
		length = slot5[7],
		operateTimePointUp = slot1[7],
		award = slot8[7],
		scene = slot3[7],
		randMove = {
			17,
			30
		},
		time = slot6[7],
		competitionRandMove = {
			24,
			39
		}
	},
	{
		name_en = "Tynamo",
		name_kr = "저리어",
		name = "Tynamo",
		desc_th = "ปลาตัวเล็กสีขาว. เส้นด้านข้างทั้งสองข้างเป็นสีเหลืองและดูเหมือนคลื่นไฟฟ้าหัวใจ และปากมีรูปร่างเหมือนมีด",
		desc = "A small white fish, its side line is yellow, its shape resembles an electrocardiogram, and its mouth is star-shaped like a ninja knife.",
		speed = 15,
		probability = 0.72,
		point = 120,
		escape = 12,
		big = 35,
		icon = "config/portrait/jinglingtouxiang/img_602_mmxy@.png",
		desc_vn = "Um pequeno peixe branco, sua linha lateral é amarela, sua forma lembra um eletrocardiograma e sua boca é em forma de estrela como uma faca ninja.",
		deadTime = 1,
		competitionSpeed = 15,
		competitionEscape = 13,
		desc_en = "A small white fish, its side line is yellow, its shape resembles an electrocardiogram, and its mouth is star-shaped like a ninja knife.",
		rare = 1,
		res = "config/big_hero/standby/img_602_mmxy@.png",
		name_vn = "Tynamo",
		name_th = "Tynamo",
		id = 8,
		bookId = 1,
		weight = 240,
		desc_kr = "하얗고 작은 물고기. 양옆에 있는 옆줄은 노랗고 심전도과 같으며 입은 인자칼 모양이다.",
		length = slot5[8],
		operateTimePointUp = slot1[8],
		award = slot8[8],
		scene = slot3[8],
		randMove = {
			18,
			33
		},
		time = slot6[8],
		competitionRandMove = slot7[8]
	},
	{
		name_en = "Wishiwashi",
		name_kr = "약어리",
		name = "Wishiwashi",
		desc_th = "ตัวย่อเดี่ยวมีขนาดเล็กมากและอ่อนแอ แต่ตัวย่อของชุมชน... มาต่อกันที่หัวข้อนี้",
		desc = "One Wishiwashi is very small and fragile. As for Wishiwashi in groups, you better run!",
		speed = 13,
		probability = 0.6,
		point = 150,
		escape = 9,
		big = 35,
		icon = "config/portrait/jinglingtouxiang/img_746_rdy@.png",
		desc_vn = "Um Wishiwashi é muito pequeno e frágil. Quanto ao Wishiwashi em grupos, é melhor você correr!",
		competitionSpeed = 13,
		competitionEscape = 10,
		desc_en = "One Wishiwashi is very small and fragile. As for Wishiwashi in groups, you better run!",
		rare = 1,
		res = "config/big_hero/standby/img_746_rdy@.png",
		name_vn = "Wishiwashi",
		name_th = "Wishiwashi",
		id = 9,
		bookId = 1,
		weight = 320,
		desc_kr = "단독의 약어리는 아주 작고 약하다. 하지만 군집의 약어리는...이 화제를 넘어가자.",
		length = slot5[9],
		operateTimePointUp = slot1[9],
		award = slot8[9],
		scene = slot3[9],
		randMove = slot2[9],
		time = slot6[9],
		competitionRandMove = slot7[9]
	},
	{
		name_en = "Chinchou",
		name_kr = "초라기",
		name = "Chinchou",
		desc_th = "พวกเขามักจะอาศัยอยู่ในทะเล แต่ไม่มีใครรู้ว่าทำไมพวกเขาถึงมาปรากฏตัวที่นี่ หนวดมีความสามารถในการเป็นประกาย",
		desc = "Always lived on the bottom of the sea, but don't know why it appears here. The tentacles have a certain light-emitting ability.",
		crossFishingWeight = 200,
		probability = 0.6,
		point = 150,
		escape = 7,
		big = 65,
		icon = "config/portrait/jinglingtouxiang/img_170_dly@.png",
		desc_vn = "Sempre viveu no fundo do mar, mas não sei porque aparece aqui. Os tentáculos têm uma certa capacidade de emissão de luz.",
		speed = 10,
		competitionSpeed = 10,
		competitionEscape = 8,
		desc_en = "Always lived on the bottom of the sea, but don't know why it appears here. The tentacles have a certain light-emitting ability.",
		rare = 1,
		res = "config/big_hero/standby/img_170_dly@.png",
		name_vn = "Chinchou",
		name_th = "Chinchou",
		id = 10,
		bookId = 1,
		weight = 320,
		desc_kr = "항상 바닷속에 사는데 왜 여기서는 나타난지 어무도 모른다. 촉수는 반짝이는 능력이 지니고 있다.",
		length = slot5[10],
		operateTimePointUp = slot1[10],
		award = slot8[10],
		scene = slot3[10],
		randMove = slot2[10],
		time = slot6[10],
		competitionRandMove = slot7[10]
	},
	{
		speed = 10,
		name_kr = "찌로꼬치",
		desc_th = "หากเห็นบางสิ่งเคลื่อนที่ไปรอบๆ มันจะวิ่งตรงไปข้างหน้า การเคลื่อนไหวจะช้ามากหลังจากรับประทานอาหารอิ่ม",
		competitionSpeed = 10,
		desc = "As long as there is any small movement around, it will rush straight through. After it full fed, movement become extremely slow.",
		competitionEscape = 8,
		probability = 0.6,
		point = 150,
		escape = 7,
		big = 55,
		icon = "config/portrait/jinglingtouxiang/img_846_csy@.png",
		desc_vn = "Enquanto houver um pequeno movimento ao redor, ele passará direto. Depois de totalmente alimentado, o movimento se torna extremamente lento.",
		deadTime = 2,
		desc_en = "As long as there is any small movement around, it will rush straight through. After it full fed, movement become extremely slow.",
		rare = 1,
		res = "config/big_hero/standby/img_846_csy@.png",
		id = 11,
		bookId = 1,
		weight = 320,
		desc_kr = "주변에 뭔가 움찔거리는 것을 발견하면 곧장 일직선으로 돌진한다. 배불리 먹은 후 동작이 극도로 느려진다.",
		length = slot5[11],
		operateTimePointUp = slot1[11],
		award = slot8[11],
		scene = slot3[11],
		randMove = {
			46,
			82
		},
		time = slot6[11],
		competitionRandMove = slot7[11]
	},
	__size = 46,
	[101] = {
		name_en = "Shellos",
		name_kr = "깝질무",
		name = "Shellos",
		desc_th = "โปรดทราบว่าการกดลงบนร่างกายที่อ่อนนุ่มของเขาจะปล่อยของเหลวสีม่วงลึกลับออกมา",
		desc = "If pressing its soft body too hard, a mysterious purple liquid will leak out, so please be careful.",
		crossFishingWeight = 118,
		probability = 0.7,
		point = 300,
		escape = 7,
		big = 30,
		icon = "config/portrait/jinglingtouxiang/img_422_wkht@.png",
		desc_vn = "Se pressionar seu corpo macio com muita força, um misterioso líquido roxo vazará, então tenha cuidado.",
		speed = 9,
		competitionSpeed = 9,
		competitionEscape = 8,
		desc_en = "If pressing its soft body too hard, a mysterious purple liquid will leak out, so please be careful.",
		rare = 2,
		res = "config/big_hero/standby/img_422_wkht@.png",
		name_vn = "Shellos",
		name_th = "Shellos",
		id = 101,
		bookId = 1,
		weight = 120,
		desc_kr = "그의 부드러운 몸을 꾹 누르면 신비한 보라색 액체가 나오는 점에 주의하라.",
		length = slot5[101],
		operateTimePointUp = {
			{
				2,
				9,
				0.5
			},
			{
				9,
				12,
				0.2
			},
			{
				12,
				17,
				0.1
			}
		},
		award = slot8[101],
		scene = slot3[101],
		randMove = slot2[101],
		time = slot6[101],
		competitionRandMove = slot7[101]
	},
	[102] = {
		name_en = "Mantyke",
		name_kr = "타만타",
		name = "Mantyke",
		desc_th = "มีลายหน้ายิ้มที่หลังคล้ายตาสีขาว ตาสีแดง และริมฝีปากสีฟ้าซีด",
		desc = "It has a smile-like pattern on its back, which seems to have white eyes, red eyeballs, and light blue mouth.",
		speed = 12,
		probability = 0.7,
		point = 300,
		escape = 9,
		big = 110,
		icon = "config/portrait/jinglingtouxiang/img_458_xqfy@.png",
		desc_vn = "Tem um padrão de sorriso nas costas, que parece ter olhos brancos, globos oculares vermelhos e boca azul clara.",
		competitionSpeed = 12,
		competitionEscape = 10,
		desc_en = "It has a smile-like pattern on its back, which seems to have white eyes, red eyeballs, and light blue mouth.",
		rare = 2,
		res = "config/big_hero/standby/img_458_xqfy@.png",
		name_vn = "Mantyke",
		name_th = "Mantyke",
		id = 102,
		bookId = 1,
		weight = 120,
		desc_kr = "등에는 하얀 눈, 붉은 눈동자, 옅은 파란 입술이 있는 듯한 웃는 얼굴 무늬가 있다.",
		length = slot5[102],
		operateTimePointUp = slot1[102],
		award = slot8[102],
		scene = slot3[102],
		randMove = slot2[102],
		time = slot6[102],
		competitionRandMove = slot7[102]
	},
	[103] = {
		name_en = "Basculin",
		name_kr = "배쓰나이",
		name = "Basculin",
		desc_th = "ลำตัวของ Bassnai เป็นสีเขียวเข้ม และมีจุดสีดำสามจุดถัดจากครีบอก และลายแท็บบี้สีดำบนหัวยื่นออกมาจากครีบหาง",
		desc = "The body of Basculin is dark green, with three black spots beside the pectoral fin, and a black marking on the head that extends to the caudal fin.",
		crossFishingWeight = 118,
		probability = 0.63,
		point = 300,
		escape = 9,
		big = 110,
		icon = "config/portrait/jinglingtouxiang/img_550_ymly@.png",
		desc_vn = "O corpo de Basculin é verde escuro, com três manchas pretas ao lado da barbatana peitoral e uma marca preta na cabeça que se estende até a barbatana caudal.",
		speed = 11,
		competitionSpeed = 11,
		competitionEscape = 10,
		desc_en = "The body of Basculin is dark green, with three black spots beside the pectoral fin, and a black marking on the head that extends to the caudal fin.",
		rare = 2,
		res = "config/big_hero/standby/img_550_ymly@.png",
		name_vn = "Basculin",
		name_th = "Basculin",
		id = 103,
		bookId = 1,
		weight = 120,
		desc_kr = "배쓰나이의 몸은 짙은 녹색이며 가슴 지느러미 옆에 검은 점 3개 있고 머리에는 검은 얼룩무늬가 꼬리 지느러미로 뻗어 있다.",
		length = slot5[103],
		operateTimePointUp = slot1[103],
		award = slot8[103],
		scene = slot3[103],
		randMove = {
			33,
			60
		},
		time = slot6[103],
		competitionRandMove = slot7[103]
	},
	[104] = {
		name_en = "Dewpider",
		name_kr = "물거미",
		name = "Dewpider",
		desc_th = "หัวถูกปกคลุมด้วยแผลพุพองซึ่งล้อมรอบด้วยเนื้อเยื่อสีเหลืองเขียวสามชิ้น ดวงตามีแถบสีน้ำเงินและสีฟ้าอ่อน ปากมีสีเหลืองอมเขียว และมีตุ่มสีน้ำเงินสองจุดบนหัว",
		desc = "Its head is surrounded by blisters, and the blisters are surrounded by three yellow-green tissues. The eyes are blue with light blue stripes. The mouth is yellow-green, and there are two blue protrusions on the top of the head.",
		speed = 10,
		probability = 0.63,
		point = 300,
		escape = 8,
		big = 30,
		icon = "config/portrait/jinglingtouxiang/img_751_dz@.png",
		desc_vn = "Sua cabeça é cercada por bolhas e as bolhas são cercadas por três tecidos verde-amarelados. Os olhos são azuis com listras azuis claras. A boca é verde-amarelada e há duas saliências azuis no topo da cabeça.",
		competitionSpeed = 10,
		competitionEscape = 9,
		desc_en = "Its head is surrounded by blisters, and the blisters are surrounded by three yellow-green tissues. The eyes are blue with light blue stripes. The mouth is yellow-green, and there are two blue protrusions on the top of the head.",
		rare = 2,
		res = "config/big_hero/standby/img_751_dz@.png",
		name_vn = "Dewpider",
		name_th = "Dewpider",
		id = 104,
		bookId = 1,
		weight = 120,
		desc_kr = "머리는 물집으로 뒤덮여 있으며, 물집은 황록색 세 조직에 둘러싸여 있다. 눈은 파란색, 연청색 줄무늬가 있다. 입은 황록색이며 머리에는 두 개의 푸른색 돌기가 있다.",
		length = slot5[104],
		operateTimePointUp = slot1[104],
		award = slot8[104],
		scene = slot3[104],
		randMove = {
			30,
			48
		},
		time = slot6[104],
		competitionRandMove = slot7[104]
	},
	[105] = {
		name_en = "Starmie",
		name_kr = "아쿠스타",
		name = "Starmie",
		desc_th = "ส่วนที่เรียกว่าแกนกลางลำตัวเปล่งแสงเจ็ดดวงจึงได้รับฉายาว่าเป็นอัญมณีแห่งท้องทะเล",
		desc = "Because the part called the core in the middle of the body emits colorful rays, it is called the gem of the sea.",
		speed = 10,
		probability = 0.56,
		point = 300,
		escape = 9,
		big = 115,
		icon = "config/portrait/jinglingtouxiang/img_121_bshx@.png",
		desc_vn = "Porque a parte chamada de núcleo no meio do corpo emite raios coloridos, é chamada de gema do mar.",
		competitionSpeed = 10,
		competitionEscape = 10,
		desc_en = "Because the part called the core in the middle of the body emits colorful rays, it is called the gem of the sea.",
		rare = 2,
		res = "config/big_hero/standby/img_121_bshx@.png",
		name_vn = "Starmie",
		name_th = "Starmie",
		id = 105,
		bookId = 1,
		weight = 80,
		desc_kr = "몸 가운데 있는 핵심이라 불리는 부분은 일곱 빛이 나기 때문에 바다의 보석이라는 별명이 있다.",
		length = slot5[105],
		operateTimePointUp = slot1[105],
		award = slot8[105],
		scene = slot3[105],
		randMove = {
			33,
			70
		},
		time = slot6[105],
		competitionRandMove = slot7[105]
	},
	[106] = {
		name_en = "Horsea",
		name_kr = "쏘드라",
		name = "Horsea",
		desc_th = "พวกมันสามารถเคลื่อนที่ได้อย่างรวดเร็วด้วยครีบหลังและเคลื่อนที่ไปในทุกทิศทางโดยมองไปข้างหน้า เมื่อสัมผัสได้ถึงอันตราย มันจะพ่นหมึกและวิ่งหนีไป",
		desc = "Can move swiftly by using the dorsal fin on the back, facing forward and moving in all directions. Once it detects danger, it will spit out ink and escape.",
		crossFishingWeight = 118,
		probability = 0.5,
		point = 300,
		escape = 8,
		big = 55,
		icon = "config/portrait/jinglingtouxiang/img_116_mhm@.png",
		desc_vn = "Pode mover-se rapidamente usando a barbatana dorsal nas costas, virada para a frente e movendo-se em todas as direções. Uma vez que detecta o perigo, ele cuspirá tinta e escapará.",
		speed = 12,
		competitionSpeed = 12,
		competitionEscape = 9,
		desc_en = "Can move swiftly by using the dorsal fin on the back, facing forward and moving in all directions. Once it detects danger, it will spit out ink and escape.",
		rare = 2,
		res = "config/big_hero/standby/img_116_mhm@.png",
		name_vn = "Horsea",
		name_th = "Horsea",
		id = 106,
		bookId = 1,
		weight = 80,
		desc_kr = "등지느러미로 빠르게 움직일 수 있고 앞을 보고 사방팔방으로 이동한다. 위험을 감지하면 먹물을 분출하여 도망을 치다.",
		length = slot5[106],
		operateTimePointUp = slot1[106],
		award = slot8[106],
		scene = slot3[106],
		randMove = {
			30,
			36
		},
		time = slot6[106],
		competitionRandMove = slot7[106]
	},
	[107] = {
		name_en = "Lumineon",
		name_kr = "네오라이트",
		name = "Lumineon",
		desc_th = "เมื่อมีรุ้งปรากฏ ร่างกายของเขาก็กลมกลืนกับรุ้งกินน้ำและจุดประกายให้ท้องทะเลสวยงาม",
		desc = "When rainbow appears, it will use its body to reflect rainbow, and it often decorates the sea very beautifully.",
		speed = 13,
		probability = 0.5,
		point = 300,
		escape = 9,
		big = 125,
		icon = "config/portrait/jinglingtouxiang/img_457_nhy@.png",
		desc_vn = "Quando o arco-íris aparece, ele usa seu corpo para refletir o arco-íris e muitas vezes decora o mar de maneira muito bonita.",
		competitionSpeed = 13,
		competitionEscape = 10,
		desc_en = "When rainbow appears, it will use its body to reflect rainbow, and it often decorates the sea very beautifully.",
		rare = 2,
		res = "config/big_hero/standby/img_457_nhy@.png",
		name_vn = "Lumineon",
		name_th = "Lumineon",
		id = 107,
		bookId = 1,
		weight = 80,
		desc_kr = "무지개가 나타날 때는 그의 몸으로 무지개와 어울려 비추어 바다를 아름답게 꾸미곤 한다.",
		length = {
			110,
			130
		},
		operateTimePointUp = slot1[107],
		award = slot8[107],
		scene = slot3[107],
		randMove = slot2[107],
		time = slot6[107],
		competitionRandMove = slot7[107]
	},
	[201] = {
		name_en = "Wailmer",
		name_kr = "고래왕자",
		name = "Wailmer",
		desc_th = "แม้ว่าจะเป็นโปเกมอนที่ปกติจะอาศัยอยู่ในทะเล แต่ก็สามารถเปิดใช้งานบนบกได้ในช่วงเวลาสั้นๆ เมื่อร่างกายของคุณแห้ง คุณจะสูญเสียพลังงาน",
		desc = "Although it usually live in the sea, it can live on land for a short time. If its body is dry, it will become very weak.",
		crossFishingWeight = 100,
		probability = 0.6,
		point = 1000,
		escape = 9,
		big = 215,
		icon = "config/portrait/jinglingtouxiang/img_320_hhj@.png",
		desc_vn = "Embora geralmente viva no mar, pode viver em terra por um curto período de tempo. Se seu corpo estiver seco, ficará muito fraco.",
		speed = 12,
		competitionSpeed = 12,
		competitionEscape = 10,
		desc_en = "Although it usually live in the sea, it can live on land for a short time. If its body is dry, it will become very weak.",
		rare = 3,
		res = "config/big_hero/standby/img_320_hhj@.png",
		name_vn = "Wailmer",
		name_th = "Wailmer",
		id = 201,
		bookId = 1,
		weight = 30,
		desc_kr = "평소 바닷속에 사는 포켓몬이지만 짧은 시간이라면 육지에서 활동할 수 있다. 몸이 건조하면 기운이 없어진다.",
		length = slot5[201],
		operateTimePointUp = slot1[201],
		award = slot8[201],
		scene = slot3[201],
		randMove = {
			57,
			67
		},
		time = slot6[201],
		competitionRandMove = {
			42,
			82
		}
	},
	[202] = {
		name_en = "Relicanth",
		name_kr = "시라칸",
		name = "Relicanth",
		desc_th = "รูปลักษณ์ของมันไม่ได้เปลี่ยนไปมากนักเป็นเวลา 100 ล้านปี ดังนั้นจึงเป็นฟอสซิลของโปเกมอนที่มีชีวิต ส่วนใหญ่กินจุลินทรีย์",
		desc = "Its appearance has not changed much in 100 million years. It is a living fossil among Pokémons, mainly eating microorganisms.",
		speed = 7,
		probability = 0.6,
		point = 1000,
		escape = 5,
		big = 105,
		icon = "config/portrait/jinglingtouxiang/img_369_gkjy@.png",
		desc_vn = "Sua aparência não mudou muito em 100 milhões de anos. É um fóssil vivo entre os Pokémons, principalmente comendo microorganismos.",
		competitionSpeed = 7,
		competitionEscape = 6,
		desc_en = "Its appearance has not changed much in 100 million years. It is a living fossil among Pokémons, mainly eating microorganisms.",
		rare = 3,
		res = "config/big_hero/standby/img_369_gkjy@.png",
		name_vn = "Relicanth",
		name_th = "Relicanth",
		id = 202,
		bookId = 1,
		weight = 30,
		desc_kr = "1억 년 동안 외형은 크게 변하지 않으니 포켓몬의 살아있는 화석이다. 미생물을 주로 먹는다.",
		length = {
			90,
			110
		},
		operateTimePointUp = {
			{
				2,
				11,
				0.5
			},
			{
				11,
				14,
				0.2
			},
			{
				14,
				19,
				0.1
			}
		},
		award = slot8[202],
		scene = slot3[202],
		randMove = {
			32,
			37
		},
		time = slot6[202],
		competitionRandMove = {
			46,
			74
		}
	},
	[203] = {
		name_en = "Whiscash",
		name_kr = "메깅",
		name = "Whiscash",
		desc_th = "ทำให้เกิดแผ่นดินไหวในบริเวณใกล้เคียง 5 กม. และในขณะเดียวกันก็มีพลังลึกลับในการทำนายแผ่นดินไหวที่เกิดขึ้นจริง",
		desc = "It can cause earthquakes within 5km of the surrounding area, and it also has the magical power to predict the real earthquake.",
		crossFishingWeight = 100,
		probability = 0.54,
		point = 1000,
		escape = 7,
		big = 110,
		icon = "config/portrait/jinglingtouxiang/img_340_nyw@.png",
		desc_vn = "Pode causar terremotos dentro de 5 km da área circundante, e também tem o poder mágico de prever o terremoto real.",
		speed = 8,
		competitionSpeed = 8,
		competitionEscape = 8,
		desc_en = "It can cause earthquakes within 5km of the surrounding area, and it also has the magical power to predict the real earthquake.",
		rare = 3,
		res = "config/big_hero/standby/img_340_nyw@.png",
		name_vn = "Whiscash",
		name_th = "Whiscash",
		id = 203,
		bookId = 1,
		weight = 30,
		desc_kr = "5km 근방의 지진을 유발하는 동시에 실제 지진을 예측할 수 있는 신기한 힘을 갖고 있다.",
		length = slot5[203],
		operateTimePointUp = {
			{
				2,
				10,
				0.5
			},
			{
				10,
				13,
				0.2
			},
			{
				13,
				18,
				0.1
			}
		},
		award = slot8[203],
		scene = slot3[203],
		randMove = {
			43,
			75
		},
		time = slot6[203],
		competitionRandMove = {
			41,
			80
		}
	},
	[204] = {
		speed = 11,
		name_kr = "어치르돈",
		desc_th = "มันส่งอากาศเย็นออกไปเพื่อแช่แข็งบริเวณโดยรอบเพื่อจับเหยื่อ และผิวบนใบหน้าของมันจะไม่ได้รับอันตรายจากการโจมตีใดๆ",
		competitionSpeed = 11,
		desc = "It will freeze the surroundings to catch prey by releasing cold air, and the skin of its face will not be injured no matter what attack it receives.",
		competitionEscape = 10,
		probability = 0.54,
		point = 1000,
		escape = 9,
		big = 215,
		icon = "config/portrait/jinglingtouxiang/img_883_syhs@.png",
		desc_vn = "Ele congelará os arredores para capturar presas liberando ar frio, e a pele de seu rosto não será ferida, não importa o ataque que receba.",
		desc_en = "It will freeze the surroundings to catch prey by releasing cold air, and the skin of its face will not be injured no matter what attack it receives.",
		rare = 3,
		res = "config/big_hero/standby/img_883_syhs@.png",
		id = 204,
		bookId = 1,
		weight = 30,
		desc_kr = "냉기를 내보내 주위를 얼려서 사냥감을 포획하며 얼굴의 피부는 어떤 공격을 받더라도 다치지 않는다.",
		length = slot5[204],
		operateTimePointUp = slot1[204],
		award = slot8[204],
		scene = slot3[204],
		randMove = {
			54,
			80
		},
		time = slot6[204],
		competitionRandMove = {
			47,
			85
		}
	},
	[205] = {
		name_en = "Tentacool",
		name_kr = "왕눈해",
		name = "Tentacool",
		desc_th = "น้ำภายในร่างกายหักเหแสงแดด เปลี่ยนเป็นพลังงานลำแสง และยิงออกจากดวงตาที่เหมือนคริสตัล",
		desc = "The water in the body refracts sunlight and converts it into beam energy. Emitted from the eyes that looked like crystals.",
		speed = 10,
		probability = 0.5,
		point = 1000,
		escape = 8,
		big = 110,
		icon = "config/portrait/jinglingtouxiang/img_72_mnsm@.png",
		desc_vn = "A água no corpo refrata a luz solar e a converte em energia de feixe. Emitido dos olhos que pareciam cristais.",
		competitionSpeed = 10,
		competitionEscape = 9,
		desc_en = "The water in the body refracts sunlight and converts it into beam energy. Emitted from the eyes that looked like crystals.",
		rare = 3,
		res = "config/big_hero/standby/img_72_mnsm@.png",
		name_vn = "Tentacool",
		name_th = "Tentacool",
		id = 205,
		bookId = 1,
		weight = 30,
		desc_kr = "몸 안의 물로 태양빛을 굴절시켜 빔의 에너지로 전환해 수정처럼 보이는 눈에서 발사한다.",
		length = slot5[205],
		operateTimePointUp = slot1[205],
		award = slot8[205],
		scene = slot3[205],
		randMove = slot2[205],
		time = slot6[205],
		competitionRandMove = slot7[205]
	},
	[206] = {
		name_en = "Octillery",
		name_kr = "대포무노",
		name = "Octillery",
		desc_th = "มีนิสัยชอบเจาะรู มันขโมยรังของคนอื่นและนอนอยู่ในนั้น",
		desc = "Has the habit of drilling holes. Will snatch other Pokémon's lair and sleep in it.",
		crossFishingWeight = 100,
		probability = 0.5,
		point = 1000,
		escape = 8,
		big = 110,
		icon = "config/portrait/jinglingtouxiang/img_224_zyt@.png",
		desc_vn = "Tem o hábito de fazer furos. Vai pegar o covil de outros Pokémon e dormir nele.",
		speed = 10,
		competitionSpeed = 10,
		competitionEscape = 9,
		desc_en = "Has the habit of drilling holes. Will snatch other Pokémon's lair and sleep in it.",
		rare = 3,
		res = "config/big_hero/standby/img_224_zyt@.png",
		name_vn = "Octillery",
		name_th = "Octillery",
		id = 206,
		bookId = 1,
		weight = 30,
		desc_kr = "구멍 뚫는 습성이 있다. 남의 둥지를 빼앗아 그 안에서 잔다.",
		length = slot5[206],
		operateTimePointUp = slot1[206],
		award = slot8[206],
		scene = slot3[206],
		randMove = slot2[206],
		time = slot6[206],
		competitionRandMove = slot7[206]
	},
	[1011] = {
		showType = "spine",
		name = "Clauncher",
		weightMax = 0.0123,
		name_kr = "완철포",
		desc_vn = "A água comprimida de enormes pinças pode disparar como uma bala e abater presas em voo",
		randType = 2,
		type = 2,
		overDeal = 3,
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/speedranktouxiang/img_692_tbqx@.png",
		weightMin = 0.001,
		priority = 1,
		desc_en = "Water compressed from huge pincers can shoot out like a bullet and shoot down prey in flight",
		rare = 2,
		speed = 11,
		res = "koudai_tiebiqiangxia/hero_tiebiqiangxia.skel",
		name_th = "Clauncher",
		id = 1011,
		scale = 3.2,
		desc_kr = "커다란 집게발로 압축한 물을 총알처럼 쏘아, 날고 있는 사냥감을 떨어뜨린다.",
		name_en = "Clauncher",
		desc_th = "มันยิงน้ำอัดเหมือนกระสุนด้วยกรงเล็บขนาดใหญ่ ปล่อยเหยื่อให้บิน",
		desc = "Water compressed from huge pincers can shoot out like a bullet and shoot down prey in flight",
		probability = 0.7,
		point = 100,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 3,
		name_vn = "Clauncher",
		weight = -1,
		maxWinTimes = 1,
		award = slot8[1011],
		scene = slot3[1011],
		randMove = slot2[1011],
		time = slot6[1011],
		competitionRandMove = slot7[1011]
	},
	[1012] = {
		showType = "spine",
		name = "Clauncher",
		weightMax = 0.0066,
		name_kr = "완철포",
		desc_vn = "A água comprimida de enormes pinças pode disparar como uma bala e abater presas em voo",
		randType = 2,
		type = 2,
		name_th = "Clauncher",
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/speedranktouxiang/img_692_tbqx@.png",
		weightMin = 0.02,
		priority = 1,
		desc_en = "Water compressed from huge pincers can shoot out like a bullet and shoot down prey in flight",
		rare = 2,
		speed = 11,
		res = "koudai_tiebiqiangxia/hero_tiebiqiangxia.skel",
		overDeal = 3,
		id = 1012,
		scale = 3.2,
		desc_kr = "커다란 집게발로 압축한 물을 총알처럼 쏘아, 날고 있는 사냥감을 떨어뜨린다.",
		name_en = "Clauncher",
		desc_th = "มันยิงน้ำอัดเหมือนกระสุนด้วยกรงเล็บขนาดใหญ่ ปล่อยเหยื่อให้บิน",
		desc = "Water compressed from huge pincers can shoot out like a bullet and shoot down prey in flight",
		probability = 0.7,
		point = 100,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 2,
		name_vn = "Clauncher",
		weight = -1,
		award = slot8[1012],
		scene = slot3[1012],
		randMove = slot2[1012],
		time = slot6[1012],
		competitionRandMove = slot7[1012]
	},
	[1021] = {
		showType = "spine",
		name = "Rare Goldeen",
		weightMax = 0.19,
		name_kr = "드문 콘치",
		desc_vn = "Ao colocá-lo em um tanque de água, mesmo um vidro grosso não pode impedi-lo de usar chifre para quebrar e fugir.",
		randType = 2,
		type = 2,
		overDeal = 3,
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/jinglingtouxiang/img_118_jjy@.png",
		weightMin = 0.01,
		priority = 1,
		desc_en = "When putting it into a water tank, even a thick glass can not prevent it to use horn to break and flee.",
		rare = 1,
		speed = 11,
		res = "koudai_jiaojinyu/hero_jiaojinyu.skel",
		name_th = "Rare Goldeen",
		id = 1021,
		scale = 3.2,
		desc_kr = "물탱크에 넣으면 아주 두꺼운 유리라도 뿔로 부딪혀 부수고 도망한다.",
		name_en = "Rare Goldeen",
		desc_th = "หากคุณใส่ไว้ในถังเก็บน้ำ แก้วที่หนามากก็จะชนและวิ่งหนีไปพร้อมกับเขาของมัน",
		desc = "When putting it into a water tank, even a thick glass can not prevent it to use horn to break and flee.",
		probability = 0.7,
		point = 300,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 3,
		name_vn = "Rare Goldeen",
		weight = -1,
		maxWinTimes = 1,
		award = slot8[1021],
		scene = slot3[1021],
		randMove = slot2[1021],
		time = slot6[1021],
		competitionRandMove = slot7[1021]
	},
	[1022] = {
		showType = "spine",
		name = "Rare Goldeen",
		weightMax = 0.019,
		name_kr = "드문 콘치",
		desc_vn = "Ao colocá-lo em um tanque de água, mesmo um vidro grosso não pode impedi-lo de usar chifre para quebrar e fugir.",
		randType = 2,
		type = 2,
		name_th = "Rare Goldeen",
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/jinglingtouxiang/img_118_jjy@.png",
		weightMin = 0.001,
		priority = 1,
		desc_en = "When putting it into a water tank, even a thick glass can not prevent it to use horn to break and flee.",
		rare = 1,
		speed = 11,
		res = "koudai_jiaojinyu/hero_jiaojinyu.skel",
		overDeal = 3,
		id = 1022,
		scale = 3.2,
		desc_kr = "물탱크에 넣으면 아주 두꺼운 유리라도 뿔로 부딪혀 부수고 도망한다.",
		name_en = "Rare Goldeen",
		desc_th = "หากคุณใส่ไว้ในถังเก็บน้ำ แก้วที่หนามากก็จะชนและวิ่งหนีไปพร้อมกับเขาของมัน",
		desc = "When putting it into a water tank, even a thick glass can not prevent it to use horn to break and flee.",
		probability = 0.7,
		point = 300,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 2,
		name_vn = "Rare Goldeen",
		weight = -1,
		award = slot8[1022],
		scene = slot3[1022],
		randMove = slot2[1022],
		time = slot6[1022],
		competitionRandMove = slot7[1022]
	},
	[1031] = {
		showType = "spine",
		name = "Gyarados",
		weightMax = 0.01,
		name_kr = "갸라도스",
		desc_vn = "Parece ter uma baixa chance de pegar Pokémon no gancho",
		randType = 2,
		type = 2,
		overDeal = 3,
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/jinglingtouxiang/img_130_bll@.png",
		weightMin = 0.00333,
		priority = 3,
		desc_en = "It seems like to have a low chance to get Pokémon on hook",
		rare = 3,
		speed = 11,
		res = "koudai_baolilong/hero_baolilong.skel",
		name_th = "Gyarados",
		id = 1031,
		scale = 3.2,
		desc_kr = "극도로 낮은 확률로 포켓몬을 낚을 수 있다.",
		name_en = "Gyarados",
		desc_th = "มีโอกาสน้อยมากที่จะจับโปเกมอน",
		desc = "It seems like to have a low chance to get Pokémon on hook",
		probability = 0.7,
		point = 1000,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 2,
		name_vn = "Gyarados",
		weight = -1,
		maxWinTimes = 1,
		award = slot8[1031],
		scene = slot3[1031],
		randMove = slot2[1031],
		time = slot6[1031],
		competitionRandMove = slot7[1031]
	},
	[1032] = {
		showType = "spine",
		name = "Gyarados",
		weightMax = 0.0035,
		name_kr = "갸라도스",
		desc_vn = "Parece ter uma baixa chance de pegar Pokémon no gancho",
		randType = 2,
		type = 2,
		name_th = "Gyarados",
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/jinglingtouxiang/img_130_bll@.png",
		weightMin = 0.0005,
		priority = 3,
		desc_en = "It seems like to have a low chance to get Pokémon on hook",
		rare = 3,
		speed = 11,
		res = "koudai_baolilong/hero_baolilong.skel",
		overDeal = 3,
		id = 1032,
		scale = 3.2,
		desc_kr = "극도로 낮은 확률로 포켓몬을 낚을 수 있다.",
		name_en = "Gyarados",
		desc_th = "มีโอกาสน้อยมากที่จะจับโปเกมอน",
		desc = "It seems like to have a low chance to get Pokémon on hook",
		probability = 0.7,
		point = 1000,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 1,
		name_vn = "Gyarados",
		weight = -1,
		award = slot8[1032],
		scene = slot3[1032],
		randMove = slot2[1032],
		time = slot6[1032],
		competitionRandMove = slot7[1032]
	},
	[1041] = {
		showType = "spine",
		name = "Mudkip",
		weightMax = 0.006,
		name_kr = "물짱이",
		desc_vn = "Contando com as bochechas para respirar na água, a força que ele exerce na angústia é suficiente para esmagar uma pedra maior do que ele. A barbatana na cabeça funciona como um radar e pode distinguir as condições circundantes",
		randType = 2,
		type = 2,
		overDeal = 3,
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/jinglingtouxiang/img_258_syy@.png",
		weightMin = 0.002,
		priority = 3,
		desc_en = "Relying on the cheeks to breathe in the water, the force he exerts in distress is enough to crush a rock larger than himself. The fin on its head acts as a radar and can distinguish the surrounding conditions",
		rare = 3,
		speed = 11,
		res = "koudai_shuiyueyu/hero_shuiyueyu.skel",
		name_th = "Mudkip",
		id = 1041,
		scale = 3.2,
		desc_kr = "물속에서 뺨의 아가미로 호흡을 하고고 조난을 당했을 때 발휘하는 힘은 자신보다 큰 바위를 분쇄하기도 한다. 머리 위의 지느러미는 레이더같은 역할을 하여 주위 상황을 판별할 수 있다.",
		name_en = "Mudkip",
		desc_th = "มันหายใจด้วยเหงือกของพวกมันในน้ำ และพลังที่มันออกแรงเมื่ออยู่ในความทุกข์บางครั้งก็ทำให้หินก้อนใหญ่ทับตัวมันเอง ครีบบนศีรษะสามารถทำหน้าที่เหมือนเรดาร์เพื่อระบุสถานการณ์โดยรอบ",
		desc = "Relying on the cheeks to breathe in the water, the force he exerts in distress is enough to crush a rock larger than himself. The fin on its head acts as a radar and can distinguish the surrounding conditions",
		probability = 0.7,
		point = 1000,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 2,
		name_vn = "Mudkip",
		weight = -1,
		maxWinTimes = 1,
		award = slot8[1041],
		scene = slot3[1041],
		randMove = slot2[1041],
		time = slot6[1041],
		competitionRandMove = slot7[1041]
	},
	[1042] = {
		showType = "spine",
		name = "Mudkip",
		weightMax = 0.0028,
		name_kr = "물짱이",
		desc_vn = "Contando com as bochechas para respirar na água, a força que ele exerce na angústia é suficiente para esmagar uma pedra maior do que ele. A barbatana na cabeça funciona como um radar e pode distinguir as condições circundantes",
		randType = 2,
		type = 2,
		name_th = "Mudkip",
		competitionSpeed = 11,
		escape = 5,
		icon = "config/portrait/jinglingtouxiang/img_258_syy@.png",
		weightMin = 0.0004,
		priority = 3,
		desc_en = "Relying on the cheeks to breathe in the water, the force he exerts in distress is enough to crush a rock larger than himself. The fin on its head acts as a radar and can distinguish the surrounding conditions",
		rare = 3,
		speed = 11,
		res = "koudai_shuiyueyu/hero_shuiyueyu.skel",
		overDeal = 3,
		id = 1042,
		scale = 3.2,
		desc_kr = "물속에서 뺨의 아가미로 호흡을 하고고 조난을 당했을 때 발휘하는 힘은 자신보다 큰 바위를 분쇄하기도 한다. 머리 위의 지느러미는 레이더같은 역할을 하여 주위 상황을 판별할 수 있다.",
		name_en = "Mudkip",
		desc_th = "มันหายใจด้วยเหงือกของพวกมันในน้ำ และพลังที่มันออกแรงเมื่ออยู่ในความทุกข์บางครั้งก็ทำให้หินก้อนใหญ่ทับตัวมันเอง ครีบบนศีรษะสามารถทำหน้าที่เหมือนเรดาร์เพื่อระบุสถานการณ์โดยรอบ",
		desc = "Relying on the cheeks to breathe in the water, the force he exerts in distress is enough to crush a rock larger than himself. The fin on its head acts as a radar and can distinguish the surrounding conditions",
		probability = 0.7,
		point = 1000,
		deadTime = 1,
		competitionEscape = 6,
		weekMax = 1,
		name_vn = "Mudkip",
		weight = -1,
		award = slot8[1042],
		scene = slot3[1042],
		randMove = slot2[1042],
		time = slot6[1042],
		competitionRandMove = slot7[1042]
	},
	[1101] = {
		name = "Gyarados Shard",
		name_en = "Gyarados Shard",
		name_kr = "갸라도스 조각",
		weight = 15,
		desc_th = "น่าเสียดายที่เขามีเพียงชิ้นเดียวเท่านั้น",
		desc = "Sorry but he only have shards",
		competitionSpeed = 11,
		probability = 0.7,
		point = 500,
		escape = 5,
		competitionEscape = 6,
		icon = "config/portrait/jinglingtouxiang/img_130_bll@.png",
		desc_vn = "Desculpe, mas ele só tem fragmentos",
		deadTime = 1,
		desc_en = "Sorry but he only have shards",
		rare = 3,
		speed = 11,
		res = "config/big_hero/standby/img_130_bll@.png",
		name_vn = "Gyarados Shard",
		name_th = "Gyarados Shard",
		id = 1101,
		scale = 1.3,
		desc_kr = "아쉽게도 그는 조각밖에 없다.",
		award = {
			[20631.0] = 1,
			__size = 1
		},
		randMove = slot2[1101],
		time = slot6[1101],
		competitionRandMove = slot7[1101]
	},
	[1102] = {
		name = "Gyarados Shard",
		name_en = "Gyarados Shard",
		name_kr = "갸라도스 조각",
		weight = 15,
		desc_th = "น่าเสียดายที่เขามีเพียงชิ้นเดียวเท่านั้น",
		desc = "Sorry but he only have shards",
		competitionSpeed = 11,
		probability = 0.7,
		point = 500,
		escape = 5,
		competitionEscape = 6,
		icon = "config/portrait/jinglingtouxiang/img_130_bll@.png",
		desc_vn = "Desculpe, mas ele só tem fragmentos",
		deadTime = 1,
		desc_en = "Sorry but he only have shards",
		rare = 3,
		speed = 11,
		res = "config/big_hero/standby/img_130_bll@.png",
		name_vn = "Gyarados Shard",
		name_th = "Gyarados Shard",
		id = 1102,
		scale = 1.3,
		desc_kr = "아쉽게도 그는 조각밖에 없다.",
		award = {
			[20631.0] = 2,
			__size = 1
		},
		randMove = slot2[1102],
		time = slot6[1102],
		competitionRandMove = slot7[1102]
	},
	[1111] = {
		name = "Mudkip Shard",
		name_en = "Mudkip Shard",
		name_kr = "물짱이 조각",
		weight = 15,
		desc_th = "น่าเสียดายที่เขามีเพียงชิ้นเดียวเท่านั้น",
		desc = "Sorry but he only have shards",
		competitionSpeed = 11,
		probability = 0.7,
		point = 500,
		escape = 5,
		competitionEscape = 6,
		icon = "config/portrait/jinglingtouxiang/img_258_syy@.png",
		desc_vn = "Desculpe, mas ele só tem fragmentos",
		deadTime = 1,
		desc_en = "Sorry but he only have shards",
		rare = 3,
		speed = 11,
		res = "config/big_hero/standby/img_258_syy@.png",
		name_vn = "Mudkip Shard",
		name_th = "Mudkip Shard",
		id = 1111,
		scale = 1.6,
		desc_kr = "아쉽게도 그는 조각밖에 없다.",
		award = {
			[21311.0] = 1,
			__size = 1
		},
		randMove = slot2[1111],
		time = slot6[1111],
		competitionRandMove = slot7[1111]
	},
	[1112] = {
		name = "Mudkip Shard",
		name_en = "Mudkip Shard",
		name_kr = "물짱이 조각",
		weight = 15,
		desc_th = "น่าเสียดายที่เขามีเพียงชิ้นเดียวเท่านั้น",
		desc = "Sorry but he only have shards",
		competitionSpeed = 11,
		probability = 0.7,
		point = 500,
		escape = 5,
		competitionEscape = 6,
		icon = "config/portrait/jinglingtouxiang/img_258_syy@.png",
		desc_vn = "Desculpe, mas ele só tem fragmentos",
		deadTime = 1,
		desc_en = "Sorry but he only have shards",
		rare = 3,
		speed = 11,
		res = "config/big_hero/standby/img_258_syy@.png",
		name_vn = "Mudkip Shard",
		name_th = "Mudkip Shard",
		id = 1112,
		scale = 1.6,
		desc_kr = "아쉽게도 그는 조각밖에 없다.",
		award = {
			[21311.0] = 2,
			__size = 1
		},
		randMove = slot2[1112],
		time = slot6[1112],
		competitionRandMove = slot7[1112]
	},
	[1201] = {
		name = "Dratini Shard",
		name_en = "Dratini Shard",
		name_kr = "미뇽 조각",
		weight = 8,
		desc_th = "น่าเสียดายที่เขามีเพียงชิ้นเดียวเท่านั้น",
		speed = 11,
		desc = "Sorry but he only have shards",
		probability = 0.65,
		point = 1000,
		escape = 5,
		competitionSpeed = 11,
		icon = "config/portrait/jinglingtouxiang/img_147_mnl@.png",
		desc_vn = "Desculpe, mas ele só tem fragmentos",
		deadTime = 1,
		competitionEscape = 6,
		desc_en = "Sorry but he only have shards",
		rare = 3,
		res = "config/big_hero/standby/img_147_mnl@.png",
		name_vn = "Dratini Shard",
		name_th = "Dratini Shard",
		id = 1201,
		scale = 2,
		desc_kr = "아쉽게도 그는 조각밖에 없다.",
		award = {
			[20751.0] = 1,
			__size = 1
		},
		scene = slot3[1201],
		randMove = slot2[1201],
		time = slot6[1201],
		competitionRandMove = slot7[1201]
	},
	[1202] = {
		name = "Dratini Shard",
		name_en = "Dratini Shard",
		name_kr = "미뇽 조각",
		weight = 8,
		desc_th = "น่าเสียดายที่เขามีเพียงชิ้นเดียวเท่านั้น",
		speed = 11,
		desc = "Sorry but he only have shards",
		probability = 0.65,
		point = 1000,
		escape = 5,
		competitionSpeed = 11,
		icon = "config/portrait/jinglingtouxiang/img_147_mnl@.png",
		desc_vn = "Desculpe, mas ele só tem fragmentos",
		deadTime = 1,
		competitionEscape = 6,
		desc_en = "Sorry but he only have shards",
		rare = 3,
		res = "config/big_hero/standby/img_147_mnl@.png",
		name_vn = "Dratini Shard",
		name_th = "Dratini Shard",
		id = 1202,
		scale = 2,
		desc_kr = "아쉽게도 그는 조각밖에 없다.",
		award = {
			[20751.0] = 2,
			__size = 1
		},
		scene = slot3[1202],
		randMove = slot2[1202],
		time = slot6[1202],
		competitionRandMove = slot7[1202]
	},
	[2001] = {
		name_kr = "낡은 자루",
		name_en = "Old bag",
		type = 3,
		name = "Old bag",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		weight = 30,
		desc = "There is something strange in it",
		speed = 10,
		probability = 1,
		point = 500,
		escape = 10,
		icon = "config/item/fishing/icon_box_dz.png",
		desc_vn = "Há algo estranho nisso",
		deadTime = 1,
		competitionSpeed = 10,
		competitionEscape = 11,
		desc_en = "There is something strange in it",
		rare = 1,
		res = "city/adventure/fishing/pjdz.png",
		name_vn = "Old bag",
		name_th = "กระเป๋าเก่า",
		id = 2001,
		scale = 3,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		award = {
			gold = 20000,
			__size = 2,
			libs = {
				631,
				631
			}
		},
		scene = slot3[2001],
		randMove = slot2[2001],
		time = slot6[2001],
		competitionRandMove = slot7[2001]
	},
	[2002] = {
		name_kr = "이상한 보물 상자",
		name_en = "Strange treasure chest",
		type = 3,
		name = "Strange treasure chest",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		weight = 10,
		desc = "There is something strange in it",
		speed = 10,
		probability = 1,
		point = 500,
		escape = 10,
		icon = "config/item/box/box_22_1.png",
		desc_vn = "Há algo estranho nisso",
		deadTime = 1,
		competitionSpeed = 10,
		competitionEscape = 11,
		desc_en = "There is something strange in it",
		rare = 1,
		res = "city/adventure/fishing/box_22_1.png",
		name_vn = "Strange treasure chest",
		name_th = "หีบสมบัติประหลาด",
		id = 2002,
		scale = 2,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		award = {
			gold = 50000,
			__size = 2,
			libs = {
				632,
				632
			}
		},
		scene = slot3[2002],
		randMove = slot2[2002],
		time = slot6[2002],
		competitionRandMove = slot7[2002]
	},
	[2003] = {
		name_kr = "이상한 보물 상자",
		name_en = "Strange treasure chest",
		type = 3,
		name = "Strange treasure chest",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		weight = 5,
		desc = "There is something strange in it",
		speed = 10,
		probability = 1,
		point = 500,
		escape = 10,
		icon = "config/item/box/box_22_2.png",
		desc_vn = "Há algo estranho nisso",
		deadTime = 1,
		competitionSpeed = 10,
		competitionEscape = 11,
		desc_en = "There is something strange in it",
		rare = 2,
		res = "city/adventure/fishing/box_22_2.png",
		name_vn = "Strange treasure chest",
		name_th = "หีบสมบัติประหลาด",
		id = 2003,
		scale = 2,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		award = {
			gold = 100000,
			rmb = 20,
			__size = 3,
			libs = {
				633,
				633
			}
		},
		scene = slot3[2003],
		randMove = slot2[2003],
		time = slot6[2003],
		competitionRandMove = slot7[2003]
	},
	[2004] = {
		weightMax = 0.009,
		name = "Strange treasure chest",
		overDeal = 3,
		type = 3,
		desc_vn = "Há algo estranho nisso",
		randType = 2,
		name_kr = "이상한 보물 상자",
		competitionSpeed = 10,
		escape = 10,
		icon = "config/item/box/box_22_3.png",
		weightMin = 0.001,
		priority = 1,
		desc_en = "There is something strange in it",
		rare = 1,
		speed = 10,
		res = "city/adventure/fishing/box_22_3.png",
		name_th = "หีบสมบัติประหลาด",
		id = 2004,
		scale = 2,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		name_en = "Strange treasure chest",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		desc = "There is something strange in it",
		probability = 1,
		point = 500,
		deadTime = 1,
		competitionEscape = 11,
		weekMax = 2,
		name_vn = "Strange treasure chest",
		weight = -1,
		award = {
			gold = 200000,
			rmb = 50,
			__size = 3,
			libs = {
				633,
				633,
				633,
				633
			}
		},
		scene = slot3[2004],
		randMove = slot2[2004],
		time = slot6[2004],
		competitionRandMove = slot7[2004]
	},
	[2010] = {
		desc_vn = "Há algo estranho nisso",
		name = "Strange treasure chest",
		weightMax = 0.05,
		type = 3,
		overDeal = 3,
		randType = 2,
		name_kr = "이상한 보물 상자",
		competitionSpeed = 10,
		escape = 10,
		icon = "config/item/box/box_22_3.png",
		weightMin = 0,
		priority = 1,
		desc_en = "There is something strange in it",
		rare = 3,
		speed = 10,
		res = "city/adventure/fishing/box_22_3.png",
		name_th = "หีบสมบัติประหลาด",
		id = 2010,
		scale = 2,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		name_en = "Strange treasure chest",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		desc = "There is something strange in it",
		probability = 1,
		point = 500,
		deadTime = 1,
		competitionEscape = 11,
		weekMax = 3,
		name_vn = "Strange treasure chest",
		maxWinTimes = 1,
		award = {
			gold = 1000000,
			__size = 1
		},
		scene = slot3[2010],
		randMove = slot2[2010],
		time = slot6[2010],
		competitionRandMove = slot7[2010]
	},
	[2011] = {
		desc_vn = "Há algo estranho nisso",
		name = "Strange treasure chest",
		weightMax = 0.025,
		type = 3,
		overDeal = 3,
		randType = 2,
		name_kr = "이상한 보물 상자",
		competitionSpeed = 10,
		escape = 10,
		icon = "config/item/box/box_22_3.png",
		weightMin = 0,
		priority = 1,
		desc_en = "There is something strange in it",
		rare = 3,
		speed = 10,
		res = "city/adventure/fishing/box_22_3.png",
		name_th = "หีบสมบัติประหลาด",
		id = 2011,
		scale = 2,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		name_en = "Strange treasure chest",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		desc = "There is something strange in it",
		probability = 1,
		point = 500,
		deadTime = 1,
		competitionEscape = 11,
		weekMax = 3,
		name_vn = "Strange treasure chest",
		maxWinTimes = 1,
		award = {
			__size = 1,
			rmb = 200
		},
		scene = slot3[2011],
		randMove = slot2[2011],
		time = slot6[2011],
		competitionRandMove = slot7[2011]
	},
	[2101] = {
		name_kr = "미끼 보물 상자",
		name_en = "Bait treasure chest",
		type = 3,
		name = "Bait treasure chest",
		desc_th = "ดูเหมือนว่าจะมีสิ่งแปลกปลอมอยู่ในนั้น",
		weight = 15,
		desc = "There is something strange in it",
		speed = 13,
		probability = 1,
		point = 500,
		escape = 10,
		icon = "config/item/box/box_22_2.png",
		desc_vn = "Há algo estranho nisso",
		deadTime = 1,
		competitionSpeed = 13,
		competitionEscape = 11,
		desc_en = "There is something strange in it",
		rare = 2,
		res = "city/adventure/fishing/box_22_2.png",
		name_vn = "Bait treasure chest",
		name_th = "หีบสมบัติเหยื่อ",
		id = 2101,
		scale = 2,
		desc_kr = "뭔가 이상한 것이 들어 있는 것 같다.",
		award = {
			[7112.0] = 1,
			__size = 1
		},
		scene = {
			2,
			3
		},
		randMove = slot2[2101],
		time = slot6[2101],
		competitionRandMove = slot7[2101]
	},
	[9999] = {
		speed = 8,
		name = "Kyogre",
		weightMax = 0.1,
		name_kr = "가이오가",
		randType = 2,
		desc_vn = "Rei do oceano, só aparece em competição de pesca",
		overDeal = 4,
		competitionSpeed = 7,
		escape = 4,
		big = 480,
		icon = "config/portrait/jinglingtouxiang/img_382_gok@.png",
		weightMin = 0.05,
		priority = 999,
		desc_en = "King of the ocean, only appear in fishing competition",
		rare = 3,
		res = "config/big_hero/standby/img_382_gok@.png",
		name_th = "Kyogre",
		id = 9999,
		scale = 2,
		desc_kr = "바다의 왕. 낚시 대회에서만 나타난다.",
		name_en = "Kyogre",
		desc_th = "ราชาแห่งท้องทะเล ปรากฏเฉพาะในการแข่งขันตกปลา",
		desc = "King of the ocean, only appear in fishing competition",
		probability = 0.5,
		point = 1000,
		competitionEscape = 5,
		weekMax = 4,
		name_vn = "Kyogre",
		bookId = 1,
		weight = 8,
		length = {
			400,
			500
		},
		operateTimePointUp = {
			{
				3,
				9,
				0.5
			},
			{
				9,
				12,
				0.2
			},
			{
				12,
				20,
				0.1
			}
		},
		award = {
			__size = 1,
			[21961.0] = 1
		},
		scene = {
			999
		},
		randMove = {
			30,
			60
		},
		time = slot6[9999],
		competitionRandMove = {
			43,
			69
		}
	},
	__default = {
		__index = {
			showType = "pic",
			name = "",
			type = 1,
			name_kr = "",
			weightMax = -1,
			overDeal = 1,
			speed = 0,
			competitionSpeed = 0,
			escape = 0,
			big = 0,
			icon = "",
			desc_vn = "",
			weightMin = -1,
			priority = 0,
			desc_en = "",
			rare = 0,
			res = "",
			name_th = "",
			randType = 1,
			scale = 1,
			desc_kr = "",
			name_en = "",
			desc_th = "",
			desc = "",
			probability = 0,
			point = 0,
			crossFishingWeight = 0,
			deadTime = 0,
			competitionEscape = 0,
			weekMax = -1,
			needLv = 0,
			name_vn = "",
			bookId = 0,
			weight = 0,
			maxWinTimes = -1,
			length = slot5.default,
			operateTimePointUp = slot1.default,
			award = {
				__size = 0
			},
			bait = ({
				default = slot0[1]
			}).default,
			scene = slot3.default,
			randMove = slot2.default,
			time = slot6.default,
			competitionRandMove = slot7.default
		}
	}
}

return csv.fishing.fish
