slot0 = cc.AssetsManagerEx:getInstance()
globals.PATCH_MIN_VERSION = slot0:getPatchMinVersion()
globals.PATCH_VERSION = slot0:getPatchVersion()

printInfo("PATCH_MIN_VERSION %d", PATCH_MIN_VERSION)
printInfo("PATCH_VERSION %d", PATCH_VERSION)
require("app.defines.dev_defines")
require("app.defines.app_defines")
require("app.defines.game_defines")
require("app.defines.ui_defines")
require("battle.battle_defines")
require("app.defines.config_defines")
