slot0 = {
	__size = 0
}
csv.cross.horse_race.horse_race_card = {
	{
		name_en = "Articuno",
		name = "Articuno",
		name_tw = "Articuno",
		name_kr = "프리져",
		group = 1,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 500,
		sprintInterval = 12,
		name_vn = "Articuno",
		name_th = "Articuno",
		id = 1,
		sprintRandom = 38,
		unitID = 721,
		sprintTime = 18
	},
	{
		name_en = "Moltres",
		name = "Moltres",
		name_tw = "Moltres",
		name_kr = "파이어",
		group = 1,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 560,
		sprintInterval = 14,
		name_vn = "Moltres",
		name_th = "Moltres",
		id = 2,
		sprintRandom = 35,
		unitID = 741,
		sprintTime = 16
	},
	{
		name_en = "Zapdos",
		name = "Zapdos",
		name_tw = "Zapdos",
		name_kr = "썬더",
		group = 1,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 590,
		sprintInterval = 15,
		name_vn = "Zapdos",
		name_th = "Zapdos",
		id = 3,
		sprintRandom = 32,
		unitID = 731,
		sprintTime = 15
	},
	{
		name_en = "Dragonite",
		name = "Dragonite",
		name_tw = "Dragonite",
		name_kr = "망나뇽",
		group = 1,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 630,
		sprintInterval = 16,
		name_vn = "Dragonite",
		name_th = "Dragonite",
		id = 4,
		sprintRandom = 30,
		unitID = 753,
		sprintTime = 14
	},
	{
		name_en = "Salamence",
		name = "Salamence",
		name_tw = "Salamence",
		name_kr = "보만다",
		group = 2,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 500,
		sprintInterval = 12,
		name_vn = "Salamence",
		name_th = "Salamence",
		id = 5,
		sprintRandom = 38,
		unitID = 1893,
		sprintTime = 18
	},
	{
		name_en = "Togekiss",
		name = "Togekiss",
		name_tw = "Togekiss",
		name_kr = "토게키스",
		group = 2,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 560,
		sprintInterval = 14,
		name_vn = "Togekiss",
		name_th = "Togekiss",
		id = 6,
		sprintRandom = 35,
		unitID = 863,
		sprintTime = 16
	},
	{
		name_en = "Latios",
		name = "Latios",
		name_tw = "Latios",
		name_kr = "라티오스",
		group = 2,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 590,
		sprintInterval = 15,
		name_vn = "Latios",
		name_th = "Latios",
		id = 7,
		sprintRandom = 32,
		unitID = 1951,
		sprintTime = 15
	},
	{
		name_en = "Latias",
		name = "Latias",
		name_tw = "Latias",
		name_kr = "라티아스",
		group = 2,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 630,
		sprintInterval = 16,
		name_vn = "Latias",
		name_th = "Latias",
		id = 8,
		sprintRandom = 30,
		unitID = 1941,
		sprintTime = 14
	},
	{
		name_en = "Cresselia",
		name = "Cresselia",
		name_tw = "Cresselia",
		name_kr = "크레세리아",
		group = 3,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 425,
		sprintInterval = 12,
		name_vn = "Cresselia",
		name_th = "Cresselia",
		id = 9,
		sprintRandom = 38,
		unitID = 2401,
		sprintTime = 18
	},
	{
		name_en = "Gardevoir",
		name = "Gardevoir",
		name_tw = "Gardevoir",
		name_kr = "가디안",
		group = 3,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 481,
		sprintInterval = 14,
		name_vn = "Gardevoir",
		name_th = "Gardevoir",
		id = 10,
		sprintRandom = 35,
		unitID = 1395,
		sprintTime = 16
	},
	{
		name_en = "Gothitelle",
		name = "Gothitelle",
		name_tw = "Gothitelle",
		name_kr = "고디모아젤",
		group = 3,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 502,
		sprintInterval = 15,
		name_vn = "Gothitelle",
		name_th = "Gothitelle",
		id = 11,
		sprintRandom = 32,
		unitID = 2843,
		sprintTime = 15
	},
	{
		name_en = "Chandelure",
		name = "Chandelure",
		name_tw = "Chandelure",
		name_kr = "샹델라",
		group = 3,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 536,
		sprintInterval = 16,
		name_vn = "Chandelure",
		name_th = "Chandelure",
		id = 12,
		sprintRandom = 30,
		unitID = 2993,
		sprintTime = 14
	},
	{
		name_en = "Lugia",
		name = "Lugia",
		name_tw = "Lugia",
		name_kr = "루기아",
		group = 4,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 598,
		sprintInterval = 12,
		name_vn = "Lugia",
		name_th = "Lugia",
		id = 13,
		sprintRandom = 38,
		unitID = 1261,
		sprintTime = 18
	},
	{
		name_en = "Ho-Oh",
		name = "Ho-Oh",
		name_tw = "Ho-Oh",
		name_kr = "칠색조",
		group = 4,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 672,
		sprintInterval = 14,
		name_vn = "Ho-Oh",
		name_th = "Ho-Oh",
		id = 14,
		sprintRandom = 35,
		unitID = 1271,
		sprintTime = 16
	},
	{
		name_en = "Kyogre",
		name = "Kyogre",
		name_tw = "Kyogre",
		name_kr = "가이오가",
		group = 4,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 708,
		sprintInterval = 15,
		name_vn = "Kyogre",
		name_th = "Kyogre",
		id = 15,
		sprintRandom = 32,
		unitID = 1961,
		sprintTime = 15
	},
	{
		name_en = "Groudon",
		name = "Groudon",
		name_tw = "Groudon",
		name_kr = "그란돈",
		group = 4,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 756,
		sprintInterval = 16,
		name_vn = "Groudon",
		name_th = "Groudon",
		id = 16,
		sprintRandom = 30,
		unitID = 1971,
		sprintTime = 14
	},
	{
		name_en = "Arcanine",
		name = "Arcanine",
		name_tw = "Arcanine",
		name_kr = "윈디",
		group = 5,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 500,
		sprintInterval = 12,
		name_vn = "Arcanine",
		name_th = "Arcanine",
		id = 17,
		sprintRandom = 38,
		unitID = 242,
		sprintTime = 18
	},
	{
		name_en = "Houndour",
		name = "Houndour",
		name_tw = "Houndour",
		name_kr = "델빌",
		group = 5,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 560,
		sprintInterval = 14,
		name_vn = "Houndour",
		name_th = "Houndour",
		id = 18,
		sprintRandom = 35,
		unitID = 1171,
		sprintTime = 16
	},
	{
		name_en = "Absol",
		name = "Absol",
		name_tw = "Absol",
		name_kr = "앱솔",
		group = 5,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 590,
		sprintInterval = 15,
		name_vn = "Absol",
		name_th = "Absol",
		id = 19,
		sprintRandom = 32,
		unitID = 1841,
		sprintTime = 15
	},
	{
		name_en = "Lucario",
		name = "Lucario",
		name_tw = "Lucario",
		name_kr = "루카리오",
		group = 5,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 630,
		sprintInterval = 16,
		name_vn = "Lucario",
		name_th = "Lucario",
		id = 20,
		sprintRandom = 30,
		unitID = 2242,
		sprintTime = 14
	},
	{
		name_en = "Blastoise",
		name = "Blastoise",
		name_tw = "Blastoise",
		name_kr = "거북왕",
		group = 6,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 425,
		sprintInterval = 12,
		name_vn = "Blastoise",
		name_th = "Blastoise",
		id = 21,
		sprintRandom = 38,
		unitID = 23,
		sprintTime = 18
	},
	{
		name_en = "Lapras",
		name = "Lapras",
		name_tw = "Lapras",
		name_kr = "라프라스",
		group = 6,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 481,
		sprintInterval = 14,
		name_vn = "Lapras",
		name_th = "Lapras",
		id = 22,
		sprintRandom = 35,
		unitID = 641,
		sprintTime = 16
	},
	{
		name_en = "Empoleon",
		name = "Empoleon",
		name_tw = "Empoleon",
		name_kr = "엠페르트",
		group = 6,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 502,
		sprintInterval = 15,
		name_vn = "Empoleon",
		name_th = "Empoleon",
		id = 23,
		sprintRandom = 32,
		unitID = 2033,
		sprintTime = 15
	},
	{
		name_en = "Feraligatr",
		name = "Feraligatr",
		name_tw = "Feraligatr",
		name_kr = "장크로다일",
		group = 6,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 536,
		sprintInterval = 16,
		name_vn = "Feraligatr",
		name_th = "Feraligatr",
		id = 24,
		sprintRandom = 30,
		unitID = 803,
		sprintTime = 14
	},
	{
		name_en = "Swampert",
		name = "Swampert",
		name_tw = "Swampert",
		name_kr = "대짱이",
		group = 7,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 425,
		sprintInterval = 12,
		name_vn = "Swampert",
		name_th = "Swampert",
		id = 25,
		sprintRandom = 38,
		unitID = 1313,
		sprintTime = 18
	},
	{
		name_en = "Starmie",
		name = "Starmie",
		name_tw = "Starmie",
		name_kr = "아쿠스타",
		group = 7,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 481,
		sprintInterval = 14,
		name_vn = "Starmie",
		name_th = "Starmie",
		id = 26,
		sprintRandom = 35,
		unitID = 552,
		sprintTime = 16
	},
	{
		name_en = "Toxapex",
		name = "Toxapex",
		name_tw = "Toxapex",
		name_kr = "더시마사리",
		group = 7,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 502,
		sprintInterval = 15,
		name_vn = "Toxapex",
		name_th = "Toxapex",
		id = 27,
		sprintRandom = 32,
		unitID = 3772,
		sprintTime = 15
	},
	{
		name_en = "Greninja",
		name = "Greninja",
		name_tw = "Greninja",
		name_kr = "개굴닌자",
		group = 7,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 536,
		sprintInterval = 16,
		name_vn = "Greninja",
		name_th = "Greninja",
		id = 28,
		sprintRandom = 30,
		unitID = 3303,
		sprintTime = 14
	},
	{
		name_en = "Zoroark",
		name = "Zoroark",
		name_tw = "Zoroark",
		name_kr = "조로아크",
		group = 8,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 500,
		sprintInterval = 12,
		name_vn = "Zoroark",
		name_th = "Zoroark",
		id = 29,
		sprintRandom = 38,
		unitID = 2822,
		sprintTime = 18
	},
	{
		name_en = "Darkrai",
		name = "Darkrai",
		name_tw = "Darkrai",
		name_kr = "다크라이",
		group = 8,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 560,
		sprintInterval = 14,
		name_vn = "Darkrai",
		name_th = "Darkrai",
		id = 30,
		sprintRandom = 35,
		unitID = 2432,
		sprintTime = 16
	},
	{
		name_en = "Krookodile",
		name = "Krookodile",
		name_tw = "Krookodile",
		name_kr = "악비아르",
		group = 8,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 590,
		sprintInterval = 15,
		name_vn = "Krookodile",
		name_th = "Krookodile",
		id = 31,
		sprintRandom = 32,
		unitID = 2723,
		sprintTime = 15
	},
	{
		name_en = "Weavile",
		name = "Weavile",
		name_tw = "Weavile",
		name_kr = "포푸니라",
		group = 8,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 630,
		sprintInterval = 16,
		name_vn = "Weavile",
		name_th = "Weavile",
		id = 32,
		sprintRandom = 30,
		unitID = 1082,
		sprintTime = 14
	},
	{
		name_en = "Cleffa",
		name = "Cleffa",
		name_tw = "Cleffa",
		name_kr = "삐",
		group = 9,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 375,
		sprintInterval = 12,
		name_vn = "Cleffa",
		name_th = "Cleffa",
		id = 33,
		sprintRandom = 38,
		unitID = 131,
		sprintTime = 18
	},
	{
		name_en = "Igglybuff",
		name = "Igglybuff",
		name_tw = "Igglybuff",
		name_kr = "푸푸린",
		group = 9,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 420,
		sprintInterval = 14,
		name_vn = "Igglybuff",
		name_th = "Igglybuff",
		id = 34,
		sprintRandom = 35,
		unitID = 151,
		sprintTime = 16
	},
	{
		name_en = "Swirlix",
		name = "Swirlix",
		name_tw = "Swirlix",
		name_kr = "나룸퍼프",
		group = 9,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 443,
		sprintInterval = 15,
		name_vn = "Swirlix",
		name_th = "Swirlix",
		id = 35,
		sprintRandom = 32,
		unitID = 3431,
		sprintTime = 15
	},
	{
		name_en = "Lickitung",
		name = "Lickitung",
		name_tw = "Lickitung",
		name_kr = "내루미",
		group = 9,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 473,
		sprintInterval = 16,
		name_vn = "Lickitung",
		name_th = "Lickitung",
		id = 36,
		sprintRandom = 30,
		unitID = 471,
		sprintTime = 14
	},
	{
		name_en = "Tyranitar",
		name = "Tyranitar",
		name_tw = "Tyranitar",
		name_kr = "마기라스",
		group = 10,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 375,
		sprintInterval = 12,
		name_vn = "Tyranitar",
		name_th = "Tyranitar",
		id = 37,
		sprintRandom = 38,
		unitID = 1253,
		sprintTime = 18
	},
	{
		name_en = "Aggron",
		name = "Aggron",
		name_tw = "Aggron",
		name_kr = "보스로라",
		group = 10,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 420,
		sprintInterval = 14,
		name_vn = "Aggron",
		name_th = "Aggron",
		id = 38,
		sprintRandom = 35,
		unitID = 1503,
		sprintTime = 16
	},
	{
		name_en = "Snorlax",
		name = "Snorlax",
		name_tw = "Snorlax",
		name_kr = "잠만보",
		group = 10,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 443,
		sprintInterval = 15,
		name_vn = "Snorlax",
		name_th = "Snorlax",
		id = 39,
		sprintRandom = 32,
		unitID = 712,
		sprintTime = 15
	},
	{
		name_en = "Slaking",
		name = "Slaking",
		name_tw = "Slaking",
		name_kr = "게을킹",
		group = 10,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 473,
		sprintInterval = 16,
		name_vn = "Slaking",
		name_th = "Slaking",
		id = 40,
		sprintRandom = 30,
		unitID = 1423,
		sprintTime = 14
	},
	{
		name_en = "Shaymin - Sky",
		name = "Shaymin - Sky",
		name_tw = "Shaymin - Sky",
		name_kr = "404404",
		group = 11,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 598,
		sprintInterval = 12,
		name_vn = "Shaymin - Sky",
		name_th = "Shaymin - Sky",
		id = 41,
		sprintRandom = 38,
		unitID = 2442,
		sprintTime = 18
	},
	{
		name_en = "Reshiram",
		name = "Reshiram",
		name_tw = "Reshiram",
		name_kr = "레시라무",
		group = 11,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 672,
		sprintInterval = 14,
		name_vn = "Reshiram",
		name_th = "Reshiram",
		id = 42,
		sprintRandom = 35,
		unitID = 3211,
		sprintTime = 16
	},
	{
		name_en = "Zekrom",
		name = "Zekrom",
		name_tw = "Zekrom",
		name_kr = "제크로무",
		group = 11,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 708,
		sprintInterval = 15,
		name_vn = "Zekrom",
		name_th = "Zekrom",
		id = 43,
		sprintRandom = 32,
		unitID = 3221,
		sprintTime = 15
	},
	{
		name_en = "Kyurem",
		name = "Kyurem",
		name_tw = "Kyurem",
		name_kr = "큐레무",
		group = 11,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 756,
		sprintInterval = 16,
		name_vn = "Kyurem",
		name_th = "Kyurem",
		id = 44,
		sprintRandom = 30,
		unitID = 3241,
		sprintTime = 14
	},
	{
		name_en = "Raikou",
		name = "Raikou",
		name_tw = "Raikou",
		name_kr = "라이코",
		group = 12,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 500,
		sprintInterval = 12,
		name_vn = "Raikou",
		name_th = "Raikou",
		id = 45,
		sprintRandom = 38,
		unitID = 1221,
		sprintTime = 18
	},
	{
		name_en = "Entei",
		name = "Entei",
		name_tw = "Entei",
		name_kr = "앤테이",
		group = 12,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 560,
		sprintInterval = 14,
		name_vn = "Entei",
		name_th = "Entei",
		id = 46,
		sprintRandom = 35,
		unitID = 1231,
		sprintTime = 16
	},
	{
		name_en = "Suicune",
		name = "Suicune",
		name_tw = "Suicune",
		name_kr = "스이쿤",
		group = 12,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 590,
		sprintInterval = 15,
		name_vn = "Suicune",
		name_th = "Suicune",
		id = 47,
		sprintRandom = 32,
		unitID = 1241,
		sprintTime = 15
	},
	{
		name_en = "404404",
		name = "404404",
		name_tw = "404404",
		name_kr = "404",
		group = 12,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 630,
		sprintInterval = 16,
		name_vn = "404404",
		name_th = "404404",
		id = 48,
		sprintRandom = 30,
		unitID = 7001,
		sprintTime = 14
	},
	{
		name_en = "Regirock",
		name = "Regirock",
		name_tw = "Regirock",
		name_kr = "레지락",
		group = 13,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 500,
		sprintInterval = 12,
		name_vn = "Regirock",
		name_th = "Regirock",
		id = 49,
		sprintRandom = 38,
		unitID = 1911,
		sprintTime = 18
	},
	{
		name_en = "Regice",
		name = "Regice",
		name_tw = "Regice",
		name_kr = "레지아이스",
		group = 13,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 560,
		sprintInterval = 14,
		name_vn = "Regice",
		name_th = "Regice",
		id = 50,
		sprintRandom = 35,
		unitID = 1921,
		sprintTime = 16
	},
	{
		name_en = "Registeel",
		name = "Registeel",
		name_tw = "Registeel",
		name_kr = "레지스틸",
		group = 13,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 590,
		sprintInterval = 15,
		name_vn = "Registeel",
		name_th = "Registeel",
		id = 51,
		sprintRandom = 32,
		unitID = 1931,
		sprintTime = 15
	},
	{
		name_en = "Regigigas",
		name = "Regigigas",
		name_tw = "Regigigas",
		name_kr = "레지기가스",
		group = 13,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 630,
		sprintInterval = 16,
		name_vn = "Regigigas",
		name_th = "Regigigas",
		id = 52,
		sprintRandom = 30,
		unitID = 2381,
		sprintTime = 14
	},
	{
		name_en = "Ditto - Purple",
		name = "Ditto - Purple",
		name_tw = "Ditto - Purple",
		name_kr = "메타몽: 보라색",
		group = 14,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 375,
		sprintInterval = 12,
		name_vn = "Ditto - Purple",
		name_th = "Ditto - Purple",
		id = 53,
		sprintRandom = 38,
		unitID = 9001,
		sprintTime = 18
	},
	{
		name_en = "Ditto - Orange",
		name = "Ditto - Orange",
		name_tw = "Ditto - Orange",
		name_kr = "메타몽: 주황색",
		group = 14,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 420,
		sprintInterval = 14,
		name_vn = "Ditto - Orange",
		name_th = "Ditto - Orange",
		id = 54,
		sprintRandom = 35,
		unitID = 9002,
		sprintTime = 16
	},
	{
		name_en = "Ditto - Red",
		name = "Ditto - Red",
		name_tw = "Ditto - Red",
		name_kr = "메타몽: 빨간색",
		group = 14,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 443,
		sprintInterval = 15,
		name_vn = "Ditto - Red",
		name_th = "Ditto - Red",
		id = 55,
		sprintRandom = 32,
		unitID = 9003,
		sprintTime = 15
	},
	{
		name_en = "Psyduck",
		name = "Psyduck",
		name_tw = "Psyduck",
		name_kr = "고라파덕",
		group = 14,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 473,
		sprintInterval = 16,
		name_vn = "Psyduck",
		name_th = "Psyduck",
		id = 56,
		sprintRandom = 30,
		unitID = 221,
		sprintTime = 14
	},
	{
		name_en = "404404",
		name = "404404",
		name_tw = "404404",
		name_kr = "메가레쿠쟈",
		group = 15,
		stamina = 150,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 598,
		sprintInterval = 12,
		name_vn = "404404",
		name_th = "404404",
		id = 57,
		sprintRandom = 38,
		unitID = 1982,
		sprintTime = 18
	},
	{
		name_en = "Dialga",
		name = "Dialga",
		name_tw = "Dialga",
		name_kr = "디아루가",
		group = 15,
		stamina = 145,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 672,
		sprintInterval = 14,
		name_vn = "Dialga",
		name_th = "Dialga",
		id = 58,
		sprintRandom = 35,
		unitID = 2351,
		sprintTime = 16
	},
	{
		name_en = "Palkia",
		name = "Palkia",
		name_tw = "Palkia",
		name_kr = "펄기아",
		group = 15,
		stamina = 140,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 708,
		sprintInterval = 15,
		name_vn = "Palkia",
		name_th = "Palkia",
		id = 59,
		sprintRandom = 32,
		unitID = 2361,
		sprintTime = 15
	},
	{
		name_en = "Giratina",
		name = "Giratina",
		name_tw = "Giratina",
		name_kr = "기라티나",
		group = 15,
		stamina = 135,
		staminaCost = 1.5,
		staminaRecovery = 1,
		speed = 756,
		sprintInterval = 16,
		name_vn = "Giratina",
		name_th = "Giratina",
		id = 60,
		sprintRandom = 30,
		unitID = 2391,
		sprintTime = 14
	},
	__size = 60,
	__default = {
		__index = {
			sprintInterval = 2,
			name_en = "",
			staminaRecovery = 10.5,
			name_kr = "",
			name_tw = "",
			weight = 100,
			name = "",
			sprintTime = 1,
			sprintRandom = 10,
			stamina = 100.1,
			sprintMultiple = 1.5,
			group = 0,
			staminaCost = 10.5,
			speed = 50,
			name_vn = "",
			name_th = "",
			unitID = 0
		}
	}
}

return csv.cross.horse_race.horse_race_card
