slot0 = {
	__size = 2,
	[3] = {
		1,
		0,
		0,
		0,
		0,
		0
	},
	[11] = {
		0,
		0,
		0,
		0,
		1,
		0
	}
}
slot1 = {
	slot0[3],
	slot0[3],
	[11] = slot0[3],
	[10] = slot0[11],
	[12] = slot0[11],
	[3] = slot0[3],
	[5] = slot0[3],
	[4] = slot0[3],
	[7] = slot0[3],
	[6] = slot0[3],
	[9] = slot0[11],
	[8] = slot0[11]
}
csv.card_battle_recommend = {
	{
		matchEffect1_th = "1. Moltres: ความสามารถของมันให้ออร่าประเภทไฟ: เพิ่มความเสียหายคริติคอลของทีม แนบกลุ่มความเสียหายเบิร์นกับทักษะการริเริ่มทั้งหมด และเพิ่มคริติคอลของทีม",
		isRecommend = true,
		matchEffect1_en = "1. Moltres: Its abilities provide Fire-type Aura: Increase team's Crit damage, attach group Burn damage to all initiative skills and increase team's Crit",
		specialMarkTitle_th = "Fire critical hit",
		matchEffect6_th = "6. Houndoom: ให้โบนัส ATK ของกลุ่ม",
		name = "Fire critical hit",
		specialMarkBg = "city/card/battle_recommend/logo_bs1.png",
		matchEffect3_en = "3. Magby: All skills are attached with Burn effect. Igniting all Burns on targets to deal a high damage.",
		matchEffect4_en = "4. Blaziken: Higher single ATK. Deal a higher damage to Burned targets",
		matchEffect5_th = "5. Arcanine: ATK ความเร็วสูงของทีมดับเพลิง ดำเนินการอย่างรวดเร็วและฆ่าเป้าหมายในไม่กี่วินาที",
		matchEffect5_en = "5. Arcanine: Fire Team's high-speed ATK. Act quickly and kill targets in seconds",
		matchEffect6 = "6. Houndoom: Provide group ATK bonus",
		features = "Fire-type team's features: high Crit, high Crit damage, high ATK, attached with Burn damage",
		matchEffect6_en = "6. Houndoom: Provide group ATK bonus",
		sort = 9999,
		features_th = "คุณสมบัติของทีมประเภทไฟ: คริติคอลสูง ความเสียหายคริติคอลสูง พลังโจมตีสูง ติดความเสียหายจากการเผาไหม้",
		desc_en = "Fire critical hit",
		specialMarkTitle = "Fire critical hit",
		haloId = 6,
		coreEffectName_en = "Burning effect",
		matchEffect3 = "3. Magby: All skills are attached with Burn effect. Igniting all Burns on targets to deal a high damage.",
		matchEffect4_th = "4. Blaziken: ATK เดี่ยวที่สูงขึ้น สร้างความเสียหายให้กับเป้าหมายที่ถูกเผาไหม้มากขึ้น",
		name_th = "Fire critical hit",
		id = 1,
		specialMarkTitle_en = "Fire critical hit",
		name_en = "Fire critical hit",
		matchEffect5 = "5. Arcanine: Fire Team's high-speed ATK. Act quickly and kill targets in seconds",
		features_en = "Fire-type team's features: high Crit, high Crit damage, high ATK, attached with Burn damage",
		desc_th = "Fire critical hit",
		desc = "Fire critical hit",
		coreEffect_en = "At the beginning of the round that Burned targets act, deal a direct damage to the target and Burn damage can be stacked up to 5 times",
		matchEffect2 = "2. Entei: Fire-type tank in the front line. Fire God (passive skill) ensures the tank level. Lose its HP for high ATK and provides a buffer for Fire-type ultimate skills launching slowly",
		matchEffect2_th = "2. Entei: รถถังประเภทไฟในแนวหน้า Fire God (สกิลติดตัว) รับรองระดับรถถัง ลด HP สำหรับ ATK ที่สูงและให้บัฟเฟอร์สำหรับทักษะอัลติเมทประเภท Fire ที่เปิดตัวช้า",
		coreEffect_th = "At the beginning of the round that Burned targets act, deal a direct damage to the target and Burn damage can be stacked up to 5 times",
		coreEffectName_th = "Burning effect",
		coreEffectName = "Burning effect",
		matchEffect2_en = "2. Entei: Fire-type tank in the front line. Fire God (passive skill) ensures the tank level. Lose its HP for high ATK and provides a buffer for Fire-type ultimate skills launching slowly",
		matchEffect4 = "4. Blaziken: Higher single ATK. Deal a higher damage to Burned targets",
		matchEffect1 = "1. Moltres: Its abilities provide Fire-type Aura: Increase team's Crit damage, attach group Burn damage to all initiative skills and increase team's Crit",
		matchEffect3_th = "3. Magby: สกิลทั้งหมดมีเอฟเฟกต์ Burn ติดไฟเผาเป้าหมายทั้งหมดเพื่อสร้างความเสียหายสูง",
		coreEffect = "At the beginning of the round that Burned targets act, deal a direct damage to the target and Burn damage can be stacked up to 5 times",
		cards = {
			741,
			603,
			1231,
			1303,
			242,
			1172
		},
		coreMark = slot1[1]
	},
	{
		matchEffect1_th = "1. Suicune: มอบออร่า SPD และ Crit Res ของทีม ทักษะขั้นสูงสุดจะขจัดดีบัฟและลดความเสียหายคริติคอล",
		isRecommend = true,
		matchEffect1_en = "1. Suicune: Provide team's SPD aura and Crit Res. Its ultimate skill dispels debuffs and reduces Crit damage",
		specialMarkTitle_th = "High Crit Res and SPD",
		desc_en = "High Crit Res and SPD",
		name = "High Crit Res and SPD",
		specialMarkBg = "city/card/battle_recommend/logo_bs4.png",
		matchEffect3_en = "3. Swampert: The tank of a Water-type team",
		matchEffect4_en = "4. 4 S-class Water-type Pokemon can match with two S-class Pokemon of a same type to make up a 4+2 team aura. It's recommended to match with 2 Dragon-type Pokemon (to increase the advantage of attacking first) or 2 Ice-type Pokemon (to increase the advantage of controlling first)",
		features = "Offensive Burst Team: Attack first. Quickly kill enemy Pokemon and be numerically superior",
		sort = 9998,
		features_th = "Offensive Burst Team: โจมตีก่อน ฆ่า Pokemon ศัตรูอย่างรวดเร็วและเหนือกว่าด้วยตัวเลข",
		specialMarkTitle = "High Crit Res and SPD",
		haloId = 6,
		coreEffectName_en = "Team's advantages",
		matchEffect3 = "3. Swampert: The tank of a Water-type team",
		matchEffect4_th = "4. โปเกมอนธาตุน้ำ S-class 4 ตัวสามารถจับคู่กับโปเกมอน S-class สองตัวที่เป็นประเภทเดียวกันเพื่อสร้างออร่าทีม 4+2 ได้ แนะนำให้จับคู่กับโปเกมอนประเภทมังกร 2 ตัว (เพื่อเพิ่มข้อได้เปรียบในการโจมตีก่อน ) หรือ โปเกมอนธาตุน้ำแข็ง 2 ตัว (เพื่อเพิ่มข้อได้เปรียบในการควบคุมก่อน)",
		name_th = "High Crit Res and SPD",
		id = 2,
		specialMarkTitle_en = "High Crit Res and SPD",
		name_en = "High Crit Res and SPD",
		features_en = "Offensive Burst Team: Attack first. Quickly kill enemy Pokemon and be numerically superior",
		desc_th = "High Crit Res and SPD",
		desc = "High Crit Res and SPD",
		coreEffect_en = "Crit Res and SPD bonus, attached with dispelling effect and take advantages to act first",
		matchEffect2 = "2. Greninja and Gyarados are the best attackers of Water-type Pokemon",
		matchEffect2_th = "2. Greninja และ Gyarados เป็นผู้โจมตีที่ดีที่สุดของ Pokemon ประเภทน้ำ",
		coreEffect_th = "Crit Res and SPD bonus, attached with dispelling effect and take advantages to act first",
		coreEffectName_th = "Team's advantages",
		coreEffectName = "Team's advantages",
		matchEffect2_en = "2. Greninja and Gyarados are the best attackers of Water-type Pokemon",
		matchEffect4 = "4. 4 S-class Water-type Pokemon can match with two S-class Pokemon of a same type to make up a 4+2 team aura. It's recommended to match with 2 Dragon-type Pokemon (to increase the advantage of attacking first) or 2 Ice-type Pokemon (to increase the advantage of controlling first)",
		matchEffect1 = "1. Suicune: Provide team's SPD aura and Crit Res. Its ultimate skill dispels debuffs and reduces Crit damage",
		matchEffect3_th = "3. Swampert: แท็งก์ของทีมประเภทน้ำ",
		coreEffect = "Crit Res and SPD bonus, attached with dispelling effect and take advantages to act first",
		cards = {
			1241,
			3303,
			631,
			1313,
			552,
			1353
		},
		coreMark = slot1[2]
	},
	{
		matchEffect1_th = "1. ทักษะของ Articuno และ Cryogonal ถูกติดด้วยเอฟเฟกต์ Freeze ในโอกาสที่สูงขึ้น",
		name = "Controlling Team",
		specialMarkTitle_th = "Controlling Team",
		matchEffect1_en = "1. Articuno and Cryogonal's skills are attached with Freeze effect at a higher chance",
		features_en = "Team of multiple controls and debuffs: Torture enemies with multiple controls and debuffs",
		desc_en = "Controlling Team",
		specialMarkBg = "city/card/battle_recommend/logo_bs5.png",
		matchEffect4_en = "3. Alakazam can disable targets",
		matchEffect5_th = "5. ความกลัวของ Gengar เป็นผลมาจากการควบคุมและสามารถลดคุณสมบัติของเป้าหมายได้",
		matchEffect5_en = "5. Gengar's fear is effected by controls and can reduce target's attributes",
		features = "Team of multiple controls and debuffs: Torture enemies with multiple controls and debuffs",
		sort = 9993,
		features_th = "ทีมที่มีการควบคุมและดีบัฟหลายแบบ: ทรมานศัตรูด้วยการควบคุมและดีบัฟที่หลากหลาย",
		specialMarkTitle = "Controlling Team",
		haloId = 3,
		coreEffectName_en = "Control Effect",
		matchEffect3 = "3. Mew's ultimate skill can silence targets",
		matchEffect4_th = "3. Alakazam สามารถปิดการใช้งานเป้าหมายได้",
		name_th = "Controlling Team",
		id = 3,
		specialMarkTitle_en = "Controlling Team",
		name_en = "Controlling Team",
		matchEffect5 = "5. Gengar's fear is effected by controls and can reduce target's attributes",
		matchEffect3_en = "3. Mew's ultimate skill can silence targets",
		desc_th = "Controlling Team",
		desc = "Controlling Team",
		coreEffect_en = "Disrupt enemies by Freeze, Silence, Disable, Confuse and other controls",
		matchEffect2 = "2. Ducknoir's Black Hole can confine the target in the black hole to make it unable to attack or being attacked",
		matchEffect2_th = "2. Ducknoir's Black Hole สามารถจำกัดเป้าหมายในหลุมดำให้ไม่สามารถโจมตีหรือถูกโจมตีได้",
		coreEffect_th = "Disrupt enemies by Freeze, Silence, Disable, Confuse and other controls",
		coreEffectName_th = "Control Effect",
		coreEffectName = "Control Effect",
		matchEffect2_en = "2. Ducknoir's Black Hole can confine the target in the black hole to make it unable to attack or being attacked",
		matchEffect4 = "3. Alakazam can disable targets",
		matchEffect1 = "1. Articuno and Cryogonal's skills are attached with Freeze effect at a higher chance",
		matchEffect3_th = "3. สกิลอัลติเมทของมิวสามารถปิดปากเป้าหมายได้",
		coreEffect = "Disrupt enemies by Freeze, Silence, Disable, Confuse and other controls",
		cards = {
			721,
			3021,
			393,
			1813,
			771,
			263
		},
		coreMark = slot1[3]
	},
	{
		matchEffect1_th = "1. Blaziken ให้โบนัสความเสียหายกลุ่ม",
		name = "Single Seckill",
		specialMarkTitle_th = "Single Seckill",
		matchEffect1_en = "1. Blaziken provides group damage bonus",
		features_en = "Single One-Hit Team: Gather the fire to kill a single enemy to be numerically superior",
		desc_en = "Single Seckill",
		specialMarkBg = "city/card/battle_recommend/logo_bs1.png",
		features = "Single One-Hit Team: Gather the fire to kill a single enemy to be numerically superior",
		sort = 9994,
		features_th = "Single One-Hit Team: รวบรวมไฟเพื่อฆ่าศัตรูตัวเดียวให้เหนือกว่าตัวเลข",
		specialMarkTitle = "Single Seckill",
		haloId = 1,
		coreEffectName_en = "Single one-hit",
		matchEffect3 = "3. High single ATK. Can quickly seckill a single enemy to get the superiority in number",
		name_th = "Single Seckill",
		id = 4,
		specialMarkTitle_en = "Single Seckill",
		name_en = "Single Seckill",
		matchEffect3_en = "3. High single ATK. Can quickly seckill a single enemy to get the superiority in number",
		desc_th = "Single Seckill",
		desc = "Single Seckill",
		coreEffect_en = "Use big skills to a single enemy Pokemon and gather the fire to kill a single enemy",
		matchEffect2 = "2. Scyther can quickly seckill Pokemon in the back line with Treecko",
		matchEffect2_th = "2. Scyther สามารถจับ Pokemon ที่ด้านหลังได้อย่างรวดเร็วด้วย Treecko",
		coreEffect_th = "Use big skills to a single enemy Pokemon and gather the fire to kill a single enemy",
		coreEffectName_th = "Single one-hit",
		coreEffectName = "Single one-hit",
		matchEffect2_en = "2. Scyther can quickly seckill Pokemon in the back line with Treecko",
		matchEffect1 = "1. Blaziken provides group damage bonus",
		matchEffect3_th = "3. ATK เดี่ยวสูง สามารถ seckill ศัตรูตัวเดียวได้อย่างรวดเร็วเพื่อรับความเหนือกว่าในจำนวน",
		coreEffect = "Use big skills to a single enemy Pokemon and gather the fire to kill a single enemy",
		cards = {
			1303,
			1423,
			753,
			1071,
			1293,
			572
		},
		coreMark = slot1[4]
	},
	{
		matchEffect1_th = "1. Absol ขโมย HP สูงสุดของเป้าหมาย",
		isRecommend = true,
		matchEffect1_en = "1. Absol steal target's max HP",
		specialMarkTitle_th = "Dark-Type Team",
		matchEffect6_th = "6. Krookodile: ทำให้เป้าหมายตาบอดและทำให้เป้าหมายสามารถรักษาได้",
		name = "Dark-Type Team",
		specialMarkBg = "city/card/battle_recommend/logo_bs3.png",
		matchEffect3_en = "3. Zoroark: Get ATK bonus from the illusion target",
		matchEffect4_en = "4. Houndoom: Steal enemy team's SP.DEF and P.DEF to own team's SP.DEF and P.DEF",
		matchEffect5_th = "5. Weavile: ขโมย P.ATK ของเป้าหมาย",
		matchEffect5_en = "5. Weavile: Steal the target's P.ATK",
		matchEffect6 = "6. Krookodile: Blind targets and make targets uanble to be healed",
		features = "Stealing Team: Steel attributes from enemies and attack in different ways",
		matchEffect6_en = "6. Krookodile: Blind targets and make targets uanble to be healed",
		sort = 9996,
		features_th = "ทีมขโมย: คุณสมบัติเหล็กจากศัตรูและโจมตีในรูปแบบต่างๆ",
		desc_en = "Dark-Type Team",
		specialMarkTitle = "Dark-Type Team",
		haloId = 6,
		coreEffectName_en = "Steal attributes",
		matchEffect3 = "3. Zoroark: Get ATK bonus from the illusion target",
		matchEffect4_th = "4. Houndoom: ขโมย SP.DEF และ P.DEF ของทีมศัตรูมาเป็น SP.DEF และ P.DEF ของทีม",
		name_th = "Dark-Type Team",
		id = 5,
		specialMarkTitle_en = "Dark-Type Team",
		name_en = "Dark-Type Team",
		matchEffect5 = "5. Weavile: Steal the target's P.ATK",
		features_en = "Stealing Team: Steel attributes from enemies and attack in different ways",
		desc_th = "Dark-Type Team",
		desc = "Dark-Type Team",
		coreEffect_en = "There are abilities to steal attributes in skill effects to weaken enemies and strengthen teammates",
		matchEffect2 = "2. Hydreigon can steal target's SP.ATK and P.ATK by multistage attacks",
		matchEffect2_th = "2. Hydreigon สามารถขโมย SP.ATK และ P.ATK ของเป้าหมายด้วยการโจมตีหลายขั้นตอน",
		coreEffect_th = "There are abilities to steal attributes in skill effects to weaken enemies and strengthen teammates",
		coreEffectName_th = "Steal attributes",
		coreEffectName = "Steal attributes",
		matchEffect2_en = "2. Hydreigon can steal target's SP.ATK and P.ATK by multistage attacks",
		matchEffect4 = "4. Houndoom: Steal enemy team's SP.DEF and P.DEF to own team's SP.DEF and P.DEF",
		matchEffect1 = "1. Absol steal target's max HP",
		matchEffect3_th = "3. Zoroark: รับโบนัส ATK จากเป้าหมายภาพลวงตา",
		coreEffect = "There are abilities to steal attributes in skill effects to weaken enemies and strengthen teammates",
		cards = {
			1841,
			3143,
			2723,
			1172,
			1082,
			2822
		},
		coreMark = slot1[5]
	},
	{
		matchEffect1_th = "1. Zapdos และ Ampharos ให้เครื่องหมาย Electrify จำนวนมากและเพิ่ม Rage ของทีม",
		isRecommend = true,
		matchEffect1_en = "1. Zapdos and Ampharos provides a lot of Electrify marks and increase team's Rage",
		specialMarkTitle_th = "Thunderbolt Reaction",
		matchEffect6_th = "6. Metagross: ป้องกันโปเกมอนประเภทไฟฟ้า ตัวเลือกที่ดีที่สุดสำหรับออร่า 4+2",
		name = "Thunderbolt Reaction",
		specialMarkBg = "city/card/battle_recommend/logo_bs5.png",
		matchEffect3_en = "3. Ampharos: Inflict a lot of 【Electrify 】, quickly recover teammates' Rage and increase the speed of team's releasing one-hit skills",
		matchEffect4_en = "4. Electivire attacks with stored electricity. A good Electric-type attacker",
		matchEffect5_th = "5. Magnezone: ระเบิดตัวเองเพื่อสร้างความเสียหายอย่างใหญ่หลวงด้วยเอฟเฟกต์อัมพาต",
		matchEffect5_en = "5. Magnezone: Explode itself to deal a great damage with Paralysis effect",
		matchEffect6 = "6. Metagross: Protect Electric-type Pokemon. The best option for 4+2 aura",
		features = "Advanced Electric-type Enhanced Team: Electrify mark brings multiple buffs. Increase the speed of Rage recovery, the speed of releasing big skills and attach Paralysis effect; Zapdos's 8-star passive skill can make allied Electric-type Pokemon's Rage increased at the beginning of a battle and can use big skills first to be superior",
		matchEffect6_en = "6. Metagross: Protect Electric-type Pokemon. The best option for 4+2 aura",
		sort = 9997,
		features_th = "Advanced Electric-type Enhanced Team: Electrify mark นำบัฟต่างๆ มาให้ เพิ่มความเร็วในการฟื้นฟู Rage, ความเร็วในการปล่อยสกิลใหญ่และติดเอฟเฟกต์ Paralysis; สกิลติดตัว 8 ดาวของ Zapdos จะทำให้โปเกมอนประเภทไฟฟ้าของฝ่ายเดียวกันเพิ่มขึ้นในตอนเริ่มต้น ต่อสู้และใช้ทักษะใหญ่ก่อนเป็นเหนือกว่า",
		desc_en = "Thunderbolt Reaction",
		specialMarkTitle = "Thunderbolt Reaction",
		haloId = 5,
		coreEffectName_en = "Electrify mark",
		matchEffect3 = "3. Ampharos: Inflict a lot of 【Electrify 】, quickly recover teammates' Rage and increase the speed of team's releasing one-hit skills",
		matchEffect4_th = "4. Electivire โจมตีด้วยไฟฟ้าที่สะสมไว้ ผู้โจมตีประเภท Electric ที่ดี",
		name_th = "Thunderbolt Reaction",
		id = 6,
		specialMarkTitle_en = "Thunderbolt Reaction",
		name_en = "Thunderbolt Reaction",
		matchEffect5 = "5. Magnezone: Explode itself to deal a great damage with Paralysis effect",
		features_en = "Advanced Electric-type Enhanced Team: Electrify mark brings multiple buffs. Increase the speed of Rage recovery, the speed of releasing big skills and attach Paralysis effect; Zapdos's 8-star passive skill can make allied Electric-type Pokemon's Rage increased at the beginning of a battle and can use big skills first to be superior",
		desc_th = "Thunderbolt Reaction",
		desc = "Thunderbolt Reaction",
		coreEffect_en = "Electrify deffect: Electrify target's damage to Raikou will be reduced. Ampharos increase the extra Rage recovery to Electrify mark.",
		matchEffect2 = "2. Reduce Raikou's damage taken from Electrify targets, paralyze/ stun targets to control the battle",
		matchEffect2_th = "2. ลดความเสียหายของ Raikou ที่ได้รับจากเป้าหมาย Electrify ทำให้เป้าหมายเป็นอัมพาต/มึนงงเพื่อควบคุมการต่อสู้",
		coreEffect_th = "Electrify deffect: Electrify target's damage to Raikou will be reduced. Ampharos increase the extra Rage recovery to Electrify mark.",
		coreEffectName_th = "Electrify mark",
		coreEffectName = "Electrify mark",
		matchEffect2_en = "2. Reduce Raikou's damage taken from Electrify targets, paralyze/ stun targets to control the battle",
		matchEffect4 = "4. Electivire attacks with stored electricity. A good Electric-type attacker",
		matchEffect1 = "1. Zapdos and Ampharos provides a lot of Electrify marks and increase team's Rage",
		matchEffect3_th = "3. Ampharos: สร้าง 【Electrify 】 จำนวนมาก ฟื้นฟู Rage ของเพื่อนร่วมทีมอย่างรวดเร็ว และเพิ่มความเร็วของการปล่อยสกิล one-hit ของทีม",
		coreEffect = "Electrify deffect: Electrify target's damage to Raikou will be reduced. Ampharos increase the extra Rage recovery to Electrify mark.",
		cards = {
			731,
			1221,
			593,
			883,
			333,
			1903
		},
		coreMark = slot1[6]
	},
	{
		matchEffect1_th = "1. Aggron มอบโล่ให้กับทุกทีมเพื่อเพิ่มระดับรถถังของทีม",
		name = "Counter-attack",
		specialMarkTitle_th = "Counter-attack",
		matchEffect1_en = "1. Aggron provides a shield to all team to increase team's tank level",
		features_en = "Counterattack Team: Defense and store energy to attack",
		matchEffect6_th = "6. Swampert: ค่าคริติคอลสูง มันสามารถกำจัดดีบัฟบางอย่างได้ เมื่อ HP ของมันต่ำ จะได้รับโบนัสภูมิคุ้มกันความเสียหายที่สูงขึ้น",
		specialMarkBg = "city/card/battle_recommend/logo_bs4.png",
		matchEffect4_en = "4. Metagross: Taunt targets (can attack Metagross with one-hit skills in Taunt state). Protect teammates. Store extra Rage to increase the damage of one-hit skills",
		matchEffect5_th = "5. Krookodile: โจมตีพื้นที่ การโจมตีของเป้าหมายในพื้นที่นี้จะพลาด",
		matchEffect6 = "6. Swampert: High Crit Res. It can dispel some debuffs. When its HP is low, it will get a higher damage immunity bonus",
		matchEffect5_en = "5. Krookodile: Attack an area. Attacks of targets in this area will miss",
		matchEffect6_en = "6. Swampert: High Crit Res. It can dispel some debuffs. When its HP is low, it will get a higher damage immunity bonus",
		features = "Counterattack Team: Defense and store energy to attack",
		desc_en = "Counter-attack",
		sort = 9995,
		features_th = "ทีมตอบโต้: ป้องกันและเก็บพลังงานเพื่อโจมตี",
		specialMarkTitle = "Counter-attack",
		haloId = 3,
		coreEffectName_en = "Defense system",
		matchEffect3 = "3. Tyranitar: Immortal and can resist damage. Kill target by counter when its HP is 0",
		matchEffect4_th = "4. Metagross: Taunt เป้าหมาย (สามารถโจมตี Metagross ด้วยสกิล one-hit ในสถานะ Taunt) ปกป้องเพื่อนร่วมทีม เก็บ Rage เพิ่มเติมเพื่อเพิ่มความเสียหายของสกิล one-hit",
		name_th = "Counter-attack",
		id = 7,
		specialMarkTitle_en = "Counter-attack",
		name_en = "Counter-attack",
		matchEffect5 = "5. Krookodile: Attack an area. Attacks of targets in this area will miss",
		matchEffect3_en = "3. Tyranitar: Immortal and can resist damage. Kill target by counter when its HP is 0",
		desc_th = "Counter-attack",
		desc = "Counter-attack",
		coreEffect_en = "Death free, shield, taunt, blind, multiple defense methods",
		matchEffect2 = "2. Rhyperior: It has a very high P.DEF",
		matchEffect2_th = "2. Rhyperior: มี P.DEF . สูงมาก",
		coreEffect_th = "Death free, shield, taunt, blind, multiple defense methods",
		coreEffectName_th = "Defense system",
		coreEffectName = "Defense system",
		matchEffect2_en = "2. Rhyperior: It has a very high P.DEF",
		matchEffect4 = "4. Metagross: Taunt targets (can attack Metagross with one-hit skills in Taunt state). Protect teammates. Store extra Rage to increase the damage of one-hit skills",
		matchEffect1 = "1. Aggron provides a shield to all team to increase team's tank level",
		matchEffect3_th = "3. Tyranitar: อมตะและสามารถต้านทานความเสียหายได้ ฆ่าเป้าหมายโดยตอบโต้เมื่อ HP เป็น 0",
		coreEffect = "Death free, shield, taunt, blind, multiple defense methods",
		cards = {
			1503,
			493,
			1253,
			1903,
			2723,
			1313
		},
		coreMark = slot1[7]
	},
	{
		matchEffect1_th = "1. Aggron: มอบโล่ให้กับทีมเพื่อเพิ่มระดับรถถังของทีม ติดสถานะ Flinch ด้วยทักษะเล็กน้อย",
		name = "Steel-Type Team",
		specialMarkTitle_th = "Player idea",
		matchEffect1_en = "1. Aggron: Provide a shield to team to increase team's tank level. Attach Flinch state with small skills",
		features_en = "Improved Steel-Type Team (inspired by Region 134 of channel server, character: Daye)",
		matchEffect6_th = "6. Aegislash - Shield: เก่ง ATK และ DEF ช่วยเหลือการโจมตีจากด้านหน้าและด้านหลัง",
		specialMarkBg = "city/card/battle_recommend/logo_bs2.png",
		matchEffect4_en = "4. Magnezone: Deal a great Electric-type damage by death",
		matchEffect5_th = "5. Metagross: ปกป้องเพื่อนร่วมทีมและเก็บพลังงานเพื่อระเบิด",
		matchEffect6 = "6. Aegislash - Shield: Good at ATK and DEF. Assist attacks from the front and back",
		matchEffect5_en = "5. Metagross: Protect teammates and store energy to explode",
		matchEffect6_en = "6. Aegislash - Shield: Good at ATK and DEF. Assist attacks from the front and back",
		features = "Improved Steel-Type Team (inspired by Region 134 of channel server, character: Daye)",
		desc_en = "Steel-Type Team",
		sort = 9992,
		features_th = "ปรับปรุงทีม Steel-Type (แรงบันดาลใจจากภูมิภาค 134 ของเซิร์ฟเวอร์ช่อง ตัวละคร: Daye)",
		specialMarkTitle = "Player idea",
		haloId = 6,
		coreEffectName_en = "Steel-Type cooperation",
		matchEffect3 = "3. Scizor: Plunder mark. More action. Absorb attacks. Reaper with low HP",
		matchEffect4_th = "4. Magnezone: สร้างความเสียหายประเภทไฟฟ้าด้วยการตาย",
		name_th = "Steel-Type Team",
		id = 8,
		specialMarkTitle_en = "Player idea",
		name_en = "Steel-Type Team",
		matchEffect5 = "5. Metagross: Protect teammates and store energy to explode",
		matchEffect3_en = "3. Scizor: Plunder mark. More action. Absorb attacks. Reaper with low HP",
		desc_th = "Steel-Type Team",
		desc = "Steel-Type Team",
		coreEffect_en = "Team's shield. Dual war's cooperation. Self explosion. Kill in streak",
		matchEffect2 = "2. Lucario: Attack with P.ATK and SP.ATK. Increase restriction",
		matchEffect2_th = "2. Lucario: โจมตีด้วย P.ATK และ SP.ATK เพิ่มข้อจำกัด",
		coreEffect_th = "Team's shield. Dual war's cooperation. Self explosion. Kill in streak",
		coreEffectName_th = "Steel-Type cooperation",
		coreEffectName = "Steel-Type cooperation",
		matchEffect2_en = "2. Lucario: Attack with P.ATK and SP.ATK. Increase restriction",
		matchEffect4 = "4. Magnezone: Deal a great Electric-type damage by death",
		matchEffect1 = "1. Aggron: Provide a shield to team to increase team's tank level. Attach Flinch state with small skills",
		matchEffect3_th = "3. Scizor : Plunder mark แอคชั่นมากกว่า ดูดซับการโจมตี Reaper ด้วย HP ต่ำ",
		coreEffect = "Team's shield. Dual war's cooperation. Self explosion. Kill in streak",
		cards = {
			1503,
			2242,
			572,
			333,
			1903,
			3413
		},
		coreMark = slot1[8]
	},
	{
		matchEffect1_th = "1. Regice: Ice-core Resistance ฟื้น HP ของ Pokemon ประเภท Ice",
		name = "Ice Control",
		specialMarkTitle_th = "Player idea",
		matchEffect1_en = "1. Regice: Ice-core Resistance. Recover Ice-type Pokemon's HP",
		features_en = "Advanced Ice-Type Team: Ice controls, icy traps, ice-core protection; good at controller, tank, attacker and assistant roles (inspired by Region 596 of channel server, character: Qifengle)",
		desc_en = "Ice Control",
		specialMarkBg = "city/card/battle_recommend/logo_bs2.png",
		matchEffect4_en = "4. Abomasnow: Increase all Pokemon's freezing rate",
		matchEffect5_th = "5. Amaura: เสริมความแข็งแกร่งให้กับเกราะทั้งหมดในทีมประเภทน้ำแข็ง",
		matchEffect5_en = "5. Amaura: Strengthen all shields in Ice-type team",
		features = "Advanced Ice-Type Team: Ice controls, icy traps, ice-core protection; good at controller, tank, attacker and assistant roles (inspired by Region 596 of channel server, character: Qifengle)",
		sort = 9990,
		features_th = "ทีม Ice-Type ขั้นสูง: การควบคุมน้ำแข็ง กับดักน้ำแข็ง การป้องกันแกนน้ำแข็ง ดีที่บทบาทคอนโทรลเลอร์ รถถัง ผู้โจมตี และผู้ช่วย (ได้รับแรงบันดาลใจจากภูมิภาค 596 ของเซิร์ฟเวอร์ช่อง ตัวละคร: Qifengle)",
		specialMarkTitle = "Player idea",
		haloId = 6,
		coreEffectName_en = "Ice Control",
		matchEffect3 = "3. Weavile: Icy traps strengthen control effects",
		matchEffect4_th = "4. Abomasnow: เพิ่มอัตราการแช่แข็งของโปเกมอนทั้งหมด",
		name_th = "Ice Control",
		id = 9,
		specialMarkTitle_en = "Player idea",
		name_en = "Ice Control",
		matchEffect5 = "5. Amaura: Strengthen all shields in Ice-type team",
		matchEffect3_en = "3. Weavile: Icy traps strengthen control effects",
		desc_th = "Ice Control",
		desc = "Ice Control",
		coreEffect_en = "Ice Control",
		matchEffect2 = "2. Articuno and Cryogonal's skills are attached with Freeze effect at a higher chance",
		matchEffect2_th = "2. ทักษะของ Articuno และ Cryogonal ถูกติดด้วยเอฟเฟกต์ Freeze ในโอกาสที่สูงขึ้น",
		coreEffect_th = "Ice Control",
		coreEffectName_th = "Ice Control",
		coreEffectName = "Ice Control",
		matchEffect2_en = "2. Articuno and Cryogonal's skills are attached with Freeze effect at a higher chance",
		matchEffect4 = "4. Abomasnow: Increase all Pokemon's freezing rate",
		matchEffect1 = "1. Regice: Ice-core Resistance. Recover Ice-type Pokemon's HP",
		matchEffect3_th = "3. Weavile: กับดักน้ำแข็งเสริมเอฟเฟกต์การควบคุม",
		coreEffect = "Ice Control",
		cards = {
			1921,
			721,
			3021,
			1082,
			2302,
			3502
		},
		coreMark = slot1[9]
	},
	{
		matchEffect1_th = "1. Goodra: เพิ่ม SP.DEF ของเพื่อนร่วมทีมและ Crit Res . ของเพื่อนร่วมทีม",
		name = "Dragon-Type Team",
		specialMarkTitle_th = "Player idea",
		matchEffect1_en = "1. Goodra: Increase team-mates' SP.DEF and own Crit Res",
		features_en = "Improved Dragon-Type Pokemon: 1 tank, 4 attackers and 1 assistants can make up a nearly perfect configuration. Each Dragon-type Pokemon is good at carrying and can restrict shield teams (inspired by Region 15 of official server, character: Doulimeitang)",
		matchEffect6_th = "6. นอยเวิร์น: รบกวนด้วยคลื่นเสียง เจาะเกราะ ช่วยทีม",
		specialMarkBg = "city/card/battle_recommend/logo_bs2.png",
		matchEffect4_en = "4. Haxorus: Pursue and attack. Damage increased. A good reaper",
		matchEffect5_th = "5. Dragonite: สร้างดีบัฟเพื่อเพิ่มความเสียหาย โจมตี All-power มอบดีบัฟที่แตกต่างกันให้กับทีม Dragon-Type",
		matchEffect6 = "6. Noivern: Disturb with sonic waves. Penetrate shield. Assist team",
		matchEffect5_en = "5. Dragonite: Inflict debuffs to increase damage. All-power attacker. Provide different debuffs to Dragon-Type Team.",
		matchEffect6_en = "6. Noivern: Disturb with sonic waves. Penetrate shield. Assist team",
		features = "Improved Dragon-Type Pokemon: 1 tank, 4 attackers and 1 assistants can make up a nearly perfect configuration. Each Dragon-type Pokemon is good at carrying and can restrict shield teams (inspired by Region 15 of official server, character: Doulimeitang)",
		desc_en = "Dragon-Type Team",
		sort = 9989,
		features_th = "โปเกมอนประเภทมังกรที่ได้รับการปรับปรุง: รถถัง 1 คัน ผู้โจมตี 4 คน และผู้ช่วย 1 คน สามารถสร้างรูปแบบที่เกือบจะสมบูรณ์แบบ โปเกมอนประเภทมังกรแต่ละตัวนั้นเก่งในการพกพาและสามารถจำกัดทีมเกราะได้ (ได้รับแรงบันดาลใจจากภูมิภาค 15 ของเซิร์ฟเวอร์อย่างเป็นทางการ ตัวละคร: Doulimeitang)",
		specialMarkTitle = "Player idea",
		haloId = 6,
		coreEffectName_en = "Dragon-Type Power",
		matchEffect3 = "3. Garchomp: Be violent when its HP is low. Crit can happen with true damage. A higher ATK",
		matchEffect4_th = "4. Haxorus: ไล่ตามและโจมตี ความเสียหายเพิ่มขึ้น ยมทูตที่ดี",
		name_th = "Dragon-Type Team",
		id = 10,
		specialMarkTitle_en = "Player idea",
		name_en = "Dragon-Type Team",
		matchEffect5 = "5. Dragonite: Inflict debuffs to increase damage. All-power attacker. Provide different debuffs to Dragon-Type Team.",
		matchEffect3_en = "3. Garchomp: Be violent when its HP is low. Crit can happen with true damage. A higher ATK",
		desc_th = "Dragon-Type Team",
		desc = "Dragon-Type Team",
		coreEffect_en = "Violent ATK. Restrict shields",
		matchEffect2 = "2. Salamence: Deal Tear damage. Disable being healed and its damage can penetrate shields.",
		matchEffect2_th = "2. Salamence: สร้างความเสียหาย Tear ปิดใช้งานการฮีลและความเสียหายของมันสามารถเจาะเกราะได้",
		coreEffect_th = "Violent ATK. Restrict shields",
		coreEffectName_th = "Dragon-Type Power",
		coreEffectName = "Dragon-Type Power",
		matchEffect2_en = "2. Salamence: Deal Tear damage. Disable being healed and its damage can penetrate shields.",
		matchEffect4 = "4. Haxorus: Pursue and attack. Damage increased. A good reaper",
		matchEffect1 = "1. Goodra: Increase team-mates' SP.DEF and own Crit Res",
		matchEffect3_th = "3. Garchomp: ใช้ความรุนแรงเมื่อ HP ต่ำ Crit สามารถเกิดขึ้นได้ด้วยความเสียหายจริง ATK . ที่สูงขึ้น",
		coreEffect = "Violent ATK. Restrict shields",
		cards = {
			3543,
			1893,
			2233,
			3003,
			753,
			3592
		},
		coreMark = slot1[10]
	},
	{
		matchEffect1_th = "1. ผู้ควบคุม: Articuno + Snowflake เมื่อเปิดใช้งานทักษะระดับ 8 ดาว Articuno สามารถเพิ่มอัตราการควบคุมเกล็ดหิมะและสร้างความเสียหาย 55% ที่จำเป็น (เพิ่มขึ้นจาก 35%) เพื่อทำลายสถานะการแช่แข็ง",
		name = "Controlling Defense",
		specialMarkTitle_th = "Player idea",
		matchEffect1_en = "1. Controller: Articuno + Snowflake. When 8-star skills are activated, Articuno can increase the rate of controlling snowflakes and 55% damage needed (increased from 35%) to break Freeze state",
		features_en = "Defense + High Controlling team with an outstanding endurance and control ability (inspired by Region 2 of official server, character: Shanlei)",
		desc_en = "Controlling Defense",
		specialMarkBg = "city/card/battle_recommend/logo_bs2.png",
		matchEffect4_en = "4. Lugia protects teammates, becomes immortal itself and improves team's tank level",
		matchEffect5_th = "5. เมื่อเปิดใช้งานทักษะระดับดาว อัตราการควบคุมประเภทน้ำแข็งจะสูงขึ้น แนะนำให้ใช้ Snowflake และ Coco เป็นกำลังหลัก และใช้ Articuno เพื่อเพิ่มอัตราการควบคุม ใช้ Sneasel เป็นผู้โจมตี Lugia สามารถถูกแทนที่ด้วย Flying- อื่น พิมพ์โปเกมอนเพื่อการเปลี่ยนแปลง",
		matchEffect5_en = "5. When star level skills are activated, Ice-type control rate will be higher. It's recommended use Snowflake and Coco as the main force, and use Articuno to increase control rate. Use Sneasel as attacker. Lugia can be replaced by other Flying-type Pokemon for transition",
		features = "Defense + High Controlling team with an outstanding endurance and control ability (inspired by Region 2 of official server, character: Shanlei)",
		sort = 9988,
		features_th = "ทีมป้องกัน + การควบคุมสูงที่มีความอดทนและความสามารถในการควบคุมที่โดดเด่น (ได้รับแรงบันดาลใจจากภูมิภาคที่ 2 ของเซิร์ฟเวอร์อย่างเป็นทางการ ตัวละคร: Shanlei)",
		specialMarkTitle = "Player idea",
		haloId = 3,
		coreEffectName_en = "Defense Control",
		matchEffect3 = "3. Sword & Shield can resist damage for teammates and attack with teammates",
		matchEffect4_th = "4. Lugia ปกป้องเพื่อนร่วมทีม กลายเป็นอมตะ และปรับปรุงระดับรถถังของทีม",
		name_th = "Controlling Defense",
		id = 11,
		specialMarkTitle_en = "Player idea",
		name_en = "Controlling Defense",
		matchEffect5 = "5. When star level skills are activated, Ice-type control rate will be higher. It's recommended use Snowflake and Coco as the main force, and use Articuno to increase control rate. Use Sneasel as attacker. Lugia can be replaced by other Flying-type Pokemon for transition",
		matchEffect3_en = "3. Sword & Shield can resist damage for teammates and attack with teammates",
		desc_th = "Controlling Defense",
		desc = "Controlling Defense",
		coreEffect_en = "Counterattack and control consumption",
		matchEffect2 = "2. Attacker: When Weavile is frozen by enemies, its ATK will be maximized",
		matchEffect2_th = "2. ผู้โจมตี: เมื่อ Weavile ถูกแช่แข็งโดยศัตรู พลังโจมตีของ Weavile จะเพิ่มขึ้นสูงสุด",
		coreEffect_th = "Counterattack and control consumption",
		coreEffectName_th = "Defense Control",
		coreEffectName = "Defense Control",
		matchEffect2_en = "2. Attacker: When Weavile is frozen by enemies, its ATK will be maximized",
		matchEffect4 = "4. Lugia protects teammates, becomes immortal itself and improves team's tank level",
		matchEffect1 = "1. Controller: Articuno + Snowflake. When 8-star skills are activated, Articuno can increase the rate of controlling snowflakes and 55% damage needed (increased from 35%) to break Freeze state",
		matchEffect3_th = "3. Sword & Shield สามารถต้านทานความเสียหายของเพื่อนร่วมทีมและโจมตีเพื่อนร่วมทีมได้",
		coreEffect = "Counterattack and control consumption",
		cards = {
			1503,
			1261,
			721,
			1082,
			3021,
			3413
		},
		coreMark = slot1[11]
	},
	{
		matchEffect1_th = "1. แนวหน้า: Suicune, Aegislash, Blaziken; แนวรับ: Lucario, Greninja, Scizor",
		name = "Assassins Alliance",
		specialMarkTitle_th = "Player idea",
		matchEffect1_en = "1. Front line: Suicune, Aegislash, Blaziken; Back line: Lucario, Greninja, Scizor",
		features_en = "Improved Assassin Alliance (inspired by Region 2 of official server, character: Qingshan). This team is focused on continuity. We will explain this team by the player's words",
		desc_en = "Assassins Alliance",
		specialMarkBg = "city/card/battle_recommend/logo_bs2.png",
		matchEffect4_en = "4. Aegislash can perfectly integrate into this team after skills are updated. Its SP.ATK and P.ATK will be increased in sword state and its Res will be increased in shield state. In sword state, small skills can increase 20% P.ATK and SP.ATK of Pokemon in back line (Scizor is laughing); In shield state, increase Res of Pokemon in front line to ensure killing emeries after a series of attacks. Big skills in shield state can increase the speed of team (Scizor is laughing again)",
		matchEffect5_th = "5. Scizor: เมื่อสกิลติดตัวของมันฆ่าโปเกมอนตัวใด ๆ ก็สามารถแสดงได้อีกครั้ง ด้วยเอฟเฟกต์ของโล่และทักษะติดตัวของ Blaziken มันสามารถหลอกได้เกือบทุกคน",
		matchEffect5_en = "5. Scizor: When its passive skills kill any Pokemon, it can act one more time. With the effect of shield and Blaziken's passive skills, it can seckill almost everyone",
		features = "Improved Assassin Alliance (inspired by Region 2 of official server, character: Qingshan). This team is focused on continuity. We will explain this team by the player's words",
		sort = 9987,
		features_th = "ปรับปรุง Assassin Alliance (ได้รับแรงบันดาลใจจากภูมิภาค 2 ของเซิร์ฟเวอร์อย่างเป็นทางการ ตัวละคร: Qingshan) ทีมนี้เน้นที่ความต่อเนื่อง เราจะอธิบายทีมนี้ด้วยคำพูดของผู้เล่น",
		specialMarkTitle = "Player idea",
		haloId = 2,
		coreEffectName_en = "Cooperation",
		matchEffect3 = "3. Blaziken's passive aura increases team's ATK and it can deal a great damage as well.",
		matchEffect4_th = "4. Aegislash สามารถรวมเข้ากับทีมนี้ได้อย่างสมบูรณ์แบบหลังจากอัปเดตทักษะแล้ว SP.ATK และ P.ATK ของมันจะเพิ่มขึ้นในสถานะดาบและ Res ของมันจะเพิ่มขึ้นในสถานะโล่ ในสถานะดาบ ทักษะเล็กน้อยสามารถเพิ่ม 20% P ATK และ SP. ATK ของโปเกมอนในแนวหลัง (Scizor กำลังหัวเราะ) ในสถานะโล่ เพิ่ม Res ของโปเกมอนในแนวหน้าเพื่อให้แน่ใจว่าจะฆ่า Emeries หลังจากการโจมตีเป็นชุด ทักษะที่ยิ่งใหญ่ในสถานะโล่สามารถเพิ่มความเร็วของทีมได้ (Scizor กำลังหัวเราะอีกครั้ง)",
		name_th = "Assassins Alliance",
		id = 12,
		specialMarkTitle_en = "Player idea",
		name_en = "Assassins Alliance",
		matchEffect5 = "5. Scizor: When its passive skills kill any Pokemon, it can act one more time. With the effect of shield and Blaziken's passive skills, it can seckill almost everyone",
		matchEffect3_en = "3. Blaziken's passive aura increases team's ATK and it can deal a great damage as well.",
		desc_th = "Assassins Alliance",
		desc = "Assassins Alliance",
		coreEffect_en = "Assassin Alliance, reap first and knock down one by one",
		matchEffect2 = "2. We use Suicune in the front line, because its speed up aura can make us act first to kill ",
		matchEffect2_th = "2. เราใช้ Suicune ในแนวหน้า เพราะการเร่งความเร็วของออร่าสามารถทำให้เราลงมือก่อนเพื่อฆ่าได้",
		coreEffect_th = "Assassin Alliance, reap first and knock down one by one",
		coreEffectName_th = "Cooperation",
		coreEffectName = "Cooperation",
		matchEffect2_en = "2. We use Suicune in the front line, because its speed up aura can make us act first to kill ",
		matchEffect4 = "4. Aegislash can perfectly integrate into this team after skills are updated. Its SP.ATK and P.ATK will be increased in sword state and its Res will be increased in shield state. In sword state, small skills can increase 20% P.ATK and SP.ATK of Pokemon in back line (Scizor is laughing); In shield state, increase Res of Pokemon in front line to ensure killing emeries after a series of attacks. Big skills in shield state can increase the speed of team (Scizor is laughing again)",
		matchEffect1 = "1. Front line: Suicune, Aegislash, Blaziken; Back line: Lucario, Greninja, Scizor",
		matchEffect3_th = "3. ออร่าแบบพาสซีฟของ Blaziken เพิ่ม ATK ของทีมและสามารถสร้างความเสียหายได้มากเช่นกัน",
		coreEffect = "Assassin Alliance, reap first and knock down one by one",
		cards = {
			3303,
			1241,
			572,
			1303,
			3413,
			2242
		},
		coreMark = slot1[12]
	},
	__size = 12,
	__default = {
		__index = {
			matchEffect1_th = "",
			name = "",
			isRecommend = false,
			matchEffect1_en = "",
			specialMarkBg = "",
			matchEffect6_th = "",
			coreEffectName_en = "",
			matchEffect4_en = "",
			matchEffect5_th = "",
			matchEffect6 = "",
			matchEffect5_en = "",
			matchEffect6_en = "",
			features = "",
			features_en = "",
			sort = 0,
			features_th = "",
			haloId = 0,
			desc_en = "",
			matchEffect3 = "",
			matchEffect4_th = "",
			name_th = "",
			name_en = "",
			matchEffect5 = "",
			matchEffect3_en = "",
			desc_th = "",
			desc = "",
			coreEffect_en = "",
			matchEffect2 = "",
			matchEffect2_th = "",
			coreEffect_th = "",
			yyhuodongID = 0,
			coreEffectName_th = "",
			coreEffectName = "",
			matchEffect2_en = "",
			matchEffect4 = "",
			matchEffect1 = "",
			matchEffect3_th = "",
			coreEffect = "",
			cards = {}
		}
	}
}

return csv.card_battle_recommend
