slot0 = {
	__size = 12,
	[3] = {
		gold = 10000,
		rmb = 20,
		__size = 2
	},
	[4] = {
		5000,
		"gold"
	},
	[5] = {
		"coin1"
	},
	[6] = {
		"gold",
		12,
		13,
		602,
		603
	},
	[8] = {
		"coin3"
	},
	[9] = {
		"coin6"
	},
	[10] = {
		"talent_point"
	},
	[11] = {
		"role_exp",
		453,
		19
	},
	[14] = {
		525,
		524,
		523
	},
	[15] = {
		2101,
		2102,
		2103,
		5000
	},
	[16] = {
		"coin4"
	},
	[17] = {
		529
	}
}
slot1 = {
	slot0[4],
	slot0[4],
	[24] = slot0[14],
	[25] = slot0[15],
	[26] = slot0[15],
	[27] = slot0[16],
	[23] = slot0[14],
	[28] = slot0[16],
	[3] = slot0[5],
	[5] = slot0[6],
	[4] = slot0[5],
	[6] = slot0[6],
	[9] = slot0[8],
	[11] = slot0[9],
	[10] = slot0[8],
	[13] = slot0[10],
	[12] = slot0[9],
	[15] = slot0[11],
	[14] = slot0[10],
	[16] = slot0[11],
	[32] = slot0[17],
	[31] = slot0[17]
}
slot2 = {
	slot0[3],
	slot0[3],
	[24] = slot0[3],
	[25] = slot0[3],
	[26] = slot0[3],
	[27] = slot0[3],
	[21] = slot0[3],
	[22] = slot0[3],
	[23] = slot0[3],
	[28] = slot0[3],
	[29] = slot0[3],
	[40] = slot0[3],
	[41] = slot0[3],
	[3] = slot0[3],
	[5] = slot0[3],
	[4] = slot0[3],
	[7] = slot0[3],
	[6] = slot0[3],
	[9] = slot0[3],
	[39] = slot0[3],
	[38] = slot0[3],
	[11] = slot0[3],
	[10] = slot0[3],
	[13] = slot0[3],
	[12] = slot0[3],
	[15] = slot0[3],
	[14] = slot0[3],
	[17] = slot0[3],
	[16] = slot0[3],
	[19] = slot0[3],
	[18] = slot0[3],
	[31] = slot0[3],
	[30] = slot0[3],
	[36] = slot0[3],
	[35] = slot0[3],
	[33] = slot0[3],
	[32] = slot0[3]
}
csv.grow_guide = {
	{
		desc_th = "โหมดความยากใหม่ ความท้าทายใหม่ข้างหน้า",
		name = "Hard level",
		name_en = "Hard level",
		goto = "20000",
		desc_en = "New difficulty modes, new challenges ahead",
		desc = "New difficulty modes, new challenges ahead",
		feature = "heroGate",
		res = "config/grow_guide/hard.jpg",
		name_th = "ระดับยาก",
		id = 1,
		icon = "city/levelup/icon_gq_rk@.png",
		award = slot2[1],
		items = slot1[1]
	},
	{
		taskDesc = "Challenge Hard levels 50 times",
		name = "Hard level",
		type = 2,
		name_en = "Hard level",
		desc_th = "โหมดความยากใหม่ ความท้าทายใหม่ข้างหน้า",
		taskDesc_th = "ท้าทายระดับยาก 50 ครั้ง",
		desc = "New difficulty modes, new challenges ahead",
		goto = "20000",
		taskParam = 50,
		icon = "city/levelup/icon_gq_rk@.png",
		desc_en = "New difficulty modes, new challenges ahead",
		taskType = 30,
		feature = "heroGate",
		res = "config/grow_guide/hard.jpg",
		name_th = "ระดับยาก",
		id = 2,
		taskDesc_en = "Challenge Hard levels 50 times",
		award = slot2[2],
		items = slot1[2]
	},
	{
		desc_th = "คู่แข่งมาเผชิญหน้ากันและผู้ชนะก็ปรากฎตัว",
		name = "Arena",
		name_en = "Arena",
		goto = "arena",
		desc_en = "Rivals meet on face to face and the winner emerges",
		desc = "Rivals meet on face to face and the winner emerges",
		feature = "arena",
		res = "config/grow_guide/arena.jpg",
		name_th = "สังเวียน",
		id = 3,
		icon = "city/levelup/ico_activity.png",
		award = slot2[3],
		items = slot1[3]
	},
	{
		taskDesc = "Attempt Arena Challenge 20 times",
		name = "Arena",
		type = 2,
		name_en = "Arena",
		desc_th = "คู่แข่งมาเผชิญหน้ากันและผู้ชนะก็ปรากฎตัว",
		taskDesc_th = "พยายามท้าทายอารีน่า 20 ครั้ง",
		desc = "Rivals meet on face to face and the winner emerges",
		goto = "arena",
		taskParam = 20,
		icon = "city/levelup/ico_activity.png",
		desc_en = "Rivals meet on face to face and the winner emerges",
		taskType = 41,
		feature = "arena",
		res = "config/grow_guide/arena.jpg",
		name_th = "สังเวียน",
		id = 4,
		taskDesc_en = "Attempt Arena Challenge 20 times",
		award = slot2[4],
		items = slot1[4]
	},
	{
		desc_th = "เคลียร์ความท้าทายได้อย่างง่ายดายและรับรางวัลมากมาย",
		name = "Daily Dungeon",
		name_en = "Daily Dungeon",
		goto = "activityGate",
		desc_en = "Clear challenges easily and get lots of rewards",
		desc = "Clear challenges easily and get lots of rewards",
		feature = "activityGate",
		res = "config/grow_guide/daily.jpg",
		name_th = "ดันเจี้ยนรายวัน",
		id = 5,
		icon = "city/levelup/icon_mx_rk@.png",
		award = slot2[5],
		items = slot1[5]
	},
	{
		taskDesc = "Clear Daily Dungeon 10 times",
		name = "Daily Dungeon",
		type = 2,
		name_en = "Daily Dungeon",
		desc_th = "เคลียร์ความท้าทายได้อย่างง่ายดายและรับรางวัลมากมาย",
		taskDesc_th = "เคลียร์ดันเจี้ยนรายวัน 10 ครั้ง",
		desc = "Clear challenges easily and get lots of rewards",
		goto = "activityGate",
		taskParam = 10,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Clear challenges easily and get lots of rewards",
		taskType = 32,
		feature = "activityGate",
		res = "config/grow_guide/daily.jpg",
		name_th = "ดันเจี้ยนรายวัน",
		id = 6,
		taskDesc_en = "Clear Daily Dungeon 10 times",
		award = slot2[6],
		items = slot1[6]
	},
	{
		desc_th = "ไปข้างหน้าและเริ่มต้นการเดินทางที่ไม่มีที่สิ้นสุด",
		name = "Adventure Road",
		name_en = "Adventure Road",
		goto = "endlessTower",
		desc_en = "Go forward and begin the endless journey",
		desc = "Go forward and begin the endless journey",
		feature = "endlessTower",
		res = "config/grow_guide/endless.jpg",
		name_th = "ถนนนักผจญภัย",
		id = 7,
		icon = "city/levelup/icon_mx_rk@.png",
		award = slot2[7],
		items = {
			451,
			452,
			19,
			"gold"
		}
	},
	__size = 37,
	[9] = {
		desc_th = "เข้าร่วมสหภาพและค้นหาสหายที่มีใจเดียวกัน",
		name = "union",
		name_en = "union",
		goto = "union",
		desc_en = "Join a union and find like-minded companions",
		desc = "Join a union and find like-minded companions",
		feature = "union",
		res = "config/grow_guide/union.jpg",
		name_th = "สหภาพ",
		id = 9,
		icon = "city/levelup/icon_gh_rk@.png",
		award = slot2[9],
		items = slot1[9]
	},
	[10] = {
		taskDesc = "Make donation to the union 10 times",
		name = "union",
		type = 2,
		name_en = "union",
		desc_th = "เข้าร่วมสหภาพและค้นหาสหายที่มีใจเดียวกัน",
		taskDesc_th = "บริจาคเงินให้สหภาพฯ 10 ครั้ง",
		desc = "Join a union and find like-minded companions",
		goto = "union",
		taskParam = 10,
		icon = "city/levelup/icon_gh_rk@.png",
		desc_en = "Join a union and find like-minded companions",
		taskType = 55,
		feature = "union",
		res = "config/grow_guide/union.jpg",
		name_th = "สหภาพ",
		id = 10,
		taskDesc_en = "Make donation to the union 10 times",
		award = slot2[10],
		items = slot1[10]
	},
	[11] = {
		desc_th = "แข่งขันเพื่อเป็นเทรนเนอร์ที่ดีที่สุด",
		name = "Indigo Plateau Conference",
		name_en = "Indigo Plateau Conference",
		goto = "craft",
		desc_en = "Compete to be the best trainer",
		desc = "Compete to be the best trainer",
		feature = "craft",
		res = "config/grow_guide/sydh.jpg",
		name_th = "Indigo Plateau Conference",
		id = 11,
		icon = "city/levelup/ico_activity.png",
		award = slot2[11],
		items = slot1[11]
	},
	[12] = {
		taskDesc = "Manually participate in Indigo Plataeu Conference 5 times",
		name = "Indigo Plateau Conference",
		type = 2,
		name_en = "Indigo Plateau Conference",
		desc_th = "แข่งขันเพื่อเป็นเทรนเนอร์ที่ดีที่สุด",
		taskDesc_th = "เข้าร่วมการประชุม Indigo Plataeu ด้วยตนเอง 5 ครั้ง",
		desc = "Compete to be the best trainer",
		goto = "craft",
		taskParam = 5,
		icon = "city/levelup/ico_activity.png",
		desc_en = "Compete to be the best trainer",
		taskType = 102,
		feature = "craft",
		res = "config/grow_guide/sydh.jpg",
		name_th = "Indigo Plateau Conference",
		id = 12,
		taskDesc_en = "Manually participate in Indigo Plataeu Conference 5 times",
		award = slot2[12],
		items = slot1[12]
	},
	[13] = {
		desc_th = "การปรับปรุงสำหรับทุกคนและแข็งแกร่งขึ้น",
		name = "Talent enhancement",
		name_en = "Talent enhancement",
		goto = "talent",
		desc_en = "Enhancements for all and become stronger",
		desc = "Enhancements for all and become stronger",
		feature = "talent",
		res = "config/grow_guide/talent.jpg",
		name_th = "Talent enhancement",
		id = 13,
		icon = "city/levelup/icon_tf_rk@.png",
		award = slot2[13],
		items = slot1[13]
	},
	[14] = {
		taskDesc = "Use 50 Talent points in total",
		name = "Talent enhancement",
		type = 2,
		name_en = "Talent enhancement",
		desc_th = "การปรับปรุงสำหรับทุกคนและแข็งแกร่งขึ้น",
		taskDesc_th = "ใช้แต้มความสามารถทั้งหมด 50 แต้ม",
		desc = "Enhancements for all and become stronger",
		goto = "talent",
		taskParam = 50,
		icon = "city/levelup/icon_tf_rk@.png",
		desc_en = "Enhancements for all and become stronger",
		taskType = 99,
		feature = "talent",
		res = "config/grow_guide/talent.jpg",
		name_th = "Talent enhancement",
		id = 14,
		taskDesc_en = "Use 50 Talent points in total",
		award = slot2[14],
		items = slot1[14]
	},
	[15] = {
		desc_th = "ก้าวเล็กๆ พาเราไปในที่ห่างไกล",
		name = "Daily quest",
		name_en = "Daily quest",
		goto = "task",
		desc_en = "Small steps get us to faraway places",
		desc = "Small steps get us to faraway places",
		feature = "dailyTask",
		res = "config/grow_guide/task.jpg",
		name_th = "Daily quest",
		id = 15,
		icon = "city/levelup/icon_rw_rk@.png",
		award = slot2[15],
		items = slot1[15]
	},
	[16] = {
		taskDesc = "Complete 20 daily quests",
		name = "Daily quest",
		type = 2,
		name_en = "Daily quest",
		desc_th = "ก้าวเล็กๆ พาเราไปในที่ห่างไกล",
		taskDesc_th = "ทำภารกิจรายวันให้สำเร็จ 20 ภารกิจ",
		desc = "Small steps get us to faraway places",
		goto = "task",
		taskParam = 20,
		icon = "city/levelup/icon_rw_rk@.png",
		desc_en = "Small steps get us to faraway places",
		taskType = 70,
		feature = "dailyTask",
		res = "config/grow_guide/task.jpg",
		name_th = "Daily quest",
		id = 16,
		taskDesc_en = "Complete 20 daily quests",
		award = slot2[16],
		items = slot1[16]
	},
	[17] = {
		desc_th = "อย่ากลัวความมืดและยอมรับความท้าทาย",
		name = "Nightmare levels",
		name_en = "Nightmare levels",
		desc_en = "Fear no darkness and accept the challenge",
		goto = "30000",
		desc = "Fear no darkness and accept the challenge",
		feature = "nightmareGate",
		res = "config/grow_guide/nightmare.jpg",
		name_th = "Nightmare levels",
		id = 17,
		icon = "city/levelup/icon_gq_rk@.png",
		award = slot2[17]
	},
	[18] = {
		taskDesc = "Clear Nightmare Dungeon 5 times",
		name = "Nightmare levels",
		type = 2,
		name_en = "Nightmare levels",
		desc_th = "อย่ากลัวความมืดและยอมรับความท้าทาย",
		goto = "30000",
		taskDesc_th = "เคลียร์ Nightmare Dungeon 5 ครั้ง",
		desc = "Fear no darkness and accept the challenge",
		taskParam = 5,
		icon = "city/levelup/icon_gq_rk@.png",
		desc_en = "Fear no darkness and accept the challenge",
		taskType = 31,
		feature = "nightmareGate",
		res = "config/grow_guide/nightmare.jpg",
		name_th = "Nightmare levels",
		id = 18,
		taskDesc_en = "Clear Nightmare Dungeon 5 times",
		award = slot2[18]
	},
	[19] = {
		desc_th = "รวบรวมโปเกมอนและปลดปล่อยพลัง",
		name = "Pokédex",
		name_en = "Pokédex",
		desc_en = "Collect Pokémons and unleash powers",
		goto = "handbook",
		desc = "Collect Pokémons and unleash powers",
		feature = "handbook",
		res = "config/grow_guide/handbook.jpg",
		name_th = "Pokédex",
		id = 19,
		icon = "city/levelup/icon_tj_rk@.png",
		award = slot2[19]
	},
	[21] = {
		desc_th = "สุ่มความท้าทายเพื่อความสนุกและความประหลาดใจที่มากขึ้น",
		name = "Aether Paradise",
		name_en = "Aether Paradise",
		goto = "randomTower",
		desc_en = "Random challenge for more fun and surprises",
		desc = "Random challenge for more fun and surprises",
		feature = "randomTower",
		res = "config/grow_guide/randomtower.jpg",
		name_th = "Aether Paradise",
		id = 21,
		icon = "city/levelup/icon_mx_rk@.png",
		award = slot2[21],
		items = {
			"coin2",
			4000
		}
	},
	[22] = {
		taskDesc = "Win Aether Paradise Challenge 20 times",
		name = "Aether Paradise",
		type = 2,
		name_en = "Aether Paradise",
		desc_th = "สุ่มความท้าทายเพื่อความสนุกและความประหลาดใจที่มากขึ้น",
		taskDesc_th = "รับรางวัล Aether Paradise Challenge 20 ครั้ง",
		desc = "Random challenge for more fun and surprises",
		goto = "randomTower",
		taskParam = 20,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Random challenge for more fun and surprises",
		taskType = 100,
		feature = "randomTower",
		res = "config/grow_guide/randomtower.jpg",
		name_th = "Aether Paradise",
		id = 22,
		taskDesc_en = "Win Aether Paradise Challenge 20 times",
		award = slot2[22],
		items = {
			"coin2"
		}
	},
	[23] = {
		desc_th = "ค้นหา & จับ",
		name = "Catch Pokémons",
		name_en = "Catch Pokémons",
		goto = "capture",
		desc_en = "Find & Catch",
		desc = "Find & Catch",
		feature = "limitCapture",
		res = "config/grow_guide/capture.jpg",
		name_th = "Catch Pokémons",
		id = 23,
		icon = "city/levelup/icon_jl_rk@.png",
		award = slot2[23],
		items = slot1[23]
	},
	[24] = {
		taskDesc = "Capture 5 Pokémons",
		name = "Catch Pokémons",
		type = 2,
		name_en = "Catch Pokémons",
		desc_th = "ค้นหา & จับ",
		taskDesc_th = "จับโปเกมอน 5 ตัว",
		desc = "Find & Catch",
		taskParam = 5,
		icon = "city/levelup/icon_jl_rk@.png",
		desc_en = "Find & Catch",
		taskType = 81,
		feature = "limitCapture",
		res = "config/grow_guide/capture.jpg",
		name_th = "Catch Pokémons",
		id = 24,
		taskDesc_en = "Capture 5 Pokémons",
		award = slot2[24],
		items = slot1[24]
	},
	[25] = {
		desc_th = "ส่งโปเกมอนเพื่อรับรางวัลมากมาย",
		name = "Dispatch quest",
		name_en = "Dispatch quest",
		goto = "dispatchTask",
		desc_en = "Dispatch Pokémon to get plenty of rewards",
		desc = "Dispatch Pokémon to get plenty of rewards",
		feature = "dispatchTask",
		res = "config/grow_guide/dispatch.jpg",
		name_th = "Dispatch quest",
		id = 25,
		icon = "city/levelup/icon_mx_rk@.png",
		award = slot2[25],
		items = slot1[25]
	},
	[26] = {
		taskDesc = "Complete 5 dispatch quests",
		name = "Dispatch quest",
		type = 2,
		name_en = "Dispatch quest",
		desc_th = "ส่งโปเกมอนเพื่อรับรางวัลมากมาย",
		taskDesc_th = "ทำภารกิจส่งสำเร็จ 5 ภารกิจ",
		desc = "Dispatch Pokémon to get plenty of rewards",
		goto = "dispatchTask",
		taskParam = 5,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Dispatch Pokémon to get plenty of rewards",
		taskType = 101,
		feature = "dispatchTask",
		res = "config/grow_guide/dispatch.jpg",
		name_th = "Dispatch quest",
		id = 26,
		taskDesc_en = "Complete 5 dispatch quests",
		award = slot2[26],
		items = slot1[26]
	},
	[27] = {
		name_en = "Explorer Device",
		name = "Explorer Device",
		goto = "explorer",
		feature = "explorer",
		res = "config/grow_guide/explorer.jpg",
		name_th = "Explorer Device",
		id = 27,
		icon = "city/levelup/icon_yc_rk@.png",
		award = slot2[27],
		items = slot1[27]
	},
	[28] = {
		name_th = "Explorer Device",
		name = "Explorer Device",
		type = 2,
		taskDesc_th = "ปรับปรุงอุปกรณ์ Explorer 5 ครั้ง",
		res = "config/grow_guide/explorer.jpg",
		taskType = 84,
		feature = "explorer",
		taskDesc = "Enhance Explorer Device 5 times",
		name_en = "Explorer Device",
		taskParam = 5,
		id = 28,
		icon = "city/levelup/icon_yc_rk@.png",
		goto = "explorer",
		taskDesc_en = "Enhance Explorer Device 5 times",
		award = slot2[28],
		items = slot1[28]
	},
	[29] = {
		desc_th = "ท้าทายโปเกมอนในตำนานและรับชิ้นส่วน",
		name = "Element Challenge",
		name_en = "Element Challenge",
		desc_en = "Challenge Legendary Pokémon and get shards",
		goto = "cloneBattle",
		desc = "Challenge Legendary Pokémon and get shards",
		feature = "cloneBattle",
		res = "config/grow_guide/clone.jpg",
		name_th = "Element Challenge",
		id = 29,
		icon = "city/levelup/icon_mx_rk@.png",
		award = slot2[29]
	},
	[30] = {
		taskDesc = "Win Element Challenge 3 times",
		name = "Element Challenge",
		type = 2,
		name_en = "Element Challenge",
		desc_th = "ท้าทายโปเกมอนในตำนานและรับชิ้นส่วน",
		goto = "cloneBattle",
		taskDesc_th = "ชนะ Element Challenge 3 ครั้ง",
		desc = "Challenge Legendary Pokémon and get shards",
		taskParam = 3,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Challenge Legendary Pokémon and get shards",
		taskType = 66,
		feature = "cloneBattle",
		res = "config/grow_guide/clone.jpg",
		name_th = "Element Challenge",
		id = 30,
		taskDesc_en = "Win Element Challenge 3 times",
		award = slot2[30]
	},
	[31] = {
		desc_th = "ฝังอัญมณีเพื่อรับเอฟเฟกต์เสียงสะท้อนอันทรงพลัง",
		name = "Gem",
		name_en = "Gem",
		goto = "gemTitle",
		desc_en = "Inlay gems to get powerful resonance effect",
		desc = "Inlay gems to get powerful resonance effect",
		feature = "gem",
		res = "config/grow_guide/gem.png",
		name_th = "Gem",
		id = 31,
		icon = "city/levelup/icon_yc_rk@.png",
		award = slot2[31],
		items = slot1[31]
	},
	[32] = {
		taskDesc = "Draw gems for a total of 20 times",
		name = "Gem Draw",
		type = 2,
		name_en = "Gem Draw",
		desc_th = "ฝังอัญมณีเพื่อรับเอฟเฟกต์เสียงสะท้อนอันทรงพลัง",
		taskDesc_th = "จั่วอัญมณีทั้งหมด 20 ครั้ง",
		desc = "Inlay gems to get powerful resonance effect",
		goto = "gemDraw",
		taskParam = 20,
		icon = "city/levelup/icon_yc_rk@.png",
		desc_en = "Inlay gems to get powerful resonance effect",
		taskType = 105,
		feature = "gem",
		res = "config/grow_guide/gemdraw.png",
		name_th = "Gem Draw",
		id = 32,
		taskDesc_en = "Draw gems for a total of 20 times",
		award = slot2[32],
		items = slot1[32]
	},
	[33] = {
		desc_th = "Mega Evolution, ความก้าวหน้าสุดขีด",
		name = "Mega Evolution",
		name_en = "Mega Evolution",
		desc_en = "Mega Evolution, Extreme Breakthrough",
		desc = "Mega Evolution, Extreme Breakthrough",
		feature = "mega",
		res = "config/grow_guide/mega.png",
		name_th = "Mega Evolution",
		id = 33,
		icon = "city/levelup/icon_yc_rk@.png",
		award = slot2[33]
	},
	[35] = {
		desc_th = "ตกปลาสบาย ๆ และเก็บเกี่ยวผลตอบแทน",
		name = "Fishing",
		name_en = "Fishing",
		desc_en = "Fishing leisurely and reap rewards",
		goto = "fishing",
		desc = "Fishing leisurely and reap rewards",
		feature = "fishing",
		res = "config/grow_guide/fishing.png",
		name_th = "ตกปลา",
		id = 35,
		icon = "city/levelup/icon_gq_rk@.png",
		award = slot2[35]
	},
	[36] = {
		taskDesc = "Draw gems for a total of 20 times",
		name = "Fishing",
		type = 2,
		name_en = "Fishing",
		desc_th = "ตกปลาสบาย ๆ และเก็บเกี่ยวผลตอบแทน",
		goto = "fishing",
		taskDesc_th = "จั่วอัญมณีทั้งหมด 20 ครั้ง",
		desc = "Fishing leisurely and reap rewards",
		taskParam = 10,
		icon = "city/levelup/icon_gq_rk@.png",
		desc_en = "Fishing leisurely and reap rewards",
		taskType = 109,
		feature = "fishing",
		res = "config/grow_guide/fishing.png",
		name_th = "ตกปลา",
		id = 36,
		taskDesc_en = "Draw gems for a total of 20 times",
		award = slot2[36]
	},
	[38] = {
		taskDesc = "Complete 1 Hunting Zone Normal Route challenge",
		name = "Hunting zone",
		type = 2,
		name_en = "Hunting zone",
		desc_th = "ปรมาจารย์ล่าท้าผู้แข็งแกร่ง",
		goto = "hunting",
		taskDesc_th = "ทำภารกิจท้าทายเส้นทางปกติ 1 โซนล่าสัตว์",
		desc = "Hunting master, challenge the strong",
		taskParam = 1,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Hunting master, challenge the strong",
		taskType = 113,
		feature = "hunting",
		res = "config/grow_guide/sldd.png",
		name_th = "Hunting zone",
		id = 38,
		taskDesc_en = "Complete 1 Hunting Zone Normal Route challenge",
		award = slot2[38]
	},
	[39] = {
		taskDesc = "Complete 1 challenge of the Hunting Zone Advanced Route",
		name = "Advanced hunting route",
		type = 2,
		name_en = "Advanced hunting route",
		desc_th = "ปรมาจารย์ล่าท้าผู้แข็งแกร่ง",
		goto = "specialHunting",
		taskDesc_th = "ผ่าน 1 การท้าทายของ Hunting Zone Advanced Route",
		desc = "Hunting master, challenge the strong",
		taskParam = 1,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Hunting master, challenge the strong",
		taskType = 114,
		feature = "specialHunting",
		res = "config/grow_guide/sldd.png",
		name_th = "Advanced hunting route",
		id = 39,
		taskDesc_en = "Complete 1 challenge of the Hunting Zone Advanced Route",
		award = slot2[39]
	},
	[40] = {
		desc_th = "ความท้าทายของโปเกมอน ถนนสู่ผู้แข็งแกร่งที่สุด",
		name = "Pokémon Challenge",
		name_en = "Pokémon Challenge",
		desc_en = "Pokémon challenge, the road to the strongest",
		goto = "normalBraveChallenge",
		desc = "Pokémon challenge, the road to the strongest",
		feature = "normalBraveChallenge",
		res = "config/grow_guide/yztz.png",
		name_th = "Pokémon Challenge",
		id = 40,
		icon = "city/levelup/icon_mx_rk@.png",
		award = slot2[40]
	},
	[41] = {
		taskDesc = "Complete 1 Pokémon Challenge challenge",
		name = "Pokémon Challenge",
		type = 2,
		name_en = "Pokémon Challenge",
		desc_th = "ความท้าทายของโปเกมอน ถนนสู่ผู้แข็งแกร่งที่สุด",
		goto = "normalBraveChallenge",
		taskDesc_th = "ทำภารกิจท้าทายโปเกมอน 1 ครั้งให้สำเร็จ",
		desc = "Pokémon challenge, the road to the strongest",
		taskParam = 1,
		icon = "city/levelup/icon_mx_rk@.png",
		desc_en = "Pokémon challenge, the road to the strongest",
		taskType = 118,
		feature = "normalBraveChallenge",
		res = "config/grow_guide/yztz.png",
		name_th = "Pokémon Challenge",
		id = 41,
		taskDesc_en = "Complete 1 Pokémon Challenge challenge",
		award = slot2[41]
	},
	__default = {
		__index = {
			desc_th = "",
			name_en = "",
			type = 1,
			taskType = 0,
			desc_en = "",
			desc = "",
			feature = "",
			taskDesc = "",
			taskDesc_th = "",
			name_th = "",
			res = "",
			name = "",
			taskParam = 9999,
			taskDesc_en = "",
			award = {
				__size = 0
			},
			items = {}
		}
	}
}

return csv.grow_guide
