slot0 = {
	__size = 2,
	[3] = {
		2,
		3,
		4,
		5,
		6
	},
	[4] = {
		1,
		5
	}
}
slot1 = {
	[8] = slot0[4],
	[5] = slot0[3],
	[7] = slot0[4],
	[6] = slot0[3]
}
csv.sysopen = {
	{
		name_en = "Elemental Challenge",
		name = "Elemental Challenge",
		sighid = "1",
		priority = 1002,
		txt = "In progress",
		goto = "cloneBattle",
		reminder = 1,
		feature = "cloneBattle",
		txt_th = "กำลังดำเนินการ",
		name_th = "Elemental Challenge",
		id = 1,
		txt_en = "In progress",
		startTime = 1200
	},
	{
		unionlevel = 2,
		name = "guild red envelope",
		name_en = "guild red envelope",
		sighid = "2",
		endTime = 2399,
		txt = "Begin distribution",
		goto = "redpacket",
		reminder = 1,
		feature = "unionRedpacket",
		priority = 2000,
		txt_th = "เริ่มจำหน่าย",
		name_th = "guild red envelope",
		id = 2,
		txt_en = "Begin distribution",
		startTime = 1
	},
	{
		name_en = "Quartz Assembly",
		name = "Quartz Assembly",
		sighid = "3",
		endTime = 1950,
		priority = 1001,
		txt = "Registration begins",
		goto = "craft",
		reminder = 1,
		feature = "craft",
		serverday = 9,
		txt_th = "เริ่มลงทะเบียน",
		name_th = "Quartz Assembly",
		id = 3,
		txt_en = "Registration begins",
		startTime = 1000
	},
	{
		name_en = "Quartz Assembly",
		name = "Quartz Assembly",
		sighid = "4",
		endTime = 2050,
		priority = 2,
		txt = "Hot",
		goto = "craft",
		serverday = 9,
		feature = "craft",
		txt_th = "นิยม",
		name_th = "Quartz Assembly",
		id = 4,
		txt_en = "Hot",
		startTime = 2000
	},
	{
		name = "guild battle",
		name_en = "guild battle",
		sighid = "5",
		goto = "unionFight",
		reminder = 1,
		serverday = 14,
		txt_th = "เริ่มลงทะเบียน",
		endTime = 2050,
		unionlevel = 4,
		priority = 1004,
		txt = "Registration begins",
		feature = "unionFight",
		name_th = "guild battle",
		id = 5,
		txt_en = "Registration begins",
		startTime = 930,
		openseq = slot1[5]
	},
	{
		unionlevel = 4,
		name = "guild battle",
		name_en = "guild battle",
		txt_th = "นิยม",
		sighid = "6",
		txt = "Hot",
		goto = "unionFight",
		endTime = 2130,
		feature = "unionFight",
		priority = 3,
		name_th = "guild battle",
		id = 6,
		serverday = 14,
		txt_en = "Hot",
		startTime = 2050,
		openseq = slot1[6]
	},
	{
		name_en = "Cross-Server Quartz",
		name = "Cross-Server Quartz",
		txt_th = "เริ่มลงทะเบียน",
		sighid = "7",
		endTime = 1850,
		txt = "Registration begins",
		goto = "crossCraft",
		reminder = 1,
		feature = "crossCraft",
		serverday = 30,
		name_th = "Cross-Server Quartz",
		id = 7,
		priority = 5,
		txt_en = "Registration begins",
		startTime = 1000,
		openseq = slot1[7]
	},
	{
		name_en = "Cross-Server Quartz",
		name = "Cross-Server Quartz",
		txt_th = "นิยม",
		sighid = "8",
		endTime = 1946,
		txt = "Hot",
		goto = "crossCraft",
		priority = 6,
		feature = "crossCraft",
		serverday = 30,
		name_th = "Cross-Server Quartz",
		id = 8,
		txt_en = "Hot",
		startTime = 1900,
		openseq = slot1[8]
	},
	{
		name_en = "Battle Arena",
		name = "Battle Arena",
		txt_en = "Hot",
		sighid = "9",
		txt = "Hot",
		goto = "onlineFight",
		reminder = 1,
		feature = "onlineFight",
		serverday = 40,
		txt_th = "นิยม",
		name_th = "Battle Arena",
		id = 9,
		priority = 2001,
		roundState = "start",
		roundKey = "cross_online_fight_round",
		startTimes = {
			1200
		}
	},
	{
		name_en = "Cross-service commercial street",
		name = "Cross-service commercial street",
		txt_en = "Hot",
		sighid = "10",
		txt = "Hot",
		goto = "crossMine",
		reminder = 1,
		feature = "crossMine",
		serverday = 36,
		txt_th = "นิยม",
		name_th = "Cross-service commercial street",
		id = 10,
		priority = 2002,
		roundState = "start",
		roundKey = "cross_mine_round",
		startTimes = {
			1000
		}
	},
	{
		name_en = "Cross-server shopping street Boss",
		name = "Cross-server shopping street Boss",
		txt_en = "In progress",
		sighid = "11",
		txt = "In progress",
		goto = "crossMineBoss",
		reminder = 2,
		feature = "crossMine",
		serverday = 36,
		txt_th = "กำลังดำเนินการ",
		name_th = "Cross-server shopping street Boss",
		id = 11,
		priority = 2003,
		roundState = "0",
		roundKey = "cross_mine_boss_time",
		startTimes = {
			1230,
			1830
		}
	},
	{
		startTime = 500,
		name = "fishing contest",
		name_en = "fishing contest",
		sighid = "12",
		goto = "fishing",
		reminder = 1,
		serverday = 40,
		txt_th = "นิยม",
		endTime = 2300,
		roundState = "start",
		priority = 2006,
		txt = "Hot",
		feature = "fishing",
		name_th = "fishing contest",
		id = 12,
		txt_en = "Hot",
		roundKey = "cross_fishing_round",
		openseq = {
			7
		}
	},
	{
		startTime = 500,
		name_en = "Guild Q&A",
		name = "Guild Q&A",
		sighid = "13",
		goto = "unionQA",
		reminder = 1,
		serverday = 30,
		txt_th = "นิยม",
		roundState = "start",
		unionlevel = 5,
		priority = 2004,
		txt = "Hot",
		feature = "unionQA",
		name_th = "Guild Q&A",
		id = 13,
		txt_en = "Hot",
		roundKey = "unionqa_round",
		openseq = {
			6,
			7
		}
	},
	{
		startTime = 1200,
		name = "Cross-Server Arena",
		name_en = "Cross-Server Arena",
		sighid = "14",
		goto = "crossArena",
		reminder = 1,
		serverday = 50,
		txt_th = "นิยม",
		endTime = 2200,
		roundState = "start",
		priority = 2005,
		txt = "Hot",
		feature = "crossArena",
		name_th = "Cross-Server Arena",
		id = 14,
		txt_en = "Hot",
		roundKey = "cross_arena_round",
		openseq = {
			1
		}
	},
	__size = 14,
	__default = {
		__index = {
			sighid = "",
			bg = "",
			priority = 0,
			txt = "",
			goto = "",
			reminder = 0,
			feature = "",
			serverday = 1,
			txt_th = "",
			endTime = 2400,
			icon = "",
			txt_en = "",
			startTime = 0,
			openseq = {
				1,
				2,
				3,
				4,
				5,
				6,
				7
			},
			startTimes = {}
		}
	}
}

return csv.sysopen
