slot0 = {
	__size = 0
}
csv.chip.suits = {
	{
		suitName_th = "Fire Dance",
		attrNum2 = "3%",
		suitName_en = "Fire Dance",
		attrNum1 = "3%",
		attrType1 = 7,
		suitName_vn = "Dança do Fogo",
		attrType2 = 8,
		suitQuality = 2,
		suitNum = 2,
		suitName = "Fire Dance",
		id = 1,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		skillID = 66001,
		suitName_en = "Fire Dance",
		suitName_vn = "Dança do Fogo",
		suitQuality = 2,
		suitNum = 4,
		suitName = "Fire Dance",
		id = 2,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		attrNum2 = "4%",
		suitName_en = "Fire Dance",
		attrNum1 = "4%",
		attrType1 = 7,
		suitName_vn = "Dança do Fogo",
		attrType2 = 8,
		suitQuality = 3,
		suitNum = 2,
		suitName = "Fire Dance",
		id = 3,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		skillID = 66002,
		suitName_en = "Fire Dance",
		suitName_vn = "Dança do Fogo",
		suitQuality = 3,
		suitNum = 4,
		suitName = "Fire Dance",
		id = 4,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		attrNum2 = "5%",
		suitName_en = "Fire Dance",
		attrNum1 = "5%",
		attrType1 = 7,
		suitName_vn = "Dança do Fogo",
		attrType2 = 8,
		suitQuality = 4,
		suitNum = 2,
		suitName = "Fire Dance",
		id = 5,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		skillID = 66003,
		suitName_en = "Fire Dance",
		suitName_vn = "Dança do Fogo",
		suitQuality = 4,
		suitNum = 4,
		suitName = "Fire Dance",
		id = 6,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		attrNum2 = "6%",
		suitName_en = "Fire Dance",
		attrNum1 = "6%",
		attrType1 = 7,
		suitName_vn = "Dança do Fogo",
		attrType2 = 8,
		suitQuality = 5,
		suitNum = 2,
		suitName = "Fire Dance",
		id = 7,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		skillID = 66004,
		suitName_en = "Fire Dance",
		suitName_vn = "Dança do Fogo",
		suitQuality = 5,
		suitNum = 4,
		suitName = "Fire Dance",
		id = 8,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		attrNum2 = "9%",
		suitName_en = "Fire Dance",
		attrNum1 = "9%",
		attrType1 = 7,
		suitName_vn = "Dança do Fogo",
		attrType2 = 8,
		suitQuality = 6,
		suitNum = 2,
		suitName = "Fire Dance",
		id = 9,
		suitID = 1
	},
	{
		suitName_th = "Fire Dance",
		skillID = 66005,
		suitName_en = "Fire Dance",
		suitName_vn = "Dança do Fogo",
		suitQuality = 6,
		suitNum = 4,
		suitName = "Fire Dance",
		id = 10,
		suitID = 1
	},
	{
		suitName_th = "Frog Thorn",
		attrNum2 = "3%",
		suitName_en = "Frog Thorn",
		attrType1 = 7,
		attrNum1 = "3%",
		suitName_vn = "Frog Thorn",
		suitQuality = 2,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 2,
		suitName = "Frog Thorn",
		id = 11,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		suitQuality = 2,
		suitName_en = "Frog Thorn",
		skillID = 66006,
		suitName_vn = "Frog Thorn",
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 4,
		suitName = "Frog Thorn",
		id = 12,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		attrNum2 = "4%",
		suitName_en = "Frog Thorn",
		attrType1 = 7,
		attrNum1 = "4%",
		suitName_vn = "Frog Thorn",
		suitQuality = 3,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 2,
		suitName = "Frog Thorn",
		id = 13,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		suitQuality = 3,
		suitName_en = "Frog Thorn",
		skillID = 66007,
		suitName_vn = "Frog Thorn",
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 4,
		suitName = "Frog Thorn",
		id = 14,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		attrNum2 = "5%",
		suitName_en = "Frog Thorn",
		attrType1 = 7,
		attrNum1 = "5%",
		suitName_vn = "Frog Thorn",
		suitQuality = 4,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 2,
		suitName = "Frog Thorn",
		id = 15,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		suitQuality = 4,
		suitName_en = "Frog Thorn",
		skillID = 66008,
		suitName_vn = "Frog Thorn",
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 4,
		suitName = "Frog Thorn",
		id = 16,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		attrNum2 = "6%",
		suitName_en = "Frog Thorn",
		attrType1 = 7,
		attrNum1 = "6%",
		suitName_vn = "Frog Thorn",
		suitQuality = 5,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 2,
		suitName = "Frog Thorn",
		id = 17,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		suitQuality = 5,
		suitName_en = "Frog Thorn",
		skillID = 66009,
		suitName_vn = "Frog Thorn",
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 4,
		suitName = "Frog Thorn",
		id = 18,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		attrNum2 = "9%",
		suitName_en = "Frog Thorn",
		attrType1 = 7,
		attrNum1 = "9%",
		suitName_vn = "Frog Thorn",
		suitQuality = 6,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 2,
		suitName = "Frog Thorn",
		id = 19,
		suitID = 2
	},
	{
		suitName_th = "Frog Thorn",
		suitQuality = 6,
		suitName_en = "Frog Thorn",
		skillID = 66010,
		suitName_vn = "Frog Thorn",
		suitIcon = "config/chip/suit/img_gj_2_00.png",
		suitNum = 4,
		suitName = "Frog Thorn",
		id = 20,
		suitID = 2
	},
	{
		suitName_th = "Lone Wolf",
		attrNum2 = "3%",
		suitName_en = "Lone Wolf",
		attrType1 = 7,
		attrNum1 = "3%",
		suitName_vn = "Lone Wolf",
		suitQuality = 2,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 2,
		suitName = "Lone Wolf",
		id = 21,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		suitQuality = 2,
		suitName_en = "Lone Wolf",
		skillID = 66011,
		suitName_vn = "Lone Wolf",
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 4,
		suitName = "Lone Wolf",
		id = 22,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		attrNum2 = "4%",
		suitName_en = "Lone Wolf",
		attrType1 = 7,
		attrNum1 = "4%",
		suitName_vn = "Lone Wolf",
		suitQuality = 3,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 2,
		suitName = "Lone Wolf",
		id = 23,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		suitQuality = 3,
		suitName_en = "Lone Wolf",
		skillID = 66012,
		suitName_vn = "Lone Wolf",
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 4,
		suitName = "Lone Wolf",
		id = 24,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		attrNum2 = "5%",
		suitName_en = "Lone Wolf",
		attrType1 = 7,
		attrNum1 = "5%",
		suitName_vn = "Lone Wolf",
		suitQuality = 4,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 2,
		suitName = "Lone Wolf",
		id = 25,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		suitQuality = 4,
		suitName_en = "Lone Wolf",
		skillID = 66013,
		suitName_vn = "Lone Wolf",
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 4,
		suitName = "Lone Wolf",
		id = 26,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		attrNum2 = "6%",
		suitName_en = "Lone Wolf",
		attrType1 = 7,
		attrNum1 = "6%",
		suitName_vn = "Lone Wolf",
		suitQuality = 5,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 2,
		suitName = "Lone Wolf",
		id = 27,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		suitQuality = 5,
		suitName_en = "Lone Wolf",
		skillID = 66014,
		suitName_vn = "Lone Wolf",
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 4,
		suitName = "Lone Wolf",
		id = 28,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		attrNum2 = "9%",
		suitName_en = "Lone Wolf",
		attrType1 = 7,
		attrNum1 = "9%",
		suitName_vn = "Lone Wolf",
		suitQuality = 6,
		attrType2 = 8,
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 2,
		suitName = "Lone Wolf",
		id = 29,
		suitID = 3
	},
	{
		suitName_th = "Lone Wolf",
		suitQuality = 6,
		suitName_en = "Lone Wolf",
		skillID = 66015,
		suitName_vn = "Lone Wolf",
		suitIcon = "config/chip/suit/img_gj_3_00.png",
		suitNum = 4,
		suitName = "Lone Wolf",
		id = 30,
		suitID = 3
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 2,
		suitName_en = "Tortoise Shell",
		attrType1 = 1,
		attrNum1 = "4%",
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 2,
		suitName = "Tortoise Shell",
		id = 31,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 2,
		suitName_en = "Tortoise Shell",
		skillID = 66016,
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 4,
		suitName = "Tortoise Shell",
		id = 32,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 3,
		suitName_en = "Tortoise Shell",
		attrType1 = 1,
		attrNum1 = "5%",
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 2,
		suitName = "Tortoise Shell",
		id = 33,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 3,
		suitName_en = "Tortoise Shell",
		skillID = 66017,
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 4,
		suitName = "Tortoise Shell",
		id = 34,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 4,
		suitName_en = "Tortoise Shell",
		attrType1 = 1,
		attrNum1 = "6.50%",
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 2,
		suitName = "Tortoise Shell",
		id = 35,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 4,
		suitName_en = "Tortoise Shell",
		skillID = 66018,
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 4,
		suitName = "Tortoise Shell",
		id = 36,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 5,
		suitName_en = "Tortoise Shell",
		attrType1 = 1,
		attrNum1 = "8%",
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 2,
		suitName = "Tortoise Shell",
		id = 37,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 5,
		suitName_en = "Tortoise Shell",
		skillID = 66019,
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 4,
		suitName = "Tortoise Shell",
		id = 38,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 6,
		suitName_en = "Tortoise Shell",
		attrType1 = 1,
		attrNum1 = "12%",
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 2,
		suitName = "Tortoise Shell",
		id = 39,
		suitID = 4
	},
	{
		suitName_th = "Tortoise Shell",
		suitQuality = 6,
		suitName_en = "Tortoise Shell",
		skillID = 66020,
		suitName_vn = "Tortoise Shell",
		suitIcon = "config/chip/suit/img_fy_1_00.png",
		suitNum = 4,
		suitName = "Tortoise Shell",
		id = 40,
		suitID = 4
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 2,
		suitName_en = "Fist shield",
		attrType1 = 1,
		attrNum1 = "4%",
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 2,
		suitName = "Fist shield",
		id = 41,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 2,
		suitName_en = "Fist shield",
		skillID = 66021,
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 4,
		suitName = "Fist shield",
		id = 42,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 3,
		suitName_en = "Fist shield",
		attrType1 = 1,
		attrNum1 = "5%",
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 2,
		suitName = "Fist shield",
		id = 43,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 3,
		suitName_en = "Fist shield",
		skillID = 66022,
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 4,
		suitName = "Fist shield",
		id = 44,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 4,
		suitName_en = "Fist shield",
		attrType1 = 1,
		attrNum1 = "6.50%",
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 2,
		suitName = "Fist shield",
		id = 45,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 4,
		suitName_en = "Fist shield",
		skillID = 66023,
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 4,
		suitName = "Fist shield",
		id = 46,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 5,
		suitName_en = "Fist shield",
		attrType1 = 1,
		attrNum1 = "8%",
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 2,
		suitName = "Fist shield",
		id = 47,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 5,
		suitName_en = "Fist shield",
		skillID = 66024,
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 4,
		suitName = "Fist shield",
		id = 48,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 6,
		suitName_en = "Fist shield",
		attrType1 = 1,
		attrNum1 = "12%",
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 2,
		suitName = "Fist shield",
		id = 49,
		suitID = 5
	},
	{
		suitName_th = "Fist shield",
		suitQuality = 6,
		suitName_en = "Fist shield",
		skillID = 66025,
		suitName_vn = "Fist shield",
		suitIcon = "config/chip/suit/img_fy_2_00.png",
		suitNum = 4,
		suitName = "Fist shield",
		id = 50,
		suitID = 5
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 2,
		suitName_en = "Snake Soul",
		attrType1 = 1,
		attrNum1 = "4%",
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 2,
		suitName = "Snake Soul",
		id = 51,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 2,
		suitName_en = "Snake Soul",
		skillID = 66026,
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 4,
		suitName = "Snake Soul",
		id = 52,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 3,
		suitName_en = "Snake Soul",
		attrType1 = 1,
		attrNum1 = "5%",
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 2,
		suitName = "Snake Soul",
		id = 53,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 3,
		suitName_en = "Snake Soul",
		skillID = 66027,
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 4,
		suitName = "Snake Soul",
		id = 54,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 4,
		suitName_en = "Snake Soul",
		attrType1 = 1,
		attrNum1 = "6.50%",
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 2,
		suitName = "Snake Soul",
		id = 55,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 4,
		suitName_en = "Snake Soul",
		skillID = 66028,
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 4,
		suitName = "Snake Soul",
		id = 56,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 5,
		suitName_en = "Snake Soul",
		attrType1 = 1,
		attrNum1 = "8%",
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 2,
		suitName = "Snake Soul",
		id = 57,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 5,
		suitName_en = "Snake Soul",
		skillID = 66029,
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 4,
		suitName = "Snake Soul",
		id = 58,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 6,
		suitName_en = "Snake Soul",
		attrType1 = 1,
		attrNum1 = "12%",
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 2,
		suitName = "Snake Soul",
		id = 59,
		suitID = 6
	},
	{
		suitName_th = "Snake Soul",
		suitQuality = 6,
		suitName_en = "Snake Soul",
		skillID = 66030,
		suitName_vn = "Snake Soul",
		suitIcon = "config/chip/suit/img_fy_3_00.png",
		suitNum = 4,
		suitName = "Snake Soul",
		id = 60,
		suitID = 6
	},
	{
		suitName_th = "Psychic",
		attrNum2 = "2%",
		suitName_en = "Psychic",
		attrNum3 = "2%",
		attrNum1 = "3%",
		suitName_vn = "Psychic",
		suitQuality = 2,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 2,
		suitName = "Psychic",
		id = 61,
		attrType1 = 1,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		suitQuality = 2,
		suitName_en = "Psychic",
		skillID = 66031,
		suitName_vn = "Psychic",
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 4,
		suitName = "Psychic",
		id = 62,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		attrNum2 = "3%",
		suitName_en = "Psychic",
		attrNum3 = "3%",
		attrNum1 = "4%",
		suitName_vn = "Psychic",
		suitQuality = 3,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 2,
		suitName = "Psychic",
		id = 63,
		attrType1 = 1,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		suitQuality = 3,
		suitName_en = "Psychic",
		skillID = 66032,
		suitName_vn = "Psychic",
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 4,
		suitName = "Psychic",
		id = 64,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		attrNum2 = "4%",
		suitName_en = "Psychic",
		attrNum3 = "4%",
		attrNum1 = "5%",
		suitName_vn = "Psychic",
		suitQuality = 4,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 2,
		suitName = "Psychic",
		id = 65,
		attrType1 = 1,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		suitQuality = 4,
		suitName_en = "Psychic",
		skillID = 66033,
		suitName_vn = "Psychic",
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 4,
		suitName = "Psychic",
		id = 66,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		attrNum2 = "5%",
		suitName_en = "Psychic",
		attrNum3 = "5%",
		attrNum1 = "7.50%",
		suitName_vn = "Psychic",
		suitQuality = 5,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 2,
		suitName = "Psychic",
		id = 67,
		attrType1 = 1,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		suitQuality = 5,
		suitName_en = "Psychic",
		skillID = 66034,
		suitName_vn = "Psychic",
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 4,
		suitName = "Psychic",
		id = 68,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		attrNum2 = "6%",
		suitName_en = "Psychic",
		attrNum3 = "6%",
		attrNum1 = "9%",
		suitName_vn = "Psychic",
		suitQuality = 6,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 2,
		suitName = "Psychic",
		id = 69,
		attrType1 = 1,
		suitID = 7
	},
	{
		suitName_th = "Psychic",
		suitQuality = 6,
		suitName_en = "Psychic",
		skillID = 66035,
		suitName_vn = "Psychic",
		suitIcon = "config/chip/suit/img_kz_1_00.png",
		suitNum = 4,
		suitName = "Psychic",
		id = 70,
		suitID = 7
	},
	{
		suitName_th = "Fear",
		attrNum2 = "2%",
		suitName_en = "Fear",
		attrNum3 = "2%",
		attrNum1 = "3%",
		suitName_vn = "Fear",
		suitQuality = 2,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 2,
		suitName = "Fear",
		id = 71,
		attrType1 = 1,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		suitQuality = 2,
		suitName_en = "Fear",
		skillID = 66036,
		suitName_vn = "Fear",
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 4,
		suitName = "Fear",
		id = 72,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		attrNum2 = "3%",
		suitName_en = "Fear",
		attrNum3 = "3%",
		attrNum1 = "4%",
		suitName_vn = "Fear",
		suitQuality = 3,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 2,
		suitName = "Fear",
		id = 73,
		attrType1 = 1,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		suitQuality = 3,
		suitName_en = "Fear",
		skillID = 66037,
		suitName_vn = "Fear",
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 4,
		suitName = "Fear",
		id = 74,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		attrNum2 = "4%",
		suitName_en = "Fear",
		attrNum3 = "4%",
		attrNum1 = "5%",
		suitName_vn = "Fear",
		suitQuality = 4,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 2,
		suitName = "Fear",
		id = 75,
		attrType1 = 1,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		suitQuality = 4,
		suitName_en = "Fear",
		skillID = 66038,
		suitName_vn = "Fear",
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 4,
		suitName = "Fear",
		id = 76,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		attrNum2 = "5%",
		suitName_en = "Fear",
		attrNum3 = "5%",
		attrNum1 = "7.50%",
		suitName_vn = "Fear",
		suitQuality = 5,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 2,
		suitName = "Fear",
		id = 77,
		attrType1 = 1,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		suitQuality = 5,
		suitName_en = "Fear",
		skillID = 66039,
		suitName_vn = "Fear",
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 4,
		suitName = "Fear",
		id = 78,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		attrNum2 = "6%",
		suitName_en = "Fear",
		attrNum3 = "6%",
		attrNum1 = "9%",
		suitName_vn = "Fear",
		suitQuality = 6,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 2,
		suitName = "Fear",
		id = 79,
		attrType1 = 1,
		suitID = 8
	},
	{
		suitName_th = "Fear",
		suitQuality = 6,
		suitName_en = "Fear",
		skillID = 66040,
		suitName_vn = "Fear",
		suitIcon = "config/chip/suit/img_kz_2_00.png",
		suitNum = 4,
		suitName = "Fear",
		id = 80,
		suitID = 8
	},
	{
		suitName_th = "Sacrifice",
		attrNum2 = "2%",
		suitName_en = "Sacrifice",
		attrNum3 = "2%",
		attrNum1 = "3%",
		suitName_vn = "Sacrifice",
		suitQuality = 2,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 2,
		suitName = "Sacrifice",
		id = 81,
		attrType1 = 1,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		suitQuality = 2,
		suitName_en = "Sacrifice",
		skillID = 66041,
		suitName_vn = "Sacrifice",
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 4,
		suitName = "Sacrifice",
		id = 82,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		attrNum2 = "3%",
		suitName_en = "Sacrifice",
		attrNum3 = "3%",
		attrNum1 = "4%",
		suitName_vn = "Sacrifice",
		suitQuality = 3,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 2,
		suitName = "Sacrifice",
		id = 83,
		attrType1 = 1,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		suitQuality = 3,
		suitName_en = "Sacrifice",
		skillID = 66042,
		suitName_vn = "Sacrifice",
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 4,
		suitName = "Sacrifice",
		id = 84,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		attrNum2 = "4%",
		suitName_en = "Sacrifice",
		attrNum3 = "4%",
		attrNum1 = "5%",
		suitName_vn = "Sacrifice",
		suitQuality = 4,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 2,
		suitName = "Sacrifice",
		id = 85,
		attrType1 = 1,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		suitQuality = 4,
		suitName_en = "Sacrifice",
		skillID = 66043,
		suitName_vn = "Sacrifice",
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 4,
		suitName = "Sacrifice",
		id = 86,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		attrNum2 = "5%",
		suitName_en = "Sacrifice",
		attrNum3 = "5%",
		attrNum1 = "7.50%",
		suitName_vn = "Sacrifice",
		suitQuality = 5,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 2,
		suitName = "Sacrifice",
		id = 87,
		attrType1 = 1,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		suitQuality = 5,
		suitName_en = "Sacrifice",
		skillID = 66044,
		suitName_vn = "Sacrifice",
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 4,
		suitName = "Sacrifice",
		id = 88,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		attrNum2 = "6%",
		suitName_en = "Sacrifice",
		attrNum3 = "6%",
		attrNum1 = "9%",
		suitName_vn = "Sacrifice",
		suitQuality = 6,
		attrType2 = 7,
		attrType3 = 8,
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 2,
		suitName = "Sacrifice",
		id = 89,
		attrType1 = 1,
		suitID = 9
	},
	{
		suitName_th = "Sacrifice",
		suitQuality = 6,
		suitName_en = "Sacrifice",
		skillID = 66045,
		suitName_vn = "Sacrifice",
		suitIcon = "config/chip/suit/img_kz_3_00.png",
		suitNum = 4,
		suitName = "Sacrifice",
		id = 90,
		suitID = 9
	},
	__size = 90,
	__default = {
		__index = {
			suitIcon = "config/chip/suit/img_gj_1_00.png",
			attrNum2 = "",
			suitName_en = "",
			attrNum3 = "",
			attrType1 = 0,
			suitName_vn = "",
			attrNum1 = "",
			attrType2 = 0,
			suitName_th = "",
			suitQuality = 1,
			suitNum = 0,
			suitName = "",
			attrType3 = 0,
			skillID = 0,
			suitID = 0
		}
	}
}

return csv.chip.suits
