--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['stage']['kjqd'] = {
	[1] = {
		id = 1,
		xloop = 1,
		scale = 1.5,
		aniName = 'kjc',
		res = 'koudai_paluqiya_qiyuan/paluqiya_qiyuan_buff.skel',
		xlength = 1136
	},
	__size = 1,
	__default = {
		__index = {
			y = 0,
			x = 0,
			opp_y_speed = 0,
			opp_x_speed = 0,
			yloop = 1,
			ylength = 757,
			resType = 1,
			xloop = 0,
			scale = 2,
			y_speed = 0,
			x_speed = 0,
			frameScale = 1
		}
	}
}
return csv.stage.kjqd