--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['stage']['ybqlmbing'] = {
	[1] = {
		id = 1,
		res = 'koudai_yanbaiqiuleimu/hero_yanbaiqiuleimu_buff.skel',
		scale = 1.5,
		xlength = 1136,
		xloop = 1,
		y = -20,
		aniName = 'ydcy_hou'
	},
	__size = 1,
	__default = {
		__index = {
			resType = 1,
			scale = 2,
			xloop = 0,
			ylength = 757,
			yloop = 1,
			opp_x_speed = 0,
			opp_y_speed = 0,
			x = 0,
			y = 0,
			frameScale = 1,
			x_speed = 0,
			y_speed = 0
		}
	}
}
return csv.stage.ybqlmbing