--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['town']['energy'] = {
	[1] = {
		id = 1,
		rarity = 1
	},
	[2] = {
		id = 2,
		starAdd = 6,
		rarity = 2,
		advanceAdd = 6
	},
	[3] = {
		id = 3,
		starAdd = 7.5,
		rarity = 3,
		advanceAdd = 7.5
	},
	[4] = {
		id = 4,
		starAdd = 9,
		rarity = 4,
		advanceAdd = 9
	},
	[5] = {
		id = 5,
		starAdd = 10.5,
		rarity = 5,
		advanceAdd = 10.5
	},
	__size = 5,
	__default = {
		__index = {
			starAdd = 0,
			rarity = 0,
			advanceAdd = 0
		}
	}
}
return csv.town.energy