--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['town']['home_score_fix'] = {
	[1] = {
		id = 1,
		correctValue = 0.9,
		averageScoreRange = {0, 1.5}
	},
	[2] = {
		id = 2,
		averageScoreRange = {1.5, 2}
	},
	[3] = {
		id = 3,
		correctValue = 1.1,
		averageScoreRange = {2, 2.25}
	},
	[4] = {
		id = 4,
		correctValue = 1.2,
		averageScoreRange = {2.25, 2.5}
	},
	[5] = {
		id = 5,
		correctValue = 1.3,
		averageScoreRange = {2.5, 2.75}
	},
	[6] = {
		id = 6,
		correctValue = 1.4,
		averageScoreRange = {2.75, 2.9}
	},
	[7] = {
		id = 7,
		correctValue = 1.5,
		averageScoreRange = {2.9, 3}
	},
	[101] = {
		id = 101,
		correctValue = 0.4,
		averageScoreRange = {-0.1, 0.3},
		text = '*快填充一些家具在你的小屋吧',
		type = 2
	},
	[102] = {
		id = 102,
		correctValue = 0.8,
		averageScoreRange = {0.3, 0.45},
		type = 2
	},
	[103] = {
		id = 103,
		averageScoreRange = {0.45, 0.58},
		type = 2
	},
	[104] = {
		id = 104,
		correctValue = -2.7,
		averageScoreRange = {0.58, 1},
		text = '*小屋过于拥挤，请减少家具摆放#C0xFFF76B45#%s%%#C0xFF60C456#/58%%',
		type = 2
	},
	[201] = {
		id = 201,
		correctValue = -0.4,
		averageScoreRange = {-0.1, 0.05},
		text = '*布置更多稀有家具来提高评价',
		type = 3
	},
	[202] = {
		id = 202,
		correctValue = 0.5,
		averageScoreRange = {0.05, 0.1},
		text = '*布置部分稀有家具来提高评价',
		type = 3
	},
	[203] = {
		id = 203,
		correctValue = 0.8,
		averageScoreRange = {0.1, 0.15},
		text = '*再布置一些稀有家具来提高评价',
		type = 3
	},
	[204] = {
		id = 204,
		averageScoreRange = {0.15, 0.25},
		type = 3
	},
	[205] = {
		id = 205,
		correctValue = 1.1,
		averageScoreRange = {0.25, 1},
		type = 3
	},
	__size = 16,
	__default = {
		__index = {
			correctValue = 1,
			averageScoreRange = {},
			type = 1
		}
	}
}
return csv.town.home_score_fix