--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[3] = {1, 100}, 
	[4] = {1, 150}, 
	[7] = {[535] = 2500, __size = 1}, 
	[8] = {150, 150}, 
	[10] = {5, 150}, 
	[13] = {7, 150}, 
	[17] = {[535] = 600, __size = 1}, 
	[19] = {[535] = 1000, __size = 1}, 
	[23] = {['coin16'] = 600, __size = 1}, 
	[26] = {['coin16'] = 800, __size = 1}, 
	[28] = {9, 150}, 
	[30] = {12, 150}, 
	[35] = {['coin16'] = 1200, __size = 1}, 
	[42] = {85, 150}, 
	[43] = {'cn', 'tw', 'en_us'}, 
	[45] = {[8202] = 1, __size = 1}, 
	[46] = {['rmb'] = 80, __size = 1}, 
	[47] = {1, 5}, 
	[48] = {6, 6}, 
	[49] = {7, 7}, 
	[50] = {8, 8}, 
	[51] = {9, 9}, 
	[52] = {10, 10}, 
	[53] = {11, 11}, 
	[54] = {12, 12}, 
	[55] = {13, 13}, 
	[56] = {14, 14}, 
	[57] = {15, 15}, 
	[58] = {16, 16}, 
	[59] = {17, 17}, 
	[60] = {18, 18}, 
	[61] = {19, 19}, 
	[62] = {20, 20}, 
	[63] = {['rmb'] = 160, __size = 1}, 
	[64] = {[8203] = 1, __size = 1}, __size = 35}
local __data_t__centerBuildingFilterRange = {
	[2323] = __predefine_t__[53],
	[2322] = __predefine_t__[52],
	[2321] = __predefine_t__[51],
	[2320] = __predefine_t__[50],
	[2327] = __predefine_t__[57],
	[2326] = __predefine_t__[56],
	[2325] = __predefine_t__[55],
	[2324] = __predefine_t__[54],
	[2329] = __predefine_t__[59],
	[2328] = __predefine_t__[58],
	[2406] = __predefine_t__[53],
	[2407] = __predefine_t__[54],
	[2404] = __predefine_t__[51],
	[2405] = __predefine_t__[52],
	[2402] = __predefine_t__[49],
	[2403] = __predefine_t__[50],
	[2400] = __predefine_t__[47],
	[2401] = __predefine_t__[48],
	[2408] = __predefine_t__[55],
	[2409] = __predefine_t__[56],
	[2318] = __predefine_t__[48],
	[2319] = __predefine_t__[49],
	[2316] = __predefine_t__[62],
	[2317] = __predefine_t__[47],
	[2314] = __predefine_t__[60],
	[2315] = __predefine_t__[61],
	[2312] = __predefine_t__[58],
	[2313] = __predefine_t__[59],
	[2310] = __predefine_t__[56],
	[2311] = __predefine_t__[57],
	[2411] = __predefine_t__[58],
	[2410] = __predefine_t__[57],
	[2413] = __predefine_t__[60],
	[2412] = __predefine_t__[59],
	[2415] = __predefine_t__[62],
	[2414] = __predefine_t__[61],
	[2417] = __predefine_t__[48],
	[2416] = __predefine_t__[47],
	[2419] = __predefine_t__[50],
	[2418] = __predefine_t__[49],
	[2309] = __predefine_t__[55],
	[2308] = __predefine_t__[54],
	[2301] = __predefine_t__[47],
	[2303] = __predefine_t__[49],
	[2302] = __predefine_t__[48],
	[2305] = __predefine_t__[51],
	[2304] = __predefine_t__[50],
	[2307] = __predefine_t__[53],
	[2306] = __predefine_t__[52],
	["default"] = __predefine_t__[4],
	[2201] = __predefine_t__[47],
	[2202] = __predefine_t__[48],
	[2203] = __predefine_t__[49],
	[2204] = __predefine_t__[50],
	[2205] = __predefine_t__[51],
	[2206] = __predefine_t__[52],
	[2207] = __predefine_t__[53],
	[2208] = __predefine_t__[54],
	[2209] = __predefine_t__[55],
	[2118] = __predefine_t__[48],
	[2119] = __predefine_t__[49],
	[2110] = __predefine_t__[56],
	[2111] = __predefine_t__[57],
	[2112] = __predefine_t__[58],
	[2113] = __predefine_t__[59],
	[2114] = __predefine_t__[60],
	[2115] = __predefine_t__[61],
	[2116] = __predefine_t__[62],
	[2117] = __predefine_t__[47],
	[2428] = __predefine_t__[59],
	[2330] = __predefine_t__[60],
	[2331] = __predefine_t__[61],
	[2420] = __predefine_t__[51],
	[2421] = __predefine_t__[52],
	[2422] = __predefine_t__[53],
	[2423] = __predefine_t__[54],
	[2424] = __predefine_t__[55],
	[2332] = __predefine_t__[62],
	[2426] = __predefine_t__[57],
	[2427] = __predefine_t__[58],
	[2124] = __predefine_t__[54],
	[2213] = __predefine_t__[59],
	[2212] = __predefine_t__[58],
	[2211] = __predefine_t__[57],
	[2210] = __predefine_t__[56],
	[2217] = __predefine_t__[47],
	[2216] = __predefine_t__[62],
	[2215] = __predefine_t__[61],
	[2214] = __predefine_t__[60],
	[2219] = __predefine_t__[49],
	[2218] = __predefine_t__[48],
	[2129] = __predefine_t__[59],
	[2109] = __predefine_t__[55],
	[2108] = __predefine_t__[54],
	[2128] = __predefine_t__[58],
	[2103] = __predefine_t__[49],
	[2102] = __predefine_t__[48],
	[2101] = __predefine_t__[47],
	[2107] = __predefine_t__[53],
	[2106] = __predefine_t__[52],
	[2105] = __predefine_t__[51],
	[2104] = __predefine_t__[50],
	[2232] = __predefine_t__[62],
	[2429] = __predefine_t__[60],
	[2431] = __predefine_t__[62],
	[2430] = __predefine_t__[61],
	[2132] = __predefine_t__[62],
	[2228] = __predefine_t__[58],
	[2131] = __predefine_t__[61],
	[2226] = __predefine_t__[56],
	[2227] = __predefine_t__[57],
	[2224] = __predefine_t__[54],
	[2225] = __predefine_t__[55],
	[2222] = __predefine_t__[52],
	[2223] = __predefine_t__[53],
	[2220] = __predefine_t__[50],
	[2221] = __predefine_t__[51],
	[2425] = __predefine_t__[56],
	[2121] = __predefine_t__[51],
	[2120] = __predefine_t__[50],
	[2123] = __predefine_t__[53],
	[2122] = __predefine_t__[52],
	[2125] = __predefine_t__[55],
	[2130] = __predefine_t__[60],
	[2127] = __predefine_t__[57],
	[2126] = __predefine_t__[56],
	[2231] = __predefine_t__[61],
	[2230] = __predefine_t__[60],
	[2229] = __predefine_t__[59]
}
local __data_t__itemWeightMap = {
	[2323] = __predefine_t__[64],
	[2322] = __predefine_t__[64],
	[2321] = __predefine_t__[64],
	[2320] = __predefine_t__[64],
	[2327] = __predefine_t__[64],
	[2326] = __predefine_t__[64],
	[2325] = __predefine_t__[64],
	[2324] = __predefine_t__[64],
	[2329] = __predefine_t__[64],
	[2328] = __predefine_t__[64],
	[2406] = __predefine_t__[45],
	[2407] = __predefine_t__[45],
	[2404] = __predefine_t__[45],
	[2405] = __predefine_t__[45],
	[2402] = __predefine_t__[45],
	[2403] = __predefine_t__[45],
	[2400] = __predefine_t__[45],
	[2401] = __predefine_t__[45],
	[2408] = __predefine_t__[45],
	[2409] = __predefine_t__[45],
	[2318] = __predefine_t__[64],
	[2319] = __predefine_t__[64],
	[2316] = __predefine_t__[64],
	[2317] = __predefine_t__[64],
	[2314] = __predefine_t__[64],
	[2315] = __predefine_t__[64],
	[2312] = __predefine_t__[64],
	[2313] = __predefine_t__[64],
	[2310] = __predefine_t__[64],
	[2311] = __predefine_t__[64],
	[2411] = __predefine_t__[45],
	[2410] = __predefine_t__[45],
	[2413] = __predefine_t__[45],
	[2412] = __predefine_t__[45],
	[2415] = __predefine_t__[45],
	[2414] = __predefine_t__[45],
	[2417] = __predefine_t__[45],
	[2416] = __predefine_t__[45],
	[2419] = __predefine_t__[45],
	[2418] = __predefine_t__[45],
	[2309] = __predefine_t__[64],
	[2308] = __predefine_t__[64],
	[2301] = __predefine_t__[64],
	[2303] = __predefine_t__[64],
	[2302] = __predefine_t__[64],
	[2305] = __predefine_t__[64],
	[2304] = __predefine_t__[64],
	[2307] = __predefine_t__[64],
	[2306] = __predefine_t__[64],
	[2201] = __predefine_t__[64],
	[2202] = __predefine_t__[64],
	[2203] = __predefine_t__[64],
	[2204] = __predefine_t__[64],
	[2205] = __predefine_t__[64],
	[2206] = __predefine_t__[64],
	[2207] = __predefine_t__[64],
	[2208] = __predefine_t__[64],
	[2209] = __predefine_t__[64],
	[2118] = __predefine_t__[45],
	[2119] = __predefine_t__[45],
	[2110] = __predefine_t__[45],
	[2111] = __predefine_t__[45],
	[2112] = __predefine_t__[45],
	[2113] = __predefine_t__[45],
	[2114] = __predefine_t__[45],
	[2115] = __predefine_t__[45],
	[2116] = __predefine_t__[45],
	[2117] = __predefine_t__[45],
	[2428] = __predefine_t__[45],
	[2330] = __predefine_t__[64],
	[2331] = __predefine_t__[64],
	[2420] = __predefine_t__[45],
	[2421] = __predefine_t__[45],
	[2422] = __predefine_t__[45],
	[2423] = __predefine_t__[45],
	[2424] = __predefine_t__[45],
	[2332] = __predefine_t__[64],
	[2426] = __predefine_t__[45],
	[2427] = __predefine_t__[45],
	[2124] = __predefine_t__[45],
	[2213] = __predefine_t__[64],
	[2212] = __predefine_t__[64],
	[2211] = __predefine_t__[64],
	[2210] = __predefine_t__[64],
	[2217] = __predefine_t__[64],
	[2216] = __predefine_t__[64],
	[2215] = __predefine_t__[64],
	[2214] = __predefine_t__[64],
	[2219] = __predefine_t__[64],
	[2218] = __predefine_t__[64],
	[2129] = __predefine_t__[45],
	[2109] = __predefine_t__[45],
	[2108] = __predefine_t__[45],
	[2128] = __predefine_t__[45],
	[2103] = __predefine_t__[45],
	[2102] = __predefine_t__[45],
	[2101] = __predefine_t__[45],
	[2107] = __predefine_t__[45],
	[2106] = __predefine_t__[45],
	[2105] = __predefine_t__[45],
	[2104] = __predefine_t__[45],
	[2232] = __predefine_t__[64],
	[2429] = __predefine_t__[45],
	[2431] = __predefine_t__[45],
	[2430] = __predefine_t__[45],
	[2132] = __predefine_t__[45],
	[2228] = __predefine_t__[64],
	[2131] = __predefine_t__[45],
	[2226] = __predefine_t__[64],
	[2227] = __predefine_t__[64],
	[2224] = __predefine_t__[64],
	[2225] = __predefine_t__[64],
	[2222] = __predefine_t__[64],
	[2223] = __predefine_t__[64],
	[2220] = __predefine_t__[64],
	[2221] = __predefine_t__[64],
	[2425] = __predefine_t__[45],
	[2121] = __predefine_t__[45],
	[2120] = __predefine_t__[45],
	[2123] = __predefine_t__[45],
	[2122] = __predefine_t__[45],
	[2125] = __predefine_t__[45],
	[2130] = __predefine_t__[45],
	[2127] = __predefine_t__[45],
	[2126] = __predefine_t__[45],
	[2231] = __predefine_t__[64],
	[2230] = __predefine_t__[64],
	[2229] = __predefine_t__[64]
}
local __data_t__levelRange = {
	[2323] = __predefine_t__[4],
	[2322] = __predefine_t__[4],
	[2321] = __predefine_t__[4],
	[2320] = __predefine_t__[4],
	[2327] = __predefine_t__[4],
	[2326] = __predefine_t__[4],
	[2325] = __predefine_t__[4],
	[2324] = __predefine_t__[4],
	[2329] = __predefine_t__[4],
	[2328] = __predefine_t__[4],
	[1070] = __predefine_t__[4],
	[2406] = __predefine_t__[4],
	[2407] = __predefine_t__[4],
	[2404] = __predefine_t__[4],
	[2405] = __predefine_t__[4],
	[2402] = __predefine_t__[4],
	[2403] = __predefine_t__[4],
	[2400] = __predefine_t__[4],
	[2401] = __predefine_t__[4],
	[2408] = __predefine_t__[4],
	[2409] = __predefine_t__[4],
	[2331] = __predefine_t__[4],
	[1090] = __predefine_t__[4],
	[1020] = __predefine_t__[4],
	[2318] = __predefine_t__[4],
	[2319] = __predefine_t__[4],
	[2316] = __predefine_t__[4],
	[1060] = __predefine_t__[4],
	[2314] = __predefine_t__[4],
	[2315] = __predefine_t__[4],
	[2312] = __predefine_t__[4],
	[2313] = __predefine_t__[4],
	[2310] = __predefine_t__[4],
	[2311] = __predefine_t__[4],
	[2411] = __predefine_t__[4],
	[2410] = __predefine_t__[4],
	[2413] = __predefine_t__[4],
	[2412] = __predefine_t__[4],
	[2415] = __predefine_t__[4],
	[2414] = __predefine_t__[4],
	[2417] = __predefine_t__[4],
	[2317] = __predefine_t__[4],
	[2419] = __predefine_t__[4],
	[2418] = __predefine_t__[4],
	[1080] = __predefine_t__[4],
	[2309] = __predefine_t__[4],
	[2308] = __predefine_t__[4],
	[2301] = __predefine_t__[4],
	[2303] = __predefine_t__[4],
	[2302] = __predefine_t__[4],
	[2305] = __predefine_t__[4],
	[2304] = __predefine_t__[4],
	[2307] = __predefine_t__[4],
	[2306] = __predefine_t__[4],
	[1044] = __predefine_t__[4],
	[1010] = __predefine_t__[4],
	[2228] = __predefine_t__[4],
	[2416] = __predefine_t__[4],
	[108] = __predefine_t__[8],
	[102] = __predefine_t__[8],
	[103] = __predefine_t__[8],
	[101] = __predefine_t__[8],
	[106] = __predefine_t__[8],
	[107] = __predefine_t__[8],
	[104] = __predefine_t__[8],
	[105] = __predefine_t__[8],
	["default"] = __predefine_t__[3],
	[2201] = __predefine_t__[4],
	[2202] = __predefine_t__[4],
	[2203] = __predefine_t__[4],
	[2204] = __predefine_t__[4],
	[2205] = __predefine_t__[4],
	[2206] = __predefine_t__[4],
	[2207] = __predefine_t__[4],
	[2208] = __predefine_t__[4],
	[2209] = __predefine_t__[4],
	[2118] = __predefine_t__[4],
	[2119] = __predefine_t__[4],
	[2110] = __predefine_t__[4],
	[2111] = __predefine_t__[4],
	[1030] = __predefine_t__[4],
	[2113] = __predefine_t__[4],
	[2114] = __predefine_t__[4],
	[2115] = __predefine_t__[4],
	[2116] = __predefine_t__[4],
	[2117] = __predefine_t__[4],
	[2428] = __predefine_t__[4],
	[2330] = __predefine_t__[4],
	[1042] = __predefine_t__[4],
	[2420] = __predefine_t__[4],
	[2421] = __predefine_t__[4],
	[2422] = __predefine_t__[4],
	[2423] = __predefine_t__[4],
	[2424] = __predefine_t__[4],
	[2332] = __predefine_t__[4],
	[2426] = __predefine_t__[4],
	[2427] = __predefine_t__[4],
	[1040] = __predefine_t__[4],
	[2112] = __predefine_t__[4],
	[2213] = __predefine_t__[4],
	[2212] = __predefine_t__[4],
	[2211] = __predefine_t__[4],
	[2210] = __predefine_t__[4],
	[2217] = __predefine_t__[4],
	[2216] = __predefine_t__[4],
	[2215] = __predefine_t__[4],
	[2214] = __predefine_t__[4],
	[2219] = __predefine_t__[4],
	[2218] = __predefine_t__[4],
	[2129] = __predefine_t__[4],
	[2109] = __predefine_t__[4],
	[2108] = __predefine_t__[4],
	[1100] = __predefine_t__[42],
	[2128] = __predefine_t__[4],
	[2103] = __predefine_t__[4],
	[2102] = __predefine_t__[4],
	[2101] = __predefine_t__[4],
	[2107] = __predefine_t__[4],
	[2106] = __predefine_t__[4],
	[2105] = __predefine_t__[4],
	[2104] = __predefine_t__[4],
	[2232] = __predefine_t__[4],
	[2429] = __predefine_t__[4],
	[2431] = __predefine_t__[4],
	[2430] = __predefine_t__[4],
	[1050] = __predefine_t__[4],
	[2132] = __predefine_t__[4],
	[2130] = __predefine_t__[4],
	[2229] = __predefine_t__[4],
	[2226] = __predefine_t__[4],
	[2227] = __predefine_t__[4],
	[2224] = __predefine_t__[4],
	[2225] = __predefine_t__[4],
	[2222] = __predefine_t__[4],
	[2223] = __predefine_t__[4],
	[2220] = __predefine_t__[4],
	[2221] = __predefine_t__[4],
	[1110] = __predefine_t__[42],
	[2425] = __predefine_t__[4],
	[2121] = __predefine_t__[4],
	[2120] = __predefine_t__[4],
	[2123] = __predefine_t__[4],
	[2122] = __predefine_t__[4],
	[2125] = __predefine_t__[4],
	[2124] = __predefine_t__[4],
	[2127] = __predefine_t__[4],
	[2126] = __predefine_t__[4],
	[2231] = __predefine_t__[4],
	[2230] = __predefine_t__[4],
	[2131] = __predefine_t__[4]
}
local __data_t__costMap = {
	[2323] = __predefine_t__[63],
	[2322] = __predefine_t__[63],
	[2321] = __predefine_t__[63],
	[2320] = __predefine_t__[63],
	[2327] = __predefine_t__[63],
	[2326] = __predefine_t__[63],
	[2325] = __predefine_t__[63],
	[2324] = __predefine_t__[63],
	[2329] = __predefine_t__[63],
	[2328] = __predefine_t__[63],
	[2406] = __predefine_t__[46],
	[2407] = __predefine_t__[46],
	[2404] = __predefine_t__[46],
	[2405] = __predefine_t__[46],
	[2402] = __predefine_t__[46],
	[2403] = __predefine_t__[46],
	[2400] = __predefine_t__[46],
	[2401] = __predefine_t__[46],
	[2408] = __predefine_t__[46],
	[2409] = __predefine_t__[46],
	[2331] = __predefine_t__[63],
	[1090] = __predefine_t__[35],
	[1020] = __predefine_t__[23],
	[2318] = __predefine_t__[63],
	[2319] = __predefine_t__[63],
	[2316] = __predefine_t__[46],
	[1060] = __predefine_t__[35],
	[2314] = __predefine_t__[46],
	[2315] = __predefine_t__[46],
	[2312] = __predefine_t__[46],
	[2313] = __predefine_t__[46],
	[2310] = __predefine_t__[46],
	[2311] = __predefine_t__[46],
	[2411] = __predefine_t__[46],
	[2410] = __predefine_t__[46],
	[2413] = __predefine_t__[46],
	[2412] = __predefine_t__[46],
	[2415] = __predefine_t__[46],
	[2414] = __predefine_t__[46],
	[2417] = __predefine_t__[63],
	[2317] = __predefine_t__[63],
	[2419] = __predefine_t__[63],
	[2418] = __predefine_t__[63],
	[2309] = __predefine_t__[46],
	[2308] = __predefine_t__[46],
	[2301] = __predefine_t__[46],
	[2303] = __predefine_t__[46],
	[2302] = __predefine_t__[46],
	[2305] = __predefine_t__[46],
	[2304] = __predefine_t__[46],
	[2307] = __predefine_t__[46],
	[2306] = __predefine_t__[46],
	[1044] = __predefine_t__[26],
	[1010] = __predefine_t__[23],
	[2228] = __predefine_t__[63],
	[2416] = __predefine_t__[63],
	[108] = __predefine_t__[17],
	[102] = __predefine_t__[7],
	[101] = __predefine_t__[7],
	[106] = __predefine_t__[19],
	[107] = __predefine_t__[19],
	[105] = __predefine_t__[17],
	[2201] = __predefine_t__[46],
	[2202] = __predefine_t__[46],
	[2203] = __predefine_t__[46],
	[2204] = __predefine_t__[46],
	[2205] = __predefine_t__[46],
	[2206] = __predefine_t__[46],
	[2207] = __predefine_t__[46],
	[2208] = __predefine_t__[46],
	[2209] = __predefine_t__[46],
	[2118] = __predefine_t__[63],
	[2119] = __predefine_t__[63],
	[2110] = __predefine_t__[46],
	[2111] = __predefine_t__[46],
	[1030] = __predefine_t__[26],
	[2113] = __predefine_t__[46],
	[2114] = __predefine_t__[46],
	[2115] = __predefine_t__[46],
	[2116] = __predefine_t__[46],
	[2117] = __predefine_t__[63],
	[2428] = __predefine_t__[63],
	[2330] = __predefine_t__[63],
	[1042] = __predefine_t__[26],
	[2420] = __predefine_t__[63],
	[2421] = __predefine_t__[63],
	[2422] = __predefine_t__[63],
	[2423] = __predefine_t__[63],
	[2424] = __predefine_t__[63],
	[2332] = __predefine_t__[63],
	[2426] = __predefine_t__[63],
	[2427] = __predefine_t__[63],
	[1040] = __predefine_t__[26],
	[2112] = __predefine_t__[46],
	[2213] = __predefine_t__[46],
	[2212] = __predefine_t__[46],
	[2211] = __predefine_t__[46],
	[2210] = __predefine_t__[46],
	[2217] = __predefine_t__[63],
	[2216] = __predefine_t__[46],
	[2215] = __predefine_t__[46],
	[2214] = __predefine_t__[46],
	[2219] = __predefine_t__[63],
	[2218] = __predefine_t__[63],
	[2129] = __predefine_t__[63],
	[2109] = __predefine_t__[46],
	[2108] = __predefine_t__[46],
	[1100] = __predefine_t__[23],
	[2128] = __predefine_t__[63],
	[2103] = __predefine_t__[46],
	[2102] = __predefine_t__[46],
	[2101] = __predefine_t__[46],
	[2107] = __predefine_t__[46],
	[2106] = __predefine_t__[46],
	[2105] = __predefine_t__[46],
	[2104] = __predefine_t__[46],
	[2232] = __predefine_t__[63],
	[2429] = __predefine_t__[63],
	[2431] = __predefine_t__[63],
	[2430] = __predefine_t__[63],
	[2132] = __predefine_t__[63],
	[2130] = __predefine_t__[63],
	[2229] = __predefine_t__[63],
	[2226] = __predefine_t__[63],
	[2227] = __predefine_t__[63],
	[2224] = __predefine_t__[63],
	[2225] = __predefine_t__[63],
	[2222] = __predefine_t__[63],
	[2223] = __predefine_t__[63],
	[2220] = __predefine_t__[63],
	[2221] = __predefine_t__[63],
	[1110] = __predefine_t__[23],
	[2425] = __predefine_t__[63],
	[2121] = __predefine_t__[63],
	[2120] = __predefine_t__[63],
	[2123] = __predefine_t__[63],
	[2122] = __predefine_t__[63],
	[2125] = __predefine_t__[63],
	[2124] = __predefine_t__[63],
	[2127] = __predefine_t__[63],
	[2126] = __predefine_t__[63],
	[2231] = __predefine_t__[63],
	[2230] = __predefine_t__[63],
	[2131] = __predefine_t__[63]
}
local __data_t__centerBuildingRange = {
	[2323] = __predefine_t__[4],
	[2322] = __predefine_t__[4],
	[2321] = __predefine_t__[4],
	[2320] = __predefine_t__[4],
	[2327] = __predefine_t__[4],
	[2326] = __predefine_t__[4],
	[2325] = __predefine_t__[4],
	[2324] = __predefine_t__[4],
	[2329] = __predefine_t__[4],
	[2328] = __predefine_t__[4],
	[1070] = __predefine_t__[28],
	[2406] = __predefine_t__[4],
	[2407] = __predefine_t__[4],
	[2404] = __predefine_t__[4],
	[2405] = __predefine_t__[4],
	[2402] = __predefine_t__[4],
	[2403] = __predefine_t__[4],
	[2400] = __predefine_t__[4],
	[2401] = __predefine_t__[4],
	[2408] = __predefine_t__[4],
	[2409] = __predefine_t__[4],
	[2331] = __predefine_t__[4],
	[1090] = __predefine_t__[30],
	[1020] = __predefine_t__[4],
	[2318] = __predefine_t__[4],
	[2319] = __predefine_t__[4],
	[2316] = __predefine_t__[4],
	[1060] = __predefine_t__[4],
	[2314] = __predefine_t__[4],
	[2315] = __predefine_t__[4],
	[2312] = __predefine_t__[4],
	[2313] = __predefine_t__[4],
	[2310] = __predefine_t__[4],
	[2311] = __predefine_t__[4],
	[2411] = __predefine_t__[4],
	[2410] = __predefine_t__[4],
	[2413] = __predefine_t__[4],
	[2412] = __predefine_t__[4],
	[2415] = __predefine_t__[4],
	[2414] = __predefine_t__[4],
	[2417] = __predefine_t__[4],
	[2317] = __predefine_t__[4],
	[2419] = __predefine_t__[4],
	[2418] = __predefine_t__[4],
	[1080] = __predefine_t__[4],
	[2309] = __predefine_t__[4],
	[2308] = __predefine_t__[4],
	[2301] = __predefine_t__[4],
	[2303] = __predefine_t__[4],
	[2302] = __predefine_t__[4],
	[2305] = __predefine_t__[4],
	[2304] = __predefine_t__[4],
	[2307] = __predefine_t__[4],
	[2306] = __predefine_t__[4],
	[1044] = __predefine_t__[30],
	[1010] = __predefine_t__[4],
	[2228] = __predefine_t__[4],
	[2416] = __predefine_t__[4],
	[108] = __predefine_t__[4],
	[102] = __predefine_t__[10],
	[103] = __predefine_t__[13],
	[101] = __predefine_t__[4],
	[106] = __predefine_t__[4],
	[107] = __predefine_t__[4],
	[104] = __predefine_t__[4],
	[105] = __predefine_t__[4],
	["default"] = __predefine_t__[3],
	[2201] = __predefine_t__[4],
	[2202] = __predefine_t__[4],
	[2203] = __predefine_t__[4],
	[2204] = __predefine_t__[4],
	[2205] = __predefine_t__[4],
	[2206] = __predefine_t__[4],
	[2207] = __predefine_t__[4],
	[2208] = __predefine_t__[4],
	[2209] = __predefine_t__[4],
	[2118] = __predefine_t__[4],
	[2119] = __predefine_t__[4],
	[2110] = __predefine_t__[4],
	[2111] = __predefine_t__[4],
	[1030] = __predefine_t__[13],
	[2113] = __predefine_t__[4],
	[2114] = __predefine_t__[4],
	[2115] = __predefine_t__[4],
	[2116] = __predefine_t__[4],
	[2117] = __predefine_t__[4],
	[2428] = __predefine_t__[4],
	[2330] = __predefine_t__[4],
	[1042] = __predefine_t__[30],
	[2420] = __predefine_t__[4],
	[2421] = __predefine_t__[4],
	[2422] = __predefine_t__[4],
	[2423] = __predefine_t__[4],
	[2424] = __predefine_t__[4],
	[2332] = __predefine_t__[4],
	[2426] = __predefine_t__[4],
	[2427] = __predefine_t__[4],
	[1040] = __predefine_t__[28],
	[2112] = __predefine_t__[4],
	[2213] = __predefine_t__[4],
	[2212] = __predefine_t__[4],
	[2211] = __predefine_t__[4],
	[2210] = __predefine_t__[4],
	[2217] = __predefine_t__[4],
	[2216] = __predefine_t__[4],
	[2215] = __predefine_t__[4],
	[2214] = __predefine_t__[4],
	[2219] = __predefine_t__[4],
	[2218] = __predefine_t__[4],
	[2129] = __predefine_t__[4],
	[2109] = __predefine_t__[4],
	[2108] = __predefine_t__[4],
	[1100] = __predefine_t__[10],
	[2128] = __predefine_t__[4],
	[2103] = __predefine_t__[4],
	[2102] = __predefine_t__[4],
	[2101] = __predefine_t__[4],
	[2107] = __predefine_t__[4],
	[2106] = __predefine_t__[4],
	[2105] = __predefine_t__[4],
	[2104] = __predefine_t__[4],
	[2232] = __predefine_t__[4],
	[2429] = __predefine_t__[4],
	[2431] = __predefine_t__[4],
	[2430] = __predefine_t__[4],
	[1050] = __predefine_t__[4],
	[2132] = __predefine_t__[4],
	[2130] = __predefine_t__[4],
	[2229] = __predefine_t__[4],
	[2226] = __predefine_t__[4],
	[2227] = __predefine_t__[4],
	[2224] = __predefine_t__[4],
	[2225] = __predefine_t__[4],
	[2222] = __predefine_t__[4],
	[2223] = __predefine_t__[4],
	[2220] = __predefine_t__[4],
	[2221] = __predefine_t__[4],
	[1110] = __predefine_t__[13],
	[2425] = __predefine_t__[4],
	[2121] = __predefine_t__[4],
	[2120] = __predefine_t__[4],
	[2123] = __predefine_t__[4],
	[2122] = __predefine_t__[4],
	[2125] = __predefine_t__[4],
	[2124] = __predefine_t__[4],
	[2127] = __predefine_t__[4],
	[2126] = __predefine_t__[4],
	[2231] = __predefine_t__[4],
	[2230] = __predefine_t__[4],
	[2131] = __predefine_t__[4]
}
local __data_t__languages = {
	[1110] = __predefine_t__[43],
	[1100] = __predefine_t__[43]
}

csv['town']['supermarket'] = {
	[101] = {
		id = 101,
		vipWeight = 100,
		itemCount = 5,
		itemWeightMap = {[21931] = 10, __size = 1},
		costMap = __data_t__costMap[101],
		-- {[535] = 2500, __size = 1}
		levelRange = __data_t__levelRange[101],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[101]
		-- {1, 150}
	},
	[102] = {
		id = 102,
		vipWeight = 100,
		position = 1,
		showUnable = true,
		itemCount = 5,
		itemWeightMap = {[21911] = 10, __size = 1},
		costMap = __data_t__costMap[102],
		-- {[535] = 2500, __size = 1}
		levelRange = __data_t__levelRange[102],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[102]
		-- {5, 150}
	},
	[103] = {
		id = 103,
		vipWeight = 100,
		position = 2,
		showUnable = true,
		itemCount = 5,
		itemWeightMap = {[21921] = 10, __size = 1},
		costMap = {[535] = 3200, __size = 1},
		levelRange = __data_t__levelRange[103],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[103]
		-- {7, 150}
	},
	[104] = {
		id = 104,
		vipWeight = 100,
		position = 3,
		itemCount = 5,
		itemWeightMap = {[23591] = 10, __size = 1},
		costMap = {[535] = 1800, __size = 1},
		levelRange = __data_t__levelRange[104],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[104]
		-- {1, 150}
	},
	[105] = {
		id = 105,
		vipWeight = 100,
		position = 4,
		itemCount = 100,
		itemWeightMap = {[529] = 10, __size = 1},
		costMap = __data_t__costMap[105],
		-- {[535] = 600, __size = 1}
		levelRange = __data_t__levelRange[105],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[105]
		-- {1, 150}
	},
	[106] = {
		id = 106,
		vipWeight = 100,
		position = 5,
		itemCount = 20,
		itemWeightMap = {[5000] = 10, __size = 1},
		costMap = __data_t__costMap[106],
		-- {[535] = 1000, __size = 1}
		levelRange = __data_t__levelRange[106],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[106]
		-- {1, 150}
	},
	[107] = {
		id = 107,
		vipWeight = 100,
		position = 6,
		itemCount = 20,
		itemWeightMap = {[930] = 10, __size = 1},
		costMap = __data_t__costMap[107],
		-- {[535] = 1000, __size = 1}
		levelRange = __data_t__levelRange[107],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[107]
		-- {1, 150}
	},
	[108] = {
		id = 108,
		vipWeight = 100,
		position = 7,
		itemCount = 10,
		itemWeightMap = {[514] = 10, __size = 1},
		costMap = __data_t__costMap[108],
		-- {[535] = 600, __size = 1}
		levelRange = __data_t__levelRange[108],
		-- {150, 150}
		centerBuildingRange = __data_t__centerBuildingRange[108]
		-- {1, 150}
	},
	[1010] = {
		id = 1010,
		vipWeight = 100,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[20381] = 1, __size = 1},
		costMap = __data_t__costMap[1010],
		-- {['coin16'] = 600, __size = 1}
		levelRange = __data_t__levelRange[1010],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1010]
		-- {1, 150}
	},
	[1020] = {
		id = 1020,
		vipWeight = 100,
		position = 1,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[20501] = 1, __size = 1},
		costMap = __data_t__costMap[1020],
		-- {['coin16'] = 600, __size = 1}
		levelRange = __data_t__levelRange[1020],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1020],
		-- {1, 150}
		sortWeight = 1
	},
	[1030] = {
		id = 1030,
		vipWeight = 100,
		position = 2,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[20611] = 1, __size = 1},
		costMap = __data_t__costMap[1030],
		-- {['coin16'] = 800, __size = 1}
		levelRange = __data_t__levelRange[1030],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1030],
		-- {7, 150}
		sortWeight = 2
	},
	[1040] = {
		id = 1040,
		vipWeight = 100,
		position = 3,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[23681] = 1, __size = 1},
		costMap = __data_t__costMap[1040],
		-- {['coin16'] = 800, __size = 1}
		levelRange = __data_t__levelRange[1040],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1040],
		-- {9, 150}
		sortWeight = 3
	},
	[1042] = {
		id = 1042,
		vipWeight = 100,
		position = 16,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[24141] = 1, __size = 1},
		costMap = __data_t__costMap[1042],
		-- {['coin16'] = 800, __size = 1}
		levelRange = __data_t__levelRange[1042],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1042],
		-- {12, 150}
		sortWeight = 4
	},
	[1044] = {
		id = 1044,
		vipWeight = 100,
		position = 17,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[24061] = 1, __size = 1},
		costMap = __data_t__costMap[1044],
		-- {['coin16'] = 800, __size = 1}
		levelRange = __data_t__levelRange[1044],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1044],
		-- {12, 150}
		sortWeight = 5
	},
	[1050] = {
		id = 1050,
		vipWeight = 100,
		position = 4,
		limitType = 3,
		showUnable = true,
		limitTimes = 5,
		itemCount = 1,
		itemWeightMap = {[8811] = 1, __size = 1},
		costMap = {['coin16'] = 300, __size = 1},
		levelRange = __data_t__levelRange[1050],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1050],
		-- {1, 150}
		sortWeight = 6
	},
	[1060] = {
		id = 1060,
		vipWeight = 100,
		position = 5,
		limitType = 3,
		showUnable = true,
		limitTimes = 2,
		itemCount = 1,
		itemWeightMap = {[8812] = 1, __size = 1},
		costMap = __data_t__costMap[1060],
		-- {['coin16'] = 1200, __size = 1}
		levelRange = __data_t__levelRange[1060],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1060],
		-- {1, 150}
		sortWeight = 7
	},
	[1070] = {
		id = 1070,
		vipWeight = 100,
		position = 6,
		limitType = 3,
		showUnable = true,
		limitTimes = 1,
		itemCount = 1,
		itemWeightMap = {[8813] = 1, __size = 1},
		costMap = {['coin16'] = 3000, __size = 1},
		levelRange = __data_t__levelRange[1070],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1070],
		-- {9, 150}
		sortWeight = 8
	},
	[1080] = {
		id = 1080,
		vipWeight = 100,
		position = 7,
		limitType = 4,
		showUnable = true,
		limitTimes = 1,
		itemCount = 1,
		itemWeightMap = {[2526] = 1, __size = 1},
		costMap = {['coin16'] = 5000, __size = 1},
		levelRange = __data_t__levelRange[1080],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1080],
		-- {1, 150}
		sortWeight = 9
	},
	[1090] = {
		id = 1090,
		vipWeight = 100,
		position = 8,
		limitType = 3,
		showUnable = true,
		limitTimes = 15,
		itemCount = 1,
		itemWeightMap = {[22381] = 1, __size = 1},
		costMap = __data_t__costMap[1090],
		-- {['coin16'] = 1200, __size = 1}
		levelRange = __data_t__levelRange[1090],
		-- {1, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1090],
		-- {12, 150}
		sortWeight = 10
	},
	[1100] = {
		id = 1100,
		vipWeight = 100,
		position = 13,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[91311] = 1, __size = 1},
		costMap = __data_t__costMap[1100],
		-- {['coin16'] = 600, __size = 1}
		levelRange = __data_t__levelRange[1100],
		-- {85, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1100],
		-- {5, 150}
		languages = __data_t__languages[1100],
		-- {'cn', 'tw', 'en_us'}
		sortWeight = 15
	},
	[1110] = {
		id = 1110,
		vipWeight = 100,
		position = 14,
		limitType = 3,
		showUnable = true,
		limitTimes = 30,
		itemCount = 3,
		itemWeightMap = {[91171] = 1, __size = 1},
		costMap = __data_t__costMap[1110],
		-- {['coin16'] = 600, __size = 1}
		levelRange = __data_t__levelRange[1110],
		-- {85, 150}
		centerBuildingRange = __data_t__centerBuildingRange[1110],
		-- {7, 150}
		languages = __data_t__languages[1110],
		-- {'cn', 'tw', 'en_us'}
		sortWeight = 16
	},
	[2101] = {
		id = 2101,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 1760,
		itemWeightMap = __data_t__itemWeightMap[2101],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2101],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2101],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2101],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2101],
		-- {1, 150}
		sortWeight = 11
	},
	[2102] = {
		id = 2102,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 2030,
		itemWeightMap = __data_t__itemWeightMap[2102],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2102],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2102],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2102],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2102],
		-- {1, 150}
		sortWeight = 11
	},
	[2103] = {
		id = 2103,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 2580,
		itemWeightMap = __data_t__itemWeightMap[2103],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2103],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2103],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2103],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2103],
		-- {1, 150}
		sortWeight = 11
	},
	[2104] = {
		id = 2104,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 3110,
		itemWeightMap = __data_t__itemWeightMap[2104],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2104],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2104],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2104],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2104],
		-- {1, 150}
		sortWeight = 11
	},
	[2105] = {
		id = 2105,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 3600,
		itemWeightMap = __data_t__itemWeightMap[2105],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2105],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2105],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2105],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2105],
		-- {1, 150}
		sortWeight = 11
	},
	[2106] = {
		id = 2106,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2106],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2106],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2106],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2106],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2106],
		-- {1, 150}
		sortWeight = 11
	},
	[2107] = {
		id = 2107,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 4490,
		itemWeightMap = __data_t__itemWeightMap[2107],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2107],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2107],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2107],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2107],
		-- {1, 150}
		sortWeight = 11
	},
	[2108] = {
		id = 2108,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 5410,
		itemWeightMap = __data_t__itemWeightMap[2108],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2108],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2108],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2108],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2108],
		-- {1, 150}
		sortWeight = 11
	},
	[2109] = {
		id = 2109,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 6270,
		itemWeightMap = __data_t__itemWeightMap[2109],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2109],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2109],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2109],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2109],
		-- {1, 150}
		sortWeight = 11
	},
	[2110] = {
		id = 2110,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 7070,
		itemWeightMap = __data_t__itemWeightMap[2110],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2110],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2110],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2110],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2110],
		-- {1, 150}
		sortWeight = 11
	},
	[2111] = {
		id = 2111,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 7800,
		itemWeightMap = __data_t__itemWeightMap[2111],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2111],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2111],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2111],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2111],
		-- {1, 150}
		sortWeight = 11
	},
	[2112] = {
		id = 2112,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 8470,
		itemWeightMap = __data_t__itemWeightMap[2112],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2112],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2112],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2112],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2112],
		-- {1, 150}
		sortWeight = 11
	},
	[2113] = {
		id = 2113,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 9970,
		itemWeightMap = __data_t__itemWeightMap[2113],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2113],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2113],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2113],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2113],
		-- {1, 150}
		sortWeight = 11
	},
	[2114] = {
		id = 2114,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 11340,
		itemWeightMap = __data_t__itemWeightMap[2114],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2114],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2114],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2114],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2114],
		-- {1, 150}
		sortWeight = 11
	},
	[2115] = {
		id = 2115,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 12580,
		itemWeightMap = __data_t__itemWeightMap[2115],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2115],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2115],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2115],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2115],
		-- {1, 150}
		sortWeight = 11
	},
	[2116] = {
		id = 2116,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 13700,
		itemWeightMap = __data_t__itemWeightMap[2116],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2116],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2116],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2116],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2116],
		-- {1, 150}
		sortWeight = 11
	},
	[2117] = {
		id = 2117,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 3520,
		itemWeightMap = __data_t__itemWeightMap[2117],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2117],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2117],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2117],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2117],
		-- {1, 150}
		sortWeight = 11
	},
	[2118] = {
		id = 2118,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2118],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2118],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2118],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2118],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2118],
		-- {1, 150}
		sortWeight = 11
	},
	[2119] = {
		id = 2119,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 5160,
		itemWeightMap = __data_t__itemWeightMap[2119],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2119],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2119],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2119],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2119],
		-- {1, 150}
		sortWeight = 11
	},
	[2120] = {
		id = 2120,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 6220,
		itemWeightMap = __data_t__itemWeightMap[2120],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2120],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2120],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2120],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2120],
		-- {1, 150}
		sortWeight = 11
	},
	[2121] = {
		id = 2121,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 7200,
		itemWeightMap = __data_t__itemWeightMap[2121],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2121],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2121],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2121],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2121],
		-- {1, 150}
		sortWeight = 11
	},
	[2122] = {
		id = 2122,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 8120,
		itemWeightMap = __data_t__itemWeightMap[2122],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2122],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2122],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2122],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2122],
		-- {1, 150}
		sortWeight = 11
	},
	[2123] = {
		id = 2123,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 8980,
		itemWeightMap = __data_t__itemWeightMap[2123],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2123],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2123],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2123],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2123],
		-- {1, 150}
		sortWeight = 11
	},
	[2124] = {
		id = 2124,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 10820,
		itemWeightMap = __data_t__itemWeightMap[2124],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2124],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2124],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2124],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2124],
		-- {1, 150}
		sortWeight = 11
	},
	[2125] = {
		id = 2125,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 12540,
		itemWeightMap = __data_t__itemWeightMap[2125],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2125],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2125],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2125],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2125],
		-- {1, 150}
		sortWeight = 11
	},
	[2126] = {
		id = 2126,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 14140,
		itemWeightMap = __data_t__itemWeightMap[2126],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2126],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2126],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2126],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2126],
		-- {1, 150}
		sortWeight = 11
	},
	[2127] = {
		id = 2127,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 15600,
		itemWeightMap = __data_t__itemWeightMap[2127],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2127],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2127],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2127],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2127],
		-- {1, 150}
		sortWeight = 11
	},
	[2128] = {
		id = 2128,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 16940,
		itemWeightMap = __data_t__itemWeightMap[2128],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2128],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2128],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2128],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2128],
		-- {1, 150}
		sortWeight = 11
	},
	[2129] = {
		id = 2129,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 19940,
		itemWeightMap = __data_t__itemWeightMap[2129],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2129],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2129],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2129],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2129],
		-- {1, 150}
		sortWeight = 11
	},
	[2130] = {
		id = 2130,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 22680,
		itemWeightMap = __data_t__itemWeightMap[2130],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2130],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2130],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2130],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2130],
		-- {1, 150}
		sortWeight = 11
	},
	[2131] = {
		id = 2131,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 25160,
		itemWeightMap = __data_t__itemWeightMap[2131],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2131],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2131],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2131],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2131],
		-- {1, 150}
		sortWeight = 11
	},
	[2132] = {
		id = 2132,
		vipWeight = 100,
		position = 9,
		showUnable = true,
		itemCount = 27400,
		itemWeightMap = __data_t__itemWeightMap[2132],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2132],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2132],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2132],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2132],
		-- {1, 150}
		sortWeight = 11
	},
	[2201] = {
		id = 2201,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 1760,
		itemWeightMap = __data_t__itemWeightMap[2201],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2201],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2201],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2201],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2201],
		-- {1, 150}
		sortWeight = 12
	},
	[2202] = {
		id = 2202,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 2030,
		itemWeightMap = __data_t__itemWeightMap[2202],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2202],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2202],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2202],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2202],
		-- {1, 150}
		sortWeight = 12
	},
	[2203] = {
		id = 2203,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 2580,
		itemWeightMap = __data_t__itemWeightMap[2203],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2203],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2203],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2203],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2203],
		-- {1, 150}
		sortWeight = 12
	},
	[2204] = {
		id = 2204,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 3110,
		itemWeightMap = __data_t__itemWeightMap[2204],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2204],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2204],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2204],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2204],
		-- {1, 150}
		sortWeight = 12
	},
	[2205] = {
		id = 2205,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 3600,
		itemWeightMap = __data_t__itemWeightMap[2205],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2205],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2205],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2205],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2205],
		-- {1, 150}
		sortWeight = 12
	},
	[2206] = {
		id = 2206,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2206],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2206],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2206],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2206],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2206],
		-- {1, 150}
		sortWeight = 12
	},
	[2207] = {
		id = 2207,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 4490,
		itemWeightMap = __data_t__itemWeightMap[2207],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2207],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2207],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2207],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2207],
		-- {1, 150}
		sortWeight = 12
	},
	[2208] = {
		id = 2208,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 5410,
		itemWeightMap = __data_t__itemWeightMap[2208],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2208],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2208],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2208],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2208],
		-- {1, 150}
		sortWeight = 12
	},
	[2209] = {
		id = 2209,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 6270,
		itemWeightMap = __data_t__itemWeightMap[2209],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2209],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2209],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2209],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2209],
		-- {1, 150}
		sortWeight = 12
	},
	[2210] = {
		id = 2210,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 7070,
		itemWeightMap = __data_t__itemWeightMap[2210],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2210],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2210],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2210],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2210],
		-- {1, 150}
		sortWeight = 12
	},
	[2211] = {
		id = 2211,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 7800,
		itemWeightMap = __data_t__itemWeightMap[2211],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2211],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2211],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2211],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2211],
		-- {1, 150}
		sortWeight = 12
	},
	[2212] = {
		id = 2212,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 8470,
		itemWeightMap = __data_t__itemWeightMap[2212],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2212],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2212],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2212],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2212],
		-- {1, 150}
		sortWeight = 12
	},
	[2213] = {
		id = 2213,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 9970,
		itemWeightMap = __data_t__itemWeightMap[2213],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2213],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2213],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2213],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2213],
		-- {1, 150}
		sortWeight = 12
	},
	[2214] = {
		id = 2214,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 11340,
		itemWeightMap = __data_t__itemWeightMap[2214],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2214],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2214],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2214],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2214],
		-- {1, 150}
		sortWeight = 12
	},
	[2215] = {
		id = 2215,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 12580,
		itemWeightMap = __data_t__itemWeightMap[2215],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2215],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2215],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2215],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2215],
		-- {1, 150}
		sortWeight = 12
	},
	[2216] = {
		id = 2216,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 13700,
		itemWeightMap = __data_t__itemWeightMap[2216],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2216],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2216],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2216],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2216],
		-- {1, 150}
		sortWeight = 12
	},
	[2217] = {
		id = 2217,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 3520,
		itemWeightMap = __data_t__itemWeightMap[2217],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2217],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2217],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2217],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2217],
		-- {1, 150}
		sortWeight = 12
	},
	[2218] = {
		id = 2218,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2218],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2218],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2218],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2218],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2218],
		-- {1, 150}
		sortWeight = 12
	},
	[2219] = {
		id = 2219,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 5160,
		itemWeightMap = __data_t__itemWeightMap[2219],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2219],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2219],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2219],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2219],
		-- {1, 150}
		sortWeight = 12
	},
	[2220] = {
		id = 2220,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 6220,
		itemWeightMap = __data_t__itemWeightMap[2220],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2220],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2220],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2220],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2220],
		-- {1, 150}
		sortWeight = 12
	},
	[2221] = {
		id = 2221,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 7200,
		itemWeightMap = __data_t__itemWeightMap[2221],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2221],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2221],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2221],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2221],
		-- {1, 150}
		sortWeight = 12
	},
	[2222] = {
		id = 2222,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 8120,
		itemWeightMap = __data_t__itemWeightMap[2222],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2222],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2222],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2222],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2222],
		-- {1, 150}
		sortWeight = 12
	},
	[2223] = {
		id = 2223,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 8980,
		itemWeightMap = __data_t__itemWeightMap[2223],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2223],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2223],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2223],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2223],
		-- {1, 150}
		sortWeight = 12
	},
	[2224] = {
		id = 2224,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 10820,
		itemWeightMap = __data_t__itemWeightMap[2224],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2224],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2224],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2224],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2224],
		-- {1, 150}
		sortWeight = 12
	},
	[2225] = {
		id = 2225,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 12540,
		itemWeightMap = __data_t__itemWeightMap[2225],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2225],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2225],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2225],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2225],
		-- {1, 150}
		sortWeight = 12
	},
	[2226] = {
		id = 2226,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 14140,
		itemWeightMap = __data_t__itemWeightMap[2226],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2226],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2226],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2226],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2226],
		-- {1, 150}
		sortWeight = 12
	},
	[2227] = {
		id = 2227,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 15600,
		itemWeightMap = __data_t__itemWeightMap[2227],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2227],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2227],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2227],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2227],
		-- {1, 150}
		sortWeight = 12
	},
	[2228] = {
		id = 2228,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 16940,
		itemWeightMap = __data_t__itemWeightMap[2228],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2228],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2228],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2228],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2228],
		-- {1, 150}
		sortWeight = 12
	},
	[2229] = {
		id = 2229,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 19940,
		itemWeightMap = __data_t__itemWeightMap[2229],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2229],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2229],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2229],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2229],
		-- {1, 150}
		sortWeight = 12
	},
	[2230] = {
		id = 2230,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 22680,
		itemWeightMap = __data_t__itemWeightMap[2230],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2230],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2230],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2230],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2230],
		-- {1, 150}
		sortWeight = 12
	},
	[2231] = {
		id = 2231,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 25160,
		itemWeightMap = __data_t__itemWeightMap[2231],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2231],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2231],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2231],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2231],
		-- {1, 150}
		sortWeight = 12
	},
	[2232] = {
		id = 2232,
		vipWeight = 100,
		position = 10,
		showUnable = true,
		itemCount = 27400,
		itemWeightMap = __data_t__itemWeightMap[2232],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2232],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2232],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2232],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2232],
		-- {1, 150}
		sortWeight = 12
	},
	[2301] = {
		id = 2301,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 1760,
		itemWeightMap = __data_t__itemWeightMap[2301],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2301],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2301],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2301],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2301],
		-- {1, 150}
		sortWeight = 13
	},
	[2302] = {
		id = 2302,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 2030,
		itemWeightMap = __data_t__itemWeightMap[2302],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2302],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2302],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2302],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2302],
		-- {1, 150}
		sortWeight = 13
	},
	[2303] = {
		id = 2303,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 2580,
		itemWeightMap = __data_t__itemWeightMap[2303],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2303],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2303],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2303],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2303],
		-- {1, 150}
		sortWeight = 13
	},
	[2304] = {
		id = 2304,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 3110,
		itemWeightMap = __data_t__itemWeightMap[2304],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2304],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2304],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2304],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2304],
		-- {1, 150}
		sortWeight = 13
	},
	[2305] = {
		id = 2305,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 3600,
		itemWeightMap = __data_t__itemWeightMap[2305],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2305],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2305],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2305],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2305],
		-- {1, 150}
		sortWeight = 13
	},
	[2306] = {
		id = 2306,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2306],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2306],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2306],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2306],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2306],
		-- {1, 150}
		sortWeight = 13
	},
	[2307] = {
		id = 2307,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 4490,
		itemWeightMap = __data_t__itemWeightMap[2307],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2307],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2307],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2307],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2307],
		-- {1, 150}
		sortWeight = 13
	},
	[2308] = {
		id = 2308,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 5410,
		itemWeightMap = __data_t__itemWeightMap[2308],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2308],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2308],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2308],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2308],
		-- {1, 150}
		sortWeight = 13
	},
	[2309] = {
		id = 2309,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 6270,
		itemWeightMap = __data_t__itemWeightMap[2309],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2309],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2309],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2309],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2309],
		-- {1, 150}
		sortWeight = 13
	},
	[2310] = {
		id = 2310,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 7070,
		itemWeightMap = __data_t__itemWeightMap[2310],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2310],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2310],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2310],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2310],
		-- {1, 150}
		sortWeight = 13
	},
	[2311] = {
		id = 2311,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 7800,
		itemWeightMap = __data_t__itemWeightMap[2311],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2311],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2311],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2311],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2311],
		-- {1, 150}
		sortWeight = 13
	},
	[2312] = {
		id = 2312,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 8470,
		itemWeightMap = __data_t__itemWeightMap[2312],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2312],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2312],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2312],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2312],
		-- {1, 150}
		sortWeight = 13
	},
	[2313] = {
		id = 2313,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 9970,
		itemWeightMap = __data_t__itemWeightMap[2313],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2313],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2313],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2313],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2313],
		-- {1, 150}
		sortWeight = 13
	},
	[2314] = {
		id = 2314,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 11340,
		itemWeightMap = __data_t__itemWeightMap[2314],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2314],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2314],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2314],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2314],
		-- {1, 150}
		sortWeight = 13
	},
	[2315] = {
		id = 2315,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 12580,
		itemWeightMap = __data_t__itemWeightMap[2315],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2315],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2315],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2315],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2315],
		-- {1, 150}
		sortWeight = 13
	},
	[2316] = {
		id = 2316,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 13700,
		itemWeightMap = __data_t__itemWeightMap[2316],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2316],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2316],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2316],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2316],
		-- {1, 150}
		sortWeight = 13
	},
	[2317] = {
		id = 2317,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 3520,
		itemWeightMap = __data_t__itemWeightMap[2317],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2317],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2317],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2317],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2317],
		-- {1, 150}
		sortWeight = 13
	},
	[2318] = {
		id = 2318,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2318],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2318],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2318],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2318],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2318],
		-- {1, 150}
		sortWeight = 13
	},
	[2319] = {
		id = 2319,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 5160,
		itemWeightMap = __data_t__itemWeightMap[2319],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2319],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2319],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2319],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2319],
		-- {1, 150}
		sortWeight = 13
	},
	[2320] = {
		id = 2320,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 6220,
		itemWeightMap = __data_t__itemWeightMap[2320],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2320],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2320],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2320],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2320],
		-- {1, 150}
		sortWeight = 13
	},
	[2321] = {
		id = 2321,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 7200,
		itemWeightMap = __data_t__itemWeightMap[2321],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2321],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2321],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2321],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2321],
		-- {1, 150}
		sortWeight = 13
	},
	[2322] = {
		id = 2322,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 8120,
		itemWeightMap = __data_t__itemWeightMap[2322],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2322],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2322],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2322],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2322],
		-- {1, 150}
		sortWeight = 13
	},
	[2323] = {
		id = 2323,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 8980,
		itemWeightMap = __data_t__itemWeightMap[2323],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2323],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2323],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2323],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2323],
		-- {1, 150}
		sortWeight = 13
	},
	[2324] = {
		id = 2324,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 10820,
		itemWeightMap = __data_t__itemWeightMap[2324],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2324],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2324],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2324],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2324],
		-- {1, 150}
		sortWeight = 13
	},
	[2325] = {
		id = 2325,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 12540,
		itemWeightMap = __data_t__itemWeightMap[2325],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2325],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2325],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2325],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2325],
		-- {1, 150}
		sortWeight = 13
	},
	[2326] = {
		id = 2326,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 14140,
		itemWeightMap = __data_t__itemWeightMap[2326],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2326],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2326],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2326],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2326],
		-- {1, 150}
		sortWeight = 13
	},
	[2327] = {
		id = 2327,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 15600,
		itemWeightMap = __data_t__itemWeightMap[2327],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2327],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2327],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2327],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2327],
		-- {1, 150}
		sortWeight = 13
	},
	[2328] = {
		id = 2328,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 16940,
		itemWeightMap = __data_t__itemWeightMap[2328],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2328],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2328],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2328],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2328],
		-- {1, 150}
		sortWeight = 13
	},
	[2329] = {
		id = 2329,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 19940,
		itemWeightMap = __data_t__itemWeightMap[2329],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2329],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2329],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2329],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2329],
		-- {1, 150}
		sortWeight = 13
	},
	[2330] = {
		id = 2330,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 22680,
		itemWeightMap = __data_t__itemWeightMap[2330],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2330],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2330],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2330],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2330],
		-- {1, 150}
		sortWeight = 13
	},
	[2331] = {
		id = 2331,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 25160,
		itemWeightMap = __data_t__itemWeightMap[2331],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2331],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2331],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2331],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2331],
		-- {1, 150}
		sortWeight = 13
	},
	[2332] = {
		id = 2332,
		vipWeight = 100,
		position = 11,
		showUnable = true,
		itemCount = 27400,
		itemWeightMap = __data_t__itemWeightMap[2332],
		-- {[8203] = 1, __size = 1}
		costMap = __data_t__costMap[2332],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2332],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2332],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2332],
		-- {1, 150}
		sortWeight = 13
	},
	[2400] = {
		id = 2400,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 1760,
		itemWeightMap = __data_t__itemWeightMap[2400],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2400],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2400],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2400],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2400],
		-- {1, 150}
		sortWeight = 14
	},
	[2401] = {
		id = 2401,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 2030,
		itemWeightMap = __data_t__itemWeightMap[2401],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2401],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2401],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2401],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2401],
		-- {1, 150}
		sortWeight = 14
	},
	[2402] = {
		id = 2402,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 2580,
		itemWeightMap = __data_t__itemWeightMap[2402],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2402],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2402],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2402],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2402],
		-- {1, 150}
		sortWeight = 14
	},
	[2403] = {
		id = 2403,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 3110,
		itemWeightMap = __data_t__itemWeightMap[2403],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2403],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2403],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2403],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2403],
		-- {1, 150}
		sortWeight = 14
	},
	[2404] = {
		id = 2404,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 3600,
		itemWeightMap = __data_t__itemWeightMap[2404],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2404],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2404],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2404],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2404],
		-- {1, 150}
		sortWeight = 14
	},
	[2405] = {
		id = 2405,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2405],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2405],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2405],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2405],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2405],
		-- {1, 150}
		sortWeight = 14
	},
	[2406] = {
		id = 2406,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 4490,
		itemWeightMap = __data_t__itemWeightMap[2406],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2406],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2406],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2406],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2406],
		-- {1, 150}
		sortWeight = 14
	},
	[2407] = {
		id = 2407,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 5410,
		itemWeightMap = __data_t__itemWeightMap[2407],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2407],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2407],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2407],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2407],
		-- {1, 150}
		sortWeight = 14
	},
	[2408] = {
		id = 2408,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 6270,
		itemWeightMap = __data_t__itemWeightMap[2408],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2408],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2408],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2408],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2408],
		-- {1, 150}
		sortWeight = 14
	},
	[2409] = {
		id = 2409,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 7070,
		itemWeightMap = __data_t__itemWeightMap[2409],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2409],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2409],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2409],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2409],
		-- {1, 150}
		sortWeight = 14
	},
	[2410] = {
		id = 2410,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 7800,
		itemWeightMap = __data_t__itemWeightMap[2410],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2410],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2410],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2410],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2410],
		-- {1, 150}
		sortWeight = 14
	},
	[2411] = {
		id = 2411,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 8470,
		itemWeightMap = __data_t__itemWeightMap[2411],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2411],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2411],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2411],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2411],
		-- {1, 150}
		sortWeight = 14
	},
	[2412] = {
		id = 2412,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 9970,
		itemWeightMap = __data_t__itemWeightMap[2412],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2412],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2412],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2412],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2412],
		-- {1, 150}
		sortWeight = 14
	},
	[2413] = {
		id = 2413,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 11340,
		itemWeightMap = __data_t__itemWeightMap[2413],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2413],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2413],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2413],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2413],
		-- {1, 150}
		sortWeight = 14
	},
	[2414] = {
		id = 2414,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 12580,
		itemWeightMap = __data_t__itemWeightMap[2414],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2414],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2414],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2414],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2414],
		-- {1, 150}
		sortWeight = 14
	},
	[2415] = {
		id = 2415,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 13700,
		itemWeightMap = __data_t__itemWeightMap[2415],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2415],
		-- {['rmb'] = 80, __size = 1}
		levelRange = __data_t__levelRange[2415],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2415],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2415],
		-- {1, 150}
		sortWeight = 14
	},
	[2416] = {
		id = 2416,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 3520,
		itemWeightMap = __data_t__itemWeightMap[2416],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2416],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2416],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2416],
		-- {1, 5}
		centerBuildingRange = __data_t__centerBuildingRange[2416],
		-- {1, 150}
		sortWeight = 14
	},
	[2417] = {
		id = 2417,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 4060,
		itemWeightMap = __data_t__itemWeightMap[2417],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2417],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2417],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2417],
		-- {6, 6}
		centerBuildingRange = __data_t__centerBuildingRange[2417],
		-- {1, 150}
		sortWeight = 14
	},
	[2418] = {
		id = 2418,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 5160,
		itemWeightMap = __data_t__itemWeightMap[2418],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2418],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2418],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2418],
		-- {7, 7}
		centerBuildingRange = __data_t__centerBuildingRange[2418],
		-- {1, 150}
		sortWeight = 14
	},
	[2419] = {
		id = 2419,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 6220,
		itemWeightMap = __data_t__itemWeightMap[2419],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2419],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2419],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2419],
		-- {8, 8}
		centerBuildingRange = __data_t__centerBuildingRange[2419],
		-- {1, 150}
		sortWeight = 14
	},
	[2420] = {
		id = 2420,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 7200,
		itemWeightMap = __data_t__itemWeightMap[2420],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2420],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2420],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2420],
		-- {9, 9}
		centerBuildingRange = __data_t__centerBuildingRange[2420],
		-- {1, 150}
		sortWeight = 14
	},
	[2421] = {
		id = 2421,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 8120,
		itemWeightMap = __data_t__itemWeightMap[2421],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2421],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2421],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2421],
		-- {10, 10}
		centerBuildingRange = __data_t__centerBuildingRange[2421],
		-- {1, 150}
		sortWeight = 14
	},
	[2422] = {
		id = 2422,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 8980,
		itemWeightMap = __data_t__itemWeightMap[2422],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2422],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2422],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2422],
		-- {11, 11}
		centerBuildingRange = __data_t__centerBuildingRange[2422],
		-- {1, 150}
		sortWeight = 14
	},
	[2423] = {
		id = 2423,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 10820,
		itemWeightMap = __data_t__itemWeightMap[2423],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2423],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2423],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2423],
		-- {12, 12}
		centerBuildingRange = __data_t__centerBuildingRange[2423],
		-- {1, 150}
		sortWeight = 14
	},
	[2424] = {
		id = 2424,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 12540,
		itemWeightMap = __data_t__itemWeightMap[2424],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2424],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2424],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2424],
		-- {13, 13}
		centerBuildingRange = __data_t__centerBuildingRange[2424],
		-- {1, 150}
		sortWeight = 14
	},
	[2425] = {
		id = 2425,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 14140,
		itemWeightMap = __data_t__itemWeightMap[2425],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2425],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2425],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2425],
		-- {14, 14}
		centerBuildingRange = __data_t__centerBuildingRange[2425],
		-- {1, 150}
		sortWeight = 14
	},
	[2426] = {
		id = 2426,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 15600,
		itemWeightMap = __data_t__itemWeightMap[2426],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2426],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2426],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2426],
		-- {15, 15}
		centerBuildingRange = __data_t__centerBuildingRange[2426],
		-- {1, 150}
		sortWeight = 14
	},
	[2427] = {
		id = 2427,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 16940,
		itemWeightMap = __data_t__itemWeightMap[2427],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2427],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2427],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2427],
		-- {16, 16}
		centerBuildingRange = __data_t__centerBuildingRange[2427],
		-- {1, 150}
		sortWeight = 14
	},
	[2428] = {
		id = 2428,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 19940,
		itemWeightMap = __data_t__itemWeightMap[2428],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2428],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2428],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2428],
		-- {17, 17}
		centerBuildingRange = __data_t__centerBuildingRange[2428],
		-- {1, 150}
		sortWeight = 14
	},
	[2429] = {
		id = 2429,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 22680,
		itemWeightMap = __data_t__itemWeightMap[2429],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2429],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2429],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2429],
		-- {18, 18}
		centerBuildingRange = __data_t__centerBuildingRange[2429],
		-- {1, 150}
		sortWeight = 14
	},
	[2430] = {
		id = 2430,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 25160,
		itemWeightMap = __data_t__itemWeightMap[2430],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2430],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2430],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2430],
		-- {19, 19}
		centerBuildingRange = __data_t__centerBuildingRange[2430],
		-- {1, 150}
		sortWeight = 14
	},
	[2431] = {
		id = 2431,
		vipWeight = 100,
		position = 12,
		showUnable = true,
		itemCount = 27400,
		itemWeightMap = __data_t__itemWeightMap[2431],
		-- {[8202] = 1, __size = 1}
		costMap = __data_t__costMap[2431],
		-- {['rmb'] = 160, __size = 1}
		levelRange = __data_t__levelRange[2431],
		-- {1, 150}
		centerBuildingFilterRange = __data_t__centerBuildingFilterRange[2431],
		-- {20, 20}
		centerBuildingRange = __data_t__centerBuildingRange[2431],
		-- {1, 150}
		sortWeight = 14
	},
	__size = 149,
	__default = {
		__index = {
			vipWeight = 1,
			position = 0,
			limitType = 0,
			endDate = 20990101,
			beginDate = 0,
			vipStart = 0,
			showUnable = false,
			limitTimes = 0,
			itemCount = 0,
			itemWeightMap = {__size = 0},
			costMap = {['coin3'] = 0, __size = 1},
			levelRange = __data_t__levelRange["default"]	--[[ {1, 100}]],
			centerBuildingFilterRange = __data_t__centerBuildingFilterRange["default"]	--[[ {1, 150}]],
			centerBuildingRange = __data_t__centerBuildingRange["default"]	--[[ {1, 100}]],
			languages = {'cn', 'tw', 'en', 'en_us', 'en_eu', 'vn', 'th', 'kr'},
			sortWeight = 0
		}
	}
}
return csv.town.supermarket