--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[3] = {['rmb'] = 0, __size = 1}, 
	[5] = {['rmb'] = 60, __size = 1}, 
	[7] = {['rmb'] = 300, __size = 1}, __size = 4}
local __data_t__items = {
	["default"] = __predefine_t__[1]
}
local __data_t__costMap = {
	[1] = __predefine_t__[3],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[7],
	[2] = __predefine_t__[5],
	[102] = __predefine_t__[5],
	[103] = __predefine_t__[7],
	[101] = __predefine_t__[3]
}

csv['yunying']['daily_random_gift'] = {
	[1] = {
		id = 1,
		huodongID = 23401,
		name = '每日免费礼包',
		items = {['gold'] = 50000, [8122] = 5, __size = 2},
		costMap = __data_t__costMap[1],
		-- {['rmb'] = 0, __size = 1}
		refresh = true,
		icon = 'activity/direct_gift/icon_cjbx.png',
		oldPrice = 60,
		sort = 1
	},
	[2] = {
		id = 2,
		huodongID = 23401,
		name = '超值惊喜礼包',
		levelLimit = 10,
		items = {['gold'] = 100000, [8125] = 50, [8122] = 10, __size = 3},
		costMap = __data_t__costMap[2],
		-- {['rmb'] = 60, __size = 1}
		refresh = true,
		icon = 'activity/direct_gift/icon_cjbx1.png',
		oldPrice = 120,
		sort = 2
	},
	[3] = {
		id = 3,
		huodongID = 23401,
		name = '豪华惊喜礼包',
		levelLimit = 20,
		items = {[8126] = 30, ['gold'] = 200000, [8122] = 20, __size = 3},
		costMap = __data_t__costMap[3],
		-- {['rmb'] = 300, __size = 1}
		refresh = true,
		icon = 'activity/direct_gift/icon_cjbx2.png',
		oldPrice = 600,
		sort = 3
	},
	[101] = {
		id = 101,
		huodongID = 23500,
		name = '每日免费礼包',
		items = {['gold'] = 50000, [8121] = 5, __size = 2},
		costMap = __data_t__costMap[101],
		-- {['rmb'] = 0, __size = 1}
		refresh = true,
		icon = 'activity/direct_gift/icon_cjbx.png',
		oldPrice = 60,
		sort = 1
	},
	[102] = {
		id = 102,
		huodongID = 23500,
		name = '超值惊喜礼包',
		levelLimit = 10,
		items = {['gold'] = 100000, [8121] = 10, __size = 2},
		costMap = __data_t__costMap[102],
		-- {['rmb'] = 60, __size = 1}
		refresh = true,
		icon = 'activity/direct_gift/icon_cjbx1.png',
		oldPrice = 120,
		sort = 2
	},
	[103] = {
		id = 103,
		huodongID = 23500,
		name = '豪华惊喜礼包',
		levelLimit = 20,
		items = {['gold'] = 200000, [8121] = 20, __size = 2},
		costMap = __data_t__costMap[103],
		-- {['rmb'] = 300, __size = 1}
		refresh = true,
		icon = 'activity/direct_gift/icon_cjbx2.png',
		oldPrice = 600,
		sort = 3
	},
	__size = 6,
	__default = {
		__index = {
			huodongID = 0,
			name = '',
			levelLimit = 1,
			limit = 1,
			items = __data_t__items["default"]	--[[ {__size = 0}]],
			costMap = __data_t__costMap["default"]	--[[ {__size = 0}]],
			rechargeID = -1,
			refresh = false,
			icon = '',
			oldPrice = 0,
			sort = 0
		}
	}
}
return csv.yunying.daily_random_gift