--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['huodongcloth_level'] = {
	[1] = {
		id = 1,
		huodongID = 101030,
		level = 0,
		needExp = 100,
		unlockPart = 10000
	},
	[2] = {
		id = 2,
		huodongID = 101030,
		needExp = 200,
		award = {['gold'] = 5880000, [2333] = 1, [925] = 1, [6220] = 1, __size = 4},
		unlockPart = 10001
	},
	[3] = {
		id = 3,
		huodongID = 101030,
		level = 2,
		needExp = 300,
		award = {[2300] = 1, ['gold'] = 8880000, [521] = 8, [500] = 8, __size = 4}
	},
	[4] = {
		id = 4,
		huodongID = 101030,
		level = 3,
		needExp = 400,
		award = {['gold'] = 8880000, [2400] = 1, [521] = 18, [500] = 18, __size = 4}
	},
	[5] = {
		id = 5,
		huodongID = 101030,
		level = 4,
		needExp = 500,
		award = {[2008] = 1, ['gold'] = 8880000, [521] = 28, [500] = 28, __size = 4},
		unlockPart = 1
	},
	[6] = {
		id = 6,
		huodongID = 101030,
		level = 5,
		needExp = 600,
		award = {[2238] = 1, ['gold'] = 8880000, [521] = 42, [500] = 42, __size = 4}
	},
	[7] = {
		id = 7,
		huodongID = 101030,
		level = 6,
		needExp = 700,
		award = {['gold'] = 8880000, [937] = 2, [521] = 58, [500] = 58, __size = 4}
	},
	[8] = {
		id = 8,
		huodongID = 101030,
		level = 7,
		needExp = 800,
		award = {['gold'] = 8880000, [521] = 58, [500] = 58, [851] = 2888, __size = 4},
		unlockPart = 10002
	},
	[9] = {
		id = 9,
		huodongID = 101030,
		level = 8,
		needExp = 900,
		award = {[452] = 2888, ['gold'] = 8880000, [521] = 58, [500] = 58, __size = 4}
	},
	[10] = {
		id = 10,
		huodongID = 101030,
		level = 9,
		needExp = 1000,
		award = {['gold'] = 8880000, [453] = 5888, [521] = 58, [500] = 58, __size = 4}
	},
	[11] = {
		id = 11,
		huodongID = 101030,
		level = 10,
		needExp = 1500,
		award = {['gold'] = 8880000, [521] = 88, [500] = 88, ['coin22'] = 588, __size = 4},
		unlockPart = 2
	},
	[12] = {
		id = 12,
		huodongID = 101030,
		level = 11,
		needExp = 2000,
		award = {[702] = 5, [2181] = 1, [521] = 188, [500] = 188, __size = 4}
	},
	[13] = {
		id = 13,
		huodongID = 101030,
		level = 12,
		needExp = 3000,
		award = {[8834] = 10, [521] = 288, [8833] = 20, [2153] = 1, __size = 4},
		unlockPart = 10003
	},
	[14] = {
		id = 14,
		huodongID = 101030,
		level = 13,
		needExp = 4000,
		award = {[7325] = 10, [2153] = 2, [521] = 588, [994] = 10, __size = 4}
	},
	[15] = {
		id = 15,
		huodongID = 101030,
		level = 14,
		needExp = 5000,
		award = {[133] = 288, [705] = 2, [521] = 888, [703] = 2, __size = 4},
		unlockPart = 3
	},
	[16] = {
		id = 16,
		huodongID = 101030,
		level = 15,
		needExp = 6000,
		award = {[2103] = 3000, [9991] = 1, [6071] = 2000, [2153] = 5, __size = 4}
	},
	[101] = {
		id = 101,
		huodongID = 10001,
		level = 0,
		needExp = 50,
		unlockPart = 10000
	},
	[102] = {
		id = 102,
		huodongID = 10001,
		needExp = 100,
		award = {[519] = 3, [951] = 5, [21941] = 5, [2319] = 1, __size = 4},
		unlockPart = 10001
	},
	[103] = {
		id = 103,
		huodongID = 10001,
		level = 2,
		needExp = 150,
		award = {['stamina'] = 100, ['gold'] = 288000, [5000] = 100, [21951] = 5, __size = 4},
		unlockPart = 1
	},
	[104] = {
		id = 104,
		huodongID = 10001,
		level = 3,
		needExp = 250,
		award = {[930] = 100, [21941] = 10, [503] = 5, [2237] = 1, __size = 4}
	},
	[105] = {
		id = 105,
		huodongID = 10001,
		level = 4,
		needExp = 350,
		award = {[902] = 20, [901] = 30, ['rmb'] = 188, [21951] = 10, __size = 4},
		unlockPart = 10002
	},
	[106] = {
		id = 106,
		huodongID = 10001,
		level = 5,
		needExp = 450,
		award = {[21941] = 10, [922] = 1, [2020] = 1, [16] = 30, __size = 4}
	},
	[107] = {
		id = 107,
		huodongID = 10001,
		level = 6,
		needExp = 600,
		award = {[4000] = 300, ['gold'] = 588000, [962] = 2, [21951] = 10, __size = 4},
		unlockPart = 2
	},
	[108] = {
		id = 108,
		huodongID = 10001,
		level = 7,
		needExp = 750,
		award = {[604] = 10, [2238] = 1, [21941] = 15, [602] = 20, __size = 4}
	},
	[109] = {
		id = 109,
		huodongID = 10001,
		level = 8,
		needExp = 1000,
		award = {['gold'] = 880000, [973] = 1, [529] = 5000, [21951] = 15, __size = 4},
		unlockPart = 10003
	},
	[110] = {
		id = 110,
		huodongID = 10001,
		level = 9,
		needExp = 1250,
		award = {[21941] = 20, [8000] = 1, [6050] = 1, [501] = 3, __size = 4}
	},
	[111] = {
		id = 111,
		huodongID = 10001,
		level = 10,
		needExp = 1250,
		award = {[6059] = 1, ['rmb'] = 388, [2152] = 1, [21951] = 20, __size = 4},
		unlockPart = 3
	},
	__size = 27,
	__default = {
		__index = {
			huodongID = 0,
			level = 1,
			needExp = 0,
			award = {__size = 0},
			unlockPart = 0
		}
	}
}
return csv.yunying.huodongcloth_level