--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['huodongboss_config'] = {
	[1] = {
		id = 1,
		huodongID = 2020,
		staminaWeightMin = 0.005,
		staminaWeightMax = 0.015,
		dailyCountLimit = 5,
		cd = 60,
		gateLibID = 2020,
		dailyChallengeLimit = 10
	},
	[2] = {
		id = 2,
		huodongID = 2021,
		staminaWeightMin = 0.005,
		staminaWeightMax = 0.015,
		dailyCountLimit = 5,
		cd = 60,
		gateLibID = 2021,
		dailyChallengeLimit = 10
	},
	[3] = {
		id = 3,
		huodongID = 2022,
		staminaWeightMin = 0.005,
		staminaWeightMax = 0.015,
		dailyCountLimit = 5,
		cd = 60,
		gateLibID = 2022,
		dailyChallengeLimit = 10
	},
	__size = 3,
	__default = {
		__index = {
			huodongID = 0,
			staminaWeightMin = 0,
			staminaWeightMax = 0,
			dailyCountLimit = 0,
			cd = 0,
			res = '',
			dailyChallengeLimit = 0
		}
	}
}
return csv.yunying.huodongboss_config