--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['levelaward'] = {
	[1] = {
		id = 1,
		huodongID = 3001,
		needLevel = 5,
		desc = '等级到达5级',
		desc_tw = '等級到達5級',
		desc_en = 'Reach Lv.5',
		desc_vn = 'Đẳng cấp đến 5 Cấp',
		desc_kr = '레벨 5 달성',
		award = {[11] = 10, ['gold'] = 10000, ['rmb'] = 50, __size = 3}
	},
	[2] = {
		id = 2,
		huodongID = 3001,
		needLevel = 10,
		desc = '等级到达10级',
		desc_tw = '等級到達10級',
		desc_en = 'Reach Lv.10',
		desc_vn = 'Đẳng cấp đến 10 Cấp',
		desc_kr = '레벨 10 달성',
		award = {[11] = 15, ['gold'] = 20000, ['rmb'] = 60, __size = 3}
	},
	[3] = {
		id = 3,
		huodongID = 3001,
		needLevel = 15,
		desc = '等级到达15级',
		desc_tw = '等級到達15級',
		desc_en = 'Reach Lv.15',
		desc_vn = 'Đạt LV15',
		desc_kr = '레벨 15 달성',
		award = {[11] = 20, ['gold'] = 30000, ['rmb'] = 70, __size = 3}
	},
	[4] = {
		id = 4,
		huodongID = 3001,
		needLevel = 20,
		desc = '等级到达20级',
		desc_tw = '等級到達20級',
		desc_en = 'Reach Lv.20',
		desc_vn = 'Đạt LV20',
		desc_kr = '레벨 20 달성',
		award = {['gold'] = 40000, [12] = 20, ['rmb'] = 80, __size = 3}
	},
	[5] = {
		id = 5,
		huodongID = 3001,
		needLevel = 25,
		desc = '等级到达25级',
		desc_tw = '等級到達25級',
		desc_en = 'Reach Lv.25',
		desc_vn = 'Đạt LV25',
		desc_kr = '레벨 25 달성',
		award = {['gold'] = 50000, [12] = 25, ['rmb'] = 90, __size = 3}
	},
	[6] = {
		id = 6,
		huodongID = 3001,
		needLevel = 30,
		desc = '等级到达30级',
		desc_tw = '等級到達30級',
		desc_en = 'Reach Lv.30',
		desc_vn = 'Đạt LV30',
		desc_kr = '레벨 30 달성',
		award = {['gold'] = 60000, [12] = 30, ['rmb'] = 100, __size = 3}
	},
	[7] = {
		id = 7,
		huodongID = 3001,
		needLevel = 35,
		desc = '等级到达35级',
		desc_tw = '等級到達35級',
		desc_en = 'Reach Lv.35',
		desc_vn = 'Đạt LV35',
		desc_kr = '레벨 35 달성',
		award = {['gold'] = 70000, [12] = 35, ['rmb'] = 110, __size = 3}
	},
	[8] = {
		id = 8,
		huodongID = 3001,
		needLevel = 40,
		desc = '等级到达40级',
		desc_tw = '等級到達40級',
		desc_en = 'Reach Lv.40',
		desc_vn = 'Đạt LV40',
		desc_kr = '레벨 40 달성',
		award = {['gold'] = 80000, [12] = 40, ['rmb'] = 120, __size = 3}
	},
	[9] = {
		id = 9,
		huodongID = 3001,
		needLevel = 45,
		desc = '等级到达45级',
		desc_tw = '等級到達45級',
		desc_en = 'Reach Lv.45',
		desc_vn = 'Đạt LV45',
		desc_kr = '레벨 45 달성',
		award = {['gold'] = 90000, ['rmb'] = 130, [13] = 20, __size = 3}
	},
	[10] = {
		id = 10,
		huodongID = 3001,
		needLevel = 50,
		desc = '等级到达50级',
		desc_tw = '等級到達50級',
		desc_en = 'Reach Lv.50',
		desc_vn = 'Đạt LV50',
		desc_kr = '레벨 50 달성',
		award = {['gold'] = 100000, ['rmb'] = 140, [13] = 25, __size = 3}
	},
	__size = 10,
	__default = {
		__index = {
			huodongID = 0,
			needLevel = 1,
			desc = '',
			desc_tw = '',
			desc_en = '',
			desc_vn = '',
			desc_kr = '',
			award = {__size = 0}
		}
	}
}
return csv.yunying.levelaward