--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, __size = 1}
local __data_t__pngResource = {
	["default"] = __predefine_t__[1]
}
local __data_t__spineResource = {
	["default"] = __predefine_t__[1]
}
local __data_t__range = {
	["default"] = __predefine_t__[1]
}

csv['yunying']['skyscraper_resources'] = {
	[1] = {
		id = 1,
		huodongID = 1,
		range = {0, 1},
		pngResource = {'activity/sky_scraper/img_fz1.png', 'activity/sky_scraper/img_fz5.png', 'activity/sky_scraper/img_fz6.png', 'activity/sky_scraper/img_fz8.png'}
	},
	[2] = {
		id = 2,
		huodongID = 1,
		range = {1, 35},
		pngResource = {'activity/sky_scraper/img_fz1.png', 'activity/sky_scraper/img_fz2.png', 'activity/sky_scraper/img_fz3.png', 'activity/sky_scraper/img_fz4.png', 'activity/sky_scraper/img_fz5.png', 'activity/sky_scraper/img_fz6.png', 'activity/sky_scraper/img_fz7.png', 'activity/sky_scraper/img_fz8.png', 'activity/sky_scraper/img_fz9.png', 'activity/sky_scraper/img_fz10.png', 'activity/sky_scraper/img_fz11.png', 'activity/sky_scraper/img_fz12.png', 'activity/sky_scraper/img_fz13.png', 'activity/sky_scraper/img_fz14.png', 'activity/sky_scraper/img_fz15.png'}
	},
	[3] = {
		id = 3,
		huodongID = 1,
		range = {35, 50},
		spineResource = {'skyscraper/floor_2.skel', 'skyscraper/floor_3.skel', 'skyscraper/floor_5.skel', 'skyscraper/flooor_6.skel'}
	},
	[4] = {
		id = 4,
		huodongID = 1,
		range = {50, 51},
		spineResource = {'skyscraper/floor_1.skel'}
	},
	__size = 4,
	__default = {
		__index = {
			huodongID = 1001,
			range = __data_t__range["default"]	--[[ {}]],
			pngResource = __data_t__pngResource["default"]	--[[ {}]],
			spineResource = __data_t__spineResource["default"]	--[[ {}]]
		}
	}
}
return csv.yunying.skyscraper_resources