--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, __size = 1}
local __data_t__advanceAttrs = {
	["default"] = __predefine_t__[1]
}
local __data_t__levelAttrs = {
	["default"] = __predefine_t__[1]
}

csv['meteorite']['helditem_effect'] = {
	[1] = {
		id = 1,
		levelAttrs = {{10, '0.1%'}, {20, '0.2%'}, {30, '0.3%'}, {40, '0.5%'}, {50, '0.75%'}, {60, '1%'}, {70, '1.3%'}, {80, '1.6%'}},
		advanceAttrs = {'0.04%', '0.12%', '0.2%', '0.32%', '0.48%', '0.72%', '1%'},
		rarityAttr = '0.30%'
	},
	[2] = {
		id = 2,
		levelAttrs = {{10, '0.12%'}, {20, '0.24%'}, {30, '0.36%'}, {40, '0.6%'}, {50, '0.9%'}, {60, '1.2%'}, {70, '1.56%'}, {80, '1.92%'}},
		advanceAttrs = {'0.06%', '0.18%', '0.3%', '0.48%', '0.72%', '1.08%', '1.5%'},
		rarityAttr = '0.60%'
	},
	[3] = {
		id = 3,
		levelAttrs = {{10, '0.24%'}, {20, '0.48%'}, {30, '0.72%'}, {40, '1.2%'}, {50, '1.8%'}, {60, '2.4%'}, {70, '3.12%'}, {80, '3.84%'}},
		advanceAttrs = {'0.2%', '0.6%', '1%', '1.6%', '2.4%', '3.6%', '5%'},
		rarityAttr = '1.00%'
	},
	[4] = {
		id = 4,
		levelAttrs = {{10, '0.5%'}, {20, '1%'}, {30, '1.5%'}, {40, '2.5%'}, {50, '3.75%'}, {60, '5%'}, {70, '6.5%'}, {80, '8%'}},
		advanceAttrs = {'0.5%', '1.5%', '2.5%', '4%', '6%', '9%', '12.5%'},
		rarityAttr = '1.80%'
	},
	[5] = {
		id = 5,
		levelAttrs = {{10, '1.2%'}, {20, '2.4%'}, {30, '3.6%'}, {40, '6%'}, {50, '9%'}, {60, '12%'}, {70, '15.6%'}, {80, '19.2%'}},
		advanceAttrs = {'1.2%', '3.6%', '6%', '9.6%', '14.4%', '21.6%', '30%'},
		rarityAttr = '4.50%'
	},
	[6] = {
		id = 6,
		levelAttrs = {{10, '1.5%'}, {20, '3%'}, {30, '4.5%'}, {40, '7.5%'}, {50, '11.25%'}, {60, '15%'}, {70, '19.5%'}, {80, '24%'}},
		advanceAttrs = {'1.5%', '4.5%', '7.5%', '12%', '18%', '27%', '37.5%'},
		rarityAttr = '7%'
	},
	__size = 6,
	__default = {
		__index = {
			levelAttrs = __data_t__levelAttrs["default"]	--[[ {}]],
			advanceAttrs = __data_t__advanceAttrs["default"]	--[[ {}]],
			rarityAttr = ''
		}
	}
}
return csv.meteorite.helditem_effect