--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {[31] = 5, [21] = 20, __size = 2}, 
	[3] = {[31] = 5, [100] = 1, __size = 2}, 
	[4] = {[32] = 5, [22] = 20, __size = 2}, 
	[5] = {[32] = 5, [100] = 1, __size = 2}, 
	[6] = {[33] = 5, [23] = 20, __size = 2}, 
	[7] = {[33] = 5, [100] = 1, __size = 2}, 
	[8] = {[24] = 20, [34] = 5, __size = 2}, 
	[9] = {[100] = 1, [34] = 5, __size = 2}, 
	[10] = {[25] = 20, [35] = 5, __size = 2}, 
	[11] = {[100] = 1, [35] = 5, __size = 2}, 
	[12] = {[26] = 20, [36] = 5, __size = 2}, 
	[13] = {[100] = 1, [36] = 5, __size = 2}, __size = 12}
local __data_t__selfExtraWeight = {
	[216] = __predefine_t__[5],
	[217] = __predefine_t__[5],
	[214] = __predefine_t__[4],
	[215] = __predefine_t__[4],
	[212] = __predefine_t__[4],
	[213] = __predefine_t__[4],
	[211] = __predefine_t__[4],
	[313] = __predefine_t__[6],
	[312] = __predefine_t__[6],
	[311] = __predefine_t__[6],
	[317] = __predefine_t__[7],
	[316] = __predefine_t__[6],
	[218] = __predefine_t__[5],
	[219] = __predefine_t__[5],
	[115] = __predefine_t__[2],
	[114] = __predefine_t__[2],
	[117] = __predefine_t__[3],
	[116] = __predefine_t__[3],
	[111] = __predefine_t__[2],
	[113] = __predefine_t__[2],
	[112] = __predefine_t__[2],
	[318] = __predefine_t__[7],
	[119] = __predefine_t__[3],
	[118] = __predefine_t__[3],
	[519] = __predefine_t__[11],
	[518] = __predefine_t__[11],
	[320] = __predefine_t__[7],
	[321] = __predefine_t__[7],
	[520] = __predefine_t__[11],
	[521] = __predefine_t__[11],
	[421] = __predefine_t__[9],
	[420] = __predefine_t__[9],
	[618] = __predefine_t__[13],
	[619] = __predefine_t__[13],
	[612] = __predefine_t__[12],
	[613] = __predefine_t__[12],
	[611] = __predefine_t__[12],
	[616] = __predefine_t__[13],
	[617] = __predefine_t__[13],
	[614] = __predefine_t__[12],
	[615] = __predefine_t__[12],
	[120] = __predefine_t__[3],
	[121] = __predefine_t__[3],
	[315] = __predefine_t__[6],
	[314] = __predefine_t__[6],
	[221] = __predefine_t__[5],
	[220] = __predefine_t__[5],
	[620] = __predefine_t__[13],
	[319] = __predefine_t__[7],
	[515] = __predefine_t__[10],
	[621] = __predefine_t__[13],
	[514] = __predefine_t__[10],
	[414] = __predefine_t__[8],
	[415] = __predefine_t__[8],
	[416] = __predefine_t__[9],
	[417] = __predefine_t__[9],
	[411] = __predefine_t__[8],
	[412] = __predefine_t__[8],
	[413] = __predefine_t__[8],
	[511] = __predefine_t__[10],
	[513] = __predefine_t__[10],
	[512] = __predefine_t__[10],
	[418] = __predefine_t__[9],
	[419] = __predefine_t__[9],
	[517] = __predefine_t__[11],
	[516] = __predefine_t__[11]
}

csv['elite_challenge']['buffs'] = {
	[111] = {
		id = 111,
		name = '火暴猴',
		group = 11,
		skillID = 86001,
		icon = 'config/big_hero/normal/img_57_hbh@.png',
		desc = '精灵造成的普攻伤害提升15%',
		selfExtraWeight = __data_t__selfExtraWeight[111]
		-- {[31] = 5, [21] = 20, __size = 2}
	},
	[112] = {
		id = 112,
		name = '修建老匠',
		group = 11,
		skillID = 86002,
		icon = 'config/big_hero/normal/img_534_xjlj@.png',
		desc = '精灵释放普攻时暴击率提升10%2回合',
		selfExtraWeight = __data_t__selfExtraWeight[112]
		-- {[31] = 5, [21] = 20, __size = 2}
	},
	[113] = {
		id = 113,
		name = '飞腿郎',
		group = 11,
		skillID = 86003,
		icon = 'config/big_hero/normal/img_106_ftl@.png',
		desc = '精灵释放普攻后暴击伤害提升15%2回合',
		selfExtraWeight = __data_t__selfExtraWeight[113]
		-- {[31] = 5, [21] = 20, __size = 2}
	},
	[114] = {
		id = 114,
		name = '快拳郎',
		group = 11,
		skillID = 86004,
		icon = 'config/big_hero/normal/img_107_kql@.png',
		desc = '精灵释放普攻双攻提升10%2回合',
		selfExtraWeight = __data_t__selfExtraWeight[114]
		-- {[31] = 5, [21] = 20, __size = 2}
	},
	[115] = {
		id = 115,
		name = '战舞郎',
		group = 11,
		skillID = 86005,
		icon = 'config/big_hero/normal/img_237_zwl@.png',
		desc = '精灵释放普攻双防提升20%2回合',
		selfExtraWeight = __data_t__selfExtraWeight[115]
		-- {[31] = 5, [21] = 20, __size = 2}
	},
	[116] = {
		id = 116,
		name = '武道熊师',
		quality = 2,
		group = 21,
		weight = 30,
		skillID = 86006,
		icon = 'config/big_hero/normal/img_892_wdxs@.png',
		desc = '单个大回合内每次普攻伤害递增10%（可叠加3层）',
		selfExtraWeight = __data_t__selfExtraWeight[116]
		-- {[31] = 5, [100] = 1, __size = 2}
	},
	[117] = {
		id = 117,
		name = '葱游兵',
		quality = 2,
		group = 21,
		weight = 30,
		skillID = 86007,
		icon = 'config/big_hero/normal/img_865_cyb@.png',
		desc = '精灵本回合内未释放主动普攻技能，则下次普攻伤害提升16%（最多可叠加2层）',
		selfExtraWeight = __data_t__selfExtraWeight[117]
		-- {[31] = 5, [100] = 1, __size = 2}
	},
	[118] = {
		id = 118,
		name = '师父鼬',
		quality = 2,
		group = 21,
		weight = 30,
		skillID = 86008,
		icon = 'config/big_hero/normal/img_620_sfy@.png',
		desc = '普攻造成的伤害对随机相邻单体，造成等同于原伤害40%的伤害',
		selfExtraWeight = __data_t__selfExtraWeight[118]
		-- {[31] = 5, [100] = 1, __size = 2}
	},
	[119] = {
		id = 119,
		name = '路卡利欧',
		quality = 2,
		group = 21,
		weight = 30,
		skillID = 86009,
		icon = 'config/big_hero/normal/img_448_lklo@.png',
		desc = '每次使用普攻获得10%最大生命的护盾（每个精灵一个大回合内最多触发3次）',
		selfExtraWeight = __data_t__selfExtraWeight[119]
		-- {[31] = 5, [100] = 1, __size = 2}
	},
	[120] = {
		id = 120,
		name = '凯路迪欧',
		quality = 2,
		group = 21,
		weight = 30,
		skillID = 86010,
		icon = 'config/big_hero/normal/img_647_kldo@.png',
		desc = '释放普攻时，有50%概率回复本次普攻30%的生命值的血量',
		selfExtraWeight = __data_t__selfExtraWeight[120]
		-- {[31] = 5, [100] = 1, __size = 2}
	},
	[121] = {
		id = 121,
		name = '艾路雷朵',
		quality = 2,
		group = 21,
		weight = 30,
		skillID = 86011,
		icon = 'config/big_hero/normal/img_475_alld@.png',
		desc = '精灵释放必杀技后额外触发【追击Ⅰ】',
		selfExtraWeight = __data_t__selfExtraWeight[121]
		-- {[31] = 5, [100] = 1, __size = 2}
	},
	[122] = {
		id = 122,
		name = '故勒顿',
		quality = 3,
		group = 31,
		weight = 10,
		skillID = 86012,
		icon = 'config/big_hero/normal/img_1007_gld@.png',
		desc = '精灵每次主动攻击后可触发一次【连击Ⅰ】，并有50%几率额外再触发1次【追击Ⅰ】，若击杀单位时可额外对随机目标触发【追击Ⅰ】'
	},
	[211] = {
		id = 211,
		name = '皮卡丘',
		group = 12,
		skillID = 86021,
		icon = 'config/big_hero/normal/img_25_pkq@.png',
		desc = '精灵必杀伤害提升20%',
		selfExtraWeight = __data_t__selfExtraWeight[211]
		-- {[32] = 5, [22] = 20, __size = 2}
	},
	[212] = {
		id = 212,
		name = '雷丘',
		group = 12,
		skillID = 86022,
		icon = 'config/big_hero/normal/img_26_lq@.png',
		desc = '精灵怒气回复速度提升40%',
		selfExtraWeight = __data_t__selfExtraWeight[212]
		-- {[32] = 5, [22] = 20, __size = 2}
	},
	[213] = {
		id = 213,
		name = '伦琴猫',
		group = 12,
		skillID = 86023,
		icon = 'config/big_hero/normal/img_405_lqm@.png',
		desc = '精灵释放必杀技的暴击率提升25%',
		selfExtraWeight = __data_t__selfExtraWeight[213]
		-- {[32] = 5, [22] = 20, __size = 2}
	},
	[214] = {
		id = 214,
		name = '帕奇利兹',
		group = 12,
		skillID = 86024,
		icon = 'config/big_hero/normal/img_417_pqlz@.png',
		desc = '精灵释放必杀技后自身下次攻击造成伤害提升100%',
		selfExtraWeight = __data_t__selfExtraWeight[214]
		-- {[32] = 5, [22] = 20, __size = 2}
	},
	[215] = {
		id = 215,
		name = '电飞鼠',
		group = 12,
		skillID = 86025,
		icon = 'config/big_hero/normal/img_587_dfs@.png',
		desc = '精灵释放必杀技后回复自身10%生命上限的血量',
		selfExtraWeight = __data_t__selfExtraWeight[215]
		-- {[32] = 5, [22] = 20, __size = 2}
	},
	[216] = {
		id = 216,
		name = '电击魔兽',
		quality = 2,
		group = 22,
		weight = 30,
		skillID = 86026,
		icon = 'config/big_hero/normal/img_466_djms@.png',
		desc = '每使用一次必杀技，提升必杀伤害加成12%（可叠加3层）',
		selfExtraWeight = __data_t__selfExtraWeight[216]
		-- {[32] = 5, [100] = 1, __size = 2}
	},
	[217] = {
		id = 217,
		name = '闪电鸟',
		quality = 2,
		group = 22,
		weight = 30,
		skillID = 86027,
		icon = 'config/big_hero/normal/img_145_sdn@.png',
		desc = '必杀技后，接下去2回合内怒气回复速度提升50%',
		selfExtraWeight = __data_t__selfExtraWeight[217]
		-- {[32] = 5, [100] = 1, __size = 2}
	},
	[218] = {
		id = 218,
		name = '电龙',
		quality = 2,
		group = 22,
		weight = 30,
		skillID = 86028,
		icon = 'config/big_hero/normal/img_181_dl@.png',
		desc = '击败敌人时，额外获得100点怒气，并永久获得必杀伤害加成10%，最多可叠加3层',
		selfExtraWeight = __data_t__selfExtraWeight[218]
		-- {[32] = 5, [100] = 1, __size = 2}
	},
	[219] = {
		id = 219,
		name = '雷电云',
		quality = 2,
		group = 22,
		weight = 30,
		skillID = 86029,
		icon = 'config/big_hero/normal/img_642_ldy@.png',
		desc = '每使用一次普攻或者小技能，提升必杀伤害20%，最多可叠加3层，释放后重置',
		selfExtraWeight = __data_t__selfExtraWeight[219]
		-- {[32] = 5, [100] = 1, __size = 2}
	},
	[220] = {
		id = 220,
		name = '雷吉艾勒奇',
		quality = 2,
		group = 22,
		weight = 30,
		skillID = 86030,
		icon = 'config/big_hero/normal/img_894_ljalq@.png',
		desc = '战斗内怒气上限降低200点',
		selfExtraWeight = __data_t__selfExtraWeight[220]
		-- {[32] = 5, [100] = 1, __size = 2}
	},
	[221] = {
		id = 221,
		name = '电束木',
		quality = 2,
		group = 22,
		weight = 30,
		skillID = 86031,
		icon = 'config/big_hero/normal/img_796_dsm@.png',
		desc = '战斗结束前，恢复精灵自身必杀技释放次数*5%的气血（最多不超过20%）',
		selfExtraWeight = __data_t__selfExtraWeight[221]
		-- {[32] = 5, [100] = 1, __size = 2}
	},
	[222] = {
		id = 222,
		name = '密勒顿',
		quality = 3,
		group = 32,
		weight = 10,
		skillID = 86032,
		icon = 'config/big_hero/normal/img_1008_mld@.png',
		desc = '入场获得满怒气，精灵每2次主动必杀技额外释放释放一次免消耗的必杀技，该免消耗的必杀技击杀单位时额外获得200点怒气'
	},
	[311] = {
		id = 311,
		name = '隆隆岩',
		group = 13,
		skillID = 86041,
		icon = 'config/big_hero/normal/img_323_pht@.png',
		desc = '精灵双攻提升15%',
		selfExtraWeight = __data_t__selfExtraWeight[311]
		-- {[33] = 5, [23] = 20, __size = 2}
	},
	[312] = {
		id = 312,
		name = '喷火驼',
		group = 13,
		skillID = 86042,
		icon = 'config/big_hero/normal/img_76_lly@.png',
		desc = '精灵生命上限提高10%',
		selfExtraWeight = __data_t__selfExtraWeight[312]
		-- {[33] = 5, [23] = 20, __size = 2}
	},
	[313] = {
		id = 313,
		name = '穿山王',
		group = 13,
		skillID = 86043,
		icon = 'config/big_hero/normal/img_28_csw@.png',
		desc = '精灵损失血量时，提升双攻5%（最多可叠加4层）',
		selfExtraWeight = __data_t__selfExtraWeight[313]
		-- {[33] = 5, [23] = 20, __size = 2}
	},
	[314] = {
		id = 314,
		name = '庞岩怪',
		group = 13,
		skillID = 86044,
		icon = 'config/big_hero/normal/img_526_pyg@.png',
		desc = '精灵每损失1%生命值，伤害加成提升3%',
		selfExtraWeight = __data_t__selfExtraWeight[314]
		-- {[33] = 5, [23] = 20, __size = 2}
	},
	[315] = {
		id = 315,
		name = '炎武王',
		group = 13,
		skillID = 86045,
		icon = 'config/big_hero/normal/img_500_yww@.png',
		desc = '精灵每损失1%生命值，双攻提升3%',
		selfExtraWeight = __data_t__selfExtraWeight[315]
		-- {[33] = 5, [23] = 20, __size = 2}
	},
	[316] = {
		id = 316,
		name = '齿轮怪',
		group = 13,
		skillID = 86046,
		icon = 'config/big_hero/normal/img_601_clg@.png',
		desc = '精灵每损失1%生命值，双防提升6%',
		selfExtraWeight = __data_t__selfExtraWeight[316]
		-- {[33] = 5, [23] = 20, __size = 2}
	},
	[317] = {
		id = 317,
		name = '快龙',
		quality = 2,
		group = 23,
		weight = 30,
		skillID = 86047,
		icon = 'config/big_hero/normal/img_149_kl@.png',
		desc = '当精灵当前生命值百分比首次小于50%时，获得自身20%生命上限的护盾，持续2回合',
		selfExtraWeight = __data_t__selfExtraWeight[317]
		-- {[33] = 5, [100] = 1, __size = 2}
	},
	[318] = {
		id = 318,
		name = '蜥蜴王',
		quality = 2,
		group = 23,
		weight = 30,
		skillID = 86048,
		icon = 'config/big_hero/normal/img_254_xyw@.png',
		desc = '进入战斗时，获得等同于已损失生命值36%伤害的护盾，持续2回合',
		selfExtraWeight = __data_t__selfExtraWeight[318]
		-- {[33] = 5, [100] = 1, __size = 2}
	},
	[319] = {
		id = 319,
		name = '烈咬陆鲨',
		quality = 2,
		group = 23,
		weight = 30,
		skillID = 86049,
		icon = 'config/big_hero/normal/img_445_lyls@.png',
		desc = '精灵损失血量后，恢复50点怒气（每个大回合最多触发1次）',
		selfExtraWeight = __data_t__selfExtraWeight[319]
		-- {[33] = 5, [100] = 1, __size = 2}
	},
	[320] = {
		id = 320,
		name = '雷吉洛克',
		quality = 2,
		group = 23,
		weight = 30,
		skillID = 86050,
		icon = 'config/big_hero/normal/img_377_ljlk@.png',
		desc = '友方首个受到致命攻击的单位将保留1滴血存活',
		selfExtraWeight = __data_t__selfExtraWeight[320]
		-- {[33] = 5, [100] = 1, __size = 2}
	},
	[321] = {
		id = 321,
		name = '班基拉斯',
		quality = 2,
		group = 23,
		weight = 30,
		skillID = 86051,
		icon = 'config/big_hero/normal/img_248_bjls@.png',
		desc = '自身每累计损失1%生命值，双攻提升1%（最高不超过200%）',
		selfExtraWeight = __data_t__selfExtraWeight[321]
		-- {[33] = 5, [100] = 1, __size = 2}
	},
	[322] = {
		id = 322,
		name = '捷克罗姆',
		quality = 3,
		group = 33,
		weight = 10,
		skillID = 86052,
		icon = 'config/big_hero/normal/img_644_jklm@.png',
		desc = '自身血量首次低于20%、50%，免消耗额外触发1次必杀技，并附带25%吸血，然后额外造成自身已损失血量的50%的真实伤害'
	},
	[411] = {
		id = 411,
		name = '雪妖女',
		group = 14,
		skillID = 86061,
		icon = 'config/big_hero/normal/img_478_xyn@.png',
		desc = '控制率提升20%',
		selfExtraWeight = __data_t__selfExtraWeight[411]
		-- {[24] = 20, [34] = 5, __size = 2}
	},
	[412] = {
		id = 412,
		name = '双倍多多冰',
		group = 14,
		skillID = 86062,
		icon = 'config/big_hero/normal/img_584_sbddb@.png',
		desc = '敌方免控率降低20%',
		selfExtraWeight = __data_t__selfExtraWeight[412]
		-- {[24] = 20, [34] = 5, __size = 2}
	},
	[413] = {
		id = 413,
		name = '喷嚏熊',
		group = 14,
		skillID = 86063,
		icon = 'config/big_hero/normal/img_613_ptx@.png',
		desc = '陷入控制状态的敌方目标受到伤害提高10%',
		selfExtraWeight = __data_t__selfExtraWeight[413]
		-- {[24] = 20, [34] = 5, __size = 2}
	},
	[414] = {
		id = 414,
		name = '土台龟',
		group = 14,
		skillID = 86064,
		icon = 'config/big_hero/normal/img_389_ttg@.png',
		desc = '敌方目标陷入控制状态后，下1次收到的攻击暴击率提高100%',
		selfExtraWeight = __data_t__selfExtraWeight[414]
		-- {[24] = 20, [34] = 5, __size = 2}
	},
	[415] = {
		id = 415,
		name = '吼爆弹',
		group = 14,
		skillID = 86065,
		icon = 'config/big_hero/normal/img_294_hbd@.png',
		desc = '精灵对陷入控制状态的敌方目标释放必杀技或者小技能时，造成伤害提高30%',
		selfExtraWeight = __data_t__selfExtraWeight[415]
		-- {[24] = 20, [34] = 5, __size = 2}
	},
	[416] = {
		id = 416,
		name = '卡璞·鸣鸣',
		quality = 2,
		group = 24,
		weight = 30,
		skillID = 86066,
		icon = 'config/big_hero/normal/img_785_kpmm@.png',
		desc = '攻击时有30%概率永久提升控制率5%（最多可叠加5层）',
		selfExtraWeight = __data_t__selfExtraWeight[416]
		-- {[100] = 1, [34] = 5, __size = 2}
	},
	[417] = {
		id = 417,
		name = '雷公',
		quality = 2,
		group = 24,
		weight = 30,
		skillID = 86067,
		icon = 'config/big_hero/normal/img_243_lg@.png',
		desc = '精灵对释放终结技有30%概率眩晕1回合',
		selfExtraWeight = __data_t__selfExtraWeight[417]
		-- {[100] = 1, [34] = 5, __size = 2}
	},
	[418] = {
		id = 418,
		name = '阿罗拉九尾',
		quality = 2,
		group = 24,
		weight = 30,
		skillID = 86068,
		icon = 'config/big_hero/normal/img_38_alljw@.png',
		desc = '攻击时对随机目标有10%概率眩晕、睡眠、冰冻、沉默、混乱1回合',
		selfExtraWeight = __data_t__selfExtraWeight[418]
		-- {[100] = 1, [34] = 5, __size = 2}
	},
	[419] = {
		id = 419,
		name = '急冻鸟',
		quality = 2,
		group = 24,
		weight = 30,
		skillID = 86069,
		icon = 'config/big_hero/normal/img_144_jdn@.png',
		desc = '敌方首次低于当前生命值百分比低于70%、30%时，有60%冰冻1回合',
		selfExtraWeight = __data_t__selfExtraWeight[419]
		-- {[100] = 1, [34] = 5, __size = 2}
	},
	[420] = {
		id = 420,
		name = '超级暴雪王',
		quality = 2,
		group = 24,
		weight = 30,
		skillID = 86070,
		icon = 'config/big_hero/normal/img_460_cjbxw@.png',
		desc = '自身每次控制一名敌人时，恢复自身3%的气血，每个行动回合内回复量最多不超过12%',
		selfExtraWeight = __data_t__selfExtraWeight[420]
		-- {[100] = 1, [34] = 5, __size = 2}
	},
	[421] = {
		id = 421,
		name = '君主蛇',
		quality = 2,
		group = 24,
		weight = 30,
		skillID = 86071,
		icon = 'config/big_hero/normal/img_497_jzs@.png',
		desc = '敌方控制效果被添加时造成等同于目标当前生命10%的真实伤害（每个大回合最多触发一次）',
		selfExtraWeight = __data_t__selfExtraWeight[421]
		-- {[100] = 1, [34] = 5, __size = 2}
	},
	[422] = {
		id = 422,
		name = '达克莱伊',
		quality = 3,
		group = 34,
		weight = 10,
		skillID = 86072,
		icon = 'config/big_hero/normal/img_491_dkly@.png',
		desc = '每个大回合开始，30%概率使目标进入眩晕、睡眠、冰冻、沉默、混乱中的一种（根据友方控制率最高的单位来享受），并额外造成一次友方攻击较大值120%加成的真实伤害（敌方每一个控制效果提升伤害10%），触发时敌方免控率降低30%'
	},
	[511] = {
		id = 511,
		name = '水箭龟',
		group = 15,
		skillID = 86081,
		icon = 'config/big_hero/normal/img_9_sjg@.png',
		desc = '持有护盾的精灵暴击率提升16%',
		selfExtraWeight = __data_t__selfExtraWeight[511]
		-- {[25] = 20, [35] = 5, __size = 2}
	},
	[512] = {
		id = 512,
		name = '龙头地鼠',
		group = 15,
		skillID = 86082,
		icon = 'config/big_hero/normal/img_530_ltds@.png',
		desc = '持有护盾的精灵暴击伤害提升30%',
		selfExtraWeight = __data_t__selfExtraWeight[512]
		-- {[25] = 20, [35] = 5, __size = 2}
	},
	[513] = {
		id = 513,
		name = '巨锻匠',
		group = 15,
		skillID = 86083,
		icon = 'config/big_hero/normal/img_959_jdj@.png',
		desc = '持有护盾的精灵双防提升20%',
		selfExtraWeight = __data_t__selfExtraWeight[513]
		-- {[25] = 20, [35] = 5, __size = 2}
	},
	[514] = {
		id = 514,
		name = '独剑鞘',
		group = 15,
		skillID = 86084,
		icon = 'config/big_hero/normal/img_679_djq@.png',
		desc = '持有护盾的精灵伤害减免提升15%',
		selfExtraWeight = __data_t__selfExtraWeight[514]
		-- {[25] = 20, [35] = 5, __size = 2}
	},
	[515] = {
		id = 515,
		name = '可可多拉',
		group = 15,
		skillID = 86085,
		icon = 'config/big_hero/normal/img_304_kkdl@.png',
		desc = '精灵受到攻击后，获得等同于本次攻击内损失的生命值18%的护盾',
		selfExtraWeight = __data_t__selfExtraWeight[515]
		-- {[25] = 20, [35] = 5, __size = 2}
	},
	[516] = {
		id = 516,
		name = '大钢蛇',
		quality = 2,
		group = 25,
		weight = 30,
		skillID = 86086,
		icon = 'config/big_hero/normal/img_208_dgs@.png',
		desc = '进入战斗时，精灵获得自身生命上限15%的护盾',
		selfExtraWeight = __data_t__selfExtraWeight[516]
		-- {[100] = 1, [35] = 5, __size = 2}
	},
	[517] = {
		id = 517,
		name = '波士可多拉',
		quality = 2,
		group = 25,
		weight = 30,
		skillID = 86087,
		icon = 'config/big_hero/normal/img_306_bskdl@.png',
		desc = '自身攻击后，60%概率获得自身12%生命上限的护盾',
		selfExtraWeight = __data_t__selfExtraWeight[517]
		-- {[100] = 1, [35] = 5, __size = 2}
	},
	[518] = {
		id = 518,
		name = '巨金怪',
		quality = 2,
		group = 25,
		weight = 30,
		skillID = 86088,
		icon = 'config/big_hero/normal/img_376_jjg@.png',
		desc = '自身受到主动攻击时，对攻击者造成自身护盾量30%的反震伤害(可暴击）',
		selfExtraWeight = __data_t__selfExtraWeight[518]
		-- {[100] = 1, [35] = 5, __size = 2}
	},
	[519] = {
		id = 519,
		name = '勾帕路翁',
		quality = 2,
		group = 25,
		weight = 30,
		skillID = 86089,
		icon = 'config/big_hero/normal/img_638_gplw@.png',
		desc = '持有护盾的精灵提高等同于自身护盾量40%的双攻，但不会超过自身初始双攻的120%',
		selfExtraWeight = __data_t__selfExtraWeight[519]
		-- {[100] = 1, [35] = 5, __size = 2}
	},
	[520] = {
		id = 520,
		name = '垒磊石',
		quality = 2,
		group = 25,
		weight = 30,
		skillID = 86090,
		icon = 'config/big_hero/normal/img_805_lls@.png',
		desc = '战斗结束前，自身身上的护盾会以20%的比例转化为生命值恢复自身',
		selfExtraWeight = __data_t__selfExtraWeight[520]
		-- {[100] = 1, [35] = 5, __size = 2}
	},
	[521] = {
		id = 521,
		name = '雷吉斯奇鲁',
		quality = 2,
		group = 25,
		weight = 30,
		skillID = 86091,
		icon = 'config/big_hero/normal/img_379_ljsql@.png',
		desc = '攻击时附带30%护盾量的真实伤害（该伤害不超过自身双攻的较大值200%，该伤害可暴击）',
		selfExtraWeight = __data_t__selfExtraWeight[521]
		-- {[100] = 1, [35] = 5, __size = 2}
	},
	[522] = {
		id = 522,
		name = '索尔迦雷欧',
		quality = 3,
		group = 35,
		weight = 10,
		skillID = 86092,
		icon = 'config/big_hero/normal/img_791_sejlo@.png',
		desc = '每个大回合结束后对敌方全体单位造成【反震】，伤害等同于我方全体护盾的总量的真实伤害，该反震伤害可暴击，继承友方暴击率最高的单位'
	},
	[611] = {
		id = 611,
		name = '乐天河童',
		group = 16,
		skillID = 86101,
		icon = 'config/big_hero/normal/img_272_ltht@.png',
		desc = '精灵接受治疗后，双防提升20%2回合',
		selfExtraWeight = __data_t__selfExtraWeight[611]
		-- {[26] = 20, [36] = 5, __size = 2}
	},
	[612] = {
		id = 612,
		name = '菊草叶',
		group = 16,
		skillID = 86102,
		icon = 'config/big_hero/normal/img_152_jcy@.png',
		desc = '精灵接受治疗后，双攻提升20%2回合',
		selfExtraWeight = __data_t__selfExtraWeight[612]
		-- {[26] = 20, [36] = 5, __size = 2}
	},
	[613] = {
		id = 613,
		name = '宝石海星',
		group = 16,
		skillID = 86103,
		icon = 'config/big_hero/normal/img_121_bshx@.png',
		desc = '精灵提供治疗后，回复等同于自身生命上限10%的生命值（每个大回合触发1次）',
		selfExtraWeight = __data_t__selfExtraWeight[613]
		-- {[26] = 20, [36] = 5, __size = 2}
	},
	[614] = {
		id = 614,
		name = '胖甜妮',
		group = 16,
		skillID = 86104,
		icon = 'config/big_hero/normal/img_685_ptn@.png',
		desc = '每个大回合开始，精灵回复等同于自身生命上限12%的生命值',
		selfExtraWeight = __data_t__selfExtraWeight[614]
		-- {[26] = 20, [36] = 5, __size = 2}
	},
	[615] = {
		id = 615,
		name = '皮可西',
		group = 16,
		skillID = 86105,
		icon = 'config/big_hero/normal/img_36_pkx@.png',
		desc = '精灵的受治疗率提升20%',
		selfExtraWeight = __data_t__selfExtraWeight[615]
		-- {[26] = 20, [36] = 5, __size = 2}
	},
	[616] = {
		id = 616,
		name = '奥利瓦',
		quality = 2,
		group = 26,
		weight = 30,
		skillID = 86106,
		icon = 'config/big_hero/normal/img_930_alw@.png',
		desc = '满血时，受到的伤害降低30%',
		selfExtraWeight = __data_t__selfExtraWeight[616]
		-- {[100] = 1, [36] = 5, __size = 2}
	},
	[617] = {
		id = 617,
		name = '椰蛋树',
		quality = 2,
		group = 26,
		weight = 30,
		skillID = 86107,
		icon = 'config/big_hero/normal/img_103_yds@.png',
		desc = '精灵释放攻击后，对主目标造成自身当前面生命值的20%的真实伤害',
		selfExtraWeight = __data_t__selfExtraWeight[617]
		-- {[100] = 1, [36] = 5, __size = 2}
	},
	[618] = {
		id = 618,
		name = '苹裹龙',
		quality = 2,
		group = 26,
		weight = 30,
		skillID = 86108,
		icon = 'config/big_hero/normal/img_841_pgl@.png',
		desc = '精灵血量低于30%时生命上限提升50%2回合（冷却3回合）',
		selfExtraWeight = __data_t__selfExtraWeight[618]
		-- {[100] = 1, [36] = 5, __size = 2}
	},
	[619] = {
		id = 619,
		name = '美纳斯',
		quality = 2,
		group = 26,
		weight = 30,
		skillID = 86109,
		icon = 'config/big_hero/normal/img_350_mns@.png',
		desc = '精灵释放普攻或者小技能回复自身本次攻击20%的气血',
		selfExtraWeight = __data_t__selfExtraWeight[619]
		-- {[100] = 1, [36] = 5, __size = 2}
	},
	[620] = {
		id = 620,
		name = '西狮海壬',
		quality = 2,
		group = 26,
		weight = 30,
		skillID = 86110,
		icon = 'config/big_hero/normal/img_730_xshr@.png',
		desc = '每个大回合我方对我方目标治疗时，记录治疗量，当任意我方目标释放攻击后，根据记录治疗量的30%对主目标造成真实附加伤害',
		selfExtraWeight = __data_t__selfExtraWeight[620]
		-- {[100] = 1, [36] = 5, __size = 2}
	},
	[621] = {
		id = 621,
		name = '花洁夫人',
		quality = 2,
		group = 26,
		weight = 30,
		skillID = 86111,
		icon = 'config/big_hero/normal/img_671_hjfr@.png',
		desc = '释放必杀时回复自身20%生命上限的气血，且获得免控率50%1回合',
		selfExtraWeight = __data_t__selfExtraWeight[621]
		-- {[100] = 1, [36] = 5, __size = 2}
	},
	[622] = {
		id = 622,
		name = '谢米',
		quality = 3,
		group = 36,
		weight = 10,
		skillID = 86112,
		icon = 'config/big_hero/normal/img_492_xm@.png',
		desc = '每个大回合结束后回复友方20%的生命值，已损失血量越多治疗量越大，并对敌方全体单位造成友方本回合总治疗量50%的真实伤害，额外回复自身200点怒气值，并触发【驱散I】'
	},
	__size = 72,
	__default = {
		__index = {
			name = '',
			quality = 1,
			group = 1,
			weight = 100,
			skillID = 1,
			icon = '',
			desc = '',
			theme = 0,
			selfExtraWeight = {__size = 0}
		}
	}
}
return csv.elite_challenge.buffs