# Auto-generated companion data — ordered tuples match achievement_task.csv rows (after 3 headers).
AUTO_CHESS_ACHIEVEMENT_EN: list[tuple[str, str]] = [
    ("New Adventure", "Clear one full Adventure run using any Trainer."),
    ("Social Anxiety", "Lose every round in three Apex Duel matches and still clear the run with your Trainer surviving."),
    ("Breakthrough Bid", "Use Promote encounters to raise any Pokémon to 2★."),
    ("Breakthrough Mastery", "Use Promote encounters to raise any Pokémon to 4★."),
    ("HP Acrobat", "Clear the run with your Trainer’s HP at 20 or lower."),
    ("Practice Pays Off", "Raise Pokémon to 4★ using Promote Strengthening encounters 20 times in total."),
    ("Focused Training", "Promote Pokémon 40 times in total using Promote Strengthening encounters."),
    ("Leaderboard Glory I", "When the season settles, rank in the global top 50."),
    ("Desperate Bite", "In the Famished encounter, choose Eat it raw and clear the run."),
    ("Burn It All", "In the Fallen Tree encounter, choose Burn it down and clear the run."),
    ("Probably a Bad Idea", "In the Delivery Box encounter, choose Open it and clear the run."),
    ("Coin Pouch Path", "In the Prepared to Depart encounter, choose the bag of coins and clear the run."),
    ("Lunchbox Boost", "In the Prepared to Depart encounter, choose the Heart Lunchbox and clear the run."),
    ("Explorer’s Prep", "In the Prepared to Depart encounter, choose the exploration kit and clear the run."),
    ("Fortune Keeper", "Clear the run with 50 Coins or more."),
    ("Shake It Off", "Clear the run after losing three or more battles."),
    ("Tightrope HP", "Clear the run with your Trainer’s HP at 10 or lower."),
    ("Closed Shop", "Clear the run without buying anything from the mystery merchant."),
    ("Blood Price", "Spend 10 or more Trainer HP at the mystery merchant and clear the run."),
    ("Self-Made Strength", "Clear the run without using any stat-enhancing encounters."),
    ("Close Shave", "Your Trainer survives after taking more than 10 damage in a single hit."),
    ("Haymaker Apex", "In an Apex Duel, deal more than 10 damage with one hit."),
    ("Light Spar", "In an Apex Duel, deal less than 10 damage with one hit."),
    ("Leaderboard Glory II", "When the season settles, rank in the global top 10."),
    ("Serious Saving", "In the Bank encounter, choose Deposit 30 Coins and clear the run."),
    ("Flawless March", "Clear an Adventure without losing any battles."),
    ("Ultra Mogul", "Clear the run with 100 Coins or more."),
    ("Last Hitpoint", "Clear the run with your Trainer at exactly 1 HP."),
    ("Training Apex", "Clear the run with six 4★ Pokémon on the board."),
    ("Quality Optional", "Clear the run with three or more 1★ Pokémon on the board."),
    ("No Promo Run", "Clear the run without using any Promote encounters."),
    ("Cheated Fate", "Your Trainer survives after taking more than 20 damage in a single hit."),
    ("Megaton Spike", "In an Apex Duel, deal more than 20 damage with one hit."),
    ("Leaderboard Glory III", "When the season settles, reach global rank #1."),
    ("Exact Coffers", "Clear the run with exactly 0 Coins."),
    ("Dress Parade", "Clear the run while every Pokémon on the board holds gear."),
    ("Double-Pack Run", "Clear the run with at least one Pokémon holding two gear pieces."),
    ("Test Subject", "In the Apothecary encounter, choose Test the new potion and clear the run."),
    ("Forest Picnic", "In the Firefly Woods encounter, choose Picnic and clear the run."),
    ("Gracidea Helper", "In the Woods-Dwellers encounter, help retrieve a Gracidea Flower and clear the run."),
    ("Right Turn Home", "In the Lost encounter, pick the correct direction and clear the run."),
    ("Let It Slide", "In the Stolen Goods encounter, choose Let it go and clear the run."),
    ("Chapter of Cinnabar", "Clear 5 full runs while using Trainer Blaine."),
    ("Blaine • First Steps", "Reach mastery level 5 with Blaine."),
    ("Blaine Legacy I", "When the season settles, rank in the Blaine leaderboard top 50."),
    ("Embers Trial", "Clear a run while using Blaine’s Embers skill."),
    ("Spark Trial", "Clear a run while using Blaine’s Spark skill."),
    ("Blazing Bear", "Clear a run while using Blaine’s Blaze Bear skill."),
    ("Blaine • True Grip", "Reach mastery level 10 with Blaine."),
    ("Blaine • Cinnabar Overlord", "Reach mastery level 15 with Blaine."),
    ("Kindled Burn", "Clear a run while using Blaine’s Kindled Burn skill."),
    ("Prairie Fire", "Clear a run while using Blaine’s Prairie Fire skill."),
    ("Press Ahead", "Clear a run while using Blaine’s Press Ahead skill."),
    ("Unyielding Blaze", "Clear a run while using Blaine’s Unyielding skill."),
    ("Cinnabar Tempest", "Clear a run while using Blaine’s Cinnabar skill."),
    ("Riddle Duel", "Clear a run while using Blaine’s Riddle skill."),
    ("Hellfire Finale", "Clear a run while using Blaine’s Hellfire skill."),
    ("Ho-Oh Ally", "Clear 5 runs with Blaine deploying Ho-Oh."),
    ("Victini Ally", "Clear 5 runs with Blaine deploying Victini."),
    ("Marshadow Ally", "Clear 5 runs with Blaine deploying Marshadow."),
    ("Zamazenta Ally", "Clear 5 runs with Blaine deploying Zamazenta."),
    ("Endless Flames", "Clear a run using Blaine with Ho-Oh and Charmander on the field."),
    ("Victory Blaze", "Clear a run using Blaine with Victini and Torchic on the field."),
    ("Sky-High Spark", "Clear a run using Blaine with Moltres and Magby on the field."),
    ("Shadow Chronicles", "Clear a run using Blaine with Marshadow and Mankey on the field."),
    ("Shield and Fang", "Clear a run using Blaine with Torchic and Zamazenta on the field."),
    ("Strike Unbroken", "Clear a run using Blaine with Riolu and Sirfetch’d on the field."),
    ("Blaine Legacy II", "When the season settles, rank in the Blaine leaderboard top 10."),
    ("Blaine • Cinnabar Overlord+", "Reach mastery level 20 with Blaine."),
    ("Undying Pyre", "Clear a run using Blaine with Cyndaquil, Chimchar, and Entei."),
    ("Blaine Legacy III", "When the season settles, place #1 on the Blaine leaderboard."),
    ("Tri-Kicking Line", "Clear a run using Blaine with Hitmonlee, Hitmonchan, and Hitmontop."),
    ("Olivine Chapter", "Clear 5 full runs while using Trainer Jasmine."),
    ("Jasmine • First Steps", "Reach mastery level 5 with Jasmine."),
    ("Component Kit", "Clear a run while using Jasmine’s Component skill."),
    ("Iron Shelter", "Clear a run while using Jasmine’s Iron Shelter skill."),
    ("Bounty Sprout", "Clear a run while using Jasmine’s Bounty skill."),
    ("Jasmine Legacy I", "When the season settles, rank in the Jasmine leaderboard top 50."),
    ("Jasmine Legacy II", "When the season settles, rank in the Jasmine leaderboard top 10."),
    ("Jasmine Legacy III", "When the season settles, place #1 on the Jasmine leaderboard."),
    ("Jasmine • True Grip", "Reach mastery level 10 with Jasmine."),
    ("Jasmine • Olivine Overlord", "Reach mastery level 15 with Jasmine."),
    ("Eternal Lattice", "Clear a run while using Jasmine’s Eternal skill."),
    ("Assembly Line", "Clear a run while using Jasmine’s Assembly skill."),
    ("Smelt Breaker", "Clear a run while using Jasmine’s Smelt skill."),
    ("Luck Engine", "Clear a run while using Jasmine’s Lucky skill."),
    ("Absolute Guard", "Clear a run while using Jasmine’s Absolute Defense skill."),
    ("Razor’s Edge", "Clear a run while using Jasmine’s Sharp skill."),
    ("Focus Surge", "Clear a run while using Jasmine’s Focus skill."),
    ("Shaymin Land Ally", "Clear 5 runs with Jasmine deploying Shaymin Land Forme."),
    ("Shaymin Sky Ally", "Clear 5 runs with Jasmine deploying Shaymin Sky Forme."),
    ("Celebi Ally", "Clear 5 runs with Jasmine deploying Celebi."),
    ("Meltan Ally", "Clear 5 runs with Jasmine deploying Meltan."),
    ("Magearna Ally", "Clear 5 runs with Jasmine deploying Magearna."),
    ("Solgaleo Ally", "Clear 5 runs with Jasmine deploying Solgaleo."),
    ("Garden Surge", "Clear a run using Jasmine with Shaymin Land Forme and Bounsweet on the field."),
    ("Wild Spiral", "Clear a run using Jasmine with Shaymin Sky Forme and Bellsprout on the field."),
    ("Evergrowth Bond", "Clear a run using Jasmine with Snivy and Celebi on the field."),
    ("Solar Flare Fang", "Clear a run using Jasmine with Solgaleo and Aron on the field."),
    ("Edge Without Blade", "Clear a run using Jasmine with Meltan and Excadrill on the field."),
    ("Steel Riposte Duo", "Clear a run using Jasmine with Steelix and Registeel on the field."),
    ("Jasmine • Olivine Overlord+", "Reach mastery level 20 with Jasmine."),
    ("Thorned Bloom Trio", "Clear a run using Jasmine with Chespin, Chikorita, and Turtwig."),
    ("Gearheart Trinity", "Clear a run using Jasmine with Klink, Aegislash Shield Forme, and Cobalion."),
    ("Ecruteak Chapter", "Clear 5 full runs while using Trainer Morty."),
    ("Morty • First Steps", "Reach mastery level 5 with Morty."),
    ("Shadow Slice", "Clear a run while using Morty’s Shadow Strike skill."),
    ("Veiled Step", "Clear a run while using Morty’s Veiled Shape skill."),
    ("Spirit Chorus", "Clear a run while using Morty’s Spirit Call skill."),
    ("Morty Legacy I", "When the season settles, rank in the Morty leaderboard top 50."),
    ("Morty Legacy II", "When the season settles, rank in the Morty leaderboard top 10."),
    ("Morty Legacy III", "When the season settles, place #1 on the Morty leaderboard."),
    ("Morty • True Grip", "Reach mastery level 10 with Morty."),
    ("Morty • Ecruteak Overlord", "Reach mastery level 15 with Morty."),
    ("Slumber Shade", "Clear a run while using Morty’s Drowsiness skill."),
    ("Disaster Spiral", "Clear a run while using Morty’s Calamity skill."),
    ("Phantom Fade", "Clear a run while using Morty’s Vanishing Shadow skill."),
    ("Soul Drain", "Clear a run while using Morty’s Exhaust skill."),
    ("Illusion Cloak", "Clear a run while using Morty’s Phantom skill."),
    ("Wraith Bloom", "Clear a run while using Morty’s Corruption skill."),
    ("Pactbound Mark", "Clear a run while using Morty’s Contract skill."),
    ("Hoopa Confined Ally", "Clear 5 runs with Morty deploying Hoopa Confined."),
    ("Lunala Ally", "Clear 5 runs with Morty deploying Lunala."),
    ("Giratina Ally", "Clear 5 runs with Morty deploying Giratina."),
    ("Yveltal Ally", "Clear 5 runs with Morty deploying Yveltal."),
    ("Darkrai Ally", "Clear 5 runs with Morty deploying Darkrai."),
    ("Mischief Engine", "Clear a run using Morty with Hoopa Confined and Misdreavus."),
    ("Lunar Eclipse Haunt", "Clear a run using Morty with Lunala and Mimikyu."),
    ("Spectral Procession", "Clear a run using Morty with Giratina and Phantump."),
    ("Ruinous Whisper", "Clear a run using Morty with Yveltal and Krokorok."),
    ("Rough Justice Duo", "Clear a run using Morty with Greninja and Krookodile."),
    ("Insomnia Duel", "Clear a run using Morty with Darkrai and Sneasel."),
    ("Morty • Ecruteak Overlord+", "Reach mastery level 20 with Morty."),
    ("Dream Sovereign Trio", "Clear a run using Morty with Misdreavus, Litwick, and Darkrai."),
    ("Rogue Spiral Trio", "Clear a run using Morty with Krookodile, Krokorok, and Sneasel."),
    ("Laverre Chapter", "Clear 5 full runs while using Trainer Valerie."),
    ("Valerie • First Steps", "Reach mastery level 5 with Valerie."),
    ("Veil Whisper", "Clear a run while using Valerie’s Ethereal skill."),
    ("Linked Fate", "Clear a run while using Valerie’s Union skill."),
    ("Last Gambit", "Clear a run while using Valerie’s Last Stand skill."),
    ("Valerie Legacy I", "When the season settles, rank in the Valerie leaderboard top 50."),
    ("Valerie Legacy II", "When the season settles, rank in the Valerie leaderboard top 10."),
    ("Valerie Legacy III", "When the season settles, place #1 on the Valerie leaderboard."),
    ("Valerie • True Grip", "Reach mastery level 10 with Valerie."),
    ("Valerie • Laverre Overlord", "Reach mastery level 15 with Valerie."),
    ("Mirror Mirage", "Clear a run while using Valerie’s Mirror Flower skill."),
    ("Enchanting Shade", "Clear a run while using Valerie’s Glamour skill."),
    ("Nimble Flourish", "Clear a run while using Valerie’s Agility skill."),
    ("Living Bond", "Clear a run while using Valerie’s Symbiosis skill."),
    ("Captured Gambit", "Clear a run while using Valerie’s Pawn skill."),
    ("Moonlit Ripple", "Clear a run while using Valerie’s Lunar Pool skill."),
    ("Healing Chorus", "Clear a run while using Valerie’s Cure skill."),
    ("Xerneas Ally", "Clear 5 runs with Valerie deploying Xerneas."),
    ("Radiant Mega Gardevoir Ally", "Clear 5 runs with Valerie deploying Shiny Mega Gardevoir."),
    ("Lugia Ally", "Clear 5 runs with Valerie deploying Lugia."),
    ("Hoopa Unbound Ally", "Clear 5 runs with Valerie deploying Hoopa Unbound."),
    ("Mewtwo Ally", "Clear 5 runs with Valerie deploying Mewtwo."),
    ("Flower of Life", "Clear a run using Valerie with Xerneas and Flabébé on the field."),
    ("Phantom Pas de Deux", "Clear a run using Valerie with Shiny Mega Gardevoir and Primarina on the field."),
    ("Mindscape Spiral", "Clear a run using Valerie with Hoopa Unbound and Mewtwo."),
    ("Prismatic Lens Duo", "Clear a run using Valerie with Necrozma and Starmie."),
    ("Double Mindlink", "Clear a run using Valerie with Mew and Abra on the field."),
    ("Guardian Duo", "Clear a run using Valerie with Gardevoir and Gallade on the field."),
    ("Valerie • Laverre Overlord+", "Reach mastery level 20 with Valerie."),
    ("Precious Peeps Trio", "Clear a run using Valerie with Cleffa, Gothita, and Exeggcute."),
    ("Sugarheart Trio", "Clear a run using Valerie with Swirlix, Slurpuff, and Wigglytuff."),
    ("Snowpoint Chapter", "Clear 5 full runs while using Trainer Candice."),
    ("Candice • First Steps", "Reach mastery level 5 with Candice."),
    ("Frost Waltz", "Clear a run while using Candice’s Frost Waltz skill."),
    ("Breaker Shot", "Clear a run while using Candice’s Ice Crash skill."),
    ("Blizzard Line", "Clear a run while using Candice’s Snow Gust skill."),
    ("Candice Legacy I", "When the season settles, rank in the Candice leaderboard top 50."),
    ("Candice Legacy II", "When the season settles, rank in the Candice leaderboard top 10."),
    ("Candice Legacy III", "When the season settles, place #1 on the Candice leaderboard."),
    ("Candice • True Grip", "Reach mastery level 10 with Candice."),
    ("Candice • Snowpoint Overlord", "Reach mastery level 15 with Candice."),
    ("Spring Thaw", "Clear a run while using Candice’s Snowmelt skill."),
    ("Rivulet Flow", "Clear a run while using Candice’s Babbling Brooks skill."),
    ("Whirlpool Grip", "Clear a run while using Candice’s Vortex skill."),
    ("Crystal Purity", "Clear a run while using Candice’s Unblemished skill."),
    ("Avalanche Break", "Clear a run while using Candice’s Crash Snow skill."),
    ("Converging Tide", "Clear a run while using Candice’s Converging Tide skill."),
    ("Tidal Surge", "Clear a run while using Candice’s Tidal Surge skill."),
    ("Kyogre Ally", "Clear 5 runs with Candice deploying Kyogre."),
    ("Manaphy Ally", "Clear 5 runs with Candice deploying Manaphy."),
    ("Palkia Ally", "Clear 5 runs with Candice deploying Palkia."),
    ("Polar Mega Abomasnow Ally", "Clear 5 runs with Candice deploying Shiny Mega Abomasnow."),
    ("Ice Rider Ally", "Clear 5 runs with Candice deploying Ice Rider Calyrex."),
    ("Kyurem Ally", "Clear 5 runs with Candice deploying Kyurem."),
    ("Frost Family Duel", "Clear a run using Candice with Shiny Mega Abomasnow and Snover."),
    ("Absolute Freeze Faceoff", "Clear a run using Candice with Kyurem and Articuno."),
    ("Icicle Steeds Duel", "Clear a run using Candice with Ice Rider Calyrex and Glastrier."),
    ("Azure Harmony", "Clear a run using Candice with Kyogre and Piplup."),
    ("Ocean Heir Duel", "Clear a run using Candice with Manaphy and Froakie."),
    ("Hydro Lancer Burst", "Clear a run using Candice with Palkia and Clauncher."),
    ("Candice • Snowpoint Overlord+", "Reach mastery level 20 with Candice."),
    ("Aquatic Nobility Trio", "Clear a run using Candice with Suicune, male Frillish, and female Frillish."),
    ("Biting Blizzard Trio", "Clear a run using Candice with Shiny Mega Abomasnow, Cloyster, and Amaura."),
    ("Adventure Road I", "During this season, start 3 Adventures."),
    ("Adventure Road II", "During this season, start 5 Adventures."),
    ("Adventure Road III", "During this season, start 10 Adventures."),
    ("Adventure Road IV", "During this season, start 20 Adventures."),
    ("Adventure Road V", "During this season, start 30 Adventures."),
    ("Adventure Road VI", "During this season, start 40 Adventures."),
    ("Adventure Master I", "During this season, clear an Adventure once."),
    ("Adventure Master II", "During this season, clear Adventures 3 times."),
    ("Adventure Master III", "During this season, clear Adventures 5 times."),
    ("Adventure Master IV", "During this season, clear Adventures 10 times."),
    ("Adventure Master V", "During this season, clear Adventures 15 times."),
    ("Fire Specialty", "Clear an Adventure while four or more Pokémon on the board are Fire-type."),
    ("Fighting Specialty", "Clear an Adventure while four or more Pokémon on the board are Fighting-type."),
    ("Grass Specialty", "Clear an Adventure while four or more Pokémon on the board are Grass-type."),
    ("Normal Specialty", "Clear an Adventure while four or more Pokémon on the board are Normal-type."),
    ("Steel Specialty", "Clear an Adventure while four or more Pokémon on the board are Steel-type."),
    ("Ghost Specialty", "Clear an Adventure while four or more Pokémon on the board are Ghost-type."),
    ("Dark Specialty", "Clear an Adventure while four or more Pokémon on the board are Dark-type."),
    ("Psychic Specialty", "Clear an Adventure while four or more Pokémon on the board are Psychic-type."),
    ("Training Expertise", "Clear an Adventure while two or more Pokémon on the board are 4★."),
    ("Powered Promotions", "During this season, raise Pokémon to 4★ ten times via Promote Strengthening."),
    ("Fairy Specialty", "Clear an Adventure while four or more Pokémon on the board are Fairy-type."),
]
