#!/usr/bin/env python3
"""Translate game_config/auto_chess/cards.csv Chinese UI text to English (brackets from key_words.csv)."""
from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CARDS = ROOT / "game_config/auto_chess/cards.csv"
KEY_WORDS = ROOT / "game_config/auto_chess/key_words.csv"
DICT_MD = ROOT / "GAME_DICTIONARY.md"

CJK_RE = re.compile(r"[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\u4e00-\u9fff\uff00-\uffef]")

# name, findDesc, cardEffect, desc, keyWords (see header row 0)
DATA_COLS = (1, 5, 10, 19, 24)


def load_bracket_map() -> dict[str, str]:
    m: dict[str, str] = {}
    with open(KEY_WORDS, newline="", encoding="utf-8") as f:
        r = csv.reader(f)
        rows = list(r)
    for row in rows[3:]:
        if len(row) < 4:
            continue
        name, _desc, key = row[1], row[2], row[3]
        if key.startswith("【") and name.startswith("【"):
            m[key.strip()] = name.strip()
    return m


def load_pokemon_cn_en() -> dict[str, str]:
    out: dict[str, str] = {}
    text = DICT_MD.read_text(encoding="utf-8")
    for line in text.splitlines():
        if not line.strip().startswith("|"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 5:
            continue
        try:
            int(parts[1])
        except ValueError:
            continue
        cn, en = parts[2], parts[3]
        if cn and en and not cn.startswith(":"):
            out[cn] = en
    return out


# Names / phrases not guaranteed in dictionary table
EXTRA_NAMES: dict[str, str] = {
    "莱希拉姆": "Reshiram",
    "风速狗测试": "Arcanine (Test)",
    "奇怪的蛋": "Strange Egg",
    "测试木桩": "Test Dummy",
    "商店占位": "Shop Placeholder",
    "怪蛋": "Odd Egg",
    "恶作剧之影": "Mischief Shadow",
    "惩戒胡帕": "Hoopa Confined",
    "解放胡帕": "Hoopa Unbound",
    "谜拟Q": "Mimikyu",
    "谜拟Ｑ": "Mimikyu",
    "百变怪·橙色": "Ditto (Orange)",
    "百变怪·紫色": "Ditto (Purple)",
    "百变怪·红色": "Ditto (Red)",
    "美洛耶塔·歌声": "Meloetta (Aria Forme)",
    "美洛耶塔·舞步": "Meloetta (Pirouette Forme)",
    "谢米·陆地": "Shaymin (Land Forme)",
    "谢米·天空": "Shaymin (Sky Forme)",
    "轻飘飘·雌": "Frillish (Female)",
    "轻飘飘·雄": "Frillish (Male)",
    "蕾冠王·白马": "Calyrex (Ice Rider)",
    "坚盾剑怪·盾牌": "Aegislash (Shield Forme)",
    "闪光超级暴雪王": "Shiny Mega Abomasnow",
    "闪光超级沙奈朵": "Shiny Mega Gardevoir",
    "闪光超级妙蛙花": "Shiny Mega Venusaur",
    "闪光超级蜥蜴王": "Shiny Mega Sceptile",
    "闪光超级耿鬼": "Shiny Mega Gengar",
    "闪光超级路卡利欧": "Shiny Mega Lucario",
    "闪光超级巨金怪": "Shiny Mega Metagross",
    "艾岚超级喷火龙X": "Alain's Mega Charizard X",
    "假面超级火焰鸡": "Masked Mega Blaziken",
    "小智版甲贺忍蛙": "Ash-Greninja",
    "凯路迪欧·觉悟": "Keldeo (Resolute Form)",
    "波尔凯尼恩": "Volcanion",
    "鳃鱼龙": "Dracovish",
    "起源梦幻": "Origin Mew",
    "无极汰那": "Eternatus",
    "恶食大王": "Guzzlord",
    "露奈雅拉": "Lunala",
    "萨戮德": "Zarude",
    "雪暴马": "Glastrier",
    "灵幽马": "Spectrier",
    "冰雪龙": "Amaura",
    "几何雪花": "Cryogonal",
    "喷嚏熊": "Cubchoo",
    "海豹球": "Spheal",
    "铁臂枪虾": "Clauncher",
    "蚊香蝌蚪": "Poliwag",
    "丑丑鱼": "Feebas",
    "泳圈鼬": "Buizel",
    "球球海狮": "Popplio",
    "泪眼蜥": "Sobble",
    "敲音猴": "Grookey",
    "迷你芙": "Sprigatito",
    "甜竹竹": "Bounsweet",
    "纸御剑": "Kartana",
    "木木枭": "Rowlet",
    "哈力栗": "Chespin",
    "喇叭芽": "Bellsprout",
    "草苗龟": "Turtwig",
    "菊草叶": "Chikorita",
    "走路草": "Oddish",
    "长尾火狐": "Braixen",
    "呆火驼": "Numel",
    "火斑喵": "Litten",
    "炎兔儿": "Scorbunny",
    "爆焰龟兽": "Turtonator",
    "砰头小丑": "Blacephalon",
    "暖暖猪": "Tepig",
    "火球鼠": "Cyndaquil",
    "小狮狮": "Litleo",
    "火狐狸": "Fennekin",
    "晃晃斑": "Spinda",
    "泡沫栗鼠": "Minccino",
    "咕妞妞": "Whismur",
    "懒人獭": "Slakoth",
    "小福蛋": "Happiny",
    "宝宝丁": "Igglybuff",
    "嘟嘟": "Doduo",
    "大葱鸭": "Farfetch'd",
    "青绵鸟": "Swablu",
    "七夕青鸟": "Altaria",
    "猫老大": "Persian",
    "烈雀": "Spearow",
    "小拉达": "Rattata",
    "大舌头": "Lickitung",
    "小卡比兽": "Munchlax",
    "胖丁": "Jigglypuff",
    "波波": "Pidgey",
    "鸭嘴宝宝": "Magby",
    "小火龙": "Charmander",
    "喷火龙": "Charizard",
    "妙蛙种子": "Bulbasaur",
    "杰尼龟": "Squirtle",
    "喵喵": "Meowth",
    "凤王": "Ho-Oh",
    "卡蒂狗": "Growlithe",
    "火焰鸟": "Moltres",
    "炎帝": "Entei",
    "席多蓝恩": "Heatran",
    "火稚鸡": "Torchic",
    "小火焰猴": "Chimchar",
    "比克提尼": "Victini",
    "盖欧卡": "Kyogre",
    "玛纳霏": "Manaphy",
    "角金鱼": "Goldeen",
    "大舌贝": "Shellder",
    "帕路奇亚": "Palkia",
    "暴鲤龙": "Gyarados",
    "水君": "Suicune",
    "呱呱泡蛙": "Froakie",
    "莲叶童子": "Lotad",
    "波加曼": "Piplup",
    "铁哑铃": "Beldum",
    "水跃鱼": "Mudkip",
    "木守宫": "Treecko",
    "藤藤蛇": "Snivy",
    "毕力吉翁": "Virizion",
    "时拉比": "Celebi",
    "雪笠怪": "Snover",
    "雪童子": "Snorunt",
    "雪妖女": "Froslass",
    "急冻鸟": "Articuno",
    "拉普拉斯": "Lapras",
    "酋雷姆": "Kyurem",
    "雷吉艾斯": "Regice",
    "刺甲贝": "Cloyster",
    "迷你冰": "Vanillite",
    "玛夏多": "Marshadow",
    "利欧路": "Riolu",
    "腕力": "Machop",
    "飞腿郎": "Hitmonlee",
    "战舞郎": "Hitmontop",
    "快拳郎": "Hitmonchan",
    "搬运小匠": "Timburr",
    "摔角鹰人": "Hawlucha",
    "猴怪": "Mankey",
    "葱游兵": "Sirfetch'd",
    "藏玛然特": "Zamazenta",
    "童偶熊": "Bewear",
    "洛奇亚": "Lugia",
    "基拉祈": "Jirachi",
    "超梦": "Mewtwo",
    "梦幻": "Mew",
    "凯西": "Abra",
    "小果然": "Wynaut",
    "克雷色利亚": "Cresselia",
    "哥德宝宝": "Gothita",
    "宝石海星": "Starmie",
    "艾路雷朵": "Gallade",
    "奈克洛兹玛": "Necrozma",
    "蛋蛋": "Exeggcute",
    "呆呆兽": "Slowpoke",
    "梦妖": "Misdreavus",
    "夜巡灵": "Duskull",
    "烛光灵": "Litwick",
    "鬼斯": "Gastly",
    "怨影娃娃": "Shuppet",
    "勾魂眼": "Sableye",
    "小木灵": "Phantump",
    "骑拉帝纳": "Giratina",
    "伊裴尔塔尔": "Yveltal",
    "达克莱伊": "Darkrai",
    "阿勃梭鲁": "Absol",
    "索罗亚": "Zorua",
    "甲贺忍蛙": "Greninja",
    "单首龙": "Deino",
    "戴鲁比": "Houndour",
    "流氓鳄": "Krookodile",
    "狃拉": "Sneasel",
    "混混鳄": "Krokorok",
    "美录坦": "Meltan",
    "玛机雅娜": "Magearna",
    "大钢蛇": "Steelix",
    "可可多拉": "Aron",
    "勾帕路翁": "Cobalion",
    "齿轮儿": "Klink",
    "龙头地鼠": "Excadrill",
    "雷吉斯奇鲁": "Registeel",
    "索尔迦雷欧": "Solgaleo",
    "垒磊石": "Stakataka",
    "帝牙卢卡": "Dialga",
    "哲尔尼亚斯": "Xerneas",
    "苍响": "Zacian",
    "沙奈朵": "Gardevoir",
    "奇鲁莉安": "Kirlia",
    "波克比": "Togepi",
    "花蓓蓓": "Flabébé",
    "胖可丁": "Wigglytuff",
    "西狮海壬": "Primarina",
    "拉鲁拉丝": "Ralts",
    "胖甜妮": "Slurpuff",
    "绵绵泡芙": "Swirlix",
    "皮宝宝": "Cleffa",
    "露力丽": "Azurill",
    "魔尼尼": "Mime Jr.",
    "捣蛋小妖": "Impidimp",
    "蒂安希": "Diancie",
    "姆克儿": "Starly",
    "老翁龙": "Drampa",
    "熊徒弟": "Kubfu",
    "盖诺赛克特": "Genesect",
    "大吾超级巨金怪": "Steven's Mega Metagross",
    "爱管侍": "Indeedee",
    "催眠貘": "Drowzee",
    "拉帝亚斯": "Latias",
    "拉帝欧斯": "Latios",
    "艾姆利多": "Mesprit",
    "由克希": "Uxie",
    "亚克诺姆": "Azelf",
    "卡璞·鸣鸣": "Tapu Koko",
    "卡璞·蝶蝶": "Tapu Lele",
    "卡璞·哞哞": "Tapu Bulu",
    "卡璞·鳍鳍": "Tapu Fini",
    "小锻匠": "Tinkatink",
    "功夫鼬": "Mienfoo",
    "无畏小子": "Tyrogue",
    "玛沙那": "Meditite",
    "铁火辉夜": "Celesteela",
    "独剑鞘": "Honedge",
    "小磁怪": "Magnemite",
    "可达鸭": "Psyduck",
    "海星星": "Staryu",
    "鲤鱼王": "Magikarp",
    "小锯鳄": "Totodile",
    "水水獭": "Oshawott",
    "凯路迪欧": "Keldeo",
    "霏欧纳": "Phione",
    "阿柏蛇": "Ekans",
    "独角虫": "Weedle",
    "大针蜂": "Beedrill",
    "尼多兰": "Nidoran♀",
    "尼多朗": "Nidoran♂",
    "毛球": "Venonat",
    "臭泥": "Grimer",
    "瓦斯弹": "Koffing",
    "不良蛙": "Croagunk",
    "百足蜈蚣": "Venipede",
    "超音蝠": "Zubat",
    "好坏星": "Mareanie",
    "毒贝比": "Poipole",
    "虚吾伊德": "Nihilego",
}

# Phrase layer (after keyword brackets). Longest matches first; avoid single-han replacements.
PHRASES: list[tuple[str, str]] = [
    ("（仅战斗外生效）", "(only outside battle)"),
    ("（无法对草苗龟造成伤害）", "(cannot damage Turtwig)"),
    ("（对【晕眩】目标造成", "(deals to 【Stun】ned targets "),
    ("（N为", "(N is "),
    ("（每次精灵阵亡，额外+", "(each time a Pokémon is knocked out, additionally +"),
    ("（敌方每次阵亡，额外+", "(each time an enemy is knocked out, additionally +"),
    ("（每累计触发", "(every "),
    ("次后额外+8）", " triggers, additionally +8)"),
    ("训练家已损失血量", "HP the Trainer has lost"),
    ("倍当前金币数量", "× current gold"),
    ("倍伤害量的攻击", "× damage taken as Attack"),
    ("倍失去的生命值）", "× HP lost)"),
    ("倍自身对应属性）", "× its matching stats)"),
    ("倍自身攻击减少值）", "× Attack lost)"),
    ("倍自身护甲值）", "× its Armor)"),
    ("倍本次获得护甲值的", "× Armor gained this time)"),
    ("倍本次受到的治疗量）", "× healing received this time)"),
    ("倍流水值）", "× Flow value)"),
    ("倍破甲值）", "× Armor Shred value)"),
    ("倍伤害量）", "× damage dealt)"),
    ("倍护甲值）", "× Armor value)"),
    ("倍治疗量）", "× healing received)"),
    ("倍治疗的", "× healing "),
    ("倍自身攻击）", "× its Attack)"),
    ("倍自身攻击", "× its Attack"),
    ("倍自身生命", "× its HP"),
    ("倍自身护甲", "× its Armor"),
    ("倍攻击和生命", "× Attack and HP"),
    ("倍对应属性）", "× matching stats)"),
    ("倍商店等级的随机精灵的原始复制", "-star base copy of a random Pokémon up to shop level"),
    ("流水值", "Flow value"),
    ("己方火系精灵", "allied Fire-type Pokémon"),
    ("己方水系精灵", "allied Water-type Pokémon"),
    ("己方草系精灵", "allied Grass-type Pokémon"),
    ("己方钢系精灵", "allied Steel-type Pokémon"),
    ("己方斗系精灵", "allied Fighting-type Pokémon"),
    ("己方鬼系精灵", "allied Ghost-type Pokémon"),
    ("己方波克比之外的精灵", "allied Pokémon other than Togepi"),
    ("己方场上的其他精灵", "another allied Pokémon on the field"),
    ("己方精灵触发或受到【流水】效果时", "when an allied Pokémon triggers or receives 【Flow】"),
    ("己方精灵触发【流水】效果时", "when an allied Pokémon triggers 【Flow】"),
    ("己方精灵阵亡时", "when an allied Pokémon is knocked out"),
    ("己方精灵进场时", "when an allied Pokémon enters the field"),
    ("己方精灵行动前", "before an allied Pokémon acts"),
    ("己方精灵行动后", "after an allied Pokémon acts"),
    ("己方精灵受到攻击后", "after allied Pokémon take damage"),
    ("己方精灵受到【治疗】时", "when allied Pokémon are 【Heal】ed"),
    ("己方精灵受到攻击前", "before allied Pokémon take damage"),
    ("己方精灵失去【隐匿】时", "when allied Pokémon lose 【Stealth】"),
    ("己方精灵失去【护盾】时", "when allied Pokémon lose 【Shield】"),
    ("己方精灵获得护甲时", "when allied Pokémon gain Armor"),
    ("己方精灵获得【坚甲】", "allied Pokémon gain 【Fortified Armor】"),
    ("己方精灵的【计时】效果额外触发", "allied Pokémon's 【Timer】 effects additionally trigger"),
    ("己方精灵/【幻影】阵亡时", "when an allied Pokémon or 【Phantom】 is knocked out"),
    ("己方精灵/【幻影】", "allied Pokémon / 【Phantom】"),
    ("己方精灵", "allied Pokémon"),
    ("己方全体", "all allied Pokémon"),
    ("己方随机", "random allied"),
    ("己方其他", "other allied"),
    ("己方最左侧的其他精灵行动后", "after the leftmost other allied Pokémon acts"),
    ("己方", "allied"),
    ("敌方生命最高精灵", "the enemy Pokémon with the highest HP"),
    ("敌方被【冰冻】时", "when an enemy is 【Freeze】d"),
    ("敌方被添加【晕眩】时", "when 【Stun】 is applied to an enemy"),
    ("敌方精灵阵亡时", "when an enemy Pokémon is knocked out"),
    ("敌方精灵生命降低时", "when an enemy Pokémon loses HP"),
    ("敌方精灵获得【晕眩】时", "when an enemy gains 【Stun】"),
    ("敌方精灵受到伤害时", "when an enemy Pokémon takes damage"),
    ("敌方精灵", "enemy Pokémon"),
    ("敌方有精灵阵亡时", "when an enemy Pokémon is knocked out"),
    ("敌方空位", "an empty enemy slot"),
    ("敌方全体", "all enemies"),
    ("敌方随机", "random enemy"),
    ("敌方", "enemy"),
    ("除波波外的精灵", "a Pokémon other than Pidgey"),
    ("除波波外的己方精灵", "an allied Pokémon other than Pidgey"),
    ("除雪笠怪外的所有友方", "all allies other than Snover"),
    ("除玛纳霏外的己方场上水系精灵的复制", "a copy of another allied Water-type on the field besides Manaphy"),
    ("除自身外的全体单位", "all units except self"),
    ("除凤王外的火系精灵", "Fire-type Pokémon to Ho-Oh's left except Ho-Oh"),
    ("除露奈雅拉外的鬼系精灵", "Ghost-type allies other than Lunala"),
    ("己方【暴击】精灵", "allied 【Critical Hit】 Pokémon"),
    ("己方其他火系精灵", "other allied Fire-type Pokémon"),
    ("己方每有1个其他火系精灵", "for each other allied Fire-type Pokémon"),
    ("己方场上水系精灵的复制", "copy of an allied Water-type on the field"),
    ("己方场上", "on your field"),
    ("己方", "allied"),
    ("随机敌方精灵", "random enemy Pokémon"),
    ("随机敌方", "random enemy"),
    ("随机敌人", "random enemy"),
    ("随机1个敌人", "1 random enemy"),
    ("随机1张价格不高于", "1 random Pokémon card costing up to"),
    ("随机1张", "1 random"),
    ("随机永久【变形】为", "permanently 【Transform】 into"),
    ("随机【变形】为", "【Transform】 into"),
    ("随机【生长】效果", "random 【Growth】 effect"),
    ("随机【生长】", "random 【Growth】"),
    ("随机精灵的【幻影】", "a random Pokémon's 【Phantom】"),
    ("随机精灵", "a random Pokémon"),
    ("随机草系精灵", "a random Grass-type Pokémon"),
    ("有几率孵化", "chance to hatch"),
    ("永久消失", "removed permanently"),
    ("永久保留这部分属性", "keep these stat gains permanently"),
    ("若不需要治疗则为其永久", "If no heal was needed, instead permanently"),
    ("若目标被【晕眩】，则永久偷取", "If the target is 【Stun】ned, steal permanently"),
    ("若攻击者生命高于受击者，令两者交换生命值，并对受击者使用", "If the attacker's HP is higher than the defender's, swap their HP, then on the defender apply"),
    ("若己方存在【隐匿】单位", "If an allied 【Stealth】 unit exists"),
    ("若轻飘飘·雌在场", "If Frillish (Female) is on the field"),
    ("若轻飘飘·雄在场", "If Frillish (Male) is on the field"),
    ("若行动者为钢系", "If the actor is Steel-type"),
    ("若自身满生命值", "If at full HP"),
    ("若阵亡的是【幻影】", "If it was a 【Phantom】"),
    ("若目标生命低于自身攻击", "If the target's HP is below your Attack"),
    ("若其攻击为0", "If its Attack is 0"),
    ("若不需要治疗", "If healing is not needed"),
    ("将其解除并令其永久", "remove it and they permanently"),
    ("击杀【宿敌】后", "After defeating its 【Rival】,"),
    ("击杀者", "the scoring unit"),
    ("对最近的敌人造成", "Deal to the nearest enemy"),
    ("对最右侧敌方造成", "Deal to the rightmost enemy"),
    ("对最左侧敌人造成", "Deal to the leftmost enemy"),
    ("对攻击最高的敌人造成", "Deal to the enemy with highest Attack"),
    ("对双方所有精灵造成", "Deal to all Pokémon on both sides"),
    ("对己方所有精灵造成", "Deal to all allied Pokémon"),
    ("对己方随机", "To random allied"),
    ("对己方全体【治疗】", "【Heal】 all allies"),
    ("对随机敌人造成", "Deal to a random enemy"),
    ("对随机1个敌人造成", "Deal to 1 random enemy"),
    ("对除自身外的全体单位造成", "Deal to all units except self"),
    ("对攻击者造成", "Deal to the attacker"),
    ("对目标相邻单位造成", "Deal to units adjacent to the target"),
    ("对目标造成", "Deal to the target"),
    ("对敌方全体造成", "Deal to all enemies"),
    ("对敌方全体降低", "Lower all enemies by"),
    ("令击杀者变为【幻影】", "Turn the killer into a 【Phantom】"),
    ("令击杀者生命变为1", "Set the killer's HP to 1"),
    ("令攻击者的攻击变为与自身相同", "Set the attacker's Attack to match yours"),
    ("令攻击者和自身", "Grant the attacker and self"),
    ("令随机1个精灵返回手牌", "Return 1 random Pokémon to hand"),
    ("令手牌随机精灵进场", "Play 1 random Pokémon from hand"),
    ("令两者交换生命值", "Swap their HP"),
    ("令左侧相邻精灵的星级提升至与自身相等", "Raise the star rating of the left adjacent ally to match yours"),
    ("在自身右侧【召唤】1个它的复制品", "【Summon】 a copy of it to your right"),
    ("在敌方空位【召唤】", "【Summon】 on an empty enemy slot"),
    ("在右侧【召唤】一个除玛纳霏外的", "【Summon】 to the right a"),
    ("在右侧【召唤】一个", "【Summon】 to the right a"),
    ("在右侧【召唤】", "【Summon】 to the right"),
    ("场上精灵阵亡时", "When a field Pokémon is knocked out"),
    ("场上精灵", "Pokémon on the field"),
    ("场上除波波外的精灵", "a field Pokémon other than Pidgey"),
    ("场上随机精灵的【幻影】", "【Phantom】 of random field Pokémon"),
    ("将1个敌方变为【幻影】", "Turn 1 enemy into a 【Phantom】"),
    ("将$(star)$个己方【幻影】变为实体", "Turn $(star)$ allied 【Phantom】s real"),
    ("将生命最低的敌方视为【宿敌】", "Treat the lowest-HP enemy as 【Rival】"),
    ("将破甲最高的敌方视为【宿敌】", "Treat the highest Armor Shred enemy as 【Rival】"),
    ("将距离最近的敌人视为【宿敌】", "Treat the nearest enemy as 【Rival】"),
    ("将伤害转为等量【破甲】", "Convert damage to equal 【Armor Shred】"),
    ("将自身【破甲】值的", "Transfer self 【Armor Shred】 value"),
    ("转移给随机1个敌方精灵", "to 1 random enemy Pokémon"),
    ("转移给目标", "to the target"),
    ("受到【治疗】时", "When 【Heal】ed"),
    ("受到溢出【治疗】时", "When overhealed"),
    ("受到攻击后", "After taking damage"),
    ("受到攻击前", "Before taking damage"),
    ("受到攻击时", "When taking damage"),
    ("受到负面【状态】时", "When afflicted by negative 【Status】"),
    ("受到生命损失时", "When losing HP"),
    ("受到伤害时若自身没有【破甲】", "When taking damage, if you have no 【Armor Shred】"),
    ("失去所有护甲时", "When losing all Armor"),
    ("失去生命时", "When losing HP"),
    ("失去【隐匿】时", "When losing 【Stealth】"),
    ("失去护甲时", "When losing Armor"),
    ("与自身相邻的精灵受到负面【状态】时", "When an adjacent ally gets negative 【Status】"),
    ("与自身相邻的精灵", "Adjacent Pokémon"),
    ("与拉帝欧斯共同胜利时额外永久", "If you win together with Latios, additionally permanently"),
    ("与拉帝亚斯共同胜利时额外永久", "If you win together with Latias, additionally permanently"),
    ("任意其他精灵行动前", "Before any other Pokémon acts"),
    ("其他精灵阵亡后", "After other Pokémon are knocked out"),
    ("其他精灵阵亡时", "When other Pokémon are knocked out"),
    ("其他精灵行动前", "Before other Pokémon act"),
    ("其他全体单位", "all other units"),
    ("其他友方", "other allies"),
    ("全体单位", "all units"),
    ("全体精灵", "all Pokémon"),
    ("全体敌人", "all enemies"),
    ("所有友方", "all allies"),
    ("所有精灵", "all Pokémon"),
    ("所有敌人", "all enemies"),
    ("所有【守卫】精灵", "all 【Guard】 Pokémon"),
    ("每次精灵阵亡，额外", "each KO, additionally"),
    ("每累计触发3次", "every 3 cumulative triggers"),
    ("每打出$(7-star)$次事件卡", "every $(7-star)$ event cards played"),
    ("选择并永久变形成一个己方精灵", "Select and permanently 【Transform】 into an allied Pokémon"),
    ("选择一个己方精灵使其永久获得", "Select an allied Pokémon to permanently gain"),
    ("选择一个己方精灵使其永久提升属性", "Select an allied Pokémon to permanently raise stats"),
    ("选择一个草系精灵并获得其属性", "Select a Grass-type and copy its stats"),
    ("选择一个草系精灵，永久获得其攻击和生命", "Select a Grass-type; permanently copy its Attack and HP"),
    ("选择一个除波波外的己方精灵使其返回手牌", "Select an allied Pokémon other than Pidgey to return to hand"),
    ("选择一个目标使其永久获得", "Select a target to permanently gain"),
    ("选择一个场上除波波外的精灵，使其返回手牌", "Select a field Pokémon other than Pidgey to return to hand"),
    ("选择一个其他精灵永久获得【守卫】", "Select another Pokémon to permanently gain 【Guard】"),
    ("选择一个精灵，使其永久", "Select a Pokémon to permanently"),
    ("选择一个精灵，永久【变形】为选择的精灵的原始复制", "Select a Pokémon; permanently 【Transform】 into its base copy"),
    ("相邻的精灵", "Adjacent Pokémon"),
    ("相邻单位", "adjacent units"),
    ("相邻精灵", "adjacent Pokémon"),
    ("最左侧精灵", "leftmost Pokémon"),
    ("最左侧敌人", "leftmost enemy"),
    ("右侧相邻精灵的", "right-adjacent ally's"),
    ("行动次数+$(1*star)$", "Actions +$(1*star)$"),
    ("行动次数+1", "Actions +1"),
    ("行动后【晕眩】所有敌人", "After acting, 【Stun】 all enemies"),
    ("行动后，返回手牌并令己方精灵", "After acting, return to hand and allied Pokémon"),
    ("行动后，为自身和相邻精灵解除", "After acting, cleanse self and adjacent allies of"),
    ("行动后，令自身和最近的敌人返回手牌", "After acting, return self and nearest enemy to hand"),
    ("行动后，偷取其", "After acting, steal"),
    ("行动后【魅惑】", "After acting, 【Charm】"),
    ("行动后重置【应激】触发次数", "After acting, reset 【Reactive】 trigger count"),
    ("行动后", "After acting"),
    ("行动前【消灭】", "Before acting, 【Destroy】"),
    ("行动前【召唤】", "Before acting, 【Summon】"),
    ("行动前解除随机", "Before acting, cleanse random"),
    ("行动前将1个敌方变为", "Before acting, turn 1 enemy into"),
    ("行动前对随机", "Before acting, to random"),
    ("行动前对目标", "Before acting, on target"),
    ("行动前在右侧【召唤】", "Before acting, 【Summon】 to the right"),
    ("行动前，偷取其", "Before acting, steal"),
    ("行动前，若自身满生命值", "Before acting, if at full HP"),
    ("行动前，将自身【破甲】值的", "Before acting, transfer self 【Armor Shred】"),
    ("行动前，自身", "Before acting, self"),
    ("行动前清除自身【破甲】", "Before acting, clear self 【Armor Shred】"),
    ("行动前自身", "Before acting, self"),
    ("行动前", "Before acting"),
    ("攻击后不会失去【暴击】", "Does not lose 【Critical Hit】 after attacking"),
    ("攻击后【晕眩】目标并【治疗】自身", "After attacking, 【Stun】 target and 【Heal】 self"),
    ("攻击后【晕眩】目标并降低其", "After attacking, 【Stun】 target and lower its"),
    ("攻击后【晕眩】自身", "After attacking, 【Stun】 self"),
    ("攻击后【晕眩】目标", "After attacking, 【Stun】 target"),
    ("攻击后获得1张【生长】", "After attacking, gain 1 【Growth】"),
    ("攻击后对目标额外造成等于", "After attacking, additionally deal to target"),
    ("攻击后", "After attacking"),
    ("攻击【破甲】单位前自身获得【暴击】", "Before attacking an 【Armor Shred】 unit, gain 【Critical Hit】"),
    ("攻击【破甲】单位时自身不受反击伤害", "When attacking 【Armor Shred】 units, take no counter damage"),
    ("攻击【破甲】单位后，自身获得1次行动", "After attacking an 【Armor Shred】 unit, gain 1 action"),
    ("攻击【冰冻】目标时", "When attacking a 【Freeze】d target"),
    ("攻击【幻影】时不受反击且永久", "When attacking 【Phantom】, no counter and permanently"),
    ("攻击【幻影】前额外增加其", "Before attacking 【Phantom】, add to it"),
    ("攻击带有护甲的精灵前", "Before attacking an Armored Pokémon"),
    ("攻击前对目标造成", "Before attacking, deal to target"),
    ("攻击前对随机", "Before attacking, to random"),
    ("攻击前自身", "Before attacking, self"),
    ("攻击前，偷取其", "Before attacking, steal"),
    ("攻击前偷取攻击目标", "Before attacking, steal from target"),
    ("攻击前偷取目标", "Before attacking, steal from target"),
    ("攻击前对目标相邻单位造成等于自身攻击的【破甲】", "Before attacking, apply 【Armor Shred】 to adjacent targets equal to your Attack"),
    ("攻击前对目标造成与自身攻击等量的【破甲】", "Before attacking, apply 【Armor Shred】 equal to your Attack"),
    ("攻击前", "Before attacking"),
    ("攻击最高的", "highest Attack"),
    ("攻击力", "Attack power"),
    ("攻击变为与自身相同", "Attack becomes equal to yours"),
    ("攻击和生命提升", "Attack and HP are multiplied"),
    ("攻击和生命与自身一致", "Attack and HP match yours"),
    ("攻击和生命", "Attack and HP"),
    ("攻击低于自身的敌人", "enemies with lower Attack than you"),
    ("攻击小于", "Attack less than"),
    ("攻击龙系精灵前", "Before attacking a Dragon-type"),
    ("点技能伤害", " skill damage"),
    ("点【破甲】", " 【Armor Shred】"),
    ("点攻击", " Attack"),
    ("点生命", " HP"),
    ("点护甲", " Armor"),
    ("降低随机", "Lower random"),
    ("降低其", "Lower its"),
    ("降低5点攻击并将其【晕眩】", "lower Attack by 5 and 【Stun】"),
    ("获得等于", "Gain"),
    ("获得【护盾】和【突袭】", "gain 【Shield】 and 【Ambush】"),
    ("获得1次行动", "Gain 1 action"),
    ("获得N点护甲", "Gain N Armor"),
    ("获得护甲时", "When gaining Armor"),
    ("获得随机1张", "Gain 1 random"),
    ("获得1张【生长】", "Gain 1 【Growth】"),
    ("获得$(3*star)$金币", "Gain $(3*star)$ gold"),
    ("获得$(1*star)$金币", "Gain $(1*star)$ gold"),
    ("获得$(1*star)$张【生长】", "Gain $(1*star)$ 【Growth】"),
    ("获得【暴击】并立即行动", "Gain 【Critical Hit】 and act immediately"),
    ("获得等量【破甲】", "Gain equal 【Armor Shred】"),
    ("给己方精灵【治疗】", "【Heal】 allied Pokémon"),
    ("刷新商店后", "After refreshing the shop"),
    ("本局游戏中，【生长】额外提供", "This match, 【Growth】 additionally grants"),
    ("本局游戏中", "This match"),
    ("被使用【生长】时", "When targeted by 【Growth】"),
    ("被使用【大葱】时", "When targeted by 【Leek】"),
    ("被添加【晕眩】时", "When 【Stun】 is applied"),
    ("被【晕眩】时", "While 【Stun】ned"),
    ("打出事件卡时", "When you play an event card"),
    ("准备阶段结束时，己方随机2个精灵永久", "At end of prep phase, 2 random allies permanently"),
    ("准备阶段结束时，获得1张【生长】", "At end of prep phase, gain 1 【Growth】"),
    ("准备阶段结束时", "At end of prep phase"),
    ("战斗阶段，己方钢系精灵获得护甲时", "During battle, when allied Steel-type gains Armor"),
    ("战斗阶段，自身获得护甲时", "During battle, when self gains Armor"),
    ("战斗阶段", "During battle"),
    ("战斗中，己方【强攻】精灵进场时获得【护盾】和【突袭】", "In battle, allied 【Brute Force】 entering gain 【Shield】 and 【Ambush】"),
    ("战斗中，自身受到负面【状态】时", "In battle, when self gets negative 【Status】"),
    ("战斗开始时进入【隐匿】", "At battle start, enter 【Stealth】"),
    ("进入【隐匿】时，获得【护盾】", "On entering 【Stealth】, gain 【Shield】"),
    ("进入【隐匿】", "Enter 【Stealth】"),
    ("敌方行动后若存活，自身从手牌进场", "After an enemy acts, if it survives, self enters from hand"),
    ("敌方行动后若存活", "After an enemy acts, if it survives"),
    ("商店升级费用", "Shop upgrade cost"),
    ("商店等级的随机精灵", "random Pokémon up to shop level"),
    ("卖出时获得", "When sold, gain"),
    ("可触发升星", "Can trigger star promotion"),
    ("负面【状态】", "negative 【Status】"),
    ("解除随机", "Cleanse random"),
    ("解除$(1*star)$个负面【状态】", "Remove $(1*star)$ negative 【Status】"),
    ("解除随机$(star)$个己方精灵的负面【状态】", "Remove negative 【Status】 from $(star)$ random allies"),
    ("产生的护甲值", "Armor gained"),
    ("均分给己方水系精灵", "split among allied Water-types"),
    ("均分给所有敌方", "split among all enemies"),
    ("均分给己方其他精灵", "split among other allies"),
    ("额外翻倍一次", "doubles once more"),
    ("额外永久", "additionally permanently"),
    ("额外获得", "additionally gain"),
    ("额外触发", "additional triggers"),
    ("返回手牌", "return to hand"),
    ("返回手牌；", "return to hand;"),
    ("返回手牌并令", "return to hand and"),
    ("战斗结束时", "At battle end"),
    ("用$(star)$次随机【生长】", "apply 【Growth】 $(star)$ times randomly"),
    ("用1次随机【生长】效果", "apply 1 random 【Growth】 effect"),
    ("使用1张【生长】", "Use 1 【Growth】"),
    ("触发右侧相邻精灵的【击破】效果", "Trigger right neighbor's 【Break】"),
    ("触发$(1*star)$次", "Trigger $(1*star)$ times"),
    ("触发或受到【流水】效果时", "when triggering or receiving 【Flow】"),
    ("触发【流水】效果时", "when 【Flow】 triggers"),
    ("进场时", "when entering"),
    ("进场时对随机敌人造成", "On entry, deal to random enemy"),
    ("进场时，使其永久", "On entry, permanently"),
    ("进场时，自身永久", "On entry, self permanently"),
    ("进场", "enters the field"),
    ("手牌", "hand"),
    ("星级为", "at"),
    ("星级提升至与自身相等", "star rating matches yours"),
    ("升星", "star promotion"),
    ("训练家", "Trainer"),
    ("精灵卡", "Pokémon card"),
    ("精灵", "Pokémon"),
    ("友方", "allies"),
    ("火系精灵", "Fire-type Pokémon"),
    ("水系精灵", "Water-type Pokémon"),
    ("草系精灵", "Grass-type Pokémon"),
    ("电系精灵", "Electric-type Pokémon"),
    ("冰系精灵", "Ice-type Pokémon"),
    ("斗系精灵", "Fighting-type Pokémon"),
    ("虫系精灵", "Bug-type Pokémon"),
    ("毒系精灵", "Poison-type Pokémon"),
    ("钢系精灵", "Steel-type Pokémon"),
    ("龙系精灵", "Dragon-type Pokémon"),
    ("恶系精灵", "Dark-type Pokémon"),
    ("超能系精灵", "Psychic-type Pokémon"),
    ("妖精系精灵", "Fairy-type Pokémon"),
    ("幽灵系精灵", "Ghost-type Pokémon"),
    ("鬼系精灵", "Ghost-type Pokémon"),
    ("一般系精灵", "Normal-type Pokémon"),
    ("火系", "Fire-type"),
    ("水系", "Water-type"),
    ("草系", "Grass-type"),
    ("电系", "Electric-type"),
    ("冰系", "Ice-type"),
    ("斗系", "Fighting-type"),
    ("虫系", "Bug-type"),
    ("毒系", "Poison-type"),
    ("钢系", "Steel-type"),
    ("龙系", "Dragon-type"),
    ("恶系", "Dark-type"),
    ("超能系", "Psychic-type"),
    ("妖精系", "Fairy-type"),
    ("幽灵系", "Ghost-type"),
    ("鬼系", "Ghost-type"),
    ("一般系", "Normal-type"),
    ("自身左侧除凤王外的火系精灵阵亡时", "When a Fire-type to your left except Ho-Oh is knocked out"),
    ("自身左侧", "to your left"),
    ("自身右侧", "to your right"),
    ("自身被【晕眩】时", "While self is 【Stun】ned"),
    ("自身攻击减半", "halve self's Attack"),
    ("自身攻击与生命相同", "Attack equals HP"),
    ("自身行动后", "After self acts"),
    ("自身行动前", "Before self acts"),
    ("自身受到", "When self takes"),
    ("自身失去护甲时", "When self loses Armor"),
    ("自身重复获得【护盾】时", "When self gains 【Shield】 again"),
    ("自身获得【护盾】", "Self gains 【Shield】"),
    ("自身", "this unit"),
    ("自身攻击前若目标生命低于自身攻击", "before self attacks, if target HP is below your Attack"),
    ("目标生命低于自身攻击", "target HP below your Attack"),
    ("先将其【消灭】", "【Destroy】 it first"),
    ("击杀【宿敌】", "defeat its 【Rival】"),
    ("阵亡时", "when knocked out"),
    ("阵亡后", "after being knocked out"),
    ("偷取攻击者", "Steal from the attacker"),
    ("偷取随机敌人", "Steal from a random enemy"),
    ("偷取其", "Steal from it"),
    ("偷取", "Steal"),
    ("永久", "permanently"),
    ("随机", "random"),
    ("金币", "gold"),
    ("护甲", "Armor"),
    ("生命", "HP"),
    ("治疗量", "healing"),
    ("技能伤害", "skill damage"),
    ("不受反击的攻击", "an attack that takes no counter"),
    ("不受反击", "take no counter"),
    ("立即行动", "act immediately"),
    ("并使其", "and"),
    ("并", "and"),
    ("然后", "then"),
    ("或", " or "),
    ("及", " and "),
]



def apply_brackets(s: str, bm: dict[str, str]) -> str:
    for cn, en in sorted(bm.items(), key=lambda x: -len(x[0])):
        s = s.replace(cn, en)
    return s


def apply_phrases(s: str) -> str:
    for cn, en in PHRASES:
        s = s.replace(cn, en)
    return s


def translate_name(name: str, names: dict[str, str]) -> str:
    if not name:
        return name
    inner = name
    if name.startswith("|") and name.endswith("|"):
        inner = name[1:-1]
    if inner in EXTRA_NAMES:
        en = EXTRA_NAMES[inner]
    else:
        en = names.get(inner, inner)
    if name.startswith("|") and name.endswith("|"):
        return f"|{en}|"
    return en


def translate_field(s: str, bm: dict[str, str]) -> str:
    if not s or not CJK_RE.search(s):
        return s
    s = apply_brackets(s, bm)
    s = apply_phrases(s)
    s = re.sub(r"  +", " ", s)
    return s


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    bm = load_bracket_map()
    names = {**load_pokemon_cn_en(), **EXTRA_NAMES}

    with open(CARDS, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    if len(rows) < 4:
        print("Unexpected CSV", file=sys.stderr)
        return 1

    out_rows = rows[:3]
    leftover = 0
    for i, row in enumerate(rows[3:], start=3):
        if len(row) < 27:
            row = row + [""] * (27 - len(row))
        row = row[:27]
        row[1] = translate_name(row[1], names)
        for ci in (5, 10, 19, 24):
            row[ci] = translate_field(row[ci], bm)
        if any(CJK_RE.search(row[c] or "") for c in DATA_COLS):
            leftover += 1
        out_rows.append(row)

    if args.dry_run:
        print(f"Rows with possible remaining CJK in translated cols: {leftover}")
        return 0

    with open(CARDS, "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(out_rows)

    print(f"Wrote {CARDS}; rows flagged with possible CJK: {leftover}")
    return 0 if leftover == 0 else 0


if __name__ == "__main__":
    raise SystemExit(main())
