--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[3] = {[135] = 5, __size = 1}, 
	[4] = {[135] = 10, __size = 1}, 
	[5] = {[135] = 20, __size = 1}, 
	[6] = {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}, 
	[7] = {[136] = 1, [135] = 60, __size = 2}, 
	[8] = {[136] = 2, [135] = 300, __size = 2}, 
	[9] = {[136] = 3, [135] = 1000, __size = 2}, __size = 7}
local __data_t__effect = {
	[100104] = __predefine_t__[6],
	[100066] = __predefine_t__[6],
	[100065] = __predefine_t__[6],
	[100064] = __predefine_t__[6],
	[100085] = __predefine_t__[6],
	[100084] = __predefine_t__[6],
	[100106] = __predefine_t__[6],
	[100086] = __predefine_t__[6],
	[100005] = __predefine_t__[6],
	[100004] = __predefine_t__[6],
	[100006] = __predefine_t__[6],
	[100105] = __predefine_t__[6],
	[100026] = __predefine_t__[6],
	[100025] = __predefine_t__[6],
	[100024] = __predefine_t__[6],
	[100045] = __predefine_t__[6],
	[100044] = __predefine_t__[6],
	[100046] = __predefine_t__[6]
}
local __data_t__decomposeReturn = {
	[100082] = __predefine_t__[4],
	[100104] = __predefine_t__[7],
	[100105] = __predefine_t__[8],
	[100106] = __predefine_t__[9],
	[100101] = __predefine_t__[3],
	[100102] = __predefine_t__[4],
	[100103] = __predefine_t__[5],
	[100084] = __predefine_t__[7],
	[100025] = __predefine_t__[8],
	[100063] = __predefine_t__[5],
	[100062] = __predefine_t__[4],
	[100061] = __predefine_t__[3],
	[100024] = __predefine_t__[7],
	[100066] = __predefine_t__[9],
	[100065] = __predefine_t__[8],
	[100064] = __predefine_t__[7],
	[100085] = __predefine_t__[8],
	[100023] = __predefine_t__[5],
	[100086] = __predefine_t__[9],
	[100081] = __predefine_t__[3],
	[100083] = __predefine_t__[5],
	[100022] = __predefine_t__[4],
	[100005] = __predefine_t__[8],
	[100004] = __predefine_t__[7],
	[100006] = __predefine_t__[9],
	[100001] = __predefine_t__[3],
	[100003] = __predefine_t__[5],
	[100002] = __predefine_t__[4],
	[100041] = __predefine_t__[3],
	[100026] = __predefine_t__[9],
	[100043] = __predefine_t__[5],
	[100042] = __predefine_t__[4],
	[100045] = __predefine_t__[8],
	[100044] = __predefine_t__[7],
	[100021] = __predefine_t__[3],
	[100046] = __predefine_t__[9]
}

csv['emera']['emera'] = {
	[100001] = {
		id = 100001,
		name = '谜三角·绿',
		strengthSeq = 1,
		maxLevel = 30,
		baseAttr = 1,
		quality = 2,
		icon = 'config/item/emera/icon_lsb_1.png',
		style = 2,
		recastCostSeq = 1,
		decomposeReturn = __data_t__decomposeReturn[100001]
		-- {[135] = 5, __size = 1}
	},
	[100002] = {
		id = 100002,
		name = '谜三角·蓝',
		strengthSeq = 2,
		maxLevel = 30,
		baseAttr = 11,
		quality = 3,
		icon = 'config/item/emera/icon_lsb_2.png',
		style = 2,
		recastCostSeq = 2,
		linkageNum = 1,
		linkageLib = 3,
		decomposeReturn = __data_t__decomposeReturn[100002]
		-- {[135] = 10, __size = 1}
	},
	[100003] = {
		id = 100003,
		name = '谜三角·紫',
		strengthSeq = 3,
		maxLevel = 40,
		baseAttr = 21,
		quality = 4,
		icon = 'config/item/emera/icon_lsb_3.png',
		style = 2,
		recastCostSeq = 3,
		linkageNum = 1,
		linkageLib = 4,
		decomposeReturn = __data_t__decomposeReturn[100003]
		-- {[135] = 20, __size = 1}
	},
	[100004] = {
		id = 100004,
		name = '谜三角·橙',
		strengthSeq = 4,
		maxLevel = 40,
		baseAttr = 31,
		quality = 5,
		icon = 'config/item/emera/icon_lsb_4.png',
		style = 2,
		recastCostSeq = 4,
		linkageNum = 2,
		linkageLib = 5,
		effect = __data_t__effect[100004],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100004]
		-- {[136] = 1, [135] = 60, __size = 2}
	},
	[100005] = {
		id = 100005,
		name = '谜三角·红',
		strengthSeq = 5,
		baseAttr = 41,
		quality = 6,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsb_5.png',
		style = 2,
		recastCostSeq = 5,
		linkageNum = 3,
		linkageLib = 6,
		effect = __data_t__effect[100005],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100005]
		-- {[136] = 2, [135] = 300, __size = 2}
	},
	[100006] = {
		id = 100006,
		name = '谜三角·钻彩',
		strengthSeq = 6,
		baseAttr = 51,
		quality = 7,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsb_6.png',
		style = 2,
		recastCostSeq = 6,
		linkageNum = 3,
		linkageLib = 7,
		effect = __data_t__effect[100006],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100006]
		-- {[136] = 3, [135] = 1000, __size = 2}
	},
	[100021] = {
		id = 100021,
		name = '滴晶·绿',
		strengthSeq = 1,
		maxLevel = 30,
		baseAttr = 2,
		quality = 2,
		icon = 'config/item/emera/icon_lsd_1.png',
		style = 3,
		recastCostSeq = 1,
		decomposeReturn = __data_t__decomposeReturn[100021]
		-- {[135] = 5, __size = 1}
	},
	[100022] = {
		id = 100022,
		name = '滴晶·蓝',
		strengthSeq = 2,
		maxLevel = 30,
		baseAttr = 12,
		quality = 3,
		icon = 'config/item/emera/icon_lsd_2.png',
		style = 3,
		recastCostSeq = 2,
		linkageNum = 1,
		linkageLib = 3,
		decomposeReturn = __data_t__decomposeReturn[100022]
		-- {[135] = 10, __size = 1}
	},
	[100023] = {
		id = 100023,
		name = '滴晶·紫',
		strengthSeq = 3,
		maxLevel = 40,
		baseAttr = 22,
		quality = 4,
		icon = 'config/item/emera/icon_lsd_3.png',
		style = 3,
		recastCostSeq = 3,
		linkageNum = 1,
		linkageLib = 4,
		decomposeReturn = __data_t__decomposeReturn[100023]
		-- {[135] = 20, __size = 1}
	},
	[100024] = {
		id = 100024,
		name = '滴晶·橙',
		strengthSeq = 4,
		maxLevel = 40,
		baseAttr = 32,
		quality = 5,
		icon = 'config/item/emera/icon_lsd_4.png',
		style = 3,
		recastCostSeq = 4,
		linkageNum = 2,
		linkageLib = 5,
		effect = __data_t__effect[100024],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100024]
		-- {[136] = 1, [135] = 60, __size = 2}
	},
	[100025] = {
		id = 100025,
		name = '滴晶·红',
		strengthSeq = 5,
		baseAttr = 42,
		quality = 6,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsd_5.png',
		style = 3,
		recastCostSeq = 5,
		linkageNum = 3,
		linkageLib = 6,
		effect = __data_t__effect[100025],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100025]
		-- {[136] = 2, [135] = 300, __size = 2}
	},
	[100026] = {
		id = 100026,
		name = '滴晶·钻彩',
		strengthSeq = 6,
		baseAttr = 52,
		quality = 7,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsd_6.png',
		style = 3,
		recastCostSeq = 6,
		linkageNum = 3,
		linkageLib = 7,
		effect = __data_t__effect[100026],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100026]
		-- {[136] = 3, [135] = 1000, __size = 2}
	},
	[100041] = {
		id = 100041,
		name = '混方·绿',
		strengthSeq = 1,
		maxLevel = 30,
		baseAttr = 3,
		quality = 2,
		icon = 'config/item/emera/icon_lsc_1.png',
		style = 4,
		recastCostSeq = 1,
		decomposeReturn = __data_t__decomposeReturn[100041]
		-- {[135] = 5, __size = 1}
	},
	[100042] = {
		id = 100042,
		name = '混方·蓝',
		strengthSeq = 2,
		maxLevel = 30,
		baseAttr = 13,
		quality = 3,
		icon = 'config/item/emera/icon_lsc_2.png',
		style = 4,
		recastCostSeq = 2,
		linkageNum = 1,
		linkageLib = 3,
		decomposeReturn = __data_t__decomposeReturn[100042]
		-- {[135] = 10, __size = 1}
	},
	[100043] = {
		id = 100043,
		name = '混方·紫',
		strengthSeq = 3,
		maxLevel = 40,
		baseAttr = 23,
		quality = 4,
		icon = 'config/item/emera/icon_lsc_3.png',
		style = 4,
		recastCostSeq = 3,
		linkageNum = 1,
		linkageLib = 4,
		decomposeReturn = __data_t__decomposeReturn[100043]
		-- {[135] = 20, __size = 1}
	},
	[100044] = {
		id = 100044,
		name = '混方·橙',
		strengthSeq = 4,
		maxLevel = 40,
		baseAttr = 33,
		quality = 5,
		icon = 'config/item/emera/icon_lsc_4.png',
		style = 4,
		recastCostSeq = 4,
		linkageNum = 2,
		linkageLib = 5,
		effect = __data_t__effect[100044],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100044]
		-- {[136] = 1, [135] = 60, __size = 2}
	},
	[100045] = {
		id = 100045,
		name = '混方·红',
		strengthSeq = 5,
		baseAttr = 43,
		quality = 6,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsc_5.png',
		style = 4,
		recastCostSeq = 5,
		linkageNum = 3,
		linkageLib = 6,
		effect = __data_t__effect[100045],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100045]
		-- {[136] = 2, [135] = 300, __size = 2}
	},
	[100046] = {
		id = 100046,
		name = '混方·钻彩',
		strengthSeq = 6,
		baseAttr = 53,
		quality = 7,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsc_6.png',
		style = 4,
		recastCostSeq = 6,
		linkageNum = 3,
		linkageLib = 7,
		effect = __data_t__effect[100046],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100046]
		-- {[136] = 3, [135] = 1000, __size = 2}
	},
	[100061] = {
		id = 100061,
		name = '涡晶·绿',
		strengthSeq = 1,
		maxLevel = 30,
		baseAttr = 4,
		quality = 2,
		icon = 'config/item/emera/icon_lsa_1.png',
		style = 5,
		recastCostSeq = 1,
		decomposeReturn = __data_t__decomposeReturn[100061]
		-- {[135] = 5, __size = 1}
	},
	[100062] = {
		id = 100062,
		name = '涡晶·蓝',
		strengthSeq = 2,
		maxLevel = 30,
		baseAttr = 14,
		quality = 3,
		icon = 'config/item/emera/icon_lsa_2.png',
		style = 5,
		recastCostSeq = 2,
		linkageNum = 1,
		linkageLib = 3,
		decomposeReturn = __data_t__decomposeReturn[100062]
		-- {[135] = 10, __size = 1}
	},
	[100063] = {
		id = 100063,
		name = '涡晶·紫',
		strengthSeq = 3,
		maxLevel = 40,
		baseAttr = 24,
		quality = 4,
		icon = 'config/item/emera/icon_lsa_3.png',
		style = 5,
		recastCostSeq = 3,
		linkageNum = 1,
		linkageLib = 4,
		decomposeReturn = __data_t__decomposeReturn[100063]
		-- {[135] = 20, __size = 1}
	},
	[100064] = {
		id = 100064,
		name = '涡晶·橙',
		strengthSeq = 4,
		maxLevel = 40,
		baseAttr = 34,
		quality = 5,
		icon = 'config/item/emera/icon_lsa_4.png',
		style = 5,
		recastCostSeq = 4,
		linkageNum = 2,
		linkageLib = 5,
		effect = __data_t__effect[100064],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100064]
		-- {[136] = 1, [135] = 60, __size = 2}
	},
	[100065] = {
		id = 100065,
		name = '涡晶·红',
		strengthSeq = 5,
		baseAttr = 44,
		quality = 6,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsa_5.png',
		style = 5,
		recastCostSeq = 5,
		linkageNum = 3,
		linkageLib = 6,
		effect = __data_t__effect[100065],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100065]
		-- {[136] = 2, [135] = 300, __size = 2}
	},
	[100066] = {
		id = 100066,
		name = '涡晶·钻彩',
		strengthSeq = 6,
		baseAttr = 54,
		quality = 7,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsa_6.png',
		style = 5,
		recastCostSeq = 6,
		linkageNum = 3,
		linkageLib = 7,
		effect = __data_t__effect[100066],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100066]
		-- {[136] = 3, [135] = 1000, __size = 2}
	},
	[100081] = {
		id = 100081,
		name = '耀星·绿',
		type = 2,
		strengthSeq = 1,
		maxLevel = 30,
		baseAttr = 5,
		quality = 2,
		icon = 'config/item/emera/icon_lsf_1.png',
		recastCostSeq = 1,
		coreType = 1,
		decomposeReturn = __data_t__decomposeReturn[100081]
		-- {[135] = 5, __size = 1}
	},
	[100082] = {
		id = 100082,
		name = '耀星·蓝',
		type = 2,
		strengthSeq = 2,
		maxLevel = 30,
		baseAttr = 15,
		quality = 3,
		icon = 'config/item/emera/icon_lsf_2.png',
		recastCostSeq = 2,
		coreType = 1,
		linkageNum = 1,
		linkageLib = 3,
		decomposeReturn = __data_t__decomposeReturn[100082]
		-- {[135] = 10, __size = 1}
	},
	[100083] = {
		id = 100083,
		name = '耀星·紫',
		type = 2,
		strengthSeq = 3,
		maxLevel = 40,
		baseAttr = 25,
		quality = 4,
		icon = 'config/item/emera/icon_lsf_3.png',
		recastCostSeq = 3,
		coreType = 1,
		linkageNum = 1,
		linkageLib = 4,
		decomposeReturn = __data_t__decomposeReturn[100083]
		-- {[135] = 20, __size = 1}
	},
	[100084] = {
		id = 100084,
		name = '耀星·橙',
		type = 2,
		strengthSeq = 4,
		maxLevel = 40,
		baseAttr = 35,
		quality = 5,
		icon = 'config/item/emera/icon_lsf_4.png',
		recastCostSeq = 4,
		coreType = 1,
		linkageNum = 2,
		linkageLib = 5,
		effect = __data_t__effect[100084],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100084]
		-- {[136] = 1, [135] = 60, __size = 2}
	},
	[100085] = {
		id = 100085,
		name = '耀星·红',
		type = 2,
		strengthSeq = 5,
		baseAttr = 45,
		quality = 6,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsf_5.png',
		recastCostSeq = 5,
		coreType = 1,
		linkageNum = 3,
		linkageLib = 6,
		effect = __data_t__effect[100085],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100085]
		-- {[136] = 2, [135] = 300, __size = 2}
	},
	[100086] = {
		id = 100086,
		name = '耀星·钻彩',
		type = 2,
		strengthSeq = 6,
		baseAttr = 55,
		quality = 7,
		canDecompose = false,
		icon = 'config/item/emera/icon_lsf_6.png',
		recastCostSeq = 6,
		coreType = 1,
		linkageNum = 3,
		linkageLib = 7,
		effect = __data_t__effect[100086],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100086]
		-- {[136] = 3, [135] = 1000, __size = 2}
	},
	[100101] = {
		id = 100101,
		name = '菱晶·绿',
		type = 2,
		strengthSeq = 1,
		maxLevel = 30,
		baseAttr = 6,
		quality = 2,
		icon = 'config/item/emera/icon_lse_1.png',
		recastCostSeq = 1,
		coreType = 2,
		decomposeReturn = __data_t__decomposeReturn[100101]
		-- {[135] = 5, __size = 1}
	},
	[100102] = {
		id = 100102,
		name = '菱晶·蓝',
		type = 2,
		strengthSeq = 2,
		maxLevel = 30,
		baseAttr = 16,
		quality = 3,
		icon = 'config/item/emera/icon_lse_2.png',
		recastCostSeq = 2,
		coreType = 2,
		linkageNum = 1,
		linkageLib = 3,
		decomposeReturn = __data_t__decomposeReturn[100102]
		-- {[135] = 10, __size = 1}
	},
	[100103] = {
		id = 100103,
		name = '菱晶·紫',
		type = 2,
		strengthSeq = 3,
		maxLevel = 40,
		baseAttr = 26,
		quality = 4,
		icon = 'config/item/emera/icon_lse_3.png',
		recastCostSeq = 3,
		coreType = 2,
		linkageNum = 1,
		linkageLib = 4,
		decomposeReturn = __data_t__decomposeReturn[100103]
		-- {[135] = 20, __size = 1}
	},
	[100104] = {
		id = 100104,
		name = '菱晶·橙',
		type = 2,
		strengthSeq = 4,
		maxLevel = 40,
		baseAttr = 36,
		quality = 5,
		icon = 'config/item/emera/icon_lse_4.png',
		recastCostSeq = 4,
		coreType = 2,
		linkageNum = 2,
		linkageLib = 5,
		effect = __data_t__effect[100104],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100104]
		-- {[136] = 1, [135] = 60, __size = 2}
	},
	[100105] = {
		id = 100105,
		name = '菱晶·红',
		type = 2,
		strengthSeq = 5,
		baseAttr = 46,
		quality = 6,
		canDecompose = false,
		icon = 'config/item/emera/icon_lse_5.png',
		recastCostSeq = 5,
		coreType = 2,
		linkageNum = 3,
		linkageLib = 6,
		effect = __data_t__effect[100105],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100105]
		-- {[136] = 2, [135] = 300, __size = 2}
	},
	[100106] = {
		id = 100106,
		name = '菱晶·钻彩',
		type = 2,
		strengthSeq = 6,
		baseAttr = 56,
		quality = 7,
		canDecompose = false,
		icon = 'config/item/emera/icon_lse_6.png',
		recastCostSeq = 6,
		coreType = 2,
		linkageNum = 3,
		linkageLib = 7,
		effect = __data_t__effect[100106],
		-- {['drawcard'] = 'huang_effect_loop', ['gain'] = 'huang_effect_loop', __size = 2}
		decomposeReturn = __data_t__decomposeReturn[100106]
		-- {[136] = 3, [135] = 1000, __size = 2}
	},
	__size = 36,
	__default = {
		__index = {
			name = '',
			type = 1,
			strengthSeq = 0,
			maxLevel = 50,
			baseAttr = 0,
			quality = 0,
			canDecompose = true,
			icon = '',
			style = 1,
			recastCostSeq = 0,
			coreType = 0,
			linkageNum = 0,
			linkageLib = 0,
			effect = {['drawcard'] = false, ['gain'] = false, __size = 2},
			decomposeReturn = {__size = 0}
		}
	}
}
return csv.emera.emera