--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['union']['union_skill'] = {
	[1] = {
		id = 1,
		name = '生命源泉',
		icon = 'common/icon/union_skill/icon_sm.png'
	},
	[2] = {
		id = 2,
		name = '物攻学习',
		icon = 'common/icon/union_skill/icon_bs.png',
		sort = 2,
		attrType = 7
	},
	[3] = {
		id = 3,
		name = '特攻学习',
		icon = 'common/icon/union_skill/icon_bj.png',
		sort = 3,
		attrType = 8
	},
	[4] = {
		id = 4,
		name = '物防增强',
		icon = 'common/icon/union_skill/icon_wf.png',
		sort = 4,
		attrType = 9
	},
	[5] = {
		id = 5,
		name = '特防增强',
		icon = 'common/icon/union_skill/icon_tf.png',
		sort = 5,
		attrType = 10
	},
	[6] = {
		id = 6,
		name = '体能训练',
		icon = 'common/icon/union_skill/icon_sm.png',
		sort = 6,
		preSkill = {1, 10},
		needGuildLv = 6
	},
	[7] = {
		id = 7,
		name = '力量锤炼',
		icon = 'common/icon/union_skill/icon_bs.png',
		sort = 7,
		preSkill = {2, 10},
		needGuildLv = 6,
		attrType = 7
	},
	[8] = {
		id = 8,
		name = '意志磨练',
		icon = 'common/icon/union_skill/icon_bj.png',
		sort = 8,
		preSkill = {3, 10},
		needGuildLv = 6,
		attrType = 8
	},
	[9] = {
		id = 9,
		name = '健身强体',
		icon = 'common/icon/union_skill/icon_wf.png',
		sort = 9,
		preSkill = {4, 10},
		needGuildLv = 6,
		attrType = 9
	},
	[10] = {
		id = 10,
		name = '精神修炼',
		icon = 'common/icon/union_skill/icon_tf.png',
		sort = 10,
		preSkill = {5, 10},
		needGuildLv = 6,
		attrType = 10
	},
	[11] = {
		id = 11,
		name = '抵御训练',
		icon = 'common/icon/union_skill/icon_tg.png',
		sort = 11,
		needGuildLv = 8,
		attrType = 17
	},
	[12] = {
		id = 12,
		name = '强化抵御',
		icon = 'common/icon/union_skill/icon_tg.png',
		sort = 12,
		needGuildLv = 8,
		attrType = 19
	},
	[13] = {
		id = 13,
		name = '精进治疗效果',
		icon = 'common/icon/union_skill/icon_sm.png',
		sort = 14,
		needGuildLv = 8,
		attrType = 28
	},
	[14] = {
		id = 14,
		name = '暴击增强',
		icon = 'common/icon/union_skill/icon_wg.png',
		sort = 15,
		needGuildLv = 8,
		attrType = 14
	},
	[15] = {
		id = 15,
		name = '强化暴击伤害',
		icon = 'common/icon/union_skill/icon_wg.png',
		sort = 16,
		needGuildLv = 8,
		attrType = 15
	},
	[16] = {
		id = 16,
		name = '强化暴击抗性',
		icon = 'common/icon/union_skill/icon_tf.png',
		sort = 17,
		needGuildLv = 8,
		attrType = 16
	},
	[17] = {
		id = 17,
		name = '破除抵御',
		icon = 'common/icon/union_skill/icon_bs.png',
		sort = 13,
		needGuildLv = 8,
		attrType = 18
	},
	[18] = {
		id = 18,
		name = '竞技伤害加成',
		icon = 'common/icon/union_skill/icon_wg.png',
		sort = 18,
		needGuildLv = 10,
		attrType = 92
	},
	[19] = {
		id = 19,
		name = '竞技伤害减免',
		icon = 'common/icon/union_skill/icon_wf.png',
		sort = 19,
		needGuildLv = 10,
		attrType = 93
	},
	__size = 19,
	__default = {
		__index = {
			name = '',
			icon = 'config/item/icon_bsdmz.png',
			sort = 1,
			preSkill = {},
			needGuildLv = 0,
			attrNatureType = 0,
			attrType = 1
		}
	}
}
return csv.union.union_skill