--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['pokedex_advance'] = {
	[1] = {
		id = 1,
		name = '收集5全体精灵',
		desc = '#C0xFF5B545B#全体精灵生命提升 #C0xFF60C456#350',
		targetArg = 5,
		attrType = 1,
		attrValue = 350
	},
	[2] = {
		id = 2,
		name = '收集10全体精灵',
		desc = '#C0xFF5B545B#全体精灵物防提升 #C0xFF60C456#120',
		targetArg = 10,
		attrType = 9,
		attrValue = 120
	},
	[3] = {
		id = 3,
		name = '收集20全体精灵',
		desc = '#C0xFF5B545B#全体精灵特防提升 #C0xFF60C456#150',
		targetArg = 20,
		attrType = 10,
		attrValue = 150
	},
	[4] = {
		id = 4,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵暴击抗性提升#C0xFF60C456#3%',
		targetArg = 30,
		attrType = 16,
		attrValue = 300
	},
	[5] = {
		id = 5,
		name = '收集50全体精灵',
		desc = '#C0xFF5B545B#全体精灵物防提升#C0xFF60C456#3%',
		targetArg = 50,
		attrType = 9,
		attrValue = 300
	},
	[6] = {
		id = 6,
		name = '收集70全体精灵',
		desc = '#C0xFF5B545B#全体精灵特防提升#C0xFF60C456#3%',
		targetArg = 70,
		attrType = 10,
		attrValue = 300
	},
	[7] = {
		id = 7,
		name = '收集100全体精灵',
		desc = '#C0xFF5B545B#全体精灵暴击抗性提升#C0xFF60C456#3%',
		targetArg = 100,
		attrType = 16,
		attrValue = 300
	},
	[8] = {
		id = 8,
		name = '收集150全体精灵',
		desc = '#C0xFF5B545B#全体精灵物伤减免提升#C0xFF60C456#3%',
		targetArg = 150,
		attrType = 33,
		attrValue = 300
	},
	[9] = {
		id = 9,
		name = '收集200全体精灵',
		desc = '#C0xFF5B545B#全体精灵特伤减免提升#C0xFF60C456#3%',
		targetArg = 200,
		attrType = 35,
		attrValue = 300
	},
	[10] = {
		id = 10,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵一般系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 1,
		attrType = 36,
		attrValue = 100
	},
	[11] = {
		id = 11,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵一般系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 1,
		attrType = 36,
		attrValue = 100
	},
	[12] = {
		id = 12,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵一般系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 1,
		attrType = 36,
		attrValue = 100
	},
	[13] = {
		id = 13,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵一般系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 1,
		attrType = 36,
		attrValue = 100
	},
	[14] = {
		id = 14,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[15] = {
		id = 15,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[16] = {
		id = 16,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[17] = {
		id = 17,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[18] = {
		id = 18,
		name = '收集5全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 5,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[19] = {
		id = 19,
		name = '收集10全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 10,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[20] = {
		id = 20,
		name = '收集20全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 20,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[21] = {
		id = 21,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[22] = {
		id = 22,
		name = '收集33全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 33,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[23] = {
		id = 23,
		name = '收集36全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 36,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[24] = {
		id = 24,
		name = '收集5全体精灵',
		desc = '#C0xFF5B545B#全体精灵草系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 5,
		targetArg2 = 4,
		attrType = 39,
		attrValue = 100
	},
	[25] = {
		id = 25,
		name = '收集10全体精灵',
		desc = '#C0xFF5B545B#全体精灵草系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 10,
		targetArg2 = 4,
		attrType = 39,
		attrValue = 100
	},
	[26] = {
		id = 26,
		name = '收集20全体精灵',
		desc = '#C0xFF5B545B#全体精灵草系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 20,
		targetArg2 = 4,
		attrType = 39,
		attrValue = 100
	},
	[27] = {
		id = 27,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵电系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 5,
		attrType = 40,
		attrValue = 100
	},
	[28] = {
		id = 28,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵电系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 5,
		attrType = 40,
		attrValue = 100
	},
	[29] = {
		id = 29,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵电系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 5,
		attrType = 40,
		attrValue = 100
	},
	[30] = {
		id = 30,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[31] = {
		id = 31,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[32] = {
		id = 32,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[33] = {
		id = 33,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[34] = {
		id = 34,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[35] = {
		id = 35,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[36] = {
		id = 36,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[37] = {
		id = 37,
		name = '收集5全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 5,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[38] = {
		id = 38,
		name = '收集10全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 10,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[39] = {
		id = 39,
		name = '收集15全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 15,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[40] = {
		id = 40,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[41] = {
		id = 41,
		name = '收集5全体精灵',
		desc = '#C0xFF5B545B#全体精灵地面系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 5,
		targetArg2 = 9,
		attrType = 44,
		attrValue = 100
	},
	[42] = {
		id = 42,
		name = '收集10全体精灵',
		desc = '#C0xFF5B545B#全体精灵地面系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 10,
		targetArg2 = 9,
		attrType = 44,
		attrValue = 100
	},
	[43] = {
		id = 43,
		name = '收集15全体精灵',
		desc = '#C0xFF5B545B#全体精灵地面系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 15,
		targetArg2 = 9,
		attrType = 44,
		attrValue = 100
	},
	[44] = {
		id = 44,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵地面系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 9,
		attrType = 44,
		attrValue = 100
	},
	[45] = {
		id = 45,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵飞行系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 10,
		attrType = 45,
		attrValue = 100
	},
	[46] = {
		id = 46,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵飞行系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 10,
		attrType = 45,
		attrValue = 100
	},
	[47] = {
		id = 47,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵飞行系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 10,
		attrType = 45,
		attrValue = 100
	},
	[48] = {
		id = 48,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵飞行系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 10,
		attrType = 45,
		attrValue = 100
	},
	[49] = {
		id = 49,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵超能系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 11,
		attrType = 46,
		attrValue = 100
	},
	[50] = {
		id = 50,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵超能系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 11,
		attrType = 46,
		attrValue = 100
	},
	[51] = {
		id = 51,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵超能系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 11,
		attrType = 46,
		attrValue = 100
	},
	[52] = {
		id = 52,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵虫系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 12,
		attrType = 47,
		attrValue = 100
	},
	[53] = {
		id = 53,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵虫系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 12,
		attrType = 47,
		attrValue = 100
	},
	[54] = {
		id = 54,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵虫系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 12,
		attrType = 47,
		attrValue = 100
	},
	[55] = {
		id = 55,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵岩石系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 13,
		attrType = 48,
		attrValue = 100
	},
	[56] = {
		id = 56,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵岩石系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 13,
		attrType = 48,
		attrValue = 100
	},
	[57] = {
		id = 57,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵岩石系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 13,
		attrType = 48,
		attrValue = 100
	},
	[58] = {
		id = 58,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵岩石系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 13,
		attrType = 48,
		attrValue = 100
	},
	[59] = {
		id = 59,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[60] = {
		id = 60,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[61] = {
		id = 61,
		name = '收集9全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 9,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[62] = {
		id = 62,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[63] = {
		id = 63,
		name = '收集15全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 15,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[64] = {
		id = 64,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[65] = {
		id = 65,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[66] = {
		id = 66,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[67] = {
		id = 67,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[68] = {
		id = 68,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[69] = {
		id = 69,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[70] = {
		id = 70,
		name = '收集9全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 9,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[71] = {
		id = 71,
		name = '收集15全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 15,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[72] = {
		id = 72,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[73] = {
		id = 73,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[74] = {
		id = 74,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[75] = {
		id = 75,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[76] = {
		id = 76,
		name = '收集3全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 3,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	[77] = {
		id = 77,
		name = '收集6全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 6,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	[78] = {
		id = 78,
		name = '收集9全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 9,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	[79] = {
		id = 79,
		name = '收集12全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 12,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	[101] = {
		id = 101,
		name = '收集250全体精灵',
		desc = '#C0xFF5B545B#全体精灵物防提升 #C0xFF60C456#3%',
		targetArg = 250,
		attrType = 9,
		attrValue = 300
	},
	[102] = {
		id = 102,
		name = '收集300全体精灵',
		desc = '#C0xFF5B545B#全体精灵特防提升 #C0xFF60C456#3%',
		targetArg = 300,
		attrType = 10,
		attrValue = 300
	},
	[103] = {
		id = 103,
		name = '收集350全体精灵',
		desc = '#C0xFF5B545B#全体精灵暴击抗性提升#C0xFF60C456#3%',
		targetArg = 350,
		attrType = 16,
		attrValue = 300
	},
	[104] = {
		id = 104,
		name = '收集400全体精灵',
		desc = '#C0xFF5B545B#全体精灵物防提升#C0xFF60C456#3%',
		targetArg = 400,
		attrType = 9,
		attrValue = 300
	},
	[111] = {
		id = 111,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵一般系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 1,
		attrType = 36,
		attrValue = 100
	},
	[112] = {
		id = 112,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵一般系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 1,
		attrType = 36,
		attrValue = 100
	},
	[115] = {
		id = 115,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[116] = {
		id = 116,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[117] = {
		id = 117,
		name = '收集60全体精灵',
		desc = '#C0xFF5B545B#全体精灵火系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 60,
		targetArg2 = 2,
		attrType = 37,
		attrValue = 100
	},
	[119] = {
		id = 119,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[120] = {
		id = 120,
		name = '收集60全体精灵',
		desc = '#C0xFF5B545B#全体精灵水系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 60,
		targetArg2 = 3,
		attrType = 38,
		attrValue = 100
	},
	[121] = {
		id = 121,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵草系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 4,
		attrType = 39,
		attrValue = 100
	},
	[122] = {
		id = 122,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵草系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 4,
		attrType = 39,
		attrValue = 100
	},
	[126] = {
		id = 126,
		name = '收集20全体精灵',
		desc = '#C0xFF5B545B#全体精灵电系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 20,
		targetArg2 = 5,
		attrType = 40,
		attrValue = 100
	},
	[127] = {
		id = 127,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵电系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 5,
		attrType = 40,
		attrValue = 100
	},
	[128] = {
		id = 128,
		name = '收集35全体精灵',
		desc = '#C0xFF5B545B#全体精灵电系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 35,
		targetArg2 = 5,
		attrType = 40,
		attrValue = 100
	},
	[131] = {
		id = 131,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[132] = {
		id = 132,
		name = '收集24全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 24,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[133] = {
		id = 133,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[134] = {
		id = 134,
		name = '收集35全体精灵',
		desc = '#C0xFF5B545B#全体精灵冰系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 35,
		targetArg2 = 6,
		attrType = 41,
		attrValue = 100
	},
	[136] = {
		id = 136,
		name = '收集24全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 24,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[137] = {
		id = 137,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[138] = {
		id = 138,
		name = '收集35全体精灵',
		desc = '#C0xFF5B545B#全体精灵格斗系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 35,
		targetArg2 = 7,
		attrType = 42,
		attrValue = 100
	},
	[140] = {
		id = 140,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[141] = {
		id = 141,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[142] = {
		id = 142,
		name = '收集50全体精灵',
		desc = '#C0xFF5B545B#全体精灵毒系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 50,
		targetArg2 = 8,
		attrType = 43,
		attrValue = 100
	},
	[144] = {
		id = 144,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵地面系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 9,
		attrType = 44,
		attrValue = 100
	},
	[145] = {
		id = 145,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵地面系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 9,
		attrType = 44,
		attrValue = 100
	},
	[148] = {
		id = 148,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵飞行系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 10,
		attrType = 45,
		attrValue = 100
	},
	[149] = {
		id = 149,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵飞行系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 10,
		attrType = 45,
		attrValue = 100
	},
	[152] = {
		id = 152,
		name = '收集27全体精灵',
		desc = '#C0xFF5B545B#全体精灵超能系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 27,
		targetArg2 = 11,
		attrType = 46,
		attrValue = 100
	},
	[153] = {
		id = 153,
		name = '收集40全体精灵',
		desc = '#C0xFF5B545B#全体精灵超能系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 40,
		targetArg2 = 11,
		attrType = 46,
		attrValue = 100
	},
	[157] = {
		id = 157,
		name = '收集16全体精灵',
		desc = '#C0xFF5B545B#全体精灵虫系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 16,
		targetArg2 = 12,
		attrType = 47,
		attrValue = 100
	},
	[158] = {
		id = 158,
		name = '收集20全体精灵',
		desc = '#C0xFF5B545B#全体精灵虫系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 20,
		targetArg2 = 12,
		attrType = 47,
		attrValue = 100
	},
	[159] = {
		id = 159,
		name = '收集24全体精灵',
		desc = '#C0xFF5B545B#全体精灵虫系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 24,
		targetArg2 = 12,
		attrType = 47,
		attrValue = 100
	},
	[162] = {
		id = 162,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵岩石系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 13,
		attrType = 48,
		attrValue = 100
	},
	[163] = {
		id = 163,
		name = '收集35全体精灵',
		desc = '#C0xFF5B545B#全体精灵岩石系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 35,
		targetArg2 = 13,
		attrType = 48,
		attrValue = 100
	},
	[166] = {
		id = 166,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[167] = {
		id = 167,
		name = '收集35全体精灵',
		desc = '#C0xFF5B545B#全体精灵幽灵系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 35,
		targetArg2 = 14,
		attrType = 49,
		attrValue = 100
	},
	[169] = {
		id = 169,
		name = '收集24全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 24,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[170] = {
		id = 170,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[171] = {
		id = 171,
		name = '收集36全体精灵',
		desc = '#C0xFF5B545B#全体精灵龙系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 36,
		targetArg2 = 15,
		attrType = 50,
		attrValue = 100
	},
	[173] = {
		id = 173,
		name = '收集20全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 20,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[174] = {
		id = 174,
		name = '收集25全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 25,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[175] = {
		id = 175,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵恶系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 16,
		attrType = 51,
		attrValue = 100
	},
	[177] = {
		id = 177,
		name = '收集24全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 24,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[178] = {
		id = 178,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[179] = {
		id = 179,
		name = '收集36全体精灵',
		desc = '#C0xFF5B545B#全体精灵钢系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 36,
		targetArg2 = 17,
		attrType = 52,
		attrValue = 100
	},
	[181] = {
		id = 181,
		name = '收集18全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 18,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	[182] = {
		id = 182,
		name = '收集24全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 24,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	[183] = {
		id = 183,
		name = '收集30全体精灵',
		desc = '#C0xFF5B545B#全体精灵妖精系伤害加成提升#C0xFF60C456#1%',
		targetType = 2,
		targetArg = 30,
		targetArg2 = 18,
		attrType = 53,
		attrValue = 100
	},
	__size = 130,
	__default = {
		__index = {
			name = '',
			desc = '',
			targetType = 1,
			attrNatureType = 0,
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr'}
		}
	}
}
return csv.pokedex_advance