--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, __size = 1}
local __data_t__attrs = {
	["default"] = __predefine_t__[1]
}
local __data_t__cards = {
	["default"] = __predefine_t__[1]
}

csv['draw_card_up_group'] = {
	[1] = {
		id = 1,
		name = '火',
		attrs = {2},
		cards = {601, 1171, 1231, 741, 241, 3151, 2991}
	},
	[2] = {
		id = 2,
		name = '水地',
		attrs = {3, 9},
		cards = {631, 1241, 1311, 2721, 491, 2031}
	},
	[3] = {
		id = 3,
		name = '电',
		attrs = {5},
		cards = {331, 591, 731, 881, 1221}
	},
	[4] = {
		id = 4,
		name = '冰妖精',
		attrs = {6, 18},
		cards = {721, 3021, 1081, 1391, 3351, 1921}
	},
	[5] = {
		id = 5,
		name = '钢岩',
		attrs = {13, 17},
		cards = {401, 1251, 1501, 1911, 1931, 3411, 491, 2031}
	},
	[6] = {
		id = 6,
		name = '恶毒',
		attrs = {16, 8},
		cards = {1081, 1171, 1841, 2721, 3141, 161}
	},
	[7] = {
		id = 7,
		name = '草虫普',
		attrs = {4, 12, 1},
		cards = {1071, 1421, 571, 1291, 3151, 3661, 2471}
	},
	[8] = {
		id = 8,
		name = '超龙幽',
		attrs = {11, 15, 14},
		cards = {261, 391, 1811, 3541, 3001, 3591, 1391, 2991}
	},
	__size = 8,
	__default = {
		__index = {
			name = '',
			attrs = __data_t__attrs["default"]	--[[ {}]],
			cards = __data_t__cards["default"]	--[[ {}]],
			priviewId = 62
		}
	}
}
return csv.draw_card_up_group