slot0 = {
	{
		__size = 2,
		x = 0,
		y = 0
	},
	__size = 1
}
csv.yunying.draw_limit = {
	{
		titleRes1 = "common/txt/txt_gld.png",
		card1 = 1971,
		id = 1,
		res1 = "config/big_hero/normal/img_383_gld@.png",
		posRes1 = "common/txt/txt_dw_gld.png",
		resScale1 = 2.618
	},
	{
		posRes1 = "common/txt/txt_dw_gld.png",
		card1 = 1971,
		id = 2,
		card2 = 1961,
		posRes2 = "common/txt/txt_dw_gok.png",
		resScale2 = 2,
		titleRes2 = "common/txt/txt_gok.png",
		resScale1 = 2.618,
		titleRes1 = "common/txt/txt_gld.png",
		res1 = "config/big_hero/normal/img_383_gld@.png"
	},
	{
		titleRes1 = "common/txt/txt_gld.png",
		card1 = 1971,
		id = 3,
		res1 = "config/big_hero/normal/img_383_gld@.png",
		posRes1 = "common/txt/txt_dw_gld.png"
	},
	{
		card2 = 3601,
		card1 = 1261,
		id = 4,
		resScale2 = 2.11,
		posRes2 = "common/txt/txt_dw_xerneas.png",
		posRes1 = "common/txt/txt_dw_lqy.png",
		titleRes2 = "common/txt/txt_xerneas.png",
		resScale1 = 2.618,
		titleRes1 = "common/txt/txt_lqy.png",
		res1 = "config/big_hero/normal/img_249_lqy@.png",
		res2 = "config/big_hero/normal/img_716_zenys@.png"
	},
	{
		titleRes1 = "common/txt/txt_dax.png",
		card1 = 3631,
		id = 5,
		res1 = "config/big_hero/standby/img_719_dax@.png",
		posRes1 = "common/txt/txt_dw_dax.png",
		resScale1 = 2.33
	},
	{
		titleRes1 = "common/txt/txt_gld.png",
		card1 = 1971,
		id = 6,
		res1 = "config/big_hero/normal/img_383_gld@.png",
		posRes1 = "common/txt/txt_dw_gld.png",
		resScale1 = 2.618
	},
	{
		titleRes1 = "common/txt/txt_lkz.png",
		card1 = 1981,
		id = 7,
		res1 = "config/big_hero/normal/img_384_lkz@.png",
		posRes1 = "common/txt/txt_dw_lkz.png",
		resScale1 = 2.618
	},
	{
		titleRes1 = "common/txt/txt_lqy.png",
		card1 = 1261,
		id = 8,
		res1 = "config/big_hero/normal/img_249_lqy@.png",
		posRes1 = "common/txt/txt_dw_lqy.png",
		resScale1 = 2.618
	},
	{
		card2 = 3631,
		card1 = 2431,
		id = 9,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dax.png",
		posRes1 = "common/txt/txt_dw_dkly.png",
		titleRes2 = "common/txt/txt_dax.png",
		resScale1 = 1.6,
		titleRes1 = "common/txt/txt_dkly.png",
		res1 = "config/big_hero/normal/img_491_dkly@.png",
		res2 = "config/big_hero/standby/img_719_dax@.png"
	},
	{
		card2 = 1261,
		card1 = 2381,
		id = 10,
		resScale2 = 2.14,
		posRes2 = "common/txt/txt_dw_lqy.png",
		posRes1 = "common/txt/txt_dw_ljqks.png",
		titleRes2 = "common/txt/txt_lqy.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_ljqks.png",
		res1 = "config/big_hero/normal/img_486_ljqks@.png",
		res2 = "config/big_hero/normal/img_249_lqy@.png"
	},
	{
		card2 = 2351,
		card1 = 1981,
		id = 11,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dylk.png",
		posRes1 = "common/txt/txt_dw_lkz.png",
		titleRes2 = "common/txt/txt_dylk.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_lkz.png",
		res1 = "config/big_hero/normal/img_384_lkz@.png",
		res2 = "config/big_hero/normal/img_483_dylk@.png"
	},
	{
		card2 = 2361,
		card1 = 1961,
		id = 12,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_gnskr.png",
		posRes1 = "common/txt/txt_dw_gok.png",
		titleRes2 = "common/txt/txt_gnskr.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_gok.png",
		res1 = "config/big_hero/normal/img_382_gok@.png",
		res2 = "config/big_hero/normal/img_484_plqy@.png"
	},
	{
		card2 = 3631,
		card1 = 1971,
		id = 13,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dax.png",
		posRes1 = "common/txt/txt_dw_gld.png",
		titleRes2 = "common/txt/txt_dax.png",
		resScale1 = 2.618,
		titleRes1 = "common/txt/txt_gld.png",
		res1 = "config/big_hero/normal/img_383_gld@.png",
		res2 = "config/big_hero/standby/img_719_dax@.png"
	},
	{
		card2 = 3271,
		card1 = 2391,
		id = 14,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_gnskr.png",
		posRes1 = "common/txt/txt_dw_qldn.png",
		titleRes2 = "common/txt/txt_gnskr.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_qldn.png",
		res1 = "config/big_hero/normal/img_487_qldnsxt@.png",
		res2 = "config/big_hero/normal/img_649_gnskt@.png"
	},
	{
		card2 = 2381,
		card1 = 2441,
		id = 15,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_ljqks.png",
		posRes1 = "common/txt/txt_dw_xm.png",
		titleRes2 = "common/txt/txt_ljqks.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_xm.png",
		res1 = "config/big_hero/normal/img_492_xm@.png",
		res2 = "config/big_hero/normal/img_486_ljqks@.png"
	},
	{
		card2 = 1261,
		card1 = 1981,
		id = 16,
		resScale2 = 2.618,
		posRes2 = "common/txt/txt_dw_lqy.png",
		posRes1 = "common/txt/txt_dw_lkz.png",
		titleRes2 = "common/txt/txt_lqy.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_lkz.png",
		res1 = "config/big_hero/normal/img_384_lkz@.png",
		res2 = "config/big_hero/normal/img_249_lqy@.png"
	},
	{
		card2 = 2351,
		card1 = 3641,
		id = 17,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dylk.png",
		posRes1 = "common/txt/txt_dw_hp.png",
		titleRes2 = "common/txt/txt_dylk.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_cjhp.png",
		res1 = "config/big_hero/normal/img_720_cjhp@.png",
		res2 = "config/big_hero/normal/img_483_dylk@.png"
	},
	{
		card2 = 2361,
		card1 = 3211,
		id = 18,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_plqy.png",
		posRes1 = "common/txt/txt_dw_lxlm.png",
		titleRes2 = "common/txt/txt_plqy.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_lxlm.png",
		res1 = "config/big_hero/normal/img_643_lxlm@.png",
		res2 = "config/big_hero/normal/img_484_plqy@.png"
	},
	{
		card2 = 2431,
		card1 = 1981,
		id = 19,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_dkly.png",
		posRes1 = "common/txt/txt_dw_lkz.png",
		titleRes2 = "common/txt/txt_dkly.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_lkz.png",
		res1 = "config/big_hero/normal/img_384_lkz@.png",
		res2 = "config/big_hero/normal/img_491_dkly@.png"
	},
	{
		card2 = 2391,
		card1 = 3221,
		id = 20,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_qldn.png",
		posRes1 = "common/txt/txt_dw_jklm.png",
		titleRes2 = "common/txt/txt_qldn.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_jklm.png",
		res1 = "config/big_hero/normal/img_644_jklm@.png",
		res2 = "config/big_hero/normal/img_487_qldnsxt@.png"
	},
	{
		card2 = 1971,
		card1 = 2431,
		id = 21,
		resScale2 = 2.618,
		posRes2 = "common/txt/txt_dw_gld.png",
		posRes1 = "common/txt/txt_dw_dkly.png",
		titleRes2 = "common/txt/txt_gld.png",
		resScale1 = 1.6,
		titleRes1 = "common/txt/txt_dkly.png",
		res1 = "config/big_hero/normal/img_491_dkly@.png",
		res2 = "config/big_hero/normal/img_383_gld@.png"
	},
	{
		card2 = 2381,
		card1 = 1961,
		id = 22,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_ljqks.png",
		posRes1 = "common/txt/txt_dw_gok.png",
		titleRes2 = "common/txt/txt_ljqks.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_gok.png",
		res1 = "config/big_hero/normal/img_382_gok@.png",
		res2 = "config/big_hero/normal/img_486_ljqks@.png"
	},
	{
		card2 = 2441,
		card1 = 3241,
		id = 23,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_xm.png",
		posRes1 = "common/txt/txt_dw_qlm.png",
		titleRes2 = "common/txt/txt_xm.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_qlm.png",
		res1 = "config/big_hero/normal/img_646_qlm@.png",
		res2 = "config/big_hero/normal/img_492_xm@.png"
	},
	{
		card2 = 3631,
		card1 = 2381,
		id = 24,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dax.png",
		posRes1 = "common/txt/txt_dw_ljqks.png",
		titleRes2 = "common/txt/txt_dax.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_ljqks.png",
		res1 = "config/big_hero/normal/img_486_ljqks@.png",
		res2 = "config/big_hero/standby/img_719_dax@.png"
	},
	{
		card2 = 1261,
		card1 = 1961,
		id = 25,
		resScale2 = 2.618,
		posRes2 = "common/txt/txt_dw_lqy.png",
		posRes1 = "common/txt/txt_dw_gok.png",
		titleRes2 = "common/txt/txt_lqy.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_gok.png",
		res1 = "config/big_hero/normal/img_382_gok@.png",
		res2 = "config/big_hero/normal/img_249_lqy@.png"
	},
	{
		card2 = 3641,
		card1 = 3261,
		id = 26,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_hp.png",
		posRes1 = "common/txt/txt_dw_mlyt.png",
		titleRes2 = "common/txt/txt_cjhp.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_mlyt.png",
		res1 = "config/big_hero/normal/img_648_mlyt@.png",
		res2 = "config/big_hero/normal/img_720_cjhp@.png"
	},
	{
		card2 = 3211,
		card1 = 1991,
		id = 27,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_lxlm.png",
		posRes1 = "common/txt/txt_dw_jlq.png",
		titleRes2 = "common/txt/txt_lxlm.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_jlq.png",
		res1 = "config/big_hero/normal/img_385_jlq@.png",
		res2 = "config/big_hero/normal/img_643_lxlm@.png"
	},
	{
		card2 = 1261,
		card1 = 3631,
		id = 28,
		resScale2 = 2.14,
		posRes2 = "common/txt/txt_dw_lqy.png",
		posRes1 = "common/txt/txt_dw_dax.png",
		titleRes2 = "common/txt/txt_lqy.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_dax.png",
		res1 = "config/big_hero/standby/img_719_dax@.png",
		res2 = "config/big_hero/normal/img_249_lqy@.png"
	},
	{
		card2 = 2431,
		card1 = 2361,
		id = 29,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_dkly.png",
		posRes1 = "common/txt/txt_dw_plqy.png",
		titleRes2 = "common/txt/txt_dkly.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_plqy.png",
		res1 = "config/big_hero/normal/img_484_plqy@.png",
		res2 = "config/big_hero/normal/img_491_dkly@.png"
	},
	{
		card2 = 3221,
		card1 = 4171,
		id = 30,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_jklm.png",
		posRes1 = "common/txt/txt_dw_mlmt.png",
		titleRes2 = "common/txt/txt_jklm.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_mlmt.png",
		res1 = "config/big_hero/normal/img_809_mlmt@.png",
		res2 = "config/big_hero/normal/img_644_jklm@.png"
	},
	{
		card2 = 1971,
		card1 = 1981,
		id = 31,
		resScale2 = 2.618,
		posRes2 = "common/txt/txt_dw_gld.png",
		posRes1 = "common/txt/txt_dw_lkz.png",
		titleRes2 = "common/txt/txt_gld.png",
		resScale1 = 2.33,
		titleRes1 = "common/txt/txt_lkz.png",
		res1 = "config/big_hero/normal/img_384_lkz@.png",
		res2 = "config/big_hero/normal/img_383_gld@.png"
	},
	{
		card2 = 2381,
		card1 = 2391,
		id = 32,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_ljqks.png",
		posRes1 = "common/txt/txt_dw_qldn.png",
		titleRes2 = "common/txt/txt_ljqks.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_qldn.png",
		res1 = "config/big_hero/normal/img_487_qldnsxt@.png",
		res2 = "config/big_hero/normal/img_486_ljqks@.png"
	},
	{
		card2 = 3241,
		card1 = 3611,
		id = 33,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_qlm.png",
		posRes1 = "common/txt/txt_dw_ypete.png",
		titleRes2 = "common/txt/txt_qlm.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_ypete.png",
		res1 = "config/big_hero/normal/img_717_ypete@.png",
		res2 = "config/big_hero/normal/img_646_qlm@.png"
	},
	{
		card2 = 3631,
		card1 = 1961,
		id = 34,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dax.png",
		posRes1 = "common/txt/txt_dw_gok.png",
		titleRes2 = "common/txt/txt_dax.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_gok.png",
		res1 = "config/big_hero/normal/img_382_gok@.png",
		res2 = "config/big_hero/standby/img_719_dax@.png"
	},
	{
		card2 = 2351,
		card1 = 2441,
		id = 35,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dylk.png",
		posRes1 = "common/txt/txt_dw_xm.png",
		titleRes2 = "common/txt/txt_dylk.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_xm.png",
		res1 = "config/big_hero/normal/img_492_xm@.png",
		res2 = "config/big_hero/normal/img_483_dylk@.png"
	},
	{
		card2 = 3261,
		card1 = 1281,
		id = 36,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_mlyt.png",
		posRes1 = "common/txt/txt_dw_slb.png",
		titleRes2 = "common/txt/txt_mlyt.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_slb.png",
		res1 = "config/big_hero/normal/img_251_slb@.png",
		res2 = "config/big_hero/normal/img_648_mlyt@.png"
	},
	{
		titleRes1 = "common/txt/txt_dkly.png",
		card1 = 2431,
		id = 37,
		res1 = "config/big_hero/normal/img_491_dkly@.png",
		posRes1 = "common/txt/txt_dw_dkly.png",
		resScale1 = 1.6
	},
	{
		card2 = 2351,
		card1 = 2361,
		id = 38,
		resScale2 = 2.33,
		posRes2 = "common/txt/txt_dw_dylk.png",
		posRes1 = "common/txt/txt_dw_plqy.png",
		titleRes2 = "common/txt/txt_dylk.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_plqy.png",
		res1 = "config/big_hero/normal/img_484_plqy@.png",
		res2 = "config/big_hero/normal/img_483_dylk@.png"
	},
	{
		card2 = 3601,
		card1 = 4161,
		id = 39,
		resScale2 = 2.33,
		posRes2 = "common/txt/xeneras2.png",
		posRes1 = "common/txt/zeraora2.png",
		titleRes2 = "common/txt/xeneras1.png",
		resScale1 = 2,
		titleRes1 = "common/txt/zeraora1.png",
		res1 = "config/big_hero/normal/img_807_jlal@.png",
		res2 = "config/big_hero/normal/img_716_zenys@.png"
	},
	{
		card2 = 1961,
		card1 = 2421,
		id = 40,
		resScale2 = 2,
		posRes2 = "common/txt/txt_dw_gok.png",
		posRes1 = "common/txt/txt_dw_mnf.png",
		titleRes2 = "common/txt/txt_gok.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_mnf.png",
		res1 = "config/big_hero/normal/img_490_mnf@.png",
		res2 = "config/big_hero/normal/img_382_gok@.png"
	},
	{
		card2 = 2431,
		card1 = 3623,
		id = 41,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_dkly.png",
		posRes1 = "common/txt/txt_dw_jged.png",
		titleRes2 = "common/txt/txt_dkly.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_jged.png",
		res1 = "config/big_hero/normal/img_718_jged100@.png",
		res2 = "config/big_hero/normal/img_491_dkly@.png"
	},
	{
		card2 = 2461,
		card1 = 4161,
		id = 42,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_bktn.png",
		posRes1 = "common/txt/zeraora2.png",
		titleRes2 = "common/txt/txt_bktn.png",
		resScale1 = 2,
		titleRes1 = "common/txt/zeraora1.png",
		res1 = "config/big_hero/normal/img_807_jlal@.png",
		res2 = "config/big_hero/normal/img_494_bktn@.png"
	},
	{
		card2 = 4121,
		card1 = 3623,
		id = 43,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_mxd.png",
		posRes1 = "common/txt/txt_dw_jged.png",
		titleRes2 = "common/txt/txt_mxd.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_jged.png",
		res1 = "config/big_hero/normal/img_718_jged100@.png",
		res2 = "config/big_hero/normal/img_802_mxd@.png"
	},
	{
		card2 = 4024,
		card1 = 2421,
		id = 44,
		resScale2 = 1.6,
		posRes2 = "common/txt/txt_dw_lnyl.png",
		posRes1 = "common/txt/txt_dw_mnf.png",
		titleRes2 = "common/txt/txt_lnyl.png",
		resScale1 = 2,
		titleRes1 = "common/txt/txt_mnf.png",
		res1 = "config/big_hero/normal/img_490_mnf@.png",
		res2 = "config/big_hero/normal/img_792_lnyl@.png"
	},
	__size = 44,
	__default = {
		__index = {
			titleRes1 = "",
			resScale2 = 1,
			posRes2 = "",
			posRes1 = "",
			titleRes2 = "",
			resScale1 = 1,
			resPos1 = ({
				default = slot0[1]
			}).default,
			resPos2 = ({
				default = slot0[1]
			}).default
		}
	}
}

return csv.yunying.draw_limit
