slot0 = {
	__size = 0
}
csv.random_tower.buffs = {
	{
		attrType1 = 7,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrNum1 = "10%",
		desc_en = "P. ATK of allied Pokémons +10%",
		desc = "P. ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 1,
		icon = "city/develop/talent/icon_wg.png",
		weight = 100
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrType1 = 7,
		attrNum1 = "15%",
		group = 2,
		desc_en = "P. ATK of allied Pokémons +15%",
		limit = 3,
		desc = "P. ATK of allied Pokémons +15%",
		buffColor = "effect",
		id = 2,
		icon = "city/develop/talent/icon_wg.png",
		weight = 100
	},
	{
		onlyOne = true,
		attrType1 = 7,
		attrNum1 = "20%",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 3,
		desc_en = "P. ATK of allied Pokémons +20%",
		limit = 1,
		desc = "P. ATK of allied Pokémons +20%",
		buffColor = "effect",
		id = 3,
		icon = "city/develop/talent/icon_wg.png",
		weight = 100
	},
	{
		attrType1 = 8,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrNum1 = "10%",
		desc_en = "SP.ATK of allied Pokémons +10%",
		desc = "SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 4,
		icon = "city/develop/talent/icon_tg.png",
		weight = 100
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrType1 = 8,
		attrNum1 = "15%",
		group = 2,
		desc_en = "SP.ATK of allied Pokémons +15%",
		limit = 3,
		desc = "SP.ATK of allied Pokémons +15%",
		buffColor = "effect",
		id = 5,
		icon = "city/develop/talent/icon_tg.png",
		weight = 100
	},
	{
		onlyOne = true,
		attrType1 = 8,
		attrNum1 = "20%",
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 3,
		desc_en = "SP.ATK of allied Pokémons +20%",
		limit = 1,
		desc = "SP.ATK of allied Pokémons +20%",
		buffColor = "effect",
		id = 6,
		icon = "city/develop/talent/icon_tg.png",
		weight = 100
	},
	{
		attrType1 = 8,
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 7,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 150
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 2,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		limit = 3,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		buffColor = "effect",
		id = 8,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 150
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "15%",
		attrNum1 = "15%",
		attrType2 = 7,
		group = 3,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +15%",
		limit = 2,
		desc = "P. ATK and SP.ATK of allied Pokémons +15%",
		attrType1 = 8,
		buffColor = "effect",
		id = 9,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 150
	},
	{
		attrType1 = 22,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrNum1 = "500",
		desc_en = "Allied Pokémons damage bonus +5%",
		desc = "Allied Pokémons damage bonus +5%",
		buffColor = "effect",
		id = 10,
		icon = "city/develop/talent/icon_shjc.png",
		weight = 100
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrType1 = 22,
		attrNum1 = "1000",
		group = 2,
		desc_en = "Allied Pokémons damage bonus +10%",
		limit = 3,
		desc = "Allied Pokémons damage bonus +10%",
		buffColor = "effect",
		id = 11,
		icon = "city/develop/talent/icon_shjc.png",
		weight = 120
	},
	{
		onlyOne = true,
		attrType1 = 22,
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 3,
		desc_en = "Allied Pokémons damage bonus +15%",
		limit = 1,
		desc = "Allied Pokémons damage bonus +15%",
		buffColor = "effect",
		id = 12,
		icon = "city/develop/talent/icon_shjc.png",
		weight = 150
	},
	{
		attrType1 = 14,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrNum1 = "500",
		desc_en = "Critical hit rate of allied Pokémons +5%",
		desc = "Critical hit rate of allied Pokémons +5%",
		buffColor = "effect",
		id = 13,
		icon = "city/develop/talent/icon_bj.png",
		weight = 100
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrType1 = 14,
		attrNum1 = "1000",
		group = 2,
		desc_en = "Critical hit rate of allied Pokémons +10%",
		limit = 3,
		desc = "Critical hit rate of allied Pokémons +10%",
		buffColor = "effect",
		id = 14,
		icon = "city/develop/talent/icon_bj.png",
		weight = 120
	},
	{
		onlyOne = true,
		attrType1 = 14,
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 3,
		desc_en = "Critical hit rate of allied Pokémons +15%",
		limit = 1,
		desc = "Critical hit rate of allied Pokémons +15%",
		buffColor = "effect",
		id = 15,
		icon = "city/develop/talent/icon_bj.png",
		weight = 150
	},
	{
		attrType1 = 15,
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		attrNum1 = "1000",
		desc_en = "Critical hit damage of allied Pokémons +10%",
		desc = "Critical hit damage of allied Pokémons +10%",
		buffColor = "effect",
		id = 16,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		attrType1 = 15,
		attrNum1 = "1500",
		group = 2,
		desc_en = "Critical hit damage of allied Pokémons +15%",
		limit = 3,
		desc = "Critical hit damage of allied Pokémons +15%",
		buffColor = "effect",
		id = 17,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 50
	},
	{
		onlyOne = true,
		attrType1 = 15,
		attrNum1 = "2000",
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 3,
		desc_en = "Critical hit damage of allied Pokémons +20%",
		limit = 1,
		desc = "Critical hit damage of allied Pokémons +20%",
		buffColor = "effect",
		id = 18,
		icon = "city/develop/talent/icon_bjsh.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		attrType1 = 9,
		attrNum1 = "15%",
		group = 1111,
		desc_en = "Allied Pokémons P.DEF +15%",
		desc = "Allied Pokémons P.DEF +15%",
		buffColor = "effect_lan",
		id = 19,
		icon = "city/develop/talent/icon_wf.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		attrType1 = 9,
		attrNum1 = "20%",
		group = 1111,
		desc_en = "Allied Pokémons P.DEF +20%",
		limit = 3,
		desc = "Allied Pokémons P.DEF +20%",
		buffColor = "effect_lan",
		id = 20,
		icon = "city/develop/talent/icon_wf.png",
		weight = 50
	},
	{
		onlyOne = true,
		attrType1 = 9,
		attrNum1 = "25%",
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		group = 1111,
		desc_en = "Allied Pokémons P.DEF +25%",
		limit = 1,
		desc = "Allied Pokémons P.DEF +25%",
		buffColor = "effect_lan",
		id = 21,
		icon = "city/develop/talent/icon_wf.png",
		weight = 10
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_purple.png",
		attrType1 = 10,
		attrNum1 = "15%",
		group = 1111,
		desc_en = "Allied Pokémons SP.DEF +15%",
		desc = "Allied Pokémons SP.DEF +15%",
		buffColor = "effect_lan",
		id = 22,
		icon = "city/develop/talent/icon_tf.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_purple.png",
		attrType1 = 10,
		attrNum1 = "20%",
		group = 1111,
		desc_en = "Allied Pokémons SP.DEF +20%",
		limit = 3,
		desc = "Allied Pokémons SP.DEF +20%",
		buffColor = "effect_lan",
		id = 23,
		icon = "city/develop/talent/icon_tf.png",
		weight = 50
	},
	{
		onlyOne = true,
		attrType1 = 10,
		attrNum1 = "25%",
		iconBg = "city/adventure/random_tower/icon/box_purple.png",
		group = 1111,
		desc_en = "Allied Pokémons SP.DEF +25%",
		limit = 1,
		desc = "Allied Pokémons SP.DEF +25%",
		buffColor = "effect_lan",
		id = 24,
		icon = "city/develop/talent/icon_tf.png",
		weight = 10
	},
	{
		attrType1 = 10,
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 9,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		desc_en = "Allied Pokémons P.DEF and SP.DEF +10%",
		desc = "Allied Pokémons P.DEF and SP.DEF +10%",
		buffColor = "effect_lan",
		id = 25,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 200
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrNum2 = "15%",
		attrNum1 = "15%",
		attrType2 = 9,
		group = 2,
		desc_en = "Allied Pokémons P.DEF and SP.DEF +15%",
		limit = 3,
		desc = "Allied Pokémons P.DEF and SP.DEF +15%",
		attrType1 = 10,
		buffColor = "effect_lan",
		id = 26,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 200
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrNum2 = "20%",
		attrNum1 = "20%",
		attrType2 = 9,
		group = 3,
		desc_en = "Allied Pokémons P.DEF and SP.DEF +20%",
		limit = 2,
		desc = "Allied Pokémons P.DEF and SP.DEF +20%",
		attrType1 = 10,
		buffColor = "effect_lan",
		id = 27,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 200
	},
	{
		attrType1 = 23,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrNum1 = "500",
		desc_en = "Allied Pokémons damage reduction +5%",
		desc = "Allied Pokémons damage reduction +5%",
		buffColor = "effect_lan",
		id = 28,
		icon = "city/develop/talent/icon_shjm.png",
		weight = 100
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		attrType1 = 23,
		attrNum1 = "1000",
		group = 2,
		desc_en = "Allied Pokémons damage reduction +10%",
		limit = 3,
		desc = "Allied Pokémons damage reduction +10%",
		buffColor = "effect_lan",
		id = 29,
		icon = "city/develop/talent/icon_shjm.png",
		weight = 100
	},
	{
		onlyOne = true,
		attrType1 = 23,
		attrNum1 = "1500",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 3,
		desc_en = "Allied Pokémons damage reduction +15%",
		limit = 1,
		desc = "Allied Pokémons damage reduction +15%",
		buffColor = "effect_lan",
		id = 30,
		icon = "city/develop/talent/icon_shjm.png",
		weight = 50
	},
	{
		attrType1 = 17,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrNum1 = "1000",
		desc_en = "Allied Pokémons DEF +10%",
		desc = "Allied Pokémons DEF +10%",
		buffColor = "effect_lan",
		id = 31,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrType1 = 17,
		attrNum1 = "1500",
		group = 2,
		desc_en = "Allied Pokémons DEF +15%",
		desc = "Allied Pokémons DEF +15%",
		buffColor = "effect_lan",
		id = 32,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		attrType1 = 17,
		attrNum1 = "2000",
		group = 3,
		desc_en = "Allied Pokémons DEF +20%",
		desc = "Allied Pokémons DEF +20%",
		buffColor = "effect_lan",
		id = 33,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		weight = 50
	},
	{
		attrType1 = 26,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		attrNum1 = "400",
		desc_en = "Allied Pokémons life steal +4%",
		desc = "Allied Pokémons life steal +4%",
		buffColor = "effect_lan",
		id = 34,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		attrType1 = 26,
		attrNum1 = "800",
		group = 2,
		desc_en = "Allied Pokémons life steal +8%",
		desc = "Allied Pokémons life steal +8%",
		buffColor = "effect_lan",
		id = 35,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 40
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		attrType1 = 26,
		attrNum1 = "1000",
		group = 3,
		desc_en = "Allied Pokémons life steal +10%",
		desc = "Allied Pokémons life steal +10%",
		buffColor = "effect_lan",
		id = 36,
		icon = "city/adventure/random_tower/icon/icon_xx.png",
		weight = 30
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		buffType = 2,
		supplyType = 1,
		supplyNum = 25,
		group = 4,
		desc_en = "Recover 25% HP for 1 Pokémon",
		condition = 1,
		desc = "Recover 25% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 37,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		buffType = 2,
		supplyType = 1,
		supplyNum = 50,
		group = 5,
		desc_en = "Recover 50% HP for 1 Pokémon",
		condition = 1,
		desc = "Recover 50% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 38,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		buffType = 2,
		supplyType = 1,
		supplyNum = 100,
		group = 5,
		desc_en = "Recover 100% HP for 1 Pokémon",
		condition = 1,
		desc = "Recover 100% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 39,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 10
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		buffType = 2,
		supplyType = 1,
		supplyNum = 25,
		group = 4,
		desc_en = "Recover 25% HP for 1 Pokémon",
		condition = 1,
		desc = "Recover 25% HP for 1 Pokémon",
		supplyTarget = 1,
		id = 40,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 1
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 2,
		supplyNum = 25,
		group = 4,
		desc_en = "Recover 200 rage points for 1 Pokémon",
		condition = 2,
		desc = "Recover 200 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 41,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 2,
		supplyNum = 50,
		group = 5,
		desc_en = "Recover 500 rage points for 1 Pokémon",
		condition = 2,
		desc = "Recover 500 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 42,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 50
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 2,
		supplyNum = 100,
		group = 5,
		desc_en = "Recover 1000 rage points for 1 Pokémon",
		condition = 2,
		desc = "Recover 1000 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 43,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 10
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 2,
		supplyNum = 100,
		group = 5,
		desc_en = "Recover 1000 rage points for 1 Pokémon",
		condition = 2,
		desc = "Recover 1000 rage points for 1 Pokémon",
		supplyTarget = 1,
		id = 44,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 1
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 3,
		group = 4,
		desc_en = "Revive one Pokémon",
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 45,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 3,
		group = 5,
		desc_en = "Revive one Pokémon",
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 46,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 3,
		group = 4,
		desc_en = "Revive one Pokémon",
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 47,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 1
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 3,
		group = 5,
		desc_en = "Revive one Pokémon",
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 48,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 1
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		buffType = 2,
		supplyType = 1,
		supplyNum = 100,
		group = 6,
		desc_en = "HP of allied Pokémons fully recovers",
		condition = 1,
		desc = "HP of allied Pokémons fully recovers",
		supplyTarget = 2,
		id = 49,
		icon = "city/adventure/random_tower/icon/icon_hx.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 2,
		supplyNum = 100,
		group = 6,
		desc_en = "Rage of all Pokémons in battle fully recovers",
		condition = 2,
		desc = "Rage of all Pokémons in battle fully recovers",
		supplyTarget = 2,
		id = 50,
		icon = "city/adventure/random_tower/icon/icon_hn.png",
		weight = 20
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 2,
		supplyType = 3,
		group = 6,
		desc_en = "Revive one Pokémon",
		condition = 3,
		desc = "Revive one Pokémon",
		supplyTarget = 1,
		id = 51,
		icon = "city/adventure/random_tower/icon/icon_fh.png",
		weight = 1
	},
	{
		onlyOne = true,
		buffType = 3,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 99,
		desc_en = "At the end of the battle, you can get an additional points of remaining rounds x2",
		pointType = 1,
		desc = "At the end of the battle, you can get an additional points of remaining rounds x2",
		buffColor = "effect_huang",
		id = 52,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 2
	},
	{
		onlyOne = true,
		buffType = 3,
		pointValue = 1,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 99,
		desc_en = "At the end of the battle, you can get an additional ponits of surviving Pokémons x1",
		pointType = 2,
		desc = "At the end of the battle, you can get an additional ponits of surviving Pokémons x1",
		buffColor = "effect_huang",
		id = 53,
		icon = "city/adventure/random_tower/icon_jf.png",
		weight = 10
	},
	{
		onlyOne = true,
		buffType = 3,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 99,
		desc_en = "At the end of the battle, you can get an additional ponits of surviving Pokémons x2",
		pointType = 2,
		desc = "At the end of the battle, you can get an additional ponits of surviving Pokémons x2",
		buffColor = "effect_huang",
		id = 54,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 2
	},
	{
		onlyOne = true,
		buffType = 3,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 99,
		desc_en = "At the end of the battle, you can get an additional points of the current floor level x2",
		pointType = 3,
		desc = "At the end of the battle, you can get an additional points of the current floor level x2",
		buffColor = "effect_huang",
		id = 55,
		icon = "city/adventure/random_tower/icon_jf.png",
		pointValue = 2
	},
	{
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 99,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 56,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	__size = 210,
	[101] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		desc_en = "P. ATK of allied Pokémons +20%",
		group = 21,
		attrType1 = 7,
		limit = 1,
		desc = "P. ATK of allied Pokémons +20%",
		buffColor = "effect",
		id = 101,
		icon = "city/develop/talent/icon_wg.png",
		attrNum1 = "20%"
	},
	[102] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		desc_en = "SP.ATK of allied Pokémons +20%",
		group = 21,
		attrType1 = 8,
		limit = 1,
		desc = "SP.ATK of allied Pokémons +20%",
		buffColor = "effect",
		id = 102,
		icon = "city/develop/talent/icon_tg.png",
		attrNum1 = "20%"
	},
	[103] = {
		desc_en = "P. ATK and SP.ATK of allied Pokémons +15%",
		attrNum2 = "15%",
		attrType2 = 7,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 21,
		attrType1 = 8,
		limit = 2,
		desc = "P. ATK and SP.ATK of allied Pokémons +15%",
		buffColor = "effect",
		id = 103,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		attrNum1 = "15%"
	},
	[104] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		desc_en = "Allied Pokémons damage bonus +20%",
		group = 21,
		attrType1 = 22,
		limit = 1,
		desc = "Allied Pokémons damage bonus +20%",
		buffColor = "effect",
		id = 104,
		icon = "city/develop/talent/icon_shjc.png",
		attrNum1 = "2000"
	},
	[105] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		desc_en = "Critical hit rate of allied Pokémons +20%",
		group = 21,
		attrType1 = 14,
		limit = 1,
		desc = "Critical hit rate of allied Pokémons +20%",
		buffColor = "effect",
		id = 105,
		icon = "city/develop/talent/icon_bj.png",
		attrNum1 = "2000"
	},
	[106] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		desc_en = "Critical hit damage of allied Pokémons +30%",
		group = 21,
		attrType1 = 15,
		limit = 1,
		desc = "Critical hit damage of allied Pokémons +30%",
		buffColor = "effect",
		id = 106,
		icon = "city/develop/talent/icon_bjsh.png",
		attrNum1 = "30%"
	},
	[121] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		desc_en = "Allied Pokémons P.DEF +30%",
		group = 22,
		attrType1 = 9,
		limit = 1,
		desc = "Allied Pokémons P.DEF +30%",
		buffColor = "effect_lan",
		id = 121,
		icon = "city/develop/talent/icon_wf.png",
		attrNum1 = "30%"
	},
	[122] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_purple.png",
		desc_en = "Allied Pokémons SP.DEF +30%",
		group = 22,
		attrType1 = 10,
		limit = 1,
		desc = "Allied Pokémons SP.DEF +30%",
		buffColor = "effect_lan",
		id = 122,
		icon = "city/develop/talent/icon_tf.png",
		attrNum1 = "30%"
	},
	[123] = {
		desc_en = "Allied Pokémons P.DEF and SP.DEF +25%",
		attrNum2 = "25%",
		attrType2 = 9,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 22,
		attrType1 = 10,
		limit = 2,
		desc = "Allied Pokémons P.DEF and SP.DEF +25%",
		buffColor = "effect_lan",
		id = 123,
		icon = "city/adventure/random_tower/icon/icon_fy.png",
		attrNum1 = "25%"
	},
	[124] = {
		onlyOne = true,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		desc_en = "Allied Pokémons damage reduction +20%",
		group = 22,
		attrType1 = 23,
		limit = 1,
		desc = "Allied Pokémons damage reduction +20%",
		buffColor = "effect_lan",
		id = 124,
		icon = "city/develop/talent/icon_shjm.png",
		attrNum1 = "2000"
	},
	[200] = {
		group = 1111,
		buffType = 2,
		supplyType = 4,
		supplyTarget = 2,
		id = 200,
		desc_en = "Reduce current HP by 10%",
		supplyNum = 10,
		desc = "Reduce current HP by 10%"
	},
	[201] = {
		group = 1111,
		buffType = 2,
		supplyType = 4,
		supplyTarget = 2,
		id = 201,
		desc_en = "Reduce current HP by 20%",
		supplyNum = 20,
		desc = "Reduce current HP by 20%"
	},
	[202] = {
		group = 1111,
		buffType = 2,
		supplyType = 4,
		supplyTarget = 2,
		id = 202,
		desc_en = "Reduce current HP by 30%",
		supplyNum = 30,
		desc = "Reduce current HP by 30%"
	},
	[203] = {
		group = 1111,
		buffType = 2,
		supplyType = 5,
		supplyTarget = 2,
		id = 203,
		desc_en = "Current rage value reduces by 200",
		supplyNum = 20,
		desc = "Current rage value reduces by 200"
	},
	[204] = {
		group = 1111,
		buffType = 2,
		supplyType = 5,
		supplyTarget = 2,
		id = 204,
		desc_en = "Current rage value reduces by 500",
		supplyNum = 50,
		desc = "Current rage value reduces by 500"
	},
	[205] = {
		group = 1111,
		buffType = 2,
		supplyType = 5,
		supplyTarget = 2,
		id = 205,
		desc_en = "Current rage value reduces by 1000",
		supplyNum = 100,
		desc = "Current rage value reduces by 1000"
	},
	[206] = {
		group = 1111,
		buffType = 2,
		supplyType = 2,
		supplyTarget = 2,
		id = 206,
		desc_en = "Increases current rage value by 500",
		supplyNum = 50,
		desc = "Increases current rage value by 500"
	},
	[207] = {
		group = 1111,
		icon = "city/adventure/random_tower/icon/icon_wf.png",
		buffColor = "effect_lan",
		attrType1 = 13,
		id = 207,
		desc_en = "Speed of allied Pokémons -20%",
		attrNum1 = "-20%",
		desc = "Speed of allied Pokémons -20%"
	},
	[208] = {
		group = 1111,
		icon = "city/adventure/random_tower/icon/icon_wf.png",
		buffColor = "effect_lan",
		attrType1 = 13,
		id = 208,
		desc_en = "Speed of allied Pokémons -40%",
		attrNum1 = "-40%",
		desc = "Speed of allied Pokémons -40%"
	},
	[210] = {
		group = 1111,
		buffType = 2,
		supplyType = 1,
		supplyTarget = 2,
		id = 210,
		desc_en = "HP of allied Pokémons fully recovers",
		supplyNum = 100,
		desc = "HP of allied Pokémons fully recovers"
	},
	[211] = {
		group = 1111,
		buffType = 2,
		supplyType = 2,
		supplyTarget = 2,
		id = 211,
		desc_en = "Rage of all Pokémons in battle fully recovers",
		supplyNum = 100,
		desc = "Rage of all Pokémons in battle fully recovers"
	},
	[212] = {
		group = 1111,
		icon = "city/adventure/random_tower/icon/icon_tg.png",
		buffColor = "effect",
		attrType1 = 7,
		id = 212,
		desc_en = "P. ATK of allied Pokémons -5%",
		attrNum1 = "-5%",
		desc = "P. ATK of allied Pokémons -5%"
	},
	[213] = {
		group = 1111,
		icon = "city/adventure/random_tower/icon/icon_tg.png",
		buffColor = "effect",
		attrType1 = 8,
		id = 213,
		desc_en = "SP.ATK of allied Pokémons -5%",
		attrNum1 = "-5%",
		desc = "SP.ATK of allied Pokémons -5%"
	},
	[214] = {
		group = 1111,
		buffType = 2,
		supplyType = 1,
		supplyTarget = 2,
		id = 214,
		desc_en = "Allied Pokémons recovers 20% HP",
		supplyNum = 20,
		desc = "Allied Pokémons recovers 20% HP"
	},
	[215] = {
		group = 1111,
		buffType = 2,
		supplyType = 2,
		supplyTarget = 2,
		id = 215,
		desc_en = "Rage of all Pokémons in battle increases by 200",
		supplyNum = 20,
		desc = "Rage of all Pokémons in battle increases by 200"
	},
	[1001] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80001,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 103,
		desc_en = "When the HP of allied Pokémons falls below 40%, damage increases by 10% per attack (stackable)",
		limit = 1,
		desc = "When the HP of allied Pokémons falls below 40%, damage increases by 10% per attack (stackable)",
		changeLib = 5,
		buffColor = "effect_huang",
		id = 1001,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1002] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 200,
		desc_en = "For every 10% HP lost, the damage of allied Pokémons increases by 8%",
		passiveSkill = 80002,
		desc = "For every 10% HP lost, the damage of allied Pokémons increases by 8%",
		buffColor = "effect",
		id = 1002,
		icon = "city/adventure/random_tower/icon/icon_cxsh.png"
	},
	[1003] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Each time it hits the enemy, it will receive an additional 8% of HP lost as true damage.",
		passiveSkill = 80003,
		desc = "Each time it hits the enemy, it will receive an additional 8% of HP lost as true damage.",
		buffColor = "effect_huang",
		id = 1003,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1004] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Each time it hits the enemy, it will deal an additional 5% of enemy's HP lost as true damage.",
		passiveSkill = 80004,
		desc = "Each time it hits the enemy, it will deal an additional 5% of enemy's HP lost as true damage.",
		buffColor = "effect_huang",
		id = 1004,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1005] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80005,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 101,
		desc_en = "Increases attack damage equivalent to 30% current DEF value",
		limit = 1,
		desc = "Increases attack damage equivalent to 30% current DEF value",
		changeLib = 7,
		buffColor = "effect",
		id = 1005,
		icon = "city/adventure/random_tower/icon/icon_qs.png"
	},
	[1006] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80006,
		effectTimes = 1,
		group = 999,
		desc_en = "An additional 50% critical strike rate bonus will be given for the ultimate move is used for the first time in the battle",
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		desc = "An additional 50% critical strike rate bonus will be given for the ultimate move is used for the first time in the battle",
		buffColor = "effect_huang",
		id = 1006,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[1007] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Each time an ultimate move is casted, the damage of the move increases by 10% and lasts until the end of the battle.",
		passiveSkill = 80007,
		desc = "Each time an ultimate move is casted, the damage of the move increases by 10% and lasts until the end of the battle.",
		buffColor = "effect_huang",
		id = 1007,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[1008] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Each time when you use the ultimate after casting a basic move, the damage will increase by 10%, which disappears when the ultimate is casted",
		passiveSkill = 80008,
		desc = "Each time when you use the ultimate after casting a basic move, the damage will increase by 10%, which disappears when the ultimate is casted",
		buffColor = "effect_huang",
		id = 1008,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[1009] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 200,
		desc_en = "Damage reduces by 20% when HP of allied Pokémon falls below 40%",
		passiveSkill = 80009,
		desc = "Damage reduces by 20% when HP of allied Pokémon falls below 40%",
		buffColor = "effect_blue",
		id = 1009,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1010] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "When the HP of allied Pokémons falls below 10%, life steal increases 50% more, but loses effect when HP is more than 10%",
		passiveSkill = 80010,
		desc = "When the HP of allied Pokémons falls below 10%, life steal increases 50% more, but loses effect when HP is more than 10%",
		buffColor = "effect_huang",
		id = 1010,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[1011] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 7,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 200,
		desc_en = "Increases P.ATK and SP.DEF by 15% for each damage taken, stacking up to 3 times for 2 turns",
		passiveSkill = 80011,
		desc = "Increases P.ATK and SP.DEF by 15% for each damage taken, stacking up to 3 times for 2 turns",
		buffColor = "effect_blue",
		id = 1011,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1012] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 200,
		desc_en = "Life steal increases by 5% when the Pokémon's current HP falls below 10%",
		passiveSkill = 80012,
		desc = "Life steal increases by 5% when the Pokémon's current HP falls below 10%",
		buffColor = "effect",
		id = 1012,
		icon = "city/adventure/random_tower/icon/icon_xx.png"
	},
	[1013] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80013,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 102,
		desc_en = "Converts all of your life steal bonuses into shield (shield value = max. HP x life steal rate x 1.5), and the shield lasts for 2 turns",
		limit = 1,
		desc = "Converts all of your life steal bonuses into shield (shield value = max. HP x life steal rate x 1.5), and the shield lasts for 2 turns",
		changeLib = 9,
		buffColor = "effect_huang",
		id = 1013,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1014] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 9,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Immune to status conditions when is shielded",
		passiveSkill = 80014,
		desc = "Immune to status conditions when is shielded",
		buffColor = "effect_huang",
		id = 1014,
		icon = "city/adventure/random_tower/icon/icon_qs.png"
	},
	[1015] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 7,
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		group = 200,
		desc_en = "Allied Pokémons have a 5% chance of silencing the attacker for 1 turn when received attacks",
		passiveSkill = 80015,
		desc = "Allied Pokémons have a 5% chance of silencing the attacker for 1 turn when received attacks",
		buffColor = "effect_huang",
		id = 1015,
		icon = "city/adventure/random_tower/icon/icon_kz.png"
	},
	[1016] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80016,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Gains additional 100 rage points when the battle begins",
		desc = "Gains additional 100 rage points when the battle begins",
		buffColor = "effect_huang",
		id = 1016,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1017] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80017,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Gains additional 100 rage points when the enemy is knocked out",
		desc = "Gains additional 100 rage points when the enemy is knocked out",
		buffColor = "effect_huang",
		id = 1017,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1018] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80018,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Gains additional 100 rage points when attacked",
		desc = "Gains additional 100 rage points when attacked",
		buffColor = "effect_huang",
		id = 1018,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1019] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80019,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 101,
		desc_en = "Provides all Pokémons present with additional 5% of P.ATK and SP.ATK for its current type (only for primary type)",
		limit = 1,
		desc = "Provides all Pokémons present with additional 5% of P.ATK and SP.ATK for its current type (only for primary type)",
		changeLib = 1,
		buffColor = "effect",
		id = 1019,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[1020] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 2,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1111,
		desc_en = "Specific type Pokémons (only for the primary type) can get a bonus of P.ATK and SP.ATK by 20% (one specific buff per type)",
		passiveSkill = 80020,
		desc = "Specific type Pokémons (only for the primary type) can get a bonus of P.ATK and SP.ATK by 20% (one specific buff per type)",
		buffColor = "effect",
		id = 1020,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[1021] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80021,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 102,
		desc_en = "An additional 5% of P.ATK and SP.ATK is given to the Pokémons with the most number of used types (only the primary types)",
		limit = 1,
		desc = "An additional 5% of P.ATK and SP.ATK is given to the Pokémons with the most number of used types (only the primary types)",
		changeLib = 2,
		buffColor = "effect",
		id = 1021,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[1022] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80022,
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 1000,
		desc_en = "When SP.ATK damage is dealt, critical hit rate is increased by 5% for 2 turns, stacking up to 4 times, and the duration of the stacks refreshes.",
		desc = "When SP.ATK damage is dealt, critical hit rate is increased by 5% for 2 turns, stacking up to 4 times, and the duration of the stacks refreshes.",
		buffColor = "effect",
		id = 1022,
		icon = "city/adventure/random_tower/icon/icon_bj.png"
	},
	[1023] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80023,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "An additional 10% SP.ATK bonus is given for every 20% P.ATK bonus",
		limit = 1,
		desc = "An additional 10% SP.ATK bonus is given for every 20% P.ATK bonus",
		buffColor = "effect_huang",
		id = 1023,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1024] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80024,
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 1000,
		desc_en = "Increases critical damage by 20% and recovers 10% of max. HP when dealing critical hit",
		desc = "Increases critical damage by 20% and recovers 10% of max. HP when dealing critical hit",
		buffColor = "effect_huang",
		id = 1024,
		icon = "city/adventure/random_tower/icon/icon_bj.png"
	},
	[1025] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80025,
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 1000,
		desc_en = "An additional 10% P.ATK bonus is given for every 20% SP.ATK bonus",
		desc = "An additional 10% P.ATK bonus is given for every 20% SP.ATK bonus",
		buffColor = "effect_huang",
		id = 1025,
		icon = "city/adventure/random_tower/icon/icon_bj.png"
	},
	[1026] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Dispels status conditions while dealing damage to enemies in status conditions and deals additional damage by 50% x  no. of turns remaining",
		limit = 1,
		desc = "Dispels status conditions while dealing damage to enemies in status conditions and deals additional damage by 50% x  no. of turns remaining",
		passiveSkill = 80026,
		buffColor = "effect_huang",
		id = 1026,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1027] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80027,
		iconBg = "city/adventure/random_tower/icon/box_orange.png",
		group = 1000,
		desc_en = "When dealing a critical hit, the critical hit damage dealt will increased by 20%, and 5% of the damage dealt will be restored as the user's HP.",
		desc = "When dealing a critical hit, the critical hit damage dealt will increased by 20%, and 5% of the damage dealt will be restored as the user's HP.",
		buffColor = "effect_huang",
		id = 1027,
		icon = "city/adventure/random_tower/icon/icon_bj.png"
	},
	[1028] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80028,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "On every final round, one of the status conditions on all allied Pokémons will be dispelled",
		limit = 1,
		desc = "On every final round, one of the status conditions on all allied Pokémons will be dispelled",
		buffColor = "effect_huang",
		id = 1028,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1029] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80029,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1111,
		desc_en = "Calculates the continuous damage taken by the target during the attack, causing its remaining continuous damage value to take effect immediately",
		desc = "Calculates the continuous damage taken by the target during the attack, causing its remaining continuous damage value to take effect immediately",
		changeLib = 6,
		buffColor = "effect_huang",
		id = 1029,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1030] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Debuff is removed at the beginning of each turn. For each debuff removed, the turn gains a 5% damage bonus.",
		passiveSkill = 80030,
		desc = "Debuff is removed at the beginning of each turn. For each debuff removed, the turn gains a 5% damage bonus.",
		buffColor = "effect_huang",
		id = 1030,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[1031] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80031,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 103,
		desc_en = "For every stack of continuous damage, the amount of damage the enemy receives increases by 5%",
		desc = "For every stack of continuous damage, the amount of damage the enemy receives increases by 5%",
		changeLib = 6,
		buffColor = "effect_huang",
		id = 1031,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1032] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "For every 2% life steal bonus, damage bonus increases by 1%",
		passiveSkill = 80032,
		desc = "For every 2% life steal bonus, damage bonus increases by 1%",
		buffColor = "effect_huang",
		id = 1032,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1033] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 7,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 9999,
		desc_en = "Damage reflection can reduce the enemy's P.ATK and SP.ATK by 5% for 2 turns, stacking up to 4 times",
		passiveSkill = 80033,
		desc = "Damage reflection can reduce the enemy's P.ATK and SP.ATK by 5% for 2 turns, stacking up to 4 times",
		buffColor = "effect",
		id = 1033,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[1034] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 8,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "For every 2% life steal bonus, damage bonus increases by 1%",
		passiveSkill = 80034,
		desc = "For every 2% life steal bonus, damage bonus increases by 1%",
		buffColor = "effect_huang",
		id = 1034,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1035] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80035,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1111,
		desc_en = "When dealing damage, additional damage is added to life steal effects",
		desc = "When dealing damage, additional damage is added to life steal effects",
		changeLib = 8,
		buffColor = "effect",
		id = 1035,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[1036] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 9,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Each damage dealt include damage with additional shield value",
		passiveSkill = 80036,
		desc = "Each damage dealt include damage with additional shield value",
		buffColor = "effect_huang",
		id = 1036,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1037] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 9,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "When damage is dealt, additional damage equivalent to the current amount of shield / HP damage is increased and all current shield is removed",
		passiveSkill = 80037,
		desc = "When damage is dealt, additional damage equivalent to the current amount of shield / HP damage is increased and all current shield is removed",
		buffColor = "effect_huang",
		id = 1037,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1038] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80038,
		effectTimes = 1,
		group = 999,
		desc_en = "In the next battle, allied Pokémons get a 100% chance of damage bonus after knocking down enemies for 2 turns",
		desc = "In the next battle, allied Pokémons get a 100% chance of damage bonus after knocking down enemies for 2 turns",
		buffColor = "effect",
		id = 1038,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[1039] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80039,
		effectTimes = 1,
		group = 999,
		desc_en = "At the beginning of the next battle, the allied Pokémon that makes the first move deals double damage",
		desc = "At the beginning of the next battle, the allied Pokémon that makes the first move deals double damage",
		buffColor = "effect_huang",
		id = 1039,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[1040] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 4,
		passiveSkill = 80040,
		effectTimes = 1,
		group = 9999,
		desc_en = "At the beginning of the next battle, there will be a 15% chance the opponent’s current HP will be reduced by half. It will only be triggered when the on the first battle, and not be triggered in the subsequent battles",
		desc = "At the beginning of the next battle, there will be a 15% chance the opponent’s current HP will be reduced by half. It will only be triggered when the on the first battle, and not be triggered in the subsequent battles",
		buffColor = "effect",
		id = 1040,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1041] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 4,
		passiveSkill = 80041,
		effectTimes = 1,
		group = 9999,
		desc_en = "At the beginning of the next battle, the enemy has a 50% chance of fainting instantly (the probability applies to individual enemy)",
		desc = "At the beginning of the next battle, the enemy has a 50% chance of fainting instantly (the probability applies to individual enemy)",
		buffColor = "effect_huang",
		id = 1041,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1042] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 1,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 200,
		desc_en = "Get an additional 2% damage reduction for every type of Pokémon used",
		passiveSkill = 80042,
		desc = "Get an additional 2% damage reduction for every type of Pokémon used",
		buffColor = "effect_huang",
		id = 1042,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1043] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		group = 1111,
		desc_en = "Allied Pokémon's immunity to status condition increases by 30%",
		passiveSkill = 80043,
		desc = "Allied Pokémon's immunity to status condition increases by 30%",
		buffColor = "effect_huang",
		id = 1043,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png"
	},
	[1044] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80044,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Every additional 5% of DEF (for Aether Paradise boost, special battle boost and buff boost) gives additional 5% of reflected damage",
		desc = "Every additional 5% of DEF (for Aether Paradise boost, special battle boost and buff boost) gives additional 5% of reflected damage",
		buffColor = "effect_huang",
		id = 1044,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1045] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 9,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Gets a shield that is equivalent to 5% of damage received each time damage is dealt",
		passiveSkill = 80045,
		desc = "Gets a shield that is equivalent to 5% of damage received each time damage is dealt",
		buffColor = "effect_huang",
		id = 1045,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1046] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 9,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Each point of over spilled HP recovery value is converted to 2 shield value",
		passiveSkill = 80046,
		desc = "Each point of over spilled HP recovery value is converted to 2 shield value",
		buffColor = "effect_huang",
		id = 1046,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1047] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 4,
		passiveSkill = 80047,
		effectTimes = 1,
		group = 9999,
		desc_en = "The first allied Pokémon that is being knocked out will be revived before its next turn, restoring 50% HP and 100% rage value. This effect can only be used once.",
		desc = "The first allied Pokémon that is being knocked out will be revived before its next turn, restoring 50% HP and 100% rage value. This effect can only be used once.",
		buffColor = "effect_huang",
		id = 1047,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1048] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1111,
		desc_en = "Increases the status condition duration dealt by allied Pokémons by 1 turn",
		passiveSkill = 80048,
		desc = "Increases the status condition duration dealt by allied Pokémons by 1 turn",
		buffColor = "effect",
		id = 1048,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[1049] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Allied Pokémons increase ability of dealing status conditions by 20%",
		passiveSkill = 80049,
		desc = "Allied Pokémons increase ability of dealing status conditions by 20%",
		buffColor = "effect_huang",
		id = 1049,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1050] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1111,
		desc_en = "Increase the duration of poisoning, bleeding, and burning by 1 turn",
		passiveSkill = 80050,
		desc = "Increase the duration of poisoning, bleeding, and burning by 1 turn",
		buffColor = "effect",
		id = 1050,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[1051] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 200,
		desc_en = "Increase damage caused by poisoning, bleeding and burning by 10%",
		passiveSkill = 80051,
		desc = "Increase damage caused by poisoning, bleeding and burning by 10%",
		buffColor = "effect_huang",
		id = 1051,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[1052] = {
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		buffType = 4,
		passiveSkill = 80052,
		effectTimes = 1,
		group = 999,
		desc_en = "All enemies are silence for 1 turn in the next battle",
		desc = "All enemies are silence for 1 turn in the next battle",
		buffColor = "effect_huang",
		id = 1052,
		icon = "city/adventure/random_tower/icon/icon_kz.png"
	},
	[1053] = {
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		buffType = 4,
		passiveSkill = 80053,
		effectTimes = 1,
		group = 999,
		desc_en = "All enemies fall asleep for 1 turn in the next battle",
		desc = "All enemies fall asleep for 1 turn in the next battle",
		buffColor = "effect_huang",
		id = 1053,
		icon = "city/adventure/random_tower/icon/icon_kz.png"
	},
	[1054] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 1,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "At the start of the battle, all Pokémons get extra x50 rage points for its current type (primary type)",
		passiveSkill = 80054,
		desc = "At the start of the battle, all Pokémons get extra x50 rage points for its current type (primary type)",
		buffColor = "effect_huang",
		id = 1054,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1055] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 2,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "If there are more than 4 Pokémons in the lineup with the same primary type, the initial anger value of the Pokémons with the specific type +500 at the beginning of the battle.",
		passiveSkill = 80055,
		desc = "If there are more than 4 Pokémons in the lineup with the same primary type, the initial anger value of the Pokémons with the specific type +500 at the beginning of the battle.",
		buffColor = "effect_huang",
		id = 1055,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1056] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "When HP falls below 40%, the rage value recovery effect doubles",
		passiveSkill = 80056,
		desc = "When HP falls below 40%, the rage value recovery effect doubles",
		buffColor = "effect_huang",
		id = 1056,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1057] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 4,
		passiveSkill = 80057,
		effectTimes = 1,
		group = 999,
		desc_en = "When the next battle begins, allied Pokémons will get an initial 1000 rage points",
		desc = "When the next battle begins, allied Pokémons will get an initial 1000 rage points",
		buffColor = "effect_huang",
		id = 1057,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1100] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 200,
		desc_en = "Allied Pokémons gain a shield that is equal to the HP it lost at the start of the battle for 2 rounds",
		passiveSkill = 80058,
		desc = "Allied Pokémons gain a shield that is equal to the HP it lost at the start of the battle for 2 rounds",
		buffColor = "effect_lan",
		id = 1100,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1101] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 5,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 200,
		desc_en = "Allied Pokémons gain 8% damage reduction each time they lose 10% HP, this is only effecitve on the first round",
		passiveSkill = 80059,
		desc = "Allied Pokémons gain 8% damage reduction each time they lose 10% HP, this is only effecitve on the first round",
		buffColor = "effect_lan",
		id = 1101,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1102] = {
		onlyOne = true,
		passiveSkill = 80060,
		buffType = 4,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 9999,
		desc_en = "Resets the enemies' rage value to zero during the second round of the battle",
		limit = 1,
		desc = "Resets the enemies' rage value to zero during the second round of the battle",
		id = 1102,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1103] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80061,
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		group = 1000,
		desc_en = "When any of the allied Pokémon is defeated, the remaining surviving Pokémons gain 20% of its max. HP and 500 rage value",
		desc = "When any of the allied Pokémon is defeated, the remaining surviving Pokémons gain 20% of its max. HP and 500 rage value",
		buffColor = "effect_huang",
		id = 1103,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png"
	},
	[1104] = {
		onlyOne = true,
		passiveSkill = 80062,
		buffType = 4,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		group = 1000,
		desc_en = "At the end of the round, all allied Pokémons recover 15% of its lost HP",
		desc = "At the end of the round, all allied Pokémons recover 15% of its lost HP",
		id = 1104,
		icon = "city/adventure/random_tower/icon/icon_hx.png"
	},
	[1105] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80063,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Gives 10% of chance to recover 100% rage level when allied Pokémon uses the ultimate skill",
		desc = "Gives 10% of chance to recover 100% rage level when allied Pokémon uses the ultimate skill",
		buffColor = "effect_huang",
		id = 1105,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1106] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80064,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1000,
		desc_en = "Marks a random enemy Pokémon at the beginning of each round to increase its damage taken by an additional 50%",
		desc = "Marks a random enemy Pokémon at the beginning of each round to increase its damage taken by an additional 50%",
		buffColor = "effect",
		id = 1106,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[1107] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80065,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Speed increases by 20% for 2 rounds when allied Pokémons use the Ultimate Skill",
		desc = "Speed increases by 20% for 2 rounds when allied Pokémons use the Ultimate Skill",
		buffColor = "effect_huang",
		id = 1107,
		icon = "city/adventure/random_tower/icon/icon_yybm.png"
	},
	[1108] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80066,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1000,
		desc_en = "Type effectiveness of allied Pokémons increases, causing 20% more damage to types that are effective during battles",
		desc = "Type effectiveness of allied Pokémons increases, causing 20% more damage to types that are effective during battles",
		buffColor = "effect",
		id = 1108,
		icon = "city/adventure/random_tower/icon/icon_cxsh.png"
	},
	[1109] = {
		onlyOne = true,
		passiveSkill = 80067,
		buffType = 4,
		iconBg = "city/adventure/random_tower/icon/box_pink.png",
		group = 1000,
		desc_en = "When your Pokémons defeat the opponent's Pokémons, you receive 10% HP and 200 rage level ",
		desc = "When your Pokémons defeat the opponent's Pokémons, you receive 10% HP and 200 rage level ",
		id = 1109,
		icon = "city/adventure/random_tower/icon/icon_hx.png"
	},
	[1110] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80068,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 9999,
		desc_en = "Enemy Pokémons with less than 10% HP at the end of the final round will be finished off by Yveltal, the god of death, and will leave the battlefield instantly",
		limit = 1,
		desc = "Enemy Pokémons with less than 10% HP at the end of the final round will be finished off by Yveltal, the god of death, and will leave the battlefield instantly",
		buffColor = "effect",
		id = 1110,
		icon = "city/adventure/random_tower/icon/icon_js.png"
	},
	[1111] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80069,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Increases speed of allied team by 20% in the first round of the battle",
		desc = "Increases speed of allied team by 20% in the first round of the battle",
		buffColor = "effect_huang",
		id = 1111,
		icon = "city/adventure/random_tower/icon/icon_yybm.png"
	},
	[1112] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 1,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 200,
		desc_en = "Increases the speed of an allied Pokémon type x4% only the Pokémon's first type is considered)",
		passiveSkill = 80070,
		desc = "Increases the speed of an allied Pokémon type x4% only the Pokémon's first type is considered)",
		buffColor = "effect_huang",
		id = 1112,
		icon = "city/adventure/random_tower/icon/icon_yybm.png"
	},
	[1113] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 7,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 200,
		desc_en = "There is a 50% chance the Pokémons in the front line are immune to status conditions",
		passiveSkill = 80071,
		desc = "There is a 50% chance the Pokémons in the front line are immune to status conditions",
		buffColor = "effect_lan",
		id = 1113,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1114] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80072,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 9999,
		desc_en = "The enemy Pokémons receive a permanent reduction in max. HP by 10%",
		limit = 1,
		desc = "The enemy Pokémons receive a permanent reduction in max. HP by 10%",
		buffColor = "effect",
		id = 1114,
		icon = "city/adventure/random_tower/icon/icon_js.png"
	},
	[1115] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80073,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 1000,
		desc_en = "When an allied Pokémon is defeated, it deals equal damage to the enemy that slays it",
		desc = "When an allied Pokémon is defeated, it deals equal damage to the enemy that slays it",
		buffColor = "effect",
		id = 1115,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[1116] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80074,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 9999,
		desc_en = "When an enemy is defeated, it deals 40% of the damage on the defeated enemy to nearby Pokémons",
		desc = "When an enemy is defeated, it deals 40% of the damage on the defeated enemy to nearby Pokémons",
		buffColor = "effect",
		id = 1116,
		icon = "city/adventure/random_tower/icon/icon_fs.png"
	},
	[1117] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80075,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Allied Pokémons get a 20% chance of stealing 50 rage level when attacking",
		desc = "Allied Pokémons get a 20% chance of stealing 50 rage level when attacking",
		buffColor = "effect_huang",
		id = 1117,
		icon = "city/adventure/random_tower/icon/icon_hn.png"
	},
	[1118] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80076,
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		group = 1000,
		desc_en = "Healing rate increases by 30% for allied Pokémons",
		desc = "Healing rate increases by 30% for allied Pokémons",
		buffColor = "effect_huang",
		id = 1118,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png"
	},
	[1119] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80077,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 9999,
		desc_en = "Allied Pokémons will remove all buff effect of the enemy after using the Ultimate Skill",
		desc = "Allied Pokémons will remove all buff effect of the enemy after using the Ultimate Skill",
		buffColor = "effect_huang",
		id = 1119,
		icon = "city/adventure/random_tower/icon/icon_yybm1.png"
	},
	[1120] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80078,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Ultimate damage of allied Pokémons increases by 30% in odd number rounds, but reduces by 15% in even number rounds",
		desc = "Ultimate damage of allied Pokémons increases by 30% in odd number rounds, but reduces by 15% in even number rounds",
		buffColor = "effect_huang",
		id = 1120,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[1121] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80079,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 9999,
		desc_en = "Deals a true damage of 20% ATK of the Pokémon with the highest ATK in the allied team to all enemy Pokémons at the end of the final round",
		desc = "Deals a true damage of 20% ATK of the Pokémon with the highest ATK in the allied team to all enemy Pokémons at the end of the final round",
		buffColor = "effect",
		id = 1121,
		icon = "city/adventure/random_tower/icon/icon_fs.png"
	},
	[1122] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80080,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 9999,
		desc_en = "When entering a battle, your team gain a shield that can absorb all damage taken by all the allied Pokémons, the amount of absorption is equal to the allied Pokémon with the highest HP",
		desc = "When entering a battle, your team gain a shield that can absorb all damage taken by all the allied Pokémons, the amount of absorption is equal to the allied Pokémon with the highest HP",
		buffColor = "effect_lan",
		id = 1122,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[1123] = {
		onlyOne = true,
		buffType = 4,
		belongLib = 6,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 200,
		desc_en = "Double the burning damage by allied Pokémons",
		passiveSkill = 80081,
		desc = "Double the burning damage by allied Pokémons",
		buffColor = "effect",
		id = 1123,
		icon = "city/adventure/random_tower/icon/icon_cxsh.png"
	},
	[1124] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80082,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 1000,
		desc_en = "Full rage value during the first round of the battle, but Ultimate Skill reduces 20% for 1 round",
		desc = "Full rage value during the first round of the battle, but Ultimate Skill reduces 20% for 1 round",
		buffColor = "effect_huang",
		id = 1124,
		icon = "city/adventure/random_tower/icon/icon_zh.png"
	},
	[2001] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 101,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2001,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2002] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 102,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2002,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2003] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 103,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2003,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2004] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 104,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2004,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2005] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 105,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2005,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2006] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 106,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2006,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2007] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 107,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2007,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2008] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 108,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2008,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2009] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 109,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2009,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2010] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 110,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2010,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2011] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 200,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2011,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2012] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 1111,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2012,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2013] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 1000,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2013,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2014] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 9999,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2014,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2015] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 999,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2015,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2221] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80083,
		group = 12221,
		desc_en = "【Fire Strength】: Each time the caster deals damage, reduces the enemy's SP.ATK and P.ATK by 8%, up to 10% of own SP.ATK and P.ATK (【Evil Strength】 further improves the effects)",
		desc = "【Fire Strength】: Each time the caster deals damage, reduces the enemy's SP.ATK and P.ATK by 8%, up to 10% of own SP.ATK and P.ATK (【Evil Strength】 further improves the effects)",
		buffColor = "effect",
		id = 2221,
		icon = "city/adventure/random_tower/icon/icon_cxsh.png"
	},
	[2222] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80084,
		group = 2221,
		desc_en = "【Water Strength】: Each time the caster deals damage, reduces the enemy's SP.DEF and P.DEF by 8%, up to 10% of own SP.DEF and P.DEF (【Evil Strength】 further improves the effects)",
		desc = "【Water Strength】: Each time the caster deals damage, reduces the enemy's SP.DEF and P.DEF by 8%, up to 10% of own SP.DEF and P.DEF (【Evil Strength】 further improves the effects)",
		buffColor = "effect",
		id = 2222,
		icon = "city/adventure/random_tower/icon/icon_gj.png"
	},
	[2223] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		buffType = 4,
		passiveSkill = 80085,
		group = 2221,
		desc_en = "【Evil Strength】: Enhance the effects of 【Fire Strength, Water Strength】: Each attack steals SP.ATK and P.ATK and SP.DEF and P.DEF from the target. If the caster has 【Evil Strength, Fire Strength and Water Strength】 at the same time, all allies gain 10% extra Leech HP",
		desc = "【Evil Strength】: Enhance the effects of 【Fire Strength, Water Strength】: Each attack steals SP.ATK and P.ATK and SP.DEF and P.DEF from the target. If the caster has 【Evil Strength, Fire Strength and Water Strength】 at the same time, all allies gain 10% extra Leech HP",
		buffColor = "effect_huang",
		id = 2223,
		icon = "city/adventure/random_tower/icon/icon_xx.png"
	},
	[2224] = {
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		buffType = 4,
		passiveSkill = 80086,
		group = 12222,
		desc_en = "【Sun Stone】: Restores 200 Rage before the move. (If the carrier has 【Sun & Moon Stone】, increases 30% Rage Regen)",
		desc = "【Sun Stone】: Restores 200 Rage before the move. (If the carrier has 【Sun & Moon Stone】, increases 30% Rage Regen)",
		buffColor = "effect_huang",
		id = 2224,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png"
	},
	[2225] = {
		iconBg = "city/adventure/random_tower/icon/box_green.png",
		buffType = 4,
		passiveSkill = 80087,
		group = 2222,
		desc_en = "【Moon Stone】: Restores 10% of lost HP at the end of each big round (If the carrier has 【Sun & Moon Stone】, increases 30% Rage Regen)",
		desc = "【Moon Stone】: Restores 10% of lost HP at the end of each big round (If the carrier has 【Sun & Moon Stone】, increases 30% Rage Regen)",
		buffColor = "effect_huang",
		id = 2225,
		icon = "city/adventure/random_tower/icon/icon_qhzl.png"
	},
	[2226] = {
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		buffType = 4,
		passiveSkill = 80088,
		group = 12223,
		desc_en = "【Anger】 At the start of the battle, gives all allies 100 Rage (For each 【Frustration, Rage Attack, Drain Rage, Irritate, Rage】 effect gained, increases 100 Rage)",
		desc = "【Anger】 At the start of the battle, gives all allies 100 Rage (For each 【Frustration, Rage Attack, Drain Rage, Irritate, Rage】 effect gained, increases 100 Rage)",
		buffColor = "effect_huang",
		id = 2226,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[2227] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80089,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2223,
		desc_en = "【Frustration】: When damaged, gains 100 Rage (Increases Rage for 【Fury】)",
		desc = "【Frustration】: When damaged, gains 100 Rage (Increases Rage for 【Fury】)",
		buffColor = "effect",
		id = 2227,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[2228] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80090,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2223,
		desc_en = "【Rage Attack】: When an ally Pokémon knocks out an enemy, restores 10% HP and 200 Rage (Increases Rage for 【Anger】)",
		desc = "【Rage Attack】: When an ally Pokémon knocks out an enemy, restores 10% HP and 200 Rage (Increases Rage for 【Anger】)",
		buffColor = "effect",
		id = 2228,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[2229] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80091,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2223,
		desc_en = "【Drain Rage】: Every ally Pokémon has a 30% chance to steal 100 Rage with each move (Increases Rage for 【Anger】)",
		desc = "【Drain Rage】: Every ally Pokémon has a 30% chance to steal 100 Rage with each move (Increases Rage for 【Anger】)",
		buffColor = "effect_huang",
		id = 2229,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[2230] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80092,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2223,
		desc_en = "【Irritate】: Using the small skill or basic attack grants 100 extra Rage (Increases Rage for 【Anger】)",
		desc = "【Irritate】: Using the small skill or basic attack grants 100 extra Rage (Increases Rage for 【Anger】)",
		buffColor = "effect_huang",
		id = 2230,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[2231] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80093,
		iconBg = "city/adventure/random_tower/icon/box_yellow.png",
		group = 2223,
		desc_en = "【Rage】: Using a move other than Ultimate increases DMG dealt by 1% for every 1% Rage used. (Increases Rage for 【Anger】)",
		desc = "【Rage】: Using a move other than Ultimate increases DMG dealt by 1% for every 1% Rage used. (Increases Rage for 【Anger】)",
		buffColor = "effect_huang",
		id = 2231,
		icon = "city/adventure/random_tower/icon/icon_nqhs.png"
	},
	[2232] = {
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		buffType = 4,
		passiveSkill = 80094,
		group = 12224,
		desc_en = "【Generate Shield】: At the start of the battle, grants a shield for all allies which absorbs damage equal to 10% of their HP (For every 【Shield Armor, Shield Immune, Shield Heal, Shield Attack, Shield Break, Shield Defense】 effect, Generate Shield gains 4% more points)",
		desc = "【Generate Shield】: At the start of the battle, grants a shield for all allies which absorbs damage equal to 10% of their HP (For every 【Shield Armor, Shield Immune, Shield Heal, Shield Attack, Shield Break, Shield Defense】 effect, Generate Shield gains 4% more points)",
		buffColor = "effect_huang",
		id = 2232,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2233] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80095,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2224,
		desc_en = "【Shield Armor】: Increases 20% SP.DEF and P.DEF when shielded (Increases shield points for 【Generate Shield】)",
		desc = "【Shield Armor】: Increases 20% SP.DEF and P.DEF when shielded (Increases shield points for 【Generate Shield】)",
		buffColor = "effect",
		id = 2233,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2234] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80096,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2224,
		desc_en = "【Shield Immune】: Becomes immune to control and negative effect when shielded (Increases shield points for 【Generate Shield】)",
		desc = "【Shield Immune】: Becomes immune to control and negative effect when shielded (Increases shield points for 【Generate Shield】)",
		buffColor = "effect",
		id = 2234,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2235] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80097,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2224,
		desc_en = "【Shield Attack】: Each attack inflicts extra True DMG equal to 20% of current shield points (Increases shield points for 【Generate Shield】)",
		desc = "【Shield Attack】: Each attack inflicts extra True DMG equal to 20% of current shield points (Increases shield points for 【Generate Shield】)",
		buffColor = "effect_huang",
		id = 2235,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2236] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80098,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2224,
		desc_en = "【Shield Defense】: Gains 10% of own Max HP as a shield for all allies for each taken critical attack (Increases shield points for 【Generate Shield】)",
		desc = "【Shield Defense】: Gains 10% of own Max HP as a shield for all allies for each taken critical attack (Increases shield points for 【Generate Shield】)",
		buffColor = "effect_huang",
		id = 2236,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2237] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80099,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2224,
		desc_en = "【Shield Break】: When the shield breaks, causes all enemies to lose 6% of max HP (Increases shield points for 【Generate Shield】)",
		desc = "【Shield Break】: When the shield breaks, causes all enemies to lose 6% of max HP (Increases shield points for 【Generate Shield】)",
		buffColor = "effect_huang",
		id = 2237,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2238] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80100,
		iconBg = "city/adventure/random_tower/icon/box_blue.png",
		group = 2224,
		desc_en = "【Shield Heal】: When the shield breaks, restores 5% of max HP (Increases shield points for 【Generate Shield】)",
		desc = "【Shield Heal】: When the shield breaks, restores 5% of max HP (Increases shield points for 【Generate Shield】)",
		buffColor = "effect_huang",
		id = 2238,
		icon = "city/adventure/random_tower/icon/icon_fy.png"
	},
	[2241] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80102,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2227,
		desc_en = "【Momentum】: Inflicts 30% extra DMG to the target with more than 70% HP (Owning 【Momentum】 and 【Autumn Wind】 at the same time increases extra 20% Crit Rate)",
		desc = "【Momentum】: Inflicts 30% extra DMG to the target with more than 70% HP (Owning 【Momentum】 and 【Autumn Wind】 at the same time increases extra 20% Crit Rate)",
		buffColor = "effect",
		id = 2241,
		icon = "city/adventure/random_tower/icon/icon_js.png"
	},
	[2242] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80103,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2227,
		desc_en = "【Autumn Wind】: Inflicts 40% extra DMG to target with less than 30% HP (Owning 【Momentum】 and 【Autumn Wind】 at the same time increases extra 20% Crit Rate)",
		desc = "【Autumn Wind】: Inflicts 40% extra DMG to target with less than 30% HP (Owning 【Momentum】 and 【Autumn Wind】 at the same time increases extra 20% Crit Rate)",
		buffColor = "effect",
		id = 2242,
		icon = "city/adventure/random_tower/icon/icon_fs.png"
	},
	[2243] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80104,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2228,
		desc_en = "【Bloody Attack】: Increases DMG Boost by 5% for every 1% Leech HP the Pokémon has (Owning 【Bloody Attack】 and 【Bat Wings】 at the same time steals 1% SP.DEF and P.DEF for every 1% Leech HP the Pokémon has)",
		desc = "【Bloody Attack】: Increases DMG Boost by 5% for every 1% Leech HP the Pokémon has (Owning 【Bloody Attack】 and 【Bat Wings】 at the same time steals 1% SP.DEF and P.DEF for every 1% Leech HP the Pokémon has)",
		buffColor = "effect_huang",
		id = 2243,
		icon = "city/adventure/random_tower/icon/icon_xx.png"
	},
	[2244] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80105,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2228,
		desc_en = "【Bat Wings】 Increases 5% Speed for every 1% Leech HP the Pokémon has (Owning 【Bloody Attack】 and 【Bat Wings】 at the same time steals 1% SP.DEF and P.DEF for every 1% Leech HP the Pokémon has)",
		desc = "【Bat Wings】 Increases 5% Speed for every 1% Leech HP the Pokémon has (Owning 【Bloody Attack】 and 【Bat Wings】 at the same time steals 1% SP.DEF and P.DEF for every 1% Leech HP the Pokémon has)",
		buffColor = "effect_huang",
		id = 2244,
		icon = "city/adventure/random_tower/icon/icon_xx.png"
	},
	[2245] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80106,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2231,
		desc_en = "【Toxic Corrosion】: Each attack has a 50% chance to apply Poison (Stacks up to 5 times. Owning 【Toxic Corrosion】, 【Blood Stained】 and 【Flash Fire】 at the same time increases 100% DoT for all allies)",
		desc = "【Toxic Corrosion】: Each attack has a 50% chance to apply Poison (Stacks up to 5 times. Owning 【Toxic Corrosion】, 【Blood Stained】 and 【Flash Fire】 at the same time increases 100% DoT for all allies)",
		buffColor = "effect_huang",
		id = 2245,
		icon = "city/adventure/random_tower/icon/icon_js1.png"
	},
	[2246] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80107,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2231,
		desc_en = "【Blood Stained】: Each attack has a 50% chance to apply Bleed (Stacks up to 5 times. Owning 【Toxic Corrosion】, 【Blood Stained】 and 【Flash Fire】 at the same time increases 100% DoT for all allies)",
		desc = "【Blood Stained】: Each attack has a 50% chance to apply Bleed (Stacks up to 5 times. Owning 【Toxic Corrosion】, 【Blood Stained】 and 【Flash Fire】 at the same time increases 100% DoT for all allies)",
		buffColor = "effect_huang",
		id = 2246,
		icon = "city/adventure/random_tower/icon/icon_js.png"
	},
	[2247] = {
		onlyOne = true,
		buffType = 4,
		passiveSkill = 80108,
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		group = 2231,
		desc_en = "【Flash Fire】: Each attack has a 50% chance to apply Burn (Stacks up to 5 times. Owning 【Toxic Corrosion】, 【Blood Stained】 and 【Flash Fire】 at the same time increases 100% DoT for all allies)",
		desc = "【Flash Fire】: Each attack has a 50% chance to apply Burn (Stacks up to 5 times. Owning 【Toxic Corrosion】, 【Blood Stained】 and 【Flash Fire】 at the same time increases 100% DoT for all allies)",
		buffColor = "effect_huang",
		id = 2247,
		icon = "city/adventure/random_tower/icon/icon_cxsh.png"
	},
	[2249] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 2221,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2249,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2250] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 2222,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2250,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2251] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 2223,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2251,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2252] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "5%",
		attrNum1 = "5%",
		attrType2 = 7,
		group = 2224,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +5%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +5%",
		buffColor = "effect",
		id = 2252,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2253] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 2227,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2253,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2254] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 2228,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2254,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	[2255] = {
		iconBg = "city/adventure/random_tower/icon/box_red.png",
		attrNum2 = "10%",
		attrNum1 = "10%",
		attrType2 = 7,
		group = 2231,
		desc_en = "P. ATK and SP.ATK of allied Pokémons +10%",
		attrType1 = 8,
		desc = "P. ATK and SP.ATK of allied Pokémons +10%",
		buffColor = "effect",
		id = 2255,
		icon = "city/adventure/random_tower/icon/icon_gj.png",
		weight = 1
	},
	__default = {
		__index = {
			attrNum1 = "",
			buffType = 1,
			supplyType = 0,
			attrNum3 = "",
			effectTimes = 0,
			attrType1 = 0,
			pointType = 0,
			desc = "",
			passiveSkill = 0,
			attrType3 = 0,
			supplyNum = 0,
			supplyTarget = 0,
			icon = "",
			pointValue = 0,
			limit = 99,
			onlyOne = false,
			attrNum2 = "",
			attrNatureType3 = 0,
			changeLib = 0,
			group = 1,
			desc_en = "",
			attrNatureType1 = 0,
			attrType2 = 0,
			belongLib = 0,
			condition = 0,
			buffColor = "",
			iconBg = "",
			weight = 999,
			skillgroup = {}
		}
	}
}

return csv.random_tower.buffs
